### ISSUE TITLE
yandex: 400 Bad Request

### ISSUE THREAD

**Issue by choin1** [rclone/rclone#7044] opened 2023-06-06 13:39 UTC
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/yandex-disk-400-bad-request/38569

#### What is the problem you are having with rclone?

Big files fail to be uploaded on Yandex cloud.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.62.2
    os/version: Microsoft Windows 8.1 Enterprise (64 bit)
    os/kernel: 6.3.9600.20721 Build 9600.20721.20721 (x86_64)
    os/type: windows
    os/arch: amd64
    go/version: go1.20.2
    go/linking: static
    go/tags: cmount
```

Please see the forum thread for details. Basically, uploading a file bigger than 5-6 GB break before completion, and an odd detail is that `chunker` does not help at all (all uploaded chunks get deleted after the error occurs). Even if there is an internal issue with my connection or environment, my understanding is that `chunker` should not fail in this way.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2023-06-07 16:16
From your forum post this seems to be the root error

    https://uploader47o.disk.yandex.net:443/upload-target/*": write tcp *:12455->*:443: wsasend: An existing connection was forcibly closed by the remote host.)

This means that the remote yandex computer, or a firewall or proxy between you and it closed the connection.

After that the retries get

    400 Bad Request

errors. I'm not sure where this is coming from - this may be a bug in rclone.

Can you do a copy of a file with a debug log please and attach the log here please? Or if you don't want to do that email it to me nick@craig-wood.com and put a link to this issue so I have some context.

So do something like

    rclone copy -vv --dump responses 5Gfile test: --log-file rclone.log

Its much easier to see what is going on with `rclone copy` instead of `rclone mount`.

I think the root problem is either Yandex or your provider/proxy/firewall but rclone should retry properly and it isn't.

**Comment by choin1** [comment] 2023-06-08 00:39
I will try that command and provide the log files soon.

But just in case:
I don't use a proxy or a firewall. My provider is using cgnat but I'm not experiencing interrupts in large transfers.
Transferring the same big file through a web browser works fine.
I specifically said that there must be some internal issue that prevents `chunker` from being a workaround, even if I do have some issues on my end. It just fails somewhere at the same place and rclone acts like it never transferred any chunks until that point.

**Comment by choin1** [comment] 2023-06-08 03:35
Log file sent.

**Comment by ncw** [comment] 2023-06-09 17:08
Thanks for the log file.

I can see a problem here - the retry is being done at the wrong level.

Please give this a go which should stop the "400 Bad Request" errors by doing a proper retry.

If it doesn't work, please send another log - thank you.

[v1.63.0-beta.7056.1e0f26cf9.fix-7044-yandex-bad-request](https://beta.rclone.org/branch/fix-7044-yandex-bad-request/v1.63.0-beta.7056.1e0f26cf9.fix-7044-yandex-bad-request/) on branch [fix-7044-yandex-bad-request](https://github.com/rclone/rclone/tree/fix-7044-yandex-bad-request) (uploaded in 15-30 mins)

**Comment by choin1** [comment] 2023-06-10 03:10
Thanks.

I don't think it fixed anything though. Can you clarify if this was supposed to fix something related to `chunker` or not? Because I'm not including it in a command for now, only doing direct cloud transfer.

New log file sent.

**Comment by ncw** [comment] 2023-06-10 14:29
Gah, I made a really silly mistake.

Can you try this instead please?

[v1.63.0-beta.7056.5d82e90ff.fix-7044-yandex-bad-request](https://beta.rclone.org/branch/fix-7044-yandex-bad-request/v1.63.0-beta.7056.5d82e90ff.fix-7044-yandex-bad-request/) on branch [fix-7044-yandex-bad-request](https://github.com/rclone/rclone/tree/fix-7044-yandex-bad-request) (uploaded in 15-30 mins)

**Comment by choin1** [comment] 2023-06-11 03:09
New log file sent.

I'm seeing that many more attempts are being made now, and the transfer even goes to 100%, but another error happens:
`Failed to copy: Put "https://uploader38j.disk.yandex.net:443/upload-target/***": write tcp ***:5811->***:443: wsasend: An existing connection was forcibly closed by the remote host.`

**Comment by choin1** [comment] 2023-06-11 06:06
Should I open a new issue regarding broken `chunker` behavior (as described above) or is it considered normal?

**Comment by ncw** [comment] 2023-06-11 10:34
Thanks for the log. I can see the retries are working properly now which is good.

I've merged this fix to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.63

I was hoping that this error would be cleared up by a retry, but it looks like there is a systematic problem causing these errrors:

> Error: write tcp 192.168.0.100:5558->141.8.157.126:443: wsasend: An existing connection was forcibly closed by the remote host.

What that error means is this rclone received a TCP RST packet to close the connection. This may have been sent by yandex, or it may have been sent by something between you and yandex like your ISP, router, firewall or proxy.

I calculated how long the time was from the start of the http request and the error for each event in your logs with a python program and this is the answer in seconds

> 403, 609, 596, 602, 602, 602, 602, 602, 602, 602, 602, 602, 602, 601, 601, 601, 601, 601, 601, 389, 206, 601, 601, 601, 601, 601, 601, 601, 601, 601

So it looks like there is a timeout on your connection of about 10 minutes (600 seconds). Sometimes this kicks in a bit earlier.

Can you try uploading a large file from a cloud VM or a different location to see if we can work out whether it is your ISP or Yandex doing this?

I tried uploading a file of the same size 6.086Gi from my test VM (which gets about 30MiB/s to Yandex) and it worked but I got "507 Insufficient Storage" which is because I only have a free account I guess.

> Should I open a new issue regarding broken `chunker` behavior (as described above) or is it considered normal?

Probably best to open a new issue with a full description and a log of the problem

**Comment by choin1** [comment] 2023-06-11 15:07
Tried with another location and it seems working. However this is still confusing.

- It didn't really work on a first attempt even though the speed was much better. After 100% transfer the error was `Received error: Put "https://uploader77j.disk.yandex.net:443/upload-target/***": net/http: timeout awaiting response headers - low level retry`
- There is always a relatively long delay (1 minute or so) between the transfer and any response, whether there is a error or not.
- Like already mentioned, using a browser works in the original environment.

**Comment by ncw** [comment] 2023-06-11 17:41
You can set the timeout with --conntimeout (I think not at computer) that will fix the timeout error

The fact it always works in the browser probably isn't relevant as most providers have a private API for their website which is different to the ones rclone is using.

**Comment by animosity22** [comment] 2023-07-20 02:36
Anything else here? The timeout would be it as not sure what else can be done.

**Comment by choin1** [comment] 2023-08-05 04:02
> What happens if you do a `HEAD` request

I'm unable to code such a behavior and don't have enough time to learn how to.

Here is a log with 1.63.1. This time 35 GB was wasted during a 6 GB transfer.

`rclone copy -vv --dump responses --contimeout 30m "E:\\folder\\6Gfile" chunker-test:temp --log-file rclone.log --disable-http-keep-alives`

[rclone-chunker2.log](https://github.com/rclone/rclone/files/12266027/rclone-chunker2.log)

I'll try to use an official desktop app as a mounting point as it shouldn't have such issues.

**Comment by devnoname120** [comment] 2023-08-05 13:22
Looks like the timeout issue at the end of a transfer is a known Yandex issue. See: https://github.com/ivknv/yadisk/issues/25#issuecomment-1380592291

-------------------

I tried uploading a 5GB file and here is the log:

```shell
❯ rclone -vvv copy '/Users/paul/Downloads/5GB.bin' yandex:
2023/08/05 14:08:06 DEBUG : Setting --transfers "8" from environment variable RCLONE_TRANSFERS="8"
2023/08/05 14:08:06 DEBUG : Setting --progress "true" from environment variable RCLONE_PROGRESS="true"
2023/08/05 14:08:06 DEBUG : rclone: Version "v1.63.1" starting with parameters ["rclone" "-vvv" "copy" "/Users/paul/Downloads/5GB.bin" "yandex:"]
2023/08/05 14:08:06 DEBUG : Creating backend with remote "/Users/paul/Downloads/5GB.bin"
2023/08/05 14:08:06 DEBUG : Using config file from "/Users/paul/.config/rclone/rclone.conf"
2023/08/05 14:08:06 DEBUG : fs cache: adding new entry for parent of "/Users/paul/Downloads/5GB.bin", "/Users/paul/Downloads"
2023/08/05 14:08:06 DEBUG : Creating backend with remote "yandex:"
2023-08-05 14:08:07 DEBUG : 5GB.bin: Need to transfer - File not found at Destination
2023-08-05 14:15:37 DEBUG : pacer: low level retry 1/1 (error Put "https://uploader22g.disk.yandex.net:443/upload-target/[ISO 8601].utd.[UNIQUE ID]-k22g.[TIMESTAMP]": net/http: timeout awaiting response headers)
2023-08-05 14:15:37 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2023-08-05 14:15:37 DEBUG : 5GB.bin: Received error: Put "https://uploader22g.disk.yandex.net:443/upload-target/[ISO 8601].utd.[UNIQUE ID]-k22g.[TIMESTAMP]": net/http: timeout awaiting response headers - low le
vel retry 1/10
2023-08-05 14:15:37 DEBUG : pacer: Reducing sleep to 15ms
Transferred:   	    4.801 GiB / 8.941 GiB, 54%, 14.887 MiB/s, ETA 4m44s
Transferred:            0 / 1, 0%
Elapsed time:      7m41.8s
Transferring:
 *                                       5GB.bin:  7% /4.470Gi, 30.092Mi/s, 2m20s^C
```

When rclone retried the transfer I pressed<kbd>ctrl</kbd><kbd>c</kbd>. After a few minutes I checked my Yandex Disk and I saw that the file was there. I'm not sure it whether it appeared immediately or not as I didn't check immediately. I then ran the following commands which gave me confirmation that the file was not corrupted during the transfer:

```shell
/var/folders/ws/tmp/T/tmp.sbcSN504 ───────────────────── ✘ INT|INT 1m 42s 02:49:08 PM
❯ rclone hashsum sha256 --download 'yandex:5GB.bin'
e42c9cc85fbf054f8673135578c6208ffee5a627be4b50039485b99ea3c71670  5GB.bin
Transferred:   	    4.470 GiB / 4.470 GiB, 100%, 31.232 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:      2m28.0s

/var/folders/ws/tmp/T/tmp.sbcSN504 ─────────────────────────────── 2m 28s 02:52:22 PM
❯ sha256sum ~/Downloads/5GB.bin
e42c9cc85fbf054f8673135578c6208ffee5a627be4b50039485b99ea3c71670  /Users/paul/Downloads/5GB.bin
```

Interestingly, the `GET /v1/disk/resources?limit=1000&path=disk%3A%2F HTTP/1.1` request returns the following JSON object for the file `5GB.bin`:

```json
{
  "antivirus_status":"not-scanned",
  "size":4800000000,
  "comment_ids":{
    "private_resource":"[RESOURCE ID]:[LONG HASH STRING]",
    "public_resource":"[RESOURCE ID]:[LONG HASH STRING]"
  },
  "name":"5GB.bin",
  "exif":{
    
  },
  "created":"2023-08-05T12:16:00+00:00",
  "custom_properties":{
    "rclone_modified":"2023-08-05T14:07:38.320212282+02:00"
  },
  "resource_id":"[RESOURCE ID]:[LONG HASH STRING]",
  "modified":"2023-08-05T12:49:14+00:00",
  "mime_type":"application/octet-stream",
  "file":"https://downloader.disk.yandex.ru/disk/[…]&filename=5GB.bin&disposition=attachment&hash=&limit=0&content_type=application%2Foctet-stream&[…]",
  "path":"disk:/5GB.bin",
  "media_type":"encoded",
  "sha256":"e42c9cc85fbf054f8673135578c6208ffee5a627be4b50039485b99ea3c71670",
  "type":"file",
  "md5":"cd3fb3487755469821346d425e0f0c7c",
  "revision":1691239754850309
}
```

Interestingly in the JSON object above the `antivirus_status` property is set to `not-scanned`. I tried uploading a 48MB file named `48MB.bin` and on that one the property is set to `clean` instead of `antivirus_status`. The connection didn't time out this time around.

Why is the `antivirus_status` property of the 5GB file set to `not-scanned`? Is it because the upload request timed out? Is it because the scan is still running? Is the file just too big?

A workaround may be to let rclone wait for the connection to time out, and then check the properties of the uploaded file until it looks good? Maybe even cut the connection on our side after 10s if we already sent 100% of the bytes of the file? Note that I can't test on bigger files because I'm on the free plan thus my limit is only 5GB.

-----------

@choin1 @animosity22 What's the file type/extension that you're trying to transfer? Yandex Disk puts different restrictions on the upload depending on the file type (yes I know it's stupid because you can just rename it immediately after the transfer).

-----------

@ncw I can confirm that the web uploader uses a private API.

-----------

If any of you @choin1 or @animosity22 can give me access to their paid account I can try to investigate the chunking issues you're having.

**Comment by choin1** [comment] 2023-08-05 14:32
> Looks like the timeout issue at the end of a transfer is a known Yandex issue. See: [ivknv/yadisk#25 (comment)](https://github.com/ivknv/yadisk/issues/25#issuecomment-1380592291)

As you can see I used `--contimeout 30m` and it still fails within the first few minutes with the "timeout" thing.

> @choin1 @animosity22 What's the file type/extension that you're trying to transfer? Yandex Disk puts different restrictions on the upload depending on the file type (yes I know it's stupid because you can just rename it immediately after the transfer).

You can see all filenames in my log. The main file is without extension, and its chunks are .001, .002 and so on.

> If any of you @choin1 or @animosity22 can give me access to their paid account I can try to investigate the chunking issues you're having.

Note:
- I have the same issue with smaller files, e.g. 1 GB, 2 GB etc. but the problem is more frequent on bigger files.
- It's not "chunking issues". Whatever the chunk size I set, it can quickly upload many chunks but somewhere between 50% and 95% (usually) of the main file size upload, it breaks. I only resorted to `chunker` in order to try and make the file upload size regular, and to ignore any additional nuances bigger file upload process may have had. But in the end the `chunker` never acted properly. #7052

**Comment by devnoname120** [comment] 2023-08-06 10:01
> Unrelated, but the timeout of upload links is [30 minutes](https://yandex.com/dev/disk/api/reference/upload.html#response-upload) according to Yandex's documentation. Their documentation may just not be up-to-date and it may have been changed to 10 minutes since they wrote it. This would explain what @ncw is observing with the numerous 601-second timeouts.

See above.

> You can see all filenames in my log.

I had no reason to believe that you didn't mess with that when you censored your log file.

----------------

What Yandex plan are you on?

**Comment by choin1** [comment] 2023-08-07 05:11
> > Unrelated, but the timeout of upload links is [30 minutes](https://yandex.com/dev/disk/api/reference/upload.html#response-upload) according to Yandex's documentation. Their documentation may just not be up-to-date and it may have been changed to 10 minutes since they wrote it. This would explain what @ncw is observing with the numerous 601-second timeouts.
> 
> See above.

I'm not getting it. There must be several processes at place bound by different timeouts then, and I can't understand what to make of that, e.g. what I can change to make it fail less often. Will test with the .txt extension when I can.

> > You can see all filenames in my log.
> 
> I had no reason to believe that you didn't mess with that when you censored your log file.

I only censored the username. I'm sorry if that made anyone feel like I tampered with it so much that it affects their ability to debug the issue.

> What Yandex plan are you on?

A paid 2 TB plan. I don't think this is useful as their plans are a mess and their availability change in time from what I remember.

**Comment by buengese** [comment] 2024-08-30 00:47
I think the recent user agent changes should help with this.

**Closed by buengese** 2024-08-30 00:47 UTC
Labels: Remote: Yandex Disk, waiting for reply...
