### ISSUE TITLE
https://beta.rclone.org/version.txt invalid file

### ISSUE THREAD

**Issue by hotio** [rclone/rclone#4602] opened 2020-09-16 07:55 UTC
The version.txt file no longer contains the latest version/build number, but some random unknown stuff that shouldn't be there.
![image](https://user-images.githubusercontent.com/26902309/93308556-b6e05680-f802-11ea-9a2f-21c8672e4dc1.png)

**Comment by kiwibrowser** [comment] 2020-09-16 22:25
Confirmed, it is not possible to install rclone beta due to invalid version.txt:

```
Run curl https://rclone.org/install.sh | sudo bash -s beta
8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
9
                                 Dload  Upload   Total   Spent    Left  Speed
10

11
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
12
100  4436  100  4436    0     0   8979      0 --:--:-- --:--:-- --:--:--  8979
13
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
14
                                 Dload  Upload   Total   Spent    Left  Speed
15

16
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
17
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
18
100    35  100    35    0     0     93      0 --:--:-- --:--:-- --:--:--    92
19
bash: line 57: warning: command substitution: ignored null byte in input
20

21
The latest beta version of rclone  is already installed.
22

```

**Comment by ncw** [comment] 2020-09-18 09:31
Thanks for pointing this out.

I've fixed this now.

beta.rclone.org is run from a mount with `--vfs-cache-mode full` on object storage.

This problem was caused an old cron entry which was deleting the version.txt file out of the VFS cache, which is now a bad thing to do!

However this same problem came up here

https://forum.rclone.org/t/corrupted-data-streaming-after-vfs-meta-files-removed/18997

And I've pushed the fix for that now too.

**Closed** 2020-09-18 09:30 UTC
Labels: bug, build
