### ISSUE TITLE
b2: Failed to set modification time: Copy source too big - need multipart copy

### ISSUE THREAD

**Issue by dsampson01** [rclone/rclone#3991] opened 2020-02-22 01:06 UTC
#### What is the problem you are having with rclone?
Am trying to set modification time on tow large files in our BackBlaze B2 bucket and it errors out. This is similar to a post I filed on the rclone support forum last fall (https://forum.rclone.org/t/failed-to-set-modification-time-copy-source-too-big-backblaze/12416). At that time, I was told to use a beta version and to use the clunker mode in my configuration file. It appeared to have fixed that. However, it returned just this month.

#### What is your rclone version (output from `rclone version`)
root@rclone:~ # /usr/local/bin/rclone version
rclone v1.51.0
- os/arch: freebsd/amd64
- go version: go1.13.7
root@rclone:~ # 

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeNAS 11.3-RELEASE-p6

####  Which cloud storage system are you using? (eg Google Drive)

BackBlaze B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
 I run a script as follows:

#!/bin/sh

src=/mnt/storage
dest=b2-backup:DawnSign-0001
fold=FreeNAS
email=admin@example.com
log_level=INFO
log_time=`date "+%Y%m%d_%H:%M"`
log_path=/var/log
log_file=${log_path}/rclone-${log_time}.log
min_age=15m
b2_chunk_size=48M
transfers=20

#/usr/local/bin/rclone sync \
/usr/bin/rclone sync \
    --copy-links \
    --fast-list \
    --exclude .DS_Store \
    --exclude-if-present .ignore \
    --min-age ${min_age} \
    --b2-chunk-size ${b2_chunk_size} \
    --transfers ${transfers} \
    --log-level ${log_level} \
    --log-file ${log_file} \
     ${src} ${dest}/${fold} $@
rc=$?

if [ $rc != 0 ]; then
    touch /root/bin/B2-error-${log_time}.txt
    cat /root/bin/B2-error.txt > /root/bin/B2-error-${log_time}.txt
    cat ${log_file} >> /root/bin/B2-error-${log_time}.txt 
    cat /root/bin/B2-error-${log_time}.txt | /usr/local/bin/mini_sendmail -fadmin@example.com -smail.example.com ${email}

else
    touch /root/bin/B2-success-${log_time}.txt
    cat /root/bin/B2-success.txt > /root/bin/B2-success-${log_time}.txt
    cat ${log_file} >> /root/bin/B2-success-${log_time}.txt 
    cat /root/bin/B2-success-${log_time}.txt | /usr/local/bin/mini_sendmail -fadmin@example.com -smail.example.com ${email}
fi

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Here's a snippet of the error log:

2020/02/21 16:54:09 INFO  : 
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:            632429 / 640943, 99%
Transferred:            0 / 0, -
Elapsed time:      18m16s
Checking:
 * Signing Naturally/SN 2â€¦l 2 Student Part 2.mov: checking
 * Signing Naturally/SN Lâ€¦l_1_Student_011119.mov: checking

2020/02/21 16:54:55 ERROR : Signing Naturally/SN Level 1/MOV/Signing_Naturally_Level_1_Student_011119.mov: Failed to set modification time: Copy source too big: 38922974256 (400 bad_request)
2020/02/21 16:55:02 ERROR : Signing Naturally/SN 2 & 3/SN 2/Signing Naturally Level 2 Student Part 2.mov: Failed to set modification time: Copy source too big: 40300155482 (400 bad_request)
2020/02/21 16:55:09 INFO  : 
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 2 (retrying may help)
Checks:            661355 / 661355, 100%
Transferred:            0 / 0, -
Elapsed time:     19m9.5s

2020/02/21 16:55:30 INFO  : B2 bucket DawnSign-0001 path FreeNAS: Waiting for checks to finish
2020/02/21 16:55:30 INFO  : B2 bucket DawnSign-0001 path FreeNAS: Waiting for transfers to finish
2020/02/21 16:55:30 ERROR : B2 bucket DawnSign-0001 path FreeNAS: not deleting files as there were IO errors
2020/02/21 16:55:30 ERROR : B2 bucket DawnSign-0001 path FreeNAS: not deleting directories as there were IO errors
2020/02/21 16:55:30 ERROR : Attempt 3/3 failed with 3 errors and: not deleting files as there were IO errors
2020/02/21 16:55:30 Failed to sync with 3 errors: last error was: not deleting files as there were IO errors

**Comment by ncw** [comment] 2020-02-22 10:47
I think I see the problem here...

Rclone uses the [b2 copy file API](https://www.backblaze.com/b2/docs/b2_copy_file.html) to set the modification time (you can't change existing files on B2 even to set the modification time, you have to copy them).

That says

> Note that the resulting file must be less than 5GB. If you wish to create a file larger than 5GB, you must do it in parts with b2_copy_part.

So it looks like rclone should be using a different method for copying large files.

This is a reasonable amount of work unfortunately but we can follow a similar pattern as used in the s3 and swift backends.

Would you like to help with this?

**Comment by dsampson01** [comment] 2020-02-22 18:52
Yes, of course! Tell me what I need to do.

~Doug
--
Doug Sampson
dsampson01 at gmail dot com

**Comment by ncw** [comment] 2020-02-24 14:40
> Yes, of course! Tell me what I need to do.

I had a quick look at this. The [mulipart copy](https://www.backblaze.com/b2/docs/large_files.html) is quite complicated, probably the best thing to do would be to parameterize the [multipart upload routine](https://github.com/rclone/rclone/blob/master/backend/b2/upload.go) so it can call [b2_copy_part](https://www.backblaze.com/b2/docs/b2_copy_part.html) instead of `b2_upload_part`.

Then it is a question of factoring out the existing copy_file and calling the multipart copy if the size is >= 5GB (that is 5,000,000,000 - all the b2 docs use SI units).

I did the factoring out in 819bfe6211481ee10fccbf0ca67b0dca2358c1cd in the fix-3991-b2-modtime - I haven't got time to do the multipart copy stuff at the moment - can you help here?

**Comment by dsampson01** [comment] 2020-02-24 19:58
I didn't realize what I was getting into when I said "yes". This is way
over my head.

Over the past weekend, I deleted the two files in our B2 cloud account and
reran the script. The uploads completed successfully. The subsequent runs
have not produced any error messages. I'm not sure what to make of this but
I am reasonably happy at the moment.

~Doug
--
Doug Sampson
dsampson01 at gmail dot com

**Comment by ncw** [comment] 2020-02-25 15:23
> I didn't realize what I was getting into when I said "yes". This is way
over my head.

No worries! We'll get round to this eventually I'm sure!

> Over the past weekend, I deleted the two files in our B2 cloud account and reran the script. The uploads completed successfully. The subsequent runs have not produced any error messages. I'm not sure what to make of this but I am reasonably happy at the moment.

It is setting the modification time of an existing file that is the problem, so I'd expect deleting the files and re-uploading them to work fine.

**Comment by premeau** [comment] 2020-02-28 15:01
Is there any way to tell rclone not to use the B2 copy api and to re-upload the files instead?

**Comment by ncw** [comment] 2020-03-01 10:00
> Is there any way to tell rclone not to use the B2 copy api and to re-upload the files instead?

Which command are you using @premeau ? If you want to disable server side copies then you can use `--disable Copy` - however I don't think that will disable the setting of the modification times using server side copy - that needs the b2 backend to return a special error when the modification time is set. This is possible to do with a flag I guess...

**Comment by premeau** [comment] 2020-03-03 18:43
I am using sync .. and conducting a simple test, I have confirmed that `--disable Copy` is not tested during the modification time process.

Rather than continuing the discussion here, I'll open a separate issue and describe my situation and concerns.

**Comment by ncw** [comment] 2020-03-03 19:39
@premeau I think you are experiencing the same issue most likely.

**Comment by Hescominsoon** [comment] 2020-04-18 18:28
There is a 5 gig limit on b2 copy operations: 
https://www.backblaze.com/b2/docs/b2_copy_part.html

**Comment by Hescominsoon** [comment] 2020-04-18 19:05
https://jira.ixsystems.com/browse/NAS-105156

**Comment by ncw** [comment] 2020-04-19 11:01
Does anyone want to work on this issue? See https://github.com/rclone/rclone/issues/3991#issuecomment-590352732 for hints on what needs to be done :-)

**Comment by Hescominsoon** [comment] 2020-04-19 15:15
With freenas 11.3x rclone wont' even start the uploads.  I do have at least 50 5GB+ files which explains why this now fails.  Did Backblaze change something or did rclone change something?

**Comment by ncw** [comment] 2020-04-23 20:22
@Hescominsoon rclone should be able to upload files bigger than 5 GB fine, it is server side copying them which includes setting the modification time which is the problem.

**Comment by dlithio** [comment] 2020-05-05 01:12
[B2 just got an S3 compatible API](https://www.backblaze.com/blog/backblaze-b2-s3-compatible-api/). It’s still in beta, but would waiting for that to leave beta make this easier?

**Comment by ncw** [comment] 2020-05-05 11:02
I just gave the B2 S3 compatible api a go - it works very well! You could use it to store data with rclone, however note that the method that rclone uses to store the modification time is different between the two so you can't swap between the methods.

**Comment by ncw** [comment] 2020-05-29 11:45
I've had a go at fixing this here. This adds a new flag `--b2-copy-cutoff` - above this limit files will be server side copies in `--b2-copy-cutoff` sized chunks. I set this quite conservatively to 4G but it might be quicker to set it lower. In my testing with copying 1GB ish files setting it to 100M made it quicker... So some experimentation with this value would be useful!

I've also reworked the multipart transfer code - I think it is all working, but please report bugs!

https://beta.rclone.org/branch/v1.52.0-004-g257a890f-fix-3991-b2-copy-beta/ (uploaded in 15-30 mins)

**Comment by benz2012** [comment] 2020-06-03 15:54
I am seeing successful tests of manual server side copy using `rclone copy`, however I am still seeing failures when running local to backblaze sync, with a modified timestamp using `rclone sync`.

`/Users/redacted/Downloads/rclone-v1.52.0-004-g257a890f-fix-3991-b2-copy-beta-osx-amd64/rclone sync /var/folders/mf/_km9zfhx7l521mc873t4bkd80000gn/T/oxbk.iso backblaze:redacted-ben/ox2019bk/oxbk.iso --progress --retries 1`

> Failed to set modification time: Copy source too big

[logfile](https://github.com/rclone/rclone/files/4724520/benlog.txt)

**Comment by ncw** [comment] 2020-06-04 11:59
Ah I completely forgot about setting the modification time....

Can you try this please? I think I've covered all the cases here.

https://beta.rclone.org/branch/v1.52.0-023-g399e8c0b-fix-3991-b2-copy-beta/ (uploaded in 15-30 mins)

Thanks

**Comment by benz2012** [comment] 2020-06-04 21:34
Working successfully!

**Comment by ncw** [comment] 2020-06-05 12:29
Thank you for testing

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

I may put it in a v1.52.x release later but it needs some more user testing first as it is quite a big change.

**Closed** 2020-06-05 12:28 UTC
Labels: Remote: Backblaze B2, bug

**Comment by BruceHowells** [comment] 2020-06-27 16:51
For what it may be worth to FreeNAS users, I replaced /usr/local/bin/rclone with the rclone v1.52.0-023-g399e8c0b-fix-3991-b2-copy-beta and successfully had a b2 sync complete which previously had hung up on the Copy source too big for modification time update issue.

**Comment by ncw** [comment] 2020-06-29 20:14
Thanks for testing @BruceHowells
