### ISSUE TITLE
[Feature Request] rclone copy Multiple files

### ISSUE THREAD

**Issue by Massaguana** [rclone/rclone#1426] opened 2017-05-20 13:30 UTC
Hello,

i wood like to make an Feature Request to use the command "copy" to copy multiple files lile this:

rclone copy Filename.S01E*.mkv Remote:

Is it possible to do something like that?

Regards
Massaguana

**Comment by niranjanshr13** [comment] 2017-05-20 14:22
@Massaguana I have always wonder that, but in Linux you can do :

> for loop in $(ls Filename.S01E*.mkv)
> do
> rclone copy $loop Remote:
> done

**Comment by Massaguana** [comment] 2017-05-20 15:52
Sorry, but i don´t understand what i must do...

**Comment by niranjanshr13** [comment] 2017-05-20 16:13
@Massaguana well the script will loop through all the matching and upload to the remote; which OS are you running.

**Comment by Massaguana** [comment] 2017-05-20 16:15
i use CentOS 7 64-Bit...

i don´t like to write scripts, i think only use * are mutch easyer

**Comment by left1000** [comment] 2017-05-20 20:22
you can make an rclone filter file that will do that for you:
https://rclone.org/filtering/

**Comment by ncw** [comment] 2017-05-24 09:19
If you do

    rclone copy . --include "Filename.S01E*.mkv" Remote:

that should have the same effect.

Not quite as convenient, I agree but it should work.

**Comment by Massaguana** [comment] 2017-05-24 09:21
i test it. but in Moment i copy alle files to an new directory and rclone this directory... thats also work for me

**Comment by ncw** [comment] 2018-11-29 10:50
@sheerun 
> That's also my use case, I need to perform very specific 70000 copies defined in file where glob won't work. Running rclone copyto for every file is very slow

You could run an rclone server with `rclone rcd` then use the rc command to use the [operations/copyto command](https://rclone.org/rc/#operations-copyfile-copy-a-file-from-source-remote-to-destination-remote)

Also if someone wanted to have a go at multiple files for rclone copy it probably wouldn't be too hard?

**Comment by zuzzurro** [comment] 2018-12-05 22:42
I would suggest to conflate this request and the other one to have copy and sync behave the unix way in respect to directories (#1228) and create a more unixy cp command.
I understand that the current behavior may be easier for people not coming from unix, but the rest of would keep the finger intelligence collected in so many years and ingrained in so many tools also in the rclone world..

**Comment by ivandeex** [comment] 2020-11-16 01:02
Currently rclone treats metacharacters (`*?`) in source file name as part of the name, while in spurce filter arguments (`--include --exclude`) they are treated as _globs_. Changing this behavior will break existing scripts. The only solution I can see is a new flag like `--source-is-filter`. Marking this as a breaking change.

**Comment by ivandeex** [comment] 2020-11-16 01:15
Duplicate of https://github.com/rclone/rclone/issues/4308

**Comment by ivandeex** [comment] 2020-11-16 17:33
Duplicate of https://github.com/rclone/rclone/issues/4777

**Comment by ivandeex** [comment] 2020-11-16 17:34
@ncw
I suggest closing this in favor of https://github.com/rclone/rclone/issues/4777

**Comment by ivandeex** [comment] 2021-02-10 20:10
Closed this stale ticket in favor of #4777

**Closed by ivandeex** 2021-02-10 20:10 UTC
Labels: UX, duplicate, enhancement, filtering, help wanted, question, thinking
