### ISSUE TITLE
rclone genautocomplete has problems with Bash

### ISSUE THREAD

**Issue by marco-brandizi** [rclone/rclone#3489] opened 2019-08-27 13:56 UTC
#### What is the problem you are having with rclone?

The file spawned by [`rclone genautocomplete`](https://rclone.org/commands/rclone_genautocomplete_bash/) generates this error when I login as root:

```
10:20:15 [brandizi@brandizmac ~]$ su - root
Password:
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: syntax error near unexpected token `<'
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: `            done < <(command rclone listremotes)'
10:20:18 [root@brandizmac ~]#
```
And rclone autocompletion fails to work after this (unsurprisingly).

This only happens when I login as root, all other users are fine. 

#### What is your rclone version (output from `rclone version`)

```bash
14:47:13 [root@brandizmac ~]# rclone -V
rclone v1.48.0
- os/arch: darwin/amd64
- go version: go1.12.6
```

I have rclone installed via [Homebrew](https://brew.sh/). Initially [I filed this same issue to them](https://github.com/Homebrew/homebrew-core/issues/43506), cause I believed they are the ones adding Bash autocompletion.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

```bash
14:52:44 [root@brandizmac ~]# sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
14:53:24 [root@brandizmac ~]#
```

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive, but not relevant hereby.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

See above.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

See above.

**Comment by ncw** [comment] 2019-08-28 13:22
Are you using the same version of bash as root as you are as a user?  Can you try this as root and a user?

```
$  echo "${BASH_VERSION}"
5.0.3(1)-release
```

That code comes from here BTW if we need to patch it.

https://github.com/rclone/rclone/blob/693112d57e0aaece5f6ec46100bedb818794dcef/cmd/help.go#L53

Cc: @sgtpep for a second opinion

**Comment by marco-brandizi** [comment] 2019-08-29 12:16
Hi @ncw, I forgot to report this, but yes, it's the same bash:

```bash
13:14:44 [brandizi@brandizmac ~]$ which bash
/bin/bash
13:14:54 [brandizi@brandizmac ~]$ bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
13:14:58 [brandizi@brandizmac ~]$
13:15:25 [brandizi@brandizmac ~]$ su -
Password:
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: syntax error near unexpected token `<'
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: `            done < <(command rclone listremotes)'
13:15:30 [root@brandizmac ~]# which bash
/bin/bash
13:15:34 [root@brandizmac ~]# bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
13:15:39 [root@brandizmac ~]#
```

which is the one shipped with macOS.

**Comment by ncw** [comment] 2019-08-29 12:42
The process substution syntax `<(command)` has been since bash 2 so bash 3 should be OK with that.

Does the autocomplete work as root or a user?

So if you type `rclone ls ` then press TAB twice do you get a list of all your remotes and all the local directories?

What happens if you `source /usr/local/etc/bash_completion.d/rclone` as root and a user?

**Comment by sgtpep** [comment] 2019-08-29 14:41
@ncw By chance I now have a macOS with the same exact version of bash. I tried `done < <(...)` construct on it and it didn't raise any error. It's weird, I have no other suggestions for diagnostics apart from `source /usr/local/etc/bash_completion.d/rclone`.

@marco-brandizi Sorry to ask you, but could you also upload `/usr/local/etc/bash_completion.d/rclone` to something like GitHub Gist or Pastebin? In this case I'll be able to reproduce it on my macOS device which I wouldn't like to pollute with Homebrew at the moment.

**Comment by marco-brandizi** [comment] 2019-08-29 15:14
I get this when I try to auto-complete rclone:

```bash
16:08:34 [brandizi@brandizmac luke]$ rclone ls -bash: compopt: command not found
rres-onedrive:-bash: compopt: command not found
```
and then it works correctly. It doesn't work at all under root.

The autocompletion file is [here][10] (I had to change its extension into .txt, but just because GH doesn't allow uploads otherwise).

[10]: https://github.com/rclone/rclone/files/3556229/rclone.txt

**Comment by marco-brandizi** [comment] 2019-08-29 15:25
More funny things:
```bash
16:23:02 [brandizi@brandizmac ~]$ su -
Password:
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: syntax error near unexpected token `<'
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: `            done < <(command rclone listremotes)'
16:23:08 [root@brandizmac ~]# cat < <(echo bla blah)
-sh: syntax error near unexpected token `<'
16:23:14 [root@brandizmac ~]#
16:23:31 [root@brandizmac ~]# exit
logout
16:23:33 [brandizi@brandizmac ~]$ cat < <(echo bla blah)
bla blah
16:24:04 [brandizi@brandizmac ~]$
```

So, must be something with the environment that is initialised  for my root, but no idea what. Since it doesn't seem rclone-specific anymore, I guess you should close this issue.

**Comment by sgtpep** [comment] 2019-08-29 15:41
> I get this when I try to auto-complete rclone:
> 
> ```shell
> 16:08:34 [brandizi@brandizmac luke]$ rclone ls -bash: compopt: command not found
> rres-onedrive:-bash: compopt: command not found
> ```

Thank you! @ncw Indeed, there's no `compopt` in macOS's native bash which is used twice in `__rclone_custom_func`. They should be used together with a check like `[[ $(type -t compopt) = "builtin" ]]` and fallback to macOS's alternative `complete -o ...` if possible.

**Comment by sgtpep** [comment] 2019-08-29 15:45
@marco-brandizi  As for operation under root there's still a way to debug it by adding `set -x` right after:
```
__rclone_handle_reply()
{
```
in `/usr/local/etc/bash_completion.d/rclone`, then restarting bash and trying to perform autocompletion.

**Comment by sgtpep** [comment] 2019-08-29 16:04
Here's the patch to prevent `compopt` from calling on macOS:
```
--- /usr/local/etc/bash_completion.d/rclone   2019-08-29 18:38:02.254440170 +0300
+++ /usr/local/etc/bash_completion.d/rclone~   2019-08-29 18:37:55.735182170 +0300
@@ -280,9 +280,9 @@
                 local reply=${prefix:+$prefix/}$line
                 [[ $reply != $path* ]] || COMPREPLY+=("$reply")
             done < <(rclone lsf "${cur%%:*}:$prefix" 2>/dev/null)
-           [[ ! ${COMPREPLY[@]} ]] || compopt -o filenames
+           [[ ! ${COMPREPLY[@]} || $(type -t compopt) != builtin ]] || compopt -o filenames
         fi
-        [[ ! ${COMPREPLY[@]} ]] || compopt -o nospace
+        [[ ! ${COMPREPLY[@]} || $(type -t compopt) != builtin ]] || compopt -o nospace
     fi
 }
``` 

Also, to someone who wants to emulate `compopt` options on macOS there's documentation for `complete` alternative: https://ss64.com/osx/complete.html. I believe it's possible to fallback to `complete` but it should be done all over `/etc/bash_completion.d/rclone` (in 6 places which just ignore `compopt` if it's not present).

**Comment by marco-brandizi** [comment] 2019-08-29 20:36
At this point, I'll report what I found just for the case you're curios. I think I know why I have the problem with process substitution: Bash doesn't support it in POSIX mode. In fact, 

```bash
21:07:03 [brandizi@brandizmac lucene]$ set -o |grep posix
posix          	off
21:07:06 [brandizi@brandizmac lucene]$ su -
Password:
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: syntax error near unexpected token `<'
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: `            done < <(command rclone listremotes)'
21:07:14 [root@brandizmac ~]# set -o |grep posix
posix          	on
21:07:19 [root@brandizmac ~]# bash
21:07:22 [root@brandizmac ~]# set -o |grep posix
posix          	off
21:07:23 [root@brandizmac ~]# exit
21:07:29 [root@brandizmac ~]# logout
21:07:32 [brandizi@brandizmac lucene]$
```
One solution might be `chsh -s /bin/bash`. But, I remembered about the `comopt` probelm too, so preferred to walk away from the rotten apple fiddlers by doing `brew install bash` (followed by a corresponding `chsh`). This fixed both the problems.

**Comment by ncw** [comment] 2019-09-03 13:01
So where are we with this?  Shall we merge your patch @sgtpep ? Does it fix the problem?

**Comment by sgtpep** [comment] 2019-09-03 14:30
@ncw My patch will eliminate the issue of `compopt` not being found on vanilla macOS `bash` that was reported by @marco-brandizi:

> I get this when I try to auto-complete rclone:
> 
> ```shell
> 16:08:34 [brandizi@brandizmac luke]$ rclone ls -bash: compopt: command not found
> rres-onedrive:-bash: compopt: command not found
> ```
> 
> and then it works correctly.

So, I think, it worth being merged, although the issue is not fatal and doesn't break the autocomplete. Sorry for not providing it as a proper PR, didn't have time for that.

The main issue of this ticket is that autocomplete is defunct when bash is run under root on vanilla macOS `bash`. If I understand @marco-brandizi correctly, it's not a case for `brew`-installed `bash`. 

We could debug this by placing `set -x` somewhere on top of bash init files to understand where `set -o posix` happens which enables posix mode for root. Or, we could just disable the whole autocomplete script if `posix` option is set (I could provide a patch for that, if needed.)

**Comment by ncw** [comment] 2019-09-03 16:04
> @ncw My patch will eliminate the issue of `compopt` not being found on vanilla macOS `bash` that was reported by @marco-brandizi as:
> 
> > I get this when I try to auto-complete rclone:
> > ```shell
> > 16:08:34 [brandizi@brandizmac luke]$ rclone ls -bash: compopt: command not found
> > rres-onedrive:-bash: compopt: command not found
> > ```
> > 
> > 
> > and then it works correctly.
> 
> So, I think, it worth being merged, although the issue is not fatal and doesn't break the autocomplete. Sorry for not providing it as a proper PR, didn't have time for that.

No problems.  I'll commit the fix unless you want to send a PR?

> The main issue of this ticket is that autocomplete is defunct when bash is run under root on vanilla macOS `bash` because it happened to operate in `posix` mode for some reason. If I understand @marco-brandizi correctly, it's not a case for `brew`-installed `bash`.
> 
> We could debug this by placing `set -x` somewhere on top of bash init files to understand where `set -o posix` happens which enables posix mode for root. 

I wonder if bash is invoked as `/bin/sh` as root on macOS?  That forces bash into posix mode.

This will tell us how the shell was invoked

    echo $0

In which case `chsh /bin/bash` as root would fix the issue.

> Or, we could just disable the whole autocomplete script if `posix` option is set (I could provide a patch for that, if needed.)

That is probably a good idea.

**Comment by sgtpep** [comment] 2019-09-04 09:22
> I'll commit the fix unless you want to send a PR?

Decided to make a proper PR to pump up my github stats a bit :)

> I wonder if bash is invoked as /bin/sh as root on macOS? That forces bash into posix mode.

That might be the most plausible explanation. Or, less likely, there're some custom configuration taking place in rc-files like `~/.bashrc` or others.

> > Or, we could just disable the whole autocomplete script if posix option is set (I could provide a patch for that, if needed.)
> 
> That is probably a good idea.

The perfect solutions could be the full support of the posix mode. The only two places that seems to be incompatible with it are introduced in `__rclone_custom_func` which are `while clause; do; body; done < <(command)`. They could be replaced with `command | while clause; do; body; done`, but in this case it would be impossible to preserve variable values changed within 'body': https://stackoverflow.com/questions/19570413/how-to-pipe-input-to-a-bash-while-loop-and-preserve-variables-after-loop-ends (And I couldn't find any workaround). So I'll sumit a PR which disables `__rclone_custom_func` in the posix mode.

**Comment by marco-brandizi** [comment] 2019-09-04 09:59
@ncw thanks for working on this. Yes, root's default shell is /bin/sh in macOS. I see you went with POSIX mode compatibility and I think that's is good.

**Comment by ncw** [comment] 2019-09-04 13:50
Thank you very much for your PR's @sgtpep - I've merged those now :-)

@marco-brandizi  can you have a go with [the latest beta](https://beta.rclone.org) (leave it 30 mins to make sure it gets built) and have a test - thank you :-)

**Comment by marco-brandizi** [comment] 2019-09-05 11:02
@ncw I've tried rclone-v1.49.0-023-g7b096688-beta-osx-386.
The compopt problem has gone. The process substitution issue under POSIX mode is still there.

Moreover, isn't there an option to generate the output of `genautocomplete` on stdout? it seems to have `/etc/bash_completion.d/rclone` hardwired and that's wrong for my system, which has autocompletion under /usr/local.

**Comment by sgtpep** [comment] 2019-09-05 12:11
@ncw Oh, snap, this error `syntax error near unexpected token `<'` happens during the parsing stage of the script execution, that's why it fails immediately before reaching the `if` clause (reproduced it to confirm). Sorry, my second PR is useless here and could be reverted.

I remembered about another obscure way to iterate over lines which should be posix-compatible. @marco-brandizi If that's not too much to ask, could you try this patch (it worked for me)?

```diff
--- /usr/local/etc/bash_completion.d/rclone	2019-09-04 12:06:49.730040668 +0300
+++ /usr/local/etc/bash_completion.d/rclone~	2019-09-05 15:06:54.109156003 +0300
@@ -260,10 +260,14 @@
             __rclone_init_completion -n : || return
         fi
         if [[ $cur != *:* ]]; then
+            local ifs=$IFS
+            IFS=$'\n'
+            local remotes=($(command rclone listremotes))
+            IFS=$ifs
             local remote
-            while IFS= read -r remote; do
+            for remote in "${remotes[@]}"; do
                 [[ $remote != $cur* ]] || COMPREPLY+=("$remote")
-            done < <(command rclone listremotes)
+            done
             if [[ ${COMPREPLY[@]} ]]; then
                 local paths=("$cur"*)
                 [[ ! -f ${paths[0]} ]] || COMPREPLY+=("${paths[@]}")
@@ -275,14 +279,18 @@
             else
                 local prefix=
             fi
+            local ifs=$IFS
+            IFS=$'\n'
+            local lines=($(rclone lsf "${cur%%:*}:$prefix" 2>/dev/null))
+            IFS=$ifs
             local line
-            while IFS= read -r line; do
+            for line in "${lines[@]}"; do
                 local reply=${prefix:+$prefix/}$line
                 [[ $reply != $path* ]] || COMPREPLY+=("$reply")
-            done < <(rclone lsf "${cur%%:*}:$prefix" 2>/dev/null)
-	    [[ ! ${COMPREPLY[@]} ]] || compopt -o filenames
+            done
+	    [[ ! ${COMPREPLY[@]} || $(type -t compopt) != builtin ]] || compopt -o filenames
         fi
-        [[ ! ${COMPREPLY[@]} ]] || compopt -o nospace
+        [[ ! ${COMPREPLY[@]} || $(type -t compopt) != builtin ]] || compopt -o nospace
     fi
 }
 ```

**Comment by ncw** [comment] 2019-09-05 13:57
@marco-brandizi wrote:
> The compopt problem has gone.

:-)

> The process substitution issue under POSIX mode is still there.

:-(

> Moreover, isn't there an option to generate the output of genautocomplete on stdout? it seems to have /etc/bash_completion.d/rclone hardwired, and that's wrong for my system, which has autocompletion under /usr/local.

You can give a file to `rclone genautocomplete bash /path/to/file`.  There is an easy issue to get it to output to stdout here: https://github.com/rclone/rclone/issues/3423 if someone wants to have a go?

@sgtpep wrote:
> Oh, snap, this error syntax error near unexpected token <'happens during the parsing stage of the script execution, that's why it fails immediately before reaching theif` clause (reproduced it to confirm). Sorry, my second PR is useless here and could be reverted.

No worries!

> I've remembered about another obscure way to iterate over lines which should be posix-compatible. @marco-brandizi If that's not too much to ask, could you try this patch (it worked for me)?

Happy to receive a PR updating things :-)

**Comment by ncw** [comment] 2019-09-06 12:12
@marco-brandizi 
I just merged @sgtpep latest change, so can you try [the latest beta](https://beta.rclone.org) in 30 mins from now when it has built?

Thanks

**Comment by marco-brandizi** [comment] 2019-09-06 17:20
@ncw, it seems to work, new/old shell, posix/non-posix mode, yeah! :-)

**Comment by ncw** [comment] 2019-09-08 17:09
> @ncw, it seems to work, new/old bash, posix/non-posix mode, yeah! :-)

Thank @sgtpep not me :-) Thank you!

**Comment by ivandeex** [comment] 2020-11-14 19:53
Closing per above

**Closed by ivandeex** 2020-11-14 19:53 UTC
Labels: bug
