### ISSUE TITLE
Copy entire directory structure, not just the contents

### ISSUE THREAD

**Issue by orlandodiaz** [rclone/rclone#1228] opened 2017-03-11 09:42 UTC
Hi, I'm trying to copy a directory but the copy command appears to only copy the contents and not the entire directory structure which is what I want:

So I have a directory dir1
dir1/
--file1
--file2
And want to copy it exactly to src/:
src/
--dir1
and not strip of its folder name like this:
src/
--file1
--file1

The command I am using is copy src remote:src. I've also tried copyto and it still copies the contents only. How can I make this work?

> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-40-gb6848a3β
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
OSX
> Which cloud storage system are you using? (eg Google Drive)
Google drive

**Comment by ncw** [comment] 2017-03-13 12:28
@orlandordiaz rclone copies directory to directory, so to do what you want use

    rclone copy dir1 src:dir1

**Comment by orlandordiaz** [comment] 2017-03-15 13:21
Please read my post again. I tried that command and it only copies the contents and subdirs without including the root folder itself. Not sure if this is a bug or if that's the intended behavior. If so, any way to work around it? Including folder should be the default IMO since that 'the default behavior of the cp command. If I wanted to copy only the contents I would have done  srcdir/ remote:dest with the forward slash at the end.

**Comment by ncw** [comment] 2017-03-16 12:15
rclone doesn't work like cp it works like rsync which syncs directories to directories.

So you need to name the remote directory in the copy, so `copy dir1 remote:src/dir1` if I've understood your example correctly.

**Comment by emilfihlman** [comment] 2017-04-13 17:13
rclone should definitely copy exactly what we tell it, not just the contents, so dir for whole dir and dir/ for just the contents. The behaviour should be amended.

**Comment by orlandordiaz** [comment] 2017-05-12 20:28
ncw doing copy dir1 remote:src/dir1 still copies the contents and doesnt preserve foldername.
Doing copy dir1 remote:src/newDirName/ only works for a specified dirname an when the dir exists on google drive.
Any chance you could implement this simple feature? It's just the case that preserving the directory name is extremely important in my case

**Comment by RobbieL811** [comment] 2017-05-16 21:54
I'm having this issue.  I'm experienced with rsync, and the behavior is not the same.  With rsync, if you remove the tailing / from the source path, it tells rclone to copy also the source directory instead of just it's contents.  @ncw, is there any way that we can make rclone behave the same in that regard?  Would be nice to be able to copy directories without having to name them in the dest path.  By the way, I'm not criticizing.  Just thinking out loud.  Thanks for the great tool!!!

**Comment by streaps** [comment] 2017-08-09 16:29
I would call this behaviour a usability bug. It makes no sense at all... Does anyone know an alternative to rclone that supports google team drives?

**Comment by ncw** [comment] 2017-08-09 17:57
Did you try the copyto command?

**Comment by streaps** [comment] 2017-08-09 19:34
rclone suggest that there is no difference between the two commands:

copy            Copy files from source to dest, skipping already copied
copyto          Copy files from source to dest, skipping already copied

rclone copyto --help

"If the source is a directory then it acts exactly like the copy command."

This doesn't seem to address the issue, if I understand it correctly.

**Comment by ncw** [comment] 2017-08-10 16:57
@streaps I'm not sure I understand the issue

Here is my fix for @orlandordiaz original issue (done on local disk)

```
$ mkdir dir1
$ touch dir1/file1
$ touch dir1/file2
$ mkdir src
$ tree dir1
dir1
├── file1
└── file2

0 directories, 2 files
$ rclone copy dir1 src/dir1
$ tree src
src
└── dir1
    ├── file1
    └── file2

1 directories, 2 files
```

or done on a remote if you prefer

```
ncw@dogger:/tmp/test$ rclone copy dir1 TestDrive:src/dir1
ncw@dogger:/tmp/test$ rclone tree TestDrive:src
/
└── dir1
    ├── file1
    └── file2

1 directories, 2 files
```

Which seems to solve the original problem.

This is documented in the [copy command docs](https://rclone.org/commands/rclone_copy/):

> Note that it is always the contents of the directory that is synced, not the directory so when source:path is a directory, it’s the contents of source:path that are copied, not the directory name and contents.

And if you want to copy the directory, there is an easy work around - just repeat the directory name on the end like I did above.

I deliberately didn't do the trailing `/` thing that rsync does as it is very easy to make a mistake with it, and it has been a source of data loss and [confusion for beginners](http://stay-calm.blogspot.co.uk/2008/10/rsync-be-mindful-of-trailing-slash.html).  When this last came up in #383 I wrote this:

I'm of the opinion that rsync's way of doing it, while clever, is extremely error prone and a mis-feature.

If you type

```
rsync -av --delete /path/to/my/files dest:/path/to/backup
```

Then one say with a bit of command line completion help, type

```
rsync -av --delete /path/to/my/files/ dest:/path/to/backup
```

Then you just deleted all the files in your backup and re-uploaded them :-(

I made rclone so that the trailing slash is irrelevant like it is in the rest of the unix world and it always refers to the directory contents.

I did write this in the docs to address this point for new users

> If you are familiar with `rsync`, rclone always works as if you had
> written a trailing / - meaning "copy the contents of this directory".
> This applies to all commands and whether you are talking about the
> source or destination.

I think, practically speaking, it is too late to change it, even if I wanted to :-(

**Comment by woky** [comment] 2017-11-26 23:10
> I think, practically speaking, it is too late to change it, even if I wanted to :-(

You could add a flag that will turn on rsync's behaviour so that brave users can make aliases. Everyone would be happy. ;-) Or perhaps just a (single-letter) flag that will make rclone copy sources _into_ traget directory. Or both. I'm more in favour of the first as I'm used to rsync syntax and I'd just make an alias for rclone with the flag.

**Comment by ncw** [comment] 2017-11-28 20:49
@woky nice idea.  Please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with this idea in and have a go at specifying what the flag should do.

**Comment by woky** [comment] 2017-11-28 21:31
@ncw Thank you for interest in implementing it! I'll post it later because I'll have to do some research first (like check which rclone commands should be affected).

**Comment by woky** [comment] 2017-11-28 21:49
Just a comparison of defaults with few tools:

```
+ mkdir -p src dst
+ touch src/a src/b
+ cleanup
+ rm -rf 'dst/*' newdst
+ cp -r src dst
+ cp -r src newdst
+ tree dst newdst
dst
└── src
    ├── a
    └── b
newdst
├── a
└── b

1 directory, 4 files
+ cleanup
+ rm -rf dst/src newdst
+ rsync -r src dst
+ rsync -r src newdst
+ tree dst newdst
dst
└── src
    ├── a
    └── b
newdst
└── src
    ├── a
    └── b

2 directories, 4 files
+ cleanup
+ rm -rf dst/src newdst
+ rclone copy src dst
+ rclone copy src newdst
+ tree dst newdst
dst
├── a
└── b
newdst
├── a
└── b

0 directories, 4 files
+ cleanup
+ rm -rf dst/a dst/b newdst
```

<details>
  <summary>script</summary>

```
#!/bin/bash

cleanup() {
	rm -rf dst/* newdst
}

set -x

mkdir -p src dst
touch src/{a,b}
cleanup

cp -r src dst
cp -r src newdst
tree dst newdst
cleanup

rsync -r src dst
rsync -r src newdst
tree dst newdst
cleanup

rclone copy src dst
rclone copy src newdst
tree dst newdst
cleanup
```

</details>

**Comment by seonwoolee** [comment] 2018-06-16 07:30
Was this ever done? I didn't fid anything with a quick search of current and past issues.

I'm having this issue as well, and as I understand it @ncw the solution you proposed doesn't work for encrypted remotes if I want folder name encryption.

To check my understanding....
I can do `rclone src secret:rclone` and it will copy the contents of src into the rclone folder on the remote. I can also do a `rclone mkdir secret:rclone/src`, and `rclone src secret:rclone/src`, but then if I log into Google drive (let's say that's my remote) then I'll see encrypted files at rclone/src. The folder name src is there in plain text.

**Comment by GAZ082** [comment] 2018-08-01 03:01
@ncw 's solution worked for me.

**Comment by mrmcmuffinz** [comment] 2018-10-04 02:57
To tack onto @woky suggestion of adding a flag could we use what `cp` does for `-R`. Reading the man for cp I see the below, so maybe something like that?

> -R    If source_file designates a directory, cp copies the directory and the entire subtree connected at that point.

**Comment by escorciav** [comment] 2019-04-08 09:02
The solution [here](https://github.com/ncw/rclone/issues/1228#issuecomment-321611378) worked.

> ```
> ncw@dogger:/tmp/test$ rclone copy dir1 TestDrive:src/dir1
> ncw@dogger:/tmp/test$ rclone tree TestDrive:src
> /
> └── dir1
>     ├── file1
>     └── file2
> 
> 1 directories, 2 files
> ```

Please note that we also need to write `dir1` in the remote part, `TestDrive`. I guess that's what the issue plan to address.

Thanks for making this public.

**Comment by SemiQuant** [comment] 2019-04-17 09:15
A bash function based on the above that works for me. Replace YourDestinationDrive with where you want to copyto.
`rclone_folder () {
     rclone copyto "${1// /\\ }" YourDestinationDrive:"${1// /\\ }"
}`

**Comment by streaps** [comment] 2019-06-07 19:04
Is there now some user friendly solution in rclone that doesn't suck?

**Comment by escorciav** [comment] 2019-06-08 04:22
Please update your reply that's not an appropriate manner to ask questions or request features. Impolite and harsh feedback damages the community.

---

If your shell is bash, you could use bash-scripting. `file=very_long_path_from_autocompletion; rclone copy $file TestDrive:$file`. There are two commands there. The first command (before `;`) defines a variable, and the second command spawns a call to `rclone`.

If you have multiple files, I usually create a small script to dump a txt-file with the path and use `--files-from list-with-files.txt`. The documentation clearly explains [this](https://rclone.org/filtering/#files-from-read-list-of-source-file-names).

**Comment by streaps** [comment] 2019-06-08 09:58
but this is not really user friendly and does not work for windows.

**Comment by piratetub** [comment] 2019-11-29 08:24
Hi there @ncw. Chiming in to say that I also believe that a flag to enable rsync's behaviour (or one that works like `-R` for `cp`, even better) would be quite useful. I can open a new issue if you want . Hope you're doing well. :)

**Comment by animosity22** [comment] 2020-05-10 19:38
@orlandodiaz  - it looks like your initial issue has been solved. is this good to close out?

**Comment by dausruddin** [comment] 2020-09-18 07:34
Would be great to see this implemented.

**Comment by castanley** [comment] 2020-11-07 20:34
+1 on getting this implemented :D 👍

**Comment by ivandeex** [comment] 2020-11-16 02:31
@dausruddin @castanley 
Your `+1` comments hardly help the project, just spam the watchers mailboxes.
Please use the 👍 counter on the isdue heading.
Thank you.

**Comment by ivandeex** [comment] 2020-11-16 02:32
@orlandodiaz looks like you are no longer intetested in this request, since May 2020.

**Comment by ivandeex** [comment] 2020-11-16 02:51
The common idea here is that `rclone copy` and `rclone sync` diverge from usual `cp` and `rsync` in syntax and semantics resulting in degraded UX.

It's pretty clear as rclone unlike `cp` was initially created as a cloud tool, and has been optimized right for network environment.

We cannot change syntax of existing commands as it would break compatibility with existing rclone wrappers and scripts. Instead, we'll add new subcommands with homelike syntax.

Unfortunately this issue has become a mix of unconnected requests and. It's really hard to track and implement this way.

Closing in favor of https://github.com/rclone/rclone/issues/4776 and https://github.com/rclone/rclone/issues/4777

**Closed by ivandeex** 2020-11-16 02:51 UTC
Labels: UX, duplicate, enhancement
