### ISSUE TITLE
large upload to Dropbox stalls at 100%, retries, fails

### ISSUE THREAD

**Issue by borkd** [rclone/rclone#2158] opened 2018-03-20 21:32 UTC
#### What is the problem you are having with rclone?

Large file upload to Dropbox Enterprise stalls for hours at 100%, eventually retries, then fails.

File in question is 380 GBytes in size, making repeated tests both expensive and time consuming.  Resumable upload would be a lifesaver, and not just for troubleshooting.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Scientific Linux 6.9, x86_64

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox (Enterprise)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -v --low-level-retries 1024 --retries 1024 --stats 10s --transfers=8 --drive-chunk-size=33554432 copy bigfile dropbox:target/dir/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
According to percentages the upload should have finished ~10 hours ago...

```
[...]

2018/03/20 11:20:59 INFO  :
Transferred:   380 GBytes (4.153 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  26h1m40.4s
Transferring:
 *             bigfile: 100% /380G, 0/s, 0s

2018/03/20 11:21:09 INFO  :
Transferred:   380 GBytes (4.152 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  26h1m50.4s
Transferring:
 *             bigfile: 100% /380G, 0/s, 0s

2018/03/20 11:21:19 INFO  :
Transferred:   380 GBytes (4.152 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:   26h2m0.4s
Transferring:
 *             bigfile: 100% /380G, 0/s, 0s

2018/03/20 11:21:29 INFO  :
Transferred:   380 GBytes (4.151 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  26h2m10.4s
Transferring:
 *             bigfile: 100% /380G, 0/s, 0s

2018/03/20 11:21:39 INFO  :
Transferred:   380 GBytes (4.151 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  26h2m20.4s
Transferring:
 *             bigfile: 100% /380G, 0/s, 0s

[...]
```

**Comment by ncw** [comment] 2018-03-20 22:04
Try rclone 1.40 which has just been released - I think it will fix this problem.

**Comment by borkd** [comment] 2018-03-20 22:44
Any hack to gently let this upload succeed w/o resorting to yet another retry? I would prefer to use new version to test upload of remaining large sets.

**Comment by ncw** [comment] 2018-03-21 10:29
It is almost certainly going to succeed - it is the stats output which is wrong I think.

Cross fingers!

**Comment by borkd** [comment] 2018-03-21 23:18
Had to interrupt the endless loop after 24hrs of 100%. No record of file on Dropbox. No problem uploading small files, which makes this bug rather frustrating. Trying with 1.40

**Comment by ncw** [comment] 2018-03-22 10:13
@borkd let me know how it goes.

**Comment by borkd** [comment] 2018-03-23 01:47
```
rclone v1.40
- os/arch: linux/amd64
- go version: go1.10
```

New release, same resounding failure and attempt to reupload for the 2nd time..

```
2018/03/22 11:39:46 INFO  :
Transferred:   434.568 GBytes (4.687 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  26h22m20.4s
Transferring:
 *             bigfile: 14% /380G, 4.306M/s, 21h29m57s

2018/03/22 11:39:56 INFO  :
Transferred:   434.623 GBytes (4.687 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  26h22m30.4s
Transferring:
 *             bigfile: 14% /380G, 4.800M/s, 19h16m51s
```

It should not matter, but the file is a XFS filesystem image.

**Comment by borkd** [comment] 2018-03-23 20:05
I would call this a bug, a 30 GByte file uploads fine

**Comment by ncw** [comment] 2018-03-23 22:15
Can you attach a **full* log made with `-vv --log-file rclone.log` please?  I can't debug further without one - thanks.

**Comment by ncw** [comment] 2018-03-26 20:49
That one hasn't reached 100% it seemed to be going fine?

```
Transferred:   1051.750 GBytes (4.683 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  63h53m0.8s
Transferring:
 *             bigfile: 76% /380G, 4.418M/s, 5h40m52s

2018/03/26 10:37:25 DEBUG : bigfile: Uploading chunk 6225/8107
2018/03/26 10:37:39 DEBUG : bigfile: Uploading chunk 6226/8107
2018/03/26 10:37:52 DEBUG : bigfile: Uploading chunk 6227/8107
2018/03/26 10:38:02 DEBUG : bigfile: Uploading chunk 6228/8107
```

**Comment by borkd** [comment] 2018-03-27 13:44
No it is not. Look at the log, please. I have killed the upload after two fails and at 76% into the third attempt so you can see repeated failures.

Transferred:   **1051.750 G**Bytes

Transferring: "76% /**380G**"

1051/380 = **276%** of expected total upload size

If verbose log message does not explain the transfer status clearly enough maybe it should be fixed as well.

**Comment by borkd** [comment] 2018-03-27 20:04
@ncw - Increased ```--low-level-retries ``` makes no difference. If you read the first entry for this bug you will see I retried the upload with both retry settings set to ridiculously high values prior to reporting the bug (```--low-level-retries 1024 --retries 1024 ```). Since the end result is always a failure, I reverted to defaults in subsequent runs.

**Comment by borkd** [comment] 2018-03-27 21:54
Plentiful retries and an exponential backoff strategy should be considered as a default during final commit and session finish phases for large uploads to Dropbox. 

Assuming current issue is resolved and a 380GB file can be uploaded in about 26hrs, is 48hr limit from [UploadSessionFinishBatchCheck](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/d298729be9aeafbdac35472ce2c873986d46f241/dropbox/files/client.go#L266)  going to become a show stopper for 1TB+ uploads?

**Comment by ncw** [comment] 2018-03-28 21:06
@borkd yes you did say you tried a large `--low-level-retries` so don't bother with that part of the suggestion above.  If you could do the logging then that would be very helpful and it will tell us what is going on.

> Plentiful retries and an exponential backoff strategy should be considered as a default during final commit and session finish phases for large uploads to Dropbox.

rclone does do both exponential retries, and as many retries as you set in `--low-level-retries`.  However the current code has the max retry set at 2s.  Maybe I should raise that limit...

It might be that I need a special retry scheme for the final commit.  I had to make one for ACD.

So 1024 retries would be about 34 minutes.  I wonder if that is long enough?

> Assuming current issue is resolved and a 380GB file can be uploaded in about 26hrs, is 48hr limit from UploadSessionFinishBatchCheck going to become a show stopper for 1TB+ uploads?

rclone uses UploadSessionFinish rather than UploadSessionFinishBatch, but the same limit seems to apply.

I wonder if the problem is that UploadSessionFinish is a synchronous method and it is just taking too long.  Maybe that mysterious HTTP error is a 408 timeout or something like that which would make sense (the edge load balancer will timeout before the call finishes).  It is only about 10 or 15 seconds until the first error though.

In which case using UploadSessionFinishBatch mght be the way to go to get an async job handle which can be sensibly polled.

Worth pursuing do you think?

**Comment by borkd** [comment] 2018-03-28 23:51
I'll upload the responses from around the failure once the upload fails again. And yes, worth pursuing -
 expensive uploads are worthy of special handling in my opinion. That is until there is a reliable way to suspend and resume at any point within the granularity of a single chunk.

**Comment by ncw** [comment] 2018-03-30 18:59
@borkd thanks for your help tracking this down.  I've worked on the dropbox upload a lot in the last 6 months and it is much more reliable than it used to be - I'd like to make it 100% even for huge files.

**Comment by borkd** [comment] 2018-03-30 23:29
At this point I am all but certain that rclone, and at least one more client, severely underestimates the amount of time Dropbox backend needs to handle **/2/files/upload_session/finish** API call for a file with many thousands of appends. 

If nothing else, giving up in 3 minutes after successful upload of ALL chunks which took 29.5 hours seems rather silly.

# Last successful append
```
2018/03/30 17:02:53 DEBUG : HTTP REQUEST (req 0xc420466400)
2018/03/30 17:02:53 DEBUG : POST /2/files/upload_session/append_v2 HTTP/1.1
2018/03/30 17:02:53 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/30 17:03:01 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/30 17:03:01 DEBUG : HTTP RESPONSE (req 0xc420466400)
2018/03/30 17:03:01 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Fri, 30 Mar 2018 21:03:01 GMT
Pragma: no-cache
Server: nginx
Vary: Accept-Encoding
X-Dropbox-Request-Id: REDACTED
X-Robots-Tag: noindex, nofollow, noimageindex
X-Server-Response-Time: 2911

4
null
0
```

# Session finish fail

```
2018/03/30 17:03:01 DEBUG : HTTP REQUEST (req 0xc420169900)
2018/03/30 17:03:01 DEBUG : POST /2/files/upload_session/finish HTTP/1.1
[...]
2018/03/30 17:03:01 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/30 17:03:17 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/30 17:03:17 DEBUG : HTTP RESPONSE (req 0xc420169900)
2018/03/30 17:03:17 DEBUG : HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Connection: keep-alive
Content-Security-Policy: sandbox allow-forms allow-scripts
Content-Type: text/plain; charset=utf-8
Date: Fri, 30 Mar 2018 21:03:17 GMT
Server: nginx
X-Dropbox-Request-Id: REDACTED
X-Robots-Tag: noindex, nofollow, noimageindex

0

[...]

2018/03/30 17:05:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/30 17:05:13 DEBUG : pacer: low level retry 9/10 (error unexpected end of JSON input)
2018/03/30 17:05:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/30 17:05:13 DEBUG : HTTP REQUEST (req 0xc420169900)
2018/03/30 17:05:13 DEBUG : POST /2/files/upload_session/finish HTTP/1.1
Host: content.dropboxapi.com
User-Agent: rclone/v1.40
Content-Length: 0
Authorization: XXXX
Content-Type: application/octet-stream
Dropbox-Api-Arg: REDACTED
Accept-Encoding: gzip

2018/03/30 17:05:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/30 17:05:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/30 17:05:26 DEBUG : HTTP RESPONSE (req 0xc420169900)
2018/03/30 17:05:26 DEBUG : HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Connection: keep-alive
Content-Security-Policy: sandbox allow-forms allow-scripts
Content-Type: text/plain; charset=utf-8
Date: Fri, 30 Mar 2018 21:05:26 GMT
Server: nginx
X-Dropbox-Request-Id: REDACTED
X-Robots-Tag: noindex, nofollow, noimageindex

0

2018/03/30 17:05:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/30 17:05:26 DEBUG : pacer: low level retry 10/10 (error unexpected end of JSON input)
2018/03/30 17:05:26 DEBUG : bigfile: Received error: upload failed: unexpected end of JSON input - low level retry 1/10
2018/03/30 17:05:26 DEBUG : bigfile: Uploading chunk 1/8107
2018/03/30 17:05:26 DEBUG : 
```

# self-inflicted abort & start from scratch
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/30 17:05:26 DEBUG : HTTP REQUEST (req 0xc420998100)
2018/03/30 17:05:26 DEBUG : POST /2/files/upload_session/start HTTP/1.1
```

**Comment by ncw** [comment] 2018-03-31 20:36
@borkd thanks for the logs - that makes it very clear what is happening.  The final session finish is getting a 503 error with an empty body.

> At this point I am all but certain that rclone, and at least one more client, severely underestimates the amount of time Dropbox backend needs to handle /2/files/upload_session/finish API call for a file with many thousands of appends.

You may well be right.  However as far as I know the dropbox API should never return a 503 error so I suspect that there may be something else going on.

@diwakergupta do you have an opinion here?

**Comment by borkd** [comment] 2018-04-02 20:44
@ncw - Per https://www.dropboxforum.com/t5/API-support/API-v2-limits/m-p/209029/highlight/true#M10342 503 response is possible. And what a better place for a lock contention than a commit for thousands worth of appends?

**Comment by borkd** [comment] 2018-04-02 21:29
Follow-up from an experiment I ran over the weekend -  attempt to retry and wait out the 503 using a modified bash/curl client. 

Just like with rclone, all chunks uploaded fine using `/2/files/upload_session/append_v2` before Dropbox API ~~shat~~ excused itself on `/2/files/upload_session/finish`. 

I did expect the call to eventually return without error, but that was not the case. Retries went on for another 89341s (24h49m), which I guess was the end of session lifetime. After that  `409 lookup_failed/not_found/.*` and `504 Gateway Time-out` variety of responses were reported.

**Comment by borkd** [comment] 2018-04-03 20:41
@ncw - until Dropbox chimes in, I'd flag this as an upstream bug.

**Comment by ncw** [comment] 2018-04-04 15:27
Thanks for doing that testing @borkd.

I guess the next thing to try might be to use UploadSessionFinishBatch - can you try that with your curl/bash lashup?

**Comment by diwakergupta** [comment] 2018-04-04 16:05
@borkd @ncw thanks for your patience! I can confirm that this is a known issue that Dropbox is looking into and isn't limited to any specific SDK. I'll update once I know more, hang tight!

**Comment by ncw** [comment] 2018-04-05 14:43
@diwakergupta thanks for the update :-)

**Comment by diwakergupta** [comment] 2018-04-06 22:34
@borkd I'm curious to better understand the use-case(s) where you're needing to upload 300+ GB large files?

@ncw speaking with my Dropbox hat on: this looks like a previously unknown limit. We will work on improving it over time but unfortunately it's not a quick fix. In the near term, we'll correct the error code and update our docs. Thanks for catching this. We'll keep you updated!

**Comment by borkd** [comment] 2018-04-06 23:00
@ncw - thanks for bringing rclone into the world.

@diwakergupta - I can appreciate the curiosity, but the use-case has nothing to do with rclone. We can follow up through the enterprise support ticket I opened.

**Comment by diwakergupta** [comment] 2018-05-23 05:08
@ncw can you retry with the latest SDK? The spec has been updated to clarify max file size and return a specific error -- that should help clients with handling failures better.

**Comment by ncw** [comment] 2018-05-23 15:22
@diwakergupta are you going to tag a release? I've just realised that `go dep` isn't updating it because there haven't been any tags since v4.0.0 in December....  I can work around this but it is probably best if you tag a release!

**Comment by diwakergupta** [comment] 2018-05-23 16:18
@ncw sure thing, released v4.1.0

**Comment by ivandeex** [comment] 2021-02-09 16:27
@borkd @diwakergupta This problem is reported against obsolete rclone version. Can you reproduce it with rclone 1.54?

**Comment by borkd** [comment] 2021-02-09 19:41
@ivandeex - this issue was on the Dropbox side, and once it was discovered and reported they have decided to cap max upload size.. Currently their website states 50GB limit by default, 250GB for some add-on, and 350GB through API, but I have not verified this is accurate and that 350GB would succeed with current version. It would not be a bad idea to tell reject attempts to upload larger objects.

> https://help.dropbox.com/installs-integrations/sync-uploads/upload-limitations

**Comment by ivandeex** [comment] 2021-02-09 19:55
@borkd
Thanks you.
Submitting your comment as an enhancement.
Closing.

**Closed by ivandeex** 2021-02-09 19:55 UTC
Labels: Remote: Dropbox, bug, waiting for reply...
