### ISSUE TITLE
lib/encoder: BenchmarkOneDriveREplaceNew fails

### ISSUE THREAD

**Issue by odeke-em** [rclone/rclone#5659] opened 2021-10-04 08:07 UTC
#### What is the problem you are having with rclone?
I tried to run benchmarks on rclone but they failed instead with
```shell
$ go test -run=^$ -bench=.
--- FAIL: BenchmarkOneDriveReplaceNew
    encoder_test.go:290: Encode("\\*<>?:|#%\".~/\\*<>?:|#%\".~") want "＼＊＜＞？：｜＃％＂.~/＼＊＜＞？：｜＃％＂.~" got "＼＊＜＞？：｜＃％＂.~／＼＊＜＞？：｜＃％＂.~"
    encoder_test.go:290: Encode(" leading space/ leading space/ leading space") want " leading space/ leading space/ leading space" got " leading space／ leading space／ leading space"
    encoder_test.go:290: Encode("~leading tilde/~leading tilde/~leading tilde") want "～leading tilde/～leading tilde/～leading tilde" got "～leading tilde／~leading tilde／~leading tilde"
    encoder_test.go:290: Encode("leading tilde/~leading tilde") want "leading tilde/～leading tilde" got "leading tilde／~leading tilde"
    encoder_test.go:290: Encode("trailing dot./trailing dot./trailing dot.") want "trailing dot．/trailing dot．/trailing dot．" got "trailing dot.／trailing dot.／trailing dot．"
goos: darwin
goarch: amd64
pkg: github.com/rclone/rclone/lib/encoder
cpu: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
BenchmarkOneDriveReplaceOld-8   	   46914	     24894 ns/op
--- FAIL: BenchmarkOneDriveRestoreNew
    encoder_test.go:301: Decode("~leading tilde/～leading tilde/～leading tilde") want "~leading tilde/~leading tilde/~leading tilde" got "~leading tilde/～leading tilde/～leading tilde"
    encoder_test.go:301: Decode("leading tilde/～leading tilde") want "leading tilde/~leading tilde" got "leading tilde/～leading tilde"
    encoder_test.go:301: Decode("trailing dot．/trailing dot．/trailing dot.") want "trailing dot./trailing dot./trailing dot." got "trailing dot．/trailing dot．/trailing dot."
BenchmarkOneDriveRestoreOld-8   	  295726	      4191 ns/op
FAIL
exit status 1
FAIL	github.com/rclone/rclone/lib/encoder	2.838s
```

and I discovered this by trying to add continuous benchmarking using Orijtech Inc's product ["Bencher"](https://bencher.orijtech.com/)  which produced the following https://dashboard.github.orijtech.com/benchmark/6eb7fed63a004f859bcea067383a9544
![Screen Shot 2021-10-04 at 1 06 04 AM](https://user-images.githubusercontent.com/4898263/135815511-bb64e206-211f-42e1-9e9a-dda29e7bc272.png)

and this can be reproduced on other systems. I highly encourage adding rclone for FREE to gobencher via the Github marketplace per https://github.com/marketplace/gobencher; every PR/commit will get benchmarked and you'll see what regressed or not 

#### What is your rclone version (output from `rclone version`)
Git commit 60323dc5e2fd0c4b269c1316784bf14adfacf5a6

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Both MacOS and Linux 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Not Applicable

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`go test -run=$^ -bench=. ./...`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

/cc-ing my colleagues @cuonglm @kirbyquerby

**Comment by ncw** [comment] 2021-10-05 15:19
Can you do a git bisect to find out when the benchmark broke? Then we can see if it has always been broken or something specific we did broke it which we probably need to fix - thank you :-)

**Comment by kirbyquerby** [comment] 2021-10-29 18:55
@ivandeex

> I admit I have problems using Github GUI to get from the CI actions page https://github.com/ivandeex/rclone/actions/runs/1395533530 though to checks https://github.com/ivandeex/rclone/runs/4037305887

Yeah, GitHub's UI is a bit weird in that respect -- unfortunately, while actions and checks behave somewhat similarly, they have some unintuitive differences. The  `Actions` tab of the repository only shows results from _actions_, not from _checks_. The way I got to your checks run from your commit was:
1. I visited the commit's page: https://github.com/ivandeex/rclone/commit/996247e33ebe41e82f2b433385c012a551fe12de
2. I clicked the little green check mark to the left of the commit title (if the checks are still running, it will be a yellow circle. Or if any checks failed, it will be a red X):
![image](https://user-images.githubusercontent.com/6455350/139475175-57427856-698b-4612-bb0f-cdabc8473ffe.png)
3. This brought up a scrollable list of all of the checks and actions. At the bottom was bencher's check:
![image](https://user-images.githubusercontent.com/6455350/139475245-2099599d-d678-46fb-a4e0-c8169e9f640e.png)
4. I clicked the "details" link, which took me to https://github.com/ivandeex/rclone/runs/4037305887

On a PR, the information is surfaced a bit more easily, as the `Checks` tab shows both _checks_ and _actions_ (eg https://github.com/kirbyquerby/test-gobencher/pull/17/checks) . Unfortunately I'm not aware of a more obvious way to get to the checks page without making a PR. We can definitely update our documentation to show how to get to the benchmark results page from a commit.

> After fixing the benchmark I repeated the commit with a different commit message. Now I have two commits with working benchmarks. Still nothing on the Bencher dashboard:

The issue is that **there are no previous successful benchmarks on master** (the "base branch"), so we have nothing to compare against when showing benchmark results. Ordinarily, bencher would populate this itself but this step failed because the benchmarks on master currently fail:
![image](https://user-images.githubusercontent.com/6455350/139480269-20aa2d8c-018e-4a14-b62d-bf991dbb6606.png)

Once the change fixing the benchmarks is merged to master, new PRs/commits will have results, such as:
https://dashboard.github.orijtech.com/benchmark/5138fac076f244b5b7dbae8aa5c36305

Thanks again for the feedback, and please let me know if anything's still unclear.

**Comment by ivandeex** [comment] 2021-10-29 19:13
I guess landing the "little green check" trick in your docs will help your future users.

Thanks, it's clear now.

**Closed** 2021-11-02 16:23 UTC
Labels: test issue
