### ISSUE TITLE
VolumeDriver.Mount: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH

### ISSUE THREAD

**Issue by logopk** [rclone/rclone#6844] opened 2023-03-14 16:32 UTC
#### What is the problem you are having with rclone?

Using the volume plugin in 1.6.2 fails with missing dependency

I guess the plugin was not updated to fuse3?

#### What is your rclone version (output from `rclone version`)

v1.6.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Docker 23.0.1 on Debian Bullseye 

#### Which cloud storage system are you using? (e.g. Google Drive)

OneDrive & WebDav

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

docker-compose up -d           
[+] Running 0/1
 ⠋ Container rclone-monitor  Creating                                                                                                     0.0s
Error response from daemon: VolumeDriver.Mount: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

see above

**Comment by dihmandrake** [comment] 2023-03-14 17:28
To avoid some spam by opening a new issue, I am going to add some more context here. I just upgraded to the new `1.62` release (I think the first post in this issue has a type @logopk ) and started to get the issue `Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH`. Obviously this is fatal and nothing else happens.
Downgrading back to version `1.61.1` solved the problem. So it is certainly somehow related to the changes from `1.61.1` -> `1.62`. My command is `rclone mount` (with a bunch of options, but I think they are irrelevant here).

Most importantly, this is getting executed in Docker (hence the easy downgrade). I would guess either the `fuse3` dependency is now required and forgotten in the image (I have not had time to build my own container yet) or some code changes are hitting this error.

Possibly related to https://github.com/rclone/rclone/issues/3562 as it was included in this release. Once I have more time, I will try to investigate this.

**Comment by JohnnyKing94** [comment] 2023-03-15 08:58
I'm having the same issue as well with the new version 1.62.
Please fix asap.

**Comment by RyukSniper** [comment] 2023-03-15 09:04
I'm having the same issue as well with the new version 1.62.
Please fix asap :c

**Comment by francofunghi** [comment] 2023-03-15 09:29
Same here, pls fix THX in advance

**Comment by logopk** [comment] 2023-03-15 15:48
Unfortunately the changed Dockerfile is not the one used for the plugin:

https://github.com/rclone/rclone/tree/master/contrib/docker-plugin/managed/Dockerfile

I'll see if I can file a PR tonight.

**Comment by ncw** [comment] 2023-03-15 15:55
I have released v1.62.1 which fixes the rclone main docker image - thank you @cycneuramus for the patch.

@logopk I expect you are right and that won't fix the volume driver though :-(

**Comment by ncw** [comment] 2023-03-15 16:00
I have pushed a fix for that to master which will arrive in `rclone/rclone:beta` in approx 1 hour (I don't know why the builds are taking so long!).

I'd appreciate testing from anyone affected - thanks.

If that works out OK then I'll release it into v1.62.2

**Comment by Cringely** [comment] 2023-03-15 22:30
Switching the the beta release resolved this issue for me.

**Comment by youtehub** [comment] 2023-03-16 01:51
![image](https://user-images.githubusercontent.com/18629921/225489177-8e8653af-3f17-4c9b-a5b5-ef2eeb0cbe03.png)
As shown in the picture, if rclone is used to mount Ubuntu directly at present, an error in issues will appear in the log. rclone is not mounted in the docker container, but is mounted using Ubuntu commands directly

**Comment by cycneuramus** [comment] 2023-03-16 07:28
@youtehub You need to install the `fuse3` package.

**Comment by logopk** [comment] 2023-03-16 09:38
@ncw 

> I have pushed a fix for that to master which will arrive in `rclone/rclone:beta` in approx 1 hour (I don't know why the builds are taking so long!).

The plugin does not have a beta tag - yet?

**Comment by ncw** [comment] 2023-03-16 11:10
I've released a fix for the docker volume plugin in v1.62.2 which is building now and should be ready in about 1 hour.

**Closed by ncw** 2023-03-16 11:10 UTC

**Comment by snickers2k** [comment] 2023-03-17 16:42
i just updated from 1.52 yesterday to 1.62.2 and now having the same problem since ..
how to downgrade? :D

**Comment by Cr2649** [comment] 2023-03-17 17:26
How can I install a previous version of rclone using commands in ubuntu to correct this error, the beta keeps giving me the same error.

**Comment by Cr2649** [comment] 2023-03-17 17:34
![image](https://user-images.githubusercontent.com/128174858/225977477-8ba6a5d6-3af6-496d-bf87-2d476f00f554.png)
Despite having it in the beta version, it keeps giving me the error when I try to mount the drive in the created folder

**Comment by cycneuramus** [comment] 2023-03-17 17:36
Install the `fuse3` package.

**Comment by Cr2649** [comment] 2023-03-17 17:39
> Install the `fuse3` packagmy friend 
![image](https://user-images.githubusercontent.com/128174858/225978422-81c18d9b-ee7b-494b-8268-4678d8c81f71.png)

I get this error and the problem is that fuse3 doesn't work for ubuntu 18.04

**Comment by cycneuramus** [comment] 2023-03-17 17:42
That's not an issue with rclone, though. You need to upgrade your distribution (which reaches end-of-life next month anyway).

**Comment by Cr2649** [comment] 2023-03-17 17:56
> That's not an issue with rclone, though. You need to upgrade your distribution (which reaches end-of-life next month anyway).

rclone going to stop working? is what you want to tell me.

What will happen to the servers that we have connected to google drive through rclone, I did not understand you, my whatsapp could help me + 573004648342

**Comment by Matzeee** [comment] 2023-03-18 22:58
Regarding the docker volume plugin, should one install [fuse3](https://packages.debian.org/bullseye/fuse3) instead of [fuse](https://packages.debian.org/bullseye/fuse) on the host?

If yes, could you update the [docs](https://rclone.org/docker/#getting-started)?
That also might explain some strange errors I encountered.  I had the volume disappearing, the plugin being disabled, go errors on starting portainer and finally the vps does not even boot. Is there anything else I should have done for [upgrading](https://docs.docker.com/engine/reference/commandline/plugin_upgrade/) the plugin?

If not, it was probably because of `-o vfs-cache-mode=full` and too little ram and hdd space on my vps…

**Comment by orcrist81** [comment] 2023-03-18 23:05
Same problem here installing in DSM 7 (Synology NAS)  :(

**Comment by jostyee** [comment] 2023-03-27 13:27
> Same problem here installing in DSM 7 (Synology NAS) :(

try `sudo ln -s /bin/fusermount /bin/fusermount3`

**Comment by weiyanle** [comment] 2023-03-30 03:50
> > Same problem here installing in DSM 7 (Synology NAS) :(
> 
> try `sudo ln -s /bin/fusermount /bin/fusermount3`

thanks! it works for me

**Comment by Dryrtan** [comment] 2023-04-18 20:53
> > Same problem here installing in DSM 7 (Synology NAS) :(
> 
> try `sudo ln -s /bin/fusermount /bin/fusermount3`

It works for me, thanks!

**Comment by AlexKLMan** [comment] 2023-05-01 20:32
Great, thank you so much, that worked!
sudo ln -s /bin/fusermount /bin/fusermount3

**Comment by aamirbinabd** [comment] 2023-05-03 19:05
> > Same problem here installing in DSM 7 (Synology NAS) :(
> 
> try `sudo ln -s /bin/fusermount /bin/fusermount3`

Works!

**Comment by Diejeitor** [comment] 2023-06-01 07:24
I have the seem problem but in a Qnap, i can´t resolve it because, in "bin" folder, i don´t have the "fusermount" and "fusermount3" folders. Can someone help me please?

**Comment by nuarif** [comment] 2023-06-05 07:40
> I have the seem problem but in a Qnap, i can´t resolve it because, in "bin" folder, i don´t have the "fusermount" and "fusermount3" folders. Can someone help me please?

I always use the old version of Rclone cause setting up in cloud VM is quicker with them until I need to do something that only the newer version can do and faced with this fuse3 problem though sudo apt install fuse3 solved it for me. Maybe you can try installing the older version if you only need basic uses like synching, copy and move? Try this version rclone-v1.52.1, that's the one I used without problem for ages.

**Comment by roisiano** [comment] 2023-06-05 07:59
Hello:

I had this problem using CoreELEC ( https://coreelec.org/ ) , and, in this system for Amlogic TV-Boxes (CoreELEC versions):
ln -s /usr/bin/fusermount /usr/bin/fusermount3
is NOT possible to create the symlink ("Read only filesystem").
https://discourse.coreelec.org/t/is-it-possible-to-create-a-symlink-in-usr-bin/26133/3

I installed (entware) fusermount3, but it seems that rclone searchs for fusermount3 in:
/usr/bin 
and not in:
/storage/.opt/bin/ 

So a "patch" for this would be, perhaps, for rclone:
* Use fusermount3 in usr/bin
* If it does NOT exists there, search and use fusermount3 in different "bin" folders
* If it doesn't find fusermount3 in ay "fin" folder, look for and use fusermount in usr/bin 


In my case, with CoreELEC, I returned to 1.61.1 version.


Kind regards

**Comment by ncw** [comment] 2023-06-09 17:18
@roisiano `fusermount3` needs to be on the `$PATH` so if you ensure `/.opt/bin` is on the PATH it will work fine. You can probably set this in your linux distro. It can even be a symlink.

**Comment by roisiano** [comment] 2023-06-10 09:32
> @roisiano `fusermount3` needs to be on the `$PATH` so if you ensure `/.opt/bin` is on the PATH it will work fine. You can probably set this in your linux distro. It can even be a symlink.

Hello:
CoreELEC:~/.opt/bin # echo $PATH
**/opt/bin**:/opt/sbin:/usr/bin:/usr/sbin: 

CoreELEC:~/.opt/bin # ls -la
(...)
-rwxr-xr-x    1 root     root         31264 May 26 22:39 **fusermount3**
(...)

So, the PATH is right, but rclone seems that does NOT use the path. 

Second option:
CoreELEC:~/.opt/bin # **ln -s /bin/fusermount /bin/fusermount3
ln: /bin/fusermount3: Read-only file system**
 
Not working for me. 

Kind regards

**Comment by ncw** [comment] 2023-06-10 14:34
> So, the PATH is right, but rclone seems that does NOT use the path.

Rclone definitely uses the path - did you remember to set it for the rclone process?

**Comment by roisiano** [comment] 2023-06-14 14:02
> > So, the PATH is right, but rclone seems that does NOT use the path.
> 
> Rclone definitely uses the path - did you remember to set it for the rclone process?

Hello:

I suppose I don't need it because in the .service I use:

"
ExecStart=/storage/.config/rclone/rclone mount 
" 

And the services work fine with previous versions of rclone.

Kind regards

**Comment by roisiano** [comment] 2023-06-15 16:40
> Set the PATH something like this in your systemd config file
> 
> ```
> [Service]
> Environment=PATH=/.opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ```

**Thanks a lot!**

**I finally got it using CoreELEC:**
1) The latest version of rclone ( https://downloads.rclone.org/rclone-current-linux-arm64.zip ; at this moment, 1.62.2) "installed" (uncompressed binary) and with executable permissions:
/storage/.config/rclone/rclone

2) Installed fuse3-utils via entware:
**opkg install fuse3-utils**

It goes to:
/storage/.opt/bin/fusermount3

3) Created rclone "services" like this:

-------------

[Unit]
Description=RClone Gdrive
After=network-online.target
[service]
Type=simple
**Environment=PATH=/storage/.opt/bin:/.opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin**
ExecStartPre=/bin/mkdir -p /var/media/Gdrive
ExecStartPre=/bin/mkdir -p /storage/.config/rclone/logs
ExecStartPre=/bin/mkdir -p /storage/.config/rclone/cache
ExecStart=/storage/.config/rclone/rclone mount \
--log-file /storage/.config/rclone/logs/rclonemount.log \
--log-level INFO \
--allow-other \
--allow-non-empty \
--tpslimit 10 \
--tpslimit-burst 10 \
--dir-cache-time=48h \
--buffer-size=64M \
--attr-timeout=1s \
--vfs-read-chunk-size=64M \
--vfs-read-chunk-size-limit=2G \
--vfs-cache-max-age=5m\
--vfs-cache-mode=writes \
--cache-dir /storage/.config/rclone/cache \
--config=/storage/.config/rclone/rclone.conf \
Gdrive: /var/media/Gdrive
ExecStop=/bin/fusermount -uz /var/media/Gdrive
Restart=on-abort
[Install]
WantedBy=default.target

-------------

I needed to add:
/storage/.opt/bin:
in the PATH.

**And it works perfectly!**

Thanks again

**Comment by medram** [comment] 2023-06-16 21:03
I've had the same issue, and solved it by just updating `fuse3`:

 **Debian**
`apt-get install fuse3`

 **Ubuntu**
`apt-get install fuse3`

 **Arch Linux**
`pacman -S fuse3`

 **Kali Linux**
`apt-get install fuse3`

 **Fedora**
`dnf install fuse3`

 **Windows (WSL2)**
`sudo apt-get update sudo apt-get install fuse3`

Hope it fixes your issue too :D

**Comment by Evidlo** [comment] 2023-12-06 00:15
Shouldn't the latest release packages pull in `fuse3`?  For example `rclone-v1.65.0-linux-amd64.deb` doesn't mark `fuse3` as a dependency.

**Comment by Toasterme** [comment] 2024-02-29 03:35
rclone: Version "v1.65.2 on ubuntu 18 here.
Still have the error
Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH

Because i do not use the docker version, the fix still work 👍 
ln -s /bin/fusermount /bin/fusermount3

**Comment by damianharouff** [comment] 2024-08-25 14:29
This fixed a super-cryptic failure message.

```
root@vm2:~# mount /b2mount/
2024/08/25 07:28:02 ERROR : Daemon timed out. Failed to terminate daemon pid 605609: os: process already finished
2024/08/25 07:28:02 Fatal error: daemon exited with error code 1
root@vm2:~#
```

```
root@vm2:~# sudo ln -s /bin/fusermount /bin/fusermount3
root@vm2:~# mount /b2mount/
root@vm2:~#
```
