### ISSUE TITLE
`RCLONE_` prefixed environment variables for multi-valued options not working in v1.68.0

### ISSUE THREAD

**Issue by lewis-yeung** [rclone/rclone#8063] opened 2024-09-11 03:19 UTC
### What is the problem you are having with rclone?

Since v1.68.0, environment variables such as `RCLONE_INCLUDE_FROM` are no longer correctly parsed, while passing a file path via CLI flags (e.g., `--include-from`, without `RCLONE_INCLUDE_FROM` set) still works as expected. There must be a bug in the option parsing logic which affects any options that accept multiple values. I think one of the related commits is 3280b6b83c778419e0d682313d4b8015cb790ea9, but there should be more.

I confirm that `RCLONE_` prefixed environment variables work correctly in v1.67.0 and before.

### What is your rclone version (output from `rclone version`)

```
rclone v1.68.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.15.146.1-microsoft-standard-WSL2 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.1
- go/linking: dynamic
- go/tags: none
```

### The command you were trying to run

Set the value of environment variable `RCLONE_INCLUDE_FROM` to `/path/to/file`, and run just `rclone version -vv`.

### A log from the command with the `-vv` flag

```
2024/09/11 02:24:37 DEBUG : Setting  include_from="/path/to/file" from environment variable RCLONE_INCLUDE_FROM
2024/09/11 02:24:37 CRITICAL: Failed to load "filter" default values: failed to initialise "filter" options: couldn't parse config item "include_from" = "/path/to/file" as []string: parsing "/path/to/file" as []string failed: invalid character '/' looking for beginning of value
```

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2024-09-11 21:17
This appears to be broken for all variables of type `[]string`. This was broken in the recent config re-organisation

```
$ git grep '\[\]string.*config:'
cmd/mountlib/mount.go:  ExtraOptions       []string      `config:"option"`
cmd/mountlib/mount.go:  ExtraFlags         []string      `config:"fuse_flag"`
cmd/serve/dlna/dlnaflags/dlnaflags.go:  InterfaceNames   []string    `config:"interface"`
cmd/serve/sftp/sftp.go: HostKeys       []string `config:"key"`             // Paths to private host keys
fs/config.go:   CompareDest                []string          `config:"compare_dest"`
fs/config.go:   CopyDest                   []string          `config:"copy_dest"`
fs/config.go:   DisableFeatures            []string          `config:"disable"`
fs/config.go:   CaCert                     []string          `config:"ca_cert"`     // Client Side CA
fs/filter/filter.go:    ExcludeFile    []string      `config:"exclude_if_present"`
fs/filter/filter.go:    FilesFrom      []string      `config:"files_from"`
fs/filter/filter.go:    FilesFromRaw   []string      `config:"files_from_raw"`
fs/filter/rules.go:     FilterRule  []string `config:"filter"`
fs/filter/rules.go:     FilterFrom  []string `config:"filter_from"`
fs/filter/rules.go:     ExcludeRule []string `config:"exclude"`
fs/filter/rules.go:     ExcludeFrom []string `config:"exclude_from"`
fs/filter/rules.go:     IncludeRule []string `config:"include"`
fs/filter/rules.go:     IncludeFrom []string `config:"include_from"`
lib/http/server.go:     ListenAddr         []string      `config:"addr"`                 // Port to listen on
```

Can you have a go with this please? I think this should fix the problem


[v1.69.0-beta.8303.a5a85ab29.fix-8063-config](https://beta.rclone.org/branch/fix-8063-config/v1.69.0-beta.8303.a5a85ab29.fix-8063-config/) on branch [fix-8063-config](https://github.com/rclone/rclone/tree/fix-8063-config) (uploaded in 15-30 mins)

Explanation from the commit message
    
After the config re-organisation, the setting of stringArray config values (eg `--exclude` set with `RCLONE_EXCLUDE`) was broken and gave a message like this for `RCLONE_EXCLUDE=*.jpg`:
    
    Failed to load "filter" default values: failed to initialise "filter" options:
    couldn't parse config item "exclude" = "*.jpg" as []string: parsing "*.jpg" as []string failed:
    invalid character '/' looking for beginning of value
    
This was caused by the parser trying to parse the input string as a JSON value.
    
When the config was re-organised it was thought that the internal representation of stringArray values was not important as it was never visible externally, however this turned out not to be true.
    
A defined representation was chosen - a comma separated string and this was documented and tests were introduced in this patch.
    
This potentially introduces a very small backwards incompatibility. In rclone v1.67.0
    
    RCLONE_EXCLUDE=a,b
    
Would be interpreted as
    
    --exclude "a,b"
    
Whereas this new code will interpret it as
    
    --exclude "a" --exclude "b"
    
The benefit of being able to set multiple values with an environment variable was deemed to outweigh the very small backwards compatibility risk.
    
If a value with a `,` is needed, then use CSV escaping, eg
    
    RCLONE_EXCLUDE="a,b"
    
(Note this needs to have the quotes in so at the unix shell that would be
    
    RCLONE_EXCLUDE='"a,b"'

**Comment by lewis-yeung** [comment] 2024-09-12 01:13
> Can you have a go with this please? I think this should fix the problem
> 
> [v1.69.0-beta.8303.a5a85ab29.fix-8063-config](https://beta.rclone.org/branch/fix-8063-config/v1.69.0-beta.8303.a5a85ab29.fix-8063-config/) on branch [fix-8063-config](https://github.com/rclone/rclone/tree/fix-8063-config) (uploaded in 15-30 mins)

@ncw The link is broken...

**Comment by ncw** [comment] 2024-09-12 08:11
Sorry forgot to push it... Try this

[v1.69.0-beta.8303.a5a85ab29.fix-8063-config](https://beta.rclone.org/branch/fix-8063-config/v1.69.0-beta.8303.a5a85ab29.fix-8063-config/) on branch [fix-8063-config](https://github.com/rclone/rclone/tree/fix-8063-config) (uploaded in 15-30 mins)

**Comment by lewis-yeung** [comment] 2024-09-12 08:55
@ncw Confirmed to be fixed in the provided beta version. Thanks! Looking forward to its landing in the next release.

**Comment by ncw** [comment] 2024-09-13 14:53
Thanks for testing - I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.69 and in v1.68.1

**Closed** 2024-09-13 14:53 UTC
Labels: bug, Point Release Candidate

**Comment by manselmi** [comment] 2024-09-13 17:35
Thanks, this also fixed [my own issue](https://forum.rclone.org/t/rclone-ca-cert-env-var-crashes-rclone-rclone-master/46973).

**Comment by ncw** [comment] 2024-09-13 18:35
Thanks for that @manselmi 

Unfortunately I didn't notice that forum post as I could have fixed the problem before the release! Oh well.
