### ISSUE TITLE
rclone lsf with --include argument can not find the Correct file

### ISSUE THREAD

**Issue by qq122356** [rclone/rclone#7807] opened 2024-04-26 04:15 UTC
#### What is the problem you are having with rclone?
I use the following command to find a file/directory that includes the parameter --include "MS23071842*", but the output is different
rclone lsd obs://ssl-share/BAM/ --include "MS23071842*"  | tail -n 1
rclone lsf obs://ssl-share/BAM/ --include "MS23071842*"  | tail -n 1
rclone ls obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1
Among them, rclone ls can get the result I want, lsd and lsf get the result is incomprehensible

```shell
(base) [root@bitool workdir]# rclone lsd obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1                               
           0 2000-01-01 08:00:00        -1 PX20000006_c5f40b61dee64af99e9ab024d41b7fb8
(base) [root@bitool workdir]# 
(base) [root@bitool workdir]# rclone lsf obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1 
PX20000006_c5f40b61dee64af99e9ab024d41b7fb8/
(base) [root@bitool workdir]# 
(base) [root@bitool workdir]# rclone ls obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1 
  4191320 MS23071842_55065f885c27410c80e80e0869f9cdd8/MS23071842P1.recaled.bam.bai
``` 

#### What is your rclone version (output from `rclone version`)
v1.66.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos7.9 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
Huaweicloud OBS

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone lsd obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1
rclone lsf obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1
rclone ls obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by qq122356** [comment] 2024-04-26 04:18
It seems that the --include parameters after rclone lsd and lsf do not work

**Comment by qq122356** [comment] 2024-04-26 04:25
[rclone.log](https://github.com/rclone/rclone/files/15125315/rclone.log)

**Comment by qq122356** [comment] 2024-04-26 04:26
It seems that the --include parameters after rclone lsd and lsf do not work
[Uploading rclone.log…]()

**Comment by nielash** [comment] 2024-04-26 04:41
Have you tried adding `-R` ?

> Note that `ls` and `lsl` recurse by default - use `--max-depth 1` to stop the recursion.
The other list commands `lsd`,`lsf`,`lsjson` do not recurse by default - use `-R` to make them recurse.
https://rclone.org/commands/rclone_lsf/

**Comment by qq122356** [comment] 2024-04-26 05:18
I want to get the directory name that contains the keyword MS23071842 as a parameter in my shell program

I changed --include "MS23071842*" in the command to --include "MS23071842*/"

The result is correct

```shell
(base) [root@bitool workdir]# rclone lsf obs://ssl-share/BAM/ --include "MS23071842*" | tail -n 1 
PX20000006_c5f40b61dee64af99e9ab024d41b7fb8/
(base) [root@bitool workdir]# 
(base) [root@bitool workdir]# rclone lsf obs://ssl-share/BAM/ --include "MS23071842*/" | tail -n 1
MS23071842_55065f885c27410c80e80e0869f9cdd8/
```

**Comment by nielash** [comment] 2024-04-26 06:25
If I'm understanding correctly, I think this is a dupe of: 
- #5891

Note also:
```
*         matches any sequence of non-separator (/) characters
**        matches any sequence of characters including / separators
```
https://rclone.org/filtering/#patterns

**Comment by qq122356** [comment] 2024-04-26 08:17
Yes, this is indeed a recurring question
I don't understand is, why use, include "MS23071842 *" parameter, will show as a result, all - include seems to have no effect, and added / symbol is normal?

**Closed** 2024-04-26 08:29 UTC
