### ISSUE TITLE
Improperly set "Range" header when retrying file download from Dropbox

### ISSUE THREAD

**Issue by janvostry** [rclone/rclone#7759] opened 2024-04-12 08:09 UTC
#### What is the problem you are having with rclone?

Rclone consistently fails to sync huge files from Dropbox to Backblaze (wrapped in rclone crypt). When doing so the percentage counter goes way beyond 100% (170%+) and then it fails because of an invalid target size.
This is due to an improperly set "Range" header when retrying download from Dropbox, which results in re-downloading already processed data and inflating the target file - resulting in sync failure.
Looks like rclone does not update the start of the range when it was already set.

#### Correct behavior
- Line 205 Request 0xc0008fd320 - Rclone starts downloading the file from Dropbox (1st attempt)
- Line 5309 - Latest uploaded chunk before reading failure (chunk 202 size 96Mi offset 18.938Gi/67.258Gi - 20333985792 bytes sent)
- Line 5310 - A reading error occurred on offset 20766346465 due to an unexpected end-of-file
- Line 5311 Request 0xc0001b27e0 - Rclone starts downloading the file from Dropbox (2nd attempt), using range 20766346465-72200451298

#### Incorrect behavior
- Line 5632 - Latest uploaded chunk before reading failure (chunk 214 size 96Mi offset 20.062Gi/67.258Gi - 21541945344 bytes sent)
- Line 5633 - A reading error occurred on offset 21662613633 due to a timeout
- Line 5634 Request 0xc0008fca20 - Rclone starts downloading the file from Dropbox (3rd attempt), using a wrong range 20766346465-72200451298
- However correct request range from Dropbox should be 21662613633-72200451298
- Rclone is now reprocessing range 20766346465-21662613633 (854.74MB of data) from Dropbox which is already (or will be) on Backblaze

#### Incorrect behavior
- Line 9012 - Latest uploaded chunk before reading failure (chunk 342 size 96Mi offset 32.062Gi/67.258Gi - 34426847232 bytes sent)
- Line 9013 - A reading error occurred on offset 34544399248 due to a timeout
- Line 9046 Request 0xc0008fcea0 - Rclone starts downloading the file from Dropbox (4th attempt), using a wrong range 20766346465-72200451298
- However correct request range from Dropbox should be 34544399248-72200451298
- Rclone is now reprocessing range 20766346465-34544399248 (12.83GB of data) from Dropbox which is already (or will be) on Backblaze

#### What is your rclone version (output from `rclone version`)

rclone v1.66.0
- os/version: Microsoft Windows 11 Pro 23H2 (64 bit)
- os/kernel: 10.0.22631.3374 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 11 23H2 (22631.3374) 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Dropbox and Backblaze B2

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone sync DropboxArchive: BackblazeSecure:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[12042024_07464315.zip](https://github.com/rclone/rclone/files/14955929/12042024_07464315.zip)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2024-04-12 11:46
Thanks for reporting this, it does look like a bug. And thank you for your excellent log and analysis.

The problem seems to be in the re-open code

First failure

    Reopening on read failure after offset 20766346465 bytes: retry 1/10: unexpected EOF

Reopens with range request - looks good

    Range: bytes=20766346465-72200451298

Second failure

    Reopening on read failure after offset 21662613633 bytes: retry 2/10: ... i/o timeout

Reopens with incorrect range request - should clearly start from 21662613633 as per the log

    Range: bytes=20766346465-72200451298

Third failure

    Reopening on read failure after offset 34544399248 bytes: retry 3/10: ... i/o timeout

Re-opens with the same incorrect range request

    Range: bytes=20766346465-72200451298

I can reproduce this by patching the dropbox backend to return errors every 1000 bytes.

I've managed to fix this I think.

It turned out to be quite a subtle bug and I think it has caused a lot of issues with rclone downloading too much data over the years.

Please give this a go

[v1.67.0-beta.7869.a97c790b8.fix-7759-dropbox-retry](https://beta.rclone.org/branch/fix-7759-dropbox-retry/v1.67.0-beta.7869.a97c790b8.fix-7759-dropbox-retry/) on branch [fix-7759-dropbox-retry](https://github.com/rclone/rclone/tree/fix-7759-dropbox-retry) (uploaded in 15-30 mins)

**Comment by janvostry** [comment] 2024-04-12 16:26
I can confirm the bug is fixed: rclone now requests the correct ranges.
I also checked the hash on the Backblaze via the unpatched release of rclone and it matched with the hash that Dropbox has.

Thank you very much for the quick fix. 👍

**Comment by ncw** [comment] 2024-04-13 18:26
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.67 and I'll put it in the upcoming v1.66.1 also.

Thanks for tracking this down - I think this has been a problem in rclone for some time and I'm very glad to fix it.

**Closed** 2024-04-13 18:25 UTC
Labels: bug, Remote: Dropbox, IMPORTANT
