### ISSUE TITLE
How can I do the equivalent of “Add to My Drive” in rclone?

### ISSUE THREAD

**Issue by ihavenoid** [rclone/rclone#3807] opened 2019-12-15 06:11 UTC
I have many Gdrive publicly shared links. But every time, I have to open the link in web version of Gdrive and click on "add to my drive".
Doing this for lots of links is difficult and time taking.
Can a feature be added in rclone for this?
something like
**Rclone -addshare remote: public link**
or
**Rclone -addshare remote: folder ID**

Before creating this issue, I searched Rclone forum and found [this thread](https://forum.rclone.org/t/how-can-i-do-the-equivalent-of-add-to-my-drive-in-rclone/7513)

and in [this](https://forum.rclone.org/t/how-can-i-do-the-equivalent-of-add-to-my-drive-in-rclone/7513/8) post, moderator also said something like

**Rclone addobject remote:ID**

Hope i am able to make it understandable to everyone.
Hoping to have this feature real soon.
Thx in advance.

**Comment by ivandeex** [comment] 2021-04-12 11:47
Duplicate of #2871
Please subscribe to that ticket
Thank you for your request
This feature still waits for its maintainer

**Closed by ivandeex** 2021-04-12 11:47 UTC
Labels: Remote: Drive, enhancement
