### ISSUE TITLE
`--s3-profile` option does not work with `role_arn` when AWS_PROFILE does

### ISSUE THREAD

**Issue by aparthiban-turner** [rclone/rclone#5468] opened 2021-07-21 02:27 UTC
### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/unable-to-connect-to-s3-using-s3-profile-with-role-arn/25347

#### What is the problem you are having with rclone?
I believe this is a bug introduced with v1.55.x. We are currently using rclone v1.53.3 and trying to upgrade to latest version v1.55.1. During smoke test, we noticed that below feature has stopped working in v1.55.1. 

`~/.aws/credentials:`
```
[test-profile-1]
role_arn = arn:aws:iam::00000000000:role/test-role
source_profile = default

[test-profile-2]
aws_access_key_id = XXXXXXXXXXXX
aws_secret_access_key = YYYYYYYYY
```

`~/.rclone.conf:`

```
[s3]
type = s3
provider = AWS
env_auth = true
region = us-east-1
acl = private
```

Here **test-profile-1** is based on `role_arn`, whereas **test-profile-2** is based on `access_key_id` and `secret_access_key`. When trying to connect using these profiles, below are the status.
```
aws s3 ls s3://test-logs/2021-07-13/ --profile test-profile-1 (Works !)
rclone ls s3://test-logs/2021-07-13/ --s3-profile test-profile-1 (Fails !!!)

aws s3 ls s3://test-logs/2021-07-13/ --profile test-profile-2 (Works !)
rclone ls s3://test-logs/2021-07-13/ --s3-profile test-profile-2 (Works !)
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.55.1

os/type: linux
os/arch: amd64
go/version: go1.16.3
go/linking: static
go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Amazon Linux 2

#### Which cloud storage system are you using? (e.g. Google Drive)
S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone ls s3://test-logs/2021-07-13/ --s3-profile test-profile-1`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2021/07/14 14:13:23 DEBUG : Using config file from "/home/ec2-user/.config/rclone/rclone.conf"
2021/07/14 14:13:23 DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone" "ls" "s3://test-logs/2021-07-13/" "--s3-profile" "testlogs" "-vv"]
2021/07/14 14:13:23 DEBUG : Creating backend with remote "s3://test-logs/2021-07-13/"
2021/07/14 14:13:23 DEBUG : s3: detected overridden config - adding "{jb+DA}" suffix to name
2021/07/14 14:13:24 DEBUG : fs cache: renaming cache item "s3://test-logs/2021-07-13/" to be canonical "s3{jb+DA}:test-logs/2021-07-13"
2021/07/14 14:13:24 DEBUG : 4 go routines active
2021/07/14 14:13:24 Failed to ls: AccessDenied: Access Denied
        status code: 403, request id: 8TVCK7CVEXPF781T, host id: wEo+4KMswde6lETjLs6QnEbRpRF/+8dyhsRxBnTo3nNXgYRrJ91BDkrmuBOuid8vy0sv5UYjY5s=
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2021-07-21 09:47
Can you try this with the just released v1.56.0 please? I think we may have fixed this already

**Comment by aparthiban-turner** [comment] 2021-07-21 16:01
@ncw After upgrading to latest version, getting different error as below for same rclone command. 

`aws s3 ls s3://test-logs/2021-07-13/ --profile test-profile-1` (Works !)
`rclone ls s3://test-logs/2021-07-13/ --s3-profile test-profile-1` (Fails !!!)

```
2021/07/21 11:56:44 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "ls" "s3://test-logs/2021-07-13/" "--s3-profile" "test-profile-1" "-vv"]
2021/07/21 11:56:44 DEBUG : Creating backend with remote "s3://test-logs/2021-07-13/"
2021/07/21 11:56:44 DEBUG : Using config file from "/home/ec2-user/.config/rclone/rclone.conf"
2021/07/21 11:56:44 DEBUG : s3: detected overridden config - adding "{jb-DA}" suffix to name
2021/07/21 11:56:44 DEBUG : fs cache: renaming cache item "s3://test-logs/2021-07-13/" to be canonical "s3{jb-DA}:test-logs/2021-07-13/"
2021/07/21 11:56:50 DEBUG : 4 go routines active
2021/07/21 11:56:50 Failed to ls: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by ncw** [comment] 2021-07-27 14:49
The profiles are definitely working, I tested that locally

    rclone lsf :s3,env_auth,profile=test:

So it must be the arn role as you suggested.

That is parsed by the AWS SDK so either there is a bug in that (possible) or rclone isn't calling the right bits of the SDK (also possible).

I suspect that it was probably this change that broke it for you e618ea83dd3e539b53d2e60b49336e27347b56f8

Can you verify that?

I'm afraid I'm out of my depth now with AWS authentication so I really need some help here!

Thanks

**Comment by aparthiban-turner** [comment] 2021-08-10 01:23
No luck. I am still getting AccessDenied error, as similar to the one I provided in issue description.

**Comment by ncw** [comment] 2021-08-10 17:07
I did a bit of searching... Try

    export AWS_SDK_LOAD_CONFIG=1

and see if that makes it work?

**Comment by aparthiban-turner** [comment] 2021-08-10 18:14
Tried above suggestion with latest version and getting below error.
```
2021/08/10 14:11:03 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "ls" "-vvv" "s3://test-logs/2021-07-13/" "--s3-profile" "test-profile-1"]
2021/08/10 14:11:03 DEBUG : Creating backend with remote "s3://test-logs/2021-07-13/"
2021/08/10 14:11:03 DEBUG : Using config file from "/Users/aparthiban/.config/rclone/rclone.conf"
2021/08/10 14:11:03 DEBUG : s3: detected overridden config - adding "{jb-DA}" suffix to name
2021/08/10 14:11:03 DEBUG : fs cache: renaming cache item "s3://test-logs/2021-07-13/" to be canonical "s3{jb-DA}:test-logs/2021-07-13"
2021/08/10 14:11:07 DEBUG : 4 go routines active
2021/08/10 14:11:07 Failed to ls: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by ncw** [comment] 2021-08-11 10:49
Can you try this binary please?

I reverted e618ea8 to see if that was the problem.

[v1.57.0-beta.5614.98d494411.fix-5468-s3-auth](https://beta.rclone.org/branch/fix-5468-s3-auth/v1.57.0-beta.5614.98d494411.fix-5468-s3-auth/) on branch [fix-5468-s3-auth](https://github.com/rclone/rclone/tree/fix-5468-s3-auth) (uploaded in 15-30 mins)

**Comment by aparthiban-turner** [comment] 2021-08-11 17:56
I guess the binary file is corrupted. When downloading through `curl` getting below error.
```
> curl -O https://beta.rclone.org/branch/fix-5468-s3-auth/v1.57.0-beta.5614.98d494411.fix-5468-s3-auth/rclone-v1.57.0-beta.5614.98d494411.fix-5468-s3-auth-linux-amd64.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 38 14.0M   38 5572k    0     0   443k      0  0:00:32  0:00:12  0:00:20  1022
curl: (18) transfer closed with 9049702 bytes remaining to read
```
I am also not able to download it manually, since it downloads only partially (~4MB), where actual file size is ~14MB.  

Can you please advise if I am doing anything incorrect ?

**Comment by aparthiban-turner** [comment] 2021-08-11 19:16
With the above mentioned binary, I am getting different error as below. I also tried setting `export AWS_SDK_LOAD_CONFIG=1`, but no luck. 

```
airflow@a26841ef9be8:~$ rclone lsd -vvv s3://test-logs/2021-07-13/ --s3-profile test-profile-1
2021/08/11 15:12:09 DEBUG : rclone: Version "v1.57.0-beta.5614.98d494411.fix-5468-s3-auth" starting with parameters ["rclone" "lsd" "-vvv" "s3://test-logs/2021-07-13/" "--s3-profile" "test-profile-1"]
2021/08/11 15:12:09 DEBUG : Creating backend with remote "s3://test-logs/2021-07-13/"
2021/08/11 15:12:09 DEBUG : Using config file from "/usr/local/airflow/.config/rclone/rclone.conf"
2021/08/11 15:12:09 DEBUG : s3: detected overridden config - adding "{jb-DA}" suffix to name
2021/08/11 15:12:09 DEBUG : fs cache: renaming cache item "s3://test-logs/2021-07-13/" to be canonical "s3{jb-DA}:test-logs/2021-07-13"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12ecb42]

goroutine 83 [running]:
github.com/aws/aws-sdk-go/aws/credentials/stscreds.(*WebIdentityRoleProvider).RetrieveWithContext(0xc0006ff170, 0x21ba568, 0xc000042090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/aws/aws-sdk-go@v1.38.22/aws/credentials/stscreds/web_identity_provider.go:111 +0x62
github.com/aws/aws-sdk-go/aws/credentials/stscreds.(*WebIdentityRoleProvider).Retrieve(0xc0006ff170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f2372b82390, ...)
        github.com/aws/aws-sdk-go@v1.38.22/aws/credentials/stscreds/web_identity_provider.go:104 +0x96
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc000614c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/aws/aws-sdk-go@v1.38.22/aws/credentials/chain_provider.go:75 +0xfe
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).singleRetrieve(0xc0003ce600, 0x21ba798, 0xc00049f530, 0x0, 0x0, 0x0, 0x0)
        github.com/aws/aws-sdk-go@v1.38.22/aws/credentials/credentials.go:279 +0x551
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).GetWithContext.func1(0x0, 0x0, 0x0, 0x0)
        github.com/aws/aws-sdk-go@v1.38.22/aws/credentials/credentials.go:255 +0x8a
github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).doCall(0xc0003ce600, 0xc0001323c0, 0x0, 0x0, 0xc00011e7c0)
        github.com/aws/aws-sdk-go@v1.38.22/internal/sync/singleflight/singleflight.go:97 +0x2e
created by github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).DoChan
        github.com/aws/aws-sdk-go@v1.38.22/internal/sync/singleflight/singleflight.go:90 +0x2cc
```

**Comment by ncw** [comment] 2021-08-13 16:06
That is kind of what I was expecting - that crash is the reason we took that code out!

Would it be possible for you to do a `git bisect` to find the commit that broke the code?

Or alternatively give some simple instructions on how to create this part of your config `role_arn = arn:aws:iam::00000000000:role/test-role` so I can reproduce the config locally? Ideally some AWS CLI commands I can run.

Thanks

**Comment by aparthiban-turner** [comment] 2021-08-18 02:45
@ncw You can refer this documentation https://docs.aws.amazon.com/codedeploy/latest/userguide/getting-started-create-service-role.html

**Comment by ncw** [comment] 2021-08-18 21:01
I created an arn which allows S3 access from EC2 and tried it out on an EC2 server. I either got permission denied

> An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::xxxx:user/xxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxx:role/s3-read-only

Or I it worked if I assigned the ARN direct to the EC2 instance. But then it worked without the config `~/.aws/credentials` file.

So I guess to progress further I need to fix that error, but I couldn't work out how to do that - assigning the ARN to the ec2 must be the wrong thing to do, but the user quoted above **is** the ec2 instance.

How are you using the config?

**Comment by aparthiban-turner** [comment] 2021-08-18 21:24
1. Create a role with arn `arn:aws:iam::1234568890:role/test-role`, which has access to specific s3 bucket/path - `s3://test-logs/2021-07-13/`
2. Create a policy with below permissions and assign it to the role (should be different) linked to an EC2 instance.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::1234568890:role/test-role"
        },
        {
            "Sid": "AllowAccountLevelS3Actions",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": "*"
        },
   ]
}
```
3. Create config in EC2 instance as below.
```
> ~/.aws/credentials

[test-profile-1]
role_arn =arn:aws:iam::1234568890:role/test-role
source_profile = EC2InstanceMetadata
```
4. Try accessing the s3 bucket using AWS config.
```
aws s3 ls s3://test-logs/2021-07-13/ --profile test-profile-1
rclone ls s3://test-logs/2021-07-13/ --s3-profile test-profile-1
```

**Comment by ncw** [comment] 2021-08-21 15:57
I'll try to find some time for the above.

In the mean time, could you try

https://beta.rclone.org/v1.57.0-beta.5642.6a9ef27b0/

This has the latest AWS SDK built in which might make a difference.

**Comment by aparthiban-turner** [comment] 2021-08-23 01:10
Getting same error with above beta version as similar to latest version (v1.56.0).
```
> rclone ls -vvv s3://test-logs/2021-07-13/ --s3-profile test-profile-1

2021/08/22 21:06:24 DEBUG : rclone: Version "v1.57.0-beta.5642.6a9ef27b0" starting with parameters ["rclone" "ls" "-vvv" "s3://test-logs/2021-07-13/" "--s3-profile" "test-profile-1"]
2021/08/22 21:06:24 DEBUG : Creating backend with remote "s3://test-logs/2021-07-13/"
2021/08/22 21:06:24 DEBUG : Using config file from "/usr/local/airflow/.config/rclone/rclone.conf"
2021/08/22 21:06:24 DEBUG : s3: detected overridden config - adding "{jb-DA}" suffix to name
2021/08/22 21:06:24 DEBUG : fs cache: renaming cache item "s3://test-logs/2021-07-13/" to be canonical "s3{jb-DA}:test-logs/2021-07-13"
2021/08/22 21:06:26 DEBUG : 2 go routines active
2021/08/22 21:06:26 Failed to ls: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by tonyreina** [comment] 2021-08-30 23:51
I'm having this issue as well with specifying roles. AWS CLI works fine.

**Comment by stefanoverna** [comment] 2021-09-13 08:24
Same issue here too!

**Comment by ncw** [comment] 2021-09-13 11:01
@aparthiban-turner I had a go with your new instructions.

Assigning the role to the EC2 instance seems to make both AWS cli and rclone work without specifying the profile, so I must be doing something wrong again.

You wrote:
> 1. Create a role with arn `arn:aws:iam::1234568890:role/test-role`, which has access to specific s3 bucket/path - `s3://test-logs/2021-07-13/`

Can you specify this step in more detail please? I only figured out how to create a role with full or read only access to s3. It basically says give all stuff in EC2 read only access to S3.

> 2. Create a policy with below permissions and assign it to the role (should be different) linked to an EC2 instance.

I don't think I understand what to do with this policy. Do I add it to the role created in 1? Or do I create a new role and assign it to that?

@tonyreina @stefanoverna care to add some step by step instructions for configuring an EC2 instance so I can replicate the problem? I know almost nothing about AWS iam/roles/arns!

**Comment by aparthiban-turner** [comment] 2021-10-01 16:24
@ncw My bad. I completely forgot to respond to your questions. Below are the detailed steps that will replace step 1 & 2 above.

Use case: Let's assume that we are sharing files to other teams through a bucket `s3://to-others`, whereas they don't have access to any of our buckets unless they use our `role_arn` or any form of credentials.

Let's create a role `test-role` on our side which has access only to bucket `s3://to-others`

1. Create a json file `policy.json` with below content. This policy allows access to s3 bucket `s3://to-others`
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::to-others",
                "arn:aws:s3:::to-others/*"
            ]
        }
    ]
}
``` 
2. Create a role `test-role` and attach above policy to it.
```
aws iam create-role --role-name test-role --assume-role-policy-document <json-file-path>/policy.json
```

The other team need to follow below steps in order to access bucket `s3://to-others` from their EC2 Instance. 

3. Create a policy using below permissions. 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::1234568890:role/test-role"
        },
        {
            "Sid": "AllowAccountLevelS3Actions",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": "*"
        },
   ]
} 
```
4. There's always been a default role attached to an EC2 instance. Let's call it as `ec2-default-role`. Attach above policy to `ec2-default-role`
5. Create below config in EC2 instance as below.
```
> ~/.aws/credentials

[test-profile-1]
role_arn =arn:aws:iam::1234568890:role/test-role
source_profile = EC2InstanceMetadata
```

4. Try accessing the s3 bucket using AWS config.
```
aws s3 ls s3://to-others --profile test-profile-1
rclone ls s3://to-others --s3-profile test-profile-1
```

**Comment by ncw** [comment] 2021-10-30 10:55
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.57

**Closed** 2021-10-30 10:55 UTC
Labels: bug, Remote: S3

**Comment by aparthiban-turner** [comment] 2021-11-01 00:32
@ncw When can we expect the release v15.7?

**Comment by ncw** [comment] 2021-11-02 15:36
It was released yesterday :-)

**Comment by rpattcorner** [comment] 2022-09-08 18:51
Appears to be failing with a hang in latest rclone v1.60.0-beta.6422.85eb9776b

This works:
```
$ aws s3 cp ~/testbed/testfile s3://x20220908-rpc-1 --profile dr_systems_profile
upload: testbed/testfile to s3://x20220908-rpc-1/testfile  
```
But rclone fails using the same profile:
```
$ rclone copy  ~/testbed/testfile s3-standard:x20220908-rpc-1
2022/09/08 14:43:12 ERROR : Attempt 1/3 failed with 1 errors and: Forbidden: Forbidden
        status code: 403, request id: XXX, host id: XXX
```

rclone version is recent:
```
rclone v1.58.0-beta.5880.2e99232a0.fix-b2-acl
- os/version: centos 7.9.2009 (64 bit)
```

rclone configuration is simple:
```
rclone v1.60.0-beta.6422.85eb9776b
- os/version: centos 7.9.2009 (64 bit)
```
And the profile entry is unchanged between AWS CLI and rclone -- looks like this:
```
# dr attempt
[dr_systems_profile]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/SOMEGOODROLE
credential_source = Environment
```

**Comment by ncw** [comment] 2022-09-09 11:01
@rpattcorner 

Assuming `bucket` is the name of your bucket, try removing it from the endpoint

> endpoint = https://bucket.vpce-MYVPCE.s3.us-east-1.vpce.amazonaws.com

If that doesn't fix it, please make a new issue - thanks.

**Comment by rpattcorner** [comment] 2022-09-14 14:04
Thanks.  The `bucket` portion of the endpoint is actually part of the endpoint spec, as illustrated in the [examples here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html).  The conflict does seem to be between endpoint handling and profile though!  I'll open a new issue.
