### ISSUE TITLE
Cache does not work with empty directories

### ISSUE THREAD

**Issue by zotune** [rclone/rclone#3077] opened 2019-03-27 11:20 UTC
#### Output of `1.46`
See attachment `aftercache2.txt`
[aftercache2.txt](https://github.com/ncw/rclone/files/3012860/aftercache2.txt)
[cache2.txt](https://github.com/ncw/rclone/files/3012861/cache2.txt)

#### Describe the issue
Cache does not work with empty directories, it causes rclone to use longer than without Cache:
https://forum.rclone.org/t/speed-up-include-with-cache-or-similar/9197/33

Calisro's test:

> Just for statistics. I’ve deleted all 200 empty directories in my case. and here are results.
> 
> cache:
> notebook2:~/Downloads$ time rclone ls robgsc-cryptp:Media/Videos/Series -vv --log-file=before.out --cache-info-age=99y >/dev/null
> 
> real	0m2.561s
> user	0m3.128s
> sys	0m0.044s
> 
> direct:
> notebook2:~/Downloads$ time rclone ls robgs-cryptp:Media/Videos/Series -vv --log-file=before.out --cache-info-age=99y >/dev/null
> 
> real	0m21.720s
> user	0m2.812s
> sys	0m0.184s
> 
> Original with empty directories and from cache (also had more checkers and workers btw)
> 
> time rclone ls robgsc-cryptp:Media/Videos/Series -vv --log-file=direct.out --cache-info-age=99y --cache-workers 20 --checkers 20
> 
> |real|1m19.529s|
> |user|0m3.720s|
> |sys|0m0.284s|

**Comment by ncw** [comment] 2019-03-27 13:53
This is a consequence of this bit of code

https://github.com/ncw/rclone/blob/6fb1c8f51cec3f5d00d2f3da027dae478bca4bf1/backend/cache/cache.go#L978-L979

Cache doesn't have a clear distinction between
- directories which haven't been cached yet
- empty directories

**Comment by zotune** [comment] 2019-03-29 14:45
Once there is a beta out, I am happy to test.

**Comment by calisro** [comment] 2019-03-29 16:53
If that bit is removed, wouldn't the code still work correctly?

```
	// search for cached dir entries and validate them
	entries, err = f.cache.GetDirEntries(cd)
	if err != nil {
		fs.Debugf(dir, "list: error: %v", err)
	} else if time.Now().After(cd.CacheTs.Add(time.Duration(f.opt.InfoAge))) {
		fs.Debugf(dir, "list: cold listing: %v", cd.CacheTs)
	} else {
		fs.Debugf(dir, "list: warm %v from cache for: %v, expiring on: %v", len(entries), cd.abs(), cd.CacheTs.Add(time.Duration(f.opt.InfoAge)))
		fs.Debugf(dir, "list: cached entries: %v", entries)
		return entries, nil
	}

```

Since rclone will just assume they are warm and cache them like any other non-empty directory?  They would still be flagged as cold once the cache time expired.  Or am I reading this wrong?

**Comment by ncw** [comment] 2019-03-29 16:55
> If that bit is removed, wouldn't the code still work correctly?

I think so, fancy giving it a go?

My only concern is are directories put into the db as empty when they are first seen to be filled in later?

I'm afraid I don't know the cache code well enough to answer that question right now.

However a bit of experimentation would discover whether it works properly or not.

**Comment by calisro** [comment] 2019-03-29 16:58
I'll give it a try.  Looking through the code I *think* it will run through and cache them and then expire them just like a directory that had data.  But i'll test some scenarios and see.

**Comment by calisro** [comment] 2019-04-01 19:01
Well.  The code would need to differentiate between empty and and non-empty.  The cached entries are added by copying the original listing from the source and the source doesn't know ahead of time (before descending into the directory how many files are in that directory.  If this was to be fixed in the cache code then it would need to descend into a directory before caching it which would require an extra transaction or to list the directory (and grab the length) as its recursing and then go back and update that entry in the DB with the directory counts.  

I was looking at using the existing 'item' counts to store that data rather than the "-1" which is stored now rather but I dont see how to get at that data without descending or coming back after and updating the entry or delaying the write to the DB till after which looks problematic.

**Comment by zotune** [comment] 2019-08-15 12:45
any news on this? i am happy to test any beta builds.

**Comment by ivandeex** [comment] 2021-02-09 18:30
@zotune @calisro
Cache backend was deprecated in favor of VFS in rclone and is no more supported.
Feel free to reopen against VFS in rclone 1.54 if you can reproduce.
Thanks.
cc @ncw

**Closed by ivandeex** 2021-02-09 18:30 UTC
Labels: Remote: Cache, bug
