### ISSUE TITLE
Rclone sync, detail is missing for deleted directories

### ISSUE THREAD

**Issue by Sephiburp** [rclone/rclone#5281] opened 2021-04-27 10:45 UTC
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/rclone-sync-detail-is-missing-for-deleted-directories/23793/2

#### What is your current rclone version (output from `rclone version`)?
rclone v1.56.0-DEV

#### What problem are you are trying to solve?
Get the info of which directories were deleted.
Command used: rclone sync --update --log-level=INFO "myGoogleDrive:myDir" "/media/myDir"

#### How do you think rclone should be changed to solve that?
"_This log needs promoting to fs.Infof_" (see forum)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2021-04-27 14:33
Here is the log in question.

https://github.com/rclone/rclone/blob/0537791d14675e9c66a2a237680f6403cba4e3f1/fs/operations/operations.go#L1046

**Comment by AyushRawal** [comment] 2021-09-11 06:20
@ncw Is this the only line that needs to be changed?

**Comment by ncw** [comment] 2021-09-13 10:12
@AyushRawal I think so

**Comment by AyushRawal** [comment] 2021-09-14 01:44
@ncw I didn't saw it before! This has already been fixed.

https://github.com/rclone/rclone/blob/18f39291863e3d57dad84d306771716fae0cf125/fs/operations/operations.go#L1098-L1105

**Comment by ncw** [comment] 2021-09-15 14:11
So it was by 675548070d50e4c30cca3d983df303860947c64a for #5464 which is a duplicate of this issue.

Sorry about that!

I'll close this issue now.

**Closed by ncw** 2021-09-15 14:11 UTC
Labels: enhancement, good first issue
