### ISSUE TITLE
Rclone mangling UTF-8 filenames (normalisation?)

### ISSUE THREAD

**Issue by ApexWeed** [rclone/rclone#1472] opened 2017-06-11 01:55 UTC
I recently migrated servers using a backup stored on an encrypted google drive (as the entire thing doesn't fit on the old server). I noticed some programs weren't finding files and rsyncing the files off the old server to the new one resulted in a different file name that was then picked up by the programs. Further to this I noticed the only files this occurred on had accents or dakuten. I'll admit the original filenames are probably _technically wrong_ but rclone needs to be using the actual filename not just what it thinks is better.

I thought it was an issue with crypt remotes but the same thing occurs regardless of whether it's Google Drive or Google Drive via crypt - likely ruling out it being a remote issue and instead being in how rclone handles character encoding.

A basic example of what happens is as follows ([tar of the offending filenames](https://helifreak.club/mangle.tar)):

```
'10 - Polonaise in Ab major Op 53 Héroique.flac'
'10 - Polonaise in Ab major Op 53 Héroique.flac'
```

These two lines will likely render the same in the browser, use a hex editor or similar to see the actual encoding. 

The first file is uploaded to a crypt remote with the correct filename, it is then renamed to have _bak at the end, the file is then downloaded back from the crypt remote, the _bak is then removed. There are now two files there - at least on Arch ls output shows the first line has the ' higher above the e than the second.

Should be affecting under 100 of my files so I can rsync them across but I can't delete anything off the new server before confirming whether the filenames themselves are mangled (requiring a reupload of 8 TiB of data, fun) or if it's just occurring during download.

It's also occurring with the following filenames (and many others) if it helps in diagnosis:

```
04 - Wormlust - Sex Augu, Tólf Stjörnur.flac on ó and ö
07 - Nyiþ - Visni Þitt Hold Svo Betur Megi Hæfa Þeim Hug Sem Það Hýsir.flac on ý
09 - Misþyrming - Ég Byggði Dyr í Eyðimökinni.flac on ö
13 ワンダーランド.flac on ダ and ド
```

I think local filesystem is also ruled out, centOS machine is running ext4, Arch is running ZFS, Arch on WSL is NTFS with its wrapper.

> What is your rclone version (eg output from `rclone -V`)

Tested on rclone v1.35, rclone v1.36, and rclone v1.36-170-g2ca477c5β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

centOS 7.2 64 bit, Arch 64 bit, Arch 64 bit via WSL

> Which cloud storage system are you using? (eg Google Drive)

Google Drive via crypt

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy test gdE:test
then
rclone copy gdE:test test

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2017/06/10 23:35:06 DEBUG : rclone: Version "v1.36-170-g2ca477c5β" starting with parameters ["rclone" "copy" "-vv" "." "gdE:test"]
2017/06/10 23:35:08 INFO  : Encrypted drive 'gdE:test': Modify window is 1ms
2017/06/10 23:35:08 DEBUG : Google drive root 'enc/up8n5n0e7087l8sppbee6fprnk': Reading ""
2017/06/10 23:35:09 DEBUG : Google drive root 'enc/up8n5n0e7087l8sppbee6fprnk': Finished reading ""
2017/06/10 23:35:09 INFO  : Encrypted drive 'gdE:test': Waiting for checks to finish
2017/06/10 23:35:09 INFO  : Encrypted drive 'gdE:test': Waiting for transfers to finish
2017/06/10 23:35:10 INFO  : 10 - Polonaise in Ab major Op 53 Héroique.flac: Copied (new)
2017/06/10 23:35:10 INFO  :
Transferred:     15 Bytes (4 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        3.4s
2017/06/10 23:35:10 DEBUG : Go routines at exit 5
2017/06/10 23:35:10 DEBUG : rclone: Version "v1.36-170-g2ca477c5β" finishing with parameters ["rclone" "copy" "-vv" "." "gdE:test"]
```
then
```
2017/06/10 23:36:38 DEBUG : rclone: Version "v1.36-170-g2ca477c5β" starting with parameters ["rclone" "copy" "-vv" "gdE:test" "."]
2017/06/10 23:36:40 INFO  : Local file system at /home/helifreak/test: Modify window is 1ms
2017/06/10 23:36:40 DEBUG : Google drive root 'enc/up8n5n0e7087l8sppbee6fprnk': Reading ""
2017/06/10 23:36:40 DEBUG : Google drive root 'enc/up8n5n0e7087l8sppbee6fprnk': Finished reading ""
2017/06/10 23:36:40 INFO  : Local file system at /home/helifreak/test: Waiting for checks to finish
2017/06/10 23:36:40 INFO  : Local file system at /home/helifreak/test: Waiting for transfers to finish
2017/06/10 23:36:40 INFO  : 10 - Polonaise in Ab major Op 53 Héroique.flac: Copied (new)
2017/06/10 23:36:40 INFO  :
Transferred:     15 Bytes (6 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        2.4s
2017/06/10 23:36:40 DEBUG : Go routines at exit 7
2017/06/10 23:36:40 DEBUG : rclone: Version "v1.36-170-g2ca477c5β" finishing with parameters ["rclone" "copy" "-vv" "gdE:test" "."]
```

May be related to #1431, #1457, or #1212.

**Comment by ncw** [comment] 2017-06-11 10:44
This is almost certainly caused by OS X and its strange decision to store denormalized UTF-8 file names.

You didn't mention OS X in the above, but I suspect that these file names have been through an OS X machine at some point.  The `b` file below has the e acute character in, whereas the `a` file has e then the acute accent combining character which is exactly what OS X does.  So if you store `b` on an OS X file system, it will read back as `a` which has caused a lot of problems with rclone!

```
$ python
>>> a=u"10 - Polonaise in Ab major Op 53 Héroique.flac"
>>> b=u"10 - Polonaise in Ab major Op 53 Héroique.flac"
>>> a == b
False
>>> a
u'10 - Polonaise in Ab major Op 53 He\u0301roique.flac'
>>> b
u'10 - Polonaise in Ab major Op 53 H\xe9roique.flac'
>>> 
```

You can try this flag in the latest beta `--local-no-unicode-normalization` which should help.

I'm beginning to think I've made a mistake normalizing the file names, what I should be doing is normalizing them in the sync routine when rclone is comparing source and destination directory, rather than normalizing them all the time.

**Comment by ApexWeed** [comment] 2017-06-11 11:01
Yeah that flag does the trick. Taking another look at the CD rip logs (XLD) it seems you're right about OS X too.

I assume that it will require a reupload to get the filenames back to how they are named on disk?

**Comment by ncw** [comment] 2017-06-11 22:05
If you use `--track-renames` then rclone will rename stuff for you rather than copying it.  The source and dest need a compatible hash which may not be available though.

**Comment by ncw** [comment] 2017-06-11 22:09
I've put the changing the place the normalization is done as an issue here #1477

**Comment by ncw** [comment] 2020-01-23 17:21
The normalization has been extensively re-worked since this issue was opened so I'm going to close it now.

**Closed by ncw** 2020-01-23 17:21 UTC
