### ISSUE TITLE
NFS Mount Input/Output error on create files

### ISSUE THREAD

**Issue by mcadam** [rclone/rclone#2115] opened 2018-03-05 18:12 UTC
#### What is the problem you are having with rclone?

Hi, I have been playing around rclone + NFS on top of it. I managed to mount, get the files listed and everything, I can delete files, read files fine, but I can't create a new file.

Error I am getting:

$ touch test
touch: cannot touch 'test': Input/output error

#### What is your rclone version (eg output from `rclone -V`)

Replicated in both stable release and beta release:

• ./rclone --version
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

• rclone --version
rclone v1.39-171-g1383df4fβ
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 64 bits 

####  Which cloud storage system are you using? (eg Google Drive)

Google drive with a Rclone Cache on top of it

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
[Unit]
Description=Mount GDrive using rclone
After=network-online.target

[Service]
Type=notify
User=root
ExecStartPre=-/bin/mkdir /mnt/test
ExecStart=/home/user/rclone-tmp/rclone mount \
                          gdrivecache: /mnt/test \
                          --config /home/user/.rclone.conf \
                          --allow-other \
                          --cache-db-purge \
                          --cache-writes \
                          --cache-db-path=/tmp/rclone-test/cache-backend \
                          --gid=100 \
                          --uid=1000 \
                          --umask=002 \
                          -vv
ExecStop=/bin/fusermount -u /mnt/test
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

So if I try to touch a "test" file from the mount directly I successfully get this:

```
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : /: Lookup: name="test"
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : /: Lookup: name="test"
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : /: Create: name="test"
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : test: Open: flags=O_RDWR|O_CREATE
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : test: >Open: fd=test (w), err=<nil>
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : /: >Create: node=test, handle=&{test (w)}, err=<nil>
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : test: Attr:
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : test: >Attr: a=valid=1m0s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : &{test (w)}: Flush:
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : test: WriteFileHandle.Flush ignoring flush on unwritten handle
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : &{test (w)}: >Flush: err=<nil>
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : &{test (w)}: Release:
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : test: WriteFileHandle.Release closing
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : gdrivecache:: File to upload is small (0 bytes), uploading instead of streaming
Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 INFO  : gdrivecache:: put data at 'test'
Mar 05 17:55:14 sbx1 rclone[880]: 2018/03/05 17:55:14 DEBUG : : cache: expired
Mar 05 17:55:14 sbx1 rclone[880]: 2018/03/05 17:55:14 DEBUG : test: object hash cached: d41d8cd98f00b204e9800998ecf8427e
Mar 05 17:55:14 sbx1 rclone[880]: 2018/03/05 17:55:14 INFO  : test: Copied (new)
Mar 05 17:55:14 sbx1 rclone[880]: 2018/03/05 17:55:14 DEBUG : &{test (w)}: >Release: err=<nil>
Mar 05 17:55:14 sbx1 rclone[880]: 2018/03/05 17:55:14 INFO  : cache: deleted (0) chunks
```

When I do the touch from the NFS mount I get this:

```
Mar 05 17:54:45 sbx1 rclone[880]: 2018/03/05 17:54:45 DEBUG : /: Lookup: name="test"
Mar 05 17:54:45 sbx1 rclone[880]: 2018/03/05 17:54:45 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
Mar 05 17:54:45 sbx1 rclone[880]: 2018/03/05 17:54:45 DEBUG : /: Lookup: name="test"
Mar 05 17:54:45 sbx1 rclone[880]: 2018/03/05 17:54:45 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
```

And thats it.

So it does the same, look for the file, don't find it but then don't try to create it? Like it does on the main file system.

Let me know how I can help to test further.

**Comment by ncw** [comment] 2018-03-05 20:51
Can you give this a go with [the latest beta](https://beta.rclone.org)?  Quite a lot of fixes went into the VFS layer in the last 30 commits! (https://beta.rclone.org has been serving old versions for a few weeks, that is part of what the VFS fixes are for!).

Also can you try it without the cache backend so we can work out whether the problem is in the cache backend or rclone mount.

> touch: cannot touch 'test': Input/output error

If you get that then I would expect to see an ERROR in the rclone log...

A quick bit of research indicates exporting FUSE filesystems via NFS might be tricky - what parameters are you using there?

**Comment by remusb** [comment] 2018-03-05 22:04
Yes, please try more recent version. Much more stable, especially around uploads. I recommend to look at --cache-upload.. flags too.

But this is a basic test that would have worked even in earlier versions. If cache isn't found to be the cause through elimination, there's also this to look at:
`Mar 05 17:55:12 sbx1 rclone[880]: 2018/03/05 17:55:12 DEBUG : gdrivecache:: File to upload is small (0 bytes), uploading instead of streaming`
I've never did a test with 0 bytes, I'll add one for sanity but try another command just for kicks: `echo "test" > test` in the mount folder just to rule it out.

**Comment by mcadam** [comment] 2018-03-06 17:56
Hi, I will try a more recent version in the next couple days. I did already tried before the echo to have file no 0 in size and same thing.

About the logs I am using -vv and thats the only log I get, no error in the rclone logs after the not found.

**Comment by putty182** [comment] 2018-05-13 02:16
I'm running into the same problems with `rclone mount` and NFSv4 with and without a cache remote (but always with crypt)

I can create and remove folders via NFS (not pictured below) and even remove files that already exist (pictured), but not create or modify existing files (pictured).

Haven't tried latest rclone beta yet;  will give that a go next and report back.

## Version
rclone v1.41, alpine 3.7.0 (running in a container / kubernetes pod)

    # rclone --version
    rclone v1.41
    - os/arch: linux/amd64
    - go version: go1.10

    # cat /etc/alpine-release
    3.7.0

## Config (redacted)
I do typically have a cache: remote between google: and crypt: remotes, but took it out for testing purposes.

    [google]
    type = drive

    [crypt]
    type = crypt
    remote = google:crypt

## `rclone mount` command
    rclone mount --allow-other \
      --verbose=2 \
      --drive-shared-with-me \
      --config=/secrets/rclone.conf \
      crypt:media /data

## Interactive shell commands
Lines prefixed with `#` are commands run on rclone nfs server; `$` are commands on NFS client.

    # echo "test file one" > test-file-one.txt
    # touch .
    # ls -ali
    total 1
    11278615397850629281 -rw-r--r--    1 plex     users           14 May 13 02:06 test-file-one.txt

    $ touch .
    $ ls -ali
    total 1
    11278615397850629281 -rw-r--r-- 1 plex plex 14 May 13 02:06 test-file-one.txt

    $ echo "test file two" > test-file-two.txt
    bash: test-file-two.txt: Input/output error

    $ echo "more lines for test file one" >> test-file-one.txt
    $ cat test-file-one.txt
    test file one

    # cat test-file-one.txt
    test file one

    $ rm test-file-one.txt
   
    # ls -ali
    total 0

## `rclone --verbose=2` output
````
2018/05/13 02:06:57 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:06:57 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2018/05/13 02:06:57 DEBUG : test/: Create: name="test-file-one.txt"
2018/05/13 02:06:57 DEBUG : test/test-file-one.txt: Open: flags=O_WRONLY|O_CREATE|O_TRUNC
2018/05/13 02:06:57 DEBUG : test/test-file-one.txt: >Open: fd=test/test-file-one.txt (w), err=<nil>
2018/05/13 02:06:57 DEBUG : test/: >Create: node=test/test-file-one.txt, handle=&{test/test-file-one.txt (w)}, err=<nil>
2018/05/13 02:06:57 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:06:57 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/05/13 02:06:57 DEBUG : &{test/test-file-one.txt (w)}: Flush:
2018/05/13 02:06:57 DEBUG : test/test-file-one.txt: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2018/05/13 02:06:57 DEBUG : &{test/test-file-one.txt (w)}: >Flush: err=<nil>
2018/05/13 02:06:57 DEBUG : &{test/test-file-one.txt (w)}: Write: len=14, offset=0
2018/05/13 02:06:57 DEBUG : &{test/test-file-one.txt (w)}: >Write: written=14, err=<nil>
2018/05/13 02:06:57 DEBUG : &{test/test-file-one.txt (w)}: Flush:
2018/05/13 02:06:57 DEBUG : Encrypted drive 'crypt:media': File to upload is small (14 bytes), uploading instead of streaming
2018/05/13 02:06:59 INFO  : test/test-file-one.txt: Copied (new)
2018/05/13 02:06:59 DEBUG : &{test/test-file-one.txt (w)}: >Flush: err=<nil>
2018/05/13 02:06:59 DEBUG : &{test/test-file-one.txt (w)}: Release:
2018/05/13 02:06:59 DEBUG : test/test-file-one.txt: WriteFileHandle.Release nothing to do
2018/05/13 02:06:59 DEBUG : &{test/test-file-one.txt (w)}: >Release: err=<nil>
2018/05/13 02:07:07 DEBUG : test/: Setattr: stat=Setattr [ID=0x723 Node=0xfd Uid=0 Gid=0 Pid=28677] atime=2018-05-13 02:07:07.044999529 +0000 UTC atime=now mtime=2018-05-13 02:07:07.044999529 +0000 UTC mtime=now handle=INVALID-0x0
2018/05/13 02:07:07 DEBUG : test/: >Setattr: err=<nil>
2018/05/13 02:07:07 DEBUG : test/: Attr:
2018/05/13 02:07:07 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:14 DEBUG : test/: Attr:
2018/05/13 02:07:14 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:14 DEBUG : test/: ReadDirAll:
2018/05/13 02:07:14 DEBUG : test/: >ReadDirAll: item=1, err=<nil>
2018/05/13 02:07:14 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:07:14 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:07:24 DEBUG : test/: Attr:
2018/05/13 02:07:24 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:24 DEBUG : test/: Setattr: stat=Setattr [ID=0x72b Node=0xfb Uid=0 Gid=0 Pid=29084] atime=2018-05-13 02:07:24.241457657 +0000 UTC atime=now mtime=2018-05-13 02:07:24.241457657 +0000 UTC mtime=now handle=INVALID-0x0
2018/05/13 02:07:24 DEBUG : test/: >Setattr: err=<nil>
2018/05/13 02:07:24 DEBUG : test/: Attr:
2018/05/13 02:07:24 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:29 DEBUG : test/: Attr:
2018/05/13 02:07:29 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:29 DEBUG : test/: ReadDirAll:
2018/05/13 02:07:29 DEBUG : test/: >ReadDirAll: item=1, err=<nil>
2018/05/13 02:07:29 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:07:29 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:07:29 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:07:29 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:07:29 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:07:29 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:07:29 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:07:29 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:07:29 DEBUG : test/: Attr:
2018/05/13 02:07:29 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:29 DEBUG : /: Attr:
2018/05/13 02:07:29 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:07:33 DEBUG : Google drive root 'crypt/24f3qfsqarbbf5lkmnjbgqribk': Checking for changes on remote
2018/05/13 02:07:33 DEBUG : test: forgetting directory cache
2018/05/13 02:07:33 DEBUG : Google drive root 'crypt/24f3qfsqarbbf5lkmnjbgqribk': All changes were processed. Waiting for more.
2018/05/13 02:08:25 DEBUG : test/: Attr:
2018/05/13 02:08:25 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:08:25 DEBUG : test/: Lookup: name="test-file-two.txt"
2018/05/13 02:08:26 DEBUG : test/: >Lookup: node=<nil>, err=no such file or directory
2018/05/13 02:08:33 DEBUG : Google drive root 'crypt/24f3qfsqarbbf5lkmnjbgqribk': Checking for changes on remote
2018/05/13 02:08:34 DEBUG : Google drive root 'crypt/24f3qfsqarbbf5lkmnjbgqribk': All changes were processed. Waiting for more.
2018/05/13 02:08:35 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:35 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:35 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Open: flags=OpenWriteOnly
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Open: flags=O_WRONLY
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Open: fd=test/test-file-one.txt (w), err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Open: fh=&{test/test-file-one.txt (w)}, err=<nil>
2018/05/13 02:08:35 DEBUG : test/: Attr:
2018/05/13 02:08:35 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:35 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : &{test/test-file-one.txt (w)}: Release:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: WriteFileHandle.Release closing
2018/05/13 02:08:35 DEBUG : &{test/test-file-one.txt (w)}: >Release: err=<nil>
2018/05/13 02:08:35 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:35 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Open: flags=OpenWriteOnly
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Open: flags=O_WRONLY
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Open: fd=test/test-file-one.txt (w), err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Open: fh=&{test/test-file-one.txt (w)}, err=<nil>
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : &{test/test-file-one.txt (w)}: Write: len=29, offset=0
2018/05/13 02:08:35 ERROR : test/test-file-one.txt: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2018/05/13 02:08:35 DEBUG : &{test/test-file-one.txt (w)}: >Write: written=0, err=operation not permitted
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:35 DEBUG : &{test/test-file-one.txt (w)}: Release:
2018/05/13 02:08:35 DEBUG : test/test-file-one.txt: WriteFileHandle.Release closing
2018/05/13 02:08:35 DEBUG : &{test/test-file-one.txt (w)}: >Release: err=<nil>
2018/05/13 02:08:52 DEBUG : test/: Attr:
2018/05/13 02:08:52 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:08:52 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:52 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:52 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:52 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Open: flags=OpenReadOnly
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Open: flags=O_RDONLY
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Open: fd=test/test-file-one.txt (r), err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Open: fh=&{test/test-file-one.txt (r)}, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:52 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:52 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:52 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:08:52 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Open: flags=OpenReadOnly
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Open: flags=O_RDONLY
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Open: fd=test/test-file-one.txt (r), err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Open: fh=&{test/test-file-one.txt (r)}, err=<nil>
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:52 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:08:52 DEBUG : &{test/test-file-one.txt (r)}: Read: len=4096, offset=0
2018/05/13 02:08:54 DEBUG : &{test/test-file-one.txt (r)}: >Read: read=14, err=<nil>
2018/05/13 02:08:54 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:08:54 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:09:04 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:09:04 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:09:04 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:09:04 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: Open: flags=OpenReadOnly
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: Open: flags=O_RDONLY
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: >Open: fd=test/test-file-one.txt (r), err=<nil>
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: >Open: fh=&{test/test-file-one.txt (r)}, err=<nil>
2018/05/13 02:09:04 DEBUG : &{test/test-file-one.txt (r)}: Read: len=4096, offset=0
2018/05/13 02:09:04 DEBUG : &{test/test-file-one.txt (r)}: >Read: read=14, err=<nil>
2018/05/13 02:09:04 DEBUG : &{test/test-file-one.txt (r)}: Flush:
2018/05/13 02:09:04 DEBUG : &{test/test-file-one.txt (r)}: >Flush: err=<nil>
2018/05/13 02:09:04 DEBUG : &{test/test-file-one.txt (r)}: Release:
2018/05/13 02:09:04 DEBUG : test/test-file-one.txt: ReadFileHandle.Release closing
2018/05/13 02:09:04 DEBUG : &{test/test-file-one.txt (r)}: >Release: err=<nil>
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:09:15 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:09:15 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:09:15 DEBUG : test/: Lookup: name="test-file-one.txt"
2018/05/13 02:09:15 DEBUG : test/: >Lookup: node=test/test-file-one.txt, err=<nil>
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: Attr:
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: >Attr: a=valid=1s ino=0 size=14 mode=-rw-r--r--, err=<nil>
2018/05/13 02:09:15 DEBUG : test/: Remove: name="test-file-one.txt"
2018/05/13 02:09:15 DEBUG : &{test/test-file-one.txt (r)}: Release:
2018/05/13 02:09:15 DEBUG : test/test-file-one.txt: ReadFileHandle.Release closing
2018/05/13 02:09:15 DEBUG : &{test/test-file-one.txt (r)}: >Release: err=<nil>
2018/05/13 02:09:15 DEBUG : test/: >Remove: err=<nil>
2018/05/13 02:09:15 DEBUG : test/: Attr:
2018/05/13 02:09:15 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:09:26 DEBUG : test/: Attr:
2018/05/13 02:09:26 DEBUG : test/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/05/13 02:09:26 DEBUG : test/: ReadDirAll:
2018/05/13 02:09:26 DEBUG : test/: >ReadDirAll: item=0, err=<nil>
````

**Comment by heikobornholdt** [comment] 2019-03-23 13:32
The problem persists in v1.46

**Comment by ncw** [comment] 2019-03-25 15:32
There are some ideas here which could help: https://unix.stackexchange.com/questions/102617/having-trouble-exporting-fuse-via-nfs

In particular the NFSv4 ideas...

**Comment by heikobornholdt** [comment] 2019-04-14 16:06
Same problem with NFSv4

**Comment by Cnly** [comment] 2019-04-14 16:33
@heikobornholdt Can you elaborate? I succeeded with rclone v1.46 and NFSv4 using only `--allow-other` for rclone and the settings mentioned in this Unix StackExchange [post](https://unix.stackexchange.com/questions/102617/having-trouble-exporting-fuse-via-nfs) for NFS.

**Comment by Cnly** [comment] 2019-04-14 16:38
_Please ignore this comment._

I thought I succeeded with v1.46 and the NFSv4 ideas in that post just now, but I didn't. :(

**Comment by Nornode** [comment] 2019-06-11 13:28
Yupp, same here.
 rclone v1.47.0
- os/arch: linux/amd64                                                                            - go version: go1.12.4

**Comment by ncw** [comment] 2019-06-12 10:31
I'm not sure I can help with investigations at the moment, but I'm cheering you on from the sideline :-)

If anyone does successfully make it work then please write it up in [the rclone wiki](https://github.com/ncw/rclone/wiki).

Likewise if we can work out what might need to change in rclone then let me know.

**Comment by sheetalgarde** [comment] 2019-07-01 19:31
How do other fuse file systems work over NFS ? Example s3QL - http://www.rath.org/s3ql-docs/mount.html

**Comment by ncw** [comment] 2019-07-01 19:39
> How do other fuse file systems work over NFS ? Example s3QL - http://www.rath.org/s3ql-docs/mount.html

So it is possible but with the `--nfs` workarounds.  Anyone fancy diving into the source to figure out what they do?

**Comment by judassssss** [comment] 2019-12-10 03:11
hi everyone, I had the same problem with rclone version beta
Has anyone succeeded yet? Can give me advice?

**Comment by Rojikku** [comment] 2020-09-18 21:02
I setup rclone with NFS and didn't realize I can't create files until now, and it's pretty upsetting, actually.
I can mkdir test, but I can't touch test.

**Comment by telvgehc** [comment] 2020-10-29 08:54
any update on this?

**Comment by ncw** [comment] 2020-10-29 15:17
I had a look at the s3ql source code to see what its --nfs option does - it looks like it is a performance optimization only and the docs agree

> S3QL filesystems can be exported over NFS. The --nfs option is recommended to improve performance when NFS is used, but no harm will occur when it is not specified.

I've investigated the problem some more and it appears that `rclone cmount` does work. The reason `rclone mount` doesn't work is that it doesn't implement the FUSE Mknod call

```
2020/10/29 14:07:02 DEBUG : fuse: <- Mknod [ID=0x2e Node=0x1 Uid=1000 Gid=1000 Pid=1370185] Name "file.txt" mode=-rw-rw-r-- umask=---------- rdev=0
2020/10/29 14:07:02 DEBUG : fuse: -> [ID=0x2e] Mknod error=EIO
```

I implemented a simple Mknod and it seems to work now - can you give this a go

[v1.54.0-beta.4869.bfcd4113c.fix-2115-nfs](https://beta.rclone.org/branch/fix-2115-nfs/v1.54.0-beta.4869.bfcd4113c.fix-2115-nfs/) on branch [fix-2115-nfs](https://github.com/rclone/rclone/tree/fix-2115-nfs) (uploaded in 15-30 mins)

Note that you'll probably need `--vfs-cache-mode writes` with this.

**Comment by telvgehc** [comment] 2020-10-30 06:20
now it works perfectly

**Comment by ncw** [comment] 2020-10-30 13:01
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

**Closed** 2020-10-30 13:01 UTC
Labels: VFS / mount, bug

**Comment by jenslam** [comment] 2020-12-30 12:39
Thanks for fixing the issue! After I installed the beta version I could also get along the descirbed problem (after a lot of trouble shooting...). Any ideas when 1.54 will be released?

**Comment by ncw** [comment] 2021-01-01 17:58
> Any ideas when 1.54 will be released?

Some time in January I expect :-)
