### ISSUE TITLE
Error When Using Rclone with Docker

### ISSUE THREAD

**Issue by AyaanZaveri** [rclone/rclone#5195] opened 2021-04-02 15:27 UTC
**Command I'm putting**
docker run --rm
--volume ~/.config/rclone:/config/rclone
--volume ~/drive:/data:shared
rclone/rclone
listremotes

**The Error I'm getting**
docker: Error response from daemon: path /host_mnt/Users/.../drive is mounted on /host_mnt but it is not a shared mount.

**Model:** M1 MacBook Air
**Version:** MacOS Big Sur 11.1 (20C69)

**Comment by ncw** [comment] 2021-04-03 12:55
Is ~/drive mounted by something else already? I think that is what the error message is saying. Maybe you need to unmount it or choose a different dir?

**Comment by FatSandwich** [comment] 2021-04-06 00:03
Where would I change the directory? Also, a command I didn't put was `    --user $(id -u):$(id -g) \`, is it important?

**Comment by ncw** [comment] 2021-04-06 10:01
> Where would I change the directory? 

    --volume ~/drive:/data:shared

Change the `~/drive` here

> Also, a command I didn't put was ` --user $(id -u):$(id -g) \`, is it important?

If you don't put that then the mount will run as root which isn't recommended. So I think you do need that line.

**Comment by FatSandwich** [comment] 2021-04-06 14:13
Thanks, I tried changing the directory but it says that for all of the other directories. Is there a way I can make it a shared directory?

**Comment by ncw** [comment] 2021-04-10 11:41
> Thanks, I tried changing the directory but it says that for all of the other directories. Is there a way I can make it a shared directory?

What error message did you get? What config did you try?

**Comment by FatSandwich** [comment] 2021-04-23 15:24
I've got my config to work but every time I try to mount it says "No Items" in the folder

<img width="69" alt="Screen Shot 2021-04-23 at 11 18 32 AM" src="https://user-images.githubusercontent.com/63752541/115892916-a4c43780-a425-11eb-8339-2d30f7df7004.png">

Do I need fuse, because that would be a problem since I would have to wait for version 11.3 of Big Sur to fix a bug?
https://github.com/osxfuse/osxfuse/issues/795

The reason I'm using Docker is because the actual one didn't work.

**Comment by ncw** [comment] 2021-04-25 15:51
You'll find this much easier if you do it without docker and rclone should work find on macOS.

Why didn't it work when you tried it?

**Comment by ivandeex** [comment] 2021-05-29 22:21
With or without Docker, rclone works with MacOS kernel via MacFUSE/osxFUSE.
See https://github.com/osxfuse/osxfuse/issues/795 and https://github.com/rclone/rclone/issues/5216#issuecomment-815357021
Sadly, rclone can't do much about it
Duplicate of #5216

**Closed by ivandeex** 2021-05-29 22:21 UTC
Labels: question
