### ISSUE TITLE
rclone genautocomplete zsh fails if vendor-completions directory is missing

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#6492] opened 2022-10-13 13:08 UTC
#### The associated forum post URL from `https://forum.rclone.org`
none

#### What is the problem you are having with rclone?
If rclone genautocomplete zsh is executed without the directory `/usr/share/zsh/vendor-completions/`, it will fail with the message `no such file or directory`.

To solve this issue, if the directory does not exist, it must be created automatically.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.59.2
- os/version: arch (64 bit)
- os/kernel: 5.15.72-1-lts (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.1
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
See above

#### Which cloud storage system are you using? (e.g. Google Drive)
none

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone genautocomplete zsh`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/10/13 22:07:37 DEBUG : rclone: Version "v1.59.2" starting with parameters ["rclone" "genautocomplete" "zsh" "-vv"]
2022/10/13 22:07:37 open /usr/share/zsh/vendor-completions/_rclone: no such file or directory
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2022-10-13 21:45
Want to send a fix?

**Comment by niksingh710** [comment] 2024-01-07 11:10
@ncw unable to find any completion files in the rclone repo
this [markdown](https://github.com/rclone/rclone/blob/master/docs/content/commands/rclone_completion_zsh.md) links to a [404](https://github.com/rclone/rclone/blob/master/commands/rclone_completion) ig where the completions script should be.

**Comment by ncw** [comment] 2024-01-09 09:47
@niksingh710 

Use

    rclone completion bash|fish|powershell|zsh

to generate the completion files - these aren't stored in the repo.

**Comment by niksingh710** [comment] 2024-01-09 09:49
@ncw i used the command 
to be specific `rclone completion zsh` 
but it gives the output 
```bash
open /usr/share/zsh/vendor-completions/_rclone: no such file or directory
```

is there any chance that i am using rclone from arch repos could be causing this?

**Comment by ncw** [comment] 2024-01-09 10:01
I think that is what this issue is about.

If you do `mkdir -p /usr/share/zsh/vendor-completions/_rclone` it should work.

**Comment by niksingh710** [comment] 2024-01-09 13:48
> I think that is what this issue is about.
> 
> If you do `mkdir -p /usr/share/zsh/vendor-completions/_rclone` it should work.

required sudo permissions but worked.

**Comment by reitzig** [comment] 2024-06-05 10:40
The more common approach is for `<tool> completion <shell>` to print the completion code to stdout so the user can put it wherever.

For instance, for fish we would usually to something like

```bash
rclone completion fish > "$HOME/.config/fish/completions/rclone.fish"
```

(when we install tools in userspace, anyway)

In fact, that's what cobra does by default (IIRC). 🤔 Not sure why you overrode that, but would you accept PRs adding the "normal" behaviour via a flag?

**Comment by ncw** [comment] 2024-06-06 10:36
You can use `rclone completion fish -` also to generate to stdout

I think this issue is mostly caused by the confusing error message.

The help is pretty clear though

```
$ rclone completion fish --help

Generates a fish autocompletion script for rclone.

This writes to /etc/fish/completions/rclone.fish by default so will
probably need to be run with sudo or as root, e.g.

    sudo rclone genautocomplete fish

Logout and login again to use the autocompletion scripts, or source
them directly

    . /etc/fish/completions/rclone.fish

If you supply a command line argument the script will be written
there.

If output_file is "-", then the output will be written to stdout.

Usage:
  rclone completion fish [output_file] [flags]
```

I don't think we can change the default of where the file is written as it has been like that for many years and that would confuse existing users.

I'm therefore going to close this issue as I think the help should be sufficient for users to figure out what is going on, and if not, searching will find this issue.

**Closed by ncw** 2024-06-06 10:36 UTC
Labels: bug, help wanted

**Comment by reitzig** [comment] 2024-06-08 18:51
Thanks, my bad for not reading the help message properly. 🙏

**Comment by rashidrafeek** [comment] 2025-01-16 06:56
By the way, the default --help does not mention the option to add a "-" at the end to print out the shell completion script :
```
$ rclone completion --help
Generates a shell completion script for rclone.
Run with `--help` to list the supported shells.

Usage:
  rclone completion [command]

Aliases:
  completion, genautocomplete

Available commands:
  bash        Output bash completion script for rclone.
  fish        Output fish completion script for rclone.
  powershell  Output powershell completion script for rclone.
  zsh         Output zsh completion script for rclone.

Flags:
  -h, --help   help for completion

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.
```

It actually mentions that it "Generates a shell completion script" and does not say anything about it printing to a file. I didn't think that I could get a better description by doing `rclone completion bash --help`.  I only found out about it from this issue through google. It would be nice to modify the above help to reflect that it prints to a file by default and can be printed to stdout by adding an "-" at the end.

**Comment by ncw** [comment] 2025-01-16 10:50
@rashidrafeek if you wanted to add this then it goes here

https://github.com/rclone/rclone/blob/5a4026ccb47f29327ff4cd9c868e7549d56671d2/cmd/genautocomplete/genautocomplete.go#L13-L18
