### ISSUE TITLE
--ignore-existing not working

### ISSUE THREAD

**Issue by dschense** [rclone/rclone#1147] opened 2017-02-17 16:51 UTC
I want to transfer a movie folder from Gdrive to ACD. 
Ive started some days ago with:

`rclone copy Googledrive:Movies Amazon:Movies`

this went fine till something abount 1000 Movies.
rclone stuck and i wanted to start it again like this:

`rclone copy --ignore-existing Googledrive:Movies Amazon:Movies`

because I dont want to copy existing files again or overwrite them.

But rclone copys files, which are already in Amazon:Movies, again..
Anybody who could help me with this problem?

**Comment by ncw** [comment] 2017-02-17 17:46
Just run the copy without `--ignore-existing` - copy is intelligent enough to figure out files are already present.

**Comment by dschense** [comment] 2017-02-23 08:51
Ive used both to test.

`rclone copy --ignore-existing Googledrive:Movies Amazon:Movies`
and
`rclone copy Googledrive:Movies Amazon:Movies`

But rclone copy files already an destination. This is no Problem for small files with some kb. But each file for me has 4-5 GB. like this its a bandwith eater.

**Comment by ncw** [comment] 2017-02-23 09:34
Can you try the latest beta, and post a log with `-v` of rclone copying files you think it shouldn't.  It will say exactly why rclone is copying the files.

**Comment by dschense** [comment] 2017-02-23 12:45
its showing me 
`2017/02/23 13:40:50 Movie.file.mkv: Sizes differ`
its for the same files every time i start the copy process. all other files get the skipping like:
`2017/02/23 13:40:50 Other-file.mkv: Sizes identical
2017/02/23 13:40:50 Other-file.mkv: Unchanged skipping`

**Comment by ncw** [comment] 2017-02-23 13:08
If the sizes are different then the file needs transferring.  So rclone thinks it needs to update that file because it is definitely different.

Can you confirm the sizes are different?

You can use `--ignore-existing` which should stop that file being transferred if you are sure you don't want it updated.

**Comment by animosity22** [comment] 2020-01-13 17:44
This looks stale. If you still have a question, feel free to post on the forums and we can help out.

**Closed by animosity22** 2020-01-13 17:44 UTC

**Comment by koanvi** [comment] 2020-02-10 11:46
Hi. Was it solved? I have the same problem.

**Comment by ncw** [comment] 2020-02-11 12:13
@koanvi write
> Hi. Was it solved? I have the same problem.

Probably best to discuss on [the rclone forum](https://forum.rclone.org/) first - as far as I'm aware `--ignore-existing` is working as designed.
