### ISSUE TITLE
Mailru backend upload forbidden.

### ISSUE THREAD

**Issue by PikaYellow35** [rclone/rclone#4635] opened 2020-09-28 06:10 UTC
### What is the problem you are having with rclone?
Mailru backend cannot sync VFS cache with cloud. Mail.ru cloud server return HTTP 403. backend password is correct, 2FA disabled, free space in cloud exist. 

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1
- os/arch: linux/amd64
- go version: go1.15.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
Mail.RU

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone mount mail-drive: ./mail-drive/ -vv --vfs-cache-mode full
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2020/09/28 09:07:19 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "mount" "mail-drive:" "./mail-drive/" "-vv" "--vfs-cache-mode" "full"]
2020/09/28 09:07:19 DEBUG : Creating backend with remote "mail-drive:"
2020/09/28 09:07:19 DEBUG : Using config file from "/home/yellow/.config/rclone/rclone.conf"
2020/09/28 09:07:20 INFO  : []: poll-interval is not supported by this remote
2020/09/28 09:07:20 DEBUG : vfs cache: root is "/home/yellow/.cache/rclone/vfs/mail-drive"
2020/09/28 09:07:20 DEBUG : vfs cache: metadata root is "/home/yellow/.cache/rclone/vfs/mail-drive"
2020/09/28 09:07:20 DEBUG : Creating backend with remote "/home/yellow/.cache/rclone/vfs/mail-drive"
2020/09/28 09:07:20 DEBUG : Aspia-local/AspiaBIG.aab: vfs cache: checking remote fingerprint "15324,2020-09-11 10:29:41 +0000 UTC,19e7875b587439f432ca4848398994b9ffc3a4fe" against cached fingerprint "15324,2020-09-11 10:29:41 +0000 UTC,19e7875b587439f432ca4848398994b9ffc3a4fe"
2020/09/28 09:07:20 DEBUG : Aspia-local/AspiaBIG.aab: vfs cache: truncate to size=15667
2020/09/28 09:07:20 DEBUG : vfs cache: looking for range={Pos:0 Size:15667} in [{Pos:0 Size:15667}] - present true
2020/09/28 09:07:20 DEBUG : Aspia-local/AspiaBIG.aab: vfs cache: setting modification time to 2020-09-21 14:22:04.367087438 +0300 MSK
2020/09/28 09:07:20 INFO  : Aspia-local/AspiaBIG.aab: vfs cache: queuing for upload in 5s
2020/09/28 09:07:20 DEBUG : []: Excluding path "/Aspia" from list: Unknown resource type "mounted"
2020/09/28 09:07:20 DEBUG : []: Excluding path "/KeeP" from list: Unknown resource type "mounted"
2020/09/28 09:07:20 DEBUG : Aspia-local: Added virtual directory entry vAdd: "AspiaBIG.aab"
2020/09/28 09:07:20 DEBUG : KeeP-local/BIG.kdbx: vfs cache: checking remote fingerprint "113822,2020-09-26 09:48:25 +0000 UTC,f999ee4c9d2cd7d9f0fb6d8a929a1a8141db773c" against cached fingerprint "113822,2020-09-26 09:48:25 +0000 UTC,f999ee4c9d2cd7d9f0fb6d8a929a1a8141db773c"
2020/09/28 09:07:20 DEBUG : KeeP-local/BIG.kdbx: vfs cache: truncate to size=113822
2020/09/28 09:07:20 DEBUG : vfs cache: looking for range={Pos:0 Size:113822} in [{Pos:0 Size:113822}] - present true
2020/09/28 09:07:20 DEBUG : KeeP-local/BIG.kdbx: vfs cache: setting modification time to 2020-09-26 12:42:16.400108982 +0300 MSK
2020/09/28 09:07:20 INFO  : KeeP-local/BIG.kdbx: vfs cache: queuing for upload in 5s
2020/09/28 09:07:20 DEBUG : KeeP-local: Added virtual directory entry vAdd: "BIG.kdbx"
2020/09/28 09:07:20 DEBUG : []: Mounting on "./mail-drive/"
2020/09/28 09:07:20 DEBUG : vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item Aspia-local/AspiaBIG.aab not removed, freed 0 bytes
2020/09/28 09:07:20 DEBUG : vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item KeeP-local/BIG.kdbx not removed, freed 0 bytes
2020/09/28 09:07:20 INFO  : vfs cache: cleaned: objects 2 (was 2) in use 2, to upload 2, uploading 0, total size 126.454k (was 0)
2020/09/28 09:07:20 DEBUG : : Root: 
2020/09/28 09:07:20 DEBUG : : >Root: node=/, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Lookup: name=".Trash"
2020/09/28 09:07:20 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/28 09:07:20 DEBUG : /: Lookup: name=".Trash-1000"
2020/09/28 09:07:20 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/28 09:07:20 DEBUG : /: Lookup: name="BDMV"
2020/09/28 09:07:20 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/28 09:07:20 DEBUG : /: Lookup: name=".xdg-volume-info"
2020/09/28 09:07:20 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Lookup: name="autorun.inf"
2020/09/28 09:07:20 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Attr: 
2020/09/28 09:07:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/28 09:07:20 DEBUG : /: ReadDirAll: 
2020/09/28 09:07:20 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/28 09:07:20 DEBUG : /: Lookup: name="autorun.inf"
2020/09/28 09:07:20 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/28 09:07:25 DEBUG : Aspia-local/AspiaBIG.aab: vfs cache: starting upload
2020/09/28 09:07:25 DEBUG : []: new meta server: https://cld-extapi2.datacloudmail.ru/meta/
2020/09/28 09:07:25 DEBUG : []: new upload shard: https://cld-upload3.cloud.mail.ru/upload-web/
2020/09/28 09:07:25 DEBUG : KeeP-local/BIG.kdbx: vfs cache: starting upload
2020/09/28 09:07:25 ERROR : Aspia-local/AspiaBIG.aab: Failed to copy: server error 403 (<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
)
2020/09/28 09:07:25 ERROR : Aspia-local/AspiaBIG.aab: vfs cache: failed to upload try #1, will retry in 10s: vfs cache: failed to transfer file from cache to remote: server error 403 (<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
)
2020/09/28 09:07:25 ERROR : KeeP-local/BIG.kdbx: Failed to copy: server error 403 (<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
)
```

**Comment by darthShadow** [comment] 2020-09-28 06:33
There were a couple of recent fixes with the Mailru backend which are present in the latest beta. Can you try with that and let us know if the issue is still present?

**Comment by ncw** [comment] 2020-09-28 10:10
> There were a couple of recent fixes with the Mailru backend which are present in the latest beta. Can you try with that and let us know if the issue is still present?

These fixes are scheduled for the v1.53.2 release too. You can find a release candidate for that branch here

https://beta.rclone.org/branch/v1.53-stable/

**Comment by PikaYellow35** [comment] 2020-09-29 17:37
Yes, i'm tested **rclone-v1.53.2-beta.4776.c7335e780.v1.53-stable-linux-amd64** and all working. Part of log of sync:
```
2020/09/29 20:33:33 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2020/09/29 20:33:33 DEBUG : /: ReadDirAll: 
2020/09/29 20:33:33 DEBUG : /: >ReadDirAll: item=8, err=<nil>
2020/09/29 20:33:33 DEBUG : /: Lookup: name="autorun.inf"
2020/09/29 20:33:33 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/09/29 20:33:37 DEBUG : Aspia-local/AspiaBIG.aab: vfs cache: starting upload
2020/09/29 20:33:37 DEBUG : []: new meta server: https://cld-extapi2.datacloudmail.ru/meta/
2020/09/29 20:33:37 DEBUG : []: new upload shard: https://cld-upload2.cloud.mail.ru/upload/
2020/09/29 20:33:37 DEBUG : KeeP-local/BIG.kdbx: vfs cache: starting upload
2020/09/29 20:33:38 DEBUG : Aspia-local/AspiaBIG.aab: MailruHash = 4cb3a53e9703114761ab60af2cdd5042c00cd4bf OK
2020/09/29 20:33:38 INFO  : Aspia-local/AspiaBIG.aab: Copied (replaced existing)
2020/09/29 20:33:38 DEBUG : Aspia-local/AspiaBIG.aab: vfs cache: fingerprint now "15667,2020-09-21 11:22:04.367087438 +0000 UTC,4cb3a53e9703114761ab60af2cdd5042c00cd4bf"
2020/09/29 20:33:38 INFO  : Aspia-local/AspiaBIG.aab: vfs cache: upload succeeded try #1
2020/09/29 20:33:38 DEBUG : KeeP-local/BIG.kdbx: MailruHash = f999ee4c9d2cd7d9f0fb6d8a929a1a8141db773c OK
2020/09/29 20:33:38 INFO  : KeeP-local/BIG.kdbx: Copied (replaced existing)
2020/09/29 20:33:38 DEBUG : KeeP-local/BIG.kdbx: vfs cache: fingerprint now "113822,2020-09-26 09:42:16.400108982 +0000 UTC,f999ee4c9d2cd7d9f0fb6d8a929a1a8141db773c"
2020/09/29 20:33:38 INFO  : KeeP-local/BIG.kdbx: vfs cache: upload succeeded try #1
2020/09/29 20:34:32 DEBUG : vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item Aspia-local/AspiaBIG.aab not removed, freed 0 bytes
2020/09/29 20:34:32 DEBUG : vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item KeeP-local/BIG.kdbx not removed, freed 0 bytes
2020/09/29 20:34:32 INFO  : vfs cache: cleaned: objects 2 (was 2) in use 0, to upload 0, uploading 0, total size 126.454k (was 126.454k)
```

**Comment by darthShadow** [comment] 2020-09-29 17:41
Great. Closing the issue then.

**Closed by darthShadow** 2020-09-29 17:41 UTC
Labels: Remote: Mailru
