### ISSUE TITLE
RCLONE Backup mode with LZ4 - feature request

### ISSUE THREAD

**Issue by pedrosimao** [rclone/rclone#1356] opened 2017-04-20 16:35 UTC
Considering many people use RCLONE as a backup tool. I was wondering why there is not a backup mode/flag that would allow us to use LZ4 compression? Besides making RCLONE less bandwidth hungry, while preserving speed (up to 400MB/s on LZ4 speed), this would solve some other issues backupers face, as RCLONE not preserving file metadata / date / time on Amazon Cloud, for instance.

It seems to me that the challenge of implementing such a feature would be to keep the capacity of RCLONE on detecting file changes on the source, while comparing the source files with the destination files in the backup location. Since the destination files would be compressed we will not be able to compare uncompressed files with compressed ones. In this sense, I think the use of extracted metadata might be a solution. We could create a database of all metadata of all files copied, save it in a separate file from the compressed files, within the destination location, and than compare this metadata with the metadata of the source files.

Does anyone feels capable / motivated to implement such a feature?

Here is LZ4 source in GO language:
https://github.com/pierrec/lz4

And here is some information about it:
http://lz4.github.io/lz4/

Unhappily I still don't code in Go, but I can try to learn some stuff and give a hand in case someone can guide me. I currently code in C, Python and Javascript.

**Comment by ncw** [comment] 2017-04-22 11:47
I think this is mostly a duplicate of #675 - can you add your comments about LZ4 to that ticket and close this one?

**Closed** 2020-01-23 17:15 UTC
