### ISSUE TITLE
Would it be possible to support a resume method for a sftp remote?

### ISSUE THREAD

**Issue by nick008a** [rclone/rclone#7483] opened 2023-12-04 14:21 UTC
#### The associated forum post URL from `https://forum.rclone.org`
Would it be possible to support a resume method for a sftp remote?

#### What is your current rclone version (output from `rclone version`)?
 v1.65.0

#### What problem are you are trying to solve?
 resume method for a sftp remote

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment] 2023-12-04 15:28
Duplicate of

https://github.com/rclone/rclone/issues/87

**Closed by Animosity022** 2023-12-04 15:28 UTC
