### ISSUE TITLE
Hubic - Unsolicited response received on idle HTTP: 408 Request Time-out

### ISSUE THREAD

**Issue by albansch** [rclone/rclone#1583] opened 2017-08-05 23:16 UTC
For reference: https://forum.rclone.org/t/hubic-unsolicited-response-received-on-idle-http-408-request-time-out/3453

Description:
Since 2-3 weeks, when using the below command with Hubic:
rclone -v --checksum --log-file /var/tmp/hubic-backup.log sync /backup/ hubic:default/backup/
I receive the below errors on all commands being run at Hubic via rclone:
Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n408 Request Time-out\nYour browser didn’t send a complete request in time.\n\n
I already refreshed the token - it didn’t help.

Version:
rclone v1.36

OS:
centos-release-7-3.1611.el7.centos.x86_64

Storage:
HUBIC

Command being run:
`rclone -v --checksum --log-file /var/tmp/hubic-backup.log sync /backup/ hubic:default/backup/`

Extract of the log:
`Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n408 Request Time-out\nYour browser didn’t send a complete request in time.\n\n`

**Comment by gerph** [comment] 2017-08-06 13:34
I'm going to have a stab and say that these are due to the preemptive connections performed by the checkers and/or transferrers when there is a lot of work to do on one side or the other. Without looking at the code (sorry, go is not my language of choice, and I've only started reading little bits in the last few weeks), I'm not sure, but I'd imagine the sequence of operations is something similar to this (on copy/sync)...

* spawn _n_ checker workers, with a queue of jobs (initially empty)
* spawn _m_ transferer workers, with a queue of jobs (initially empty)
* begin an enumeration thread for the source files we're interested in
  * feed the checker queue each file as we find it.

Each checker:
* make a persistent http/1.x connection to the server
* pull an item off the transfer queue
* request the timestamp/hash of the remote item; if the connection has gone away, make another one.
* if the items differ, push the pair (source, destination) on to the transfer queue
* repeat from 'pull an item'.

Each transferrer:
* make a persistent http/1.x connection to the server
* pull an item off the transfer queue
* perform the operation on the destination as requested; if the connection has gone away make another one
* repeat from 'pull an item off the transfer queue'

I would expect that the checker queue and the transferrer queue were longer than the number of checkers or transferrers (maybe by a factor of 2 above the maximum of the number of checkers and transferrers), and would block if they were full. This would prevent the transferrers being left with no jobs whilst the checkers were doing theirs but finding little to do - essentially preventing a burst of checkers blocking waiting for transferrers, and then once the transferers finish leaving them with little to do because the checkers need to find more work. The limits on the queues prevent long operations on later parts of the pipeline causing a large amount of memory allocations as the queues fill with huge amounts of job data that cannot be serviced yet; it also means that if the transfers are busy, the checkers go idle, giving all the bandwidth (cpu and network) to the transferrers.

Anyhow, assuming the above operation, consider the circumstance where there is nothing on the destination.

* the enumeration finds _max(n,m)*2_ items on the source system and queues them for the checkers.
* the enumeration blocks because the checker queue is now full.
* the checkers find _max(n,m)*2_ items on the destination system need to be operated on, and queue them.
* because the transfer queue is now full, the checkers block.
* the transfers start on _m_ items to the destination system, and this takes some time.
* the time is sufficiently long that the checker's persistent connection is recognised as idle by the server and it sends a message to that effect, closing the connection. (if the connection handler is itself a worker, it may be at this point the connection notice is raised - if not, then it's not until the checker tries to operate on the connection)
* a transfer completes, and this unblocks a checker.
* the checker pulls an item off its checker queue and tries to check it.
* then it notices the connection is closed and so has to reopen it.
* if only a single checker gets the work, then all the other checkers will find their connections will time out, with a single connection being busy and remaining persistent (or being constantly reopened).
* on the other hand, if the checkers are unblocked randomly, then the connections may all stay open and get reused. OR, if the transfers take long enough, every single one may time out repeatedly, and be caused to be reopened, with none ever staying persistent.

[[[Actually the above is slightly wrong as there will end up, in the above scenario with more items in flight between the checkers and transferrers - _m_ being processed by transferers, _max(n+m)_  in the transfer queue, _min(n,m)_ inside the checkers themselves, blocking waiting on the queue having space available, _n_ waiting in the enumeration queue, and 1 blocking waiting to be added to the enumeration queue... but I don't think these in flight details will affect the persistent connection state. The above just simplifies things a little.
And this may be made more complicated if the connections themselves are workers to whom jobs are submitted, but if there is a high degree of blocking (eg lots of large transfers) then the greater use of persistent connections may be counter-productive for the server, with lots of connections made but no operations performed before the timeout... and may in fact be the reason that the timeout was instated in the first place]]]

The opposite may also happen - on a fully populated remote, the checkers are busy doing work checking, but the preemptively opened transfer connections end up being idle most of the time. Even if they're not preemptively opened, a bust of transfers followed by a period of idleness may cause the connections to close at the server end.

The reason I suggest that these connections are preemptively opened is that with a fully populated remote and lots of files to check, I commonly see a flurry of the 'request time-out' messages whilst the checkers are working to find something to transfer, which I'd assume were the transferers timing out their open connections. Or they could be the checkers connections timing out after the transferrers had started but were taking a longer time to do their work than the request timeout.

If any of this were likely to be possible, I'd be thinking about getting some statistics out from each of the workers for number of items queued, number of connections idled out (and needing to be reopened). If it were the case that the connections were 'always' timing out after the operations (ie large delays between work) it might be useful to not use persistent connections/preemptively opened connections. And with those figures, it might even be possible for the system to dynamically decide whether it was sensible to keep the connections open - which would be better on the server, as having connections opened but doing nothing consumes a resource for it.

In any case, the message is almost certainly benign for the user, I believe. Maybe. I guess. Sorry, that's a lot of speculation with very little evidence, but just my thoughts if that might be useful to NCW (or others).

**Comment by ncw** [comment] 2017-08-07 14:02
@gerph - you are reasonably close to what happens!  The problem as I see it is indeed the persistent HTTP connections.  These are managed entirely by go's http library though.

What I think is happening is that rclone or the swift library are timing out some operations however hubic does come back with a reply eventually, after the listener to the persistent connection has gone away and the persistent connection is idle.  Hence the log message (which also comes from the http library directly).

It might also be a load balancer or something in front of hubic which is doing the timing out.

It would be worth increasing the values of `--conntimeout` and `--timeout` to see if those make a difference.

I don't think it is an rclone problem though

**Comment by albansch** [comment] 2017-08-11 13:21
Interesting, it seems I don't have this issue with version 1.35 (using same command).

**Comment by ncw** [comment] 2017-08-11 14:27
@albansch that is likely because 1.35 was compiled with an older go compiler which didn't give that message. That is my guess anyway.  Have you tried recompiling 1.35 with go1.8?

**Comment by albansch** [comment] 2017-08-14 08:27
Forget about what I said - it has happened also with 1.35 - it's just random.

**Comment by Flameborn** [comment] 2017-09-06 10:17
I am also receiving this error.

As it has no effect on the transfer, would it be possible to ignore this? With a two hour backup, my log contains 4291 entries of the error message. This is particularly frustrating when having small files, in my case around five hundred thousand.

**Comment by ncw** [comment] 2017-09-07 09:09
Can you try

> It would be worth increasing the values of --conntimeout and --timeout to see if those make a difference.

And see what happens?

**Comment by Flameborn** [comment] 2017-09-09 09:46
I have tried a five and a ten minute timeout with both parameters, unfortunately, the message still shows.

**Comment by vovcacik** [comment] 2017-09-21 11:33
- `--contimeout 1m0s` changing this has no effect (e.g. `10m0s`)
- `--timeout 5m0s` changing this has no effect (e.g. `50m0s`)
- `--stats 1m0s` changing this has no effect (e.g. `10m0s`)

- `--checkers 4` all values yields `408` response except `--checkers 1`, which always succeed. `--checkers 2` occasionally succeed.
-  `--tpslimit 23 --tpslimit-burst 1` 23 transactions per second is magic number for me, <=23 always succeed, >23 always fails. The burst needs to be kept low, <=4.

I was testing the parameters with `ncdu`, i.e. `rclone --tpslimit 23 ncdu hubic:default`.

**Comment by UltimateByte** [comment] 2017-10-25 20:04
Thanks @vovcacik 
The following arguments allowed the download of my Hubic backup to continue quite OK:
`--tpslimit 20 --tpslimit-burst 2`
Before that, it would fail after just a few seconds.

Note that some 408 errors occurred anyways, so it might be a good idea to put the limit at 18 and the burst at 1, just to be safe. (my download is too advanced now, so I cannot test until it's over, in around 4.912 days according to my calculations)

Full command syntax & real world example to download a backup:
`rclone --tpslimit 20 --tpslimit-burst 2 copy cloud:HubiC-DeskBackup_Work /srv/dev-disk-by-label-Work/`

**Comment by vovcacik** [comment] 2017-10-26 09:37
@UltimateByte thanks for the data!

**Comment by vovcacik** [comment] 2017-10-26 09:46
Regarding severity of this bug, nobody likes to see 408s in the output, but I don't think it negatively impacts functionality at all. On the contrary, maximizing transactions (i.e. `--tpslimit`) makes rclone fast (e.g. listing with `rclone ncdu`).

There is probably some sweet spot for everyone where you can tune `--tpslimit` and get same performance but without 408s. Or hide the 408s from log completely. What do you think?

**Comment by Flameborn** [comment] 2017-10-26 11:23
You are right, there is no adverse effect of this error, however I’d rather hide it due to the fact that it’s quite unnecessary information.

**Comment by UltimateByte** [comment] 2017-10-26 11:34
You are welcome about the output.
Are you 100% sure that this error has no adverse effect?
Because when it was occurring at first, I ran df -sh on my target directory, and couldn't see a dir size increase, which made me think the download was somewhat struck (then I googled and gladly found this issue).

**Comment by Flameborn** [comment] 2017-10-26 12:01
I’m not sure about downloads, but uploads are fine. The files and folders get synced properly. It might affect downloads, so I will have to look into this. Unfortunately, Hubic’s support is not the best, and I am exaggerating here.

**Comment by UltimateByte** [comment] 2017-10-26 14:06
A replication test for this issue would be a good idea. Unfortunately Hubic ils kinda dead, with its support team so yeah...

**Comment by jay1337** [comment] 2017-11-09 07:18
I'm using 2.0.9 GUI on Windows and this issue throws a blocking error during backup (ie causing backup to stop):

```
[17:24:28] Backup operation returned an error:
2017/11/08 17:22:13 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html> <body> <h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body> </html>\n"; err=<nil>
ERROR Failed to upload the chunk 3a379940937993b4dee8ac5ce12227d13282fc5ee3494038de738189c4a8b36b: Put https://lb1.hubic.ovh.net/v1/AUTH_0749e82d???????????????????67/default/DuplicacyBackupStorage/chunks/3a379940937993b4dee8ac5ce12227d13282fc5ee3494038de738189c4a8b36b: net/http: timeout awaiting response headers
```

**Comment by vovcacik** [comment] 2017-11-09 11:05
@jay1337 can you try to upload using cli and see if it helps?

**Comment by UltimateByte** [comment] 2017-11-09 12:37
3 OVH datacenters were down today because of a huge power delivery issue, they are under loads of issues to get all services back online, so probably not the best time to diagnose this ^^

**Comment by jay1337** [comment] 2017-11-09 13:51
@vovcacik it seems better !
Strange isn't it ?

**Comment by jay1337** [comment] 2017-11-09 13:55
@vovcacik ooops, another error occurred ! I often get this one too:

```
Uploaded chunk 533 size 3003193, 3.63MB/s 3 days 00:21:18 0.3%
Uploaded chunk 534 size 16777216, 3.63MB/s 3 days 00:14:09 0.3%
Uploaded chunk 536 size 9737905, 3.64MB/s 3 days 00:06:19 0.3%
Failed to upload the chunk e9cb096c642c370f3f078ac42e2d4e1fc73ec15556ac2ef303e5b4e67fa36ca6: Put https://lb1.hubic.ovh.net/v1/AUTH_0749????????????67/default/DuplicacyBackupJerome/chunks/e9cb096c642c370f3f078ac42e2d4e1fc73ec15556ac2ef303e5b4e67fa36ca6: net/http: timeout awaiting response headers
```

Is it possible to choose the timeout and what's the default value?

**Comment by ncw** [comment] 2017-11-10 09:18
@jay1337 if you try [the latest beta](https://beta.rclone.org) you should find it handles this a bit better.

> Is it possible to choose the timeout and what's the default value?

See `--conntimeout` flag

**Comment by jay1337** [comment] 2017-11-10 09:28
In fact, I'm using duplicacy (which I think relies on rclone since duplicacy's author redirected me to this issue).
I can't see how to test a specific version of rclone with my current version of duplicacy...

**Comment by vovcacik** [comment] 2017-11-10 15:31
@jay1337 I was fiddling with `--timeout` in previous [comment][].

[comment]: https://github.com/ncw/rclone/issues/1583#issuecomment-331130238

**Comment by gingerbeardman** [comment] 2017-11-29 12:42
Thanks @vovcacik @UltimateByte for help with command line args

**Comment by vovcacik** [comment] 2018-01-30 11:51
@marianobrc Hi, I believe that no one has reported that data was lost or not uploaded properly in this thread, but your scenario is bit different. We are pushing to Hubic but you're using S3. Can you make sure your data are fine and report back?

**Comment by marianobrc** [comment] 2018-01-30 12:01
Hi @vovcacik thanks for your answer.
I let it running and I got more errors later while uploading files so I desisted from using this tool.

My last errors:
`2018/01/30 07:27:11 ERROR : uploads/checkins/Alex hacienda/books/Alex_hacienda_book_1_96652036f21d11e7b3d93a88db29d44e.pdf: Failed to copy: MultipartUpload: upload multipart failed
	upload id: lWTneIYozJnc.2GHHpsuRDetfSqhJbB8sEPJBvauWnLDV17Lo7k5z0tMaT7f0LCRCtfL4n8L5oyGfFvCg74l44WVGnDTUm.sH6CeS3nxbNst9o9D7WByVZxHkyEq5B4T
caused by: ReadRequestBody: read multipart upload data failed
caused by: read tcp 192.168.1.37:50572->5.101.110.225:443: read: connection reset by peer
2018/01/30 07:27:11 ERROR : S3 bucket chekinapptest: not deleting files as there were IO errors
2018/01/30 07:27:11 ERROR : S3 bucket chekinapptest: not deleting directories as there were IO errors
2018/01/30 07:27:11 ERROR : Attempt 1/3 failed with 30 errors and: MultipartUpload: upload multipart failed
	upload id: lWTneIYozJnc.2GHHpsuRDetfSqhJbB8sEPJBvauWnLDV17Lo7k5z0tMaT7f0LCRCtfL4n8L5oyGfFvCg74l44WVGnDTUm.sH6CeS3nxbNst9o9D7WByVZxHkyEq5B4T
caused by: ReadRequestBody: read multipart upload data failed
`

Thanks
Regards

**Comment by vovcacik** [comment] 2018-01-30 12:09
@marianobrc Oh I see. This looks like known error. The developer (@ncw) is trying to get feedback on this in #1823.

**Comment by ncw** [comment] 2018-01-30 16:44
@marianobrc wrote:

> HI, I'm using rclone to copy files from Digital Ocean spaces to Amazon S3 busckets and I'm getting the same error 408 Request Time-out.
> Does that error mean that some file failed to be copied? can I lose data?

The error is harmless and it won't cause any data loss.  It is just the go runtime saying that someone sent data on a channel it wasn't expecting.

In your other post the root cause of your error is `read tcp 192.168.1.37:50572->5.101.110.225:443: read: connection reset by peer` which is a networking error.  rclone will retry this sort of error as networks are unreliable and errors like this are common.

**Comment by rmalayter** [comment] 2018-04-19 21:47
I can repro uploading a large tree with 200k little files to Rackspace Cloud Files as well. It seems as though rclone opens http connections but then does nothing with them for an extended period while it is trolling the directory tree locally.

**Comment by ncw** [comment] 2018-04-20 18:58
@rmalayter wrote:
> I can repro uploading a large tree with 200k little files to Rackspace Cloud Files as well. It seems as though rclone opens http connections but then does nothing with them for an extended period while it is trolling the directory tree locally.

That sounds correct.  And when the server closes them for being idle too long I think it should just close them, not send a message.

The fact that the server does send a message might mean that it thinks rclone is still reading the response whereas rclone (and net/http) thinks it is done with the connection.  That is conclusion I've come to, but I haven't managed to nail it down.

Here is the [section on 408 timeout in the rfc](https://tools.ietf.org/html/rfc7231#section-6.5.7) if you are interested.

Another possibility that I was working on (but haven't completed) is that this is a bug in HA Proxy.

rclone sets [IdleConnTimeout = 60 * time.Second](https://github.com/ncw/rclone/blob/a0c65deca822cf263570f33d2156a2833a5ed64b/fs/fshttp/http.go#L138) in the Transport, so these idle connections should time out after 60 seconds.  It might be that this number is too high.

@rmalayter if you can reproduce this reasonably easily, it would be interesting to recompile rclone with different values for the idle timeout and see whether that makes a difference.

Though you said above "does nothing with them for an extended period" - how long is that?  > 30s?

It would be interesting to monitor rclone with lsof or netstat to see what connections it has open too.

If there is a bug then it is probably in the swift library rclone uses (also written by me) as that seems to be the common point of all the reports I've seen.

**Comment by rmalayter** [comment] 2018-08-10 20:40
What sort of structured test should I do? Which timeouts should I change?

I don't want to flail around aimlessly

**Comment by davispuh** [comment] 2020-05-06 23:52
I'm also getting bunch of these when copying from Mega

```
2020/05/07 02:50:42 Unsolicited response received on idle HTTP channel starting with "\x02\x90\x15\x89+[...]\x160$\xf5\a\r\x18X\xfc'\xefe"; err=<nil>
```

**Comment by ncw** [comment] 2020-05-07 11:12
@davispuh these are harmless I think and just indicate that rclone and the server have got confused about which connections are idle.

**Comment by ImportTaste** [comment] 2020-05-25 18:11
@ncw The Unsolicited response errors I'm getting from MEGA are VERY long and spam the console. Is there a way to reliably filter them out?

**Comment by ncw** [comment] 2020-05-26 11:43
@ImportTaste these logs are coming from the go standard library and there isn't a flag to turn them off.  I think running with `-q` might work but not sure.

**Comment by ivandeex** [comment] 2021-02-09 15:24
@albansch Does the problem reproduce with rclone 1.54?

**Comment by albansch** [comment] 2021-03-02 22:45
@ivandeex confirming that in version 1.50.2, I can't see these entries within logs anymore. Will try 1.54 later on.

**Comment by ivandeex** [comment] 2021-03-12 14:26
Feel free to reopen if the problem reappears in 1.54

**Closed by ivandeex** 2021-03-12 14:26 UTC
Labels: Remote: Hubic, bandwidth, bug, waiting for reply...
