### ISSUE TITLE
Copy to ACD crypt stalls out after 100% upload. 

### ISSUE THREAD

**Issue by robertclemens** [rclone/rclone#1078] opened 2017-01-30 19:00 UTC
Previously was using the GA release of rclone v1.35. This is the version that the issue started on.
I was still having this issue with: v1.35-41-g2abfae2
I've now installed v1.35-55-g37fe6d5 and will test accordingly.

OS: RHEL 6 x64 (rclone binary using linux-amd64)

I'm copying from local ext4 filesystem to acd crypt location. It generally works but as of the last week or two I'm uploading and get to 100% and rclone log sits at 100% for a long time and I'll get a gateway timeout. There are a dozen or so files, most are small but there is one large file each day at around 21GB to 22GB.

Script running:
#!/bin/bash
bwlimit=2400

######################################

DATE=`date +%Y%m%d`
SHORTDATE=`date +%y%m%d`

######################################

/usr/local/bin/rclone --config /root/.rclone.conf --include \*$SHORTDATE\* copy /local/dump/ crypt:$DATE --bwlimit $bwlimit -v --no-traverse --max-depth 0

Logs attached in zip.
[rclone_log.zip](https://github.com/ncw/rclone/files/739974/rclone_log.zip)

I looked at issue #902 but it was moved from acd to acd crypt as a culprit. I couldn't seem to find an open case or current forum topic that matched my issue. Could it just be my filesize or something else particular to my selected file list?

**Comment by ncw** [comment] 2017-01-30 21:19
This looks like it is large files on acd problem. When uploading large files sometimes acd takes the file but gives an error. 

Rclone then waits a configurable length of time to wait for the file to appear - that is what you are seeing. 

For big files this is a long time. See the acd upload wait parameter. 

I've had other reports that uploading big files to acd isn't working well at the moment too. I don't think it is rclone's fault though.

**Comment by robertclemens** [comment] 2017-01-30 23:33
Thanks for such a quick reply. I see that the acd upload wait defaults to 3m0s per GB. Have you heard of any desirable wait times that have proven fruitful? I'm going to attempt --acd-upload-wait-per-gb 10m0s.

**Comment by breunigs** [comment] 2017-01-31 12:30
You can also try to limit the throughput per file by using `bwlimit` option or just by increasing parallelism until they saturate your uplink, which helped when I tried to push big files. Note that this voodoo changes over time and it depends on the (amazon server) region you end up in.

If you're not in a hurry, setting a high limit will almost always help, though.

**Comment by robertclemens** [comment] 2017-01-31 15:09
So now I'm getting wrong file size matching with the longer wait.
It seems that ACD is just so unreliable. I may take to the forums to discuss reliable providers.

Rclone is quite possibly the best software I've found in the last year. I just wish the providers would provide a consistent storage experience to go along with it.

==> /tmp/rclone_log.1 <==
2017/01/31 09:06:07 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1304/2410)
2017/01/31 09:06:12 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1305/2410)
2017/01/31 09:06:17 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1306/2410)
2017/01/31 09:06:22 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1307/2410)
2017/01/31 09:06:27 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1308/2410)
2017/01/31 09:06:32 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1309/2410)
2017/01/31 09:06:38 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1310/2410)
2017/01/31 09:06:43 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1311/2410)
2017/01/31 09:06:48 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1312/2410)
2017/01/31 09:06:53 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1313/2410)
2017/01/31 09:06:58 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1314/2410)
2017/01/31 09:07:03 localFile.0.dmp_170131_035012: Object found but wrong size 21560052832 vs 23472313248 - waiting (1315/2410)

==> /tmp/rclone_log.2 <==
2017/01/31 09:07:04
Transferred:   21.855 GBytes (1.356 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:   4h35m2.8s
Transferring:
 *                 localFile.0.dmp_170131_035012: 108% done, 0 Bytes/s, ETA: 0s

**Comment by ncw** [comment] 2017-01-31 17:39
> Thanks for such a quick reply. I see that the acd upload wait defaults to 3m0s per GB. Have you heard of any desirable wait times that have proven fruitful? I'm going to attempt --acd-upload-wait-per-gb 10m0s.

The 3m was based on extensive testing and supposed to be a figure that will always work... However things change :-(

> So now I'm getting wrong file size matching with the longer wait.
It seems that ACD is just so unreliable. I may take to the forums to discuss reliable providers.

ACD does appear to have got less reliable over time.  Especially with big files....

**Comment by wikt0r** [comment] 2017-02-01 09:44
I can confirm something is wrong with ACD these days and not only with really big files. I am just uploading files to ACD and I got `Object not found - waiting (701/899)` for a 800MB (yes, under 1 GB) file. I am already using `--acd-upload-wait-per-gb=100m` paramter. :(

**Comment by kk7ds** [comment] 2017-02-01 22:20
I too am hitting this problem a lot with ACD. Just curious, but would it be better to wait a shorter amount of time and then just move on and let the full-sync retry pick up anything that didn't ever show up? I haven't yet had a situation where both of my uploaders are sitting idle waiting for something to appear, but I can see it on the horizon.

Also, would it make sense to spawn a temporary extra thread to do the waiting so that the upload pipeline isn't stalled?

**Comment by robertclemens** [comment] 2017-02-02 14:35
Can anyone confirm if this only happens when using crypt or does this also happen when just transferring to ACD without crypt as well?

**Comment by trustin** [comment] 2017-04-18 09:59
It happens without crypt for me.

**Comment by ncw** [comment] 2020-01-14 14:13
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.

**Closed by ncw** 2020-01-14 14:13 UTC
