### ISSUE TITLE
[GDrive + FUSE] 403 Forbidden Errors - API daily limit exceeded

### ISSUE THREAD

**Issue by natoriousbigg** [rclone/rclone#972] opened 2016-12-26 07:08 UTC
As discussed in the forum (https://forum.rclone.org/t/google-drive-vs-acd-for-plex/471), users are getting 403 forbidden errors and unable to file access when using rclone FUSE mount. This is especially with using Plex to access the mount. Appears to be related to exceeding daily API access: https://developers.google.com/drive/v3/web/handle-errors . Users will get a temporary ban from access files via rclone FUSE mount or download files. Access to the Google Drive website still seems to work and upload still works without issue. It seems the only viable solution is to have a local cache as mentioned in #897.

> What is your rclone version (eg output from `rclone -V`)
v1.34-75-gcbfec0dβ
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Ubuntu
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --verbose --no-traverse gdrive:test/jellyfish-40-mbps-hd-h264.mkv ~/tmp
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

	2016/12/26 05:43:12 Local file system at /home/xxxxxx/tmp: Modify window is 1ms
	2016/12/26 05:43:13 Local file system at /home/xxxxxx/tmp: Waiting for checks to finish
	2016/12/26 05:43:13 Local file system at /home/xxxxxx/tmp: Waiting for transfers to finish
	2016/12/26 05:43:13 jellyfish-40-mbps-hd-h264.mkv: Failed to copy: failed to open source object: bad response: 403: 403 Forbidden
	2016/12/26 05:43:13 Attempt 1/3 failed with 1 errors and: failed to open source object: bad response: 403: 403 Forbidden
	2016/12/26 05:43:13 Local file system at /home/xxxxxx/tmp: Waiting for checks to finish
	2016/12/26 05:43:13 Local file system at /home/xxxxxx/tmp: Waiting for transfers to finish
	2016/12/26 05:43:13 jellyfish-40-mbps-hd-h264.mkv: Failed to copy: failed to open source object: bad response: 403: 403 Forbidden
	2016/12/26 05:43:13 Attempt 2/3 failed with 1 errors and: failed to open source object: bad response: 403: 403 Forbidden
	2016/12/26 05:43:13 Local file system at /home/xxxxxx/tmp: Waiting for checks to finish
	2016/12/26 05:43:13 Local file system at /home/xxxxxx/tmp: Waiting for transfers to finish
	2016/12/26 05:43:13 jellyfish-40-mbps-hd-h264.mkv: Failed to copy: failed to open source object: bad response: 403: 403 Forbidden
	2016/12/26 05:43:13 Attempt 3/3 failed with 1 errors and: failed to open source object: bad response: 403: 403 Forbidden
	2016/12/26 05:43:13 Failed to copy: failed to open source object: bad response: 403: 403 Forbidden

**Comment by scoopydude2002** [comment] 2016-12-26 07:11
I don't know this API access limit is shared amount all rclone users or specific to each user's Google Drive account. But according here https://developers.google.com/drive/v3/web/handle-errors under "403: Daily Limit Exceeded" you can request additional quota @ncw

**Comment by rwenz3l** [comment] 2016-12-28 23:01
I'm running into this issue as well, referencing issue #647 . It appears that Google is setting a few limitations, some of them are public and some are not. It appears that once you hit the file limit, you cannot fetch any file at all, witch is a major bummer. The Problem seems to stay for a while. I'll try to contact google support on this and see what they recommend..

**Comment by scoopydude2002** [comment] 2016-12-28 23:21
Just an update, it seems that's not necessarily an API limit, because API access still works fine. Rclone mount Gdrive fine and you can even see the files. It's just can't you read or download files. For some reason it seems you can still read smaller files (around 20MB or less). But larger files you can't.

**Comment by rwenz3l** [comment] 2016-12-28 23:40
It definitely isn't connected to the API quotas on the Application page. I can still upload files with rclone to google but every file in my drive is locked. I contacted Google Support and will report back what they say.

I also discovered that small files seem to be ok.
My Limit appears to be around 8MB.. All file smaller than 8MB can be downloaded.. all files greater or equal 8MB are locked everywhere in my Drive. Even those not accessed (with or without rclone) at all.

This was tested in a Google Business Account.

**Comment by Korni22** [comment] 2016-12-29 14:54
Has anyone tried to contact google and raise the "download" quota? 🤔

**Comment by rwenz3l** [comment] 2016-12-29 15:00
I contacted google via mail/feedback but have not gotten any replies yet.

Also want to add, that my "Ban" is gone now. Seems like I did not have to wait 24 hours.

**Comment by Korni22** [comment] 2016-12-29 15:26
@rwenz3l I thought the ban is reset at [9 am PST](http://www.wolframalpha.com/input/?i=9+am+PST) - but I am not sure if that is just the API or also the "download" rate limiting 🤔

**Comment by martinbowling** [comment] 2016-12-29 17:30
Looks like my G Drive mount done with node-gdrive-fuse only shows each file downloaded once during the scan, now it does show files being downloaded multiple times during it being watched though.

**Comment by scoopydude2002** [comment] 2016-12-29 19:13
From my experience the length of the ban varies from a few hours up to 16 hours. There's no rhyme or reason to it.

@martinbowling Is node-gdrive-fuse will help preventing you from getting banned?

**Comment by jpat0000** [comment] 2016-12-29 19:33
@martinbowling 

If you're using Plex, it should access the file multiple times as it doesn't keep the file open when transcoding/it only accesses pieces at a time (maybe 10-20% of the file?). I imagine rclone has the same behavior, it's just harder to notice since verbose shows a flood of data.

**Comment by martinbowling** [comment] 2016-12-30 00:01
@jpat0000 you are correct forgot that chunk size is definable in config and it will grab file at least chunkSize / fileSize times

@scoopydude2002 yes don't have any ban issues with it but rclone performs better

**Comment by fbrassin** [comment] 2017-01-02 13:42
This is a really annoying problem.
I couldn't manage to solve it.
Every day a have a 24 hours api ban.
I hope someone can help with an idea.
I mount my google drive with:
nohup rclone mount --allow-other --umask 0 google:/ /media/Google &

Maybe any other optin can help?

**Comment by zenjabba** [comment] 2017-01-03 14:19
rclone -v mount --allow-non-empty --allow-other --max-read-ahead 200M --drive-chunk-size 128M --checkers 40 --dir-cache-time 30m --transfers=32 gsuites:/Plex /share/CACHEDEV1_DATA/gsuites

This is what I use to mount the file system. It seems my "banning" has been removed with this one, BUT I'm using my own client ID and client secret.

**Comment by jrwr** [comment] 2017-01-03 18:17
Im doing some testing with the suggested settings above, I've got a pretty big archive of crap, Ill report back my findings, I am using my own API key of course

**Comment by jrwr** [comment] 2017-01-04 00:08
Already banned, The console is saying that I did drive.files.list 1900 times at a rate of 0.023 and drive about.get 6 times.

**Comment by scoopydude2002** [comment] 2017-01-04 01:39
Where does it show you did drive.files.list? I use my ow API key and only sees total number of API hits.

**Comment by jrwr** [comment] 2017-01-04 01:44
[Screenshot](https://i.imgur.com/TTgH4Bq.png)

Its just listing by API Method

**Comment by fbrassin** [comment] 2017-01-04 09:05
@zenjabba 
What do you mean with?

>  BUT I'm using my own client ID and client secret.

Is there any difference from using rclone in the normal way?

**Comment by fbrassin** [comment] 2017-01-04 10:23
@jrwr 
I cannot see any info in that page.
How do you enable linsting?
I see no traffic at all.

**Comment by jrwr** [comment] 2017-01-04 15:09
I don't think you are using your own Client ID / Secret - Please see the Google Drive Document ion on the RClone website @fbrassin

**Comment by fbrassin** [comment] 2017-01-04 15:35
@jrwr  
Now i got it, tnx.

**Comment by scoopydude2002** [comment] 2017-01-04 18:49
I think the developer consult only shows API hits and not actually data transfer. API hits alone never hits the default limits for ban seems to be from data transfer and/or number of files access, although I don't know where this information is stored.

Anyone has success with contacting Google directly.

**Comment by zenjabba** [comment] 2017-01-04 18:56
I've got a case open with Google at the moment, but not sure what else to ask them.

**Comment by jrwr** [comment] 2017-01-05 04:01
This is pretty stupid overall, makes working with drive impossible

**Comment by fbrassin** [comment] 2017-01-05 07:28
Just to let you know.
After creating my own id and secret and mount as suggested:
rclone -v mount --allow-non-empty --allow-other --max-read-ahead 200M --drive-chunk-size 128M --checkers 40 --dir-cache-time 30m --transfers=32 gsuites:/Plex /share/CACHEDEV1_DATA/gsuites

For the moment i had no ban.
Before making this i had bans.

**Comment by scoopydude2002** [comment] 2017-01-05 07:57
I'll give those settings a try. Ironically, I reduce the --checkers to 4 to reduce API hits but I got banned even faster.

**Comment by jrwr** [comment] 2017-01-05 09:13
as a note, I'm using mergerfs ontop of gdrive because ACD is not fully copied over yet
Im doing some MD5sums to test and see if I can get it to ban using "normal" usage

**Comment by ncw** [comment] 2017-01-05 11:02
Sorry late to the party!  I looked at the drive console for rclone.  I can see that rclone isn't approaching its global queries per second limit (I got google to raise that to 500 QPS in November 2016).

From my analysis of the error codes it seems to be directory listings that are causing the problems..

Can anyone reproduce the problem just using `rclone ls` commands?  Or is it something specific to what plex is doing?

**Comment by fbrassin** [comment] 2017-01-06 08:16
I'm totally newbie about rclone, but as my ban stopped as soon as i used my own id and secret, maybe is it possible that the ban came because most of people used the same id (default one) and reached some kind of limit?

**Comment by spencercharest** [comment] 2017-01-06 16:39
@fbrassin after reading through the thread yesterday I followed your suggestion and created my own client ID and secret and mounted with your suggested parameters. I still received the ban. It may help for smaller libraries but I think people with larger libraries will still have issues.

**Comment by scoopydude2002** [comment] 2017-01-06 17:55
I have a 17TB library and still getting banned even after using my own client ID and secret and using the above mount settings. I think using rclone's library might be better because @ncw had google increases the API hit quote. Ban used to occur after 6 hours but been occurring now after 2-3 hrs. This is even after disabling Plex scheduled tasks and library updates, and turning off Sickbeard and CouchPotato.

**Comment by zenjabba** [comment] 2017-01-06 18:46
@spencercharest what is interesting is I have a 87tb library, and if I use my own client id... no ban

**Comment by spencercharest** [comment] 2017-01-06 18:53
Yeah it seems to be specific to how Plex analyzes files. I have been experimenting with Kodi instead of Plex and have not received a ban using Kodi.

**Comment by scoopydude2002** [comment] 2017-01-07 06:48
It would be worthwhile to see if Emby also causes ban if someone would give it a try.

**Comment by fbrassin** [comment] 2017-01-07 07:56
@scoopydude2002 
I don't know why i don't have the ban while you do. My library is about 6TB. Maybe it is not too big.

**Comment by scoopydude2002** [comment] 2017-01-07 08:06
@fbrassin I'm not sure about the size either. Are you having Plex directly read your rclone mount? I'm using unionfs to merge the rclone mount with a local folder. I was using the fuse option "auto_cache" with unionfs and wonder if this was causing excessive I/O. Seem to be a little better with this option. I'm also thinking of delete all small files (subtitles, nfo file, thumbnails, trailers) and only keep larger media files. This will at least reduce the number of files and require less API hits.

**Comment by fbrassin** [comment] 2017-01-07 08:10
What do you read in google console about api usage?

**Comment by spencercharest** [comment] 2017-01-10 18:15
I've had some luck the past couple of days by doing this... I added 2 google drives in the rclone config using the same Google account. For the first I used rclone default client id and secret. I use this one strictly for uploading. For the second I used my own client id and secret. I use this one for mounting using the parameters @fbrassin posted above. I have not received a ban since trying this. I haven't done much testing so I have no idea if this is what actually caused it to work but I guess (in theory) it would be dividing up the API hits up at least a little bit.

**Comment by DerUntote** [comment] 2017-01-15 07:55
I´am doing the same like you @spencercharest. But i receive Bans everyday.

**Comment by jrwr** [comment] 2017-01-15 18:48
I have found that doing Plex indexing with local files first then moving to
the backing store (GDrive) helps a ton since media indexing is done within
the first few hours plex knows of a video existing. I use MergerFS,
download everything to local disk first using a read only GDrive then
uploading from the staging folder to gdrive nightly, Plex updates its
library hourly. So far no bans with the community IDs but this does require
having the Plex Server on the same box as the Ingress server

**Comment by NeoPhyTe-x360** [comment] 2017-01-16 11:58
I still getting banned. I have a custom id+secred, and in api website, the requests don't go over 200/100s

My library is about 23Tb, but I think problem is related to a lot of "lists requests" in a short period of time.

This is the mount command I'm using now: 
`rclone mount google: /media/gdrive --allow-non-empty --allow-other --max-read-ahead 200M --dir-cache-time 30m --checkers 3 --umask 000 --drive-use-trash &
`

**Comment by jackalblood** [comment] 2017-02-03 17:32
I also really hope to see a fix for this I'm running both acd and gdrive and the peering with gdrive is far superior

**Comment by zenjabba** [comment] 2017-02-03 17:33
We are all hoping to see this fixed.

**Comment by jackalblood** [comment] 2017-02-11 09:22
Amazon blocked my account today waiting to hear from them to see if I'm getting it back or not so I'd be happy to see this even more now

**Comment by IKShadow** [comment] 2017-02-11 09:52
@jackalblood call the support dont email them, i had my account blocked multiple times and it was always unlocked within 5 minutes by calling them. First time several months ago I email them and waited for 2 days and the first reply was they are looking into it. 

p.s. Amazon is a bit touchy once your average bandwith breach 2Gbit ( i was always locked when using multiple servers to upload/download data )

**Comment by jackalblood** [comment] 2017-02-11 09:54
Sadly I did call them and was told it's permanent so I span a story about using it on 3 pcs running vpn which isn't actually a lie I am and I'm alone in using it too so I've been told it will be sent on to technical and I'll hear back in 3 days

**Comment by ajkis** [comment] 2017-02-12 01:53
What is their reason for ban ? 

Check their claim when they ban me twice within a week: 

> Now to your issue about the locked Amazon Drive:
> 
> Your account was locked on 2016/11/25 and again on 2016/11/30 because you downloaded hundreds of terabytes of data in a single 24 hour period.
> 
> Since it is not generally possible for a single user with a non-commercial internet connection to do this, nor would it be reasonable for a single user to do so when the account only contains a fraction of this much data, it indicates to us that you are using Amazon Drive in a manner which violates our terms of use.

I uploaded from 4 server close to full 1GPBs speed each when those bans happened, but still the claim of   hundreds of terabytes its a bit absurd , i told them i wish I had access to such awesome internet as even 10GBPs line could not do it :)

I explained them that Iam using acd on 2PC's at home + my notebook and my work PC and that iam moving all my backups to amazon drive. 

I also asked for official email from that with exact reason why my account was blocked so they appologized and unblocked me and somoene else called me within an hour and told me that my account was blocked with auto scripts that is blocking all high bandwith users.

They would not reveal ( he did not know) whats the limit as i explained I could set it if I knew what it is.

Since then my account was blocked at least 3 or 4 more times but after mid December all blocks stopped and I intentionally was pushing tons of data  to acd.

>                       rx      /      tx      /     total    /   estimated
>  enp7s0:
>        Jan '17    124.31 TiB  /  125.72 TiB  /  250.03 TiB
>        Feb '17     67.32 TiB  /   67.78 TiB  /  135.10 TiB  /  340.33 TiB
>      yesterday      8.31 TiB  /    8.31 TiB  /   16.62 TiB
>          today    988.06 GiB  /  988.24 GiB  /    1.93 TiB  /   16.74 TiB


Btw on my 5 or 6th ban i did call support twice as the person on other side just would not discuss it and told me they will look into it. So i just called again got another representative, told him that I need to get my data as my family is visiting and we have all home videos and pictures on .. he did not even ask anything just told me your account is unblocked. 

I really dont belive there is a perm ban with Amazon except if they ban for illegal content eg unencrypted data. 

p.s. There is a guy with 1.5PB uploaded to ACD so far and was not banned once, but he is uploading just with 1GB speed.

**Comment by jackalblood** [comment] 2017-02-13 19:53
They are yet to give me a reason for the ban and I've spoken to 3 different people and all I keep being told is I have to wait for technical team to contact me

**Comment by jackalblood** [comment] 2017-02-13 19:53
Oh also everything on my drive is encrypted regardless of what it was

**Comment by romanturbo** [comment] 2017-04-04 15:08
any news?

**Comment by jackalblood** [comment] 2017-04-04 16:54
They finally unbanned me after a 2 week process and haven't been banned since so I asked what the reason was for the ban and received a phone call 3 days later and the guy basically said that my in and out traffic was more then what was considered normal and this could be caused by third party apps keeping data in sync to which my reply was how am I meant to use Amazon on a Linux pc if they don't offer any 1st party application his reply was basically you can't and to carry on using 3rd party programmes and see what happens so basically after the whole ordeal nobody knew exactly the reason I was banned

**Comment by RikuXan** [comment] 2017-04-08 16:57
Would it make sense to add a randomized quotaUser parameter to GDrive API calls for people who have set their own client ID and secret? I feel like the first limit one would hit with the default quotas is the 1,000 queries per 100 seconds per user limit. Using the quotaUser parameter (as far as I understand it) would result in having 10,000 queries per 100 seconds available and could help people between 10 and 100 calls per second.

Still I'm not sure if that would help with the bans overall, since it seems Google is handing out bans even when far below any quota (at least for me).

**Comment by zenjabba** [comment] 2017-04-08 21:10
Wouldn't make any difference, it's to do with the specific "drive" account not the client ID. I tested it yesterday with an identical copy from two different accounts and when one got banned, simply changed to the next account (keeping the CID and CS) the same, and it continued working fine.

**Comment by benjamato** [comment] 2017-04-24 20:38
Any chance this API ban has anything to do using a unionfs mount with a rclone mount?  I never had bans with plex pointed directly at my rclone google drive mount folder and local folder but when I created a unionfs mount folder for those two paths and pointed Plex at it instead, then the bans started almost daily.

**Comment by RikuXan** [comment] 2017-04-29 22:06
After some days of testing, it seems that disabling Sub-Zero in Plex stopped the bans altogether for me. So that might be something to explore for people using it as well and experiencing bans.

**Comment by zenjabba** [comment] 2017-04-29 22:27
Will give SubZero removal a change.. will report back in 24 hours.

**Comment by zenjabba** [comment] 2017-04-30 03:44
I can confirm it doesn't make any different for me, after 4 hours, 403 Forbidden.

**Comment by jackalblood** [comment] 2017-04-30 09:16
Same result here I'm afraid and come to think of it it happend way before I installed sub-zero right now I'm using google-drive-ocamlfuse with great success been using it for months no bans but the mount is up and down like a yo-yo

**Comment by tcf909** [comment] 2017-06-02 18:32
I ran in to this issue as well. I love RCLONE and was looking for a way to move away from the ACD B.S. Moved my data to Google Drive (without issue), but as soon as I started using Drive as my media source I started getting 403's.

I'm using my own client id / client secret (api app).

After a day, I tried out google-drive-ocamlfuse as my mount to google drive, and then using rclone crypt against that directory (and then mergerfs on top of rclone mount) to provide media to plex.

The 403's have more or less gone away. I will say though, google is MUCH more restrictive around access patterns etc.

I don't actually believe are problems are JUST the public API limit. Google is running some behind the scenes limits (publicly acknowledged) but won't publish those limits.

Definitely looking forward to RCLONE being able to accommodate Drive's access pattern limitations.

**Comment by rwenz3l** [comment] 2017-06-02 23:01
maybe checkout https://github.com/dweidenfeld/plexdrive .. also maybe rclone can implement some of the techniques introduces there to reduce API hits. Works really well for me.

**Comment by zenjabba** [comment] 2017-06-02 23:05
@tcf909 What I have that is working great is

1. plexdrive /mnt/plexdrivero
2. rclone /mnt/plexdriverw
3. unionfs with plexdrivero=RO:plexdriverw=RW /mnt/plexdrive

and reading gets done by plexdrive
and writing get done my rclone 

best of both worlds.

**Comment by silvether** [comment] 2017-06-11 23:32
Would directory caching functionality in rclone fix this issue? It seems other tools that do directory structure caching don't seem to run into the issues expressed above. I could have sworn I saw a feature request for something like this. Thoughts?

**Comment by jackalblood** [comment] 2017-06-11 23:35
It seems that would be the case since having a cache seems to cut down api and folder access dramatically and I've not had a single ban ever since setting up google-drive-ocamlfuse 

⁣Sent from TypeApp ​

**Comment by Enderswood** [comment] 2017-07-20 11:56
> It seems that would be the case since having a cache seems to cut down api and folder access dramatically and I've not had a single ban ever since setting up google-drive-ocamlfuse ⁣

do you also use encryption ? 
does mount with google-drive-ocamlfuse then use with rclone local drive could can work ?

**Comment by animosity22** [comment] 2020-01-10 12:28
Legacy issue and has been resolved. If any new questions, please use the forums for them.

**Closed by animosity22** 2020-01-10 12:28 UTC
