### ISSUE TITLE
[Feature Request]: Transparent de(en)cryption of mounted directory using gpg

### ISSUE THREAD

**Issue by rowhit** [rclone/rclone#922] opened 2016-12-01 16:06 UTC
Hi,

I am new to rclone. I really liked the project. It almost has all the feature I need for cloud backup. However, it would be great if the above mentioned feature is implemented.

Assuming following directories
- /path/to/encrypted/dir
-/path/to/decrypted/dir
implement something similar to the following:
rclone mount --decrypt-gpg "gpg-key-fingerprint" /path/to/encrypted/dir /path/to/decrypted/dir
rclone umount /path/to/decrypted/dir

Now, the sync process can continue in the background for encrypted dir and user can continue working . I am not sure, if the backup can corrupted if work is being done simultaneously on decrypted dir.

**Comment by ncw** [comment] 2016-12-02 14:46
You can make a workflow like this already using rclone's built in crypt support.

Why do you particularly want to use gpg?

**Comment by davidstrauss** [comment] 2017-02-06 18:12
I don't particularly care about mounting with rclone (versus syncing), but I would like to use GPG because I have a smart card that allows me to keep my secret keys isolated from my laptop. Basically, I'd like something similar to Password Store, where I can configure the GPG key IDs that should be able to read the data.

GPG support would also allow using OpenKeychain as a foundation for an Android app. OpenKeychain can work with NFC-accessible GPG tokens.

**Comment by ncw** [comment] 2017-02-08 10:07
@davidstrauss 

So instead of reading the encryption keys from the rclone config file, rclone would read them from the gpg agent - is that right?

Any idea what the gpg command line would look like for that?

I could add an option to rclone which would run a command to get the key material quite easily.

Though if you can run a command to get key material then you can (using a recent beta) set environment variables with the keys in before running rclone quite easily.  If you had an encrypte remote called `eremote` then you could set `RCLONE_EREMOTE_PASSWORD` and `RCLONE_EREMOTE_PASSWORD2` and take the `password` and `password2` lines out of the config.

**Comment by davidstrauss** [comment] 2017-02-22 20:57
> So instead of reading the encryption keys from the rclone config file, rclone would read them from the gpg agent - is that right?

Unfortunately, it would require a more radical approach to provide the main benefits of GPG.

This is what I would recommend:

1. Every file has its own symmetric encryption key. Additionally, this key should change whenever the file changes to prevent public keys with revoked access from being able to read new revisions of the file.
2. Use GPG to encrypt the symmetric key so that it's decryptable by the specified public keys. This gets written alongside the primary, symmetrically encrypted data.

Benefits of this approach:
* By only using public keys to encrypt the symmetric key, this method works with files of any size and should be very fast. (Using GPG to directly encrypt files with public keys does not scale well with file size.)
* The private key stays protected by the GPG agent (at a minimum) or a hardware smart card (at a maximum).
* The GPG agent's cache allows sustained access without re-entering a passphrase (agent) or PIN (smart card) every time a file needs to be decrypted.
* It's possible to have some machines that can only encrypt and send files, not decrypt. This is useful when having, say, remote machine rclone to back up data.

**Comment by davidstrauss** [comment] 2017-02-22 21:11
I should be more clear with my recommendations. Here's how it would work for writing and reading. All of the file names are, of course, suggestions.

Writing a file (including a new revision of an existing file):

1. Generate a new symmetric key.
2. Encrypt the file using the key. AES-256 is quite good for this, and it's hardware-accelerated on many machines. Store this file as something like `FILENAME.ext.aes`.
3. Load the list of authorized public keys from `.gpg-id`.
3. Encrypt the symmetric key using GPG to the authorized public keys. (The private key is not necessary here.) Store this in something like `FILENAME.ext.key.gpg`.
4. Upload both files.

Reading a file:

1. Download both the `.aes` and `.key.gpg` files.
2. Decrypt the symmetric key from the `.key.gpg` file using GPG. This decryption may actually occur on a smart card, but the GPG agent abstracts all of that.
3. Use the symmetric key to decrypt the file.

Adding a new authorized GPG key:

1. Update `.gpg-id` to add the new key ID.
2. Using an existing GPG key, decrypt each `.key.gpg` file and re-encrypt to include all authorized keys.
3. Upload the altered (and small) `.key.gpg` files.

Revoking an authorized GPG key:

1. Update `.gpg-id` to add the remove the key ID. All future files and revisions will now be unreadable by the revoked authorization.
2. Optional: Re-encrypt existing files as if creating a new revision, removing the ability of the revoked key to read the current data.

**Comment by leeparayno** [comment] 2017-09-20 17:38
@ncw Has there been any movement on this issue to implement gpg.  I have a requirement to use gpg at my company with syncing to cloud storage volumes and this project looks like a perfect fit, but we would require gpg encryption/decryption of files before they are uploaded to cloud storage.  If this could be handled by rclone, that would complete the cycle.

**Comment by batpudding** [comment] 2018-11-15 11:22
GPG encryption would have a clear advantage regarding future proofing.  The things I would be concerned about are the lack of direct access and corralling GPG to make it produce the same encrypted result for checksum verification.

This could be as simple as a generic cryptlike filter that calls third party programs to encrypt/decrypt:
- command to pipe file data while uploading
- command to pipe file data while downloading
- command to encrypt filename
- command to decrypt filename

Ultimately this is just a shortcut for encrypting everything locally before uploading it, I guess.

**Comment by ivandeex** [comment] 2020-11-15 14:25
Duplicate of https://github.com/rclone/rclone/issues/4292 and https://github.com/rclone/rclone/issues/1295 with minor deviations

**Comment by ivandeex** [comment] 2020-11-15 14:26
Duplicate of https://github.com/rclone/rclone/issues/1295

**Comment by ivandeex** [comment] 2021-10-16 20:28
closing out duplicates

**Closed by ivandeex** 2021-10-16 20:28 UTC
Labels: duplicate, enhancement, Remote: Crypt, integration
