### ISSUE TITLE
Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH

### ISSUE THREAD

**Issue by lansexiatian** [rclone/rclone#6856] opened 2023-03-16 13:42 UTC
What is the problem you are having with rclone?

Using the volume plugin in 1.6.2 fails with missing dependency

What is your rclone version (output from `rclone version`)
Because there was a problem when mounting, I tested two versions.
1.rclone v1.62.2
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-22-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

2.rclone v1.63.0-beta.6813.0e134364a
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-22-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

 ubuntu 18.04 (64 bit)

Which cloud storage system are you using? (e.g. Google Drive)

Microsoft Onedrive

The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

1.root@hatsunemiku:~# rclone mount Summer:/ /www/wwwroot/spring.hatsunemiku.life/Onedrive --copy-links --no-gzip-encoding --no-check-certificate --allow-other --allow-non-empty --umask 000 --vfs-cache-mode writes
2023/03/16 06:33:01 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH

2.root@hatsunemiku:~# rclone mount Summer:/ /www/wwwroot/spring.hatsunemiku.life/Onedrive --copy-links --no-gzip-encoding --no-check-certificate --allow-other --allow-non-empty --umask 000 --vfs-cache-mode writes
2023/03/16 06:31:54 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH

A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

See above
![uTools_1678974090412](https://user-images.githubusercontent.com/70825804/225636356-78bdcedd-c25f-4468-a85b-86a50d6c34c6.png)

This problem was discovered on March 14th. At first, it was thought that the fuse on the server was missing, but it could not be updated and installed. I just found the rclone update submitted by the author. I tested it at the first time and found that there is still such a problem. So I give feedback to the author and look forward to solving it as soon as possible.（"Because my English is relatively poor, I almost communicate through computer translation. I hope you will understand".）

**Comment by lansexiatian** [comment] 2023-03-16 14:47
![uTools_1678977851932](https://user-images.githubusercontent.com/70825804/225653458-eb32e1c2-2159-48ae-be98-df51d8726499.png)

[var-mail-root.txt](https://github.com/rclone/rclone/files/10992146/var-mail-root.txt)

**Comment by cycneuramus** [comment] 2023-03-16 15:03
You're using a version of Ubuntu from 2018 (EOL in April, by the way) that most does not package `fuse3`.

**Comment by snickers2k** [comment] 2023-03-17 16:44
same problem here 

rclone v1.62.2
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-144-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

**Comment by cycneuramus** [comment] 2023-03-17 17:05
Have you installed `fuse3`?

**Comment by Greatdane** [comment] 2023-03-18 04:01
See https://github.com/rclone/rclone/issues/6844

Installing `fuse3` did not fix the problem for me, but using the latest rclone:beta docker image mentioned in the above issue did.

**Comment by cycneuramus** [comment] 2023-03-18 12:16
1. Running rclone in Docker? Use the latest version, where `fuse3` is included in the image.
2. Running rclone on bare-metal? Install `fuse3`.

I think this issue should be closed.

**Comment by ncw** [comment] 2023-03-20 11:46
The root cause of this issue is that our upstream bazil/fuse switched to using fuse3, so rclone had to too.

I didn't realise that there would be so many distros not using fuse3 but there you go!

There is another alternative to switching to fuse3 - compile your own rclone with `go build -tags cmount`. This will build rclone with the `rclone cmount` command and you can use this in place of `rclone mount` and this **will** run on a fuse2 system.

We don't do this by default because that would involve building different rclones for all the different distros as it needs to link with the C library at that point.

Anyway, I think the docker images are fixed now in v1.62.2 so I will close this issue.

**Closed** 2023-03-20 11:46 UTC

**Comment by ncw** [comment] 2023-03-22 16:06
Note that another solution is

    ln -s /bin/fusermount /bin/fusermount3

This works well.

**Comment by samucamg** [comment] 2023-03-30 22:02
> Note that another solution is
> 
> ```
> ln -s /bin/fusermount /bin/fusermount3
> ```
> 
> This works well.

Thank you!
That solve my problem on ubuntu 20.04

**Comment by simprovider** [comment] 2023-05-31 14:11
simple:

`echo 'deb http://download.opensuse.org/repositories/home:/alvistack/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/home:alvistack.list`

`curl -fsSL https://download.opensuse.org/repositories/home:alvistack/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_alvistack.gpg > /dev/null`

`sudo apt update`

`sudo apt install fuse3`

:)

**Comment by samucamg** [comment] 2023-05-31 16:06
or just cp /bin/fusermount /bin/fusermount3

Just work in many installations I made.


Em qua., 31 de mai. de 2023 às 11:11, simprovider ***@***.***>
escreveu:

**Comment by MestreLion** [comment] 2023-06-21 07:07
@cycneuramus 
>     2. Running rclone on bare-metal? Install `fuse3`.

Shouldn't the `.deb` package have `fuse3` as a dependency then? 

> I think this issue should be closed.

Perhaps, and maybe open a new one about fixing the `.deb` package?

**Comment by jlbturbo** [comment] 2023-09-26 09:27
I am currently getting the same error message, however I am running Ubuntu 22.04.2 on WSL, and have Fuse3 installed
