### ISSUE TITLE
Some files not uploaded to Amazon Drive

### ISSUE THREAD

**Issue by holygamer** [rclone/rclone#1105] opened 2017-02-05 16:44 UTC
> What is your rclone version (eg output from `rclone -V`): rclone-v1.35-windows-amd64

> Which OS you are using and how many bits (eg Windows 7, 64 bit): Windows 7, 64 bit

> Which cloud storage system are you using? (eg Google Drive): Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) copy

I'm copying a folder of MKVs to my Amazon Drive. I'm using RClone Browser as a GUI. I left it running overnight and it says 97 GB was transferred yet I only see 36 GB uploaded (3 files out of 17). RClone Browser says 3 files were transferred and it says there are no errors or checks.

Once a file is uploaded should it appear instantly on my Amazon Drive?
If an upload stops due to my internet disconnecting, what happens?
If it says 97GB was transferred then does that mean that 97GB of files are on Amazon Drive or could it mean that 97GB of files were partially transferred but failed to upload due to network disconnecting?
How can I access a log to see what happened to the missing files?

**Comment by ajkis** [comment] 2017-02-05 19:58
Are you trying to transfer any file bigger then 50GB ?

**Comment by holygamer** [comment] 2017-02-05 20:01
No. The files are each under 20 GB. Also tried other programs:

Amazon Drive's desktop software fails after a few hours with this message: "File Name Conflicts". All files have unique names so that makes no sense. Only a few files were uploaded.

Air Explorer after a few hours my uploads failed with this error: "Unable to write data to the transport connection. An existing connection was forcibly closed by the remote host". Only a few files were uploaded.

**Comment by ncw** [comment] 2017-02-05 20:32
Amazon is quite unreliable uploding large files.  When they fail, rclone will try again - hence the 97GB transferred but only 36 GB uploaded.

> Once a file is uploaded should it appear instantly on my Amazon Drive?

yes

> If an upload stops due to my internet disconnecting, what happens?

You'll have to start the upload again.

> If it says 97GB was transferred then does that mean that 97GB of files are on Amazon Drive or could it mean that 97GB of files were partially transferred but failed to upload due to network disconnecting?

See above for the most likely explanation - Amazon being unreliable with big files.

> How can I access a log to see what happened to the missing files?

Use `--log-file` to store the log somewhere.  Use `-v` for more detail.

**Comment by holygamer** [comment] 2017-02-05 21:32
OK thanks. I know Amazon's own software can pause and resume uploads but does it also resume uploads that fail due to the network disconnecting for a minute or so?

**Comment by ncw** [comment] 2017-02-05 21:44
@holygamer 
> I know Amazon's own software can pause and resume uploads but does it also resume uploads that fail due to the network disconnecting for a minute or so?

Yes it can, but it uses an unpublished API unfortunately :-(  Some work had been done to work out what it is doing, but it isn't ready for use in rclone yet.

**Comment by holygamer** [comment] 2017-02-05 21:50
Strange. I actually came to rClone after Amazon Drive's own desktop software didn't work very well. Amazon Drive's desktop software fails after a few hours with this message: "File Name Conflicts". All files have unique names so that makes no sense. Only a few files were uploaded.

**Comment by ncw** [comment] 2017-02-05 22:19
>  Amazon Drive's desktop software fails after a few hours with this message: "File Name Conflicts". All files have unique names so that makes no sense. Only a few files were uploaded.

That is caused by uploading a file that has already been uploaded without checking it already exists.  rclone has that problem too sometimes, though much less recently.

**Comment by holygamer** [comment] 2017-02-05 22:27
Expect there was literally nothing on my Amazon Drive.  Tried to upload several files totalling 200GB and only about 30 GB of files uploaded. Most of them gave the "File Name Conflicts" error!

**Comment by animosity22** [comment] 2020-01-13 18:56
RIP ACD.

**Closed by animosity22** 2020-01-13 18:56 UTC
