### ISSUE TITLE
cache: rclone reports inability to move file on same remote with error "can't move - not same remote type"

### ISSUE THREAD

**Issue by scottmlew** [rclone/rclone#3907] opened 2020-01-27 05:55 UTC
Please refer to https://forum.rclone.org/t/still-unable-to-move-files-on-gdrive/13921

I am using the latest release of rclone on Win2016 and Win10 64-bit. Other info is in the linked thread.

**Comment by ivandeex** [comment] 2021-01-22 23:40
@scottmlew 
Could you try rclone 1.53.4?
Does the problem persist?

**Comment by scottmlew** [comment] 2021-01-23 02:31
@ivandeex I will try it as soon as I can, hopefully Saturday.

**Comment by scottmlew** [comment] 2021-01-23 21:18
@ivandeex The problem still persists with v1.53.4.

**Comment by ncw** [comment] 2021-01-25 12:34
I think the root cause of this is a cache backend bug, so it is unlikely to get fixed.

@scottmlew have you tried using --vfs-cache-mode full instead of the cache backend?

**Comment by scottmlew** [comment] 2021-01-25 19:26
@ncw that only applies to mounts, right? I am not using mounts.

**Comment by ncw** [comment] 2021-01-28 18:23
> that only applies to mounts, right? I am not using mounts.

Yes you are right `--vfs-cache-mode full` only applies to mount and rclone serve. One day I'll merge the vfs backend which will allow you to add a vfs cache to normal rclone commands.

**Comment by ivandeex** [comment] 2021-01-28 18:34
@ncw
As the cache backend is deprecated and VFS caches only for mount and only at the final stage,
does rclone support caching intermediate results between leaf storage backends like S3
and intermediate backends like compress or chunker?

**Comment by ncw** [comment] 2021-01-30 17:55
@ivandeex wrote:
> As the cache backend is deprecated and VFS caches only for mount and only at the final stage,
> does rclone support caching intermediate results between leaf storage backends like S3
> and intermediate backends like compress or chunker?

Not yet. What I want to do is make a VFS wrapper for any backend which will be able to do that. That will unify the internals of rclone. This will be backend which a) wraps a VFS wrapping a backend b) also implements the VFS interface

**Comment by ivandeex** [comment] 2021-02-26 04:36
unfortunately the developer who started cache backend is no longer with rclone, and we don't have a maintainer.
this backend  deprecated and will not receive new fixes.
later @ncw can develop an alternative that mimics it but is based on the vfs code.

i am going to close this ticket.
sorry about that.

**Closed** 2021-02-26 04:37 UTC
Labels: Remote: Cache, VFS / mount, bug, needs retest
