### ISSUE TITLE
sftp: Update ReadFrom failed: failed to send packet: EOF errors and very slow

### ISSUE THREAD

**Issue by rustycanb** [rclone/rclone#5197] opened 2021-04-02 23:29 UTC
#### What is the problem you are having with rclone?

Version 1.55.0
2021-04-03 09:56:22 ERROR : Attempt 1/3 failed with 1 errors and: Update ReadFrom failed: Connection Lost
Transferred:        9.273M / 508.719 MBytes, 2%, 139.669 kBytes/s, ETA 1h1m1s
The same file transferred with 1.54.1
Transferred:      499.910M / 499.910 MBytes, 100%, 1.307 MBytes/s, ETA 0s
Checks:                 4 / 4, 100%
Transferred:            1 / 1, 100%
Elapsed time:      6m28.6s

#### What is your rclone version (output from `rclone version`)

rclone v1.55.0
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount

#### Which cloud storage system are you using? (e.g. Google Drive)

sftp (rsync.net)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone sync -P /path/to/upload/ rsyncxxx:path/to/file/

**Comment by rustycanb** [comment] 2021-04-03 00:29
Part output from rclone --vv. file.ext is 499MB
2021-04-03 11:04:38 DEBUG : sftp://xxxx@xxxx.usw-s003.rsync.net:22/path/to/file/: Waiting for transfers to finish
2021-04-03 11:05:38 DEBUG : sftp://xxxx@xxxx.usw-s003.rsync.net:22/path/to/file/: closing 1 unused connections
2021-04-03 11:05:40 DEBUG : sftp://xxxx@xxxx.usw-s003.rsync.net:22/path/to/file/: New connection myip:port->69.43.165.3:22 to "SSH-2.0-OpenSSH_8.2-hpn14v15 FreeBSD-openssh-portable-8.2.p1_1,1"
2021-04-03 11:05:42 DEBUG : file.ext: Removed after failed upload: failed to send packet: EOF
2021-04-03 11:05:42 ERROR : file.ext: Failed to copy: Update ReadFrom failed: failed to send packet: EOF
2021-04-03 11:05:42 ERROR : sftp://xxxx@xxxx.usw-s003.rsync.net:22/path/to/file/: not deleting files as there were IO errors
2021-04-03 11:05:42 ERROR : sftp://xxxx@xxxx.usw-s003.rsync.net:22/path/to/file/: not deleting directories as there were IO errors
2021-04-03 11:05:42 ERROR : Attempt 3/3 failed with 1 errors and: Update ReadFrom failed: failed to send packet: EOF
Transferred:       24.551M / 24.551 MBytes, 100%, 130.934 kBytes/s, ETA 0s
Errors:                 1 (retrying may help)
Checks:                 9 / 9, 100%
Elapsed time:      3m19.3s
<6>INFO  : 
Transferred:   	   24.551M / 24.551 MBytes, 100%, 130.934 kBytes/s, ETA 0s
Errors:                 1 (retrying may help)
Checks:                 9 / 9, 100%
Elapsed time:      3m19.3s

<7>DEBUG : 11 go routines active
Failed to sync: Update ReadFrom failed: failed to send packet: EOF

**Comment by ncw** [comment] 2021-04-03 11:34
This looks like a failure within the sftp library.

It might be some sort of networking problem.

Is it 100% repeatable?

I have an rsync.net account I can test things on.

In testing this I found a performance regression - v1.54 transfers at  aout 300KB/s whereas 1.55 transfers at about 100KB/s

rsync.net is a long way from me ~150ms so it is the long fat pipe TCP problem.

I used git bisect to discover that this is the problem commit 713f8f357dc5eb512f736ad97cb092dfbd1dbfe9

>     sftp: fix "file not found" errors for read once servers - fixes #5077
>     
>     It introduces a new flag --sftp-disable-concurrent-reads to stop the
>     problematic behaviour in the SFTP library for read-once servers.
>     
>     This upgrades the sftp library to v1.13.0 which has the fix.

I've bisected this futher and reported it to the sftp package bug tracker: https://github.com/pkg/sftp/issues/426

In the mean time can you try this which reverts the the library to v1.12.0 and see if it fixes your problem

[v1.56.0-beta.5357.b89d085cb.fix-5197-sftp-regression](https://beta.rclone.org/branch/fix-5197-sftp-regression/v1.56.0-beta.5357.b89d085cb.fix-5197-sftp-regression/) on branch [fix-5197-sftp-regression](https://github.com/rclone/rclone/tree/fix-5197-sftp-regression) (uploaded in 15-30 mins)

**Comment by rustycanb** [comment] 2021-04-03 21:07
Thanks for your quick response.

The problem is 100% reproducible using sftp. (Not relevant, I guess, but I have another backup using rclone to a webdav server which succeeds.)

Ping to rsync.net is 200-250m/s for me, so also a long way, but has been consistent and reliable for 2 years using rclone (thanks).

I tried v1.56.0-beta but the uploaded failed with:
2021-04-04 06:41:26 ERROR : Attempt 3/3 failed with 1 errors and: Update Close failed: failed to send packet: EOF

Although the speed was normal and 3 times faster at 1.418 MBytes/s than v1.55.0

I'm happy to keep trying and thanks again.

**Comment by rustycanb** [comment] 2021-04-03 23:46
BTW, as expected, all sync/copy actions succeeded to Mega and webdav accounts with v1.55.0 and v1.56.0-beta.

To try and eliminate any network issues, all test (including rsync.net) carried out with and without wireguard VPN. No difference to results or speed.

**Comment by WhatIsThisAllAboutSilly** [comment] 2021-04-04 11:20
I can confirm that this has also resolved my issues with 1.55 and various 1.56 betas (Slow SFTP speeds and EOF issues).

**Comment by ncw** [comment] 2021-04-04 18:06
I managed to reproduce the EOF failure and I'm trying to bisect the problem - it may take a while...

**Comment by ncw** [comment] 2021-04-04 18:54
Bisect worked and came up with this very likely candidate

> commit a3fcadddc871e646f7ce756fa5d168d4bdd6997c
> Author: Nick Craig-Wood <nick@craig-wood.com>
> Date:   Fri Feb 12 18:41:37 2021 +0000
> 
>     sftp: close idle connections after --sftp-idle-timeout (1m by default)
>     
>     This fixes a problem where sftp backends live on forever when using
>     the rc and use more and more connections.
>     
>     Fixes #4883
> 
>  backend/sftp/sftp.go | 70 +++++++++++++++++++++++++++++++++++-----------------
>  1 file changed, 48 insertions(+), 22 deletions(-)

This was released in v1.55.0 which means v1.54.0 should have been OK too.

I will have a go at fixing this shortly.

**Comment by ncw** [comment] 2021-04-05 13:27
I've attempted to fix this here

[v1.56.0-beta.5365.87a8c8817.fix-5197-sftp-regression](https://beta.rclone.org/branch/fix-5197-sftp-regression/v1.56.0-beta.5365.87a8c8817.fix-5197-sftp-regression/) on branch [fix-5197-sftp-regression](https://github.com/rclone/rclone/tree/fix-5197-sftp-regression) (uploaded in 15-30 mins)

This fixes
- uploads which take longer than 1 minute
- downloads which take longer than 1 minute
- the speed regression

Testing appreciated!

**Comment by WhatIsThisAllAboutSilly** [comment] 2021-04-05 15:46
Yep - seems to have worked OK (passed the 5 min mark anyway...)

This must have been your addition? "Not closing 4 unused connections as 1 transfers in progress"

Thanks!

**Comment by ncw** [comment] 2021-04-05 17:01
> Yep - seems to have worked OK (passed the 5 min mark anyway...)

Great!
 
> This must have been your addition? "Not closing 4 unused connections as 1 transfers in progress"

That is the fix.

It is the simplest I could make it as I want to put it into 1.55.1!

**Comment by rustycanb** [comment] 2021-04-05 21:12
Works for me, too.

Transferred:      499.910M / 499.910 MBytes, 100%, 1.416 MBytes/s, ETA 0s
Checks:                 3 / 3, 100%
Transferred:            1 / 1, 100%
Elapsed time:      5m57.8s

Thanks for the excellent software and quick response.

Regards

**Comment by ncw** [comment] 2021-04-06 09:02
Thank you all for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.55.1 and v1.56

**Closed** 2021-04-06 09:02 UTC
Labels: Point Release Candidate, Remote: SFTP, bug

**Comment by WhatIsThisAllAboutSilly** [comment] 2021-04-06 10:24
Great, I'll pull the latest beta and keep an eye on it this week to confirm.

**Comment by acsfer** [comment] 2021-04-11 12:11
I'm having this issue, i'll test `rclone v1.56.0-beta.5386.e7b736f8c` tonight.

**Comment by acsfer** [comment] 2021-04-11 12:49
Seems good too after transfer 10Gb 👍

**Comment by ncw** [comment] 2021-04-12 12:31
Thanks for testing @acsfer :-)

**Comment by spout** [comment] 2021-04-15 09:13
@ncw had same issue, rclone v1.56.0-beta.5365.87a8c8817.fix-5197-sftp-regression solved it. Thank you.

**Comment by ncw** [comment] 2021-04-26 08:26
Note that I've now released 1.55.1 with a fix for this in.

As for the speed regression, I reverted the sftp libray to the previous version for v1.55.1.

[the latest beta](https://beta.rclone.org/) now contains a proper fix with an updated library.

**Comment by rustycanb** [comment] 2021-04-26 21:09
Confirming 1.55.1 works as expected. Thanks.
