### ISSUE TITLE
[BUG] VFS issue. Google Cloud can not create new (empty directory) on mount

### ISSUE THREAD

**Issue by thestigma** [rclone/rclone#3597] opened 2019-10-07 00:35 UTC
### What is the problem you are having with rclone?
Google Cloud can not create new (empty directory) on mount
This problem likely extends to other backends that don't treat folders as objects as well.
NCW mentioned this was likely a bug in the VFS layer

#### What is your rclone version (output from `rclone version`)
rclone v1.49.4-003-gb5ea6af6-v1.49-fixes-beta
- os/arch: windows/amd64
- go version: go1.12.10

But the problem has been observed all the way back to 1.48 I believe.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win10-64
Linux replication not tested yet, but assumed to also be affected.

####  Which cloud storage system are you using? (eg Google Drive)
GCP / Google Cloud bucket

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Right click - create new folder. Input name => "The file or folder does not exist"

Here is the relevant reminders from the discussion we had.
Config:

```
[Gcloud]
type = google cloud storage
project_number = REDACTED
service_account_file = C:\rclone\SA\rcloneonegcp.json
object_acl = bucketOwnerFullControl
location = us-central1

rclone mount Gcloud:rclonestore P: ^
--cache-dir "E:\---RCLONE_VFSCACHE_GCLOUD" ^
--vfs-cache-mode writes ^
--vfs-read-chunk-size 128M ^
--vfs-read-chunk-size-limit off ^
--attr-timeout 1s ^
--dir-cache-time 8700h ^
--vfs-cache-max-age 8760h ^
--vfs-cache-poll-interval 1m ^
--vfs-cache-max-size 1024G ^
--poll-interval 10s ^
--allow-other ^
--buffer-size 64M ^
--multi-thread-cutoff 512M ^
--multi-thread-streams 0 ^
--stats 5s ^
-v
```
reproduction steps - (on windows) - right click and "make new folder". Input name and hit enter --> ERROR
I assume most Linux GUIs will do the exact same thing

**Comment by ncw** [comment] 2019-10-08 08:46
I see what is causing the problem...

When you do right click and "make new folder" windows actually makes the folder called "New Folder".  When you type in a name for it (eg "New Name"), then windows renames that folder to "New Name".

It is some part of this directory rename process which is causing the empty folder to drop out of the directory cache on a bucket based remote.

This is perfectly reproducable on Linux using mount (instead of cmount) which indicates that it is a problem in the VFS layer

```
$ ls /mnt/tmp/
file2.txt  file3.txt  file4.txt  one.txt  ONE.txt  potato.txt
$ mkdir /mnt/tmp/"New Folder"
$ ls /mnt/tmp/
 file2.txt   file4.txt     one.txt   potato.txt
 file3.txt  'New Folder'   ONE.txt
$ mv /mnt/tmp/"New Folder" /mnt/tmp/"New Name"
$ ls /mnt/tmp/
file2.txt  file3.txt  file4.txt  one.txt  ONE.txt  potato.txt
$ 
```

I think this is the exact problem - that we are invalidating the directory cache from the root

```
2019/10/07 17:09:25 DEBUG : /: Rename: oldName="New Folder", newName="New Name", newDir=/
2019/10/07 17:09:25 DEBUG : New Folder: Updating dir with New Name 0xc00062c090
2019/10/07 17:09:25 DEBUG : : invalidating directory cache  <<<<<< problem
2019/10/07 17:09:25 DEBUG : New Folder: forgetting directory cache
```

I've had a go at fixing this here - can you have a go?

https://beta.rclone.org/branch/v1.49.5-180-gca46458e-fix-3597-vfs-rename-dir-beta/ (uploaded in 15-30 mins)

**Comment by thestigma** [comment] 2019-10-09 18:11
Yes, will test and report back - within today or tomorrow I expect.

**Comment by thestigma** [comment] 2019-10-13 20:47
Sorry for being late again, but Arnold did some testing for us on this and he reports:

mkdir from command promt works.
right clicking and new dir in explorer (WinServ2019) creates five new folders.

I'll see if I can add my own confirmation to this, but hopefully it gives you something to go on.

**Comment by ncw** [comment] 2019-10-14 13:39
The many folders thing is a known issue and I think there is a fix here...
- see https://github.com/rclone/rclone/issues/3216

I've merged the fix since it is an improvement!

I'll re-open this until we've decided what the problem is with the multiple folders.

**Comment by ncw** [comment] 2019-10-26 17:22
Actually I'm going to close this - I think the above issue covers the multiple folders.

**Closed by ncw** 2019-10-26 17:22 UTC
Labels: VFS / mount, bug
