### ISSUE TITLE
Rclone 1.58 release

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#6020] opened 2022-03-03 17:09 UTC
The rclone 1.58 release is overdue - this is mostly due to me having to take a bit of time off the project as I felt the burn out approaching. I've recovered now, so let's make a release!

Outstanding items:
- I'd like to release 1.58 without `replace` lines in the go mod. We can either hard fork `github.com/jlaffaye/ftp` or update to use it. I did try compiling with upstream and it looks like they've taken your patches @ivandeex. Which option do you prefer a) hard fork b) revert to use upstream?
- If the fix for https://github.com/rclone/rclone/issues/6003 is small I'd like to get that in (usually they are just `s/int/int64/` but I haven't looked at the specifics). I'm happy to cherry pick this from your repo @ivandeex 
- I have a couple of other almost finished small things to merge

Anything else? Any outstanding PRs which desperately should be merged @rclone/rclone ?

I'm planning that this release should be released with go1.17 - I suspect go1.18 when it arrives will be disruptive.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ivandeex** [comment] 2022-03-03 18:46
@ncw 

> having to take a bit of time off the project

I'm still busy with paid projects and elsewhere... :(

> We can either hard fork github.com/jlaffaye/ftp or update to use it. I did try compiling with upstream and it looks like they've taken your patches @ivandeex. Which option do you prefer a) hard fork b) revert to use upstream?

I remember more ftp related requests on tracker and forum. I prefer hard fork.

> If the fix for mail.ru on 32-bit ARM is small

It's tiny, trivial, and confirmed by user (oxford comma before _and_?). I just can't get time for full pr with code review now.

> I'm happy to cherry pick this from your repo @ivandeex

I think it's safe. You'd save me the pr time altogether :)

**Comment by ncw** [comment] 2022-03-07 10:24
Both of the above are now done!

**Comment by rnewson** [comment] 2022-03-07 14:31
https://github.com/rclone/rclone/pull/5845 would be nice for those of us that want to prevent TLS 1.0/1.1 for rcd.

**Comment by realansgar** [comment] 2022-03-09 08:35
#4984 would be nice. It would require the build to be done with go 1.17.8, nothing more.

**Comment by ncw** [comment] 2022-03-09 11:57
@rnewson I'm not going to merge #5845 just yet as the whole http serving stuff in rclone is in a mess and I want to sort it out for 1.59

@realansgar 1.58 will be built with the latest go1.17.x - in fact [the latest beta](https://beta.rclone.org/) should be built with it so you could try that.

**Comment by ncw** [comment] 2022-03-09 12:14
@realansgar just noticed that the beta is still being built with go1.17.7 which means `actions/setup-go@v2` hasn't picked it up yet...

I'm attempting a fix here

[v1.58.0-beta.6027.f4d8120ca.fix-6020-build-go](https://beta.rclone.org/branch/fix-6020-build-go/v1.58.0-beta.6027.f4d8120ca.fix-6020-build-go/) on branch [fix-6020-build-go](https://github.com/rclone/rclone/tree/fix-6020-build-go) (uploaded in 15-30 mins)

**Comment by ncw** [comment] 2022-03-09 12:23
That failed. I made an issue here: https://github.com/actions/virtual-environments/issues/5202

**Comment by l3v11** [comment] 2022-03-11 13:45
Any ETA for the release?

**Comment by animosity22** [comment] 2022-03-11 14:07
> Any ETA for the release?

As soon as it's ready, it'll be released :)

**Comment by ncw** [comment] 2022-03-11 17:02
Here is one of those loose ends! https://github.com/actions/setup-go/issues/205

**Comment by l3v11** [comment] 2022-03-16 04:42
> Here is one of those loose ends! [actions/setup-go#205](https://github.com/actions/setup-go/issues/205)

The issue is fixed https://github.com/actions/setup-go/issues/205#issuecomment-1068560031

**Comment by l3v11** [comment] 2022-03-16 12:17
Oops! Without merging this https://github.com/actions/go-versions/pull/50 it won't work.

**Comment by MisterY** [comment] 2022-03-19 22:10
@ivandeex, you've moved the item "Rclone 1.58 release" into v1.59. 
Technically, that will now never happen? :D

Anyways, re ETA, just posting to say that v1.58 update installed through Arch community repo, which most likely means it's out.

**Comment by ivandeex** [comment] 2022-03-19 23:35
:)
The release is out in the wild.
Closing
cc @ncw

**Closed by ivandeex** 2022-03-19 23:35 UTC
Labels: build
