### ISSUE TITLE
S3 Compatible (AWS) - whitespace folder fail to copy

### ISSUE THREAD

**Issue by CentaurSoft** [rclone/rclone#4574] opened 2020-09-07 12:11 UTC
**What is the problem you are having with rclone?**

rclone sync fail to copy on a S3 bucket when there are white spaces in folder name. If folder is empty it fails to sync to S3 bucket, if folder contains file - it syncing well.

**What is your rclone version (eg output from rclone -V)**

rclone v1.52.3
- os/arch: windows/amd6
- go version: go1.14.7

**Which OS you are using and how many bits (eg Windows 7, 64 bit)**

Windows Server 2012 x64

**Which cloud storage system are you using?**

type = s3
provider = AWS

**Comment by animosity22** [comment] 2020-09-07 12:18
This is a duplicate of:

https://github.com/rclone/rclone/issues/3453

So I'm going to close it out.

**Closed by animosity22** 2020-09-07 12:18 UTC
