### ISSUE TITLE
Sync directory mtimes (folder modtime)

### ISSUE THREAD

**Issue by rodalpho** [rclone/rclone#1669] opened 2017-09-10 02:05 UTC
Per https://forum.rclone.org/t/change-directory-mtime-on-gdrive/3797

I’m syncing a bunch of backup directories to an encrypted GDrive.

The contents of those directories frequently change, and on my desktop this also changes the directories’ last modified time. So I can go in nautilus or finder and sort by date modified and see the directories with the newest files on top.

Rclone doesn’t sync directory mtimes, so they all have the mtime of when they were first synced to GDrive.

***ncw note*** when this gets done we will need to update `rclone touch` too.

**Comment by reticentnz** [comment] 2017-10-17 12:24
Hi @ncw, 

Thought I should mention that this used to (and may still) work on ACD, but doesn't seem to on Gdrive. I don't know if this was implemented server side (ie ACD updates the time of the folder when files are changed within it) or whether this was something rclone was pushing. In any case, I thought I should mention this in case you didn't know, and that some of the code/work required could be lifted from the ACD module.

It's caused some issues with applications that use this folder date as a quick way of checking whether files have been updated.

Looking forward to the fix.

Cheers

**Comment by CottonEaster** [comment] 2018-05-09 12:30
I too would find this feature useful, on Google Drive.

**Comment by aatreya** [comment] 2018-08-01 09:04
Looking forward to this as well. I have a bunch of archived data I'd like to transfer to Google Drive, but it's important that the directory modification times don't get changed, so I can't do that until this is supported. :(

Anything I can do to help with this effort?

**Comment by ncw** [comment] 2018-08-01 13:43
@aatreya what needs to be done is that an optional interface for setting directory times is added do all directory objects emitted by backends that are supported.  It is quite a big job unfortunately but not an impossible sized one if you want to help?

**Comment by vicmarto** [comment] 2020-12-02 13:46
I would find this feature useful too, but with the SFTP backend.

**Comment by duaneg3** [comment] 2022-07-15 22:22
This would be useful on the local backend as well ...

I have a version which works for local files:

1) add fs.DirDateHash variable  (fs/dir.go) and store date for every dir 
    (create AddDir() which call from backend/local/local.go::List())
 2) modify local/local.go::Mkdir to set file mod time  (it is an interface routine)
    (calls new lib/files/mkdir_windows.go::MkdirAll3())
 3) modify syn/syn.go::run() to modify the directory date using operations.Mkdir() 
     (just sets the modtime in this case)
     (similar location as --delete-empty-src-dirs)

the directory mod time needs to be updated after the last file is created in the directory.  With all the multi-threading in the copy routines, it seems to work best to update the directory times at the end after all the file copying is done.

Any interest in having it checked in?

**Comment by ncw** [comment] 2022-07-17 16:06
@duaneg3 I'd be interested to take a look at what you've done. I can't promise we'll merge as-is but it sounds interesting :-)

**Comment by duaneg3** [comment] 2022-07-23 16:26
I can't seem to create a branch with my changes ..

https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md

git push -u origin dir-date-feature
git remote rename origin upstream
git remote add origin git@github.com:duaneg3/rclone.git
git checkout -b dir-date-feature
git commit -a
git push -u origin dir-date-feature
   -> fails due to lack of permissions

I am not sure what to do .. I am not much a git expert ..

**Comment by ncw** [comment] 2022-07-25 10:11
@duaneg3 did you fork the repository first? Press this button

![image](https://user-images.githubusercontent.com/536803/180753159-c80fe75e-227b-48de-b6f4-647045e4d5fe.png)

To fork rclone to your github first, then the above should work.

**Comment by frittentheke** [comment] 2022-08-30 08:36
I just ran into this issue with copied directories having the current date as creation and modification date.
Is an implementation of this feature still being pursued?

**Comment by frittentheke** [comment] 2022-08-30 08:44
I just ran into this issue with copied directories having the current date as creation and modification date.
This is an issue when doing a remote delete via `--min-age` which does not delete empty dirs due to their "wrong" date compared to the source.

Others seems to have ran into this a well:
 * https://github.com/rclone/rclone/issues/977
 * https://forum.rclone.org/t/keep-the-origin-creation-date-rclone/8373
 
Is an implementation of creating remote dirs with "proper" creation or modification time still being pursued @ncw @albertony ?

**Comment by albertony** [comment] 2022-08-30 08:50
I don't think so. The closest thing would be the newly introduced metadata feature, but it is only on files (not directories), and currently only implemented on a few backends. See https://rclone.org/docs/#metadata.

**Comment by cgigate** [comment] 2023-03-25 20:57
after 5 years , the issue is still not resolved yet, that is very disappointed

**Comment by darthShadow** [comment] 2023-07-04 08:49
Closing in favour of #6685 since that's more generic rather than being focussed only on modtime.

**Closed by darthShadow** 2023-07-04 08:49 UTC
Labels: enhancement, maintenance, metadata
