### ISSUE TITLE
"--links" doesn't work if symlink path is provided explicitly

### ISSUE THREAD

**Issue by mirfatif** [rclone/rclone#4453] opened 2020-07-22 14:37 UTC
#### What is the problem you are having with rclone?

Links are excluded when list of files/symlinks is provided in file or to STDIN. 

#### What is your rclone version (output from `rclone version`)

```
~$ rclone version
rclone v1.52.2
- os/arch: linux/arm64
- go version: go1.14.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Android 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone --files-from - --links copy /Linux/home/test GDrive:Linux/home/test`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
~$ pwd
/Linux/home/test
~$ touch file
~$ ln -s file link
~$ echo -e 'file\nlink' | rclone -vv --stats=10m --files-from - --links copy /Linux/home/test GDrive:Linux/home/test
2020/07/22 19:31:26 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "-vv" "--stats=10m" "--files-from" "-" "--links" "copy" "/Linux/home/test" "GDrive:Linux/home/test"]
2020/07/22 19:31:26 DEBUG : Using config file from "/Linux/home/.config/rclone/rclone.conf"
2020/07/22 19:31:27 DEBUG : link.rclonelink: Excluded
2020/07/22 19:31:28 DEBUG : Google drive root 'Linux/home/test': Waiting for checks to finish
2020/07/22 19:31:28 DEBUG : Google drive root 'Linux/home/test': Waiting for transfers to finish
2020/07/22 19:31:34 DEBUG : file: MD5 = d41d8cd98f00b204e9800998ecf8427e OK
2020/07/22 19:31:34 INFO  : file: Copied (new)
2020/07/22 19:31:34 INFO  : 
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         6.4s

2020/07/22 19:31:34 DEBUG : 4 go routines active
```

**EDIT:**
Actually the behavior is same if a symlink path is provided explicitly, in whatever way:
```
~$ rclone --files-from <files_list> --links copy /Linux/home/test GDrive:Linux/home/test
~$ rclone --filter-from <filter_list> --links copy /Linux/home/test GDrive:Linux/home/test
~$ rclone --filter '+ link' --filter '- *' --links copy /Linux/home/test GDrive:Linux/home/test
~$ rclone --include link --links copy /Linux/home/test GDrive:Linux/home/test
```
```
~$ rclone --links copy /Linux/home/test/link GDrive:Linux/home/test
2020/07/22 21:24:23 ERROR : Attempt 1/3 failed with 1 errors and: object not found
2020/07/22 21:24:23 ERROR : Attempt 2/3 failed with 1 errors and: object not found
2020/07/22 21:24:23 ERROR : Attempt 3/3 failed with 1 errors and: object not found
2020/07/22 21:24:23 Failed to copy: object not found
```
The only way `--links` works is if the parent directory of symlink is being copied.
Is this the intended behavior?

**Comment by animosity22** [comment] 2020-07-24 20:54
What's the use case for copying up a single sym link for my own curiosity?

I avoid all links with rclone.

**Comment by mirfatif** [comment] 2020-07-25 11:11
> What's the use case for copying up a single sym link for my own curiosity?

Well I don't copy a single symlink but symlink can be a part of the list which my cron service auto-generates on daily basis. That's how I keep my important files and directories on Android and Ubuntu synced to Google Drive.

My bash script runs `rclone --dry-run` and creates a list of changed or new created files in watched locations. Individual size of each file and then a total size to be synced is calculated. If it's within provided size limit (or after my approval if it's not), `rclone` is run again without `--dry-run`.
However if a file was created after the dry-run, it would be synced without my notice. Also `rclone` has to go through all watched locations once again (which may slow down the system, particularly on HDD). So I want to use the list of files created in dry-run as input to second run. And this list may include symlinks, which would be skipped due to the problem discussed.

There are workarounds to my problem, doing some more scripting, but it'd be more satisfactory if `rclone` handles this on its own. Also, syncing symlinks isn't that important but it would save my time in case I need to do a restore. Creating hundreds or even scores of symlinks would waste time purposelessly.

**Comment by ncw** [comment] 2020-07-26 11:26
The problem is that when you engage `--links`, then rclone thinks the links are called `XXX.rclonelink`

```
$ ls -l .
total 0
-rw-rw-r-- 1 ncw ncw 0 Jul 26 12:13 a
lrwxrwxrwx 1 ncw ncw 1 Jul 26 12:13 b -> a
$ rclone lsf --links .
a
b.rclonelink
$ echo b | rclone lsf --files-from - --links .
$ echo b.rclonelink | rclone lsf --files-from - --links .
b.rclonelink
$ 
```

I'm not 100% sure how to fix this..

Mostly rclone works on directory listings internally so it will be using the internal name b.rclonelink

This could be fixed very easily when using `--no-traverse` where rclone makes individual objects so will have enough info to do this.

There is even a bit in the code which makes sure these objects don't get created with the wrong name so it would be easy to fix that up

https://github.com/rclone/rclone/blob/711736054fada7ee0044db04bc4feeed1f80c42e/backend/local/local.go#L352-L355

Is that worth doing? You'd have to add `--no-traverse` to your command line.

**Comment by mirfatif** [comment] 2020-07-26 14:29
> Is that worth doing? You'd have to add --no-traverse to your command line.

That'd be sufficient for my use case at least. The list `rclone --dry-run` generates includes only files and symlinks, no directories. So I can add `--no-traverse`.

But as you have pointed out the root cause, it's also possible to automate appending `.rclonelink` to symlink names. If you think no changes should be made to code for this, please close the issue.

Thanks.

**Comment by ncw** [comment] 2020-07-26 16:24
I had a go at this but it doesn't work because the file is excluded at a higher layer :-(

How are you generating the file list? If you use rclone to generate the list with the `--links` flag then you'll get the translated names in.

**Comment by mirfatif** [comment] 2020-07-26 21:12
> How are you generating the file list? If you use rclone to generate the list with the `--links` flag then you'll get the translated names in.

Previously I was doing:
```
~$ tree .
.
├── 1
│   ├── file1
│   ├── file2
│   ├── file3
│   └── link1 -> file1
└── 2

2 directories, 4 files
~$ rclone --dry-run --links sync 1 2 2>&1 | sed -u -n 's|.*NOTICE: |1/|; s|.rclonelink: |: |; s|: Not copying .*||p' | xargs -I {} stat -c '%s %n' '{}' | awk '{ sum += $1; print} END { print sum }'
5242880 1/file1               <--- Individual size of file1
10485760 1/file2              <--- Individual size of file2
2097152 1/file3               <--- Individual size of file3
5 1/link1                     <--- Individual size of link1
17825797                      <--- Total size of all files
```
Now I can do something like:
```
~$ rclone --dry-run --links sync 1 2 2>&1 | sed -u -n 's|.*NOTICE: |1/|; s|.rclonelink: |: |; s|: Not copying .*||p' | xargs -I {} stat -c '%s %n' '{}' | awk '{ sum += $1; if ((system("test -L " $2))==0) {printf "%s %s.rclonelink\n",$1,$2} else print} END { print sum }'
10485760 1/file2
5242880 1/file1
5 1/link1.rclonelink
2097152 1/file3
17825797

# or ignore the symlinks size

~$ rclone --dry-run --links sync 1 2 2>&1 | sed -u -n 's|.*NOTICE: |1/|; s|: Not copying .*||p' | xargs -I {} bash -c "[ -f '{}' ] && stat -c '%s %n' '{}' || echo '0 {}'" | awk '{ sum += $1; print} END { print sum }'
5242880 1/file1
10485760 1/file2
2097152 1/file3
0 1/link1.rclonelink
17825792

~$ rclone --dry-run --links sync 1 2 2>&1 | sed -u -n 's|.*NOTICE: |1/|; s|.rclonelink: |: |; s|: Not copying .*||p' | xargs -I {} bash -c "[ -L '{}' ] && echo '0 {}.rclonelink' || stat -c '%s %n' {}" | awk '{ sum += $1; print} END { print sum }'
5242880 1/file1
10485760 1/file2
2097152 1/file3
0 1/link1.rclonelink
17825792
```

**Comment by ncw** [comment] 2020-07-27 10:37
So are you happy with rclone as it is? Shall I close this?

Just for posterity here is the patch I tried.

```diff
diff --git a/backend/local/local.go b/backend/local/local.go
index fcd788c17..1e86a1445 100644
--- a/backend/local/local.go
+++ b/backend/local/local.go
@@ -350,8 +350,12 @@ func (f *Fs) newObjectWithInfo(remote string, info os.FileInfo) (fs.Object, erro
                        return nil, err
                }
                // Handle the odd case, that a symlink was specified by name without the link suffix
+               // This gets translated into a name.rclonelink
+               // This means there are two ways to refer to a single file in NewObject
+               // However it makes life easier for the users
                if o.fs.opt.TranslateSymlinks && o.mode&os.ModeSymlink != 0 && !o.translatedLink {
-                       return nil, fs.ErrorObjectNotFound
+                       o.translatedLink = true
+                       o.remote += linkSuffix
                }
 
        }
```

**Comment by mirfatif** [comment] 2020-07-27 12:26
> So are you happy with rclone as it is? Shall I close this?

It's working for me after your help. Thanks. But waht's working is a kinda workaround, not a robust solution. You are in better position to decide whether something needs to be done here. You can close it from my side.

> Just for posterity here is the patch I tried.

And it didn't work? As you said, due to file being excluded at a higher layer?

**Comment by ncw** [comment] 2020-07-27 15:48
I'd like to fix this, but I think fixing it would involve reworking rather a lot of rclone.

At some point rclone might get better at handling metadata without having to use the `.rclonelink` suffix - when that happens this would be necessary.

The patch didn't work because the sync layers excluded the file because the `.rclonelink` name wasn't in the allowed list.

I'll close this for the time being.

**Closed by ncw** 2020-07-27 15:48 UTC
Labels: bug
