### ISSUE TITLE
azureblob: is throwing "409 Public access is not permitted on this storage account" with v1.61.0

### ISSUE THREAD

**Issue by wallina3** [rclone/rclone#6645] opened 2022-12-21 12:17 UTC
sync works fine
copy stopped working...same code that has been running for months broke immediately after the upgrade.
copy is ignoring the config file with the authentication key to ADLS storage so a 409 is returned

**Comment by ncw** [comment] 2022-12-21 12:36
I need more details please!

Can you fill in the template you deleted and supply a log - thanks.

**Comment by wallina3** [comment] 2022-12-21 12:49
running linux ubuntu on Azure Batch

doesn't work (but did before update to 1.6.1 from 1.6.0)
/usr/bin/rclone copy --config temp_rclone.conf --fast-list --update --use-server-modtime --max-age 6h --progress --no-traverse  s3:processed/3 viadls:json-3/incoming/

 
 works:
/usr/bin/rclone sync --config temp_rclone.conf --fast-list --size-only --checkers=8 s3:processed/3 viadls:json-3/processed/

Error: 
RESPONSE 409: 409 Public access is not permitted on this storage account.
ERROR CODE: PublicAccessNotPermitted


That's about all I have time for as this has caused a lot of issues I have to go deal with (downgrades)

**Comment by ncw** [comment] 2022-12-21 14:01
Can you post a redacted config file please?

**Comment by an-tex** [comment] 2022-12-22 08:25
i have the same issue. backups worked for month, yesterday upgrade to 1.6.1 and the above issue arised

**Comment by ncw** [comment] 2022-12-22 09:11
The error `PublicAccessNotPermitted` means rclone is trying to access the container without auth which is weird and not what is happening here when I try the same.

@wallina3 or @an-tex can you make me a log with the command failing and attach it here? Something like

    rclone lsf yourazureremote:container -vv --dump bodies --retries 1 --low-level-retries 1 --log-file issue-6645.log

Please redact the log file as necessary and attach it here.

If `rclone lsf` doesn't fail, then please find a command which does. If you are transferring data then change the command to `--dump headers` instead of `--dump bodies` otherwise the data will be in the log file.

Thank you.

Without a log file, I have no idea what is going on!

**Comment by P-Stam** [comment] 2022-12-22 09:25
Hi all, we also implemented this new version v1.61.0.0 and we also have an ERROR CODE: PublicAccessNotPermitted.
It looks like it only happens using subfolders in an Azure container

**Comment by an-tex** [comment] 2022-12-22 09:44
[issue-6645.log](https://github.com/rclone/rclone/files/10285725/issue-6645.log)
@ncw here you go

for comparison, here's the same successful copy using 1.60.1
[issue-6645_1.60.1.log](https://github.com/rclone/rclone/files/10285731/issue-6645_1.60.1.log)

**Comment by P-Stam** [comment] 2022-12-22 10:06
@ncw . We agree that it is weird, because we tested version v1.61.0.0 on our test environment, and there it workfed fine. But in another environment it failed (with another storage account). This did work before placing this version.
When we restored the old version of rclone, it worked again.

**Comment by ncw** [comment] 2022-12-22 17:09
I believe I've fixed this here https://beta.rclone.org/branch/fix-6645-azureblob-container/v1.62.0-beta.6657.3d42ae02c.fix-6645-azureblob-container/ on branch [fix-6645-azureblob-container](https://github.com/rclone/rclone/tree/fix-6645-azureblob-container)

Can you give it a try please?

```
    azureblob: fix "409 Public access is not permitted on this storage account"
    
    This error was caused by rclone supplying an empty
    `x-ms-blob-public-access:` header when creating a container for
    private access, rather than omitting it completely.
    
    This is a valid way of specifying containers should be private, but if
    the storage account has a no public data policy then it gives "409
    Public access is not permitted on this storage account".
    
    This patch fixes the problem by only supplying the header if the
    access is set.
```

PS I'm sure I posted this 2 hours ago but I don't see it - apologies if it turns out to be a duplicate!

**Comment by nilsbuer** [comment] 2022-12-22 23:40
Hi Nick,
I can confirm that on my system it is working with the updated Version:
**v1.62.0-beta.6657.3d42ae02c.fix-6645-azureblob-container**

I ran the command:
rclone copy -vv --config temp_rclone.conf --ignore-checksum --ignore-times awsnbu:commission2022/sales.csv sbdatalake:sbdatalake/reports/

## Results:

# Version v1.61.0
RESPONSE 409: 409 Public access is not permitted on this storage account.
ERROR CODE: PublicAccessNotPermitted

#Version v1.62.0-beta.6657.3d42ae02c.fix-6645-azureblob-container
2022/12/23 00:34:42 INFO  : **sales.csv: Copied** (replaced existing)
2022/12/23 00:34:42 INFO  :
Transferred:            104 B / 104 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:        21.5s

Thanks a lot for the quick response. Greate support.

**Comment by ncw** [comment] 2022-12-23 11:56
Thanks @nilsbuer for the report. I'll merge this for v1.61.1 now which I'll release today or tomorrow.

**Closed** 2022-12-23 12:29 UTC
Labels: bug, Remote: Azure Blob, Point Release Candidate

**Comment by nilsbuer** [comment] 2022-12-23 12:34
Hi Nick,
Thanks a lot.
I noticed that the guys from Achmea Insurance also participating in the rclone forum now.

Best regards ,
Nils

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Nick Craig-Wood ***@***.***>
Gesendet: Friday, December 23, 2022 12:56:26 PM
An: rclone/rclone ***@***.***>
Cc: Nils Buer ***@***.***>; Mention ***@***.***>
Betreff: Re: [rclone/rclone] azureblob: is throwing "409 Public access is not permitted on this storage account" with v1.61.0 (Issue #6645)


Thanks @nilsbuer<https://github.com/nilsbuer> for the report. I'll merge this for v1.61.1 now which I'll release today or tomorrow.

**Comment by ncw** [comment] 2022-12-23 18:28
This fix has been released in v1.61.1 which is available now

**Comment by P-Stam** [comment] 2022-12-28 12:16
Hi Nick,
we have tested this new version v1.61.1.0 and the error doesn't occur anymore.
Thanks for your help.

Kind regards,

Peter

**Comment by ncw** [comment] 2022-12-28 23:39
Thanks for testing.
