### ISSUE TITLE
rclone.conf has trouble with quotes in configuration

### ISSUE THREAD

**Issue by jprecuch** [rclone/rclone#5384] opened 2021-06-07 09:59 UTC
#### Output of `rclone version`
root@pgbouncer-5f8576f97d-kj2dr:/opt/data# rclone --version
rclone v1.55.1
- os/type: linux
- os/arch: amd64
- go/version: go1.16.3
- go/linking: static
- go/tags: none

#### Describe the issue
I was manually adjusting the rclone conf (without using rclone config commands) and accidentally put quotes to the region name. Until I figured out that rclone had trouble it took me ot of time and it threw not very handy error.

Can there be some precheck for this config file and threw more handy error if it found quotas in the config file?

This works nicely:
```
[bucketsrc]
type = s3
provider = AWS
env_auth = true
region = eu-west-2
acl = private
server_side_encryption = AES256
storage_class = STANDARD
```

This will throw various errors:
```
[bucketsrc]
type = s3
provider = AWS
env_auth = true
region = "eu-west-2"
acl = private
server_side_encryption = AES256
storage_class = STANDARD

```

```
rclone ls bucketsrc:nice --config /tmp/rclone.conf
2021/06/07 09:57:36 Failed to ls: MissingEndpoint: 'Endpoint' configuration is required for this service
```

```
rclone ls bucketsrc:nice --config /tmp/rclone.conf
2021/06/07 07:38:45 Failed to ls: RequestError: send request failed
caused by: Get "https://nice-production-cv-backup.\"\"/?delimiter=&encoding-type=url&max-keys=1000&prefix=": dial tcp: lookup nice-production-cv-backup."": no such host
```

**Comment by ivandeex** [comment] 2021-06-07 14:40
Quotes are not part of the INI format used by rclone. Not a bug.

**Comment by ivandeex** [comment] 2021-06-07 16:41
Some dialects of the INI format are known to handle quoted values: https://en.wikipedia.org/wiki/INI_file#Varying_features
However rclone uses this library to parse INI files: https://github.com/Unknwon/goconfig
The library does not support this format variation. Probably you could submit your request against the library or submit a pull request to switch rclone for another INI library.

**Comment by ivandeex** [comment] 2021-06-22 02:34
WONT FIX

**Closed by ivandeex** 2021-06-22 02:34 UTC
