### ISSUE TITLE
Dropbox polling bugs?

### ISSUE THREAD

**Issue by andresmatasuarez** [rclone/rclone#5089] opened 2021-03-03 07:00 UTC
I just installed the latest beta to see [dropbox polling](https://github.com/rclone/rclone/issues/2949) in action and I'm getting a couple of potential errors related to it which I'm explaining below:

I've given rclone Dropbox's "app folder" type access, meaning I've scoped access to a certain sub-folder in my cloud drive, let's assume it's `Apps/my-media`

I'm mounting my cloud files in the following way:
`rclone mount {...}  dropbox-remote:/ /media-from-dropbox/`

Note the `/` beside the colon since I want everything that's inside `Apps/my-media` to be mounted.

However, I'm getting the following in the logs:
```
INFO  : Dropbox root '': Failed to get StartCursor: Error in call to API function "files/list_folder/get_latest_cursor": Path root is not supported for sandbox app.
```

If I change my command to `rclone mount {...}  dropbox-remote: /media-from-dropbox/` (removed `/` next to colon), I get instead:
```
INFO  : Dropbox root '': Failed to get StartCursor: Error in call to API function "files/list_folder/get_latest_cursor": request body: path: Specify the root folder as an empty string rather than as "/".
```

...and we're back to square one.

I found some insight in this support ticket: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Download-on-scoped-app/td-p/462689

If I had to guess, I'd say the problem lies [in this line](https://github.com/rclone/rclone/pull/5049/files#diff-7070c850317ae70144b7c0544c568a183ab48d05f0210e96160c3ecf3746ff22R1258), particularly in the portion:
`f.opt.Enc.FromStandardPath(f.slashRoot)`

any ideas?

**Comment by ivandeex** [comment] 2021-03-03 07:17
@wolveix could you take a look?

**Comment by wolveix** [comment] 2021-03-03 07:18
Yeah, I have an idea of what the issue is. I'll take a look when I get a minute later today :)

**Comment by wolveix** [comment] 2021-03-03 13:19
Okay, so the first error you encountered is expected behaviour in my eyes. You can mount the scoped remote without the slash as a prefix, and it'll mount all contents without any issues. The second error was caused by a slight error on my part, which I've now fixed by reusing code from another part of the Dropbox implementation. I've tested that mounting + polling works for both a full Dropbox remote and a scoped remote with no issues. I'll commit the fix for review in a few minutes.

**Comment by andresmatasuarez** [comment] 2021-03-03 15:24
@wolveix lightning fast work! thanks a lot, let's hope it gets approved & released shortly

**Closed** 2021-03-05 17:44 UTC
Labels: Remote: Dropbox, question
