### ISSUE TITLE
Telegram Backend

### ISSUE THREAD

**Issue by mohamedkaissi** [rclone/rclone#6975] opened 2023-04-25 11:45 UTC
I found this project that helped me mount a telegram chat on my pc , I would love to see that in Rclone 

https://github.com/greengeckowizard/RcloneTelegram

**Comment by animosity22** [comment] 2023-04-25 12:28
Duplicate of 

https://github.com/rclone/rclone/issues/5829

**Closed by animosity22** 2023-04-25 12:28 UTC
