### ISSUE TITLE
B2: "ERROR : : error reading destination directory: 200 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)"

### ISSUE THREAD

**Issue by jikamens** [rclone/rclone#3990] opened 2020-02-21 13:56 UTC
#### What is the problem you are having with rclone?

It is making too many calls per minute to the B2 API and then failing to recover gracefully from the resulting error.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.9
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 20.04 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

crypt remote backed by B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone check --download`, can't tell you the exact arguments since it's run by a backup script not by me directly.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Can't reproduce on demand, so can't give you a log output. This is the first time it has happened so unlikely to be able to reproduce frequently, but if I start seeing it more often I will modify the backup script to capture the verbose output.

Here's the output I got:

```
2020/02/21 07:57:03 ERROR : : error reading destination directory: 200 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/02/21 07:58:04 ERROR : : error reading destination directory: 200 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
```

I think rclone needs to be detecting this error and retrying after a suitable back-off time.

**Comment by ncw** [comment] 2020-02-21 21:28
The B2 backend detects 429 errors and obeys the "Retry-After" headers B2 returns.

Does this only happen for `rclone check --download` ?

Using the `--fast-list` flag might help at the expense of using more memory.

**Comment by majutsushi** [comment] 2020-02-22 02:31
This also suddenly started happening for me during my daily backup (using `rclone sync`, also on B2). If it happens again I can try the `--fast-list` option to see if it makes any difference.

**Comment by ncw** [comment] 2020-02-22 10:49
If you can reproduce the error then it would be really helpful if you could post a debug log with `-vv --dump responses`

**Comment by jikamens** [comment] 2020-02-22 16:07
>The B2 backend detects 429 errors and obeys the "Retry-After" headers B2 returns.

When it gets a 429 error and retries successfully, then does it subsequently exit with a non-zero exit status or with a zero exit status? If it recovers successfully then it shouldn't be an error that causes a non-zero exit status, it should be an informational or warning message, right?

>Does this only happen for `rclone check --download` ?

I've only seen it once, and it was during an `rclone check --download`, so I can't say if that's the only time it happens. @majutsushi's experience would seem to indicate otherwise.

Worth noting: my backup script actually calls `rclone check --download` multiple times in a row with different parameters. I suspect it's multiple calls from different invocations of `rclone` in quick succession that are causing the limit to be exceeded, and that's obviously not something that a single `rclone` invocation is going to be able to do anything about.

>Using the `--fast-list` flag might help at the expense of using more memory.

Already doing that. At the top of the Perl script (yes, Perl ;-) ) that calls `rclone`:

>`$ENV{RCLONE_FAST_LIST} = 'true';`

**Comment by majutsushi** [comment] 2020-02-23 01:11
Since we both seem to have hit this at around the same time (based on the issue comment timestamps), and it didn't happen again during last night's backup for me, I wonder if this was actually a temporary issue on Backblaze's part. Maybe they failed to send the correct header for a while, or something like that. If it does happen again I'll try to get a debug log.

**Comment by ncw** [comment] 2020-02-24 12:38
> When it gets a 429 error and retries successfully, then does it subsequently exit with a non-zero exit status or with a zero exit status? If it recovers successfully then it shouldn't be an error that causes a non-zero exit status, it should be an informational or warning message, right?

It should be invisible unless you have `-vv` when you will see messages about low level retries.



> Since we both seem to have hit this at around the same time (based on the issue comment timestamps), and it didn't happen again during last night's backup for me, I wonder if this was actually a temporary issue on Backblaze's part. Maybe they failed to send the correct header for a while, or something like that. If it does happen again I'll try to get a debug log.

It might be that backblaze have put some new limits in - that was my initial thought on seeing the error. It might be that they forgot the Retry-After header in the initial deployment or something like that.

Then again there might be something to fix in rclone.

If we can capture what is happening with `-vv --dump responses` that should show what is going on. If it doesn't happen again then I guess we can say that it was something at backblaze.

**Comment by jikamens** [comment] 2020-02-24 14:24
>It should be invisible unless you have -vv when you will see messages about low level retries.

I run `rclone check --download` with a single `--verbose` flag, so is it therefore a bug that I saw the messages quoted above? Also, as I noted, `rclone check --download` exited with a non-zero exit status and the messages quoted above were the only ones it generated before doing so, so is it a bug that that happened?

**Comment by ncw** [comment] 2020-02-24 17:34
> > It should be invisible unless you have -vv when you will see messages about low level retries.
> 
> I run `rclone check --download` with a single `--verbose` flag, so is it therefore a bug that I saw the messages quoted above? Also, as I noted, `rclone check --download` exited with a non-zero exit status and the messages quoted above were the only ones it generated before doing so, so is it a bug that that happened?

What happened is that it probably did 10 low level retries in quick succession then gave up.

**Comment by deflax** [comment] 2020-04-04 22:36
It does happen to me too on each attempt to use it. Ive notice it by comparing the total number of files in the dir im trying to sync and what backblaze count as rclone skips file deletion on errors.

`

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26

2020/04/04 22:31:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/04/04 22:31:33 DEBUG : HTTP REQUEST (req 0xc000348700)
2020/04/04 22:31:33 DEBUG : POST /b2api/v1/b2_list_file_names HTTP/1.1
Host: api003.backblazeb2.com
User-Agent: rclone/v1.51.0
Content-Length: 156
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

2020/04/04 22:31:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/04/04 22:31:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/04/04 22:31:33 DEBUG : HTTP RESPONSE (req 0xc000348700)
2020/04/04 22:31:33 DEBUG : HTTP/1.1 429 
Content-Length: 124
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=utf-8
Date: Sat, 04 Apr 2020 22:31:33 GMT

{
  "code": "too_many_requests",
  "message": "1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED",
  "status": 429
}
2020/04/04 22:31:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

`

**Comment by ncw** [comment] 2020-04-11 15:51
> Does that means those files are skipped?

Yes it does. Rclone will sync what it can.

Try adding `--fast-list` does that help?

**Comment by deflax** [comment] 2020-04-13 20:02
Yes, it does help. Thank you! (good thing we have extra RAM on the backup server 😄)

**Comment by ncw** [comment] 2020-04-14 12:03
I didn't realise there was a limit for that API.... Is that documented anywhere?

Another way to work around would be to take 1000 calls/minute and set a `--tpslimit of 16` to stay beneath it.

Currently rclone is reacting to 429 errors by slowing down. Rclone would obey a `Retry-After` header here if there was one but it should be sleeping for 1 second after each error.

Is there any chance you could send me a complete log with `-vv` so I can look at the timings. Attach here preferred or email it to nick@craig-wood.com with a link to this page.

**Comment by benz2012** [comment] 2020-04-22 23:00
I saw this issue this morning. `--tpslimit 16` works well as a solution, but I did notice a significant slow down in the speed at which rclone checked files.

I don't see any documentation to support that limit, but they discuss using an exponential backoff at the bottom of this page: https://www.backblaze.com/b2/docs/uploading.html

I can't seem to reproduce the issue now. I thought it was related to having more than 1000 files that needed to be uploaded, but when running that test I still did not see the error.

**Comment by ncw** [comment] 2020-04-23 19:44
Rclone uses exponential backoff for everything however it looks like it isn't backing off fast enough to stop the limit tripping.

Experimenting with these constants might be helpful - also increasing --low-level-retries might help to allow rclone to double the backoff a few more times as it starts quite small at 10ms

https://github.com/rclone/rclone/blob/c4572ebc91288957356de519a178e9dd21da09e3/backend/b2/b2.go#L49-L51

> I can't seem to reproduce the issue now. 

I wonder if b2 put in a change then backed it out again?

**Comment by benz2012** [comment] 2020-05-13 15:43
I finally have a reproducible example, however, it's a directory containing 16 million files, which takes many hours to sync. I imagine the `-vv` log for this would be a nightmare. Not that this helps us solve the issue, but here are the points in time when the error occurred. It is interesting to see that it only happened _once in a while_, but sometimes consecutively.

```
2020/05/13 02:51:39 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 03:42:44 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 03:42:50 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 04:01:05 ERROR : Attempt 1/3 failed ...
2020/05/13 05:38:52 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 05:51:50 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 06:18:25 ERROR : Attempt 2/3 failed ...
2020/05/13 07:30:52 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 07:30:53 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 08:09:40 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 08:09:46 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 08:09:57 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020/05/13 08:35:25 ERROR : Attempt 3/3 failed ...
```

What would the `-vv` log reveal? How would you solve the problem depending on what information it does reveal?

I guess what I'm really asking is, should I just experiment with the constants you mentioned, or is there a different solution that you would take if the `--vv` log revealed something specific.

**Comment by ncw** [comment] 2020-05-14 17:44
> I finally have a reproducible example

:smile: 

> however, it's a directory containing 16 million files, which takes many hours to sync.

:frowning: 

> I imagine the `-vv` log for this would be a nightmare.

Indeed!

> Not that this helps us solve the issue, but here are the points in time when the error occurred. It is interesting to see that it only happened _once in a while_, but sometimes consecutively.
> 
> ```
> 2020/05/13 02:51:39 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 03:42:44 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 03:42:50 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 04:01:05 ERROR : Attempt 1/3 failed ...
> 2020/05/13 05:38:52 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 05:51:50 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 06:18:25 ERROR : Attempt 2/3 failed ...
> 2020/05/13 07:30:52 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 07:30:53 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 08:09:40 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 08:09:46 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 08:09:57 ERROR : ... API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
> 2020/05/13 08:35:25 ERROR : Attempt 3/3 failed ...
> ```
> 
> What would the `-vv` log reveal? How would you solve the problem depending on what information it does reveal?

The `-vv` log will show the low level retries. For each of those errors there will be 10 low level retries so we might learn something about what is going on there.

> I guess what I'm really asking is, should I just experiment with the constants you mentioned, or is there a different solution that you would take if the `--vv` log revealed something specific.

The `-vv` log will show the exact timings of the retries - using `--log-format "time,microseconds"` might be a good idea.

Here what I would try

- raising `--low-level-retries` to 20 - I would expect this to work and fix all the problems. It maybe isn't a generic enough solution though.
- increasing `minSleep` might help. It will also slow everything down so I'd want to monitor that too. Increasing it to 20ms would make for a max number of transactions per minute of 3,000. Increasing it to 60ms would decrease that to 1,000 per minute which is the limit stated above.
- you could simulate this with `--tpslimit`, so running with a `--tpslimit 16` for 60ms or `--tpslimit 50` for 20ms.

**Comment by benz2012** [comment] 2020-06-02 21:05
`--low-level-retries 20` seems to work fantastically and doesn't slow down the entire process in the way that `--tpslimit 16` does.

Would it make sense to set LowLevelRetries to 20 within the b2 backend module?

**Comment by alexs77** [comment] 2020-12-03 08:07
FWIW, I also have this issue. Going to try `--low-level-retries 20`. @ncw , would you require a `-vv` output? With about 1/2 million files, I guess it'll be lengthy…

```
rclone v1.53.3
- os/arch: darwin/amd64
- go version: go1.15.4
```

```text
2020-12-02 23:55:09 NOTICE: Library/WebKit/com.linguee.DeepLCopyTranslator/WebsiteData/IndexedDB/v0: Can't follow symlink without -L/--copy-links
2020-12-02 23:56:43 ERROR : Documents/Git/foo/Gitlab/foo-ch/sysops/foo-terraform/.git/objects/5a: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:56:49 ERROR : Documents/Git/foo/dev/foo-bar_/lib/__zabbix_server/files/twilio-php-master/Twilio/Rest/Trunking: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:56:50 ERROR : Documents/Git/foo/dev/foo-bar_/lib/__zabbix_server/files/twilio-php-master/Twilio/Rest/Proxy/V1/Service/Session: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:56:52 ERROR : Library/Screen Savers/Drift.saver: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:56:53 ERROR : Documents/Git/foo/Gitlab/foo-ch/sysops/dns-terraform/.git/objects/b5: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:56:54 ERROR : Documents/Git/foo/Gitlab/foo-ch/sysops/sysops-terraform/.git/objects/5d: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:56:55 ERROR : Documents/Git/foo/dev/foo-bar/lib/__zabbix_server/files/twilio-php-master/Twilio/Rest/Preview/Understand: error reading destination directory: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
2020-12-02 23:57:11 NOTICE: .oh-my-zsh/plugins/per-directory-history/per-directory-history.plugin.zsh: Can't follow symlink without -L/--copy-links
2020-12-02 23:58:34 ERROR : B2 bucket mac-backup-as path HOME: not deleting files as there were IO errors
2020-12-02 23:58:34 ERROR : B2 bucket mac-backup-as path HOME: not deleting directories as there were IO errors
2020-12-02 23:58:34 ERROR : Attempt 3/3 failed with 28 errors and: march failed with 27 error(s): first error: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
Transferred:   	    3.596M / 3.596 MBytes, 100%, 105.248 kBytes/s, ETA 0s
Errors:                28 (retrying may help)
Checks:            512318 / 512318, 100%
Transferred:           30 / 30, 100%
Elapsed time:     48m44.1s
2020/12/02 23:58:34 Failed to sync with 28 errors: last error was: march failed with 27 error(s): first error: 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests)
```

**Comment by ncw** [comment] 2020-12-06 12:45
> FWIW, I also have this issue. Going to try `--low-level-retries 20`. @ncw , would you require a `-vv` output? With about 1/2 million files, I guess it'll be lengthy…

Give that a go. I don't think I need a log - I think I know what is happening now!

Try experimenting with `--tpslimit` to slow rclone down. 16 is the theoretically correct limit, but you may be able to use higher than that.

Increasing --low-level-retries will stop rclone failing.

**Comment by alexs77** [comment] 2020-12-09 09:20
I was able to do a successful run of rclone with `--low-level-retries 20`. Thank you 👍

**Comment by ivandeex** [comment] 2021-03-17 17:12
Apparently rclone has a lot of tools to successfully overcome provider rate limits

--low-level-retries --tpslimit --bwlimit to name a few
--fast-list to reduce api calls, where supported

Some were demonstrated above with success

Closing

**Comment by jikamens** [comment] 2021-03-17 17:42
The point is that rclone publishes what its API limits are _and_ sends headers with rate-limit responses telling the client how long to wait before trying again, so it's not arcane magic for rclone to be doing the right thing. It _could_ be doing the right thing with the information available to it but is not.

**Comment by ncw** [comment] 2021-03-23 10:55
> The point is that rclone publishes what its API limits are _and_ sends headers with rate-limit responses telling the client how long to wait before trying again, so it's not arcane magic for rclone to be doing the right thing. It _could_ be doing the right thing with the information available to it but is not.

I presume you mean "backblaze publishes" rather than "rclone publishes".

The problem is that backblaze isn't putting a `Retry-After` header in the 429 response which rclone would obey. So rclone sleeps for 1 second.

Another way of fixing the problem might be to adjust the default timeout when backblaze don't send a `Retry-After` header for a 429 error.

https://github.com/rclone/rclone/blob/1406b6c3c9e21f59cba027101bfb2e014a21736e/backend/b2/b2.go#L316

Setting it to 5 (seconds) might be enough to fix the problem

Fancy experimenting to find a value which works?

**Comment by TeNNoX** [comment] 2021-03-29 11:10
@ncw I can confirm that setting `retryAfter` to 5 works well. Here's some log snippets I could catch:

> 2021/03/29 10:56:45 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:56:45 DEBUG : pacer: Rate limited, increasing sleep to 5s
> 2021/03/29 10:56:50 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:56:55 DEBUG : pacer: low level retry 1/10 (error Post https://api003.backblazeb2.com/b2api/v1/b2_list_file_names: EOF)
> 2021/03/29 10:56:55 DEBUG : pacer: Rate limited, increasing sleep to 10s
> 2021/03/29 10:57:01 DEBUG : pacer: Reducing sleep to 5s
> 
> 
> 2021/03/29 10:58:04 DEBUG : pacer: low level retry 3/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:58:09 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:58:10 INFO  :
> Transferred:   	   16.979M / 16.979 MBytes, 100%, 1.208 MBytes/s, ETA 0s
> Checks:             71287 / 71287, 100%
> Transferred:            1 / 1, 100%
> Elapsed time:       2m2.4s
> 
> 2021/03/29 10:58:14 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:58:19 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:58:24 DEBUG : pacer: low level retry 1/10 (error Post https://api003.backblazeb2.com/b2api/v1/b2_list_file_names: EOF)
> 2021/03/29 10:58:24 DEBUG : pacer: Rate limited, increasing sleep to 10s
> 2021/03/29 10:58:29 DEBUG : pacer: Reducing sleep to 5s
> 
> 
> 2021/03/29 10:59:36 DEBUG : pacer: Reducing sleep to 625ms
> 2021/03/29 10:59:36 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:59:36 DEBUG : pacer: Rate limited, increasing sleep to 5s
> 2021/03/29 10:59:41 DEBUG : pacer: Reducing sleep to 2.5s
> 2021/03/29 10:59:41 DEBUG : dolores/files_trashbin/XXX: Size and modification time the same (differ by 0s, within tolerance 1ms)
> 2021/03/29 10:59:41 DEBUG : dolores/files_trashbin/XXX: Unchanged skipping
> 2021/03/29 10:59:46 DEBUG : pacer: Reducing sleep to 1.25s
> 2021/03/29 10:59:49 DEBUG : pacer: Reducing sleep to 625ms
> 2021/03/29 10:59:50 DEBUG : pacer: Reducing sleep to 312.5ms
> 
> 2021/03/29 10:59:56 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:59:56 DEBUG : pacer: Rate limited, increasing sleep to 5s
> 2021/03/29 10:59:56 DEBUG : pacer: Reducing sleep to 2.5s
> 2021/03/29 10:59:56 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 10:59:56 DEBUG : pacer: Rate limited, increasing sleep to 5s
> 2021/03/29 11:00:01 DEBUG : pacer: low level retry 1/10 (error 1000 calls/minute allowed for: API_LIST_FILE_NAMES_CALLED (429 too_many_requests))
> 2021/03/29 11:00:06 DEBUG : pacer: low level retry 1/10 (error Post https://api003.backblazeb2.com/b2api/v1/b2_list_file_names: EOF)
> 2021/03/29 11:00:06 DEBUG : pacer: Rate limited, increasing sleep to 10s
> 2021/03/29 11:00:10 INFO  :
> Transferred:   	   16.979M / 16.979 MBytes, 100%, 1.136 MBytes/s, ETA 0s
> Checks:             80814 / 80814, 100%
> Transferred:            1 / 1, 100%
> Elapsed time:       4m2.4s
> 
> 2021/03/29 11:00:11 DEBUG : pacer: Reducing sleep to 5s

**Comment by ncw** [comment] 2021-03-29 22:25
Great news! Can you find the minimum value of `Retry-After` which works for you? It would be worth lowering from 5s if we can.

If not, 5s it is!

Do you want to send a pull request when you've found the minimum value?

Thanks

**Comment by jikamens** [comment] 2022-08-05 16:52
I haven't seen this issue in a long time. Is anyone else still seeing it, or has some combination of changes on Backblaze's servers and changes to rclone fixed it or made it moot? I'm currently using rclone v1.56.0-beta.5532.1f846c18d. Looks like that's a bit old so I guess I'll upgrade.

**Comment by ncw** [comment] 2022-08-09 11:42
I've heard no reports of this recently.

I shall close this issue - if it turns up again we can re-open it.

**Closed by ncw** 2022-08-09 11:42 UTC
Labels: bug, Remote: Backblaze B2
