### ISSUE TITLE
Failed to copy: update getinfo: object not found

### ISSUE THREAD

**Issue by miku-sama** [rclone/rclone#1982] opened 2018-01-17 02:35 UTC
> What is your rclone version (eg output from `rclone -V`)

```
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu16.04.3

> Which cloud storage system are you using? (eg Google Drive)

ftp

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -vv sync /www/wwwroot/anime/* woot:/public_html/ni-co.moe/anime/public_html`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/01/17 03:31:16 INFO  : 黄金拼图/[KTXP][Kiniro_mosaic][05][GB][720P].[卜卜酱].mp4: Copied (new)
2018/01/17 03:31:37 INFO  : 黄金拼图2/[YUI-7][Hello!! Kin-iro Mosaic][04][GB][X264_AAC][720P].mp4: Copied (new)
2018/01/17 03:31:40 INFO  : 魔装学园HxH/[Array Stars][Masou Gakuen HxH][06][720P][GB&JAP].mp4: Copied (new)
2018/01/17 03:31:58 ERROR : [CASO&SumiSora][Sound!Euphonium2][01-13][GB][720P]/[CASO&SumiSora][Sound!Euphonium2][03][GB][720P].mp4: Failed to copy: update getinfo: object not found
2018/01/17 03:32:08 INFO  : 
Transferred:   91.528 GBytes (17.160 MBytes/s)
Errors:                 5
Checks:               526
Transferred:          561
Elapsed time:   1h31m1.7s
Transferring:
 *                                魔法禁书目录Ⅱ/10.mkv: 70% /300.690M, 3.480M/s, 25s
 *                     魔法禁书目录/16-dmxz.zerodm.mp4: 35% /279.863M, 3.110M/s, 58s
 *      ... the Bottom][BDrip X264 AAC 720P].mkv: 100% /351.495M, 4.876M/s, 0s
 *      ...esub][Kuromukuro][04v2][720P][GB].mp4: 16% /231.927M, 2.304M/s, 1m24s

2018/01/17 03:32:09 ERROR : Wake Up, Girls! Beyond the Bottom[720P]/[漏勺rip][Wake Up, Girls! Beyond the Bottom][BDrip X264 AAC 720P].mkv: Failed to copy: update getinfo: object not found
2018/01/17 03:32:30 INFO  : 魔法禁书目录Ⅱ/10.mkv: Copied (new)
```

**Comment by ncw** [comment] 2018-01-17 08:52
I see you put this on the forum too...

Did rclone retry the errors and they all work OK, or did those files fail permanently?

**Comment by shirakun** [comment] 2018-11-19 12:41
Sorry, I didn't reply so late (LOL).

All files in question are present and usable (can be requested and accessed through http)
I think this problem is caused by some special characters in the filename.

**Comment by shirakun** [comment] 2018-11-24 01:03
> It would be worth retrying with [the latest beta](https://beta.rclone.org) since this query is quite old now!
> 
> Is it a public server this? Could I try it?

hi
I have sent you the server information by mail.
Please note the email from nico@ni-co.moe

**Comment by ncw** [comment] 2018-12-29 22:43
> I get the same error with latest rclone, ftp-ing files from an ubuntu server 18.04.
> Tons of 'Failed to copy: update getinfo: object not found' errors in the log. Even if the files are actually created correctly at the destination. The problem is that with rclone retrying the files several times, it adds 30 minutes and tens of GBs of useless traffic to my backups.

Which ftp server are you using on the ubuntu server?

Can you paste a log with `-vv` of the problem?

**Comment by kh2ouija** [comment] 2018-12-30 09:36
Rclone is running on ubuntu server. The FTP server is Pure-FTPd running on a NAS.
`
$ rclone -vv copy /mnt/tank/music/artists/America\ -\ History\ \[Vinyl\]/ nsa:/public/backup/music/artists/America\ -\ History\ \[Vinyl\]/
2018/12/30 09:20:45 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "-vv" "copy" "/mnt/tank/music/artists/America - History [Vinyl]/" "nsa:/public/backup/music/artists/America - History [Vinyl]/"]
2018/12/30 09:20:45 DEBUG : Using config file from "/home/stefan/.config/rclone/rclone.conf"
2018/12/30 09:20:45 DEBUG : ftp://192.168.1.9:21/public/backup/music/artists/America - History [Vinyl]: Connecting to FTP server
2018/12/30 09:20:46 INFO  : ftp://192.168.1.9:21/public/backup/music/artists/America - History [Vinyl]: Waiting for checks to finish                                          
2018/12/30 09:20:46 INFO  : ftp://192.168.1.9:21/public/backup/music/artists/America - History [Vinyl]: Waiting for transfers to finish                                                                                                         
2018/12/30 09:20:46 DEBUG : ftp://192.168.1.9:21/public/backup/music/artists/America - History [Vinyl]: Connecting to FTP server                                                                                                                
2018/12/30 09:20:46 DEBUG : ftp://192.168.1.9:21/public/backup/music/artists/America - History [Vinyl]: Connecting to FTP server                                                                                                                
2018/12/30 09:20:46 DEBUG : ftp://192.168.1.9:21/public/backup/music/artists/America - History [Vinyl]: Connecting to FTP server                                                                                                                
2018/12/30 09:20:46 ERROR : AlbumArtSmall.jpg: Failed to copy: update getinfo: object not found                         
2018/12/30 09:20:48 ERROR : HMV.nfo: Failed to copy: update getinfo: object not found                                   
2018/12/30 09:20:48 ERROR : HMV.jpg: Failed to copy: update getinfo: object not found                                   
2018/12/30 09:20:48 ERROR : Thumbs.db: Failed to copy: update getinfo: object not found                                 
2018/12/30 09:20:54 ERROR : a2.i.need.you.flac: Failed to copy: update getinfo: object not found  
[...]
2018/12/30 09:21:45 ERROR : Attempt 3/3 failed with 17 errors and: update getinfo: object not found                     
2018/12/30 09:21:45 Failed to copy: update getinfo: object not found   
`

**Comment by ncw** [comment] 2018-12-30 13:04
> If it helps, it's always the same files that "fail" to copy btw.

Is it because there are `[` and `]` in the directory?

**Comment by kh2ouija** [comment] 2018-12-30 14:21
Thanks, that was the issue. What is the explanation, what's wrong with the square brackets in the directory name?

**Comment by ncw** [comment] 2018-12-30 16:39
> Thanks, that was the issue. What is the explanation, what's wrong with the square brackets in the directory name?

I managed to replicate this with a local copy of pureftpd

It is only directories with `[` `]` in that it doesn't like - files are fine.

Doing a bit of poking around it appears pureftp is interpreting those `[` as `]` glob characters in the `MLSD` command rclone is using to list directories whereas it shouldn't according to the rfc: https://tools.ietf.org/html/rfc3659#section-2.2.2

I'll email the author and see what they say.

**Comment by acs-ferreira** [comment] 2019-01-12 12:59
Just letting this here as it is related: https://github.com/ncw/rclone/issues/2908#issuecomment-453741341

**Comment by shouldnotappearcalm** [comment] 2020-08-06 03:46
@ncw The problem with `[`  `]` in the directory name should not be fixed in the `1.52.0`, right?

**Comment by ncw** [comment] 2020-08-06 17:14
> The problem with `[` `]` in the directory name should not be fixed in the `1.52.0`, right?

It is a bug in pureftpd alas...

**Comment by shouldnotappearcalm** [comment] 2020-08-07 01:16
Ok, thank you very much

**Comment by ivandeex** [comment] 2020-11-16 21:20
@ncw 
Do you think this _pureftp bug_ deserves to be added in the _FTP Caveats_ documentation?

**Comment by ivandeex** [comment] 2021-02-10 20:13
Closing after 6 months of inactivity

**Closed by ivandeex** 2021-02-10 20:13 UTC
Labels: Remote: FTP, doc fix, question
