### ISSUE TITLE
Not deleting source as copy failed: 404 Not Found

### ISSUE THREAD

**Issue by diman82** [rclone/rclone#3239] opened 2019-05-30 21:39 UTC
#### What is the problem you are having with rclone?
Not deleting source as copy failed: 404 Not Found

#### What is your rclone version (output from `rclone version`)
rclone v1.46

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
ARM8

####  Which cloud storage system are you using? (eg Google Drive)
Onedrive for business (webdav)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move . onedrive:XXX --ignore-existing --progress --stats-one-line

**Comment by Cnly** [comment] 2019-05-31 06:23
Hi, could you please a log from the command you ran, with the `-vv` flag? And https://github.com/ncw/rclone/issues/3212 may be a related issue that you might want to have a look.

**Comment by diman82** [comment] 2019-05-31 08:44
@Cnly Here you go:
`
2019-05-31 11:40:02 ERROR : Attempt 2/3 failed with 7 errors and: 404 Not Found
2019-05-31 11:40:02 INFO  : webdav root 'XXX': Waiting for checks to finish
2019-05-31 11:40:02 INFO  : webdav root 'XXX': Waiting for transfers to finish
2019-05-31 11:40:05 ERROR : yat.18.04.13.vlada.int_Epidemz.net_Styanulo.net.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:05 ERROR : yat.18.04.13.vlada.int_Epidemz.net_Styanulo.net.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:05 ERROR : Purwle.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:05 ERROR : Purwle.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:05 ERROR : wowg.18.04.13.nancy.a.good.in.bed.4k_Epidemz.net_Styanulo.net.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:05 ERROR : wowg.18.04.13.nancy.a.good.in.bed.4k_Epidemz.net_Styanulo.net.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:05 ERROR : yat.18.05.01.nataly.4k_Epidemz.net_Styanulo.net.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:05 ERROR : yat.18.05.01.nataly.4k_Epidemz.net_Styanulo.net.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:07 ERROR : yat.18.05.13.via.lasciva.4k_Epidemz.net_Styanulo.net.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:07 ERROR : yat.18.05.13.via.lasciva.4k_Epidemz.net_Styanulo.net.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:07 ERROR : yat.18.05.19.melisa.benz.4k_Epidemz.net_Styanulo.net.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:07 ERROR : yat.18.05.19.melisa.benz.4k_Epidemz.net_Styanulo.net.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:07 ERROR : yat.18.05.16.selena.mur.4k_Epidemz.net_Styanulo.net.mp4: Failed to copy: 404 Not Found
2019-05-31 11:40:07 ERROR : yat.18.05.16.selena.mur.4k_Epidemz.net_Styanulo.net.mp4: Not deleting source as copy failed: 404 Not Found
2019-05-31 11:40:07 ERROR : Attempt 3/3 failed with 7 errors and: 404 Not Found
`
Nothing informative.
I've also verified that copied content doesn't exist on the cloud source.

**Comment by ncw** [comment] 2020-01-24 17:06
I'm going to close this one as a duplicate of #3212

**Closed by ncw** 2020-01-24 17:06 UTC
Labels: Remote: One Drive
