### ISSUE TITLE
Copy/Sync from shared folder using --drive-shared-with-me and --drive-server-side-across-configs will result in duplicates if stopped and resumed

### ISSUE THREAD

**Issue by evertonstz** [rclone/rclone#4173] opened 2020-04-27 18:07 UTC
Command I'm running is this one: `rclone -v --drive-shared-with-me sync drive:Folder drive:FolderCopy --drive-server-side-across-configs`

Where "Folder" is one of those new shortcuts from drive that is basically a folder that was shared with me by someone elses and "FolderCopy" is a new folder in my own drive. My intent is sync Folder from someone elses with my FolderCopy, the transaction is server side. 

Transaction happens and the files are copied server side, the problem is that if stop the sync transaction and start it again, instead of resuming the transaction on "FolderCopy" rsync will actually make a duplicated "FolderCopy" and start the transaction again.

**Comment by diolos** [comment] 2020-04-27 20:22
I had the same issue, and I found the solution. Copy the shared folder with Shift+z to your drive,
then do rclone sync "DRIVE1:xxx/xxx" "DRIVE2:xxx/xxx" -P -c --drive-server-side-across-configs.

the issue is with the --drive-shared-with-me flag. The only workaround is to do shift-z to add to your drive and not use it.

**Comment by darthShadow** [comment] 2020-04-28 09:36
This is a duplicate of the issue reported here: https://github.com/rclone/rclone/issues/3132

Closing this issue to keep all discussion in a single place and avoid clutter.

**Closed by darthShadow** 2020-04-28 09:36 UTC
