### ISSUE TITLE
Copy from Dropbox hangs for large files when encountering multi-threaded download

### ISSUE THREAD

**Issue by flaki** [rclone/rclone#4192] opened 2020-05-01 11:41 UTC
#### What is the problem you are having with rclone?

The rclone copy seems to hang while reaching the point when it tries to download 1.0G files from a Google data takeout. Transfers go fine until this point, but once these files come up the transfer stalls and rclone hangs (data transfer speeds are updated on the console, but once End Task or Ctrl+C is hit the command completely freezes and takes a good minute or two to finally exit).

![image](https://user-images.githubusercontent.com/2089432/80802811-b8411780-8bb0-11ea-82c0-0875abfc7972.png)

After checking the logs, and some trial & error, increasing `multi-thread-cutoff` to `2000M` seems to fix the issue:
![image](https://user-images.githubusercontent.com/2089432/80802610-17525c80-8bb0-11ea-9265-4880af42ed8c.png)

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: windows/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 Home N (1909) x64

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox (Plus)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`"c:\Program Files\rclone\rclone.exe" copy -vv -P --log-file d:\rclone.log Dropbox: D:\Dropbox-Backup`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2020/05/01 14:20:02 DEBUG : rclone: Version "v1.51.0" starting with parameters ["c:\\Program Files\\rclone\\rclone.exe" "copy" "-vv" "-P" "--log-file" "d:\\rclone.log" "Dropbox:" "D:\\Dropbox-Backup"]
2020/05/01 14:20:02 DEBUG : Using config file from "C:\\Users\\me\\.config\\rclone\\rclone.conf"

...
```

All goes fine until the log lists 4 times this (for 4 different takeout zip parts):

```
...

2020/05/01 14:20:28 DEBUG : Apps/Google Download Your Data/takeout-20190825T140459Z-014.zip: Starting multi-thread copy with 4 parts of size 256.062M
2020/05/01 14:20:28 DEBUG : Apps/Google Download Your Data/takeout-20190825T140459Z-014.zip: multi-thread copy: stream 4/4 (805502976-1073917371) size 255.980M starting
2020/05/01 14:20:28 DEBUG : Apps/Google Download Your Data/takeout-20190825T140459Z-014.zip: multi-thread copy: stream 1/4 (0-268500992) size 256.062M starting
2020/05/01 14:20:28 DEBUG : Apps/Google Download Your Data/takeout-20190825T140459Z-014.zip: multi-thread copy: stream 3/4 (537001984-805502976) size 256.062M starting
2020/05/01 14:20:28 DEBUG : Apps/Google Download Your Data/takeout-20190825T140459Z-014.zip: multi-thread copy: stream 2/4 (268500992-537001984) size 256.062M starting
```

**Comment by animosity22** [comment] 2020-05-01 12:44
Are you seeing disk IO? Is it writing the file out?

**Comment by flaki** [comment] 2020-05-01 12:58
I haven't checked disk IO, but network I/O falls to zero (according to the Task Manager). I can run a test if needed, but unless `rclone` uses a temp file for ongoing downloads, I don't see any incomplete files in the target directory either.

**Comment by animosity22** [comment] 2020-05-01 14:08
It's gotta combine the 4 streams into a file write so you'd want to check your disk IO as I would guess it's doing something.

How long are you waiting before killing it?

**Comment by ncw** [comment] 2020-05-01 16:08
I'm pretty sure this problem is fixed in [the latest beta](https://beta.rclone.org) - it is to with sparse files on Windows. I forgot to set the sparse flag on windows so the first thing it does is fill the file with zeros.

Give the beta a go.

**Comment by ncw** [comment] 2020-05-13 21:20
I'm going to close this now since I'm reasonably sure the issue is fixed

**Comment by animosity22** [comment] 2020-05-20 00:57
Looks like this should be closed out.

**Closed by animosity22** 2020-05-20 00:57 UTC
Labels: bug
