### ISSUE TITLE
Performance issues: Why  not use 'Cgo' to list all files?

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4944] opened 2021-01-21 08:35 UTC
https://github.com/rclone/rclone/blob/eb090d3544cb755ed8bc30a401ceff69671546e7/backend/local/local.go#L421

Please take look at this:

Go code:
![image](https://user-images.githubusercontent.com/13997135/105324260-2b3e6280-5c06-11eb-9f2f-312aecdb27a8.png)

C code:
![image](https://user-images.githubusercontent.com/13997135/105324424-5de85b00-5c06-11eb-846c-b1c7af2e24fc.png)

There is a big gap in performance. 

Reference link：https://stackoverflow.com/questions/41419056/golang-os-file-readdir-using-lstat-on-all-files-can-it-be-optimised

@ncw

**Comment by ncw** [comment] 2021-01-21 18:45
This isn't a like for like comparison - the go library calls `stat` on each file returned whereas the C code doesn't.

Have you got a real world test which shows a problem?

These are pretty similar

```
$ strace --summary-only find /usr -type f | wc -l
305597
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 26.72    0.979956           4    239864           fcntl
 23.24    0.852432           4    192196           close
 19.34    0.709153           7     96162           getdents64
 15.18    0.556686           5     96114           newfstatat
  8.84    0.324241           6     48446         2 openat
  5.69    0.208557           4     48444           fstat
  0.95    0.034926           7      4694           write
  0.01    0.000332          10        32           mmap
  0.01    0.000312           7        41           brk
  0.01    0.000240         240         1           execve
  0.00    0.000095           9        10           mprotect
  0.00    0.000074           7        10           read
  0.00    0.000063           7         8           pread64
  0.00    0.000028          14         2         2 access
  0.00    0.000025          12         2         2 statfs
  0.00    0.000019          19         1           munmap
  0.00    0.000015           7         2           rt_sigaction
  0.00    0.000014           7         2         1 arch_prctl
  0.00    0.000010           5         2         1 ioctl
  0.00    0.000008           8         1           set_robust_list
  0.00    0.000007           7         1           prlimit64
  0.00    0.000005           5         1           rt_sigprocmask
  0.00    0.000005           5         1           uname
  0.00    0.000005           5         1           sysinfo
  0.00    0.000004           4         1           fchdir
  0.00    0.000004           4         1           fstatfs
  0.00    0.000004           4         1           set_tid_address
------ ----------- ----------- --------- --------- ----------------
100.00    3.667220                726041         8 total
```

vs

```
$ strace --summary-only rclone lsf -l -R --files-only /usr | wc -l
348521
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 73.19    1.495848         658      2270       201 futex
  7.92    0.161877          18      8549        11 newfstatat
  6.15    0.125664           9     12673           write
  3.37    0.068788          19      3445           getdents64
  1.87    0.038176          31      1231         2 openat
  1.84    0.037591          15      2383      2375 epoll_ctl
  1.67    0.034113         541        63           epoll_pwait
  1.55    0.031586           8      3695       102 rt_sigreturn
  1.01    0.020729         109       190           nanosleep
  0.74    0.015070          13      1137           close
  0.33    0.006743          28       239           getpid
  0.17    0.003517          46        76           madvise
  0.12    0.002401          14       168           sched_yield
  0.05    0.001086           4       236           tgkill
  0.00    0.000070           2        27           read
  0.00    0.000062           4        14           umask
  0.00    0.000054           1        51           mmap
  0.00    0.000050           3        16           pread64
  0.00    0.000049           3        15           fcntl
  0.00    0.000030           4         7           geteuid
  0.00    0.000030           4         7           getegid
  0.00    0.000025           2        11           fstat
  0.00    0.000024           8         3           socket
  0.00    0.000024           8         3         2 connect
  0.00    0.000023          11         2           pipe2
  0.00    0.000014          14         1           epoll_create1
  0.00    0.000008           4         2           munmap
  0.00    0.000008           4         2           getrandom
  0.00    0.000005           0        11           mprotect
  0.00    0.000004           4         1           getsockname
  0.00    0.000004           2         2           uname
  0.00    0.000003           3         1           getpeername
  0.00    0.000002           2         1           getuid
  0.00    0.000001           1         1           lseek
  0.00    0.000000           0         3           brk
  0.00    0.000000           0       120           rt_sigaction
  0.00    0.000000           0        11           rt_sigprocmask
  0.00    0.000000           0         1         1 access
  0.00    0.000000           0         4           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         2           sigaltstack
  0.00    0.000000           0         2         1 arch_prctl
  0.00    0.000000           0         1           gettid
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           unlinkat
  0.00    0.000000           0         1           readlinkat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           utimensat
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    2.043679                 36685      2695 total
```

**Comment by zhucan** [comment] 2021-01-22 02:27
I will do it with 'cgo'  out of day.

**Comment by ncw** [comment] 2021-01-22 15:59
Can you post a benchmark which shows a problem?

Using `cgo` is annoying in Go programs because it means that they can't be cross compiled, so rclone tries to avoid it.

**Comment by ivandeex** [comment] 2021-02-24 14:53
Closing unconfirmed questions after timeout.
Feel free to open a new thread
when you really have all requested data.

**Closed by ivandeex** 2021-02-24 14:53 UTC
Labels: LocalFS, question, waiting for reply...
