### ISSUE TITLE
azureblob: implement Rmdir for "directories" on blob

### ISSUE THREAD

**Issue by daniele-spl** [rclone/rclone#4986] opened 2021-02-01 13:13 UTC
#### What is the problem you are having with rclone?
When a folder is deleted on the mount it wont be on the blob storage.

rm -r dir/ 

removes files within this directory but the directory still exists. As soo as the directory cache refreshes from blob, i can see it on the mount again.

#### What is your rclone version (output from `rclone version`)
v1.53.4

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
SLES 12 SP5 64bit

####  Which cloud storage system are you using? (e.g. Google Drive)
Azureblob

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rm -r
or
rmdir

**Comment by krmanish** [comment] 2021-02-22 11:02
I think blob storage is not for deleting folders. One has to have a complete blob (file) path to delete them. Blob storage does not have a concept called folder.

https://stackoverflow.com/a/34737858/1704235 
https://docs.microsoft.com/en-us/answers/questions/49041/azure-blob-storage-delete-folder.html

I think we should mark this ticket as deferred or something. Definitely not a bug.

**Comment by ivandeex** [comment] 2021-02-22 19:48
Marking as "question". Unlike bugs, questions are periodically removed after a period of inactivity.

**Comment by ivandeex** [comment] 2021-02-24 15:06
@daniele-spl
I think that the above answer is complete

**Comment by daniele-spl** [comment] 2021-02-26 09:03
> I think blob storage is not for deleting folders. One has to have a complete blob (file) path to delete them. Blob storage does not have a concept called folder.
> 
> https://stackoverflow.com/a/34737858/1704235
> https://docs.microsoft.com/en-us/answers/questions/49041/azure-blob-storage-delete-folder.html
> 
> @ivandeex
> I think we should mark this ticket as deferred or something. Definitely not a bug.

I aggree that its not a bug when having a look at the information you posted, but I think it is worth to implement.

They are also saying that if you delete everything inside of the folder/blob the folder/blob itself should be deleted but thats not the case. I am not sure if this is the case.

Anyhow it, would be really good to have the rmdir command also for azureblob working. Also rm -r should delete the content and also the folder/blob. As stated in the links it should be possible by this:

"If you want to remove the "folder", you actually have to remove each of the blobs that are named with the same "path".

The most common approach is to get a list of these blobs then feed that to the delete blob call"

And this: 
https://stackoverflow.com/a/63846242

**Comment by ivandeex** [comment] 2021-02-26 09:15
@ncw

sorry to bother but i'm not aware of all details of rclone directory simulation for bucket backends.

the request is to make Rmdir (and Purge, I guess) clear virtual directory markers (probably, fecursively) on bucket backends.
requested here is azureblob only, but i'd expect this to be soon requested for all bucket backends.
i think the requirements still need more elaboration.
do you agree to convert this to an enhancement request?

**Comment by ivandeex** [comment] 2021-03-12 14:22
@ncw
Do you think it's possible to emulate _Rmdir_ with directory markers on backends with virtual directories like S3 or Azureblob?
If not, let's close this feature request with _Won't Fix_.
If yes, it will wait in the _Help Wanted_ queue.

**Comment by ncw** [comment] 2021-03-15 12:23
Making S3 and other bucket based backends store directories (probably optionally) as empty length file is one of those things that I'd like to do but have never found the time.

It is a feature people ask for.

**Comment by ivandeex** [comment] 2021-03-16 21:24
This was requested in the past
Duplicate of #4779

**Comment by ncw** [comment] 2023-09-03 10:11
This is now implemented with

      --azureblob-directory-markers   Upload an empty object with a trailing slash when a new directory is created
      --gcs-directory-markers         Upload an empty object with a trailing slash when a new directory is created
      --s3-directory-markers          Upload an empty object with a trailing slash when a new directory is created

**Closed by ncw** 2023-09-03 10:11 UTC
Labels: duplicate, enhancement, Remote: S3, Remote: Azure Blob, metadata
