### ISSUE TITLE
crash: goroutine 563 [IO wait]:

### ISSUE THREAD

**Issue by laurentopia** [rclone/rclone#3458] opened 2019-08-19 23:30 UTC
When running this on a small ubuntu gcloud instance
`rclone --tpslimit=10 --drive-chunk-size=256M --transfers=10 --checkers=10 --fast-list sync drop:/transfer one:/TRANSFER_from_Dropbox `
I get that after a little while
```
goroutine 563 [IO wait]:
internal/poll.runtime_pollWait(0x7f27191614b8, 0x72, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc009b29498, 0x72, 0x1a00, 0x1a5a, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc009b29480, 0xc00982ea00, 0x1a5a, 0x1a5a, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc009b29480, 0xc00982ea00, 0x1a5a, 0x1a5a, 0xc003fea770, 0x443eac, 0x30)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0006a2580, 0xc00982ea00, 0x1a5a, 0x1a5a, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/net.go:177 +0x69
github.com/ncw/rclone/fs/fshttp.(*timeoutConn).readOrWrite(0xc0007c51c0, 0xc003fea850, 0xc00982ea00, 0x1a5a, 0x1a5a, 0x203004, 0xd5b, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/fshttp/http.go:75 +0x48
github.com/ncw/rclone/fs/fshttp.(*timeoutConn).Read(0xc0007c51c0, 0xc00982ea00, 0x1a5a, 0x1a5a, 0x2, 0x2, 0x10)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/fshttp/http.go:87 +0x8a
crypto/tls.(*atLeastReader).Read(0xc0129435e0, 0xc00982ea00, 0x1a5a, 0x1a5a, 0x1650, 0xc00bde3000, 0xc003fea938)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00bde8cd8, 0x17587c0, 0xc0129435e0, 0x409f35, 0x12ef1a0, 0x1403cc0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00bde8a80, 0x7f2719742c40, 0xc0007c51c0, 0x5, 0xc0007c51c0, 0xc003fea9f0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00bde8a80, 0x1547600, 0xc00bde8bb8, 0x3)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00bde8a80, 0xc013444000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc009a77560, 0xc013444000, 0x1000, 0x1000, 0x60, 0xc000708488, 0x42c4af)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc00c4b6a80)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00c4b6a80, 0x1, 0xc012964660, 0xc000708588, 0xc000708728, 0x652d3d, 0xc00bde8a80)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc009a77560)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1357 +0xae8
```

**Comment by ncw** [comment] 2019-08-20 16:04
Alas that doesn't contain the actual crash message.

I'm guessing it is out of memory though.

Note that this `--drive-chunk-size=256M` can use 256M per transfer.  You've asked for 10 so 2.5GB of memory.

How much memory does your VM have?

**Comment by laurentopia** [comment] 2019-08-21 01:21
I see the arithmetic, thanks for the info.
The VM has 0.6GB of RAM so if it's not swapping it's crashing, although I thought it would kernel panic with no swap space.

**Comment by ncw** [comment] 2019-08-21 09:05
> I see the arithmetic, thanks for the info.
> The VM has 0.6GB of RAM so if it's not swapping it's crashing, although I thought it would kernel panic with no swap space.

You'll get an out of memory from rclone first which will cause a backtrace.  It will say at the very top what the problem is.

**Comment by laurentopia** [comment] 2019-08-23 00:22
Is this normal on a 0.6GB VM after a few minutes and maybe 100 files copied?
`rclone --transfers=10 --fast-list copy -v drop:/transfer box:`

`fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x14d8029, 0x16)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc05c000000, 0x4000000, 0x22ff5d8)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x22e6800, 0x2000000, 0x22e6810, 0x1000)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x22e6800, 0x1000, 0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x22e6800, 0x1000, 0x22ff5e8, 0x1c15908)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x22e6800, 0x1000, 0x101, 0xc000063f20)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x22e6800, 0x1000, 0xc000010101, 0xc000001380)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x2000000, 0xc000000101, 0xc00047fb00)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/proc.go:1153
goroutine 38 [running]:
runtime.systemstack_switch()`

**Comment by laurentopia** [comment] 2019-08-23 00:50
A test was interesting: with an upgraded VM at 2 cores and 7.5GB, --transfers=60 you can see free -m at 3000MB used after a minute, stabilizing at 5700MB after 3 minutes (and a beautiful troughput of 1.5 Gbps both up and down)

**Comment by ncw** [comment] 2019-08-23 12:46
> Is this normal on a 1.7GB VM after a few minutes and maybe 100 files copied?
> `rclone --transfers=10 --fast-list copy -v drop:/transfer box:`
> 
> `fatal error: runtime: out of memory runtime stack: runtime.throw(0x14d8029, 0x16)`

Increasing `--transfers` uses memory as does `--fast-list` (though dropbox doesn't support --fast-list anyway).  The default chunk size is 48M for dropbox so you might have several of those in memory for each transfer which could easily add up to 1GB.

If you want the go runtime to be more careful with memory you can set `export GOGC=20` which will help.

> A test was interesting: with an upgraded VM at 2 cores and 7.5GB, --transfers=60 you can see free -m at 3000MB used after a minute, stabilizing at 5700MB after 3 minutes

For a default chunk size of 48M, 48M* 60 transfers = 2.8 GB so the garbage collector could work harder... What happens to memory usage if you set GOGC as above - does that use less memory?

**Comment by laurentopia** [comment] 2019-08-25 23:48
> If you want the go runtime to be more careful with memory you can set `export GOGC=20` which will help.
> 

--export and --gogc flags are not recognized, how do I tune the GC?

**Comment by ncw** [comment] 2019-08-26 16:18
> > If you want the go runtime to be more careful with memory you can set `export GOGC=20` which will help.
> 
> --export and --gogc flags are not recognized, how do I tune the GC?

You need to set the environment variable `GOGC` to  the value `20`

In a unix shell you'd type `export GOGC=20` before running rclone.

**Comment by laurentopia** [comment] 2019-09-03 16:47
got it, thanks!
I added these info to your wiki https://github.com/rclone/rclone/wiki/Rclone-Optimizations

**Comment by ncw** [comment] 2019-09-04 11:01
> got it, thanks!

:-)

> I added these info to your wiki https://github.com/rclone/rclone/wiki/Rclone-Optimizations

Thank you very much.

I'll close this now.

**Closed by ncw** 2019-09-04 11:01 UTC
