### ISSUE TITLE
rclone bisync command retrieves files from remote even they are deleted locally

### ISSUE THREAD

**Issue by WhaleFell** [rclone/rclone#7042] opened 2023-06-05 03:33 UTC
## Issue Description

I am using the `rclone bisync` command to sync files between my local machine and OneDrive cloud storage. However, I noticed that when I delete a file locally and then run the `rclone bisync` command, it retrieves the file from OneDrive again. This seems like a bug as I expect the deleted file to be removed from OneDrive as well.

## Steps to Reproduce

1. Set up rclone configuration for OneDrive
2. Run the following command to start bidirectional sync: 

   ```
   rclone bisync /path/to/local/folder/ onedrive:/path/to/remote/folder/ --check-access --resync --delete-after --workdir=/root/.cache/rclone/bisync --cache-chunk-size 20M --transfers=8
   ```

3. Delete a file in `/path/to/local/folder/`
4. Re-run the above command to sync changes

## Expected Behavior

I expect that the `rclone bisync` command will delete the corresponding file from the remote folder (`onedrive:/path/to/remote/folder/`) as well when I delete it from the local folder (`/path/to/local/folder/`). The subsequent re-run of the `bisync` command should not retrieve the deleted file from the remote folder.

## Actual Behavior

The `rclone bisync` command retrieves the deleted file from the remote folder (`onedrive:/path/to/remote/folder/`) even though it was deleted locally.

## Additional Information

- Operating System: Docker rclone f6322df9af20[latest](https://hub.docker.com/layers/rclone/rclone/latest/images/sha256-f6322df9af20b551049c2746f15facc9be1154aed3ab79e0d2529edbc8433935?context=explore)

I hope this helps! Please feel free to modify the issue report as needed.

**Comment by nielash** [comment] 2023-06-09 00:43
@WhaleFell if you remove `--resync` in step 4, does it do what you expect? `--resync` is intended to be used for the first run only. During a `--resync` it is expected behavior that unique files on each side will be copied to the other, and nothing will be deleted.

**Comment by animosity22** [comment] 2023-07-20 02:35
Any updates here?

**Comment by nielash** [comment] 2023-08-09 18:15
> Any updates here?

(I'm pretty sure this can just be closed as "not a bug".)

**Comment by animosity22** [comment] 2023-08-09 18:16
Closed as stale / not a bug.

**Closed by animosity22** 2023-08-09 18:16 UTC
Labels: question, bisync
