### ISSUE TITLE
[Feature request] merge plexdrive into rclone to have one app and not 2.

### ISSUE THREAD

**Issue by tvvid** [rclone/rclone#1478] opened 2017-06-12 08:26 UTC
Can rclone devs merge https://github.com/dweidenfeld/plexdrive into rclone to have local cache inside one app, one fuse fs?

**Comment by ajkis** [comment] 2017-06-12 13:32
I would not count on it, since @dweidenfeld did not find his way in rclone code.
Keep in mind that plexdrive is still being in development and its not yet optimized for best performance. 

If anything maybe at one point additional mount command can be implemented that would use local cached URL endpoints and chunk system. ( like cmount is for windows )

**Comment by calisro** [comment] 2017-06-12 19:26
There are issues already in rclone to add things like cache'd urls and file cache and such.  For example:

https://github.com/ncw/rclone/issues/711

I think this issue is really a duplicate of multiple other 'issues'.

**Comment by diamondsw** [comment] 2017-07-11 21:42
Might not be a bad metaissue to track a lot of the "optimization" issues. Or maybe it is bad. Up to ncw. ;)

**Comment by snickers2k** [comment] 2017-08-18 18:12
anything new here? the 24h bans drives me crazy :(

**Comment by ncw** [comment] 2020-01-23 17:23
I think the vfs layer is now improved to such a point that we no longer need this issue :-)

**Closed by ncw** 2020-01-23 17:23 UTC
