### ISSUE TITLE
webdav: sync from encrypt remote to encrypt remote

### ISSUE THREAD

**Issue by Powerbless** [rclone/rclone#2716] opened 2018-11-01 07:43 UTC
#### What is the problem you are having with rclone?
Please see error log below. if i sync to te root directory on the webdav remote, than it works, but not when i sync into a subfolder.
EDIT:
if the Remote 2 is empty, then rclone sync ONE file and stop without error(hangs and do nothing). If i run the command again he print the log see below.

#### What is your rclone version (output from `rclone version`)
rclone v1.44
- os/arch: windows/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows Server 2016 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Remote 1: Google Drive
Remote 2: WebDAV (bitrix24.net)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync "gsuite_crypt:_Skyspace/_alles wichtige" "b24-07xfl6_crypt:_Skyspace/_alles wichtige" --config="C:\configfile\.config.conf" -vv
(i have test with Backslash in Remotes but the same error)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/11/01 08:38:01 DEBUG : rclone: Version "v1.44" starting with parameters ["C:\\rclone4\\rclone.exe" "sync" "gsuite_crypt:_Skyspace/_alles wichtige" "b24-07xfl6_crypt:_Skyspace/_alles wichtige" "--config=C:\\configfile\\.config.conf" "-vv"]
2018/11/01 08:38:02 DEBUG : Using config file from "C:\\configfile\\.config.conf"
2018/11/01 08:38:05 Failed to create file system for "b24-07xfl6_crypt:_Skyspace/_alles wichtige": is a file not a directory

**Comment by ncw** [comment] 2018-11-02 16:15
> 2018/11/01 08:38:05 Failed to create file system for "b24-07xfl6_crypt:_Skyspace/_alles wichtige": is a file not a directory

This error suggests that the file "b24-07xfl6_crypt:_Skyspace/_alles wichtige" is in the way.  

So probably what has happened is that somehow rclone thinks that directory is a file.

Can you double check that "Skyspace/_alles wichtige" is a directory?

Can you try syncing a local directory and see if you get the same result?

Can you send a log with `-vv --dump bodies` please?  Feel free to redact sensitive looking data.

Thanks

**Comment by Powerbless** [comment] 2018-11-19 07:30
Sorry for Late reply.
I Try but the Same Error. The Command:
`rclone sync "C:\testsync\_alles wichtige" "b24-07xfl7_crypt:_Skyspace\_alles wichtige" --config="C:\configfile\rclone.conf" -vv --dump bodies`

the Log:
`2018/11/19 08:23:44 DEBUG : Using config file from "C:\\configfile\\rclone.conf"
2018/11/19 08:23:45 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/11/19 08:23:45 DEBUG : HTTP REQUEST (req 0xc0000f9100)
2018/11/19 08:23:45 DEBUG : PROPFIND /company/personal/user/1/disk/path/003bxxxxxxxxm0iv8/9e9d0tdtj7jhdrsn8079298d64 HTTP/1.1
Host: b24-07xfl6.bitrix24.de
User-Agent: rclone/v1.44
Authorization: XXXX
Depth: 1
Accept-Encoding: gzip
2018/11/19 08:23:45 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/11/19 08:23:45 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/11/19 08:23:45 DEBUG : HTTP RESPONSE (req 0xc0000f9100)
2018/11/19 08:23:45 DEBUG : HTTP/1.1 207 Multi-Status
Transfer-Encoding: chunked
Cache-Control: no-store, no-cache, must-revalidate
Connection: keep-alive
Content-Type: text/xml; charset="utf-8"
Date: Mon, 19 Nov 2018 07:23:45 GMT
Dav: 1
Expires: Thu, 19 Nov 1981 08:52:00 GMT
P3p: policyref="/bitrix/p3p.xml", CP="NON DSP COR CUR ADM DEV PSA PSD OUR UNR BUS UNI COM NAV INT DEM STA"
Pragma: no-cache
Server: nginx/1.12.2
Set-Cookie: PHPSESSID=xwTxxxxxxcjDwAx3dOnOyB8weP; path=/; secure; HttpOnly
Set-Cookie: BITRIX_SM_PK=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Set-Cookie: BITRIX_SM_PK=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
X-Dav-Powered-By: Bitrix Site Manager
X-Powered-Cms: Bitrix Site Manager (xxxxxxxx)
X-Webdav-Status: 207 Multi-Status
886
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:Office="urn:schemas-microsoft-com:office:office" xmlns:Repl="http://schemas.microsoft.com/repl/" xmlns:Z="urn:schemas-microsoft-com:">
 <D:response xmlns:ns0="urn:uuid:c2f41010-65b3-11d1-a29f-00aa00c14882/">
  <D:href>/company/personal/user/1/disk/path/003bqxxxxxxxv8/9e9d0tdtj7jhdrsn8079298d64/</D:href>
   <D:propstat>
    <D:prop>
     <D:name>9e9d0tdtj7jhdrsn8079298d64</D:name>
     <D:creationdate ns0:dt="dateTime.tz">2018-11-16T14:43:37Z</D:creationdate>
     <D:getlastmodified ns0:dt="dateTime.rfc1123">Fri, 16 Nov 2018 14:43:38 GMT</D:getlastmodified>
     <D:iscollection>1</D:iscollection>
     <D:resourcetype><collection/></D:resourcetype>
     <D:getcontenttype>httpd/unix-directory</D:getcontenttype>
     <D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry
></D:supportedlock>
    </D:prop>
    <D:status>HTTP/1.1 200 OK</D:status>
   </D:propstat>
 </D:response>
 <D:response xmlns:ns0="urn:uuid:c2f41010-65b3-11d1-a29f-00aa00c14882/">
  <D:href>/company/personal/user/1/disk/path/003bqqcik3kxxxx2iqgcmm0iv8/9e9d0tdtj7jhdrsn8079298d64/hiv0vgh8ub7at80vfq6a4f6qksifcc836mrtm4ecjanfhttj0lj0</D:href>
   <D:propstat>
    <D:prop>
     <D:name>hiv0vgh8ub7at80vfq6a4f6qksifcc836mrtm4ecjanfhttj0lj0</D:name>
     <D:getcontentlength>28724</D:getcontentlength>
     <D:creationdate ns0:dt="dateTime.tz">2018-11-16T14:43:38Z</D:creationdate>
     <D:getlastmodified ns0:dt="dateTime.rfc1123">Fri, 16 Nov 2018 14:43:38 GMT</D:getlastmodified>
     <D:iscollection>0</D:iscollection>
     <D:getcontenttype/>
     <D:isreadonly/>
     <D:ishidden/>
     <D:resourcetype/>
     <D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry
></D:supportedlock>
    </D:prop>
    <D:status>HTTP/1.1 200 OK</D:status>
   </D:propstat>
 </D:response>
</D:multistatus>
0
2018/11/19 08:23:45 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/11/19 08:23:45 Failed to create file system for "b24-07xfl6_crypt:_Skyspace\\_alles wichtige": is a file not a directory`

**Comment by ncw** [comment] 2018-11-19 13:20
Thanks for that :-)

The problem is that the collection tag is missing the namespace declaration

```xml
    <D:resourcetype><collection/></D:resourcetype>
```

It should be

```xml
    <D:resourcetype><D:collection/></D:resourcetype>
```

This is causing the go XML parser to ignore that tag completely

That is a definite bug that should be reported to whoever made that bit of software.

I've made a work-around here - can you give it a test please?

https://beta.rclone.org/branch/v1.44-095-g4e007da6-fix-2716-webdav-collection-beta/ (uploaded in 15-30 mins)

**Comment by Powerbless** [comment] 2018-11-19 18:49
i test with "rclone-v1.44-097-g2191592e-beta-windows-amd64" but the same error:

**Comment by ncw** [comment] 2018-11-19 20:51
Can you test it with the version I linked above please

https://beta.rclone.org/branch/v1.44-095-g4e007da6-fix-2716-webdav-collection-beta/

That has a potential fix - thanks

**Comment by Powerbless** [comment] 2018-11-19 21:34
I would Like to Test Thema Version You linked but there is no Windows Version. Can You Post a Windows 64bit Version?

**Comment by ncw** [comment] 2018-11-23 20:09
Oh, sorry.  I didn't see it didn't build.

Try this

https://beta.rclone.org/branch/v1.44-109-g279d84b2-fix-2716-webdav-collection-beta/ (uploaded in 15-30 mins)

**Comment by Powerbless** [comment] 2018-11-24 13:09
thank you. i have try your version and its better than before BUT he dont start the transfer. he show the first 4 files to transfer(the overview who refresh every minute) and stuck. he refresh every minute and does nothing...stuck for hours at 0% for every file and do nothing until i abort the process. Can you check it?

**Comment by ncw** [comment] 2018-11-24 15:47
> thank you. i have try your version and its better than before BUT he dont start the transfer. he show the first 4 files to transfer(the overview who refresh every minute) and stuck. he refresh every minute and does nothing...stuck for hours at 0% for every file and do nothing until i abort the process. Can you check it?

I think that is probably a different problem :-(

Can you run it with `-vv --dump responses` so we can see what it is doing?

**Comment by Powerbless** [comment] 2018-11-28 19:55
send you an emal with the log. very long! and at the end i cut because he print infirnity random letters.

Search in E-Mail for "webdav: sync from encrypt remote to encrypt remote"

**Comment by ncw** [comment] 2019-02-03 13:01
Oops, sorry I dropped the ball on this.

I've merged the fix for the extension problem which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46

I got your log - I can see it looks like the transfers start.

Can you try uploading just a text file from the local disk to bitrix?  Does that work?  If not can you send a log with `-vv --dump bodies` and that should give a clue - thanks :-)

**Comment by Powerbless** [comment] 2019-02-15 08:26
I tested and now i am Herring userratelimitexceeded. Can I get this message because I'm trying to start a second rclone instance with one API key?

2019/02/15 09:21:11 DEBUG : pacer: Rate limited, sleeping for 16.421430959s (5 consecutive low level retries)
2019/02/15 09:21:11 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user 
traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: 
https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=2315133333330, userRateLimitExceeded)

**Comment by ncw** [comment] 2019-02-15 13:52
> EDIT:::tested with an brandnew exclusive API-Key and the same error. My other rclone move command runs without problems.

That is only a warning - did you get an actual error?  It will retry 10 times before giving an error

**Comment by Powerbless** [comment] 2019-02-15 15:54
I am get:

2019/02/15 16:53:22 ERROR : file.txt: Failed to copy: Update mkParentDir failed: 409 Conflict


For every file

**Comment by ncw** [comment] 2019-02-26 18:19
> I am get:
> 
> 2019/02/15 16:53:22 ERROR : file.txt: Failed to copy: Update mkParentDir failed: 409 Conflict
> 
> For every file

Can you send or attach a log for this with `-vv --dump headers` please?

**Comment by Powerbless** [comment] 2019-05-25 11:45
actually, only the first file in folders would be copied. same for the sub-dir`s. Getting Failed to copy: Update mkParentDir failed: 409 Conflict

hope it will be in v1.48. Very thank you for all the work you did in the last time!

**Comment by ivandeex** [comment] 2021-02-09 16:05
@Powerbless Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment] 2021-03-15 23:00
"409 Conflict" is a retriable status.
Otherwise the request was resolved long ago.
Closing.

**Closed by ivandeex** 2021-03-15 23:00 UTC
Labels: Remote: WebDAV, bug, waiting for reply...
