### ISSUE TITLE
rclone drives not showing up in Finder sidebar and Desktop

### ISSUE THREAD

**Issue by v57** [rclone/rclone#3545] opened 2019-09-17 22:37 UTC
When i connect my drives i want them to show up in my finder sidebar so i can easily access them and see if they are connected or not.

I tried this command with flag `local` (which works in `sshfs`)
```
rclone mount --allow-non-empty --fuse-flag local yandex:/ /Volumes/Yandex
```
But it still didn't shows in my sidebar.

**Comment by ncw** [comment] 2019-09-18 10:11
I think you are using this option: https://github.com/osxfuse/osxfuse/wiki/Mount-options#user-content-local

Unfortunately the standard `rclone mount` doesn't support `--fuse-flag` - you should have seen an ERROR in the log.

It would be relatively straight forward to add a new flag, or parse the `--fuse-flag` looking for that option...

https://github.com/rclone/rclone/blob/c49a71f4385b371563a81bfae8959eb29823e94a/cmd/mount/mount.go#L73-L75

Because the fuse library does support it

https://github.com/bazil/fuse/blob/65cc252bf6691cb3c7014bcb2c8dc29de91e3a7e/options.go#L71-L72

**Comment by aatreya** [comment] 2020-05-27 21:35
Why is it important to parse these flags rather than just passing them through to FUSE as-is?

**Comment by ncw** [comment] 2020-05-31 11:36
> Why is it important to parse these flags rather than just passing them through to FUSE as-is?

That is because the fuse library rclone uses doesn't actually use libfuse - it talks straight to the kernel.

Does anyone want to have a go at this?

We could either parse the input to `--fuse-flag` - probably not my favoured option as these options are for passing to fuse, or add a new option `--local` say which will only work on macOS and will set the fuse option.

**Comment by andresmatasuarez** [comment] 2020-08-31 20:07
so, in the meantime, is there a fix for this? how can I achieve passing fuse flags down via rclone?

**Comment by ncw** [comment] 2020-09-08 16:18
The macOS build now support `rclone cmount` which will become `rclone mount` in v1.54

So you can use `rclone cmount` now and pass fuse options with the `-o local` flag as this does use libfuse.

**Comment by ivandeex** [comment] 2020-11-14 19:49
@andresmatasuarez @v57 
Please try `rclone cmount` with latest rclone 1.53.2
Does the problem reproduce?

**Comment by ivandeex** [comment] 2021-02-07 03:55
Closed after 3 months of inactivity

**Comment by andresmatasuarez** [comment] 2021-03-03 03:57
@ncw @ivandeex sorry for the ultra late response. I've just got time to give this another try and sadly it didn't work.

I'm using Ubuntu though, so maybe that's a deciding factor? I updated `rclone` to latest version such that running  `rclone version` throws:
```
rclone v1.54.0
- os/arch: linux/amd64
- go version: go1.15.7
```

Under Linux, neither `cmount` is recognized (`Error: unknown command "cmount" for "rclone"`) nor `-o`/`--fuse-flag` arguments work (both log `... not supported with this FUSE backend`)

**Comment by ivandeex** [comment] 2021-03-03 04:16
We have two distribution formats for Linux: `.zip` and `.deb`. The former contains a static binary that supports only `mount` command with a limited set of features. You want `.deb` which has rclone as dynamic executable linked with libfuse and has `cmount` with extended features.
Please download https://downloads.rclone.org/v1.54.0/rclone-v1.54.0-linux-amd64.deb and install it as root `sudo dpkg -i rclone-v1.*.deb`

**Comment by andresmatasuarez** [comment] 2021-03-03 04:31
@ivandeex no luck, did what you said and I'm still getting `Error: unknown command "cmount" for "rclone"`

I even tried upgrading to beta release 1.55 using this package https://beta.rclone.org/v1.55.0-beta.5241.0ad38dd6f/rclone-v1.55.0-beta.5241.0ad38dd6f-linux-amd64.deb (cause I need `poll-interval` for Dropbox) to no avail

**Comment by ivandeex** [comment] 2021-03-03 05:06
I think that `which rclone` and `rclone version` will explain your gotcha. Try to run using the full path `/usr/bin/rclone`, it comes right from deb.

**Comment by ivandeex** [comment] 2021-03-03 05:37
@andresmatasuarez 
I am sorry, was wrong. Just rechecked on a clean box. The deb from the link contains a static executable.

@animosity22 
Please advise, which Linux artifact from https://downloads.rclone.org/v1.54.0/ has a dynamic executable and supports `cmount` and libfuse ??

**Comment by ivandeex** [comment] 2021-03-03 06:13
@andresmatasuarez 
While rclone gurus confirm existence and location of official rclone binary with cmount/libfuse, you can try my unofficial beta https://github.com/ivandeex/rclone/releases/tag/v1.54-iva04
I build it for deployment on my farm.

**Comment by ivandeex** [comment] 2021-03-03 08:59
from the forum
> [rclone for linux with libfuse feature] isn't officially packaged yet but you can build it yourself with `go build -tags cmount`

@andresmatasuarez 
So there is no official fix on Linux as of yet. Only Windows and OSX support libfuse flags as of yet.

> so, in the meantime, is there a fix for this? how can I achieve passing fuse flags down via rclone?

**Comment by ivandeex** [comment] 2021-03-03 09:27
I guess we have the original request sorted on `OS: Mac`

**Comment by ivandeex** [comment] 2021-03-03 11:20
Closing in favor of #5090

**Closed by ivandeex** 2021-03-03 11:20 UTC
Labels: OS: Mac, VFS / mount, enhancement, waiting for reply...

**Comment by andresmatasuarez** [comment] 2021-03-04 16:23
@ivandeex are there any plans of making a Linux release including these functionalities?
