### ISSUE TITLE
Temporary file support on copy/sync for local/ftp/sftp targets

### ISSUE THREAD

**Issue by cjnaz** [rclone/rclone#4513] opened 2020-08-14 16:55 UTC
#### What is your current rclone version (output from `rclone version`)?
v1.52.2

#### What problem are you are trying to solve?
When the copy or sync target is a local filesystem (for ftp / sftp) it is possible that a corrupted file is created on the target if the rclone process dies or the network connection is lost.  Ways that the rclone process can die include...
- laptop goes to sleep, or battery dies
- Windows does a forced reboot for updates
- bad karma

The impact for the [rclonesync ](https://github.com/cjnaz/rclonesync-V2) application is that a corrupted output file on one side ends up clobbering the original good file on the other side on the next sync, since the two files are seen as different.

Reference 
- [https://forum.rclone.org/t/temporary-file-support-on-copy-sync/18484](https://forum.rclone.org/t/temporary-file-support-on-copy-sync/18484)
- [https://unix.stackexchange.com/questions/517834/what-are-the-temporary-files-that-rsync-uses-while-continuing-a-breaked-copy](https://unix.stackexchange.com/questions/517834/what-are-the-temporary-files-that-rsync-uses-while-continuing-a-breaked-copy)
- [https://github.com/cjnaz/rclonesync-V2/issues/56](https://github.com/cjnaz/rclonesync-V2/issues/56)

#### How do you think rclone should be changed to solve that?
When copying to a local fs or ftp/sftp target, copy to a temporary filename and then rename to the correct filename after the successful transfer.

**Comment by darthShadow** [comment] 2020-08-14 19:35
I believe this is a duplicate of #1316, so closing it.

**Closed** 2020-08-14 19:35 UTC

**Comment by cjnaz** [comment] 2020-08-14 21:07
Yes, dup.  As @ncw noted, affects local, ftp, and sftp.  

I'm planning to leave this as a open/bug for rclonesync for now, since the better and more complete solution is in rclone itself.

**Comment by ncw** [comment] 2020-08-16 15:47
@cjnaz I suggest you subscribe to that other issue. I wrote some implementation notes there too!
