### ISSUE TITLE
"rclone info remote:" Creates a whole bunch of unnecessary files

### ISSUE THREAD

**Issue by thekiefs** [rclone/rclone#4344] opened 2020-06-13 15:12 UTC
#### What is the problem you are having with rclone?
I accidentally typed "rclone info remote:" and hundreds of binary files like "position-right-24-$" were created in my drive. Is this expected behavior?

#### What is your rclone version (output from `rclone version`)
rclone v1.52.1
- os/arch: darwin/amd64
- go version: go1.14.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS 64Bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive
#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone info remote:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
rclone info gd: -vv
2020/06/13 11:12:00 DEBUG : rclone: Version "v1.52.1" starting with parameters ["rclone" "info" "gd:" "-vv"]
2020/06/13 11:12:00 DEBUG : Using config file from "/Users/thekiefs/.config/rclone/rclone.conf"
2020/06/13 11:12:00 INFO  : Google drive root '': Trying to create control character file names
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x02
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x03
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x05
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x06
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x07
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x04
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0x01
2020/06/13 11:12:00 INFO  : Google drive root '': Writing position file 0xFE
2020/06/13 11:12:02 INFO  : Google drive root '': Writing middle position file 0x03 OK
2020/06/13 11:12:02 INFO  : Google drive root '': Getting middle position file 0x03 Error: object not found
2020/06/13 11:12:02 INFO  : Google drive root '': Writing middle position file 0x02 OK
2020/06/13 11:12:02 INFO  : Google drive root '': Writing middle position file 0x05 OK
2020/06/13 11:12:02 INFO  : Google drive root '': Writing middle position file 0x04 OK
2020/06/13 11:12:02 INFO  : Google drive root '': Getting middle position file 0x05 Error: object not found
2020/06/13 11:12:02 INFO  : Google drive root '': Getting middle position file 0x02 Error: object not found
2020/06/13 11:12:02 INFO  : Google drive root '': Getting middle position file 0x04 Error: object not found
2020/06/13 11:12:03 INFO  : Google drive root '': Writing middle position file 0x07 OK
2020/06/13 11:12:03 INFO  : Google drive root '': Getting middle position file 0x07 Error: object not found
2020/06/13 11:12:03 INFO  : Google drive root '': Writing middle position file 0x01 OK
2020/06/13 11:12:04 INFO  : Google drive root '': Getting middle position file 0x01 Error: object not found
2020/06/13 11:12:04 INFO  : Google drive root '': Writing middle position file 0xFE OK
2020/06/13 11:12:04 INFO  : Google drive root '': Getting middle position file 0xFE OK
2020/06/13 11:12:05 INFO  : Google drive root '': Writing left position file 0x03 OK
2020/06/13 11:12:05 INFO  : Google drive root '': Getting left position file 0x03 Error: object not found
2020/06/13 11:12:05 INFO  : Google drive root '': Writing middle position file 0x06 OK
2020/06/13 11:12:05 INFO  : Google drive root '': Getting middle position file 0x06 Error: object not found
2020/06/13 11:12:05 INFO  : Google drive root '': Writing left position file 0x02 OK
2020/06/13 11:12:06 INFO  : Google drive root '': Getting left position file 0x02 Error: object not found
2020/06/13 11:12:06 INFO  : Google drive root '': Writing left position file 0x04 OK
2020/06/13 11:12:06 INFO  : Google drive root '': Getting left position file 0x04 Error: object not found
2020/06/13 11:12:06 INFO  : Google drive root '': Writing left position file 0x07 OK


```

**Comment by animosity22** [comment] 2020-06-13 15:41
This is a duplicate of:

https://github.com/rclone/rclone/issues/3638

Closing out.

**Closed by animosity22** 2020-06-13 15:41 UTC

**Comment by ncw** [comment] 2020-06-14 08:48
The info command is for developers... that is why it is hidden

I should probably move this into a debug command - what do you think @animosity22 ?

I was thinking `rclone debug info` which leaves space for other commands. Then I could unhide it and write some docs.
