### ISSUE TITLE
uploading files to OneDrive not supports resuming from break-points

### ISSUE THREAD

**Issue by zhaoguomanong** [rclone/rclone#7285] opened 2023-09-10 02:43 UTC
I am using rclone(webdav)+alist to mount OndeDrive locally on debian 12.0.

rclone config:
```
[webdav]
type = webdav
url = http://192.168.1.239:5244/dav
vendor = other
user = xxx
pass = xxx

```

mount cmd:
```
rclone mount webdav:/ ${mount_point} \
            --allow-other \
            --allow-non-empty \
            --vfs-cache-mode writes \
            --vfs-cache-max-age 5m \
            --umask 000
```

upload cmd

```
rclone move /upload ${upload_dest_rclone} \
            --transfers 1 \
            --checksum \
            --ignore-size \
            --progress \
            --retries 2048 \
            --low-level-retries 1024
```

rclone move cmd can't resume(it always retries from 0%, with errors: 405 method not allowed) the tasks from the break-points when the network connection not stable, such as disconnection for a while.

Does reclone support resuming download/upload from breakpoints?

reproduce steps:

1. using rclone move cmd to trigger a upload task
2. when the progress goes above 0%(such as 10%), disconnect your network connection and connect network again
3. you will receive 405 errors and the task retries from 0% again. not from the break-point(10%).

reproduce rate 100%

It's a bad user experience for uploading large files, it will waste more retry time.

**Comment by animosity22** [comment] 2023-09-10 12:03
Duplicate of:

https://github.com/rclone/rclone/issues/87

best bet - don't turn off your computer when uploading :)

**Closed by animosity22** 2023-09-10 12:03 UTC
