### ISSUE TITLE
Bisync fails when files are added during bisync operation

### ISSUE THREAD

**Issue by laurensknoll** [rclone/rclone#6841] opened 2023-03-13 21:53 UTC
#### What is the problem you are having with rclone?

Bisync fails when files are added during bisync operation. Typically, files are added to the Path1 source (GCS), causing Listing1 to include files not actually copied. 

As a result, the final Path1 Listing does not match the Path2 Listing. Hence, the bisync is marked as "failed" and the succeeding runs fail as well.

**Error flow**
* [Optimistic copy at end of bisync-operation](https://github.com/rclone/rclone/blob/ce3b65e6dc0866cac041b82aabbf790ebd9778b6/cmd/bisync/operations.go#L263)
* [Error triggered by checkSync at end of bisync-operation](https://github.com/rclone/rclone/blob/ce3b65e6dc0866cac041b82aabbf790ebd9778b6/cmd/bisync/operations.go#L295)

**Solution area**
As we update files based on deltas, it makes sense to also update the Listing1 and Listing2 fileLists based on these deltas, instead of scanning the source and destination folders.

To do so, the copy operation needs to return the actual updates as well. Currently, `fastCopy` only returns the error details. By including the actual updates, we have the information to update the listing. Sadly, this information needs to propagate quite some layers and modules, from actual background transfers up to the bisync module.

* [Queued delta execution reference](https://github.com/rclone/rclone/blob/ce3b65e6dc0866cac041b82aabbf790ebd9778b6/cmd/bisync/deltas.go#L253)
* [fastCopy reference](https://github.com/rclone/rclone/blob/98fd00a655cada0bda53b7be3d54dd656a8ab21c/cmd/bisync/queue.go#L14)
* [copyDir reference](https://github.com/rclone/rclone/blob/98fd00a655cada0bda53b7be3d54dd656a8ab21c/fs/sync/sync.go#L1126)
* [run copy reference](https://github.com/rclone/rclone/blob/98fd00a655cada0bda53b7be3d54dd656a8ab21c/fs/sync/sync.go#L844)

#### What is your rclone version (output from `rclone version`)

1.61.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows Server 2022, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Cloud Storage and Local File Storage (Windows)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`bisync gcs:/ C:\clone\`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Sadly I haven't got an actual log of the issue. The script runs in the background on my server and fails every now and then.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment] 2023-08-20 12:37
I can confirm that this is still an issue, and (IMO) one of the most important to solve (but also one of the trickiest.)

> Does this not sort itself out if you run bisync again?

No, and that's [by design](https://rclone.org/bisync/#check-sync). The idea is that if Path1 and Path2 don't match at the end of a bisync run, then something went very wrong and we want to lock out future runs until the user can take a look.

My proposed solution is the approach I [described here](https://forum.rclone.org/t/bisync-bugs-and-feature-requests/37636#:~:text=5.%20Final%20listings%20should%20be%20created%20from%20initial%20snapshot%20%2B%20deltas%2C%20not%20full%20re%2Dscans%2C%20to%20avoid%20errors%20if%20files%20changed%20during%20sync), which is similar to what the OP suggests.

In the meantime, my recommendation is to use `--check-sync=false` and periodically do an independent integrity check as described [here](https://tip.rclone.org/bisync/#concurrent-modifications).

Since this issue is a dupe of #5676, I propose that it should be closed in favor of that one.

**Comment by nielash** [comment] 2023-09-05 07:31
I'm closing this as a duplicate of #5676. Please subscribe to that ticket for further updates!

**Closed by nielash** 2023-09-05 07:31 UTC
Labels: duplicate, bisync
