### ISSUE TITLE
rclone self-update command

### ISSUE THREAD

**Issue by nagualcode** [rclone/rclone#548] opened 2016-06-27 17:34 UTC
Please, add a option to get the last binary version from command line.
Rclone is very useful to embed hardware, such as the Pi, and others. 
It would be very handy to have a cron job to search for the last version and be safe that rclone will be always up to date across a network of embeds,

**Comment by ncw** [comment] 2016-06-28 07:54
Nice idea.  Might be a bit of work.  I wonder if there are any Go frameworks about to help?

**Comment by ncw** [comment] 2016-06-28 10:22
A bit of research comes up with
  * https://github.com/sanbornm/go-selfupdate
  * https://github.com/inconshreveable/go-update

**Comment by fredericofs** [comment] 2016-09-17 00:40
I wish I could help you in here

**Comment by ivandeex** [comment] 2020-11-16 00:26
Duplicate of https://github.com/rclone/rclone/issues/3269

**Comment by ivandeex** [comment] 2020-11-16 00:26
Duplicate of https://github.com/rclone/rclone/issues/2867

**Comment by ivandeex** [comment] 2021-02-14 00:42
This ticket duplicates #3269 so merging in.

**Comment by ivandeex** [comment] 2021-02-19 22:26
Sorry all. I was wrong when I closed this in favor of #3269. I can see now that that ticket actually requests automatic update feature. Sorry for noise. Reopening.

**Comment by ivandeex** [comment] 2021-02-19 22:30
I'd like to quote https://github.com/rclone/rclone/issues/3269#issuecomment-502997308 which better fits in this ticket, I think

> Great idea! I'd like to emulate `restic self-update` which seems to work really well.

**Comment by ivandeex** [comment] 2021-02-20 04:56
A quote of the idea of https://github.com/rclone/rclone/issues/2867#issuecomment-450499371 with minor edits:

`rclone self-update  --check` will just tell you if rclone needs updating!

**Comment by ivandeex** [comment] 2021-02-20 05:28
I think the algorithm can look like:
- check whether self executable is writable by process user id (there may be windows specific tricks)
- if not writable, ask to rerun as _root_ (Administrator)
- parse https://downloads.rclone.org/version.txt
- parse [https://downloads.rclone.org/[VERSION]/SHA1SUMS](https://downloads.rclone.org/v1.54.0/SHA1SUMS)
- download architecture-compatible zip into /tmp from [https://downloads.rclone.org/[VERSION]/](https://downloads.rclone.org/v1.54.0)
- validate hash
- extract executable into self binary directory with temporary suffix (not to `/tmp`, to ensure atomicity of name swap  below)
- atomically swap name (similar to `mv -f` on Unix, I expect trickery on Windows)

What will not be implemented by this ticket:
- `.deb`, `.rpm`, etc package install -- this ticket is only about binary, I want to keep things simple, do not duplicate `apt-get install` or `yum install`
- auto self update -- I think it's enough to add `rclone self-update`  into unix cron or windows task scheduler
- package repositories have their dedicated requests #136 #2153

Todo: use reference ideas from https://github.com/restic/restic/blob/master/cmd/restic/cmd_self_update.go and https://github.com/restic/restic/tree/master/internal/selfupdate

**Comment by ivandeex** [comment] 2021-02-20 06:50
I'm not yet decided about two more options
- `--backup` to backup previous executable with a timestamp
- `--beta` to mimic `install.sh -s beta`

**Comment by ivandeex** [comment] 2021-02-20 16:17
I decided to tackle this one earlier because I see a lot of support questions here and on rclone forum when rclone support guys have to explain that author's rclone version is outdated, and copy-paste upgrade instructions. I hope that one day this can be reduced to the simple "please rerun your test after rclone self-update".

**Comment by ivandeex** [comment] 2021-02-25 22:17
@ncw Could you make the CI/CD pipe maintain a file like `stable-version.txt` (in addition to `version.txt`) on https://download.rclone.org ? This would unlock the `rclone self-update --stable` feature

**Comment by ivandeex** [comment] 2021-02-27 02:00
Here is a related comment from rclone forum:

https://forum.rclone.org/t/previously-working-rclone-backup-now-giving-error-unknown-command-rcat-for-rclone/22507/19

The number in `version.txt` reflects latest release tag from the `master` branch (which is sometimes called `main` nowadays). Also, this notion would be frequently called `main` in the Debian repository and Ubuntu PPA parlance.

I propose new `stable-version.txt` which should contain latest release from the `v1.x-stable branch`.
A Debian or Ubuntu repository in such a case will frequently have `/stable/` in its URL.

For example, if we ran the command **right now**,
`self-update` would install `v1.54` from https://download.rclone.org
`self-update --stable` -- would install `v1.53.4` (or whatever)
`self-update --beta` -- the latest beta from https://beta.rclone.org

**Comment by ivandeex** [comment] 2021-02-27 02:41
@ncw do you think `rclone version --check` can be made an alias for `rclone self-update --check` ??

**Comment by Jwink3101** [comment] 2021-02-27 17:31
It may be a good idea to do more than just validate the hash for a (semi-)automatic update. Is it possible to sign the release and validate the signature? And then have the public key somewhere trustworthy? That would make me feel more comfortable about a self-updater. (Is this common practice?)

**Comment by ivandeex** [comment] 2021-02-27 19:03
You idea will need some support on the CI/CD side which will need time. I want to have self-update out ASAP, preferably in a month. This means we keep it simple at the moment. I propose to submit your idea as a new ticket so the team can address it later as an enhancement.

**Comment by ivandeex** [comment] 2021-03-08 08:56
@Jwink3101 

> It may be a good idea to do more than just validate the hash for a (semi-)automatic update. Is it possible to sign the release and validate the signature?

Your idea will be implemented in 1.55 or 1.56 with some modifications:
- rclone will have a GPG public release key embedded in the binary
- SHA256 hashsum file signature will be validated with the key
- distribution archive of a stable release will be verified by SHA256 upon download in memory
- new binary will be extracted on disk from memory right after validations
- this holds for stable releases, betas (if explicitly requested) will not be verified

**Closed** 2021-03-11 19:39 UTC
Labels: maintenance, new feature
