### ISSUE TITLE
No access when using shared folders in Mega

### ISSUE THREAD

**Issue by emailforos** [rclone/rclone#2709] opened 2018-10-28 11:07 UTC
#### Describe the issue

I found out that when I'm using shared folders in the mega account, rclone can't log in/ access to the mega account.

When I delete these sahred folders, rclone access (without any change in the account config) to the mega account files and folders without any problem.

Thank you for your work and efforts.

**Comment by ncw** [comment] 2018-10-28 20:13
Hey, that is really useful information - thank you :-)

Can you tell me
- What was the error message rclone gave you?  Was it `Failed to create file system for “Mega:”: couldn’t login: Block decryption failed`
- How do you create shared folders - I'd like to see if I can reproduce it.

Thanks

**Comment by ncw** [comment] 2018-10-30 21:31
According [qehwidodo on the forum](https://forum.rclone.org/t/mega-account-doesnt-work/6292/15?u=ncw)

> You are right. If I share a folder from my main account to my test account, then I get the error “Block decryption failed”. When I un-share the folder, it works.

So hopefully that will be easy to reproduce... However it didn't reproduce when I tried it :-(

**Comment by emailforos** [comment] 2018-10-31 14:47
Hi, ncw

In that link, you can check what messages I got when trying to find the error with your cooperation in the forum. I don't know if it may help you.

https://forum.rclone.org/t/mega-error-couldnt-login/7023/14

On the other side, I would try to explain you how it was my link between mega accounts: At the office, I've got a Mega account for backing up some of my documents and I share a folder to my home account if I have a pending work to do at home. This shared folder has read and write attributes.

What I was trying to access with rclone was my home account. The problems I met are int the forum page I put above, and I finally could log in when I deleted my access to the office shared folder.

Hope this may help you.

Thanks

**Comment by edmundlaugasson** [comment] 2018-12-14 13:42
Still having same issue:
```
$ rclone version
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2
```

**Comment by ncw** [comment] 2018-12-30 18:46
I haven't had time to work on this - anyone want to help?

**Comment by Itzyaoni** [comment] 2019-02-05 04:59
SOLVED. I verify that situation. 
I own 2 Mega accounts, in account #1 i could mount my drive using rclone without problems, in the account #2 i couldn't. I log in in account #2, and delete all sharing links in 3 dot right menu => Syncing in each folder and pressing the X next to each folder until no folder remains sharing. 
And then tried again and entered without a problem.
I used a .sh file with execution permissions like this:
#!/bin/bash
rclone --vfs-cache-mode writes mount Mega_JIM: /home/jior/RCloneCloudDrives/MegaDrive/Mega_JIM --config /home/jior/.config/rclone/rclone.conf

Hope this could help. Thanks.

**Comment by ncw** [comment] 2019-02-05 08:20
> SOLVED. I verify that situation.
> I own 2 Mega accounts, in account #1 i could mount my drive using rclone without problems, in the account #2 i couldn't. I log into account #2, and delete all sharing links in 3 dot right menu => Syncing in each folder and pressing the X next to each folder until no folder remains sharing.
> And then tried again and entered without a problem.

If you add a sharing link does it stop working again?

If so can you tell me exactly what kind of sharing link and on which object?

Thanks

**Comment by Itzyaoni** [comment] 2019-02-05 14:48
Yes. If i add a shared Folder again rclone stops as if were forced to unmount. I verified this with mega mounted with rclone and web site opened and logged into same Mega account.
As fast as i add a shared Folder rclone stops and shows exactly the same error in terminal. I think this could be happening because shared Folders in Mega seems to use a mapped space in the reciving account drive from the original account drive. 
i.e. Imagine you own a mega account and have 10 gb in files but have a friend whos sharing with you a Folder weighting 20 gb. In your space cuotta you will see you are using 30 gb of space of your 50 gb account. Mega lets you see your friends files as read only or even, if he/she gives you permissions as full access (collaborative), plus has an import to my drive button which lets you copy this 20 gb to your account but the link from where the data comes stills remaining in the shared with me section. Thats the reason i think shared data has a different behavior than just stored data and rclone confuse when try to connects and shows to you. 
The same happens in the opposite way when you share a Folder with some People. 
Please notice that this error just happens with shared Folders (between Mega accounts) but it doesnt happens when you just share a link to a file (from your mega account to someone whos not necesary needs to own a mega account). 
I hope this info helps.

**Comment by ncw** [comment] 2019-02-05 17:33
> Yes. If i add a shared Folder again rclone stops as if were forced to unmount. I verified this with mega mounted with rclone and web site opened and logged into same Mega account.

I tried sharing a folder from one account to another, but they both carry on working.

> As fast as i add a shared Folder rclone stops and shows exactly the same error in terminal.

What was the error in the terminal?

> Please notice that this error just happens with shared Folders (between Mega accounts) but it doesnt happens when you just share a link to a file (from your mega account to someone whos not necesary needs to own a mega account).

I've tried sharing a Folder between accounts but I have not replicated the problem.  Both accounts carry on working just fine with rclone.

Any ideas?

**Comment by caspertone2003** [comment] 2019-02-13 23:29
@ncw 

Not same but, but on same theme:

I notice that if I mount remotetarget with rclone mount (windows), any shared folder in remotetarget is not shown in the mounted disk when opened with file explorer...

Is it not working or is it a feature not available?

Thanks again!

**Comment by ncw** [comment] 2019-02-14 10:31
> I notice that if I mount remotetarget with rclone mount (windows), any shared folder in remotetarget is not shown in the mounted disk when opened with file explorer...

This isn't supported at the moment. The underlying library has a GetSharedRoots() call which will return them.  I'm not sure how you would show them in rclone though as smashing the shared files into the root could cause file name conflicts.  It probably needs a `--mega-shared-with-me` flag.

**Comment by caspertone2003** [comment] 2019-02-16 20:46
Thanks!

**Comment by NathanielHill** [comment] 2019-05-26 01:31
Also had a similar issue when sharing folders.

@ncw Any plans to add access to "incoming" shared folders on Mega?

**Comment by ncw** [comment] 2019-05-27 13:53
> Also had a similar issue when sharing folders.
> 
> Any plans to add access to "incoming" shared folders on Mega?

I'd love to make this work better, but I'm short of time at the moment and mega is really difficult to work on since there are no docs and everything is reverse engineered from their C++ program.

Would you like to help with this @NathanielHill ?

**Comment by ncw** [comment] 2020-01-17 21:58
I'm pretty sure this problem is fixed now with more careful handling of shared keys.  See [the latest beta](https://beta.rclone.org) for something to test.

**Closed by ncw** 2020-01-17 21:58 UTC
Labels: Remote: Mega, bug
