### ISSUE TITLE
illegal base64 data at input byte 43 / Windows / Mega upload

### ISSUE THREAD

**Issue by caspertone2003** [rclone/rclone#3852] opened 2020-01-04 11:17 UTC
Windows 10; RClone 1.50.2; Mega upload

2020/01/04 04:17:31 ERROR : Laxxxxxofuscatedxxxxxxx.mp4: Failed to copy: failed to finish upload: illegal base64 data at input byte 43
2020/01/04 04:17:31 ERROR : Laxxxxxofuscatedxxxxxxx.mp4: Not deleting source as copy failed: failed to finish upload: illegal base64 data at input byte 43
2020/01/04 04:17:31 INFO  : *go-mega*: pollEvents: Error processing event "t" '{"a":"t","t":{"f":[{"h":"tINmXQ5K","t":0,"a":"TBsqeb9m7rJgs_KgsXS7GXJ3siGBT5JCwqZSs-mA9Imd_HF7vQvcHGwbqlGT3T1xwlGLkyx3KOnCPpWHBWvKtE_83xnJhmmikg9dgyhKfhSq564ANjKfnlhPSf9lypE_c1G5TAkI4FMrbODhINwdcktPmzWPjWnpwvbB1L3HjRR3uu8EM7gPY_huGu43D8gdDB9LDDoFWzolAUrBYAIqvqm6cm6EhWCWbuQx7ErkrC7Lo3joe-pHxAFdI2x_0K94","k":"q6iclUe-lw0:2gf8Ok-YoOSaY3A6mBCWlLPTWsZt_VMkOgD8yCZa9YE/8EcEHJoD:7CUor5_PEH3VJl7JZCIYDr6TN8cgS06McI4bYLA1C5o","p":"1N1gyCQT","ts":1578107851,"u":"q6iclUe-lw0","s":289692784}]},"ou":"q6iclUe-lw0"}': illegal base64 data at input byte 43
2020/01/04 04:17:31 ERROR :Laxxxxxofuscatedxxxxxxx.mp4: Failed to copy: upload file failed to create session: Request over quota
2020/01/04 04:17:31 ERROR : Laxxxxxofuscatedxxxxxxx.mp4: Not deleting source as copy failed: upload file failed to create session: Request over quota

Request over quota - i see that.
What about the "illegal base64 data at input byte 43" (might be related to the -ofuscated-name of the file?

TIA
CT

**Comment by ncw** [comment] 2020-01-04 13:49
That error is from the events poller

An event "t" is a node addition - so a file being created.  So it looks like rclone didn't understand that one for some reason.

Things should have carried on working after that though.

Can you reproduce that error?

**Comment by caspertone2003** [comment] 2020-01-04 17:22
I have not seen it anymore and seems I am unable...
I have not any more info either.
So, perhaps time to close issue if you wish.

**Comment by ncw** [comment] 2020-01-05 20:00
OK thanks.  I'll close this for the moment then - please reopen if you can reproduce and I'll have a go at fixing :-)

**Closed by ncw** 2020-01-05 20:00 UTC
