### ISSUE TITLE
FTPS (FTP with implicit TLS) issues in rclone-v1.55.0-windows-amd64

### ISSUE THREAD

**Issue by aliron19** [rclone/rclone#5210] opened 2021-04-04 17:05 UTC
Hello,

I've been using rclone (on a Windows 10 Pro 64bits machine) to sync a local directory with a remote FTPS server (FileZilla Server v0.9.60.2, configured to use implicit TLS) without issues, until rclone v1.54.1.

However, after testing rclone v1.55.0 I've found that it doesn't work with FTPS (implicit TLS) any more, but it seems to work fine with FTPES (FTP over explicit TLS).

If I try to list the remote, this is what I get:

```
>rclone.exe ls -vv ftps_remote://

2021/04/04 18:40:37 DEBUG : Using config file from "C:\\Users\\MyUsername\\.config\\rclone\\rclone.conf"
2021/04/04 18:40:37 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "ls" "-vv" "ftps_remote://"]
2021/04/04 18:40:37 DEBUG : Creating backend with remote "ftps_remote://"
2021/04/04 18:40:37 DEBUG : ftps://MY_IP:MY_PORT: Connecting to FTP server
2021/04/04 18:40:37 ERROR : : error listing: 521 PROT P required
2021/04/04 18:40:37 DEBUG : 2 go routines active
2021/04/04 18:40:37 Failed to ls with 2 errors: last error was: 521 PROT P required
```

On my FileZilla server, using restic v1.55.0 I get the following log:

```
(000070)04/04/2021 18:45:13 - (not logged in) (MY_IP)> Connected on port MY_PORT, sending welcome message...
(000070)04/04/2021 18:45:13 - (not logged in) (MY_IP)> 220 Welcome message
(000070)04/04/2021 18:45:13 - (not logged in) (MY_IP)> TLS connection established
(000070)04/04/2021 18:45:13 - (not logged in) (MY_IP)> USER username
(000070)04/04/2021 18:45:13 - (not logged in) (MY_IP)> 331 Password required for username
(000070)04/04/2021 18:45:13 - (not logged in) (MY_IP)> PASS ******
(000070)04/04/2021 18:45:13 - username (MY_IP)> 230 Logged on
(000070)04/04/2021 18:45:13 - username (MY_IP)> FEAT
(000070)04/04/2021 18:45:13 - username (MY_IP)> 211-Features:
(000070)04/04/2021 18:45:13 - username (MY_IP)>  MDTM
(000070)04/04/2021 18:45:13 - username (MY_IP)>  REST STREAM
(000070)04/04/2021 18:45:13 - username (MY_IP)>  SIZE
(000070)04/04/2021 18:45:13 - username (MY_IP)>  MLST type*;size*;modify*;
(000070)04/04/2021 18:45:13 - username (MY_IP)>  MLSD
(000070)04/04/2021 18:45:13 - username (MY_IP)>  AUTH SSL
(000070)04/04/2021 18:45:13 - username (MY_IP)>  AUTH TLS
(000070)04/04/2021 18:45:13 - username (MY_IP)>  PROT
(000070)04/04/2021 18:45:13 - username (MY_IP)>  PBSZ
(000070)04/04/2021 18:45:13 - username (MY_IP)>  UTF8
(000070)04/04/2021 18:45:13 - username (MY_IP)>  CLNT
(000070)04/04/2021 18:45:13 - username (MY_IP)>  MFMT
(000070)04/04/2021 18:45:13 - username (MY_IP)>  EPSV
(000070)04/04/2021 18:45:13 - username (MY_IP)>  EPRT
(000070)04/04/2021 18:45:13 - username (MY_IP)> 211 End
(000070)04/04/2021 18:45:13 - username (MY_IP)> TYPE I
(000070)04/04/2021 18:45:13 - username (MY_IP)> 200 Type set to I
(000070)04/04/2021 18:45:13 - username (MY_IP)> OPTS UTF8 ON
(000070)04/04/2021 18:45:13 - username (MY_IP)> 202 UTF8 mode is always enabled. No need to send this command.
(000070)04/04/2021 18:45:13 - username (MY_IP)> EPSV
(000070)04/04/2021 18:45:13 - username (MY_IP)> 229 Entering Extended Passive Mode (|||RANDOM_PORT_NUMBER|)
(000070)04/04/2021 18:45:13 - username (MY_IP)> MLSD /
(000070)04/04/2021 18:45:13 - username (MY_IP)> 521 PROT P required
(000070)04/04/2021 18:45:13 - username (MY_IP)> disconnected.
```

While using rclone v1.54.1, I get this other log on my FileZilla Server:
```
(000071)04/04/2021 18:45:48 - (not logged in) (MY_IP)> Connected on port MY_PORT, sending welcome message...
(000071)04/04/2021 18:45:48 - (not logged in) (MY_IP)> 220 Welcome message
(000071)04/04/2021 18:45:48 - (not logged in) (MY_IP)> TLS connection established
(000071)04/04/2021 18:45:48 - (not logged in) (MY_IP)> USER username
(000071)04/04/2021 18:45:48 - (not logged in) (MY_IP)> 331 Password required for username
(000071)04/04/2021 18:45:48 - (not logged in) (MY_IP)> PASS ******
(000071)04/04/2021 18:45:48 - username (MY_IP)> 230 Logged on
(000071)04/04/2021 18:45:48 - username (MY_IP)> FEAT
(000071)04/04/2021 18:45:48 - username (MY_IP)> 211-Features:
(000071)04/04/2021 18:45:48 - username (MY_IP)>  MDTM
(000071)04/04/2021 18:45:48 - username (MY_IP)>  REST STREAM
(000071)04/04/2021 18:45:48 - username (MY_IP)>  SIZE
(000071)04/04/2021 18:45:48 - username (MY_IP)>  MLST type*;size*;modify*;
(000071)04/04/2021 18:45:48 - username (MY_IP)>  MLSD
(000071)04/04/2021 18:45:48 - username (MY_IP)>  AUTH SSL
(000071)04/04/2021 18:45:48 - username (MY_IP)>  AUTH TLS
(000071)04/04/2021 18:45:48 - username (MY_IP)>  PROT
(000071)04/04/2021 18:45:48 - username (MY_IP)>  PBSZ
(000071)04/04/2021 18:45:48 - username (MY_IP)>  UTF8
(000071)04/04/2021 18:45:48 - username (MY_IP)>  CLNT
(000071)04/04/2021 18:45:48 - username (MY_IP)>  MFMT
(000071)04/04/2021 18:45:48 - username (MY_IP)>  EPSV
(000071)04/04/2021 18:45:48 - username (MY_IP)>  EPRT
(000071)04/04/2021 18:45:48 - username (MY_IP)> 211 End
(000071)04/04/2021 18:45:48 - username (MY_IP)> TYPE I
(000071)04/04/2021 18:45:48 - username (MY_IP)> 200 Type set to I
(000071)04/04/2021 18:45:48 - username (MY_IP)> OPTS UTF8 ON
(000071)04/04/2021 18:45:48 - username (MY_IP)> 202 UTF8 mode is always enabled. No need to send this command.
(000071)04/04/2021 18:45:48 - username (MY_IP)> PBSZ 0
(000071)04/04/2021 18:45:48 - username (MY_IP)> 200 PBSZ=0
(000071)04/04/2021 18:45:48 - username (MY_IP)> PROT P
(000071)04/04/2021 18:45:48 - username (MY_IP)> 200 Protection level set to P
(000071)04/04/2021 18:45:48 - username (MY_IP)> EPSV
(000071)04/04/2021 18:45:48 - username (MY_IP)> 229 Entering Extended Passive Mode (|||RANDOM_PORT_NUMBER|)
(000071)04/04/2021 18:45:48 - username (MY_IP)> MLSD /
(000071)04/04/2021 18:45:48 - username (MY_IP)> 150 Opening data channel for directory listing of "/"
(000071)04/04/2021 18:45:48 - username (MY_IP)> TLS connection for data connection established
(000071)04/04/2021 18:45:48 - username (MY_IP)> 226 Successfully transferred "/"
(000071)04/04/2021 18:45:48 - username (MY_IP)> EPSV
(000071)04/04/2021 18:45:48 - username (MY_IP)> 229 Entering Extended Passive Mode (|||RANDOM_PORT_NUMBER|)
(000071)04/04/2021 18:45:48 - username (MY_IP)> MLSD /test_dir1
(000071)04/04/2021 18:45:48 - username (MY_IP)> 150 Opening data channel for directory listing of "/test_dir1"
```

The only difference I can spot on both FileZilla logs is that, rclone v1.54.1 sends:
 
```
...
OPTS UTF8 ON
PBSZ 0
PROT P
EPSV
MLSD /
```

While rclone v1.55.0 only sends the following commands

```
...
OPTS UTF8 ON
EPSV
MLSD /
```

And those missing `PBSZ 0` and `PROT P` seem to break the session negotiation.

How can I help to debug this issue?

Thanks.

**Comment by ncw** [comment] 2021-04-04 22:45
Is there any chance you could use git bisect to find the commit which broke this?

**Comment by ivandeex** [comment] 2021-04-05 07:35
Let me try to reproduce this on Windows 8.1 with https://filezilla-project.org/download.php?type=server

**Comment by ivandeex** [comment] 2021-04-05 11:21
> How can I help to debug this issue?

Please provide your remote config with secrets redacted

**Comment by ivandeex** [comment] 2021-04-05 12:14
Here is my testbed:
- Windows 8.1 Pro
- FileZilla server latest on internal IP address, one test user with password
- DNS record for that IP
- LetsEncrypt certificate
- rclone 1.52.3, 1.53.0, 1.53.4, 1.54.1, 1.55.0

rclone config:
```
[ftps]
type = ftp
host = testhost.deex.me
user = ftpuser1
pass = xxx
tls = false
explicit_tls = true
```

Results of running various rclone clients:
```
> rclone-1.52.3 ls -vv ftps:dir
2021/04/05 15:06:41 DEBUG : rclone: Version "v1.52.3" starting with parameters ["C:\\abyss\\bin\\rclone-1.52.3.exe" "ls" "-vv" "ftps:dir"]
2021/04/05 15:06:41 DEBUG : Using config file from "C:\\Users\\ivandeex\\.config\\rclone\\rclone.conf"
2021/04/05 15:06:41 DEBUG : ftp://testhost.deex.me:21/dir: Connecting to FTP server
    17408 Thumbs.db
   133341 kitty.jpg
2021/04/05 15:06:41 DEBUG : 2 go routines active

> rclone-1.53.0 ls -vv ftps:dir
2021/04/05 15:06:47 DEBUG : rclone: Version "v1.53.0" starting with parameters ["C:\\abyss\\bin\\rclone-1.53.0.exe" "ls" "-vv" "ftps:dir"]
2021/04/05 15:06:47 DEBUG : Using config file from "C:\\Users\\ivandeex\\.config\\rclone\\rclone.conf"
2021/04/05 15:06:47 DEBUG : Creating backend with remote "ftps:dir"
2021/04/05 15:06:47 DEBUG : ftp://testhost.deex.me:21/dir: Connecting to FTP server
2021/04/05 15:06:47 ERROR : : error listing: directory not found
2021/04/05 15:06:47 DEBUG : 2 go routines active
2021/04/05 15:06:47 Failed to ls with 2 errors: last error was: directory not found

PS C:\Users\ivandeex\rclone> rclone-1.55.0 ls -vv ftps:dir
2021/04/05 15:06:54 DEBUG : Using config file from "C:\\Users\\ivandeex\\.config\\rclone\\rclone.conf"
2021/04/05 15:06:54 DEBUG : rclone: Version "v1.55.0" starting with parameters ["C:\\abyss\\bin\\rclone-1.55.0.exe" "ls" "-vv" "ftps:dir"]
2021/04/05 15:06:54 DEBUG : Creating backend with remote "ftps:dir"
2021/04/05 15:06:54 DEBUG : ftp://testhost.deex.me:21/dir: Connecting to FTP server
2021/04/05 15:06:54 ERROR : : error listing: directory not found
2021/04/05 15:06:54 DEBUG : 2 go routines active
2021/04/05 15:06:54 Failed to ls with 2 errors: last error was: directory not found
```

rclone version output for tested binaries:
```
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7

rclone v1.53.0
- os/arch: windows/amd64
- go version: go1.15

rclone v1.55.0
- os/type: windows
- os/arch: amd64
- go/version: go1.16.2
- go/linking: dynamic
- go/tags: cmount
```

Conclusion: something has changed with TLS handling in the Golang standard library between go 1.14.7 and 1.15

**Comment by ivandeex** [comment] 2021-04-05 12:26
Here is my testbed:
- Windows 8.1 Pro
- FileZilla server latest on internal IP address, one test user with password
- DNS record for that IP
- LetsEncrypt certificate
- rclone 1.52.3, 1.53.0, 1.53.4, 1.54.1, 1.55.0

rclone config:
```
[ftps]
type = ftp
host = testhost.xxx
user = ftpuser1
pass = xxx
tls = false
explicit_tls = true
```

Results of running various rclone clients:
```
2021/04/05 15:06:41 DEBUG : rclone: Version "v1.52.3" starting with parameters ["C:\\bin\\rclone-1.52.3.exe" "ls" "-vv" "ftps:dir"]
2021/04/05 15:06:41 DEBUG : Using config file from "C:\\Users\\ivandeex\\.config\\rclone\\rclone.conf"
2021/04/05 15:06:41 DEBUG : ftp://testhost.xxx:21/dir: Connecting to FTP server
    17408 Thumbs.db
   133341 kitty.jpg
2021/04/05 15:06:41 DEBUG : 2 go routines active

2021/04/05 15:06:47 DEBUG : rclone: Version "v1.53.0" starting with parameters ["C:\\bin\\rclone-1.53.0.exe" "ls" "-vv" "ftps:dir"]
2021/04/05 15:06:47 DEBUG : Using config file from "C:\\Users\\ivandeex\\.config\\rclone\\rclone.conf"
2021/04/05 15:06:47 DEBUG : Creating backend with remote "ftps:dir"
2021/04/05 15:06:47 DEBUG : ftp://testhost.xxx:21/dir: Connecting to FTP server
2021/04/05 15:06:47 ERROR : : error listing: directory not found
2021/04/05 15:06:47 DEBUG : 2 go routines active
2021/04/05 15:06:47 Failed to ls with 2 errors: last error was: directory not found

2021/04/05 15:06:54 DEBUG : Using config file from "C:\\Users\\ivandeex\\.config\\rclone\\rclone.conf"
2021/04/05 15:06:54 DEBUG : rclone: Version "v1.55.0" starting with parameters ["C:\\bin\\rclone-1.55.0.exe" "ls" "-vv" "ftps:dir"]
2021/04/05 15:06:54 DEBUG : Creating backend with remote "ftps:dir"
2021/04/05 15:06:54 DEBUG : ftp://testhost.xxx:21/dir: Connecting to FTP server
2021/04/05 15:06:54 ERROR : : error listing: directory not found
2021/04/05 15:06:54 DEBUG : 2 go routines active
2021/04/05 15:06:54 Failed to ls with 2 errors: last error was: directory not found
```

1.52.3 lists directory correctly
1.53.0 and later fail on TLS

Server output for 1.52.3 (all works):
```
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> Connected on port 21, sending welcome message...
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> 220-FileZilla Server 0.9.60 beta
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> 220 Please visit https://filezilla-project.org/
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> FEAT
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> 211-Features:
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  MDTM
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  REST STREAM
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  SIZE
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  MLST type*;size*;modify*;
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  MLSD
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  AUTH SSL
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  AUTH TLS
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  PROT
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  PBSZ
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  UTF8
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  CLNT
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  MFMT
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  EPSV
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)>  EPRT
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> 211 End
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> USER ftpuser1
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> 331 Password required for ftpuser1
(000083)4/5/2021 15:17:49 PM - (not logged in) (10.33.3.5)> PASS ********
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 230 Logged on
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> TYPE I
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 200 Type set to I
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> OPTS UTF8 ON
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 202 UTF8 mode is always enabled. No need to send this command.
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> EPSV
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 229 Entering Extended Passive Mode (|||62494|)
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> MLSD .
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 150 Opening data channel for directory listing of "/"
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 226 Successfully transferred "/"
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> EPSV
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 229 Entering Extended Passive Mode (|||57640|)
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> MLSD dir
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 150 Opening data channel for directory listing of "/dir"
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> 226 Successfully transferred "/dir"
(000083)4/5/2021 15:17:49 PM - ftpuser1 (10.33.3.5)> disconnected.
```

Server output for 1.53.0 (TLS fails):
```
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> Connected on port 21, sending welcome message...
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 220-FileZilla Server 0.9.60 beta
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 220 Please visit https://filezilla-project.org/
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> AUTH TLS
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 234 Using authentication type TLS
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> TLS connection established
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> FEAT
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 211-Features:
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  MDTM
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  REST STREAM
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  SIZE
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  MLST type*;size*;modify*;
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  MLSD
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  AUTH SSL
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  AUTH TLS
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  PROT
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  PBSZ
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  UTF8
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  CLNT
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  MFMT
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  EPSV
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)>  EPRT
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 211 End
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> USER ftpuser1
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> 331 Password required for ftpuser1
(000084)4/5/2021 15:19:16 PM - (not logged in) (10.33.3.5)> PASS ********
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 230 Logged on
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> TYPE I
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 200 Type set to I
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> OPTS UTF8 ON
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 202 UTF8 mode is always enabled. No need to send this command.
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> PBSZ 0
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 200 PBSZ=0
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> PROT P
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 200 Protection level set to P
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> EPSV
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 229 Entering Extended Passive Mode (|||56810|)
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> MLSD .
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 150 Opening data channel for directory listing of "/"
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 450 TLS session of data connection has not resumed or the session does not match the control connection
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> EPSV
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 229 Entering Extended Passive Mode (|||52503|)
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> MLSD dir
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 150 Opening data channel for directory listing of "/dir"
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 450 TLS session of data connection has not resumed or the session does not match the control connection
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> EPSV
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 229 Entering Extended Passive Mode (|||55098|)
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> MLSD .
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 150 Opening data channel for directory listing of "/"
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> 450 TLS session of data connection has not resumed or the session does not match the control connection
(000084)4/5/2021 15:19:16 PM - ftpuser1 (10.33.3.5)> disconnected.
```

rclone version output for tested binaries:
```
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7

rclone v1.53.0
- os/arch: windows/amd64
- go version: go1.15

rclone v1.55.0
- os/type: windows
- os/arch: amd64
- go/version: go1.16.2
- go/linking: dynamic
- go/tags: cmount
```

Conclusion:
Something has changed with TLS handling in the Go standard library between go 1.14.7 and 1.15

**Comment by aliron19** [comment] 2021-04-05 17:15
Hi @ncw. I'm afraid that's far beyond my knowledge to do this. I could try to learn how to use git bisect, but this is going to take some time.

Regarding @ivandeex testbed, thanks for taking your time to check this. However, your rclone remote config shows `type = ftp` and  `explicit_tls = true`, which means you are using FTPES (FTP over **explicit** TLS), but my setup is using FTPS (FTP over **implicit** TLS). Maybe, that's why your report shows different rclone versions (implicit was working for me up to v1.54.1) failing?

**Comment by ivandeex** [comment] 2021-04-05 17:21
> However, your rclone remote config shows `type = ftp` and `explicit_tls = true`, .....

Just send here your redacted config.

**Comment by aliron19** [comment] 2021-04-05 17:58
Here you are:

```
[ftps_remote]
type = ftp
host = MY_IP
user = username
port = MY_PORT
pass = *** ENCRYPTED ***
tls = true
```

**Comment by ncw** [comment] 2021-04-05 18:18
According to this thread: https://forum.filezilla-project.org/viewtopic.php?t=36903

This should fix the problem in the FileZilla server

> just un-tick
> "Require TLS session resumption on data connection..."

Here is a relevant issue in the FTP library rclone uses: https://github.com/jlaffaye/ftp/issues/203

**Comment by aliron19** [comment] 2021-04-05 20:00
Thanks for sharing your finding, but my FileZilla Server has already unselected that option.

I've seen that the FTP library issue you mention appears as closed from Dec 3, 2020. Should we reopen it, or would it perhaps be better to open a new one?

**Comment by ivandeex** [comment] 2021-04-05 23:20
Doing bisection among only those commits that changed `backend/ftp/...` I found:
- guilty commit: https://github.com/rclone/rclone/commit/edfe183ba2f95120062596c98f23fe91e615b6f7
- guilty PR: https://github.com/rclone/rclone/pull/4266
- quick fix (reverts guilty commit for backend/ftp/...): https://github.com/ivandeex/rclone/commit/fd7bad259607b97a8afa5a7ffa2519dff1da6e98

@aliron19 Please try this beta: [ivandeex/rclone@v1.55.0-ftpx01](https://github.com/ivandeex/rclone/releases/tag/v1.55.0-ftpx01)
It works for me with a config similar to yours.

Tomorrow I will dig what was wrong with that PR. Most probably, a wrong rebase.

**Comment by ncw** [comment] 2021-04-06 08:17
Great digging @ivandeex 🙂 A faulty rebase seems likely. I seem to remember fixing one for that commit already.

**Comment by ncw** [comment] 2021-04-06 09:12
@ivandeex if we can get a fix for this in the next day or two I'd like to put it in a 1.55.1 to go out with the sftp fix.

**Comment by aliron19** [comment] 2021-04-06 09:18
@ivandeex 
I'm pleased to confirm that your beta [ivandeex/rclone@v1.55.0-ftpx01](https://github.com/ivandeex/rclone/releases/tag/v1.55.0-ftpx01) works perfectly fine with my setup.

**Comment by ivandeex** [comment] 2021-04-07 14:24
@aliron19 
Please also try beta https://github.com/ivandeex/rclone/releases/tag/v1.55.0-ftps03

**Comment by aliron19** [comment] 2021-04-07 19:11
> 
> 
> @aliron19
> Please also try beta https://github.com/ivandeex/rclone/releases/tag/v1.55.0-ftps03

I've just tested it, and it seems to work perfectly fine.

**Comment by ivandeex** [comment] 2021-04-08 10:21
@aliron19 
Thank you very much for spotting this, completness of your reports and for thorough testing!

**Comment by aliron19** [comment] 2021-04-08 10:41
Thank you @ivandeex for your quick response and patience.

**Closed** 2021-04-08 22:43 UTC
Labels: Point Release Candidate, Remote: FTP
