### ISSUE TITLE
Can't download to external storage on Android

### ISSUE THREAD

**Issue by FoxP** [rclone/rclone#2468] opened 2018-08-15 09:10 UTC
#### What is the problem you are having with rclone?

rclone can't sync / copy to external storage (micro SD card) content on Android.
See related issue with rcloneExplorer: https://github.com/kaczmarkiewiczp/rcloneExplorer/issues/201

#### What is your rclone version (eg output from `rclone -V`)

1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

- **Phone:** Xiaomi Redmi Note 3 Pro Prime (ARM64)
- **System:** LineageOS 13 Official Stable build (Android 6.0.1_r81 with security patch level 2018-06-05).

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

- `rclone sync`
- `rclone copy`

**Comment by vb0** [comment] 2018-08-15 17:09
I think this works as designed. Please see: https://termux.com/storage.html

_External storage: Storage on external SD cards. Each app has a private folder on the external SD card, and interchange between them needs to use a special API not yet available in Termux._

Please test if you can write to ~/storage/external (you might need to re-run termux-setup-storage if you have a new card), this is the only place you can write to on the card (it works for me without any tweaks). Although this might not be what you want...

**Comment by animosity22** [comment] 2020-01-13 15:59
This looks answered so closing out.

**Closed by animosity22** 2020-01-13 15:59 UTC

**Comment by mirfatif** [comment] 2020-08-14 15:40
@ncw it's not directly related to this issue. I can open a new issue if needed. This comment can be deleted.

Android's Storage Access Framework, which started with Android 4.4, is enforced in Android 10 with name Scoped Storage. Android 11 is probably going to deprecate "Legacy Storage" access i.e. apps will no more be able to access filesystem directly on external shared storage (with some exceptions).
What this means is that apps using such programs and libraries which are not refactored to use Android's SAF won't work the way they do up till now.
`rclone` will also be affected by this, if an app targeting Android 11 intends to use it. A quick solution to this can be to read file (one at a time) from STDIN, instead of filesystem.
So is it poasible to add an option to `rclone` to read file (not file path) from input stream?

**Comment by vb0** [comment] 2020-08-14 16:29
I think this is already implemented, if I understand correctly the ask: https://rclone.org/commands/rclone_rcat/

**Comment by mirfatif** [comment] 2020-08-14 16:43
> I think this is already implemented, if I understand correctly the ask: https://rclone.org/commands/rclone_rcat/

Ha! I totally missed that. I was only thinking about `copy` and `sync`. Looks great. I'll test.

**Comment by x0b** [comment] 2020-08-18 08:04
SAF is an interface that is only available via a JVM Android Context, and it only provides Input /  Output streams, not standard pipes. I.e. rclone cat/rcat won't help you (correct me if your tests indicate otherwise, @mirfatif). 

In the [rcx app](https://github.com/x0b/rcx), we emulate a WebDAV remote and convert rclone fs calls into SAF calls. However, if rclone is executed inside an app that has [``ALL_FILES_ACCESS``](https://developer.android.com/preview/privacy/storage#all-files-access), it will continue to work in Android 11+ without SAF.

**Comment by mirfatif** [comment] 2020-09-12 11:40
> SAF is an interface that is only available via a JVM Android Context, and it only provides Input / Output streams, not standard pipes. I.e. rclone cat/rcat won't help you (correct me if your tests indicate otherwise, @mirfatif).

Get file's URI from SAF. Create Cursor from URI and get file name. Get file's InputStream from URI. Run `rclone rcat remote:/<filename>` Process and get OutputStream (`rclone`'s input stream). Write file's stream to `rclone`'s input stream.

But this approach doesn't seem to go very far. Without filesystem access `rclone` won't be able to check file's metadata. So in case of incremental/differential backups, all file checks would have to be handled manually (not sure if timestamps can be retrieved from URI). Also forking new `rclone` process for every file would be a performance hit for large number of files.

Hopefully Google don't discontinue the `ALL_FILES_ACCESS` in future releases. But the way they threat with every release, discontinuation isn't very unlikely.
