### ISSUE TITLE
rclone sync command duplicates Google Forms files in a Google Drive source directory

### ISSUE THREAD

**Issue by rlkennedyreid** [rclone/rclone#5927] opened 2022-01-19 00:25 UTC
#### What is the problem you are having with rclone?
When syncing from a personal google drive to a shared team drive, Google Forms files are created in the **source** directory. These forms files are duplicates of forms files in **different** directories on the personal drive, not the source directory.

So after running a few syncs, I have a number of directories with numerous Google Forms duplicates, copied from other directories for seemingly no reason.

Verbose logs given below. I've renamed (consistently) some of the directories in the remotes.

#### What is your rclone version (output from `rclone version`)
```text
rclone v1.57.0
- os/version: darwin 11.6.2 (64 bit)
- os/kernel: 20.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.17.2
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
MacOS Big Sur - 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

Source: Personal Drive subdirectory with 3 Google Sheets and a number of identically-named Google Forms (which have come from previous sync runs)
Destination: Shared Drive/Team Drive directory

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```bash
rclone sync --drive-server-side-across-configs personal-google-drive:source/path/in/personal/drive shared-google-drive:test-of-backups/
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```text
2022/01/18 23:53:25 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "sync" "--drive-server-side-across-configs" "-vv" "--log-file" "bug.log" "personal-google-drive:source/path/in/personal/drive" "shared-google-drive:test-of-backups/"]
2022/01/18 23:53:25 DEBUG : Creating backend with remote "personal-google-drive:source/path/in/personal/drive"
2022/01/18 23:53:25 DEBUG : Using config file from "/Users/robin.kennedy-reid/.config/rclone/rclone.conf"
2022/01/18 23:53:25 DEBUG : personal-google-drive: detected overridden config - adding "{Db_Y9}" suffix to name
2022/01/18 23:53:26 DEBUG : Google drive root 'source/path/in/personal/drive': 'root_folder_id = 0AJAQpZqg7mXXUk9PVA' - save this in the config to speed up startup
2022/01/18 23:53:29 DEBUG : fs cache: renaming cache item "personal-google-drive:source/path/in/personal/drive" to be canonical "personal-google-drive{Db_Y9}:source/path/in/personal/drive"
2022/01/18 23:53:29 DEBUG : Creating backend with remote "shared-google-drive:test-of-backups/"
2022/01/18 23:53:29 DEBUG : Creating backend with remote "personal-google-drive,team_drive=0AMwAP092xvWlUk9PVA,root_folder_id=:test-of-backups"
2022/01/18 23:53:29 DEBUG : personal-google-drive: detected overridden config - adding "{V2Bh3}" suffix to name
2022/01/18 23:53:30 DEBUG : fs cache: renaming cache item "personal-google-drive,team_drive=0AMwAP092xvWlUk9PVA,root_folder_id=:test-of-backups" to be canonical "personal-google-drive{V2Bh3}:test-of-backups"
2022/01/18 23:53:30 DEBUG : fs cache: renaming cache item "shared-google-drive:test-of-backups/" to be canonical "personal-google-drive{V2Bh3}:test-of-backups"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : g-form-file: No export formats found for "application/vnd.google-apps.form"
2022/01/18 23:53:30 DEBUG : Google drive root 'test-of-backups': Waiting for checks to finish
2022/01/18 23:53:30 DEBUG : g-sheet-1.xlsx: Modification times differ by 3848h5m24.785s: 2021-08-11 15:41:24.076 +0000 UTC, 2022-01-18 23:46:48.861 +0000 UTC
2022/01/18 23:53:30 DEBUG : g-sheet-2.xlsx: Modification times differ by 2382h59m27.983s: 2021-10-11 16:47:08.075 +0000 UTC, 2022-01-18 23:46:36.058 +0000 UTC
2022/01/18 23:53:30 DEBUG : g-sheet-3.xlsx: Modification times differ by 33533h29m58.689s: 2018-03-23 18:16:37.155 +0000 UTC, 2022-01-18 23:46:35.844 +0000 UTC
2022/01/18 23:53:30 DEBUG : Google drive root 'test-of-backups': Waiting for transfers to finish
2022/01/18 23:53:37 DEBUG : Google drive root 'test-of-backups': Sleeping for 2s before setting the modtime to work around drive bug - see #4517
2022/01/18 23:53:38 DEBUG : Google drive root 'test-of-backups': Sleeping for 2s before setting the modtime to work around drive bug - see #4517
2022/01/18 23:53:39 DEBUG : Google drive root 'test-of-backups': Sleeping for 2s before setting the modtime to work around drive bug - see #4517
2022/01/18 23:53:41 INFO  : g-sheet-3.xlsx: Copied (server-side copy)
2022/01/18 23:53:42 INFO  : g-sheet-2.xlsx: Copied (server-side copy)
2022/01/18 23:53:43 INFO  : g-sheet-1.xlsx: Copied (server-side copy)
2022/01/18 23:53:43 DEBUG : Waiting for deletions to finish
2022/01/18 23:53:43 INFO  :
Transferred:   	          off / off, -, 0 B/s, ETA -
Checks:                 3 / 3, 100%
Transferred:            3 / 3, 100%
Elapsed time:        17.6s

2022/01/18 23:53:43 DEBUG : 13 go routines active
```
**Note:** `g-form-file` is the duplicated Google Form. As can be seen, 11 files were present with the same name before running the command. After running the command, a 12th is created. Looking at the drive activity logs indicates that this file is being copied from an entirely different directory in the personal drive - **not** the source directory.

#### `rclone.conf` file:
```text
[personal-google-drive]
type = drive
client_id = REDACT.apps.googleusercontent.com
client_secret = REDACT
scope = drive
token = {"access_token":"REDACT","token_type":"Bearer","refresh_token":"REDACT","expiry":"2022-01-19T00:21:58.857015Z"}
team_drive =

[drive-auditing]
type = alias
remote = personal-google-drive,team_drive=0ANlBAkmjELiAUk9PVA,root_folder_id=:

[shared-google-drive]
type = alias
remote = personal-google-drive,team_drive=0AMwAP092xvWlUk9PVA,root_folder_id=:
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment] 2022-01-19 13:51
Can you share your rclone.conf as well with no secrets? I'd like to test with one file to get a little more info.

**Comment by rlkennedyreid** [comment] 2022-01-19 16:09
From the documentation, I expect that forms probably can't be copied to the destination because they can't be converted for other cloud platforms. But I'm pretty sure no `rclone sync` command is expected to affect the source directory - correct me if I'm wrong there.

Some extra info - there were a number of directories where the GForms were duplicated versions of GForms already in the directory. It wasn't always the case that the forms were copied from entirely different directories.

It definitely seems to be the rclone command causing the copying - I have the log files from running old sync commands, and there are large batches of copying activity on the drive at the exact times those commands were running.

**Comment by animosity22** [comment] 2022-01-19 16:56
You got some interesting stuff going on there as your copy / sync work on source -> destination generally.

You have aliases pointing around to things as I'm not sure what those do as they don't point to a remote, but to some team drive ID which is different?

Why are you using aliases and not making remotes for the team drive?

**Comment by animosity22** [comment] 2022-01-19 19:14
Those are alias remotes and not drive remotes as I've never seen that before.

Normally, drive remotes are of that type.

**Comment by animosity22** [comment] 2022-01-19 19:21
See the item you linked:

```
[remote]
client_id =
client_secret =
token = {"AccessToken":"xxxx.x.xxxxx_xxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","RefreshToken":"1/xxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxx","Expiry":"2014-03-16T13:57:58.955387075Z","Extra":null}
team_drive = xxxxxxxxxxxxxxxxxxxx
``

That's a team drive remote.

I have no idea what this is:

```
[drive-auditing]
type = alias
remote = personal-google-drive,team_drive=0ANlBAkmjELiAUk9PVA,root_folder_id=:
```

**Comment by rlkennedyreid** [comment] 2022-01-19 19:27
Check out [this forum post](https://forum.rclone.org/t/bulk-create-remotes-to-existing-google-shared-drives/26837) - it seems to be a pretty normal configuration.

**Comment by animosity22** [comment] 2022-01-19 19:31
One post vs majority of configuration / documentation / etc. It works, but isn't "normal".

Good luck as I'm stepping out.

**Comment by rlkennedyreid** [comment] 2022-01-19 19:33
As I said, I configured with the command line rclone tool. Not manually. So the conf file is configured in the way rclone has decided is 'normal'.

**Comment by rlkennedyreid** [comment] 2022-01-20 10:47
Comments seem to have been removed - hence the out-of-context comments from me.

**Comment by ncw** [comment] 2022-01-28 17:28
Rclone can't normally copy google forms, however since you are doing a server side copy then it is copying them.

Do you think you could
- make a new directory
- create a single form in it
- then reproduce the problem

If you can add `-vv --dump bodies --log-file issue-5927.log` to your rclone command then attach `issue-5927.log` this issue.

There won't be any authentication stuff in the log, but there may be file names / personal details you don't want to make public. If so you can redact them with a text editor, or email the file straight to me nick@craig-wood.com - put a link to this issue in the email.

Thanks

**Comment by rlkennedyreid** [comment] 2022-01-31 23:48
Hey thanks for the reply! Yeah I assumed that copying forms may be an issue for non-server side copies, or even some server-side. The main concern was that the copies are in the source directory, which obviously should experience any changes. I'll try and get some time to follow your advised steps by the weekend.

**Comment by rlkennedyreid** [comment] 2022-05-24 23:06
Hi @ncw, very sorry I didn't get back to you, I no longer had access to the infrastructure I was using.

I believe, however, I discovered the cause of the issue. When you make a copy of a Google Sheet which has GForm linked to it, it automatically creates a copy of the associated GForm.

This copy of the GForm gets created in the directory of the original sheet, regardless of where the original GForm is.

So in a situation where you have a GForm and a linked sheet in the same directory and make a copy of both, you'll end up with 2 copies of the form, and 1 copy of the sheet...

**Comment by ncw** [comment] 2022-05-27 17:01
@rlkennedyreid Oh, well spotted. Not sure what I can do about that, but it is good to have an explanation :-)

**Comment by rlkennedyreid** [comment] 2022-05-27 18:08
Yes this seems well out of scope for rclone to account for.

Even Google Drive's web UI reports "n files copied" when many more than n files show up after a copy, so it seems to be something they're not documenting or taking into account in their tools!

**Comment by ncw** [comment] 2022-05-30 16:54
Ha! Not the first quirk we've discovered in Google drive!

I will close this issue then, but it will be here in the archives if someone needs to refer to it.

Thanks.

**Closed by ncw** 2022-05-30 16:54 UTC
Labels: bug, Remote: Drive
