### ISSUE TITLE
Progress shown is overlapping on console during copy command

### ISSUE THREAD

**Issue by viv2793** [rclone/rclone#3530] opened 2019-09-11 12:33 UTC
While running copy command, the progress on console is getting overlapped with console output. This issue comes only when the --log-file flag is used to redirect the logs. I debugged a bit and found out that printProgress() function is not able to correctly calculate the starting and ending position of previously written block. 
Question - How can this overlapping be solved (attaching the screenshot of console to show overlapping) ? 

Command used - 
go run rclone.go copy <source-folder-path> --config <path-to-gcs-config-file> --log-file a.txt -vP

Note - a.txt is the file in which logs are getting redirected.
![progress-issue|690x162](upload://2NkgAjCmEuIViKpGCfDVtlzdmko.png) 
Rclone version used - 
rclone v1.2.0
- os/arch: windows/amd64
- go version: go1.12.9
<img width="673" alt="progress-issue" src="https://user-images.githubusercontent.com/31568028/64697445-7dbe2980-d4be-11e9-84d8-c052667edcc1.PNG">

**Comment by ncw** [comment] 2019-09-11 21:14
I think this is very likely the same issue as https://github.com/rclone/rclone/issues/3500 and https://github.com/rclone/rclone/issues/2623 which is a bug in windows 10 which is fixed in Windows 10 1903

**Comment by animosity22** [comment] 2020-01-12 17:06
This looks to be a duplicate of the above. Closing out.

**Closed by animosity22** 2020-01-12 17:06 UTC
