### ISSUE TITLE
Android Q (Android 10): executable’s TLS segment is underaligned 

### ISSUE THREAD

**Issue by calisro** [rclone/rclone#3515] opened 2019-09-05 15:31 UTC
Have been using rclone on android for a while now. I recently upgraded to Android Q (Android 10) and i'v starting to see this issue. i can't get rclone to run now on android. I was downloading this:

https://beta.rclone.org/test/testbuilds-latest/rclone-android-16-arm

The error i'm getting is:
executable's TLS segment is underaligned: alignment is 4, needs to be at least 32 for ARM Bionic

**Comment by x0b** [comment] 2019-09-05 15:51
AFAIK Android Q needs at least go1.13 - there have been [quite a few changes](https://github.com/golang/go/commits/master/src/runtime/cgo/gcc_android.c) to TLS memory layout for Android Q [between 1.12 and 1.13](https://github.com/golang/go/compare/release-branch.go1.12...release-branch.go1.13#diff-2499). However, I never saw this affecting arm (we complile with go1.12.8), only x86 (https://github.com/x0b/rcloneExplorer/issues/3).

**Comment by calisro** [comment] 2019-09-05 17:17
How hard of an effort is it to move to 1.13?  I'm asking to gauge how long i'd have to go without rclone on android.

Also there was a workaround  in the go.lang ticket.  Is  that something that can be incorporated easier?

https://github.com/golang/go/issues/29674

There's a simple way to fix arm/arm64 by adding an API to Bionic that allocates a single word of static TLS memory at a fixed offset. For example, I could add something like this to Bionic:

> 
> int pthread_alloc_static_tls_word_np(intptr_t* tpoff, void** tlsbase)
> (https://android-review.googlesource.com/c/platform/bionic/+/862083)
> 
> gcc_android_{arm,arm64}.c could then look for the new API with dlopen and fall back to the current allocation behavior if the API is missing.

**Comment by ncw** [comment] 2019-09-06 08:41
> How hard of an effort is it to move to 1.13? I'm asking to gauge how long i'd have to go without rclone on android.

What I need to do is update the rclone/xgo-fuse container to use go1.13

This in turn depends on karalabe/xgo-latest which is currently at go1.12.

I put a issue in there: https://github.com/karalabe/xgo/issues/169

> EDIT2: I just compiled my own with 1.13. Works fine now.

Great :-)

**Comment by ncw** [comment] 2019-11-15 10:56
karalabe/xgo#169 is now fixed, just need billziss/xgo-cgofuse to follow suit!

**Comment by ivandeex** [comment] 2020-11-16 17:54
Latest https://hub.docker.com/r/karalabe/xgo-latest/dockerfile uses go-1.13.x since a year ago
Latest https://hub.docker.com/r/billziss/xgo-cgofuse/dockerfile is based off the former and was updated a week ago.
We are ready for retest

@calisro @x0b 
Does the issue reproduce with latest rclone 1.53.2 ?

**Comment by x0b** [comment] 2020-11-16 23:01
I don't have Android 10 ARM hardware, but I can confirm that 1.53.2 and the latest 1.54 are compiled with the correct go version. In other words, this issue is most likely resolved.

**Comment by ivandeex** [comment] 2020-11-17 00:02
I tried it in latest termux on my redmi with unofficial A10 based Havos-OS and magisk root:
```
$ uname -a
Linux vagrant 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ wget https://beta.rclone.org/v1.53.2/testbuilds/rclone-android-16-arm.gz
$ gunzip rclone-android-16-arm.gz
$ chmod +x rclone-android-16-arm
$ scp rclone-android-16-arm redmi:
$ ssh redmi
Welcome to Termux!
$ pwd
/data/data/com.termux/files/home
$ uname -a
Linux localhost 3.18.140-loki-V3 #2 SMP PREEMPT Tue Feb 25 10:45:32 +05 2020 aarch64 Android
$ ls
rclone-android-16-arm  storage
$ ./rclone-android-16-arm version
CANNOT LINK EXECUTABLE "./rclone-android-16-arm": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
$ su
:/data/data/com.termux/files/home #
:/data/data/com.termux/files/home # ./rclone-android-16-arm version
2020/11/17 00:00:14 ERROR : error reading available plugins: Error creating : /.cache/rclone/webgui/plugins/config
rclone v1.53.2-DEV
- os/arch: android/arm
- go version: go1.13.4
:/data/data/com.termux/files/home # exit
$ exit
logout
```
Probably it's good.

**Comment by ivandeex** [comment] 2020-11-17 00:08
@x0b BTW will we see new RCX this year?

**Comment by x0b** [comment] 2020-11-17 22:09
@ivandeex This month actually, or early december depending on test group results

**Comment by ivandeex** [comment] 2020-11-17 23:29
@calisro please retest

**Comment by ivandeex** [comment] 2021-01-23 00:15
Resolved. Closing due to inactivity.

**Closed by ivandeex** 2021-01-23 00:15 UTC
Labels: OS: Android, bug, build, needs retest, waiting for reply...
