### ISSUE TITLE
_segments container using default policy rather than parent container policy

### ISSUE THREAD

**Issue by ATGiant** [rclone/rclone#2620] opened 2018-10-02 18:30 UTC
Hey there,

We've run into an issue with rclone where the `_segments` container that is created uses the default policy rather than the policy of the parent container. It should be using `X-Storage-Policy: <name>` of the parent container. This causes confusion and in our case wasn't realized until data had already been migrated to it.

Thanks,

Andrei

**Comment by ncw** [comment] 2018-10-03 10:16
Looking at the code

https://github.com/ncw/rclone/blob/d9037fe2be2701b10d8a59ce13519cfdd2dd96dd/backend/swift/swift.go#L913-L919

It looks like the segments container is created with the storage policy.

Can you reproduce this problem with 1.43.1 or [the latest beta](https://beta.rclone.org)?

**Comment by akincer** [comment] 2018-10-05 14:49
I can reproduce this with 1.43.1. I have not tested the latest beta.

**Comment by ATGiant** [comment] 2019-05-02 21:42
@akincer Is this still an issue for you?

**Comment by bebosudo** [comment] 2020-04-02 10:50
I was bitten by this same bug, and I've discovered it once we've already moved several TBs.
Here's a repro:
```
$ swift post -H X-Storage-Policy:ec104 data_ec104
$ swift list
data_ec104

$ truncate -s 6G /tmp/6gb  # just above the default 5 gb threshold
$ rclone copy --progress /tmp/6gb uzh_swift:data_ec104/test
^C  # it doesn't matter if it's copied, we are interested only in _segments creation
$ swift stat data_ec104; swift stat data_ec104_segments
       Container: data_ec104
X-Storage-Policy: ec104

       Container: data_ec104_segments
X-Storage-Policy: replica-2
```

**Comment by ivandeex** [comment] 2021-02-09 16:12
@ATGiant @bebosudo Does the problem reproduce with rclone 1.54?

**Comment by bebosudo** [comment] 2021-02-09 18:35
Hi @ivandeex, unfortunately I changed job and I no longer have access to a swift storage.

**Comment by ivandeex** [comment] 2021-02-09 18:38
@bebosudo Got you
Closing

**Closed by ivandeex** 2021-02-09 18:38 UTC
Labels: Remote: Swift, bug, waiting for reply...
