### ISSUE TITLE
mount2 has uid / gid reversed

### ISSUE THREAD

**Issue by DaElf** [rclone/rclone#4508] opened 2020-08-13 19:06 UTC
#### What is the problem you are having with rclone?
Using --gid / --uid seems to be reversed

```
diff --git a/cmd/mount2/fs.go b/cmd/mount2/fs.go
index 00e97e8a3..0fdd0c811 100644
--- a/cmd/mount2/fs.go
+++ b/cmd/mount2/fs.go
@@ -67,8 +67,8 @@ func setAttr(node vfs.Node, attr *fuse.Attr) {
        modTime := node.ModTime()
        // set attributes
        vfs := node.VFS()
-       attr.Owner.Gid = vfs.Opt.UID
-       attr.Owner.Uid = vfs.Opt.GID
+       attr.Owner.Gid = vfs.Opt.GID
+       attr.Owner.Uid = vfs.Opt.UID
        attr.Mode = getMode(node)
        attr.Size = Size
        attr.Nlink = 1

```

#### What is your rclone version (output from `rclone version`)
~/go/bin/rclone version                                                                                                                           130 ↵ ──(Thu,Aug13)─┘
rclone v1.52.3-297-gaab9aa8a-beta
- os/arch: linux/amd64
- go version: go1.13.8

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux

####  Which cloud storage system are you using? (eg Google Drive)
IBM COS

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

clone mount2 b-ibm: /s3/ibm -o rw,nodev,noatime,suid --gid 64055 --uid 108 --allow-other --buffer-size=16M --vfs-read-chunk-size=64k --vfs-cache-mode=full --cache-dir=/tmp/ram_disk_cache --log-level=DEBUG

**Comment by darthShadow** [comment] 2020-08-13 19:40
Closing as duplicate of #4507

**Closed by darthShadow** 2020-08-13 19:40 UTC
