### ISSUE TITLE
s3: ls/mount -- support access to a specific version of a key

### ISSUE THREAD

**Issue by yarikoptic** [rclone/rclone#5064] opened 2021-02-24 18:50 UTC
#### What is your current rclone version (output from `rclone version`)?

rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.15.5

#### What problem are you are trying to solve?

be able to `rclone ls` (or more important - access `rclone mount`ed) files from S3 where multiple versions of a file exist (and likely differ).  Similarly, I believe, dropbox and possibly others do provide versioning of files (but not sure if exposed via API etc, never tried), so such functionality could be useful there as well.

#### How do you think rclone should be changed to solve that?

Provide 
- a command line option (e.g., `--versions`) for `ls` and `mount` to enable access to versions of the files
- some "semantic" for a file tree, so a user was able to ls/access a specific (not just current) version of a file. E.g., since unlikely to collide, could be just a directory named after the filename with `@` (or something even less to collide, e.g. `.rclone_versions`) where different versions would be listed.  Original file would be present as well, unless it was actually deleted (but prior versions still exist).  May be even aforementioned `--versions` could just become `--versions-dir-suffix SUFFIX` so it would be up for a user to choose its poison (and any non-empty value would trigger this versioning support)

<details>
<summary>e.g., there are two version of s3://openneuro.org/ds000001/CHANGES file and the latest is available (not a DeleteMarker):</summary> 

```shell
$> datalad ls -aL --list-content md5 s3://openneuro.org/ds000001/CHANGES 
Connecting to bucket: openneuro.org
[INFO   ] S3 session: Connecting to the bucket openneuro.org anonymously 
Bucket info:
  Versioning: S3ResponseError: 403 Forbidden
     Website: S3ResponseError: 403 Forbidden
         ACL: <Policy: openneurocommon (owner) = FULL_CONTROL, http://acs.amazonaws.com/groups/global/AllUsers = READ, rblair2 = FULL_CONTROL, http://acs.amazonaws.com/groups/global/AllUsers = READ_ACP>
ds000001/CHANGES 2020-08-21T20:27:29.000Z 286 ver:rgzXS_kxpT28qCt4vE3KfSoKDbRC9Na5  acl:AccessDenied  http://openneuro.org.s3.amazonaws.com/ds000001/CHANGES?versionId=rgzXS_kxpT28qCt4vE3KfSoKDbRC9Na5 [OK] 54904bf147105d8c8d2ef5903eeaadad
ds000001/CHANGES 2020-08-21T20:27:28.000Z DeleteMarker
ds000001/CHANGES 2020-08-21T20:24:13.000Z 291 ver:hdVjSXh5y7Z.SNYCW7G2T9sIPhu75yyw  acl:AccessDenied  http://openneuro.org.s3.amazonaws.com/ds000001/CHANGES?versionId=hdVjSXh5y7Z.SNYCW7G2T9sIPhu75yyw [OK] 63e3213153aa31569fb64710b0c9a113
```
</details>

If I `rclone mount` that bucket, I can only access the latest version:

```shell
$> md5sum /tmp/m-openneuro/ds000001/CHANGES
54904bf147105d8c8d2ef5903eeaadad  /tmp/m-openneuro/ds000001/CHANGES
```

but it would have been cool if there were smth like:

```shell
$> md5sum /tmp/m-openneuro/ds000001/CHANGES{,@/*}
54904bf147105d8c8d2ef5903eeaadad  /tmp/m-openneuro/ds000001/CHANGES
54904bf147105d8c8d2ef5903eeaadad  /tmp/m-openneuro/ds000001/CHANGES@/rgzXS_kxpT28qCt4vE3KfSoKDbRC9Na5
63e3213153aa31569fb64710b0c9a113  /tmp/m-openneuro/ds000001/CHANGES@/hdVjSXh5y7Z.SNYCW7G2T9sIPhu75yyw
```
then we could (ab)use in datalad to provide FUSE'ed access to git-annex'ed content (ref: https://github.com/datalad/datalad/issues/4003)

edit1 from a greedy me: I wish it was also supported somehow for HTTP remotes.  It will not be specifically a "version" but rather "pass additional parameters to HTTP call", e.g. like in the above example we have http://openneuro.org.s3.amazonaws.com/ds000001/CHANGES?versionId=rgzXS_kxpT28qCt4vE3KfSoKDbRC9Na5 URL, so if I could `cat CHANGES@/versionId=rgzXS_kxpT28qCt4vE3KfSoKDbRC9Na5` rclone would operate on a url with those additional parameters (so kinda like versions of the same URL) -- sure thing `rclone` would not be able to list any (until any requested) under that `@/` folder

**Comment by darthShadow** [comment] 2021-02-25 04:29
Closing as duplicate of https://github.com/rclone/rclone/issues/1776. Please add any comments there.

**Closed by darthShadow** 2021-02-25 04:29 UTC
