### ISSUE TITLE
rclone --version fatal error

### ISSUE THREAD

**Issue by sheetalgarde** [rclone/rclone#3590] opened 2019-10-04 17:12 UTC
Running rclone on Ubuntu 16.04 LTS

rclone version v1.49.4.
When there is a large file copy being done to a rclone mount, the command rclone --version failed with the following error-

```
rclone --version
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x15b30e8, 0x16)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/panic.go:774 +0x72 fp=0x7fff133ec2c0 sp=0x7fff133ec290 pc=0x42f272
runtime.sysMap(0xc000000000, 0x4000000, 0x230b218)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mem_linux.go:169 +0xc5 fp=0x7fff133ec300 sp=0x7fff133ec2c0 pc=0x418565
runtime.(*mheap).sysAlloc(0x22f2500, 0x2000, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/malloc.go:701 +0x1cd fp=0x7fff133ec3a8 sp=0x7fff133ec300 pc=0x40b67d
runtime.(*mheap).grow(0x22f2500, 0x1, 0xffffffff)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mheap.go:1252 +0x42 fp=0x7fff133ec400 sp=0x7fff133ec3a8 pc=0x4264e2
runtime.(*mheap).allocSpanLocked(0x22f2500, 0x1, 0x230b228, 0x0)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mheap.go:1163 +0x291 fp=0x7fff133ec480 sp=0x7fff133ec400 pc=0x4263d1
runtime.(*mheap).alloc_m(0x22f2500, 0x1, 0x2a, 0x0)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mheap.go:1015 +0xc2 fp=0x7fff133ec4d0 sp=0x7fff133ec480 pc=0x425c42
runtime.(*mheap).alloc.func1()
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mheap.go:1086 +0x4c fp=0x7fff133ec508 sp=0x7fff133ec4d0 pc=0x45a96c
runtime.(*mheap).alloc(0x22f2500, 0x1, 0x1002a, 0x0)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mheap.go:1085 +0x8a fp=0x7fff133ec558 sp=0x7fff133ec508 pc=0x425f2a
runtime.(*mcentral).grow(0x22f3320, 0x0)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mcentral.go:255 +0x7b fp=0x7fff133ec598 sp=0x7fff133ec558 pc=0x417f8b
runtime.(*mcentral).cacheSpan(0x22f3320, 0x7f17eb500000)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mcentral.go:106 +0x2fe fp=0x7fff133ec5f8 sp=0x7fff133ec598 pc=0x417aae
runtime.(*mcache).refill(0x7f17eb500008, 0x2a)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/mcache.go:138 +0x85 fp=0x7fff133ec618 sp=0x7fff133ec5f8 pc=0x417555
runtime.(*mcache).nextFree(0x7f17eb500008, 0x230b22a, 0x7f17eb500008, 0x8, 0xfffffffffffffff8)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/malloc.go:854 +0x87 fp=0x7fff133ec650 sp=0x7fff133ec618 pc=0x40bea7
runtime.mallocgc(0x180, 0x158eda0, 0x1, 0x230b280)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/malloc.go:1022 +0x793 fp=0x7fff133ec6f0 sp=0x7fff133ec650 pc=0x40c7e3
runtime.newobject(0x158eda0, 0x4000)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/malloc.go:1151 +0x38 fp=0x7fff133ec720 sp=0x7fff133ec6f0 pc=0x40cbd8
runtime.malg(0x8ac600008000, 0x22f4b90)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/proc.go:3232 +0x31 fp=0x7fff133ec760 sp=0x7fff133ec720 pc=0x438611
runtime.mpreinit(...)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/os_linux.go:324
runtime.mcommoninit(0x22ecfc0)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/proc.go:626 +0xc2 fp=0x7fff133ec798 sp=0x7fff133ec760 pc=0x432032
runtime.schedinit()
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/proc.go:543 +0x72 fp=0x7fff133ec7f0 sp=0x7fff133ec798 pc=0x431c92
runtime.rt0_go(0x7fff133ec828, 0x2, 0x7fff133ec828, 0x0, 0x0, 0x2, 0x7fff133ed887, 0x7fff133ed88e, 0x0, 0x7fff133ed898, ...)
        /opt/hostedtoolcache/go/1.13.1/x64/src/runtime/asm_amd64.s:214 +0x125 fp=0x7fff133ec7f8 sp=0x7fff133ec7f0 pc=0x45cde5
```

The copy however was not interrupted. Also, running rclone --version after 10 minutes reported the version successfully.

**Comment by terorie** [comment] 2019-10-05 01:30
@sheetalgarde Your system ran out of memory. This is not really an rclone bug. However, S3 uploads use a lot of memory sometimes (https://github.com/rclone/rclone/issues/3568). A fix can be expected soon.

In the meantime, you can add more swap space as a workaround: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

Alternatively, https://www.downloadmoreram.com and pray.

**Comment by animosity22** [comment] 2020-01-10 12:25
This is a duplicate of https://github.com/rclone/rclone/issues/3568 and should be addressed as noted above.

**Closed by animosity22** 2020-01-10 12:25 UTC
