### ISSUE TITLE
systemctl can't auto mount after version 1.50 when boot. (it's normal by manual exec.)

### ISSUE THREAD

**Issue by jjasoncool** [rclone/rclone#4791] opened 2020-11-21 17:59 UTC
#### What is your rclone version (output from `rclone version`)
I have tested version 1.49.5 is normal.
version **after 1.51.0**  has this issue.
I don't change any settings below, just change the version of rclone binary file .

#### Which OS you are using and how many bits 
fedora 33

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf

rclone.service - rclone
     Loaded: loaded (/etc/systemd/system/rclone.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2020-11-22 01:52:08 CST; 58s ago
    Process: 1026 ExecStart=/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf (code=exited, status=1/FAILURE)
        CPU: 53ms

11月 22 01:52:08 coding.jason systemd[1]: Starting rclone...
11月 22 01:52:08 coding.jason rclone[1026]: 2020/11/22 01:52:08 Failed to create file system for "Google_Drive:/": couldn't find root directory ID: Get "https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true": dial tcp: lookup www.googleapis.com on 127.0.0.53:53: server misbehaving
11月 22 01:52:08 coding.jason systemd[1]: rclone.service: Control process exited, code=exited, status=1/FAILURE
11月 22 01:52:08 coding.jason systemd[1]: rclone.service: Failed with result 'exit-code'.
11月 22 01:52:08 coding.jason systemd[1]: Failed to start rclone.

**Comment by ivandeex** [comment] 2020-11-22 08:27
1. I see the problem here:
```
dial tcp: lookup www.googleapis.com on 127.0.0.53:53: server misbehaving
```
Either your mount starts slightly before the network is up (configured, finished DHCP if any) or `systemd-resolved` is slow starting / misbehaving.

2. Make sure you have this in your `/etc/systemd/system/YOUR_UNIT.service` file:
```
[Unit]
....
After=network-online.target
Wants=network-online.target
```

3. Please paste here your `.service` file for further analysis. Redact `Environment=` clauses wirh secrets if any.

**Comment by ivandeex** [comment] 2020-11-22 09:23
Sidenote: it looks as if around v1.50 the Gdrive backend started refreshing directory id cache at init and became more dependant on network availability. If so, it's not a bug but implementation detail.

**Comment by jjasoncool** [comment] 2020-11-23 03:08
> 1. I see the problem here:
> 
> ```
> dial tcp: lookup www.googleapis.com on 127.0.0.53:53: server misbehaving
> ```
> 
> Either your mount starts slightly before the network is up (configured, finished DHCP if any) or `systemd-resolved` is slow starting / misbehaving.
> 
> 1. Make sure you have this in your `/etc/systemd/system/rclone.service` file:
> 
> ```
> [Unit]
> ....
> After=network-online.target
> Wants=network-online.target
> ```
> 
> 1. Please paste here your `.service` file for further analysis. Redact `Environment=` stanzas with secrets if any.

OK, I will try this.
Because many tutorial server conf as follow.
```
    [Unit]
    Description=rclone
    After=network.target

    [Service]
    User=jason
    Group=jason
    Type=forking
    ExecStart=/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf
    ExecStop=/usr/bin/fusermount -uz /home/jason/Google_Drive
    Restart=1

    [Install]
    WantedBy=multi-user.target
```

**Comment by animosity22** [comment] 2020-11-24 15:24
You don't want forking either, you want notify.

```
Type=notify
```

**Comment by jjasoncool** [comment] 2020-11-27 02:03
> Type=notify

Hello @animosity22 

I don't know why that I setting `rclone.service` `Type=notify`, it's don't work.

**Comment by animosity22** [comment] 2020-11-27 11:57
You'd have to share more information as notify is the right setting.

**Comment by ivandeex** [comment] 2020-11-28 14:41
@animosity22 

Please point me to a forum thread that compared running `Type=notify` vs `simple` or `fork`.

**Comment by animosity22** [comment] 2020-11-28 15:54
A forking process starts a new process which rclone does not do.

https://rclone.org/commands/rclone_mount/#systemd

![image](https://user-images.githubusercontent.com/5088712/100519771-05499400-3168-11eb-85ea-6ee2aa8351a4.png)

**Comment by ivandeex** [comment] 2020-11-28 16:25
@animosity22 
Systemd notification was committed this May, it's a rather new feature.

https://github.com/rclone/rclone/issues/992#issuecomment-612432627

> Rclone emits a systemd notification when it is mounted. I don't know how that actually works though - I just used this libary: https://github.com/okzk/sdnotify

I thought you know some real world discussions of it from rclone forum.

I have compared rclone mount under systemd (both as a service and as a mount/automount unit) against more battle tested _sshfs_, found a few quirks. While it is ok for normal use, I think needs some stability improvements before I start using it as an docker volume manager where mounts/unmounts will happen frequently as short-living containers pop up and exit.

I will investigate it further when I work on https://github.com/rclone/rclone/issues/2968

@jjasoncool 
I suggest that `Type=notify` is optional for the time being. If `simple` (or even `fork`) works better for a user, so let it be.

**Comment by animosity22** [comment] 2020-11-28 16:59
@jjasoncool  That's really bad advice as rclone doesn't fork so you do not want to use forking as systemd expects it to launch a new process:

```
If set to forking, it is expected that the process configured with ExecStart= will call fork() as part of its start-up. The parent process is expected to exit when start-up is complete and all communication channels are set up. The child continues to run as the main service process, and the service manager will consider the unit started when the parent process exits. This is the behavior of traditional UNIX services. If this setting is used, it is recommended to also use the PIDFile= option, so that systemd can reliably identify the main process of the service. systemd will proceed with starting follow-up units as soon as the parent process exits.

```

and that is not what rclone does.

simple works but the best choice is notify, which is why all the rclone documentation references it.

The reason for notify is that is returns back to systemd that rclone is started and is recommended.

@ivandeex  - There are many, many links on the forums:

https://forum.rclone.org/t/systemd-mount-failed-to-unmount/6002/5
https://forum.rclone.org/t/unable-to-mount-rclone-remote-using-systemd/11387/2
https://forum.rclone.org/t/using-rclone-mount-with-systemd/14780/3

If you hit search on the forums and enter in 'systemd notify', you can find many more links.

https://www.freedesktop.org/software/systemd/man/systemd.service.html

@ncw might be able to add more detail how rclone implements it as I am speaking from a Linux admin's experience and recommending based on what rclone does based on @ncw's comments in previous posts.

**Comment by ivandeex** [comment] 2020-11-28 17:35
@jjasoncool 
> I don't know why that I setting `rclone.service` `Type=notify`, it's don't work.

1. Please check that you did `systemctl daemon-reload` after editing unit file
2. Make sure the old rclone process was killed by `systemctl stop rclone.service`:
```
pgrep -af rclone
journalctl -u rclone.service
```
3. If `stop` didn't kill it (it happens when you try many variants), kill it manually. Start from `kill -INT PID`, if it doesn't help, the `kill -9 PID` is your sledge hammer.
4. Check that remote was unmounted by `stop`. Run `fuser -v /path` or `df -h /path`. If needed, purge the mount from kernel tables by `sudo umount -l /path`.
5. Now as process and mount are cleaned and systemd is reloaded, take a look at your unit file. Looks fine? Fire `systemctl restart rclone.service`
6. See `journalctl -u rclone`. Post it here if the problem persists.
7. Still persists? Try `Type=notify`, then `simple`, then `fork` in that order.
8. Still? Try removing `Restart=1`
9. Still? See working configs on the forum links above.

I hope https://github.com/rclone/rclone/issues/4791#issuecomment-731715139 shoyld have helped with the initial _boot-time_ problem. Can you confirm that?

@animosity22 
Thank you for links. That's what I wanted.

**Comment by animosity22** [comment] 2020-11-28 17:56
The general problem folks have with systemd is when they stop and also do not have KillMode=none, it eventually kills the process after a period of time and the mountpoint is left in a not working state.

Fuse mounts are tough as you need to stop all processes from hitting the mount point to cleanly unmount them and have rclone properly exit which is also when I have KillMode=none

It's best to build all your system service around some requirements and make sure things stop that need to be stopped when you want to stop rclone.

When I stop rclone, I use Requires=rclone.service which allows systemd to stop every service that hits my mount points so things can restart properly.

There is a nice lengthy issue here with that:

https://github.com/rclone/rclone/issues/4487

**Comment by ivandeex** [comment] 2020-11-28 22:14
I extracted the final succesful service file from https://github.com/rclone/rclone/issues/4487 and slightly beautified it:
```
...
```

**Comment by ivandeex** [comment] 2020-11-28 22:24
Let's compare it against _bad_ config from @jjasoncool (beautified again)
```
# /etc/systemd/syste/rcline.conf
  [Unit]
    Description=rclone
    After=network.target

    [Service]
    User=jason
    Group=jason
    Type=forking
    ExecStart=/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf
    ExecStop=/usr/bin/fusermount -uz /home/jason/Google_Drive
    Restart=1

    [Install]
    WantedBy=multi-user.target
```

**Comment by ivandeex** [comment] 2020-11-28 23:25
What's bad in _bad_?
Let's see...
1. `Restart=2` - plain wrong, see _good file_ and systemd docs (many advice sites from google search are just pure copy-pasted SEO crap, sorry)
2. `After=network.target` - You should use `network-online.target`. The former triggers instantaneously after systemd _starts_ network services, while the latter also waits for _started_ network services to bring up network interfaces, get DNS servers IPs from DHCP etc (this can take few seconds), resulting in _online state_ ...[see _note#1_ below]
3. `--daemon` - daemonization (aka forking) in rclone is currently unstable, don't use it for now ...[see _note#2_ below]
4. `Type=forking` - would work if `--daemon` worked, for now please use `notify`...[see _note#3_]
5. `KillMode=none` - advisable since rclone might be fragile when killed by systemd, it's better to signal it by unmounting, which is done by `fusermount -u` ...[see _note#4_]

Other flags are really up to your taste.
`User=nonrootuser` is not actually bad. If you remove it then systemd will run rclone as root and without `allow-other` the mount will be inaccessible for ordinary users.

**Note#1**: `Wants=network-online.target` is recommended too (though optional), see systemd docs for details

**Note#2**: With `--daemon` rclone is in fact _forking_, it really forks but does it uncleanly. This will be eventually fixed by https://github.com/rclone/rclone/issues/2968 (as I want https://github.com/rclone/rclone/issues/4750 which blocks on it)

**Note#3**: Difference between `Type=simple` and `notify` is that systemd declares the _former_ started right after binary has been loaded and started execution, but will additionally wait for a special packet over _d-bus_ from the _latter_ service (rclone triggers it after mount preparations are done, typically few seconds). This is only important if another service depends on _rclone.service_, otherwise `notify` is optional (systemd will just ignore the packet)

**Note#4**: @animosity22 I wonder whether anyone on forum tried `fusemount -l ...`? Lazy (-l) mode is stronger, it makes the mount immediately invisible for _new_ processes even if the mount path is held by a stuck process, thus preventing locked unmounts.

Hope it helps

**Comment by jjasoncool** [comment] 2020-11-29 11:23
> @animosity22
> 
> Please point me to a forum thread that compared running `Type=notify` vs `simple` or `fork`.

notify
```
● rclone.service - rclone
     Loaded: loaded (/etc/systemd/system/rclone.service; enabled; vendor preset: disabled)
     Active: failed (Result: protocol) since Sun 2020-11-29 19:20:04 CST; 8s ago
    Process: 3529 ExecStart=/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf (code=exited, status=0/SUCCESS)
   Main PID: 3529 (code=exited, status=0/SUCCESS)
        CPU: 41ms

11月 29 19:20:04 coding.jason systemd[1]: Starting rclone...
11月 29 19:20:04 coding.jason systemd[1]: rclone.service: Failed with result 'protocol'.
11月 29 19:20:04 coding.jason systemd[1]: Failed to start rclone.

```
forking
```
● rclone.service - rclone
     Loaded: loaded (/etc/systemd/system/rclone.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2020-11-29 19:22:25 CST; 2s ago
    Process: 3781 ExecStart=/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf (code=exited, status=0/SUCCESS)
   Main PID: 3800 (rclone)
      Tasks: 27 (limit: 38357)
     Memory: 10.7M
        CPU: 218ms
     CGroup: /system.slice/rclone.service
             └─3800 /usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf

```

simple 
```
● rclone.service - rclone
     Loaded: loaded (/etc/systemd/system/rclone.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2020-11-29 19:23:18 CST; 2s ago
    Process: 3927 ExecStart=/usr/local/bin/rclone mount Google_Drive:/ /home/jason/Google_Drive --vfs-cache-mode full --default-permissions --allow-non-empty --daemon --allow-other --config /home/jason/.config/rclone/rclone.conf (code=exited, status=0/SUCCESS)
    Process: 3952 ExecStop=/usr/bin/fusermount -uz /home/jason/Google_Drive (code=exited, status=203/EXEC)
   Main PID: 3927 (code=exited, status=0/SUCCESS)
        CPU: 48ms

11月 29 19:23:18 coding.jason systemd[1]: Started rclone.
11月 29 19:23:18 coding.jason systemd[3952]: rclone.service: Failed to execute command: Permission denied
11月 29 19:23:18 coding.jason systemd[3952]: rclone.service: Failed at step EXEC spawning /usr/bin/fusermount: Permission denied
11月 29 19:23:18 coding.jason systemd[1]: rclone.service: Control process exited, code=exited, status=203/EXEC
11月 29 19:23:18 coding.jason systemd[1]: rclone.service: Failed with result 'exit-code'.

```

**Comment by jjasoncool** [comment] 2020-11-29 11:27
> What's wrong with _failing_?
> Let's see...
> 
>     1. `Restart=2` - plain wrong, see _good file_ and systemd docs (many advice sites from google search are just copy-pasted SEO-clickbaity crap, sorry)
> 
>     2. `After=network.target` - You should use `network-online.target`. The former triggers instantaneously after systemd _starts_ network services, while the latter also waits for _started_ network services to bring up network interfaces, get DNS servers IPs from DHCP etc (this can take few seconds), resulting in _online state_ ...[see _note#1_ below]
> 
>     3. `--daemon` - daemonization (aka forking) in rclone is currently unstable, don't use it for now ...[see _note#2_ below]
> 
>     4. `Type=forking` - would work if `--daemon` worked, for now please use `notify`...[see _note#3_]
> 
>     5. `KillMode=none` - advisable since rclone might be fragile when killed by systemd, it's better to signal it by unmounting, which is done by `fusermount -u` ...[see _note#4_]
> 
> 
> Other flags are really up to your taste.
> `User=nonrootuser` is not actually bad. If you remove it then systemd will run rclone as root and without `allow-other` the mount will be inaccessible for ordinary users.
> 
> **Note#1**: `Wants=network-online.target` is recommended too (though optional), see systemd docs for details
> 
> **Note#2**: With `--daemon` rclone is in fact _forking_, it really forks but does it uncleanly. This will be eventually fixed by #2968 (as I want #4750 which blocks on it)
> 
> **Note#3**: Difference between `Type=simple` and `notify` is that systemd declares the _former_ as _started_ right after the binary has been loaded and started execution, but will additionally wait for a special packet over _d-bus_ from the _latter_ service (rclone triggers it after mount preparations are done, typically few seconds). This is only important if another service depends on _rclone.service_, otherwise `notify` is optional (systemd will just ignore the packet)
> 
> **Note#4**: @animosity22 I wonder whether anyone on forum tried `fusermount -l ...`? Lazy (-l) mode is stronger, it makes the mount immediately invisible for _new_ processes even if the mount path is held by a stuck process, thus preventing locked unmounts.
> 
> P.S. Mounting is 30+ years old facility in Linux and drags along 30+ years of historical compatibility crap, like many Windows APIs still carry MSDOS baggage in 2020. It's neigher good nor bad, rather ugly at times.
> 
> Hope it helps

When I remove flag --daemon
And change Type=notify
it's work.

**Comment by ivandeex** [comment] 2020-11-29 11:34
> I suggest in the document should write --daemon flag will need to change service Type=forking

And recommend against it :)

**Comment by jjasoncool** [comment] 2020-11-29 11:35
> > I suggest in the document should write --daemon flag will need to change service Type=forking
> 
> And recommend against it :)

OK, hahaha!!

In fedora latest version 33.

have notice message below:
```
11月 29 19:26:46 coding.jason systemd[1]: Starting rclone...
11月 29 19:26:46 coding.jason systemd[1]: Started rclone.
11月 29 19:33:52 coding.jason systemd[1]: /etc/systemd/system/rclone.service:23: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
```

**Comment by ivandeex** [comment] 2020-11-29 11:37
@jjasoncool 
Please post here your final config after monitoring for some time in prod (especially boots). It's gonna help others. Thanks

**Comment by ivandeex** [comment] 2020-11-29 11:46
Offtopic:
The problem of killing dead mounts becomes even worse when people try it in automated environments when container orchestrator (kubernetes or swarm) creates and drops services continuously. I've seen attempts to mitigate unmount locks as ugly as [this](https://github.com/sapk/docker-volume-rclone/pull/47/files#diff-26febfa18b49dfb19cf1c3a7d72c601554fe8e99c0bcad4c8f5fd71dbf919e10R214)...

**Comment by jjasoncool** [comment] 2020-11-29 11:48
> @jjasoncool
> Please post here your final config after monitoring for some time in prod (especially boots). It's gonna help others. Thanks

[Unit]
Description=RClone Service
After=network-online.target
Wants=network-online.target

[Service]
User=jason
Group=jason
Type=notify
Restart=1

ExecStart=/usr/local/bin/rclone \
mount Google_Drive:/ \
/home/jason/Google_Drive \
--config /home/jason/.config/rclone/rclone.conf
--vfs-cache-mode full \
--default-permissions \
--allow-non-empty \
--allow-other \

ExecStop=/usr/bin/fusermount -uz /home/jason/Google_Drive

[Install]
WantedBy=multi-user.target

**Comment by ivandeex** [comment] 2020-11-29 11:55
Restart=1 might work for you but see https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart= and https://github.com/rclone/rclone/issues/4791#issuecomment-735304299

**Comment by ivandeex** [comment] 2020-11-29 11:57
```--allow-other \``` followed by empty line is unclean

**Comment by jjasoncool** [comment] 2020-11-29 12:02
> `--allow-other \` followed by empty line is unclean

I have fixed it!
Thank you!

**Closed** 2020-11-29 19:28 UTC
Labels: OS: Unix, Remote: Drive, VFS / mount, doc fix, question

**Comment by jjasoncool** [comment] 2020-12-04 03:42
Hello @ivandeex 
May I ask a question about `--default-permissions` and `--umask 002`?
Because I am using git on google drive, but git do some command like `git commit` will prompt `permission deny` or `I/O error`.
Is this relate to file permissions?
Thank you.

**Comment by ivandeex** [comment] 2020-12-04 14:36
https://forum.rclone.org/ has similar topics
