### ISSUE TITLE
RCLONE stamp at the start of encrypted files

### ISSUE THREAD

**Issue by NumberedThought** [rclone/rclone#1894] opened 2017-12-08 02:52 UTC
rclone v1.38-030-g94171947β
- os/arch: linux/amd64
- go version: go1.9

When Rclone encrypts files, it stamps the word RCLONE as the first few bits.  This makes files encrypted with rclone extremely easy to detect by automated processes.

Can this please be removed?
![image](https://user-images.githubusercontent.com/25142109/33748881-d03eb6d2-db7f-11e7-8583-5d757645974d.png)

**Comment by zenjabba** [comment] 2017-12-08 02:55
agreed. I am also seeing this in rclone

```
rclone v1.38-211-gbb3ba7b3β
- os/arch: linux/amd64
- go version: go1.9.2

**Comment by ncw** [comment] 2017-12-08 09:32
It is considered good practice to embed a [magic numbers at the start of file formats](https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files) to detect errors and so that you don't try to interpret a file which is obviously the wrong type.

It would be possible to remove the magic from the start of the crypt files.  That would mean rclone can't be certain which files are encrypted files or not, which would make some kind of errors more likely.

It is a trade-off, so it could be an option I suppose!

However I'm intending to use the magic to separate v1 crypt files from any further revisions.

The magic is actually 8 characters `RCLONE` plus two null bytes.  I'm intending that the two null bytes are used as a kind of version number, giving a possible 64k types to the file.

**Comment by NumberedThought** [comment] 2017-12-15 03:13
Perhaps it would be better to have the magic numbers a random string, or string known only to the app to make files not so readily identifiable as encrypted by Rclone.  Some cloud providers are looking at or are actively blocking rclone from being used.  The current magic number implementation could give them ammunition against legitimate users

**Comment by zenjabba** [comment] 2017-12-15 03:14
agreed, it also gives a vector of attack against rclone encrypted files.

**Comment by ivandeex** [comment] 2020-11-16 21:05
I suggest closing as this is an expected behavior.
A random, long enough _crypt_ password will provide a good security against cracking (no flame intended). 
SSH too provides a clear signature in the first response,
just try `curl http://your-own-server.com:22` and behold.

@ncw
I suggest to mention this explicitly in the rclone documentation and close as not an issue

**Comment by ivandeex** [comment] 2021-02-10 20:11
Closing after 3+ years of inactivity

**Closed by ivandeex** 2021-02-10 20:11 UTC
Labels: Remote: Crypt, doc fix, question
