### ISSUE TITLE
Dropbox poll-interval support

### ISSUE THREAD

**Issue by andresmatasuarez** [rclone/rclone#4548] opened 2020-09-01 16:25 UTC
Hi! I'm trying to make the usual streaming Plex media server on a VPS by mounting my Dropbox movie directory with `rclone`.

I noticed that `poll-interval` is not supported with Dropbox remotes, and so I'm currently mounting my cloud drive with `dir-cache-time` set to `1`. I don't know what the exact implications of doing that are performance-wise; I'd really appreciate it if we can discuss them here as I'm willing to work on a solution to this.

The relevant Dropbox API endpoint that matches this scenario would be:
https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-longpoll

What's your opinion on this matter?

**Comment by animosity22** [comment] 2020-09-01 17:07
This is a duplicate of:

https://github.com/rclone/rclone/issues/2949

It's been idle a bit so I'd close this out and just use the one listed.

**Comment by animosity22** [comment] 2020-09-02 12:29
Closing out as duplicate.

**Closed by animosity22** 2020-09-02 12:29 UTC
