### ISSUE TITLE
Support multi-threaded downloads when downloading a file to the cache

### ISSUE THREAD

**Issue by darthShadow** [rclone/rclone#4760] opened 2020-11-11 20:07 UTC
#### What is your current rclone version (output from `rclone version`)?

rclone v1.54.0-beta.4889.45e8bea8d
- os/arch: linux/amd64
- go version: go1.15.3

#### What problem are you are trying to solve?

With rclone copy, and --multi-thread-streams set to 4, I get speeds of up to 40 MB/s whereas the same with rclone mount gives me only 10 MB/s (which is equal to the value obtained via rclone copy with the number of streams set to 1).

#### How do you think rclone should be changed to solve that?

Add support for multi-threaded downloads when downloading a file to the vfs cache. Per @ncw and this thread (https://forum.rclone.org/t/multi-threaded-downloads-comments-and-testers-needed/9721/18), this was present in the previous iteration of the full-mode cache but was removed to add support for partial downloads/streams.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by qazero** [comment] 2021-01-11 09:38
I too am very much interested in this feature. Any chance we can have this implemented?

**Comment by Silent-Remux** [comment] 2021-01-14 20:13
Here here, this would be a very welcome addition to rclone.

**Comment by luxus** [comment] 2021-02-02 21:43
another vote :D

**Comment by aleliaert** [comment] 2021-02-12 16:01
+1

**Comment by whiteworthy** [comment] 2021-04-24 03:40
+1

**Comment by whiteworthy** [comment] 2021-04-24 04:27
Is there any current solution for this?

**Comment by ncw** [comment] 2021-04-25 15:49
This feature is under consideration at the moment - watch this space!

**Comment by whiteworthy** [comment] 2021-07-11 16:32
Is this still planned for 1.56?

**Comment by ivandeex** [comment] 2021-07-11 19:32
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ivandeex** [comment] 2021-11-10 13:25
Marked as important after 18 total thumbs up

**Comment by dihmandrake** [comment] 2021-12-15 15:44
I ran across this issue as well and noted that the rclone documentation mentions "Multi thread downloads will be used with rclone mount and rclone serve if `--vfs-cache-mode` is set to `writes` or above" [here](https://rclone.org/docs/#multi-thread-cutoff-size).

Is this issue still actual or is the documentation outdated as it appears (according to the comments in this issue) that multi-threaded downloads used to work before.
In case the documentation is outdated it might help other users to mention that multi-thread downloads do not work for mount/serve operations in the documentation.

**Comment by agneevX** [comment] 2021-12-15 16:25
I see the documentation now. It doesn't appear to be correct from my testing.

**Comment by Abdulla060** [comment] 2022-01-28 23:50
I could really use this if it's implemented

**Comment by seertenedos** [comment] 2022-05-08 03:39
one feature i would love to see is the ability for multi download of different parts of the file based on the requests coming into the VFS eg. if say a file is being read from in 2 different places the read-ahead would run for both locations in the file. Currently it sort of feels like it cancels 1 read-ahead to go to the other location then reads a bit there and then flips back.  That said i could be wrong as i am still investigating my issue.

**Comment by rudnypc** [comment] 2022-06-11 17:15
up

**Comment by rudnypc** [comment] 2022-06-11 17:18
I would like to use VFS CACHE instead of the OLD CACHE, But the multithread download is very important.

**Comment by RemuxKid** [comment] 2022-09-30 06:54
Hi, after seeing many forum posts on the forum, and this thread, I see you were interested in the use cases for this to be implemented.

After a lot of testing and trying to compare some else mount with mine, I see a massive issue with peering. In my particular example, I am using Dropbox and connecting to my files through Europe. After asking Dropbox about where servers are located, they are primarily in the US, the article can be found [here](https://help.dropbox.com/security/physical-location-data-storage). 

I'm referring to this ticket [here](https://github.com/animosity22/homescripts/issues/98) where it shows more information about speeds. Thanks again animosity22 for the support!

Multi-threading is a lot closer to utilising the speed of transfers, in my instance, this is a Gbit server and doesn't have I/O blockers. I've not had issues with Google (but they have a beefier backbone with more geo-located servers).

I'd also seen a few remarks of bringing this back, and would be keen to know if this is the aim :)

Thanks in advance!

**Comment by venomone** [comment] 2022-10-10 23:38
I would also love to see this feature. Currently I dont get fast transferes using the StorJ hosted Gateway as backend for rclone... If I'm lucky I get 15 MB/s per connection ... yeah... The server has 5 Gbit/s ...

**Comment by peterhase** [comment] 2022-10-11 08:42
I would also love to see this feature

**Comment by paul-chambers** [comment] 2023-01-15 05:46
One more vote for this.

I'm running a VPS overseas, and would like to use 'rclone mount' on that VPS to an SFTP server at home. The VPS has a >10Gbps connection, my home connection is about 1.4 Gbps, but the latency between the two is ~150ms. So a classic 'high latency fat pipe' where the latency constrains the throughput, not the bandwidth.

Pulling from home, a single-threaded 'move' of a single large file manages about 25-30 GB/sec, a multi-threaded 'move' can manage around 150 MB/sec on average (one file or many). Being able to obtain the latter throughput would make it practical to move to a less expensive VPS with SSD storage, which I expect will be well-suited for 'vfs-cache-mode full'

- Paul

**Comment by youtehub** [comment] 2023-02-25 08:54
I would also love to see this feature. 
After mounting a web disk as a webdav, using rclone to mount the webdav local disk, copying files can be slow
, especially for some rate-limiting web disk mounts that download at woefully low speeds, but use multithreaded downloaders like bitcomet

Internet Download Manager, these two programs are very fast when downloading files under webdav, because they both support multi-threaded, chunked downloads.

Now using rclone to mount webdav with block multithreading enabled still has no effect, hope to support cache multithreading download soon.

```
 /extdisk01/software/rclone/rclone  mount  thunderData: /extdisk02/minioData/thunderdata   --config /extdisk01/software/rclone/rclone.conf   --vfs-cache-mode writes   --allow-non-empty   --no-modtime  --umask 0000  --default-permissions  --dir-perms 777   --file-perms  777 --allow-other  --multi-thread-streams 32  --multi-thread-cutoff 128M  --buffer-size 2G  --transfers 32  --checkers 64  --cache-chunk-size 300M  --cache-chunk-total-size 4G  --vfs-read-chunk-size 300M --vfs-read-chunk-size-limit 2G  --vfs-cache-max-size 2G   --vfs-disk-space-total-size 6G  --log-file=/extdisk01/software/rclone/log/rclone-thunderdata02.log  &  

```

**Comment by s1dave-web** [comment] 2023-07-13 20:11
Think I am also running into this limitation.

rclone mount - cp command will hit 20-30Mbps
rclone copy command for the same file will hit 100Mbps (connection limit)

+1 vote for this to be added

**Comment by Wishall05** [comment] 2024-01-11 12:28
I also feel it's an impacting issue for users wanting to download large files via rclone mount. 
when are we planning this? Hope this supports multithreading download soon.

**Comment by hekmon** [comment] 2024-01-11 13:39
I know that for others @ncw can [ask for sponsorship](https://github.com/rclone/rclone/issues/4595#issuecomment-1029884558) in order to tackle (or prioritise) one particular feature (especially if this is a big one).

Given the number of thumbs up on this issue (and it's age) would it be acceptable for you @ncw to open a crowdfunding sponsorship for this issue ? I'm willing to participate but I can not say I am able to sponsor the whole thing on my own :)

**Comment by willjgit** [comment] 2024-01-14 22:03
+1 would love this to be fixed.

**Comment by Arif59** [comment] 2024-01-18 12:35
Yes please, I'd love to have this feature

**Comment by venomone** [comment] 2024-02-27 22:56
Feature request since 2020, this is ridicules, start a funding process, and I'll donate ...
n the one side the devs are asking for a payment, on the other side they don't offer you a way to donate. Clever ...

**Comment by ncw** [comment] 2024-02-27 23:03
This feature is planned for 1.67. we have a sponsor for the work!

**Comment by venomone** [comment] 2024-02-28 12:31
Can't wait for it :D 👯 👍 👍 👍

**Comment by erickyun** [comment] 2024-02-28 18:27
> This feature is planned for 1.67. we have a sponsor for the work!

+1 👍👍👍🤞🙏

**Comment by lostb1t** [comment] 2024-05-30 09:32
@ncw is there an pr/branch where we can follow progress on this

**Comment by professornope** [comment] 2024-06-14 18:04
1.67 just released...

Unless I'm blind I don't see any changes for this in the changelog...

**Comment by xd003** [comment] 2024-06-14 18:11
> 1.67 just released...
> 
> Unless I'm blind I don't see any changes for this in the changelog...

Yeah was wondering the same, can't see any change related to this

**Comment by ncw** [comment] 2024-06-24 08:39
This feature didn't get released for 1.67 - it is still in testing.

If you want to give it a try, then use the latest beta from here

https://beta.rclone.org/branch/fix-multithread-chunker/

And experiment with the --vfs-read-chunk-streams parameter

**Comment by hacktek** [comment] 2024-07-15 21:50
I have the same issue described by Paul above: a fat pipe at home, but really bad latency of close to 200 ms from a remote server. I just deployed the 1.68 beta branch specifically for the webdav mount that I was having issues with and set `--vfs-read-chunk-streams` to 10. Throughput is very much improved now (8-10x faster), so far not adverse behaviors judging from the logs. THANK YOU.

For reference, this is the mount command I'm using:

`/usr/bin/rclone-chunker mount --allow-other --cache-dir=/home/hacktek/.cache --config=/home/hacktek/.config/rclone/rclone.conf --copy-links --dir-cache-time=6000h --buffer-size 32M --rc --rc-addr=localhost:5573 --rc-no-auth --syslog --umask=002 --user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 --vfs-cache-min-free-space=off --vfs-cache-max-age=504h --vfs-cache-max-size=400G --vfs-cache-mode=full --vfs-fast-fingerprint --vfs-read-ahead=1G --vfs-read-chunk-streams=10 --poll-interval 0 --vfs-read-chunk-size=2M --vfs-read-chunk-size-limit=8M --contimeout=5s --timeout=120s -v offsite_dav: /mnt/remote/offsite_dav`

**Comment by ncw** [comment] 2024-07-19 09:31
@hacktek thank you very much for testing the code

> reading the code, it seems that when using this functionality, `vfs-read-chunk-size-limit` does not have any effect

That is correct

> and rclone will ignore the limit and simply create `vfs-read-chunk-streams` requests of `vfs-read-chunk-size`, so in my example above, it will download 2MB chunks and not 8MB chunks. Is that accurate?

Yes

> So in my case where I want to use a majority of 8MB chunks, I should just remove `vfs-read-chunk-size-limit` and set `vfs-read-chunk-size` to 8MB instead?

That sounds correct.

I'm very interested in any performance numbers you can come up with as I haven't decided what the defaults should be yet.

**Comment by hacktek** [comment] 2024-07-22 19:59
I haven't validated these numbers, they're mostly taken by eye while testing using vnstat. I've since changed my settings a bit and reduced `vfs-read-ahead` to 512M (from 1G) and `vfs-read-chunk-streams` to 5 (from 10). I have not noticed any adverse effects and may lower these further (especially read-ahead).

I can say that, since I started using this, performance is better by leaps and bounds. This is a hosted video solution pulling files from a remote NAS 200 ms away. Streams (being pulled in single chunks) would often drop in performance to single digit Mbps. I tried playing with the chunk sizes and limits but that didn't help. Performance when pulling a single video could easily drop to 2 Mbps or below, making the video buffer to a level where it became unwatchable (and these aren't high bitrate videos to begin with, most are 4-6 Mbps). Lowering the chunk size helped a bit, as well as implementing lower connection and read timeouts, but in situations when performance dropped and bytes still flowed, the read timeout didn't do anything. Finishing a chunk also did not guarantee that the next chunk would see good performance.

After making this change, I see traffic averaging about 30-50 Mbps, much better than 2 Mbps for sure. I haven't experienced any buffering and have verified that the server side buffer fills up in its entirety (meaning entire video buffered) at about 2 to 4 times faster than the playback speed. 

After you confirmed that `vfs-read-chunk-size-limit` doesn't have any effect, I re-evaluated the need for bigger chunks and decided against it. I think it makes more sense in a solution like this to fail quickly and having larger chunks simply increases the likelihood that bytes will pass through the wire and invalidate a possible timeout that could force a retry.

**Comment by ncw** [comment] 2024-07-30 14:04
@hacktek thank you for writing that up - very useful. To answer your question, the webdav mount is pretty high performance. It has its quirks but low throughput isn't one of them!

**Comment by ncw** [comment] 2024-07-30 15:53
If you can stream from `rclone serve webdav` then I'd prefer that over `rclone mount` as it will make less trips in and out of the kernel to the FUSE code.

**Comment by lapastillaroja** [comment] 2024-08-13 01:29
I have a similar situation like the one described by @hacktek in https://github.com/rclone/rclone/issues/4760#issuecomment-2229499199

Using the latest beta mentioned above and also @hacktek settings `rclone server webdav` is able to pull from the remote between 100 and 200 Mbps (around 20x faster than before). However, it takes too much time for file to be "available" (since the download starts until the data starts to flow at a steady speed can take more than 2 minutes).
I assume that's because the chunks are too big and takes too much time to be available because of the high latency to the remote.

After some tests I found that by reducing the chunk size and increasing considerably the number of streams the download starts much faster. Below configs give me steady 30 Mbps download.

```
    /usr/bin/rclone-mt serve webdav \
        remote-samba:/ \
        --addr :8081 \
        --htpasswd=/root/.config/webdav/htpasswd \
        --cache-dir=/mnt/cache/remote-samba \
        --dir-cache-time=2000h \
        --vfs-cache-mode=full \
        --vfs-cache-max-size=400G \
        --vfs-cache-max-age=2000h \
        --vfs-read-chunk-streams=40 \
        --vfs-read-chunk-size=3M \
        --buffer-size=8M
```

Ideally I would like to be able to download at around 70~90 Mbps with the download starting no longer than 15 seconds but I wasn't able to find a better set of configs.

I understand there are limits of what can be done because of my environment constraints. Btw, the ping to my remote server is around 270ms and it's a samba remote.

**Closed** 2024-08-14 20:13 UTC
Labels: enhancement, VFS / mount, IMPORTANT

**Comment by ncw** [comment] 2024-08-14 20:15
Thank you @lapastillaroja @hacktek and everyone else for testing this code.

I've decided it works well enough to merge so I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.68

If you find any bugs, please make a new issue - thank you :-)

**Comment by hacktek** [comment] 2024-09-19 22:42
> I have a similar situation like the one described by @hacktek in [#4760 (comment)](https://github.com/rclone/rclone/issues/4760#issuecomment-2229499199)
> 
> Using the latest beta mentioned above and also @hacktek settings `rclone server webdav` is able to pull from the remote between 100 and 200 Mbps (around 20x faster than before). However, it takes too much time for file to be "available" (since the download starts until the data starts to flow at a steady speed can take more than 2 minutes). I assume that's because the chunks are too big and takes too much time to be available because of the high latency to the remote.
> 
> After some tests I found that by reducing the chunk size and increasing considerably the number of streams the download starts much faster. Below configs give me steady 30 Mbps download.
> 
> ```
>     /usr/bin/rclone-mt serve webdav \
>         remote-samba:/ \
>         --addr :8081 \
>         --htpasswd=/root/.config/webdav/htpasswd \
>         --cache-dir=/mnt/cache/remote-samba \
>         --dir-cache-time=2000h \
>         --vfs-cache-mode=full \
>         --vfs-cache-max-size=400G \
>         --vfs-cache-max-age=2000h \
>         --vfs-read-chunk-streams=40 \
>         --vfs-read-chunk-size=3M \
>         --buffer-size=8M
> ```
> 
> Ideally I would like to be able to download at around 70~90 Mbps with the download starting no longer than 15 seconds but I wasn't able to find a better set of configs.
> 
> I understand there are limits of what can be done because of my environment constraints. Btw, the ping to my remote server is around 270ms and it's a samba remote.

This might be due to using the samba remote, I don't have any experience with that one. I think our use cases are slightly different though...

I do `rclone serve webdav` of a folder, then `rclone mount` that remotely. On this remote mount is where I use the chunked streams.

Maybe the SMB protocol doesn't cope as well with multiple parallel streams vs a folder in the local filesystem. But also, is that SMB share over the internet? I think SMB/NFS perform quite poorly over the internet, they expect really low latency to work in the first place.

**Comment by aniel300** [comment] 2024-09-23 01:56
has anybody gotten this work, i can't get it to work.

**Comment by darthShadow** [comment] 2024-09-23 09:27
Please stop bumping closed issues. If you are facing any issues, please open a new thread at the forums: https://forum.rclone.org/
