### ISSUE TITLE
OneDrive special character treatment (%): possible url escaping bug

### ISSUE THREAD

**Issue by hsai1020** [rclone/rclone#5127] opened 2021-03-14 20:47 UTC
I'm copying this from the forum question following @ncw's response:
https://forum.rclone.org/t/onedrive-special-character-treatment/22808

#### What is the problem you are having with rclone?
In rclone copy, when the file name and/or folder name contains the character % followed by something that can be considered a hex digit (for example, %e3), the results of the copy are different from what is expected.

When the file contains the %?? string, the corresponding uploaded filename has a converted string.
For example, if we have "test%e3%46232.txt", the final name is "testï¿½F232.txt" where ï¿½ probably corresponds to the character ã and the %46 recognized as the character F:

https://grox.net/utils/encoding.html

If the rclone copy is used on a specified file (instead of a folder to folder copy), then the --onedrive-no-versions switch behaves as expected, generationg no new versions and just performing checks upon repeated commands.

If the rclone copy is used on a folder that contains the file with the %?? string in the filename, the checker does not recognize the identical file and overwrites, creating a new version. When rclone cleanup is performed on the specific file (with the source file name), the removal of previous versions works as intended.

If the rclone copy is used on a folder with a folder name containing the %?? string, the folder is not created in the destination, and the files within the source folder is copied to the destination folder, effectively shifting the directory tree up by one.

Most likely this is an effect of the change in 1.54.0 that allowed the use of % and # in OneDrive encoding. I have not extensively checked the other combinations, but use of # in filename looked ok. My guess is that %?? where the ?? can be treated as hex is a special case?

Thank you for your help!

#### What is your rclone version (output from `rclone version`)
rclone v1.54.0

os/arch: windows/amd64
go version: go1.15.7
(I also tested with 1.54.1 as well as 1.55.0-beta.5270 and can confirm the same results)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 7 or Windows 10, 64 bit, Shell used is Command Prompt.

####  Which cloud storage system are you using? (e.g. Google Drive)
Microsoft OneDrive for Business / SharePoint

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone copy "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap -u

rclone copy "<redacted>\test" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap -u
```
(in the second example, "test%e3%46232.txt" was moved into a folder called "test".)

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
C:\usr\Programs\rclone>rclone copy "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" --onedrive-no-versions -vv
2021/03/13 02:51:16 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv"]
2021/03/13 02:51:16 DEBUG : Creating backend with remote "<redacted>\test%e3%46232.txt"
2021/03/13 02:51:16 DEBUG : Using config file from "<redacted>"
2021/03/13 02:51:16 DEBUG : fs cache: adding new entry for parent of "<redacted>\test%e3%46232.txt", "<redacted>"
2021/03/13 02:51:16 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:51:17 DEBUG : test%e3%46232.txt: Need to transfer - File not found at Destination
2021/03/13 02:51:17 DEBUG : test%e3%46232.txt: Starting multipart upload
2021/03/13 02:51:17 DEBUG : test%e3%46232.txt: Uploading segment 0/4 size 4
2021/03/13 02:51:18 DEBUG : test%e3%46232.txt: QuickXorHash = 7428c31ce8000000000000000400000000000000 OK
2021/03/13 02:51:18 INFO  : test%e3%46232.txt: Copied (new)
2021/03/13 02:51:18 INFO  :
Transferred:             4 / 4 Bytes, 100%, 3 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         2.3s

2021/03/13 02:51:18 DEBUG : 6 go routines active

C:\usr\Programs\rclone>rclone copy "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" --onedrive-no-versions -vv
2021/03/13 02:51:19 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv"]
2021/03/13 02:51:19 DEBUG : Creating backend with remote "<redacted>\test%e3%46232.txt"
2021/03/13 02:51:19 DEBUG : Using config file from "<redacted>"
2021/03/13 02:51:19 DEBUG : fs cache: adding new entry for parent of "<redacted>\test%e3%46232.txt", "<redacted>"
2021/03/13 02:51:19 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:51:20 DEBUG : test%e3%46232.txt: Size and modification time the same (differ by -505.1033ms, within tolerance 1s)
2021/03/13 02:51:20 DEBUG : test%e3%46232.txt: Unchanged skipping
2021/03/13 02:51:20 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.9s

2021/03/13 02:51:20 DEBUG : 3 go routines active

C:\usr\Programs\rclone>rclone copy "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap
2021/03/13 02:56:51 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test%e3%46232.txt" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv" "--ignore-size" "--ignore-checksum" "--fast-list" "--use-mmap"]
2021/03/13 02:56:51 DEBUG : Creating backend with remote "<redacted>\test%e3%46232.txt"
2021/03/13 02:56:51 DEBUG : Using config file from "<redacted>"
2021/03/13 02:56:51 DEBUG : fs cache: adding new entry for parent of "<redacted>\test%e3%46232.txt", "<redacted>"
2021/03/13 02:56:51 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:56:52 DEBUG : test%e3%46232.txt: Size and modification time the same (differ by -505.1033ms, within tolerance 1s)
2021/03/13 02:56:52 DEBUG : test%e3%46232.txt: Unchanged skipping
2021/03/13 02:56:52 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.9s

2021/03/13 02:56:52 DEBUG : 3 go routines active

C:\usr\Programs\rclone>rclone copy "<redacted>\test%e3" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap -u
2021/03/13 02:58:31 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test%e3" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv" "--ignore-size" "--ignore-checksum" "--fast-list" "--use-mmap" "-u"]
2021/03/13 02:58:31 DEBUG : Creating backend with remote "<redacted>\test%e3"
2021/03/13 02:58:31 DEBUG : Using config file from "<redacted>"
2021/03/13 02:58:31 DEBUG : fs cache: renaming cache item "<redacted>\test%e3" to be canonical "<redacted>/test%e3"
2021/03/13 02:58:31 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:58:32 DEBUG : One drive root 'Collaborations': Waiting for checks to finish
2021/03/13 02:58:32 DEBUG : One drive root 'Collaborations': Waiting for transfers to finish
2021/03/13 02:58:32 DEBUG : test%e3%46232.txt: Starting multipart upload
2021/03/13 02:58:32 DEBUG : test%e3%46232.txt: Uploading segment 0/4 size 4
2021/03/13 02:58:33 INFO  : test%e3%46232.txt: Copied (new)
2021/03/13 02:58:33 INFO  :
Transferred:             4 / 4 Bytes, 100%, 3 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.9s

2021/03/13 02:58:33 DEBUG : 6 go routines active

C:\usr\Programs\rclone>rclone copy "<redacted>\test%e3" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap -u
2021/03/13 02:58:35 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test%e3" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv" "--ignore-size" "--ignore-checksum" "--fast-list" "--use-mmap" "-u"]
2021/03/13 02:58:35 DEBUG : Creating backend with remote "<redacted>\test%e3"
2021/03/13 02:58:35 DEBUG : Using config file from "<redacted>"
2021/03/13 02:58:35 DEBUG : fs cache: renaming cache item "<redacted>\test%e3" to be canonical "<redacted>/test%e3"
2021/03/13 02:58:35 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:58:35 DEBUG : One drive root 'Collaborations': Waiting for checks to finish
2021/03/13 02:58:35 DEBUG : One drive root 'Collaborations': Waiting for transfers to finish
2021/03/13 02:58:35 DEBUG : test%e3%46232.txt: Starting multipart upload
2021/03/13 02:58:36 DEBUG : test%e3%46232.txt: Uploading segment 0/4 size 4
2021/03/13 02:58:36 INFO  : test%e3%46232.txt: Copied (new)
2021/03/13 02:58:36 INFO  :
Transferred:             4 / 4 Bytes, 100%, 3 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.8s

2021/03/13 02:58:36 DEBUG : 6 go routines active

C:\usr\Programs\rclone>rclone copy "<redacted>\test" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap -u
2021/03/13 02:59:00 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv" "--ignore-size" "--ignore-checksum" "--fast-list" "--use-mmap" "-u"]
2021/03/13 02:59:00 DEBUG : Creating backend with remote "<redacted>\test"
2021/03/13 02:59:00 DEBUG : Using config file from "<redacted>"
2021/03/13 02:59:00 DEBUG : fs cache: renaming cache item "<redacted>\test" to be canonical "<redacted>/test"
2021/03/13 02:59:00 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:59:01 DEBUG : One drive root 'Collaborations': Waiting for checks to finish
2021/03/13 02:59:01 DEBUG : One drive root 'Collaborations': Waiting for transfers to finish
2021/03/13 02:59:01 DEBUG : test%e3%46232.txt: Starting multipart upload
2021/03/13 02:59:01 DEBUG : test%e3%46232.txt: Uploading segment 0/4 size 4
2021/03/13 02:59:02 INFO  : test%e3%46232.txt: Copied (new)
2021/03/13 02:59:02 INFO  :
Transferred:             4 / 4 Bytes, 100%, 3 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         2.0s

2021/03/13 02:59:02 DEBUG : 6 go routines active

C:\usr\Programs\rclone>rclone copy "<redacted>\test" "sharepoint:Collaborations" --onedrive-no-versions -vv --ignore-size --ignore-checksum --fast-list --use-mmap -u
2021/03/13 02:59:03 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "copy" "<redacted>\test" "sharepoint:Collaborations" "--onedrive-no-versions" "-vv" "--ignore-size" "--ignore-checksum" "--fast-list" "--use-mmap" "-u"]
2021/03/13 02:59:03 DEBUG : Creating backend with remote "<redacted>\test"
2021/03/13 02:59:03 DEBUG : Using config file from "<redacted>"
2021/03/13 02:59:03 DEBUG : fs cache: renaming cache item "<redacted>\test" to be canonical "<redacted>/test"
2021/03/13 02:59:03 DEBUG : Creating backend with remote "sharepoint:Collaborations"
2021/03/13 02:59:04 DEBUG : One drive root 'Collaborations': Waiting for checks to finish
2021/03/13 02:59:04 DEBUG : One drive root 'Collaborations': Waiting for transfers to finish
2021/03/13 02:59:04 DEBUG : test%e3%46232.txt: Starting multipart upload
2021/03/13 02:59:04 DEBUG : test%e3%46232.txt: Uploading segment 0/4 size 4
2021/03/13 02:59:05 INFO  : test%e3%46232.txt: Copied (new)
2021/03/13 02:59:05 INFO  :
Transferred:             4 / 4 Bytes, 100%, 3 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.8s

2021/03/13 02:59:05 DEBUG : 6 go routines active
```
This output created a file "testï¿½F232.txt" and when I tried creating a folder called "test%46", it did not create a folder called "testF" but rather copied the contents of it into the folder called "Collaborations" in the destination.

**Comment by ncw** [comment] 2021-03-15 10:33
I tried to reproduce this in the simplest possible way

    rclone mkdir onedrive:issue-5127
    rclone touch -vv --dump bodies onedrive:issue-5127/test%46.txt
    rclone lsf onedrive:issue-5127/

Gives

    testF.txt

The PUT request uploading the file looks like this

```
2021/03/15 09:56:18 DEBUG : HTTP REQUEST (req 0xc0005c7000)
2021/03/15 09:56:18 DEBUG : PUT /v1.0/drives/71a96798e7b1d253/items/71A96798E7B1D253!534417:/test%2546.txt:/content HTTP/1.1
Host: graph.microsoft.com
User-Agent: rclone/v1.55.0-DEV
Content-Length: 0
Authorization: XXXX
Accept-Encoding: gzip

2021/03/15 09:56:18 DEBUG : HTTP RESPONSE (req 0xc0005c7000)
2021/03/15 09:56:18 DEBUG : HTTP/1.1 201 Created
Transfer-Encoding: chunked
Cache-Control: no-store
Client-Request-Id: 1d4b35cf-d807-459b-8148-cd2dd0476730
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Date: Mon, 15 Mar 2021 09:56:18 GMT
Location: https://df.s2s-api.onedrive.com/v1.0/drives('71a96798e7b1d253')/items('71A96798E7B1D253!534418')
Odata-Version: 4.0
Request-Id: 1d4b35cf-d807-459b-8148-cd2dd0476730
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"4","ScaleUnit":"003","RoleInstance":"LO2PEPF0000006F"}}

61c
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('71a96798e7b1d253')/items/$entity","@microsoft.graph.downloadUrl":"https://vfqrqa.am.files.1drv.com/y4pA-pc_TibJ4uGA-fGEv4zzI2mEDBLo8H2nRfoDIJ0Ch47BuJsOAHrLZ24gdt2RIpetFRiecBeGWt88R4cORy_QYoRGVL1DOR6x3NkOfBNAv7zDcIFVUOfloZUNYtYX1nnzlL170YqUvz-feVPPMljME-pf4gMAvaNaiCEM3_vMjHKC5WXDDw4thsH-u2x7mcvDEkkqEqDL01nFMrk8tLw7zBToQzfn_Qr-gD4xn3m9n21LM7Zn1W5R8dhbZQTRetOeHnNaFo8Pqfbljx0-1yYnV7hOqCiZt93qf7sdqnPZMw","createdDateTime":"2021-03-15T09:56:18.76Z","cTag":"aYzo3MUE5Njc5OEU3QjFEMjUzITUzNDQxOC4yNTc","eTag":"aNzFBOTY3OThFN0IxRDI1MyE1MzQ0MTguMA","id":"71A96798E7B1D253!534418","lastModifiedDateTime":"2021-03-15T09:56:18.76Z","name":"testF.txt","size":0,"webUrl":"https://1drv.ms/t/s!AFPSseeYZ6lxoM8S","reactions":{"commentCount":0},"createdBy":{"application":{"displayName":"rclone","id":"48211038"},"user":{"displayName":"Nick Craig-Wood","id":"71a96798e7b1d253"}},"lastModifiedBy":{"application":{"displayName":"rclone","id":"48211038"},"user":{"displayName":"Nick Craig-Wood","id":"71a96798e7b1d253"}},"parentReference":{"driveId":"71a96798e7b1d253","driveType":"personal","id":"71A96798E7B1D253!534417","name":"issue-5127","path":"/drive/root:/issue-5127"},"file":{"mimeType":"text/plain","hashes":{"quickXorHash":"AAAAAAAAAAAAAAAAAAAAAAAAAAA=","sha1Hash":"DA39A3EE5E6B4B0D3255BFEF95601890AFD80709","sha256Hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"}},"fileSystemInfo":{"createdDateTime":"2021-03-15T09:56:18.76Z","lastModifiedDateTime":"2021-03-15T09:56:18.76Z"}}
0
```

You can see that rclone correctlyURL escaped the file name as `test%2546.txt:` however the name in the JSON return was returned as `"name":"testF.txt"`

The web interface agrees that that is the name.

![image](https://user-images.githubusercontent.com/536803/111136332-85f49a80-8575-11eb-9af8-d10709885b42.png)

Uploading a file `webui%46.txt` via the web interface does work

![image](https://user-images.githubusercontent.com/536803/111136747-f6032080-8575-11eb-996b-cc27c9fe57c0.png)

The webui uses a different interface to upload - namely `https://api.onedrive.com/rup/` which isn't documented in the onedrive API docs.

So I think this is very likely a onedrive bug

I've reported this upstream here: https://github.com/OneDrive/onedrive-api-docs/issues/1455

**Comment by ncw** [comment] 2021-04-06 09:24
This is now fixed in onedrive.

My tests work find now - how about yours @hsai1020 ?

**Comment by ivandeex** [comment] 2021-11-05 15:45
Closed after 7 months of NOTHING

**Closed by ivandeex** 2021-11-05 15:45 UTC
Labels: bug, Remote: One Drive
