### ISSUE TITLE
Incomplete json data returned when i try to login the "Azure and Office 365 operated by 21Vianet in China" on remote machine mode

### ISSUE THREAD

**Issue by crmmc** [rclone/rclone#5938] opened 2022-01-22 05:40 UTC
when i using rclone's "Azure and Office 365 operated by 21Vianet in China"  login onedrive function, I don't have any problem with my windows 10 local login, but on my ubuntu 20.04 Server with rcloneV1.57.0 login, I need to get tocken after login on remote machine, I tried many times on my I tried several times to log in on my windows to get the tocken, but the format obtained is very strange, there may be a bug in the output tocken component, I redacted the privacy information in my logs, but kept the information of the last output in that strange format for researchers to refer to
I tried to log in directly using the browser on windows 10, and then went to the rclone configuration file to copy the tocken parameters in json format and paste them into the remote machine and successfully logged in

my rclone v1.57.0 log:
===============================start==================================================

D:\Downloads\rclone-v1.57.0-windows-amd64>rclone authorize "onedrive" "DELETED" -vv
2022/01/22 13:29:44 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "authorize" "onedrive" "DELETED" "-vv"]
2022/01/22 13:29:44 DEBUG : **temp-fs**: config in: state="", result=""
2022/01/22 13:29:44 DEBUG : OAuth only is set - overriding return state
2022/01/22 13:29:44 DEBUG : **temp-fs**: config out: out=&{State:*oauth,,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2022/01/22 13:29:44 DEBUG : **temp-fs**: config in: state="*oauth,,,", result=""
2022/01/22 13:29:44 DEBUG : Using config file from "C:\\Users\\[DELETED]\\AppData\\Roaming\\rclone\\rclone.conf"
2022/01/22 13:29:44 DEBUG : **temp-fs**: config out: out=&{State:*oauth-confirm,,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2022/01/22 13:29:44 DEBUG : **temp-fs**: config in: state="*oauth-confirm,,,", result=""
2022/01/22 13:29:44 DEBUG : Auto confirm is set, choosing default "true" for state "*oauth-islocal,,,", override by setting config parameter "config_is_local"
2022/01/22 13:29:44 DEBUG : **temp-fs**: config out: out=&{State:*oauth-islocal,,, Option:<nil> OAuth:<nil> Error: Result:true}, err=<nil>
2022/01/22 13:29:44 DEBUG : **temp-fs**: config in: state="*oauth-islocal,,,", result="true"
2022/01/22 13:29:44 DEBUG : **temp-fs**: config out: out=&{State:*oauth-do,,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2022/01/22 13:29:44 DEBUG : **temp-fs**: config in: state="*oauth-do,,,", result=""
2022/01/22 13:29:44 NOTICE: Make sure your Redirect URL is set to "http://localhost:53682/" in your custom config.
2022/01/22 13:29:44 DEBUG : Starting auth server on 127.0.0.1:53682
2022/01/22 13:29:44 NOTICE: If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=[DELETED]
2022/01/22 13:29:44 NOTICE: Log in and authorize rclone for access
2022/01/22 13:29:44 NOTICE: Waiting for code...
2022/01/22 13:29:44 DEBUG : Redirecting browser to: https://login.chinacloudapi.cn/common/oauth2/v2.0/authorize?access_type=offline&client_id=[DELETED]&redirect_uri=[DELETED]&response_type=code&scope=Files.Read+Files.ReadWrite+Files.Read.All+Files.ReadWrite.All+offline_access+Sites.Read.All&state=[DELETED]
2022/01/22 13:29:45 DEBUG : Received GET request on auth server to "/"
2022/01/22 13:29:45 NOTICE: Got code
2022/01/22 13:29:45 DEBUG : Closing auth server
2022/01/22 13:29:45 DEBUG : Closed auth server with error: accept tcp 127.0.0.1:53682: use of closed network connection
2022/01/22 13:29:46 DEBUG : **temp-fs**: Saved new token in config file
2022/01/22 13:29:46 DEBUG : **temp-fs**: config out: out=&{State:*oauth-done,,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2022/01/22 13:29:46 DEBUG : **temp-fs**: config in: state="*oauth-done,,,", result=""
2022/01/22 13:29:46 DEBUG : **temp-fs**: config out: out=&{State: Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
Paste the following into your remote machine --->
eyJ0b2tlbiI6IntcImFjY2Vzc190b2tlblwiOlwiZXlKMGVYQWlPaUpLVjFRaUxDSnViMjVqWlNJNklrUk1VFUUyWldaQlIydDRjekV4WTFaU01ISlpTM2hrUWtSamJHZHhhSEp5Wm14UFpXcFZhM2xLY1VraUxDSmhiR2NpT2lKU1V6STFOaUlzSW5nMWRDSTZJbDlEU2tGUGRIbHpXVlp0Tlhoak1WbHZTekJ2VVRkeGVVSkRVU0lzSW10cFpDSTZJbDlEU2tGUGRIbHpXVlp0Tlhoak1WbHZTekJ2VVRkeGVVSkRVU0o5LmV5SmhkV1FpT2lJd01EQXdNREF3TXkwd01EQXdMVEF3TURBdFl6QXdNQzB3TURBd01EQXdNREF3TURBaUxDSnBjM01pT2lKb2RIUndjem92TDNOMGN5NWphR2x1WVdOc2IzVmtZWEJwTG1OdUx6RXpaakZoTURWa0xUWTFOamN0TkRnNVpDMDVPV1l5TFRabE5HUmhOakE1TlRZMk55OGlMQ0pwWVhRaU9qRTJOREk0TWprd09EY3NJbTVpWmlJNk1UWTBNamd5T1RBNE55d2laWGh3SWpveE5qUXlPRE15T1RnM0xDSmhZM0lpT2lJeElpd2lZV2x2SWpvaVFWTlJRVEl2T0V0QlFVRkJRbFJJWm1SMVQwSXpja2xCTDNkR2FUaGlUR292V1ZCTWFWTkRMMjgxSzBaRFpFUURhak5JU2pkSVp6MGlMQ0poYlhJaU9sc2ljSGRrSWwwc0ltRndjRjlrYVhOd2JHRjVibUZ0WlNJNklrZHZiMlJOWVc0aUxDSmhjSEJwWkNJNklqUm1PRGszWldZMUxUSTJNMlV0TkRjNE5TMDVPV1prTFRjeE16QXdZMkU0WkRBd1lpSXNJbUZ3Y0dsa1lXTnlJam9pTVNJc0ltWmhiV2xzZVY5dVlXMWxJam9pNlptSUlpd2laMmwyWlc1ZmJtRnRaU0k2SXVtVWtPbVRyU0lzSW1sd1lXUmtjaUk2SWpJeU15NDNNeTR5TVRndU1UZzBJaXdpYm1GdFpTSTZJdW1aaU9tVWtPbVRyU0lzSW05cFpDSTZJamN6T0Roa01UWTVMVGcxT0dVdE5EZGhZUzA1TW1RMkxUaGpPV0psWWpRek0ySmpPU0lzSW05dWNISmxiVjl6YVdRaU9pSlRMVEV0TlMweU1TMHpOamcyTkRVM01UVTNMVE01TURVNU5EZzNNVGd0TXpBME16TTFOVE0zTXkwMk56TXlNeUlzSW5Cc1lYUm1Jam9pTXlJc0luQjFhV1FpT2lJeE1EQXpNekl6TUVNMVJqSkVPVEkwSWl3aWNtZ2lPaUl3TGtGQlFVRllFUUI0UlRKa2JHNVZhVm80YlRWT2NHZHNWMXBmVmkxcFZUZ3RTbTlXU0cxbU1YaE5RWGx2TUVGelFrRkVUUzRpTENKelkzQWlPaUpHYVd4bGN5NVNaV0ZrSUVacGJHVnpMbEpsWVdRdVFXeHNJRVpwYkdWekxsSmxZV1JYY21sMFpTQkdhV3hsY3k1U1pXRmtWM0pwZEdVdVFXeHNJRk5wZEdWekxsSmxZV1F1UVd4c0lIQnliMlpwYkdVZ2IzQmxibWxrSUdWdFlXbHNJaXdpYzJsbmJtbHVYM04wWVhSbElqcGJJbXR0YzJraVhTd2ljM1ZpSWpvaWNUQmFSbWR0YzBOR09EaFBUREZSUVVORVdGUjZSREoxVW1nMk5ETTBTRkpJUTNOdlQycDFORTVxUlNJc0luUnBaQ0k2SWpFelpqRmhNRFZrTFRZMU5qY3RORGc1WkMwNU9XWXlMVFpsTkdSaE5qQTVOVFkyTnlJc0luVnVhWEYxWlY5dVlXMWxJam9pTWpGeWJXTm9aVzVBYzNSMUxtVmtkUzVqYmlJc0luVndiaUk2SWpJeGNtMWphR1Z1UUhOMGRTNWxaSFV1WTI0aUxDSjFkR2tpT2lKT01XcHROWEpqZERJd1UzaE1PWFJKT1ZsdlQwSlJJaXdpZG1WeUlqb2lNUzR3SWl3aWQybGtjeUk2V3lKaU56bG1ZbVkwWkMwelpXWTVMVFEyT0RrdE9ERTBNeTAzTm1JeE9UUmxPRFUxTURraVhTd2llRzF6WDNOMElqcDdJbk4xWWlJNklsaG5TMFl5UzBoc1lUSlVNMjlrVlVGUU5FY3hSbGd5TTE5cGJ6Z3dTM3BQVjNKM05FbFUFUFUFUFUNaWZTd2llRzF6WDNSalpIUWlPakUwTXpNME9UWTNNRGw5LktheGlwdDNscDkySzNZR2oweG5DbzhKZUVmdElmVG5UcFlZclpzOVhKclFRS0FqWXBHZDVKVmpSeGtYM3dJdjJ2cDFiYUxtbFUkbXp2enRvYUZJUUQ5c2VrOFNLVkRfeUFOT3BuUURHQklBRzNfczBmYVJNQjJhSkdyY1UwdVljSzliUjJmalVQLTVpWWxtQUNGcHN6M3dib2cwMGZSMEl5TFU0Mkdwa1haVGcxNjBQTjVvSUxVZExTVlFlaU1BeE42aGxXUVc2T0RlS2RuNktvV1l3ZUtjeEtqblFSSHhoQVFja3VfNkVOUkl1ckFFUXRjZTVJaWVwOUltUHhFYjJiT2lqWmFrcTRFamZKb0pLLXBUeUdfU0I5MlhXR0plV1FyUGZKdURiZkpCakRfRnQ1UC1rRTRSa2haVmtxY0s2cGZ4NHROenJENzFOaXdwUWE4QmJDUVwiLFwidG9rZW5fdHlwZVwiOlwiQmVhcmVyXCIsXCJyZWZyZXNoX3Rva2VuXCI6XCIwLkFBQUFYYUR4RTJkbG5VaVo4bTVOcGdsV1pfVi1pVTgtSm9WSG1mMXhNQXlvMEFzQkFETS5BZ0FCQUFBQUFBREY4dWhiZHFNS1RxcnJGdG95RGhtWUF3RHNfd1FBOF9fUG9KaGEyWDVNV2pKLXpmb3dUOThMUlhYWmZoN1NyaXlUejNINWc0N3FLUTdFenpydnhoFUFUU0N5WngwVG9fMGZINS0wXzdPN3JLNGxxVUwxVzJ6VjVMS0RsdjctaVRCOWN2RTdSN1h2ODczX0JQT2gyaFFNWmR1U3BVby1idFh5STlDWk1ydlNSdlRiTURXc1ZnYmJma2lDRzRzQmFJN0lndzlta29lUlBxR3pUTHMtbjQzcjJfMkZFU2JkYmxHdVVDSmk4Q0tZYWczdXlBQkR6ZWt6WG1LVkJSTGRZNHpnRk5oSlJnYkk2TkdycldsdENUdjdkMUt1VWhlRG5IOFJjZldZRDRXN0xtTUtwVDhmSk9rSnhoUWJfUVRwUndvNERxdHRUVTY0S0dqd2dlbVRkLXdqMzNGd0FiejFsTUZLS09kbURjRDF6VnpKbTd1UGZ6czhjVVI3WGhmb29DS2dBa2pWTVRvMjAzZE9kelRHVDJHLWFzWnVHUlU4dmpaYTRvUTEwM1hKRmFmN0RKb3dSbW1ia1pTdVprS1A0bXE5aC1YTng2ZmZGUTVBS0RPRTRTT0Z4cGxuVUgtaFdiTE5SSkdjekZOQXQtVktIdkkzVTZ0Um05OW40U05odHI4amk3aXpEc3RnbVY5dF91dmFWY19GYnNtNmRxVEwyc2kwMkw5WHFLWlBrWFd5N2RGYzNqdEVwcURPR2NnX2hUT0RndXR1c01fZUV3dU9CX1VKQ1J2VU9tNDl1dzA3dXl0X1dIUFM0Z0hyNW5PYUdyd3ZNdUg4VHRyQzNpbGotUmRwVVIyQjhzZHBEQl9JeWVHVHRkY0RqOEEzLVg0em9tdE5OUTFjWHZ3ZXZ3VjI3UXlITjZMVmRIX29CWmFOTjJwX21mb0tqd1hnTHZvUlQ5T2tzOTE2b1g0SXk2dzQzX0E5SVNnNjBEM3MxOUlMRkFvZWJia0NZNVA5N2wwaTNTaGQ2SXdQQTA1RmhGaGhnQWtIOU11Nk5VLThla25DLVlnclJVYVljSWxnSTczMDlJdmRfbVB0TkdLaURWa0Mzal9VTTdnWVFjZVdYRDBJSzR5ekxpdUtOZFpsb21GNDB3THVPSm9xODNlZEdCRG9PQnkzM2lGRDdOUkhRN1NQc3FDLVpVRmtuQjVqXy0tbjlvZ01VWTd2ako0M3FBejFtNmdJX011bGxTdUp5T2NFX0k2UVZSTWRFaHQ2Z2szSTlBaDR2czZ6T25OZXVoOXcwd1wiLFwiZXhwaXJ5XCI6XCIyMDIyLTAxLTIyVDE0OjI5OjQ1LjAxMjEzMjcrMDg6MDBcIn0ifQ
<---End paste
2022/01/22 13:29:46 DEBUG : rclone: Version "v1.57.0" finishing with parameters ["rclone" "authorize" "onedrive" "[DELETED]" "-vv"]

================================================END==============================
Thanks!

**Comment by animosity22** [comment] 2022-01-22 12:07
Duplicate of:

https://github.com/rclone/rclone/issues/5835

Please follow that issue.

**Closed by animosity22** 2022-01-22 12:07 UTC
