### ISSUE TITLE
WebDAV attempts HTTPS on HTTP-only Configuration

### ISSUE THREAD

**Issue by optimiz** [rclone/rclone#4418] opened 2020-07-08 00:40 UTC
#### What is the problem you are having with rclone?

**rclone** attempts to connect via HTTPS on port 443 even when configured as HTTP.  This fails with a connection refused error, since this local SharePoint server is HTTP on port 80 only.  My ultimate goal is to bulk upload everything from this legacy on-premise SharePoint server to a secure cloud instance.  (**rclone** is working well for the cloud end, just not this local local end.)  I looked at the various available SSL related switches, none seemed appropriate.  Did I miss something important in the config?  Please advise, thank you.

```
$ cat /home/user/.config/rclone/rclone.conf

[localsharepoint]
type = webdav
url = http://sharepoint.example.org/
vendor = sharepoint
user = user@example.org
pass = xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.11.10
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

```
Linux unit.example.org 5.3.11-100.fc29.x86_64 #1 SMP Tue Nov 12 20:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

####  Which cloud storage system are you using? (eg Google Drive)

SharePoint via WebDAV 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`$ rclone --vfs-cache-mode writes mount localsharepoint: /home/user/localsharepoint`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2020/07/07 16:48:38 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "-vv" "--vfs-cache-mode" "writes" "mount" "localsharepoint:" "/home/user/localsharepoint"]
2020/07/07 16:48:38 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2020/07/07 16:48:39 Failed to create file system for "localsharepoint:": Error while grabbing cookies from endpoint: %v: Post https://sharepoint.example.org/_forms/default.aspx?wa=wsignin1.0: dial tcp 172.16.11.22:443: connect: connection refused
```
A newer version of rclone (v1.51.0) gives a different error…
```
2020/07/07 17:32:43 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "-vv" "--vfs-cache-mode" "writes" "mount" "localsharepoint:" "/home/user/localsharepoint"]
2020/07/07 17:32:43 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2020/07/07 17:32:43 Failed to create file system for "localsharepoint:": :  ()
```

The site itself works fine from this workstation via HTTP directly, for example, here's the **curl** server info response…

```
$ curl  --ntlm -u example.org/user -I http://sharepoint.example.org/SitePages/Home.aspx
Enter host password for user 'example.org/user':

HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Length: 98859
Content-Type: text/html; charset=utf-8
Expires: Tue, 23 Jun 2020 00:18:05 GMT
Last-Modified: Wed, 08 Jul 2020 00:18:05 GMT
Server: Microsoft-IIS/10.0
X-SharePointHealthScore: 1
X-AspNet-Version: 4.0.30319
SPRequestGuid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
request-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
X-FRAME-OPTIONS: SAMEORIGIN
SPRequestDuration: 114
SPIisLatency: 0
Set-Cookie: http%3A%2F%2Fsharepoint%2Eexample%2Eorg%2FDiscovery=WorkspaceSiteName=xxxxxxxxxxxxxxxxxxxxxx&WorkspaceSiteUrl=xxxxxxxxxxxxxxxxxxxxxxx==&WorkspaceSiteTime=xxxxxxxxxxxxxxxxxxxxxxx==; expires=Fri, 07-Aug-2020 00:18:06 GMT; path=/_vti_bin/Discovery.asmx
Persistent-Auth: true
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.4807
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Date: Wed, 08 Jul 2020 00:18:05 GMT
```

**Comment by ncw** [comment] 2020-07-08 11:53
Are you doing username / password authentication?

The normal `vendor = sharepoint` uses a magic cookie... which is the https transaction you see.

Try with `vendor = other` and see if that helps.

**Comment by optimiz** [comment] 2020-07-08 22:48
Switching to "vendor = other" does allow the connection via HTTP to complete, thank you.  However, any subsequent task results in a continuous stream of '401 Unauthorized' errors, which is weird since I'm using a domain admin account.  Rather than worry any further about what will soon be a historical footnote, I'll use PowerShell from a Windows 10 unit for this effort instead.

P.S. — To counter a future [search fiasco](https://xkcd.com/979/), this [blog post from 2017](https://christopherclementen.wordpress.com/2017/08/14/download-all-files-from-library/) contains a script that is working to recursively pull all files from this legacy SharePoint server (after executing 'Install-Module SharePointPnPPowerShell2016' of course).

**Comment by jonathanpantall** [comment] 2021-03-23 21:37
Hey @optimiz @ncw, all,
I know this ticket is closed, so I'm happy to make a new one if you'd like.

I'm experiencing the same issues as @optimiz currently. I'm trying to connect to an on-premise Sharepoint 2013 server over port 80 using Rclone's webdav connector.

Any tips on connecting Rclone to a "http://" Sharepoint 2013 instance via the webdav connector?

Also, something else interesting to note, I tried mapping the Sharepoint 2013 site as a named mapped drive in Windows 10 (X:/) and using Rclone to read from my local machine, but it's not able to read the contents of the mapped drive (although I can run a "dir" command and see the contents outside of Rclone).

Appreciate the help!

**Comment by ncw** [comment] 2021-03-24 18:00
Actually I looked at the code for the cookie magic and it has `https` hard wired in.

I changed it to use the `http` or `https` as configured so hopefully that will work.

Can you give this a go?

[v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http](https://beta.rclone.org/branch/fix-4418-webdav-sharepoint-http/v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http/) on branch [fix-4418-webdav-sharepoint-http](https://github.com/rclone/rclone/tree/fix-4418-webdav-sharepoint-http) (uploaded in 15-30 mins)

**Comment by jonathanpantall** [comment] 2021-03-25 14:11
@ncw This worked great! I'm able to connect and list on-premise SP2013 files using the new sharepoint-ntlm vendor option. Thank you so much! :)

**Comment by jonathanpantall** [comment] 2021-03-25 14:17
Just one thing to note: I'm able to use the new Rclone connector to connect to an SP2013 using http://.

However, I still wasn't able to read from a windows mapped drive that pointed to the same webdav connection (for example: X: drive mapped to the same site). 

It's probably just Windows being unique in how they map Sharepoint's HTTP:// Webdav connection. Wanted to just let you know about that, Nick. Let me know if you need any additional info from me. I know it's a rather edge-case scenario.

Thanks!

**Comment by optimiz** [comment] 2021-03-26 05:03
Thank you for resolving this issue in **rclone**.  Alternatively, last month I had one last big migration push and used the official [Microsoft SharePoint Migration Tool ](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool), which is finally (circa its October 2020 update) able to perform these functions directly from even as old as SharePoint 2010.  It took three continuous days to complete every last transfer, but it's done and those servers have been fully decommissioned. 😅

**Comment by ivandeex** [comment] 2021-03-31 13:26
@optimiz 
Please confirm that below rclone beta works for you
https://beta.rclone.org/branch/fix-4418-webdav-sharepoint-http/v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http/
If yes, Nick will promote this beta to rclone master the next release

**Comment by ivandeex** [comment] 2021-03-31 16:54
@optimiz 

> any subsequent task results in a continuous stream of '401 Unauthorized' errors, which is weird since I'm using a domain admin account.

We have recently merged #2921, which fixes `401 Unauthorized` for the `sharepoint-ntlm` webdav vendor (and maybe for others, as a byproduct). It will be released with rclone 1.55 in 2-3 days.

**Comment by ivandeex** [comment] 2021-03-31 16:59
Assigned on @optimiz as a reminder to do the test.

Assigned on @ncw as reminder to merge the branch on master.

Thanks all

**Comment by jonathanpantall** [comment] 2021-03-31 20:42
Hey @ivandeex,
Thanks for following up on this, greatly appreciated.

I can confirm that the https://beta.rclone.org/branch/fix-4418-webdav-sharepoint-http/v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http/ branch is working for my use case with the sharepoint-ntlm connector.

However, I just also confirmed that it doesn't appear to be a permissions issue in accessing a Windows 10 Sharepoint 2013 mapped drive using Rclone. I was able to perform native functions on the mapped drive as the current user outside of Rclone.

Here's the output of the verbose logs of my actions just in case that's helpful:

P:\ = the Windows 10 Sharepoint 2013 (accessed via http) mapped drive.

```
P:\reports\Documents>rclone ls -vv .
2021/03/31 15:36:00 DEBUG : Using config file from "C:\\Users\\jpantall.WEIOFFICE\\.config\\rclone\\rclone.conf"
2021/03/31 15:36:00 DEBUG : rclone: Version "v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http" starting with parameters ["rclone" "ls" "-vv" "."]
2021/03/31 15:36:00 DEBUG : Creating backend with remote "."
2021/03/31 15:36:00 DEBUG : fs cache: renaming cache item "." to be canonical "//?/P:/reports/Documents"
```
Unless there's anything you'd like me to try, I'll go ahead and open up a new ticket on the forum like you mentioned. Thanks!

**Comment by jonathanpantall** [comment] 2021-03-31 21:02
@ivandeex Interesting... I just tried to post on the Rclone forum and it's saying new users aren't allowed to post more than 2 links.

Any chance I could get your help in posting? Sorry to ask that of you. Not sure why my post is getting flagged, I only have 1 link.

------------------------------------------------------
Title: Windows 10 - Unable to Access Sharepoint Mapped Drive through HTTP
------------------------------------------------------

#### What is the problem you are having with rclone?
Windows 10 - Unable to Access Sharepoint Mapped Drive through http/2 using Rclone

#### What is your rclone version (output from `rclone version`)
rclone v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
Sharepoint 2013, hosted on-premise

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  

```
rclone ls -vv P:/
```

#### The rclone config contents with secrets removed.  

N/A as it should be bypassing config and accessing a named drive.

#### A log from the command with the `-vv` flag  

```
P:\reports\Documents>rclone ls -vv .
2021/03/31 15:36:00 DEBUG : Using config file from "C:\\Users\\myusername\\.config\\rclone\\rclone.conf"
2021/03/31 15:36:00 DEBUG : rclone: Version "v1.55.0-beta.5340.470d1c197.fix-4418-webdav-sharepoint-http" starting with parameters ["rclone" "ls" "-vv" "."]
2021/03/31 15:36:00 DEBUG : Creating backend with remote "."
2021/03/31 15:36:00 DEBUG : fs cache: renaming cache item "." to be canonical "//?/P:/reports/Documents"
```

It seems to get stuck at the fs cache section, no matter how long I allow the command to run.

I'm able to create a Rclone connector using sharepoint-ntlm and access the Sharepoint 2013 that way but am not able to through a windows mapped network drive.

I've tested native functions as the current user in the terminal on the mapped drive and confirmed I am able to copy, mkdir, etc on the mapped drive.

Thanks for your help and please reach out if you need any additional information.

**Comment by ivandeex** [comment] 2021-03-31 21:09
I'm sorry about unfriendly forum engine, but you can just submit a bug request here.
I'm sorry it wasted your time.

**Comment by jonathanpantall** [comment] 2021-03-31 21:17
No worries, I'll post it here

**Comment by optimiz** [comment] 2021-04-06 20:30
Sorry for the delay, I was on vacation.  Unfortunately I no longer have access to legacy SharePoint systems — operations wiped our last system last month…30 days after I certified its data had fully migrated to the cloud.

**Comment by ivandeex** [comment] 2021-04-06 21:59
@ncw
1st user had success using  sharepoint-ntlm vendor instead of your fix (if I get it right)
2nd user cannot reproduce the original issue anymore
We are rather stuck with this ticket
Probably we can close it
If you feel surd about your fix and decide to merge, we have two months before next release to check it out with beta.

**Comment by ncw** [comment] 2021-04-10 11:01
Thanks for your analysis @ivandeex 

I've decided to merge my fix - it worked for one user and it looks OK for me.

That will close this issue which I think is correct.

**Closed** 2021-04-10 11:00 UTC
Labels: Remote: WebDAV, enhancement, waiting for reply...
