### ISSUE TITLE
Please support fshare.vn on rclone

### ISSUE THREAD

**Issue by thinhplust** [rclone/rclone#5062] opened 2021-02-24 08:22 UTC
Hi Rclone Team and everyone,
I created this topic so that I would like the rclone team to support fshare cloud on rclone software, glad if you can support it.
https://www.fshare.vn/api-doc

**Comment by ivandeex** [comment] 2021-02-24 14:39
It's a complete duplicate of #5009 
Put your thumbs up there
Closing

**Closed by ivandeex** 2021-02-24 14:39 UTC
Labels: new backend
