### ISSUE TITLE
Jottacloud: don't create a local copy to calculate MD5 when using encryption

### ISSUE THREAD

**Issue by tikki** [rclone/rclone#2809] opened 2018-12-02 18:02 UTC
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.45
- os/arch: freebsd/amd64
- go version: go1.11.2
```

#### What problem are you are trying to solve?

When sending data to an encrypted jottacloud remote, rclone will copy the encrypted file to temp in order to calculate its md5 hash, if the file is larger than a configurable threshold.
This happens in the [readMD5 function](https://github.com/ncw/rclone/blob/master/backend/jottacloud/jottacloud.go#L967).
My problem is that some of the files I want to copy are rather large (multiple GB) and I don't have the necessary resources (neither RAM nor disk space) to create full local copies of those files. This makes it *impossible* to copy these files to jottacloud.

#### How do you think rclone should be changed to solve that?

Calculate the md5 hash without creating a copy of the file.
The file would have to be read & encrypted twice, so maybe this behavior should be configurable.

---

This problem has already been mentioned in [#2462](https://github.com/ncw/rclone/issues/2462#issuecomment-414346294), but has not been further addressed.

**Comment by ncw** [comment] 2018-12-03 12:06
Alas this is a lot harder than it appears!

Rclone uses a streamed architecture for transferring files so the backends don't get files to upload, they get file streams (an `io.Reader` in go speak).

One thing to bear in mind is that encrypting the same file twice won't get the same result (becuase of the nonce at the start of the file) so this needs to be done in the same encryption stream.

The only way this could possibly work is if
1. crypt upload streams implement `io.Seeker`
2. local upload streams implement `io.Seeker`
3. all the accounting gubbins for uploads implements `io.Seeker`

Then the jottacloud backend would be able to do a type assertion for `io.Seeker` and if found it could read the file to make the MD5, seek, then read it again.  If the `io.Seeker` wasn't available it would do what it does at the moment.

Points 2. and 3. above are reasonably easy, but point 1. is really hard.  Crypt has a file decryptor with Seek capability and that was extremely challenging to get correct.  The encryptor with seek would be equally challenging.

Providing a cut down interface `Rewind` (say) would be much easier - maybe that is the way to go.

**Comment by nakermann1973** [comment] 2018-12-12 20:47
My workaround for this is to set $TMPDIR to a location which has lots of free space (https://golang.org/pkg/os/#TempDir).  It is not the best solution, but it works for me.

**Comment by V33m** [comment] 2020-04-11 14:12
I had an unfortunate start with rclone and Jottacloud as this issue has bothered me for many hours without figuring out why I was seeing `TIMESTAMP ERROR : FILE: Failed to copy: failed to calculate MD5: write /tmp/rclone-*md5-*: no space left on device`. Especially frustrating was the part that I thought not using `-c` should solve this, as well as using `--ignore-checksum`. In addition to that, I tried to change the tmp-dir with `--cache-tmp-upload-path`. Thankfully I found this issue.

So, I highly recommend adding a bigger NOTE at https://rclone.org/jottacloud/ so people that use crypt and have limited storage space for the /tmp folder can easily spot this issue. If you ask me, this should be mentioned just below configuration with an example on how to solve this. In my case, my SD card has little space and I have multiple external drives and therefore want to set $TMPDIR to a specific folder on separate drives when I copy.

> Jottacloud supports MD5 type hashes, so you can use the --checksum flag.
> 
> Note that Jottacloud requires the MD5 hash before upload so if the source does not have an MD5 checksum then the file will be cached temporarily on disk (wherever the TMPDIR environment variable points to) before it is uploaded. Small files will be cached in memory - see the --jottacloud-md5-memory-limit flag

Speaking of MD5 support. I'm uploading files from two external drives which have some files in common which are of importance. Since I don't want any unnecessary duplication, I upload all files to the same destination folder. So, the same file at S1 and S2 should be at D1. However, setting -c flag gives `--checksum is in use but the source and destination have no hashes in common`. I receive this when I'm copying from the same source S1, as well as the other source S2 where the files have a different timestamp, but the same size. I guess this is expected as hashing the file locally will give different results? If so, new people will probably appreciate that there is a note about this as well.

Given the MD5 comparison, would it be possible to add an option to add the MD5 checksum in a file in the same folder when the files are copied and encrypted so it can be used to compare to Jottacloud MD5 later on? Let's say that I copy a file to the server once with `rclone copy test.txt crypt: -c -v` and want to save the MD5 checksum to the same folder with example test_md5sum.txt. Or with a file at the local root with all checksums (both unencrypted and encrypted) of files which have been sent to destination D1. I would therefore only need to copy the checksum-file between my sources and can easily spot mismatches between all of the locations. I guess the checksum-file could be saved to D1 as well after being encrypted and used for comparison later with content (line ) (or just size and timestamp) mismatch. It seems like a doable solution if adding metadata to crypt files (https://github.com/rclone/rclone/issues/3667) is still far away from being implemented?

**Comment by ncw** [comment] 2020-04-15 17:18
This should be fixed by - can you give it a go?

https://beta.rclone.org/branch/v1.51.0-172-gc8442705-fix-crypt-src-hash-beta/ (uploaded in 15-30 mins)

**Comment by V33m** [comment] 2020-04-16 14:04
I can confirm that the version is working perfectly! Thx :) 

@tikki, you can try the version as well and close the issue if it's working for you too.

**Comment by tikki** [comment] 2020-04-17 15:28
Yes! I only did a quick test with a single large file, but as far as I can tell it didn't copy it to RAM or disk anymore. It took about two minutes of maxing out the CPU before the actual upload started, but other than that everything went smoothly.
Really great, thanks a lot!

Does that mean the `RCLONE_JOTTACLOUD_MD5_MEMORY_LIMIT` env setting serves no purpose anymore? I previously had it set to 1GB to avoid disk usage, which was as much as I could spare on the machine in question.

**Closed** 2020-04-22 10:34 UTC
Labels: Remote: Crypt, Remote: Jottacloud, enhancement

**Comment by ncw** [comment] 2020-04-22 10:37
I've merged this fix to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

This will be the first beta with the fix in

https://beta.rclone.org/v1.51.0-191-gd22e6f5a-beta/ (uploaded in 15-30 mins)

> Does that mean the RCLONE_JOTTACLOUD_MD5_MEMORY_LIMIT env setting serves no purpose anymore? I previously had it set to 1GB to avoid disk usage, which was as much as I could spare on the machine in question.

No there are still cases where it is needed, for instance copying direct from OneDrive to jottacloud - onedrive doesn't support MD5 hashes so the jotta backend will still need to calculate them.

**Comment by V33m** [comment] 2020-04-22 11:05
Glad to hear that! I've been using `rclone v1.51.0-154-ga283c655-fix-crypt-src-hash-beta` on several devices without any issues. Will transform over to https://beta.rclone.org/v1.51.0-191-gd22e6f5a-beta/  to help with testing to ensure it's stable enough for v.1.52 👍

**Comment by ncw** [comment] 2020-04-23 19:26
Thanks @V33m more testing would be very useful :-)
