### ISSUE TITLE
Chunking Hash Compare Before Upload.

### ISSUE THREAD

**Issue by PoeticDeath** [rclone/rclone#5082] opened 2021-03-01 22:05 UTC
#### What is your current rclone version (output from `rclone version`)?

rclone v1.55.0-beta.5241.0ad38dd6f
- os/arch: linux/amd64
- go version: go1.16

#### What problem are you are trying to solve?

Redundant uploading of chunks when they match the original after a file is updated.

#### How do you think rclone should be changed to solve that?

Here is the idea... Using the already implemented hashing to hash each chunk so that if they are the same after a file is updated they don't have to be reuploaded. (Bandwidth and Time Savings).

Here is a python 3 example of what I mean (NOT functional just a better idea of what I mean):

def upload(file):
----file.split(chunk_size)
----for chunk in file:
--------hashed-chunk = hash.md5(chunk)
--------if (hashed-chunk != old-hashed-chunk):
------------chunk-file.write(chunk)
--------else:
------------pass

**Comment by ivandeex** [comment] 2021-03-02 10:55
duplicate of #4547 and #5041

**Closed by ivandeex** 2021-03-02 10:55 UTC
