### ISSUE TITLE
Symbol ‛  auto added before character "？""

### ISSUE THREAD

**Issue by a-box** [rclone/rclone#3723] opened 2019-11-12 10:57 UTC
#### What is the problem you are having with rclone?
Symbol `  auto added before character "**？**"
Problem existed only on 1.50 or newer, 1.49.5 is fine

#### What is your rclone version (output from `rclone version`)
rclone v1.50.1
- os/arch: windows/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64bit

####  Which cloud storage system are you using? (eg Google Drive)
local, google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone rmdirs "A？B"
rclone ls "A？B"
rclone copy "XYZ"
rclone copy "DEF" "DEF？"
rclone mkdir "X？Z"

rclone copy -vv "gd:XX？YY" .

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
local 
```
> rclone rmdirs "A？B" -vv
2019/11/12 18:31:10 ERROR : Local file system at //?/O:/Trash/3/A‛‛？B: Failed to list "": directory not found

> rclone ls "A？B" -vv
2019/11/12 18:33:43 ERROR : : error listing: directory not found

> rclone copy "A？B" XYZ -vv
2019/11/12 18:33:43 ERROR : : error listing: directory not found

> rclone copy "DEF" "DEF？"
> dir /ad
2019-11-12  18:32    <DIR>          DEF
2019-11-12  18:39    <DIR>          DEF‛？   <-- unwanted ‛ added

> rclone lsd .
          -1 2019-11-12 18:32:04        -1 DEF
          -1 2019-11-12 18:39:47        -1 DEF？  
```
```
> rclone mkdir "X？Z"
> dir /ad
2019-11-12  18:44    <DIR>          X‛？Z    <-- unwanted ‛ added
```

drive to local
```
rclone copy -vv "gd:XX？YY" .
> dir /ad
2019-11-12  18:39    <DIR>          XX‛？YY   <-- unwanted ‛ added
```

local to drive
```
rclone copy "CC？DD" gd:
> dir /ad
2019/11/12 18:46:43 ERROR : : error reading source directory: directory not found
```

**Comment by ncw** [comment] 2019-11-12 12:02
This is a consequence of the lib encoder changes to allow rclone to store any filename anywhere.

Note that the symbol `‛` isn't actually added on the remote, it is just a display thing locally.

What rclone is allowing you to do is to make files with `?` in them on windows.  See here for the replacements: https://rclone.org/local/#restricted-characters

So when you do

    rclone mkdir "X?Z"

rclone will create a directory called `X？Z`

However when you do

    rclone mkdir "X？Z"

rclone needs to disambiguate that and creates a directory called `X‛？Z`.  However if you look at that directory on drive it will be called `X？Z` as `?` isn't a special character for drive.

The replacement character set was chosen so that it wasn't in wide use, but you are obviously using it!

Hopefully that makes some sort of sense!

Can you describe more the problems that this is causing you?

**Comment by a-box** [comment] 2019-11-12 12:06
> This is a consequence of the lib encoder changes to allow rclone to store any filename anywhere.
> 
> Note that the symbol `‛` isn't actually added on the remote, it is just a display thing locally.
> 
> What rclone is allowing you to do is to make files with `?` in them on windows. See here for the replacements: https://rclone.org/local/#restricted-characters
> 
> So when you do
> 
> ```
> rclone mkdir "X?Z"
> ```
> 
> rclone will create a directory called `X？Z`
> 
> However when you do
> 
> ```
> rclone mkdir "X？Z"
> ```
> 
> rclone needs to disambiguate that and creates a directory called `X‛？Z`. However if you look at that directory on drive it will be called `X？Z` as `?` isn't a special character for drive.
> 
> The replacement character set was chosen so that it wasn't in wide use, but you are obviously using it!
> 
> Hopefully that makes some sort of sense!
> 
> Can you describe more the problems that this is causing you?

I can't download the file or folder with exactly same name to my window local if the folder or file contains "？" on the remote

copy drive=> local
remote |  local
A？B  => A‛？B
A？B .mkv A‛？B

**Comment by ncw** [comment] 2019-11-12 13:19
> I can't copy the file or folder with exactly same name to my window local if the folder or file contains "？" on the remote.

Yes, that is the unfortunate consequence of this.

> Character "？：＜＞＊／＼" is widely use on Japanese or Chinese environment.

What do you think rclone should do instead? Any ideas?

**Comment by k2love** [comment] 2019-11-14 11:37
I submitted a bug report to the forum for the same issue. I hope the developers are well oriented. The freedom to rename files is a very important issue for rclone.

**Comment by a-box** [comment] 2019-11-14 12:32
> What do you think rclone should do instead? Any ideas?

Is it possible add a flag to **disable (OFF)** the conversion?
But I don't have much idea when the conversion is **enable (ON)**.
As my main enivonment is windows (manage on windows, mount on debian), I never face the invalid filename problem over a year for my 150TB plex media files. 
- rarely, rarely and rarely used :/\/?<>
- widely used ：／＼？＊＜＞

when **OFF**
copy from drive to local (windows)
- error for incorrect filename (:/\/? ...etc)
- copy with exactly filename (：＼／？＊｜）

**Comment by ncw** [comment] 2019-11-14 21:48
OK I will have a think about this - thank you for your suggestion.

**Comment by k2love** [comment] 2019-11-22 06:46
I am still at 1.4.5 because of this problem. I would like to see a resolved version soon.

**Comment by k2love** [comment] 2019-11-29 21:19
It's a pity that the great developer Nick doesn't know much about MS Windows. I also want to study programming to help the developer. (Rclone seems to be made in the Go language, right?)

Windows uses ":" as the folder name. But what I need is not ":" but ":". Not only me but many Asian languages ​​use these special characters. "?" Of course this cannot be used as a folder name. Use "？" instead.

I'll find some data and show you.

**Comment by k2love** [comment] 2019-11-29 21:22
https://wepplication.github.io/tools/charMap/

KS X 1001 Special Characters /Unicode table /Unicode table /Unicode (Hanja) Table

**Comment by ncw** [comment] 2020-01-26 17:14
Please can you try this with the `--local-encoding None` flag? You can put that as encoding = None in your config if you make a local remote.

That disables the character name conversion and should fix the problem for you.

You can find this in [the latest beta](https://beta.rclone.org).

**Comment by boxothing** [comment] 2020-01-30 20:17
I also had same issue because I had local windows files using those extended characters in filenames and rclone wouldn't upload them to remote google drive.

I just tried the latest beta (v1.50.2-200-gf80d9855-beta) with `--local-encoding None` and everything works as intended.

**Comment by a-box** [comment] 2020-01-31 07:19
Sorry for the late reply.
The flag work and fix the problem for me. 
Thanks

**Comment by ncw** [comment] 2020-01-31 15:58
Thanks for testing - I'll close this now.

**Closed by ncw** 2020-01-31 15:58 UTC
Labels: bug

**Comment by boxothing** [comment] 2020-02-01 19:54
Just found an issue while testing these full width symbols.
＼＊＜／？＞：＂｜

So with `--local-encoding None` option it works except for  forwardslash '／' 
None of my files had this so I missed on my initial testing.

**Comment by ncw** [comment] 2020-02-02 22:34
> So with `--local-encoding None` option it works except for forwardslash '／'
> None of my files had this so I missed on my initial testing.

What was the issue?
