### ISSUE TITLE
VFS: stale entries in the cache with --vfs-cache-mode full

### ISSUE THREAD

**Issue by FrankSansC** [rclone/rclone#6053] opened 2022-03-22 12:20 UTC
#### What is the problem you are having with rclone?

Can't install "rclone-beta-latest-linux-amd64.deb"

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian sid
```
$ uname -a
Linux 5.16.0-5-amd64 #1 SMP PREEMPT Debian 5.16.14-1 (2022-03-15) x86_64 GNU/Linux
```
#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
$ sudo apt install /tmp/rclone-beta-latest-linux-amd64.deb
```
#### A log from the command
```
Reading package lists... Error!
E: Invalid archive member header
E: Could not read meta data from rclone-beta-latest-linux-amd64.deb
E: The package lists or status file could not be parsed or opened.
```
#### Other information

When trying to open the .deb package with an archive manager I got the following error when trying to open "data.tar.gz" :
```
An error occurred while extracting files
Truncated ar archive
```
The .deb packages for other platforms don't seem to be impacted (can extract the content of "data.tar.gz")
```
$ sha256sum rclone-beta-latest-linux-amd64.deb
532bc5a8c1fb9cf02009aefa9716b8af3984c151406d8c7a7eca411140902f42  rclone-beta-latest-linux-amd64.deb
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment] 2022-03-22 16:30
Seems to be something broken with that as I can reproduce it as well. Wonder if that's back when the beta area had a file full issue?

@ncw would been to rebuild I'd imagine.

**Comment by ncw** [comment] 2022-03-24 10:00
https://beta.rclone.org is served by caddy pointing at an rclone mount.

The rclone mount in turn points to a swift bucket where the data is actually held.

The config is like this

```
/usr/bin/rclone mount
-v
--read-only
--config /home/www-data/.rclone.conf
--cache-dir /home/www-data/.cache/rclone
--dir-cache-time 1m
--vfs-cache-mode full
--vfs-cache-max-age 168h
--allow-non-empty
--allow-other
--use-mmap=true
--vfs-cache-max-size 30G
--rc
memstore:beta-rclone-org
/mnt/beta.rclone.org
```


This is very likely a subtle bug in the rclone VFS cache.

That particular file seems to be OK now but I found a different one

download and download2 were downloaded (with rclone) but memstore was from the source swift bucket directly

Sizes all the same

```
$ ls -l /tmp/beta-latest-*/rclone-beta-latest-freebsd-arm.zip
-rw-rw-r-- 1 ncw ncw 13563975 Jan  1  1970 /tmp/beta-latest-download2/rclone-beta-latest-freebsd-arm.zip
-rw-rw-r-- 1 ncw ncw 13563975 Jan  1  1970 /tmp/beta-latest-download/rclone-beta-latest-freebsd-arm.zip
-rw-rw-r-- 1 ncw ncw 13563975 Mar 22 16:51 /tmp/beta-latest-memstore/rclone-beta-latest-freebsd-arm.zip
```
But md5sums different

```
$ md5sum /tmp/beta-latest-*/rclone-beta-latest-freebsd-arm.zip
7d1bc9554f1f885b48a3fa85aaf25b57  /tmp/beta-latest-download2/rclone-beta-latest-freebsd-arm.zip
7d1bc9554f1f885b48a3fa85aaf25b57  /tmp/beta-latest-download/rclone-beta-latest-freebsd-arm.zip
b81f1ad495e96e743aaf469c19a08922  /tmp/beta-latest-memstore/rclone-beta-latest-freebsd-arm.zip
```

If I look on the server I see

```
# cat /home/www-data/.cache/rclone/vfsMeta/memstore/beta-rclone-org/rclone-beta-latest-freebsd-arm.zip
{
	"ModTime": "2022-03-19T04:17:21.921988478Z",
	"ATime": "2022-03-24T09:25:15.338262287Z",
	"Size": 13561509,
	"Rs": [
		{
			"Pos": 0,
			"Size": 13561509
		}
	],
	"Fingerprint": "13563975,2022-03-22 16:51:36.245197511 +0000 UTC,b81f1ad495e96e743aaf469c19a08922",
	"Dirty": false
}
```

The hash and length in the fingerprint match the file in the bucket. The size is wrong though 13,561,509 is smaller than the correct size of 13,563,975 by 2,466 bytes

Directly on the mount the file looks like this, so the size looks correct

```
# md5sum /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip
a3d432d95acb1b27fbe61a034a5291a0  /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip
# ls -l /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip
-rw-r--r-- 1 www-data www-data 13563975 Mar 22 16:51 /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip
```

Which is a different hash again!

If I try downloading that file with wget

    wget https://beta.rclone.org/rclone-beta-latest-freebsd-arm.zip

it doesn't work with the server stopping at `Connection closed at byte 13561509` which is what you might expect

Copying the file direct from the mount truncates it

```
# cp -av /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip /tmp/z
'/mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip' -> '/tmp/z'
# ls -l /tmp/z
-rw-r--r-- 1 www-data www-data 13561509 Mar 22 16:51 /tmp/z
# ls -l /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip
-rw-r--r-- 1 www-data www-data 13563975 Mar 22 16:51 /mnt/beta.rclone.org/rclone-beta-latest-freebsd-arm.zip
```

The file in the cache looks like this on the server

```
# md5sum /home/www-data/.cache/rclone/vfs/memstore/beta-rclone-org/rclone-beta-latest-freebsd-arm.zip
a3d432d95acb1b27fbe61a034a5291a0  /home/www-data/.cache/rclone/vfs/memstore/beta-rclone-org/rclone-beta-latest-freebsd-arm.zip
# ls -l /home/www-data/.cache/rclone/vfs/memstore/beta-rclone-org/rclone-beta-latest-freebsd-arm.zip
-rw------- 1 www-data www-data 13561509 Mar 22 16:51 /home/www-data/.cache/rclone/vfs/memstore/beta-rclone-org/rclone-beta-latest-freebsd-arm.zip
```

So it is the incorrect short size (matching the metadata) but not the actual file.

So what looks like happened is the cache and the actual file system got out of sync. What will have happened is that the `rclone-beta-latest-freebsd-arm.zip` will have got updated in the swift bucket, but somehow rclone did not notice the new size. It clearly did notice the new fingerprint because it has that.

If I look at a diff between the downloaded file and the correct file I see

```
$ diff -u <(hd /tmp/beta-latest-memstore/rclone-beta-latest-freebsd-arm.zip) <(hd /tmp/beta-latest-download/rclone-beta-latest-freebsd-arm.zip)
--- /dev/fd/63  2022-03-24 09:52:37.320948663 +0000
+++ /dev/fd/62  2022-03-24 09:52:37.320948663 +0000
@@ -1,847750 +1,847599 @@
-00000000  50 4b 03 04 0a 00 00 00  00 00 6f 86 76 54 00 00  |PK........o.vT..|
+00000000  50 4b 03 04 0a 00 00 00  00 00 bd 78 72 54 00 00  |PK.........xrT..|
 00000010  00 00 00 00 00 00 00 00  00 00 2f 00 1c 00 72 63  |........../...rc|
 00000020  6c 6f 6e 65 2d 76 31 2e  35 39 2e 30 2d 62 65 74  |lone-v1.59.0-bet|
-00000030  61 2e 36 30 33 39 2e 64  34 64 61 39 62 39 38 64  |a.6039.d4da9b98d| <- correct version
+00000030  61 2e 36 30 33 37 2e 37  35 30 66 66 66 64 66 37  |a.6037.750fffdf7| <- downloaded version
 00000040  2d 66 72 65 65 62 73 64  2d 61 72 6d 2f 55 54 09  |-freebsd-arm/UT.|
```

Which quite clearly shows the data is from a previous vesion the `6037` revision, not the `6039` revision it should be.

So what appears to have happened is the fingerprint changed, but rclone never invalidated the data and re-downloaded it.

I will try to reproduce this locally.

**Comment by ncw** [comment] 2024-01-14 12:28
Here is a reproducer for this, from: https://forum.rclone.org/t/cached-webdav-mount-fingerprints-get-nuked-on-ls/43974/5

```
mkdir mnt
mkdir data

# run this in one window
rclone -vv mount \
       --read-only   \
       --cache-dir=/tmp \
       --vfs-cache-mode=full \
       --dir-cache-time=1s  \
       $(pwd)/data \
       $(pwd)/mnt

# do this in another window
for i in $(seq -w 1000); do echo foo$i > data/test ; sleep 5 ; got=$(cat mnt/test); echo $got ; [[ "$got" != "foo$i" ]] && { echo "FAILED"; break; } ; done
```

This will print something like

```
$ for i in $(seq -w 1000); do echo foo$i > data/test ; sleep 5 ; got=$(cat mnt/test); echo $got ; [[ "$got" != "foo$i" ]] && { echo "FAILED"; break; } ; done
foo0001
foo0001
FAILED
```

At this point you'll get

```
$ cat mnt/test
foo0001
$ cat data/test
foo0002
$ cat mnt/test
foo0001
```

And in the log

```
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): openPending: 
2024/01/14 12:20:44 DEBUG : test: vfs cache: checking remote fingerprint "8,2024-01-14 12:19:41.374743943 +0000 UTC,c5023da84524a7331e89d6c4ae800230" against cached fingerprint "8,2024-01-14 12:19:41.374743943 +0000 UTC,c5023da84524a7331e89d6c4ae800230"
2024/01/14 12:20:44 DEBUG : test: vfs cache: truncate to size=8 (not needed as size correct)
2024/01/14 12:20:44 DEBUG : : Added virtual directory entry vAddFile: "test"
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): >openPending: err=<nil>
2024/01/14 12:20:44 DEBUG : vfs cache: looking for range={Pos:0 Size:8} in [{Pos:0 Size:8}] - present true
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): >_readAt: n=8, err=EOF
2024/01/14 12:20:44 DEBUG : &{test (rw)}: >Read: read=8, err=<nil>
2024/01/14 12:20:44 DEBUG : &{test (rw)}: Flush: 
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): RWFileHandle.Flush
2024/01/14 12:20:44 DEBUG : &{test (rw)}: >Flush: err=<nil>
2024/01/14 12:20:44 DEBUG : &{test (rw)}: Release: 
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): RWFileHandle.Release
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): close: 
2024/01/14 12:20:44 DEBUG : test: vfs cache: setting modification time to 2024-01-14 12:19:41.374743943 +0000 GMT
2024/01/14 12:20:44 DEBUG : test(0xc000b142c0): >close: err=<nil>
2024/01/14 12:20:44 DEBUG : &{test (rw)}: >Release: err=<nil>
```

Where that md5sum `c5023da84524a7331e89d6c4ae800230` is that of the new data

```
$ md5sum data/test 
c5023da84524a7331e89d6c4ae800230  data/test
$ md5sum mnt/test
4d6388cad348ce6d6c73ea6e962f0e5c  mnt/test
```

However the modtime of both files is the same and correct

```
$ stat data/test
  File: data/test
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 10104163    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/     ncw)   Gid: ( 1000/     ncw)
Access: 2024-01-14 12:19:46.378731794 +0000
Modify: 2024-01-14 12:19:41.374743943 +0000
Change: 2024-01-14 12:19:41.374743943 +0000
 Birth: 2024-01-14 11:53:33.305889231 +0000

$ stat mnt/test 
  File: mnt/test
  Size: 8         	Blocks: 1          IO Block: 4096   regular file
Device: 32h/50d	Inode: 14597221540505887712  Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/     ncw)   Gid: ( 1000/     ncw)
Access: 2024-01-14 12:19:41.374743943 +0000
Modify: 2024-01-14 12:19:41.374743943 +0000
Change: 2024-01-14 12:19:41.374743943 +0000
 Birth: -
```

In the VFS cache we have the wrong data

```
$ cat /tmp/vfs/local/tmp/webdav-bug/data/test 
foo0001
```

But the metadata is that of the new file.

```
$ cat /tmp/vfsMeta/local/tmp/webdav-bug/data/test
```

```json
{
	"ModTime": "2024-01-14T12:19:41.369368711Z",
	"ATime": "2024-01-14T12:25:19.756311287Z",
	"Size": 8,
	"Rs": [
		{
			"Pos": 0,
			"Size": 8
		}
	],
	"Fingerprint": "8,2024-01-14 12:19:41.374743943 +0000 UTC,c5023da84524a7331e89d6c4ae800230",
	"Dirty": false
}
```

**Comment by ncw** [comment] 2024-01-15 11:47
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.66

**Closed** 2024-01-15 11:47 UTC
Labels: bug, VFS / mount, build

**Comment by nicobrevin** [comment] 2024-02-04 20:02
I'm presuming this is the bug referenced in the changelog as "Fix stale data when using --vfs-cache-mode full (Nick Craig-Wood)"?

**Comment by ncw** [comment] 2024-02-04 20:06
@nicobrevin yes, that is correct
