### ISSUE TITLE
rclone generate versions when using chunker on onedrive wasting 50% available space

### ISSUE THREAD

**Issue by tecepeipe** [rclone/rclone#4373] opened 2020-06-19 08:40 UTC
Using current version of rclone (1.40-1.50) I noticed that all my onedrive 5TB were full after filling with 2.5TB (with copy/sync) ONLY if using the chunker to split large files. 
After a lot of googling and frustation I found evidences that each chunk file was being saved twice as version history.

This might be affecting other storage types, but I'm not sure. For sure this is an issue on Onedrive.

**Comment by Zvezdin** [comment] 2020-06-19 11:50
I think this issue is separate from Chunker. 
I suspect that you'll observe the same issue without chunker. Generally rclone copy uses double the user's quota, see the onedrive backend docs on why. See #4106 on progress for a workaround.

**Comment by tecepeipe** [comment] 2020-06-19 19:37
actually not. This versioning issue is only present on onedrive when using chunker. tested/confirmed.
as suggested by 4106 cleanup currently does nothing on onedrive - returns "ne drive root 'Folder X' doesn't support cleanup"

**Comment by Zvezdin** [comment] 2020-06-19 22:33
I would still suggest that the issue is still caused by the OneDrive 'feature' where setting modification times on an uploaded file creates a new version of it which takes the same amount of space. The chunker might be doing that see here. I do use chunker for OneDrive (ontop of crypt), I'll try to confirm later if I observe the same problem too.

19 Jun 2020 22:38:12 Fabricio Lima <notifications@github.com>:

**Comment by ncw** [comment] 2020-06-20 15:20
> I would still suggest that the issue is still caused by the OneDrive 'feature' where setting modification times on an uploaded file creates a new version of it which takes the same amount of space.

That would be my guess too - it would be useful if we can confirm that.

Looking at the source code I think this doubling of the versions only happens on server side copy or set mod time, neither of which is normally necessary when uploading files straight to onedrive.

If you set the modification time of a file then it creates another version on onedrive which we haven't found a way around. 

Looking at the source of chunker I think it only sets the modtime on the first chunk - can you confirm it is only the first chunk being doubled or all of them?

**Comment by tecepeipe** [comment] 2020-06-20 19:58
All chunks have duplicate versions, thus I was only able to use 2.5T in all of my onedrives using chunker.

**Comment by ncw** [comment] 2020-06-26 11:23
@tecepeipe can you upload a single large file with chunker with `-vv --dump headers` - that should enable us to see where the extra version gets made which will give us a chance to work out what is happening - thanks!

**Comment by tecepeipe** [comment] 2020-06-29 01:53
6gb file uploaded using a recent beta version.
The version isn't relevant as I have faced this issue across several versions. As I'm dealing with this since when I started to uplaod this back on January using 1.49.
logs enclosed.
[chunker version history.zip](https://github.com/rclone/rclone/files/4843373/chunker.version.history.zip)

**Comment by ncw** [comment] 2020-07-01 21:43
That is interesting - thank you.

I wonder if the renames chunker is doing is making versions. It didn't in my tests though.

Can you see if you do a server side rename you get a version?

So upload a small file then rename it with rclone so `rclone moveto onedrive:file onedrive:file-renamed`

Are you using onedrive personal or business?

**Comment by tecepeipe** [comment] 2020-07-01 21:45
It doesn't happen when doing rename
OneDrive for business

Cheers
Fabricio Lima
021 088-12688

**Comment by tecepeipe** [comment] 2020-07-01 23:24
"Effective immediately, Microsoft has increased the upload file size limit
from 15 GB to 100 GB in OneDrive and SharePoint for everyone."

This fixes this bug as chunker is no long required for large files.

Cheers
Fabricio Lima
021 088-12688

**Comment by ncw** [comment] 2020-07-02 08:34
> "Effective immediately, Microsoft has increased the upload file size limit from 15 GB to 100 GB in OneDrive and SharePoint for everyone." This fixes this bug as chunker is no long required for large files.

That is good news!

I'd still like to fix this bug though!

Can you show me your chunker config please?

**Comment by tecepeipe** [comment] 2020-07-02 08:57
[onedrive-30]
type = chunker
remote = onedrive-3:
chunk_size = 5G
hash_type = none

**Comment by ncw** [comment] 2020-07-02 09:58
I've managed to replicate this and pin it down to exactly where it is happening.

It is the server side moves that chunker does that cause onedrive for business to make an extra version. This doesn't happen on onedrive personal.

    rclone moveto -vv onedriveb:5Mb.rclone_chunk.001a  onedriveb:5Mb.rclone_chunk.001 --dump bodies

Gives

```
2020/07/02 10:31:21 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/07/02 10:31:21 DEBUG : 5Mb.rclone_chunk.001a: Need to transfer - File not found at Destination
2020/07/02 10:31:21 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/07/02 10:31:21 DEBUG : HTTP REQUEST (req 0xc000762300)
2020/07/02 10:31:21 DEBUG : PATCH /v1.0/drives/b!tPczmrJTCE2ShO96VLAAn_DGv2_4eZJGl83N0OQe_t9LuHcGPileQ7YByS0_6_xp/items/01W3O4PF47DKFGIP5DMBF2X6A42A4RAHFS HTTP/1.1
Host: graph.microsoft.com
User-Agent: rclone/v1.52.2-190-g32d3236d-fix-onedrive-moveto-beta
Content-Length: 237
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"parentReference":{"driveId":"","id":"01W3O4PF56Y2GOVW7725BZO354PWSELRRZ","path":"","driveType":""},"name":"5Mb.rclone_chunk.001","fileSystemInfo":{"createdDateTime":"2020-07-02T08:34:44Z","lastModifiedDateTime":"2020-07-02T08:34:44Z"}}
2020/07/02 10:31:21 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


2020/07/02 10:31:22 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/07/02 10:31:22 DEBUG : HTTP RESPONSE (req 0xc000762300)
2020/07/02 10:31:22 DEBUG : HTTP/1.1 200 OK
Cache-Control: private
Client-Request-Id: b7ad8b69-02bc-4509-831c-411f8ea81419
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Date: Thu, 02 Jul 2020 09:31:21 GMT
Odata-Version: 4.0
Request-Id: b7ad8b69-02bc-4509-831c-411f8ea81419
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"3","ScaleUnit":"000","RoleInstance":"AGSFE_IN_75"}}

{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('b%21tPczmrJTCE2ShO96VLAAn_DGv2_4eZJGl83N0OQe_t9LuHcGPileQ7YByS0_6_xp')/items/$entity", SNIP,"file":{"mimeType":"application/octet-stream","hashes":{"quickXorHash":"AAAAAAAAAAAAAAAAAAAQAAAAAAA="}},"fileSystemInfo":{"createdDateTime":"2020-07-02T08:34:44Z","lastModifiedDateTime":"2020-07-02T08:34:44Z"}}
2020/07/02 10:31:22 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/07/02 10:31:22 INFO  : 5Mb.rclone_chunk.001a: Moved (server side)
2020/07/02 10:31:22 INFO  : 
```

This also creates a new version if I rename stuff in the web interface.

@Cnly - I'm not sure we can do much about this - it is the same kind of bug as the setmodtime bug - modifying the metadata creates a version.

Maybe Microsoft like charging their customers extra for renamed files ;-)

PS While researching this problem I found two bugs in `moveto` one general one 8d5bc7f28b8459a0e04fdbfd2dca43c5d9ec4555 and one specific to onedrive 50e36fb4822c2b23442333f70c6de894bef6fea4

**Comment by Cnly** [comment] 2020-07-02 10:42
#4106 may fix this by automatically cleaning up versions after metadata changes.

**Comment by ncw** [comment] 2020-08-06 17:11
Note that this issue is being fixed with the `no_versions` flag for the onedrive backend in #4106 so please follow that issue for updates :-)

in particular there is a beta here https://github.com/rclone/rclone/issues/4106#issuecomment-670059477 for you to check out.

I'm going to close this as I think it will be fixed by the above, if not write here and I'l re-open the issue.

**Closed by ncw** 2020-08-06 17:11 UTC
Labels: Remote: Chunker, Remote: One Drive, enhancement
