### ISSUE TITLE
API ban.. but not an API ban?

### ISSUE THREAD

**Issue by kerbysj** [rclone/rclone#1211] opened 2017-03-05 12:38 UTC
> What is your rclone version (eg output from `rclone -V`)
1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 15.10 64bit
> Which cloud storage system are you using? (eg Google Drive)
Gdrive (and acd)
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Mount
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
No output.

Sthis is the second time this has happened to me in two days. My current setup is with union-fs so typical local/media/remote folder. I have my own API key set to that particular machine as well, so i am aware of what api request is like.
Currently using with some plex on an archived folder (rather than keeping everything on my local 30tb storage) so its not something that gets used alot. Past couple of days i have been able to continuly upload to drive however each morning i wake up to find out the permissions on all my mounted files have changed that plex is now saying it is saying it does not have the correct permissions for this file.
If i send of a rclone move or copy this works fine... If i try to download from the web client i get an error.

Has anyone seen this behaviour?

**Comment by breunigs** [comment] 2017-03-06 20:04
You *have* an API ban. The ban applies to specific actions, in this case downloading. This is why you can still upload or rename (move) files. 

I am quite confused by your description on how you setup Plex, but I *guess* the following happens:
* you have set Plex to update your library periodically
* Plex sees the files on the rclone mount as new, e.g. due to slightly different paths or because your union mount is not setup properly.
* Plex starts to index the new files – i.e. it reads _every_ file on the rclone mount
* You receive an API ban
* Plex reports some permission error because rclone mount cannot read (=download) files anymore

Start the rclone mount with the `--verbose` flag and save the logs. When Plex indexes and every file is being read, then you need to tweak your mounts.

**Comment by jpat0000** [comment] 2017-03-08 17:29
@breunigs 

This is a close description of what's happening. However, the issue likely isn't caused by any configuration issues and Google Drive doesn't seem to have any download limit. API bans are common with Plex user because Plex traverses your entire library every time you go to refresh your available media. Plex is also setup to re-analyze (download) all of your files periodically by default while it isn't required to do so.

If rclone requests the contents (file names) of a folder too many times in a day you will receive a 24-hour download ban.

I have transferred over 10 terabytes on Google Drive in a single day before, I don't believe that they have a very achievable bandwidth cap. I currently mount my Google Drive with other software which caches the entire file structure, this has resolved my Plex misfortunes.

You can do some things to possibly prevent getting API banned using rclone though.

I wrote this elsewhere, so it's just a copy & paste.

> Don't sync, just upload your files. If you have a local folder, let's say "Movies", and a folder on Google Drive "Movies", and you simply want to upload or move your files to Google Drive, use rclone to upload them, with the added command "--no traverse". Example usage:

>rclone --no-check-certificate --no-traverse --drive-chunk-size=64M --transfers=6 move /home/myuser/Movies google:Data/Movies --exclude .@**

Without "--no-traverse" rclone will check every folder to make sure you're not uploading a file which exists elsewhere on your Google Drive. This uses a lot of queries and gets you closer to getting banned.

>Go into Plex > Settings> Server > Scheduled Tasks > **Uncheck:**

>Remove old cache files every week (possibly)
Refresh local metadata every three days
Update all libraries during maintenance
Upgrade media analysis during maintenance
Refresh metadata periodically
Perform extensive media analysis during maintenance

>Do not use --no-modtime when mounting Google Drive, Plex will need to re-analyze your files at every remount because it will believe your files have been in some way modified. General advice: try not to interrupt a library refresh, ever.

>Move all of your movie files into a single directory, instead of allowing your Movies to have their own folder. It should be Movies/file.2016.mp4 instead of Movies/file.2016/file.2016.mp4

>Do not excessively refresh your Plex library.
If you are getting media added to your local drive and you're periodically uploading the data to Google Drive, you probably wont need to refresh your Plex library ever, just so long as partial scans are working.

**Comment by ncw** [comment] 2017-03-09 21:43
I plan to hook into the google drive changes API eventually (got some re-org to do first) which should help.

**Comment by animosity22** [comment] 2020-01-11 21:23
This has been resolved for some time now. If you have a new question, please ask on the forums.

**Closed by animosity22** 2020-01-11 21:23 UTC
