### ISSUE TITLE
rclone destroys config file upon crash

### ISSUE THREAD

**Issue by TimetravelerDD** [rclone/rclone#4234] opened 2020-05-14 19:49 UTC
#### What is the problem you are having with rclone?
Dear rclone team,

today it happend the second time to me, that my config file was completely wiped out. It happend because I had to force shutdown my computer. The rclone.conf file still exists and the size is unchanged, however it is completely wiped (overwritten with 00 in binary format). If you like I can upload the broken config file, however I checked with Hex edit: there is really nothing but '00'

I am not sure if this matters, but i use rclone though rclone browser v1.8.0

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: windows/amd64
- go version: go1.13.7

i use it though rclone browser v1.8.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 1909 x64 

####  Which cloud storage system are you using? (eg Google Drive)
gdrive + crypt

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount though rclone browser. 2 remotes were mounted during the crash. The config file was not opened for edit or modified recently.

#### Expected Behaviour
I would prefer that rclone.exe made a backup of the rclone.conf before it tries to modify it

**Comment by animosity22** [comment] 2020-05-14 21:12
You can make a copy of your rclone.conf once you have your config setup so you can always restore it.

The way the mounts work is they need to update the refresh tokens in your rclone.conf and that happens like once an hour or so I believe with Google Drive.

I don't think rclone corrupted the file as it was the crash.

**Comment by ncw** [comment] 2020-05-15 15:20
The zeros in the file are caused by the OS not writing back the dirty data in the config file.

In 47e2d5c415 I added a sync to the file which should help in scenarios like this. This is in [the latest beta](https://beta.rclone.org)...

**Comment by TimetravelerDD** [comment] 2020-05-16 19:57
Thanks, that sounds promising!

**Comment by calisro** [comment] 2020-05-16 21:42
Closing this as the latest beta should fix this.

**Closed by calisro** 2020-05-16 21:42 UTC
Labels: question
