### ISSUE TITLE
bisync: handle deletion conflicts

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5691] opened 2021-10-08 17:27 UTC
## Synopsis

bisync should handle deletion conflicts

## References

- https://github.com/rclone/rclone/issues/118
- https://github.com/cjnaz/rclonesync-V2/issues/71
- https://github.com/Jwink3101/syncrclone/blob/master/docs/algorithm.md
- https://github.com/Jwink3101/syncrclone

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment] 2023-08-23 10:14
I'm not clear on what this is about...does anyone know? Best guess is it may be a dupe of #5690, or possibly the work completed recently in https://github.com/rclone/rclone/pull/6971/commits/add917cfac363bd49ac718123f29f764ea5531c0.

**Comment by nielash** [comment] 2023-09-05 07:44
Closing as stale. If anyone disagrees, please feel free to reply / reopen (preferably with a clearer description of the problem).

**Closed as not planned by nielash** 2023-09-05 07:44 UTC
Labels: enhancement, thinking, bisync
