### ISSUE TITLE
Only require config pass for commands that specify a remote

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#1163] opened 2017-02-21 19:21 UTC
Currently if I use an encrypted configuration, I'm asked for the password no matter what command I run. `rclone ls .` `rclone version` `rclone help`, even `rclone` with no arguments asks for a password. Since the configuration file only stores logins for remotes it should only ask for the password when a command makes use of a remote. 
I guess the only possible issue with this is that on windows unc settings may also be stored in the config http://rclone.org/local/#long-paths-on-windows/, but at the very least commands like help and version shouldn't require a password and ideally the rest shouldn't require a password when run on the local filesystem.

**Comment by ncw** [comment] 2017-02-22 09:22
Not a bad idea.  Not sure how easy it would be though as rclone relies on the config file being set up to parse the remote string.

**Comment by ivandeex** [comment] 2020-11-15 13:48
Duplicate of https://github.com/rclone/rclone/issues/4360

**Comment by ivandeex** [comment] 2021-02-14 01:11
This request is very similar to #4360
I'm not dismissing the request, just a little housekeeping.
@ghost You can subscribe to #4360
Thank you

**Closed by ivandeex** 2021-02-14 01:11 UTC
Labels: UX, configuration, duplicate, enhancement, terminal
