### ISSUE TITLE
rclone exit when api limit error

### ISSUE THREAD

**Issue by RaymondSchnyder** [rclone/rclone#1701] opened 2017-09-23 18:58 UTC
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone 1.37
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy /.local/ gdrive:/
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Just a Question.

I often reach the API User Limit on Google Drive, then i see on Rclone "Error 403 API Limit reached" but rclone doesnt exit, is it possible to immediatly exit rclone itself if such an error happens?
I looked up the documentation but found nothing about this.
Help would be appreciated

**Comment by Technifocal** [comment] 2017-09-24 00:32
Just out of interest, what would be the use case for this? Surely you'd want rclone to retry uploads if they fail, no?

**Comment by RaymondSchnyder** [comment] 2017-09-24 09:44
No i dont want that, because it even makes more API Hits, i want it to exit, and to retry a few hours later, because in the last days, ive not been able to copy even one file, because im always hitting the limit and its getting really annoying.

**Comment by RaymondSchnyder** [comment] 2017-09-24 10:32
Another Question: Is it possible to raise the Delay when a API Limit has been hitted from 10ms to an much higher value with an command option? Or do i have then to build rclone myself?

**Comment by Dulanic** [comment] 2017-10-01 10:59
I could see this being beneficial if it is a flag added. This is more impactful /w GDrives recent restriction to uploading 750GB per day.

**Comment by RaymondSchnyder** [comment] 2017-10-02 17:30
I did this now so as a workaround (Its cancer, so if you dont want to read cancer, skip this)

- I created a cronjob with rclone which starts a screen session which checks if its already running and if a "api.lock" is present, this cronjob writes the whole log to a file.
- I created another cronjob which runs faster than the cronjob above, which starts a script which reads the file declared above, and searchs for the string "ERROR: 403", if this string is found, the file gets cleaned, a file named "api.lock" in a folder is created, and the rclone screen will get killed.
- I did another script to check the API every 15 Minutes if the limit is free or locked, this can override the script result above.



You see, this workaround is... yeah its not cool. Please consider implementing automatic exit codes.

**Comment by SPDurkee** [comment] 2019-04-05 12:48
I'm surprised the isn't requested more. Hitting Google's 750gb limit is very common these days.

The transfers don't error out at exactly 750gb. So setting the max transfer limit to 750gb can still cause rclone to sit and spin for hours...

Setting low-level-retries and retries to 1 doesn't help either (now sure why??).

My current workaround is to run rclone prefaced with a timeout command as I know it will take X amount of minutes max before rclone sits and spins.

**Comment by kronnnnnn** [comment] 2019-04-23 17:26
This feature request should be at the top of the list, right?

**Comment by RaymondSchnyder** [comment] 2019-04-29 09:16
Can we get an answer from one of the devs? @ncw maybe?
This issue is open since september 2017... more than a year...

**Comment by ncw** [comment] 2019-05-13 15:51
The problem is that the 403 errors happen during normal operations, and as far as I know google doesn't distinguish the errors.  So you can get an error which means "slow down a bit" and the same error can mean "you are banned for 24 hours".

I'd be delighted to be proved wrong about this, so if you could capture some errors (using `-vv --dump responses) in the different situations I'd be grateful.

**Comment by RaymondSchnyder** [comment] 2019-05-13 20:42
> 
> 
> The problem is that the 403 errors happen during normal operations, and as far as I know google doesn't distinguish the errors. So you can get an error which means "slow down a bit" and the same error can mean "you are banned for 24 hours".
> 
> I'd be delighted to be proved wrong about this, so if you could capture some errors (using `-vv --dump responses) in the different situations I'd be grateful.

What i remember is that the errors dont stop when you are banned for 24 hours.
When you only get a "warning", rclone can continue to upload.

So you could differentiate by that:
- If error more than x in timeframe z, stop rclone and exit with a bad exitcode

Also, it would be beneficial to make this an option and not default behaviour.

**Comment by JavaJunkie09** [comment] 2019-06-14 14:55
Was having the same issue as OP. I need rclone to close when it errors and stops transferring.

@ncw Sorry to bring up an old topic, but a solution I thought of was maybe having it check how much data is uploaded in a time frame. For example, if 5MB has not been uploaded in the last 5 minutes, then exit?

Possible flag can maybe be something like this:
--exitif "5M,300"
(Exit if 5MB is not transferred in a 300 second duration?

**Comment by ncw** [comment] 2019-06-19 10:17
> Was having the same issue as OP. I need rclone to close when it errors and stops transferring.
> 
> @ncw Sorry to bring up an old topic, but a solution I thought of was maybe having it check how much data is uploaded in a time frame. For example, if 5MB has not been uploaded in the last 5 minutes, then exit?
> 
> Possible flag can maybe be something like this:
> --exitif "5M,300"
> (Exit if 5MB is not transferred in a 300 second duration?

That is a great idea...

Something like exit if
- no data or files transferred for X seconds

would be easy to implement?

**Comment by igoticecream** [comment] 2019-09-02 23:27
This is a much needed feature, use case is using rclone on a cron job that runs every X amount of time, but currently it will only spawn one job that will get stuck getting a bunch of 403

**Comment by lloydie11sky** [comment] 2020-01-01 17:40
I've written a whole host of scripts to manually implement this for my requirements, and as such would love to see rclone handle this natively.

Keep up the great work @ncw

**Comment by ncw** [comment] 2020-01-05 16:34
> I've written a whole host of scripts to manually implement this for my requirements, and as such would love to see rclone handle this natively.

What is the heuristic you are using @lloydie11sky ?

**Comment by lloydie11sky** [comment] 2020-01-05 22:45
I'm currently using more than 60 occurrences in the 100 transfer attempts, I'm just testing this now as a percent of 80% which I'm hoping will help.

The point of my script is to create a full sync agent for multiple mounts, so when it hits either API 750 daily limit, it queues the next sync for 24 hours, and queues each one with 750GB max transfer, records the result and only then pulls the sync back past a certain period.

I'm often asked why i don't just set the BWLIMIT to 8 and run them all one after the other, however i don't seem to get the speeds i need that way, and quite like the concept of my box having IDLE times, and not running sync jobs constantly when it doesn't need to.

Works quite well, but not exactly versatile for all situations, so i have a props file that let's you adjust various elements within my program.

Works well for what i need, but still wish it was native to rclone to save me the faff, after all, rclone is the whole reason I've tried to do it, because it's an exceptional project. Love it @ncw , keep up the good work.

**Comment by ncw** [comment] 2020-01-06 17:10
Interesting!

> The point of my script is to create a full sync agent for multiple mounts, so when it hits either API 750 daily limit,

How does this work? I've found it very hard to detect when the 750 limit is reached

**Comment by lloydie11sky** [comment] 2020-01-06 19:22
Well in my case, it simply monitors your log file for when this response comes back for from the API for more than x in x, which I've put in a parameter file so i can easily change it incase google changes the way it handles those requests.

At the moment I'm working on a data counter, so it will add up the transferred data, either from the output of the rclone log, or from something such as nethogs to let me know when i'm around 20 GB off the limit, then add a flag with date to in essence kill the job, and then check that flag each time a job is spun to see if 24 hours has elapsed since the flag was put in place.

Can you not look at something relating to the errors, so when maybe 20 consecutive errors are reached, then you check the response code for the API for each of those 20 errors, and if it's a permanent drop, then alert and kill?

It's by no means a polished piece of work, and i'm sure it's a lot more complicated than that to implement into something such as rclone, but it suits my needs.

**Comment by lloydie11sky** [comment] 2020-01-06 22:29
Perhaps you can clarify, i notice  when --MaxTransfer 750G has been hit in rclone, the exitcode for rclone still shows as 7, although the documentation shows this as being 8 for exceeding that switch.

https://rclone.org/docs/#exit-code

Is this something known that I've missed the issue log for?

Thanks,

**Comment by ncw** [comment] 2020-01-09 16:26
> Perhaps you can clarify, i notice when --MaxTransfer 750G has been hit in rclone, the exitcode for rclone still shows as 7, although the documentation shows this as being 8 for exceeding that switch.

Sounds like a bug!  Can you make a separate issue please :-)

**Comment by ncw** [comment] 2020-01-09 16:29
> Can you not look at something relating to the errors, so when maybe 20 consecutive errors are reached, then you check the response code for the API for each of those 20 errors, and if it's a permanent drop, then alert and kill?

Trouble is that the errors look the same from google telling you to back off a bit, to google not allowing any more data to be uploaded.  Can you verify that?

I guess some number, say 100 of these errors in a row might be reliable enough to conclude that the transfer limit has been reached.

**Comment by lloydie11sky** [comment] 2020-01-09 16:35
> > Can you not look at something relating to the errors, so when maybe 20 consecutive errors are reached, then you check the response code for the API for each of those 20 errors, and if it's a permanent drop, then alert and kill?
> 
> Trouble is that the errors look the same from google telling you to back off a bit, to google not allowing any more data to be uploaded. Can you verify that?
> 
> I guess some number, say 100 of these errors in a row might be reliable enough to conclude that the transfer limit has been reached.

This is in essence exactly what I've done, consecutive back-offs for each request that exceeds 60. OK my number may be a little low, but 100 would still be better than it simply going on forever.

I've not come across any issues as a result so far, and I've been doing that for around 6 months.

Oh the woes!

**Comment by ncw** [comment] 2020-01-12 17:13
I've just merged a fix for this in [the latest beta](https://beta.rclone.org) (you'll want v1.50.2-131 or later so may need to wait 15 mins from now).

If you use this flag then rclone should exit when we get to the 750 GB limit.

#### --drive-stop-on-upload-limit

Make upload limit errors be fatal

At the time of writing it is only possible to upload 750GB of data to
Google Drive a day (this is an undocumented limit). When this limit is
reached Google Drive produces a slightly different error message. When
this flag is set it causes these errors to be fatal.  These will stop
the in-progress sync.

Note that this detection is relying on error message strings which
Google don't document so it may break in the future.

See: https://github.com/rclone/rclone/issues/3857


- Config:      stop_on_upload_limit
- Env Var:     RCLONE_DRIVE_STOP_ON_UPLOAD_LIMIT
- Type:        bool
- Default:     false

**Closed by ncw** 2020-01-12 17:13 UTC

**Comment by lloydie11sky** [comment] 2020-01-13 08:21
Sounds very promising, can you confirm if their is a separate exit code for this, should we need to report on a mount that has reached it's upload limit?

Thanks,
