### ISSUE TITLE
pClound cleanup command error: login required (1000)

### ISSUE THREAD

**Issue by dhammel** [rclone/rclone#5625] opened 2021-09-25 00:23 UTC
When issuing the cleanup command for pCloud remote, it outputs error: 

2021/09/25 00:16:23 ERROR : Attempt 1/3 failed with 1 errors and: pcloud error: Log in required. (1000)
2021/09/25 00:16:23 ERROR : Attempt 2/3 failed with 1 errors and: pcloud error: Log in required. (1000)
2021/09/25 00:16:24 ERROR : Attempt 3/3 failed with 1 errors and: pcloud error: Log in required. (1000)
2021/09/25 00:16:24 Failed to cleanup: pcloud error: Log in required. (1000)

every other rclone command that i normally use sync as copy, move, sync and lsd/f commands work, so I am logged in properly.

Also, i had switched to using custom client ID and secret to see if that would help, but it didn't. 

If it matters, I have a premium account with pCloud.

Error occurs in version (on android via termux): 1.56.1-termux

Issue also occurs through a self-compiled binary on linux, can't recall its version at the moment.

Would this be a bug in termux, or maybe with pCloud's API? pCloud gives no support for its APIs, so might be hard to resolve if its on their end.

**Comment by FloGa** [comment] 2021-09-26 13:45
Seems to be an issue with pCloud's API, I cannot call this function even with `curl`:

    $ curl 'https://api.pcloud.com/trash_clear?access_token=<my_token>&folderid=0'
    {       
            "result": 1000,
            "error": "Log in required."
    }

The documentation seems not to be up-to-date, since they display an obviously wrong URL for the trash cleaning: https://docs.pcloud.com/methods/trash/trash_clear.html.

After further investigation: Not even `trash_list` works. Maybe the trash commands have been phased out of the public API?

**Comment by FloGa** [comment] 2021-09-26 13:53
Ah, just found an older bug in the list, so this one is a duplicate of #3853.

**Comment by ncw** [comment] 2021-10-01 10:47
Yes @FloGa - I think this is a duplicate.

I suggest you subscribe to the other issue.

Maybe you'd like to contribute a fix?

I'll close this one now.

**Closed by ncw** 2021-10-01 10:47 UTC
Labels: bug, duplicate, Remote: PCloud

**Comment by FloGa** [comment] 2021-10-01 14:38
@ncw
> Maybe you'd like to contribute a fix?

I'm afraid this is something that pCloud needs to come clean with. Their documentation is outdated and they obviously block calls to their trash methods for as long as the referenced bug exists (so for nearly 2 years now).

There is nothing we can do about this.
