### ISSUE TITLE
Ability to provide rclone with a specific date/time interval for it to run over

### ISSUE THREAD

**Issue by ShixAJ** [rclone/rclone#4211] opened 2020-05-08 12:32 UTC
Was wondering if its possible to tell rclone  to do and action only for objects created/modified from a certain date/time to a certain date/time.

Examples:
- Lets say I want to copy, I want to be able to tell rclone to copy everything from that source that has been created after May 1st 12am or something. Maybe if I only specify a day it assumes 12am.
- Rclone list me all files from date/time x to that date/time y

**Comment by darthShadow** [comment] 2020-05-08 13:16
`min-age` and `max-age` should help you.

**Comment by ShixAJ** [comment] 2020-05-08 20:05
I don’t find them very friendly. Having the ability to set a specific date instead of me calculating days would be better. Like lets say I did a backup day x I would remember that date or save it somewhere then when I want to do another backup I’d just input the date

**Comment by animosity22** [comment] 2020-05-09 22:22
You want to backup files from that changed from 4/20 to 4/30 only and not a snapshot of a day? Is that what you mean? So the flag take dates rather than using min / max age?

**Comment by ShixAJ** [comment] 2020-05-09 23:13
Yeah so instead of giving it min age 10 I want to give it 5/1/2020 (maybe if I don't say 2020 it assumes the current year) and time would help too but not necessary.

**Comment by animosity22** [comment] 2020-05-09 23:40
So you'd want the functionality of min-age and max-age but just the ability to pass a date.

**Comment by ShixAJ** [comment] 2020-05-09 23:56
Yeah.

**Comment by ncw** [comment] 2020-05-10 16:46
Internally `--min-age` and `--max-age` immediately get turned into dates so having them settable by dates doesn't seem unreasonable!

This could either be a special format for `--min-age` so you could say `--min-age 1d` or `--min-age 2007-01-01`?

Or maybe some different flags?

**Comment by darthShadow** [comment] 2020-05-10 17:30
Perhaps `--min-date` & `--max-date`?

**Comment by ShixAJ** [comment] 2020-05-11 06:49
Both options work, I guess go with whatever you see fit :D

**Comment by ncw** [comment] 2020-05-11 12:28
Have a go with this - does that work for you?

https://beta.rclone.org/branch/v1.51.0-303-gd455c36e-fix-4211-age-format-beta/ (uploaded in 15-30 mins)

Here is the docs

### `--max-age` - Don't transfer any file older than this ###

This option controls the maximum age of files to transfer.  Give in
seconds or with a suffix of:

  * `ms` - Milliseconds
  * `s` - Seconds
  * `m` - Minutes
  * `h` - Hours
  * `d` - Days
  * `w` - Weeks
  * `M` - Months
  * `y` - Years

For example `--max-age 2d` means no files older than 2 days will be
transferred.

This can also be an absolute time in one of these formats

- RFC3339 - eg "2006-01-02T15:04:05Z07:00"
- ISO8601 Date and time, local timezone - "2006-01-02T15:04:05"
- ISO8601 Date and time, local timezone - "2006-01-02 15:04:05"
- ISO8601 Date - "2006-01-02" (YYYY-MM-DD)

**Comment by ShixAJ** [comment] 2020-05-12 11:31
Seems to be working but in the opposite way of thinking. So when you set `rclone lsf remote: --min-age 2020-01-01` it lists everything before that date. Kinda counter-intuitive but works at least.

**Closed** 2020-05-12 16:52 UTC
Labels: enhancement, help wanted

**Comment by ncw** [comment] 2020-05-13 11:44
> Seems to be working but in the opposite way of thinking. So when you set `rclone lsf remote: --min-age 2020-01-01` it lists everything before that date. Kinda counter-intuitive but works at least.

Yes `--min-age` should really have been called `--older` - that would make more sense wouldn't it?

I think it is working as intended `--min-age 1d` means all files older than one day, so `--min-age 2020-01-01` means all files older than 2020-01-01.

**Comment by ShixAJ** [comment] 2020-05-13 13:36
Yep good enough :D
