### ISSUE TITLE
mail.ru.cloud oauth2 still fails

### ISSUE THREAD

**Issue by positron96** [rclone/rclone#6524] opened 2022-10-29 07:30 UTC
#### What is the problem you are having with rclone?

This is a continuation of https://github.com/rclone/rclone/issues/3988 as that one is closed and locked.

I am having that exact problem, I do not use F2A, the credentials are definitely correct (the config worked before).

I was able to capture the HTTP dump, see below. Basically the server complains that credentials are invalid. 

What's more, I cannot login via old Mail.ru Cloud Windows software (with the same error text). It was syncing well, but after I logged out, I cannot log back in. Have not tried Disk-O as I don't have it.

I hope that, like the original, the error is sporadic and will resolve by itself. Otherwise, it seems the server has changed (or stopped supporting "cloud-win" client_id) method of auth.
 
#### What is your rclone version (output from `rclone version`)

v1.51.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Win 10 x64

#### Which cloud storage system are you using? (e.g. Google Drive)

mailru

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone lsd mrc:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
C:\Users\positron\Downloads\Soft>rclone lsd mrc: --dump headers,bodies -vvv
2022/10/29 13:15:54 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "lsd" "mrc:" "--dump" "headers,bodies" "-vvv"]
2022/10/29 13:15:54 DEBUG : Using config file from "C:\\Users\\positron\\Downloads\\Soft\\rclone.conf"
2022/10/29 13:15:54 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2022/10/29 13:15:54 INFO  : []: Valid token not found, authorizing.
2022/10/29 13:15:54 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/10/29 13:15:54 DEBUG : HTTP REQUEST (req 0xc0000f4900)
2022/10/29 13:15:54 DEBUG : POST /token HTTP/1.1
Host: o2.mail.ru
User-Agent: rclone/v1.51.0
Content-Length: 91
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

client_id=cloud-win&grant_type=password&password=***&username=***%40mail.ru
2022/10/29 13:15:54 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/10/29 13:15:58 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/10/29 13:15:58 DEBUG : HTTP RESPONSE (req 0xc0000f4900)
2022/10/29 13:15:58 DEBUG : HTTP/2.0 200 OK
Content-Length: 111
Cache-Control: no-cache,no-store,must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Sat, 29 Oct 2022 07:15:57 GMT
Expires: Fri, 29 Oct 2021 07:15:56 GMT
Last-Modified: Sat, 29 Oct 2022 10:15:56 GMT
Pragma: no-cache
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: DENY
X-Host: fau43.m.smailru.net
X-Mru-Request-Id: f1efa4cb

{"error":"invalid username or password","error_code":3,"error_description":"username or password is incorrect"}
2022/10/29 13:15:58 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/10/29 13:15:58 Failed to create file system for "mrc:": Failed to authorize: oauth2: server response missing access_token

```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2022-10-29 12:43
I think this issue is a duplicate of #6398. I just noticed in the other issue someone posted a fix - can you give that a go? I've not tried it yet.

https://github.com/rclone/rclone/issues/6398#issuecomment-1293865600

**Comment by positron96** [comment] 2022-10-29 16:48
Hi @ncw . Yes, that workaround with creating an app password worked for me. It required to add a phone number to the account btw.

**Comment by ncw** [comment] 2022-10-29 22:47
Great - it works for me too.

I'll close this issue and use the other one as the master issue for the documentation fix.

**Closed by ncw** 2022-10-29 22:47 UTC
