### ISSUE TITLE
S3 object copy failed when object name contain "//"

### ISSUE THREAD

**Issue by TerrenceChina** [rclone/rclone#7253] opened 2023-08-28 03:50 UTC
#### What is the problem you are having with rclone?
object "thumb//objectxxx" can head,but can not download it to local disk with rclone

#### What is your rclone version (output from `rclone version`)
rclone v1.63.1
- os/version: centos 7.5.1804 (64 bit)
- os/kernel: 3.10.0-862.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.6
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Centos 7.5

#### Which cloud storage system are you using? (e.g. Google Drive)
AWS s3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
./rclone copy remote:mybucket/thumb//objectxxx ./ -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2023/08/28 11:44:29 DEBUG : rclone: Version "v1.63.1" starting with parameters ["./rclone" "copy" "remote:mybucket/thumb//objectxxx" "./" "-vv"]
2023/08/28 11:44:29 DEBUG : Creating backend with remote "remote:mybucket/thumb//objectxxx"
2023/08/28 11:44:29 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2023/08/28 11:44:29 DEBUG : name = "remote", root = "[lenovoboxbucket/thumb//000003cd07839f68e3f102fc90bf636c5a5d09e42ab60d04228c12a8f593f5a4](remote:mybucket/thumb//objectxxx)", opt = &s3.Options{Provider:"Other", EnvAuth:false, AccessKeyID:"akstring", SecretAccessKey:"skstring", Region:"", Endpoint:"http://mylocation", STSEndpoint:"", LocationConstraint:"", ACL:"", BucketACL:"", RequesterPays:false, ServerSideEncryption:"", SSEKMSKeyID:"", SSECustomerAlgorithm:"", SSECustomerKey:"", SSECustomerKeyBase64:"", SSECustomerKeyMD5:"", StorageClass:"", UploadCutoff:209715200, CopyCutoff:4999341932, ChunkSize:5242880, MaxUploadParts:10000, DisableChecksum:false, SharedCredentialsFile:"", Profile:"", SessionToken:"", UploadConcurrency:4, ForcePathStyle:true, V2Auth:false, UseAccelerateEndpoint:false, LeavePartsOnError:false, ListChunk:1000, ListVersion:0, ListURLEncode:fs.Tristate{Value:false, Valid:false}, NoCheckBucket:false, NoHead:false, NoHeadObject:false, Enc:0x0, MemoryPoolFlushTime:60000000000, MemoryPoolUseMmap:false, DisableHTTP2:false, DownloadURL:"", DirectoryMarkers:false, UseMultipartEtag:fs.Tristate{Value:false, Valid:false}, UsePresignedRequest:false, Versions:false, VersionAt:fs.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Decompress:false, MightGzip:fs.Tristate{Value:false, Valid:false}, UseAcceptEncodingGzip:fs.Tristate{Value:false, Valid:false}, NoSystemMetadata:false}
2023/08/28 11:44:29 DEBUG : Resolving service "s3" region "us-east-1"
2023/08/28 11:44:29 DEBUG : Creating backend with remote "./"
2023/08/28 11:44:29 DEBUG : fs cache: renaming cache item "./" to be canonical "/home/test"
2023/08/28 11:44:29 DEBUG : Local file system at /home/test: Waiting for checks to finish
2023/08/28 11:44:29 DEBUG : Local file system at /home/test: Waiting for transfers to finish
2023/08/28 11:44:29 INFO  : There was nothing to transfer
2023/08/28 11:44:29 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         0.1s

2023/08/28 11:44:29 DEBUG : 6 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2023-09-02 18:20
I think this is a duplicate of this issue: https://github.com/rclone/rclone/issues/5858

Please check it out @TerrenceChina

**Closed by ncw** 2023-09-02 18:20 UTC
