### ISSUE TITLE
--version shouldn't try to decrypt the config

### ISSUE THREAD

**Issue by SuperSandro2000** [rclone/rclone#5358] opened 2021-05-25 01:24 UTC
#### What is the problem you are having with rclone?

I was detecting the version of rclone via ``rclone --version`` but since one of the last updates it tries to decrypt password protected configs which broke my very easy detection before prompting any password.

#### What is your rclone version (output from `rclone version`)

1.55.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

``rclone --version | awk 'NR == 1 {print $2}'``

#### Workaround

I figured out that I could use ``HOME=/ rclone --version 2>/dev/null | awk 'NR == 1 {print $2}'`` to workaround this.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment] 2021-05-25 09:22
Thanks for reporting.

This should be fixed in next release: https://github.com/rclone/rclone/pull/5258

(Duplicate of : https://github.com/rclone/rclone/issues/5228)

**Closed by albertony** 2021-05-25 09:22 UTC
Labels: configuration, duplicate
