### ISSUE TITLE
build: don't make a beta when building a point release

### ISSUE THREAD

**Issue by stefangweichinger** [rclone/rclone#4789] opened 2020-11-20 18:00 UTC
The molecule tests in my ansible role fail right now when installing rclone beta version.

The latest rclone beta zip file contains a different version than https://beta.rclone.org/version.txt says.

Please see:

https://github.com/stefangweichinger/ansible-rclone/issues/66#issuecomment-731321368

**Comment by darthShadow** [comment] 2020-11-20 18:26
@ncw ?

**Comment by ncw** [comment] 2020-11-23 16:19
From the comment:

> currently there is a mismatch between https://beta.rclone.org/version.txt and https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
> 
> version.txt says : "1.54.0-beta.4903.211b08f77"
> 
> the zip-file contains : rclone-v1.53.3-linux-amd64

This is a known oddity in the build process for a point release, which overwrites the current beta.

As soon as another beta gets released it will get overwritten.

The Release process says this

  * make startstable
  * NB this overwrites the current beta so we need to do this
  * git co master
  * # cherry pick the changes to the changelog
  * git checkout ${BASE_TAG}-stable docs/content/changelog.md
  * git commit -a -v -m "Changelog updates from Version ${NEW_TAG}"
  * git push

So that push obviously didn't work - I wonder whether the point release build was still in progress.

It should be fixed in a moment though.

So in a perfect world we need to stop the build of the point release making a beta, so I'll update the title of this issue to reflect that.

**Comment by stefangweichinger** [comment] 2020-11-23 17:27
Thanks @ncw for the check and the explanation.
Right now it's fixed, my molecule tests run through.

I plan to add some new code to the ansible role as prepared in https://github.com/stefangweichinger/ansible-rclone/pull/67
It contains a check step: is the content of the archive the same as the requested version ... ?

Sure, as long as the described oddity exists, things might fail now and then.
As far as I understand I can only write some informative error message and/or maybe some FAQ to catch this?

Thanks for now, regards, Stefan

**Comment by ncw** [comment] 2020-11-24 17:57
> Thanks @ncw for the check and the explanation.
> Right now it's fixed, my molecule tests run through.

Great

You aren't the first person to notice this, so I really need to fix this properly.

In the Makefile

https://github.com/rclone/rclone/blob/7078311a844fe7a12b66ff6e632065d20b48b7d2/Makefile#L214-L221

What we need to do is when making the point release (or any release on the stable branch for that matter), don't do the things in the `ifndef BRANCH_PATH` section.

In fact if `RELEASE_TAG` is set we are building a release and if we update the current beta then I think that would be appropriate.

So I think the if statement needs to be something like `if BRANCH_PATH == "" && RELEASE_TAG==""` which in Makefile speak is something like

```Makefile
ifeq ($(and $(BRANCH_PATH),$(RELEASE_TAG)),)
```

This will stop making betas for .0 releases as well as .1 releases but I think that is OK.

I'll give that a go shortly...

**Comment by stefangweichinger** [comment] 2020-11-25 08:45
> So I think the if statement needs to be something like `if BRANCH_PATH == "" && RELEASE_TAG==""` which in Makefile speak is something like
> 
> ```makefile
> ifeq ($(and $(BRANCH_PATH),$(RELEASE_TAG)),)
> ```
> 
> This will stop making betas for .0 releases as well as .1 releases but I think that is OK.
> 
> I'll give that a go shortly...

I would like to be helpful here but unfortunately I am not a Makefile guru at all ;-)
Looking forward to your progress here. If you solve it this avoids that edge case and I don't have to cover that in the ansible role.

**Comment by ncw** [comment] 2020-11-25 10:01
> I would like to be helpful here but unfortunately I am not a Makefile guru at all ;-)

I don't think anyone ever sets out to be Makefile guru!

I got the above wrong it should be `ifeq ($(or $(BRANCH_PATH),$(RELEASE_TAG)),)` - come back [DeMorgan](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) all is forgiven!

> Looking forward to your progress here. If you solve it this avoids that edge case and I don't have to cover that in the ansible role.

Yes, my intention is to fix this once and for all! I've tested it as well as I can and it should work, but we don't know for certain until the next point release :-)

**Comment by stefangweichinger** [comment] 2020-11-25 10:09
Nice, looks promising. There might be some gh magic to link this issue to such a release step, as a reminder or so.

Aside from that, and way more general: any suggestions what the ansible role might do or support? Sure, another topic/issue.

**Comment by ncw** [comment] 2020-11-25 11:26
> Nice, looks promising. There might be some gh magic to link this issue to such a release step, as a reminder or so.

I'll put it on the release milestone...
 
> Aside from that, and way more general: any suggestions what the ansible role might do or support? Sure, another topic/issue.

I'm not sure what you mean here?

**Comment by stefangweichinger** [comment] 2020-11-25 11:34
> > Nice, looks promising. There might be some gh magic to link this issue to such a release step, as a reminder or so.
> 
> I'll put it on the release milestone...

great

> > Aside from that, and way more general: any suggestions what the ansible role might do or support? Sure, another topic/issue.
> 
> I'm not sure what you mean here?

I mean: do you have any ideas/wishes/suggestions what the ansible-role https://github.com/stefangweichinger/ansible-rclone might do better? Additional things to check or test, files to install, whatever .. You are the one knowing what `rclone` needs to be happy ;-)

OK? Maybe this should go into an issue in the role repo.

**Comment by ncw** [comment] 2020-11-25 12:53
> I mean: do you have any ideas/wishes/suggestions what the ansible-role https://github.com/stefangweichinger/ansible-rclone might do better? Additional things to check or test, files to install, whatever .. You are the one knowing what `rclone` needs to be happy ;-)

I had a quick look at the code. I've used ansible a small amount in the past so it made some sort of sense.

It is possible for the `version.txt` and the zip files to get out of sync as you've seen. This issue fixes one of them but it has happened before. There is only ever one directory in the .zip file and that will always have the correct version and arch, so you could update the variables from listing that directory, or just assume that there will always be only one directory.

As for other things, you've installed the man page so that is about it I think! Rclone was designed to not need too much installation.

One thought - since your ansible role is the most popular - we could make it an official part of rclone and move it under the `rclone` organisation. If you think that is interesting then I can explain more, but I totally understand if you want to have it in your own GitHub.

Thanks for maintaining the ansible role :-)

**Comment by stefangweichinger** [comment] 2020-11-25 14:40
1. Ad directories unzipped: I now added a task that removes the temporary directory at each run:
https://github.com/stefangweichinger/ansible-rclone/commit/40ef4cf490ac3be232035799cd99428fb755065d

That helps to avoid having multiple historic subdirs in the temp dir and not being able to compare the version you want to install with the extracted archive. Sure, download everytime, but I think that's OK for now.

You refer to this logic, I assume: right now the role reads that text file from above and fetches the according zip.
You suggest to just download `rclone-current-$xyz.zip` and just see what's in there, right?
Yes, worth a thought.

2. move to `rclone` organization: why not, sounds great ... maybe more co-work there and more eyes reviewing the changes.
The role name on ansible galaxy would change then, this leads to issues for users, I assume.

**Comment by ncw** [comment] 2020-11-25 22:04
> 1. Ad directories unzipped: I now added a task that removes the temporary directory at each run:
>    [stefangweichinger/ansible-rclone@40ef4cf](https://github.com/stefangweichinger/ansible-rclone/commit/40ef4cf490ac3be232035799cd99428fb755065d)

:-)

> That helps to avoid having multiple historic subdirs in the temp dir and not being able to compare the version you want to install with the extracted archive. Sure, download everytime, but I think that's OK for now.
> 
> You refer to this logic, I assume: right now the role reads that text file from above and fetches the according zip.
> You suggest to just download `rclone-current-$xyz.zip` and just see what's in there, right?

Yes, that is what I was thinking.

> Yes, worth a thought.
> 
> 1. move to `rclone` organization: why not, sounds great ... maybe more co-work there and more eyes reviewing the changes.
>    The role name on ansible galaxy would change then, this leads to issues for users, I assume.

I moved rclone/rclone from https://github.com/ncw/rclone and you'll see that if you go there then GitHub redirects everything. The move is pretty seamless, moving the history, issues, code, wiki etc and redirecting where appropriate.

Can you find out if ansible galaxy would follow a redirect?

**Comment by stefangweichinger** [comment] 2020-11-26 08:42
It's your repo here, but shouldn't we discuss this in a new issue?

I don't find anything particular around galaxy redirects, maybe I should ask someone on IRC or file an issue somewhere.

https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names  is interesting, as it seems to explain some issues I had with the name of the role.

https://github.com/stefangweichinger/ansible-rclone/blob/master/meta/main.yml does not set `role_name`

As mentioned in https://github.com/stefangweichinger/ansible-rclone#troubleshooting we already had troubles because somehow someday galaxy changed the name scheme. This isn't exactly what we need to know now but somehow related and to keep in mind. Maybe setting `role_name` would help to get some kind of "alias" or "handle"  ...

**Comment by ncw** [comment] 2020-11-26 10:28
I made a new issue about this here: https://github.com/rclone/rclone/issues/4809 I'll carry on the discussion there.

**Comment by ncw** [comment] 2021-01-28 14:22
This was fixed with 1ce0b4596588d4cef42d264b0f35ba66f7a1dff4

**Closed by ncw** 2021-01-28 14:22 UTC
Labels: IMPORTANT, bug, build, maintenance
