### ISSUE TITLE
Rclone starting two processes 

### ISSUE THREAD

**Issue by daniele-spl** [rclone/rclone#5513] opened 2021-08-05 12:43 UTC
#### What is the problem you are having with rclone?
Rclone is starting an additional process of itself. I am not sure if its only related to mount but it does not happen with older versions.
I updated from 1.53.4 without any change in the starting configuration and the process is starting another process. 
You can see that in the failing remote control, cause the first process already assigned the port. When the "--rc" flag is removed, the process starts but 2 times. The first one creates a child with exactly the same parameters as the first one.

Installed version 1.55.1 without any changes in the parameters and its working properly.

So something changed in 1.56.0 

#### What is your rclone version (output from `rclone version`)
1.56.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
SLES 12

#### Which cloud storage system are you using? (e.g. Google Drive)
AzureBlob

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
/usr/bin/rclone" "mount" "??" "??" "--daemon" "--rc" "--cache-dir" "/mnt/resource/rclonecache" "--dir-cache-time" "24h" "--vfs-write-back" "5s" "--vfs-cache-mode" "full" "--transfers=8" "--azureblob-upload-cutoff" "64m" "--azureblob-chunk-size" "16m" "--azureblob-memory-pool-use-mmap=true" "--checksum" "--vfs-read-chunk-size" "16m" "--vfs-read-chunk-size-limit" "500m" "--multi-thread-cutoff=64m" "--multi-thread-streams=8"  "--vfs-cache-max-age" "168h" "--vfs-cache-max-size" "900g" " "--allow-other" "--allow-non-empty" "--use-mmap" "--log-level" "DEBUG" "--buffer-size" "1"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2021/08/05 13:06:18 NOTICE: Serving remote control on http://localhost:5572/
2021/08/05 13:06:18 Failed to start remote control: start server failed: listen tcp 127.0.0.1:5572: bind: address already in use

Just let me know if I can do some more testing.

**Comment by animosity22** [comment] 2021-08-09 20:55
This is a duplicate of another issue.

https://github.com/rclone/rclone/issues/5472

Check the beta and validate it.

Thanks.

**Closed by animosity22** 2021-08-09 20:55 UTC

**Comment by daniele-spl** [comment] 2021-08-11 14:44
I would like to do so, but https://beta.rclone.org/ does not let me download any new beta and I am not aware where else to find the correct beta with that fix.

**Comment by animosity22** [comment] 2021-08-11 16:36
Not sure what you mean as that page returns all the betas.

Just pick the latest beta for your OS.

![image](https://user-images.githubusercontent.com/5088712/129068291-68b23562-929f-4485-835e-fea5f895f596.png)

**Comment by ncw** [comment] 2021-08-13 16:38
Is beta.rclone.org working for you now @daniele-spl ? I've had a few reports of it not working for people but it seems OK to me both on IPv4 and IPv6.

**Comment by daniele-spl** [comment] 2021-08-17 13:50
> Is beta.rclone.org working for you now @daniele-spl ? I've had a few reports of it not working for people but it seems OK to me both on IPv4 and IPv6.

Yes it is. Thx! It was just that day. The next day it was working as usual.

With the newest Beta I can also confirm that this bug is fixed. Thanks for the help. Waiting for the next release...
