### ISSUE TITLE
Unable to create API key for Jottacloud

### ISSUE THREAD

**Issue by generiskk** [rclone/rclone#3171] opened 2019-05-06 09:24 UTC
#### What is the problem you are having with rclone?

Error when trying to creating machine specific API key for Jottacloud
2019/05/06 11:15:04 Failed to get resource token: HTTP error 400 (400 Bad Request) returned body: "{\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant (e.g., authorization code, resource owner credentials)
or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}"

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0-031-gb68c3ce7-beta
- os/arch: windows/amd64
- go version: go1.12.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/05/06 11:22:10 Failed to get resource token: HTTP error 400 (400 Bad Request) returned body: "{\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant (e.g., authorization code, resource owner credentials)
or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}"

**Comment by ncw** [comment] 2019-05-12 19:38
Any thoughts on this @buengese ?

**Comment by buengese** [comment] 2019-05-14 15:28
Sorry I didn't see this issue earlier but I've been quite busy however I've not been able to reproduce this. I can configure Jottacloud just fine both with and without creating a machine specific key. Could you please describe the exact steps you took and provide the entire output during the configuration while running with the the `-vv` flag?

**Comment by tlystad24** [comment] 2019-05-14 16:22
Make sure you enter your Jottacloud username/email. I had the same issue when I forgot to.
```
Storage> 14
** See help for jottacloud backend at: https://rclone.org/jottacloud/ **

User Name:
Enter a string value. Press Enter for the default ("").
user>your@jottacloud.email
```

**Comment by CHRONiCiTY** [comment] 2019-05-19 13:36
I'm actually having this same issue.
I already have a working config file from an earlier version of rclone so the username is definitely correct there but when I run rclone config, go through the steps in the JC entry and select to create a machine specific key I'm greeted with the same message as OP:

2019/05/19 15:33:56 Failed to get resource token: HTTP error 400 (400 Bad Request) returned body: "{\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}"

**Comment by CHRONiCiTY** [comment] 2019-05-19 13:45
I'm actually greeted by this same message in 1.47 but not when creating the remote but when using it. I usually have several instances of rclone running on the machine, some for mounts, some syncing and whatnot.
Sooner or later however all or some of them will stop working and the logs are littered with the error message in the OP. The only way to solve it is to create another machine key.
Since that's not really usable in the long run, I'm still stuck running rclone 1.45 which works but are sadly missing some features added in the newer versions.

**Comment by buengese** [comment] 2019-05-19 15:15
That sounds like there might be some limititations to the number of devices that can be used. @CHRONiCiTY could you describe you setup with a little more detail. How many instances of rclone are you running and are all of them registered with a different device id, Do any of them use rclone's inbuilt device. 

Also if anyone can consistently reproduce this during config can you please run config with `-dump responses` or `-dump bodies` as decribed here: https://rclone.org/docs/#developer-options. But please be careful to not leak any sensitive information. 

@CHRONiCiTY In theory it would be possible to bring back some of the old API but it has it's own limitations. And we don't know how much longer it will be supported.

**Comment by CHRONiCiTY** [comment] 2019-05-19 15:27
I have two JC accounts but they have their separate remote entries in the config so they are using separate device id's.
I use one union mount merging both JC remotes with the local filesystem. The two remotes are also mounted separately in their own folder on the filesystem.
Other than that I have some sync jobs running a couple of times a day for both remotes. All this is done on only one machine though, so I don't have rclone running on any other computer.

**Comment by buengese** [comment] 2019-05-19 16:36
I really cannot think of any reason why a reboot should have any effect on this.

**Comment by dbond007** [comment] 2019-07-21 14:42
This happens to me, but appears to be due to the renewal of the token. You can setup the remote, it will work fine, after 1-2 hours (how long the token lasts) you will start getting this error. Going in and manually renewing / creating a new api key in rclone will allow it to work for another 1-2 hours.

**Comment by lunderhage** [comment] 2019-08-14 08:16
I have a similar problem:
I create a new jottacloud remote, enter the username/password and the two factor auth code, but still:
bash-4.4# rclone ls jottacloud:/
2019/08/14 08:09:46 Failed to create file system for "jottacloud:/": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: Token mismatch! (Unauthorized)

Rclone version:
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

**Comment by buengese** [comment] 2019-08-14 08:55
This was another issue this has been fixed in the latest beta available here [https://beta.rclone.org/](https://beta.rclone.org/). I'm closing this issue now too because it was never successfully reproduced and has probably been resolved by now.

**Closed by buengese** 2019-08-14 08:55 UTC
Labels: Remote: Jottacloud, can't reproduce
