### ISSUE TITLE
GDrive: option in copy/sync to convert duplicate file names

### ISSUE THREAD

**Issue by ulion** [rclone/rclone#470] opened 2016-05-05 20:42 UTC
Hi, I'm planning to use rclone to backup files from google drive to aws s3. as you know, google drive can have files on with same name in the same folder, which cause problem: #119 

I'd like to backup all of them, and distinguish files with same name with their original fileId on google directory. so, is it possible rclone support to store the original fileId into s3 as some metadata, or part of the filename, so when doing the sync, rclone knows clearly which file on google drive should be copied to which path of s3?

Btw, does rclone support copy files from google drive's trash folder as source?

**Update [2020]** (ivandeex):
1. Copying from trash has been implemented
2. This request is about _copy/sync_ particularly for cases when _dedupe_ is not possible.

**Comment by ncw** [comment] 2016-05-06 12:42
You can use the `rclone dedupe` command to de-duplicate your drive first.  See the relevant section in [the docs](http://rclone.org/docs/).  This can rename the duplicate file names to be different then then will copy to S3 just fine.

Is that helpful?

rclone doesn't support copying files from the trash at the moment, but if you restore it, then it can copy them.

**Comment by ulion** [comment] 2016-05-06 22:16
Thank you for the answers.

That apply but not quite fit for my usage, I can not dedupe or change
google drive side files, we just do the backup from trash.

As the trash, shouldn't it just be a special folder of the drive, with
certain id to identify the trash folder? or it require some special search
and check to identify those trashed files?

2016-05-06 20:42 GMT+08:00 Nick Craig-Wood <notifications@github.com>:

> You can use the rclone dedupe command to de-duplicate your drive first.
> See the relevant section in the docs <http://rclone.org/docs/>. This can
> rename the duplicate file names to be different then then will copy to S3
> just fine.
>
> Is that helpful?
>
> rclone doesn't support copying files from the trash at the moment, but if
> you restore it, then it can copy them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/470#issuecomment-217429049>
>



-- 
Ulion

**Comment by ncw** [comment] 2016-05-07 08:42
It would be relatively easy to make rclone look in the trash too, in drive/drive.go you'd just change this to true

```
	query := fmt.Sprintf("trashed=false")
```

On a flag would be best, eg `--drive-trash-only`

Then you would pass a flag `rclone --drive-trash-only copy drive: /blah` to copy stuff out the trash.

Fancy having a go at that?

**Comment by ulion** [comment] 2016-05-07 12:12
Thank you and this is great. the only thing left is the same name multiple
files copy problem.

2016-05-07 16:42 GMT+08:00 Nick Craig-Wood <notifications@github.com>:

> It would be relatively easy to make rclone look in the trash too, in
> drive/drive.go you'd just change this to true
>
>     query := fmt.Sprintf("trashed=false")
>
> On a flag would be best, eg --drive-trash-only
>
> Then you would pass a flag rclone --drive-trash-only copy drive: /blah to
> copy stuff out the trash.
>
> Fancy having a go at that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/470#issuecomment-217620517>
>



-- 
Ulion

**Comment by ivandeex** [comment] 2020-11-16 20:11
@ncw
As the `--drive-trash-only` has been long implemented, I suggest clising this issue.

**Comment by ulion** [comment] 2020-11-17 04:02
> @ulion @ncw
> As the `--drive-trash-only` has been implemented long ago, I suggest closing this issue.

This issue was created long time ago, but as I can see, as the issue title described, the main issue is about whether rclone can auto name and map source duplicate-name files to target different name files, and this main issue is still not resolved, right?

**Comment by ivandeex** [comment] 2020-11-18 14:02
@ulion You are right. Updating issue name and description.

**Comment by ulion** [comment] 2020-11-19 01:24
> @ulion You are right. Updating issue title and description.

you are welcome. hope this can be resolved some day :)

**Comment by ivandeex** [comment] 2020-11-22 13:28
Almost duplicate of https://github.com/rclone/rclone/issues/4412

**Comment by ivandeex** [comment] 2020-11-22 13:29
Duplicate of https://github.com/rclone/rclone/issues/4412

**Comment by ivandeex** [comment] 2021-02-14 01:38
@ulion 

> This issue was created long time ago, but the main issue is about whether rclone can auto name and map source duplicate-name files to target different name files, and this main issue is still not resolved, right?

Not resolved yet, but as I just found, we have another ticket #4412 where people not only formulate the desire to have the feature but also discuss some concrete methods of implementing it.

Having several tickets requesting the same won't speed things up anyway. This will be implemented when someone finds time.

I suggest that you subscribe to #4412
Thank you

**Comment by ivandeex** [comment] 2021-03-15 22:37
Closing in favor of more complete ticket #4412

**Closed by ivandeex** 2021-03-15 22:37 UTC
Labels: Remote: Drive, duplicate, new feature, versioning, waiting for reply...
