### ISSUE TITLE
OneDrive for Business uses 2x the space

### ISSUE THREAD

**Issue by Steini1984** [rclone/rclone#1716] opened 2017-10-05 09:31 UTC
When uploading to onedrive for business two versions of every file are created. That means that for every 1MB of backups 2MB of storage is used. 

This was tested on the latest 1.38 beta on Linux and 1.38 stable on Windows and Linux.

Here you can see that the used space is double the size of the file:

![image1](https://user-images.githubusercontent.com/5666926/31220299-86d32642-a9af-11e7-9a8a-be8fa64886c4.jpg)

And here you can see the culprit, two versions of the same file from the same upload:

![image2](https://user-images.githubusercontent.com/5666926/31220298-86d2bd56-a9af-11e7-999c-7090dfd5d90f.jpg)

More info:
[https://forum.rclone.org/t/onedrive-for-business-uses-2x-the-space/3971/8](url)

**Comment by ncw** [comment] 2017-10-05 16:56
I've managed to replicate this.  And it doesn't happen with onedrive, only onedrive for business.

@olihey Do you have any ideas?  I'm thinking this might actually be a bug in onedrive for business, but maybe you can see something rclone is doing that I can't!.

Here is the [resumable file upload API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession) that rclone is using.

**Comment by olihey** [comment] 2017-10-07 09:58
It's the SetModTime after the upload has finished. Apparently OneDrive for Business will create a new version for the item then. You can see that, because 1.0 is always the time one uploaded the file and 2.0 the actual modtime of the original.

@ncw We could "maybe" send the modtime when creating the upload session as part of the request instead of uploading and then setting the modtime, see here: [https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession#create-an-upload-session](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession#create-an-upload-session) ?

**Comment by olihey** [comment] 2017-10-07 10:55
Nope, does not work.
I just did a quick hack and it still creates two versions 😞 
```2017/10/07 12:29:14 DEBUG : HTTP REQUEST (req 0xc04207a300)
2017/10/07 12:29:14 DEBUG : POST /_api/v2.0/drives/me/root:/TESTFILE:/upload.createSession HTTP/1.1
Host: raygina-my.sharepoint.com
User-Agent: rclone/v1.38
Content-Length: 116
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"item":{"fileSystemInfo":{"createdDateTime":"2017-10-07T09:08:24Z","lastModifiedDateTime":"2017-10-07T09:08:24Z"}}}```

**Comment by ncw** [comment] 2017-10-07 12:38
Did putting the modtime in the upload session work? That means we can lose an http transaction so that is a win even if it doesn't fix the problem.

**Comment by olihey** [comment] 2017-10-07 13:21
Yes, that actually worked. Although I haven't tested it very much.

**Comment by ndbeals** [comment] 2017-10-10 17:28
How can I as a user implement the workaround/fix @ncw mentioned two posts ago?

I'm trying to sync a few hundred gigabytes to OD, having 2X the used space isn't good haha. 

Thanks in advance.

**Comment by olihey** [comment] 2017-10-10 17:44
Well, there is no workaround at the moment.
Rclone uploads the file to OneDrive for Business and afterwards sets the modification time to the modification time of the local file. Unfortunately OneDrive for Business (but NOT OneDrive Personal) creates a new version for the change of the modification time.

I haven't found a solution to prevent this, even sending the modification time together with the file also resulted into 2 versions.

I currently see only two options.
1. Disable setting the modification time after upload, so the file will have the time of the upload as modification time in OneDrive for Business
2. Talk to Microsoft about the issue.

**Comment by ncw** [comment] 2017-10-10 18:23
Can you make your patch to set the modtime as part of the upload session available? I'd like to have a play with it before reporting the issue to Microsoft.

**Comment by Weropol** [comment] 2017-10-16 16:10
I tried setting `--no-update-modtime` and other combinations of flags in rclone, but still experienced duplicate versioning.  However, I did find a workaround to prevent it:

1. Open the settings menu by clicking on the gear symbol at the top of the OneDrive Business page.
1. Click **Site settings**.
1. Once on the Site settings page, navigate to **Site Administration > Site libraries and lists**.
1. Click **Customize "Documents"**.
1. Click **General Settings > Versioning Settings**.
1. Under **Document Version History** select the option **No versioning**.
- Note:  This will disable the creation of new file versions, but will not remove any previous versions. Your documents are safe.
7. Apply the changes by clicking **OK**.
7. Use rclone to upload or modify files.  (I also use the `--no-update-modtime` flag)
7. Restore the versioning settings after using rclone. (Optional)

I hope that this helps some users.  Also, my many thanks to @ncw and @olihey for implementing Business support. You rock!

**Comment by reticentnz** [comment] 2017-10-20 15:30
Hi @Weropol, 

Thanks for finding that - happy to turn versioning off on my account. Will this need to be retrospectively fixed, ie delete all of those duplicate files or will that setting trash any of the old versions automatically?

Cheers

**Comment by Weropol** [comment] 2017-10-24 16:42
@reticentnz, no previous versions are removed, so you will have to delete them manually from **Storage Metrics** in the site settings, or use rclone to transfer the files out and then back into OneDrive again.

**Comment by Arjoni** [comment] 2017-12-28 13:29
Any new information about this issue?

**Comment by ncw** [comment] 2018-01-05 15:21
@Weropol other than turning off versioning we don't have a fix for this yet

**Comment by olihey** [comment] 2018-01-24 08:02
There is now an issue opened on the offical OneDrive API github repo. Seems like other users are having the exact same issue.
[https://github.com/OneDrive/onedrive-api-docs/issues/778](https://github.com/OneDrive/onedrive-api-docs/issues/778)

**Comment by olihey** [comment] 2018-03-06 10:47
So, Microsoft has fixed the issue in there API. But there is some work left for rclone.
Basically we need to remove the `--onedrive-upload-cutoff` option at all and create chunked uploads even for small files.
@ncw This should be fine as the amount of requests should be the same for small file. Before we did a PUT and then a PATCH to fix the file date, now we do the POST for the createSession with submitting the file date and then PUT the file content. So, two request either way 😃
@ncw Would it be okay to do this fix in my Microsoft Graph branch only and then switch the onedrive backend to Microsoft Graph?

**Comment by ncw** [comment] 2018-03-06 11:50
> So, Microsoft has fixed the issue in there AP

:-)

> But there is some work left for rclone. Basically we need to remove the --onedrive-upload-cutoff option at all and create chunked uploads even for small files. This should be fine as the amount of requests should be the same for small file. Before we did a PUT and then a PATCH to fix the file date, now we do the POST for the createSession with submitting the file date and then PUT the file content. So, two request either way ￼

Sounds like an excellent plan!

> Would it be okay to do this fix in my Microsoft Graph branch only and then switch the onedrive backend to Microsoft Graph?

Is Microsoft Graph working well enough?  I know you had some concerns about it.

If you think it is ready for the big time, then yes let's merge it and do this work on top of that.

Bear in mind that I'd like to make a release in about 10 days, and we need a bit of time for stuff to settle.  It might be that we postpone the merge of the Microsoft Graph branch until after v1.40 is released - what do you think?

If this fix misses v1.40 then it will be in a beta shortly after which would be acceptable to me, especially since this is only affecting the quota on small files now.

**Comment by olihey** [comment] 2018-03-06 15:07
Hm.... I don't think I have to time for the Microsoft Graph stuff before the 1.40. So I guess I do the `--onedrive-upload-cutoff` removal only.

**Comment by ncw** [comment] 2018-03-07 15:03
@olihey sounds like a plan!

**Comment by olihey** [comment] 2018-03-09 08:32
@ncw I have a problem with the fix. It's working beautifully for upload but the Copy method is failing in the Test. Problem is, that the Copy action from OneDrive uses the current time for the modTime of the destination file and there is no way to set the date as part of the call to [/copy](https://docs.microsoft.com/onedrive/developer/rest-api/api/driveitem_copy).
Setting the date afterwards using a PATCH call would again result in 2 versions.

So, I am a bit stuck currently:
![image](https://user-images.githubusercontent.com/372454/37197826-8425c2dc-237c-11e8-8419-c5f93830fe98.png)

**Comment by ncw** [comment] 2018-03-10 13:25
I think the copy is a niche action compared to the main problem in this issue, so I'd suggest seeing the modtime in copy which will create the two versions problem. What do you think? We could document the problem.

**Comment by ivandeex** [comment] 2020-11-15 12:19
@ncw @Steini1984 @olihey @Weropol 

This similar issue was discussed in https://github.com/rclone/rclone/issues/4106 (clean up onedrive versions, fixed) and fixed by commits:
- (implement cleanup) https://github.com/rclone/rclone/commit/97d8530edb217b909ce3d9bcc79508b62f319d40
- (add `--onedrive-no-versions`) https://github.com/rclone/rclone/commit/b401a727f761a5bbb94742b0b37683be81d58e25

I suggest closing this issue.

**Comment by ivandeex** [comment] 2021-02-09 15:22
@Steini1984 Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment] 2021-03-12 14:25
Closing stale tickets

**Closed by ivandeex** 2021-03-12 14:25 UTC
Labels: Remote: One Drive, bug, needs retest, versioning, waiting for reply...
