### ISSUE TITLE
Excessively Long ReadDirAll Listings

### ISSUE THREAD

**Issue by phillibert** [rclone/rclone#2255] opened 2018-04-15 20:22 UTC
#### What is the problem you are having with rclone?
I have an rclone mount with a directory that contains ~3500 child directories. After clearing any caches (through HUP’ing, using vfs/expire and/or cache/forget), a directory listing can take upwards of 6 minutes due to what looks a ReadDirAll operation listing all the child objects and then iterating through each one. This causes many applications to lock up.

#### What is your rclone version (eg output from `rclone -V`)
```
2018/04/15 13:09:36 DEBUG : rclone: Version "v1.40-084-g3d5106e5β" starting with parameters ["/usr/bin/rclone" "--verbose=2" "--version"]
rclone v1.40-084-g3d5106e5β
- os/arch: linux/amd64
- go version: go1.10.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
```
Linux DEBIAN 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux
```

####  Which cloud storage system are you using? (eg Google Drive)
( ( ( Google Drive ) Cache ) Crypt )

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone mount "${MOUNT_NAME}:" "${MOUNT_DIR}" \
--allow-other \
--default-permissions \
--buffer-size=0 \
--vfs-cache-mode=writes \
--cache-tmp-upload-path="${TMP_UPLOAD_DIR}" \
--rc \
;
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
I can produce the results reliably and have a verbose log saved. This is a trimmed version that shows the problem behavior. Further details can be found in a [post on the rclone forums](https://forum.rclone.org/t/readdirall-long-directory-listings-and-blocked-for-more-than-120-seconds/5373).
```
Apr 13 08:32:14 DEBIAN rclone[2478]: 2018/04/13 08:32:14 DEBUG : Google drive root 'Crypt': Checking for changes on remote
Apr 13 08:32:14 DEBIAN rclone[2478]: 2018/04/13 08:32:14 DEBUG : Google drive root 'Crypt': All changes were processed. Waiting for more.
...
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : LargeDir/: Attr:
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : LargeDir/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : LargeDir/: ReadDirAll:
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : Cache remote gdcache:Crypt: list 'qtven3b8rorak2le5h4htl55hg'
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : qtven3b8rorak2le5h4htl55hg: list: empty listing
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : qtven3b8rorak2le5h4htl55hg: list: read 0 from temp fs
Apr 13 08:36:30 DEBIAN rclone[2478]: 2018/04/13 08:36:30 DEBUG : qtven3b8rorak2le5h4htl55hg: list: temp fs entries: []
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: read 3459 from source
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: source entries: [qtven3b8rorak2le5h4htl55hg/b6vn27vu5urb7au8tomnoc64imkuakarig76j2ddpdfuptl9r2069ig5kg5tr0hmna48jou55s6g6 ... (all 3459 child objects) ... qtven3b8rorak2le5h4htl55hg/1204r646g3jbip7ephi7mafur9rgjto21of5c6oel0pvh3r89ci0]
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/b6vn27vu5urb7au8tomnoc64imkuakarig76j2ddpdfuptl9r2069ig5kg5tr0hmna48jou55s6g6
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/mv1ulr1ufefmptnbqqmkdeflvt1ipvt993jvpq0o594468vepl80
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/mvq7nt41712f80n36b7d5ubf208gnf0kvcipgtmpemu98l1ad1eg
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/pmavqc3r65287kljfnr0jruprq9aao88m0p4u28v62m47ms2m8lo1n7ro1t8stpbe6q2ek75038fo
Apr 13 08:37:00 DEBIAN rclone[2478]: 2018/04/13 08:37:00 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/0k05d82ui3tbna419ifu9jpa9c
...
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/hb3f880eoshg3qfvbdptueplvuisrqe012t3274s26s92tm14avg
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/r19ahrq1pp4si5trvsb6scktt1tdgtd2kcs609dmtl2pil5pi53g
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: qtven3b8rorak2le5h4htl55hg/1204r646g3jbip7ephi7mafur9rgjto21of5c6oel0pvh3r89ci0
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : qtven3b8rorak2le5h4htl55hg: list: cached dir: 'Crypt/qtven3b8rorak2le5h4htl55hg', cache ts: 2018-04-13 08:38:04.765211873 -0700 PDT m=+352.418024454
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : LargeDir/: >ReadDirAll: item=3459, err=<nil>
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : /: Attr:
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : /: Lookup: name="LargeDir"
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : /: >Lookup: node=LargeDir/, err=<nil>
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : LargeDir/: Attr:
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : LargeDir/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : /: Lookup: name="LargeDir"
Apr 13 08:38:04 DEBIAN rclone[2478]: 2018/04/13 08:38:04 DEBUG : /: >Lookup: node=LargeDir/, err=<nil>
```

**Comment by ncw** [comment] 2018-04-16 07:36
@remusb what this looks like to me is that when `mount` asks the cache for a directory listing, cache lists the directory **and** all the subdirectories.

You can see it is doing that from the log above by the placement of the `LargeDir/: ReadDirAll:` and the `LargeDir/: >ReadDirAll: item=3459, err=<nil>` logs.

For this very large directory with ~3500 entries in, this is causing the directory listing to take > 120s which is making kernel warnings etc.

I guess this will only be a problem for very large directories.

Is my analysis correct?  Can we fix it?

**Comment by remusb** [comment] 2018-05-12 09:38
Hi @phillibert 

Just to understand, what exactly triggers the read of all the child directories? A simple read of the root directory? /
Cache shouldn't do that.

**Comment by phillibert** [comment] 2018-05-13 01:26
I consistently reproduced it by unmounting, deleting the cache dir (containing cache.db, data, and vfs subdirectory), remounting, and then running an ```ls```.

**Comment by remusb** [comment] 2018-06-03 10:59
Ok, I think I found the issue (sorry for the delay by the way).

Every folder is checked in the persistent db (read lock) and then every new or expired one is written in the cache (write lock). These should be batched really. I'll give it a try and push it.

**Comment by remusb** [comment] 2018-06-04 18:44
@phillibert 
Here's a beta that should improve the performance (I will avoid fix it until I put up some synthetic tests for this): https://beta.rclone.org/v1.41-084-g8a849759/

**Comment by remusb** [comment] 2018-06-11 07:43
I can't seem to reproduce this with `mount`.
I got something like this:
```
=== RUN   TestInternalListLargeDirectory
2018/06/10 23:33:21 Listing root folder (4 items) took 524.021319ms
2018/06/10 23:33:29 Listing large folder (3500 items) took 8.253931507s
2018/06/10 23:33:29 Flushing cache once
2018/06/10 23:33:29 Listing root folder (4 items) took 1.122411ms
2018/06/10 23:33:29 Listing large folder (3500 items) took 153.852036ms
```

Basically a ls on the mount of the root folder (with one folder containing 3500 subfolders) takes a small amount of time. There is no indication that the large folder gets listed (neither from the logs you posted, those are just inspects).

A ls on the large folder(still on mount) does take a bit longer but no where the amounts described here.

Now if I switch to `rclone ls`, things are different and there is the freeze that takes a long time to finish. But `rclone ls` does a recursive listing from what I can see so maybe this is normal. 

Cache does not go in the subfolders on its own without being asked to. I don't believe the change I did previously does anything for this.

**Comment by remusb** [comment] 2018-06-11 19:25
It is not normal to freeze like that in `rclone ls`. Still, it seems to be happening only there. There might be some double locking or something.

**Comment by remusb** [comment] 2018-06-11 19:37
Ran it again with more verbose logs. rclone is doing 3500 http requests, caching and displaying the contents at the same time, it will take time. I can't see any locking, just steady progress and a lot of HTTP requests in the background.

@ncw is it normal that `rclone ls` to do a recursive listing? I've looked at the code, it does look like some recursion there instead of a standard List call.

**Comment by ncw** [comment] 2018-06-11 19:51
Yes rclone ls is recursive by default. It is an accident of history ... Rclone lsf is quite a good alternative.

**Comment by ivandeex** [comment] 2021-02-09 16:24
Closing stale issue

**Closed by ivandeex** 2021-02-09 16:24 UTC
Labels: Remote: Cache, bug, can't reproduce
