### ISSUE TITLE
Add option for copy command to use temporary partial file during download so updates are atomic

### ISSUE THREAD

**Issue by patakijv** [rclone/rclone#5086] opened 2021-03-02 17:09 UTC
We use `rclone copy` to copy specific files in specific containers (defined in a configuration file - not an across the board sync or mount type of thing) from a remote cloud provider to a local file system. This occurs in a cron job to keep the files up to date regularly.

We run into situations where we try to access the file at the same moment it is getting updated in that moment because the file is not complete.

It would great if there was an option for when the file is downloading through the copy command, for it to be first saving to a temporary file (ex: filename.ext.rclonepartial ) as it is downloading and then "move" the temporary to the final destination (ex: filename.ext), so that the copy process was as atomic as possible and whenever you try to access the file, it is a completely downloaded file (either the previous version or the new version).

**Comment by ivandeex** [comment] 2021-03-03 01:13
This was proposed and described in greater detail in https://github.com/rclone/rclone/issues/3770#issuecomment-559816532

**Comment by ivandeex** [comment] 2021-03-03 01:19
Duplicate of #3770 

The feature is waiting for developers
We are happy to accept your pull request implementing it

Or put your thumbs up in #3770
After getting enough thumbs up, the feature will be marked as important and one of devs will tackle it

**Closed by ivandeex** 2021-03-03 01:19 UTC
Labels: duplicate, enhancement, help wanted
