### ISSUE TITLE
No mega backend?

### ISSUE THREAD

**Issue by liar666** [rclone/rclone#4701] opened 2020-10-22 20:53 UTC
#### What is the problem you are having with rclone?
Hi,

I've just downloaded rclone 1.53.1 for (linux/Ubuntu amd64) from your official site and I'm trying to configure my mega account following: https://rclone.org/mega/

But there's no "mega" backend to be selected :{
```
Storage> mega
Bad remote "mega": didn't find backend called "mega"
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / 1Fichier
   \ "fichier"
 2 / Alias for an existing remote
   \ "alias"
 3 / Amazon Drive
   \ "amazon cloud drive"
 4 / Amazon S3 Compliant Storage Provider (AWS, Alibaba, Ceph, Digital Ocean, Dreamhost, IBM COS, Minio, etc)
   \ "s3"
 5 / Backblaze B2
   \ "b2"
 6 / Box
   \ "box"
 7 / Cache a remote
   \ "cache"
 8 / Citrix Sharefile
   \ "sharefile"
 9 / Dropbox
   \ "dropbox"
10 / Encrypt/Decrypt a remote
   \ "crypt"
11 / FTP Connection
   \ "ftp"
12 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
13 / Google Drive
   \ "drive"
14 / Google Photos
   \ "google photos"
15 / Hubic
   \ "hubic"
16 / JottaCloud
   \ "jottacloud"
17 / Koofr
   \ "koofr"
18 / Local Disk
   \ "local"
19 / Mail.ru Cloud
   \ "mailru"
20 / Microsoft Azure Blob Storage
   \ "azureblob"
21 / Microsoft OneDrive
   \ "onedrive"
22 / OpenDrive
   \ "opendrive"
23 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
24 / Pcloud
   \ "pcloud"
25 / Put.io
   \ "putio"
26 / SSH/SFTP Connection
   \ "sftp"
27 / Transparently chunk/split large files
   \ "chunker"
28 / Union merges the contents of several remotes
   \ "union"
29 / Webdav
   \ "webdav"
30 / Yandex Disk
   \ "yandex"
31 / http Connection
   \ "http"
32 / premiumize.me
   \ "premiumizeme"
Storage> 
```

#### What is your rclone version (output from `rclone version`)
1.53.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Mint  20

####  Which cloud storage system are you using? (eg Google Drive)
mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone -vv config 
2020/10/22 22:52:21 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "-vv" "config"]
2020/10/22 22:52:21 NOTICE: Config file "/home/gmuller/.config/rclone/rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> test
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / 1Fichier
   \ "fichier"
 2 / Alias for an existing remote
   \ "alias"
 3 / Amazon Drive
   \ "amazon cloud drive"
 4 / Amazon S3 Compliant Storage Provider (AWS, Alibaba, Ceph, Digital Ocean, Dreamhost, IBM COS, Minio, etc)
   \ "s3"
 5 / Backblaze B2
   \ "b2"
 6 / Box
   \ "box"
 7 / Cache a remote
   \ "cache"
 8 / Citrix Sharefile
   \ "sharefile"
 9 / Dropbox
   \ "dropbox"
10 / Encrypt/Decrypt a remote
   \ "crypt"
11 / FTP Connection
   \ "ftp"
12 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
13 / Google Drive
   \ "drive"
14 / Google Photos
   \ "google photos"
15 / Hubic
   \ "hubic"
16 / JottaCloud
   \ "jottacloud"
17 / Koofr
   \ "koofr"
18 / Local Disk
   \ "local"
19 / Mail.ru Cloud
   \ "mailru"
20 / Microsoft Azure Blob Storage
   \ "azureblob"
21 / Microsoft OneDrive
   \ "onedrive"
22 / OpenDrive
   \ "opendrive"
23 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
24 / Pcloud
   \ "pcloud"
25 / Put.io
   \ "putio"
26 / SSH/SFTP Connection
   \ "sftp"
27 / Transparently chunk/split large files
   \ "chunker"
28 / Union merges the contents of several remotes
   \ "union"
29 / Webdav
   \ "webdav"
30 / Yandex Disk
   \ "yandex"
31 / http Connection
   \ "http"
32 / premiumize.me
   \ "premiumizeme"
Storage> 
```

**Comment by darthShadow** [comment] 2020-10-22 21:21
Are you using the package from your repository? Can you try downloading and trying the one from here instead: https://rclone.org/downloads/?

**Comment by Cnly** [comment] 2020-10-23 04:40
From the log you posted, it seems that you've run the old version installed in your system, rather than the one you downloaded. Maybe you missed the `./` before the program name?

**Comment by ncw** [comment] 2020-10-26 17:35
If you look in the [debian source package](https://packages.debian.org/source/sid/rclone) you'll see there is patch to disable the mega backend

https://salsa.debian.org/go-team/packages/rclone/-/blob/master/debian/patches/0002-Disable-mega-backend.patch

If you take a look at this comment

https://github.com/rclone/rclone/issues/3980#issuecomment-654415017

> the reason that the mega backend is disabled is simple: the package "github.com/t3rm1n4l/go-mega" is not available in Debian, therefore I cannot enable that backend.

This is actually a duplicate of #3980 so I'm going to close this one in favour of that one.

**Closed by ncw** 2020-10-26 17:35 UTC
Labels: question
