### ISSUE TITLE
[BUG] copy via backend cache from commandline + temp-upload => destination folder ignored

### ISSUE THREAD

**Issue by thestigma** [rclone/rclone#3326] opened 2019-07-03 19:42 UTC
I have read contribution guide

#### Output of `rclone version`
rclone v1.48.0-033-g6bae3595-beta
- os/arch: windows/amd64
- go version: go1.12.3
Win10, 64bit

#### Describe the issue
Copying files to a remote folder in commandline through cache with --cache-tmp-upload-path results in the destination folder being ignored. Files are copied, but directly to the root.
Screenshot of the result (root of temp upload folder - apologies for not capturing full path)
https://ibb.co/FnSQHL3

#### Command and debug output

```
C:\rclone>rclone copy c:\testfiles\3files\ TeamdriveCache:\subfolder1\subfolder2\ --cache-db-path "C:\RCLONECACHE" --cache-chunk-path "C:\RCLONECACHE" --cache-chunk-clean-interval 1m --cache-workers 5 --cache-writes --cache-tmp-upload-path "C:\RCLONEUPLOAD" --cache-tmp-wait-time 99h --drive-upload-cutoff 64M --drive-chunk-size 64M --transfers 4 --fast-list -vv
--------------------------------------
2019/07/03 21:36:12 DEBUG : rclone: Version "v1.48.0-033-g6bae3595-beta" starting with parameters ["rclone" "copy" "c:\\testfiles\\3files\\" "TeamdriveCache:\\subfolder1\\subfolder2\\" "--cache-db-path" "C:\\RCLONECACHE" "--cache-chunk-path" "C:\\RCLONECACHE" "--cache-chunk-clean-interval" "1m" "--cache-workers" "5" "--cache-writes" "--cache-tmp-upload-path" "C:\\RCLONEUPLOAD" "--cache-tmp-wait-time" "99h" "--drive-upload-cutoff" "64M" "--drive-chunk-size" "64M" "--transfers" "4" "--fast-list" "-vv"]
2019/07/03 21:36:12 DEBUG : Using config file from "C:\\Users\\Stigma\\.config\\rclone\\rclone.conf"
2019/07/03 21:36:12 DEBUG : Teamdrive: Loaded invalid token from config file - ignoring
2019/07/03 21:36:13 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2019/07/03 21:36:13 DEBUG : Teamdrive: Saved new token in config file
2019/07/03 21:36:14 DEBUG : TeamdriveCache: wrapped Teamdrive:Secure/subfolder1/subfolder2 at root subfolder1/subfolder2
2019/07/03 21:36:14 INFO  : TeamdriveCache: Cache DB path: C:\RCLONECACHE\TeamdriveCache.db
2019/07/03 21:36:14 INFO  : TeamdriveCache: Cache chunk path: C:\RCLONECACHE\TeamdriveCache
2019/07/03 21:36:14 INFO  : TeamdriveCache: Chunk Memory: true
2019/07/03 21:36:14 INFO  : TeamdriveCache: Chunk Size: 32M
2019/07/03 21:36:14 INFO  : TeamdriveCache: Chunk Total Size: 10G
2019/07/03 21:36:14 INFO  : TeamdriveCache: Chunk Clean Interval: 1m0s
2019/07/03 21:36:14 INFO  : TeamdriveCache: Workers: 5
2019/07/03 21:36:14 INFO  : TeamdriveCache: File Age: 1y
2019/07/03 21:36:14 INFO  : TeamdriveCache: Cache Writes: enabled
2019/07/03 21:36:14 INFO  : TeamdriveCache: Upload Temp Rest Time: 4.125d
2019/07/03 21:36:14 INFO  : TeamdriveCache: Upload Temp FS: C:/RCLONEUPLOAD
2019/07/03 21:36:14 DEBUG : Adding path "cache/expire" to remote control registry
2019/07/03 21:36:14 DEBUG : Adding path "cache/stats" to remote control registry
2019/07/03 21:36:14 DEBUG : Adding path "cache/fetch" to remote control registry
2019/07/03 21:36:14 DEBUG : Cache remote TeamdriveCache:subfolder1/subfolder2: list recursively from ''
2019/07/03 21:36:14 INFO  : Cache remote TeamdriveCache:subfolder1/subfolder2: Waiting for checks to finish
2019/07/03 21:36:14 INFO  : Cache remote TeamdriveCache:subfolder1/subfolder2: Waiting for transfers to finish
2019/07/03 21:36:14 DEBUG : Cache remote TeamdriveCache:subfolder1/subfolder2: put data at '20161029_203748_010.jpg'
2019/07/03 21:36:14 DEBUG : Cache remote TeamdriveCache:subfolder1/subfolder2: put data at '20161029_203748_011.jpg'
2019/07/03 21:36:14 DEBUG : Cache remote TeamdriveCache:subfolder1/subfolder2: put data at '20161029_203748_009.jpg'
2019/07/03 21:36:14 INFO  : 20161029_203748_010.jpg: put: uploaded in temp fs
2019/07/03 21:36:14 INFO  : 20161029_203748_011.jpg: put: uploaded in temp fs
2019/07/03 21:36:14 INFO  : 20161029_203748_009.jpg: put: uploaded in temp fs
2019/07/03 21:36:14 INFO  : 20161029_203748_010.jpg: put: queued for upload
2019/07/03 21:36:14 DEBUG : subfolder1/subfolder2/20161029_203748_010.jpg: pending upload found
2019/07/03 21:36:14 INFO  : 20161029_203748_011.jpg: put: queued for upload
2019/07/03 21:36:14 DEBUG : subfolder1/subfolder2/20161029_203748_011.jpg: pending upload found
2019/07/03 21:36:14 INFO  : 20161029_203748_009.jpg: put: queued for upload
2019/07/03 21:36:14 DEBUG : subfolder1/subfolder2/20161029_203748_009.jpg: pending upload found
2019/07/03 21:36:14 DEBUG : 20161029_203748_010.jpg: put: added to cache
2019/07/03 21:36:14 INFO  : : put: cache expired
2019/07/03 21:36:15 DEBUG : 20161029_203748_011.jpg: put: added to cache
2019/07/03 21:36:15 DEBUG : 20161029_203748_009.jpg: put: added to cache
2019/07/03 21:36:15 DEBUG : 20161029_203748_010.jpg: object hash cached: 1d78e455f3fb104330131f13084b7ce3
2019/07/03 21:36:15 INFO  : 20161029_203748_010.jpg: Copied (new)
2019/07/03 21:36:15 INFO  : : put: cache expired
2019/07/03 21:36:15 INFO  : : put: cache expired
2019/07/03 21:36:15 DEBUG : 20161029_203748_011.jpg: object hash cached: 7a9edd22d749add2276d72c0efcac353
2019/07/03 21:36:15 INFO  : 20161029_203748_011.jpg: Copied (new)
2019/07/03 21:36:15 DEBUG : 20161029_203748_009.jpg: object hash cached: 263981c38ba2bb69b408ad9822aa4dc2
2019/07/03 21:36:15 INFO  : 20161029_203748_009.jpg: Copied (new)
2019/07/03 21:36:15 INFO  :
Transferred:        1.942M / 1.942 MBytes, 100%, 915.776 kBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:        2.1s

2019/07/03 21:36:15 DEBUG : 14 go routines active
2019/07/03 21:36:15 DEBUG : rclone: Version "v1.48.0-033-g6bae3595-beta" finishing with parameters ["rclone" "copy" "c:\\testfiles\\3files\\" "TeamdriveCache:\\subfolder1\\subfolder2\\" "--cache-db-path" "C:\\RCLONECACHE" "--cache-chunk-path" "C:\\RCLONECACHE" "--cache-chunk-clean-interval" "1m" "--cache-workers" "5" "--cache-writes" "--cache-tmp-upload-path" "C:\\RCLONEUPLOAD" "--cache-tmp-wait-time" "99h" "--drive-upload-cutoff" "64M" "--drive-chunk-size" "64M" "--transfers" "4" "--fast-list" "-vv"]
2019/07/03 21:36:15 DEBUG : Cache remote TeamdriveCache:subfolder1/subfolder2: Services stopped
```

#### Troubleshooting
- copy in commandline without cache: OK
- copy in commandline with cache, without temp-upload: OK
- copy in mounted drive with cache (with and without temp-upload): OK
- copy in commandline with cache AND temp upload: FAIL 
(files uploaded to root, destination directory ignored). 

#### Additional observations
- Files in temp-upload folder can be seen to be ignoring directory before they actually reach cloud drive

#### Hypothesis
Bug somewhere in the temp-upload handling leading to unexpected result when not mounted. Perhaps since cache was first intended to be used for media this was not tested outside of mount?

I have attempted all due diligence in testing all variations that came to mind to isolate the issue and not report a non-bug, but I am still an rclone noob, so if this is down to user-error I apologize in advance. I figure it's better to report it than not.

**Comment by thestigma** [comment] 2019-07-03 20:48
I found this issue that seems like it is probably related?
https://github.com/ncw/rclone/issues/3305

**Comment by ncw** [comment] 2019-07-04 07:02
Could you paste your config for the cache and the remote it is using, redacting any secrets in them?

This could conceivably be a bug in the drive backend.  Could you try making a cache remote pointing to a local disk directory (`remote = /path/to/folder`) and see if you can replicate?

I suspect this is the cache backend forgetting to add its root when doing temp uploads. Can you see whether the path of the files are OK in the temp upload directory? Or is the problem when they come out the temp upload directory?

**Comment by thestigma** [comment] 2019-07-04 10:09
1) - configs
---------------------
[Teamdrive]
type = drive
client_id = [REDACTED]
client_secret = [REDACTED]
scope = drive
token = [REDACTED]
team_drive = [REDACTED]
#####
upload_cutoff = 256M
chunk_size = 256M

NOTES: Drive is bog standard except I have used custom API key + messed with upload chunks a bit, but I'm certain these do not affect this issue. Don't think the latter two were even in the config while I did that testing, but I note them here just to be thorough.
--------------------
[TeamdriveCache]
type = cache
remote = Teamdrive:/Secure
chunk_size = 32M
info_age = 1y
chunk_total_size = 10G
#####
db_path = C:\RCLONECACHE
chunk_path = C:\RCLONECACHE
chunk_clean_interval = 1m
workers = 4
writes = true
tmp_upload_path = C:\RCLONEUPLOAD
tmp_wait_time = 99h

NOTES: I'm 99% sure this is the config I used when I logged the problem - but I will re-test to verify, and make an update to confirm within max 12 hrs. Artificially high tmp_wait and info_age were for testing/debugging purposes.
---------------------
2) - Local filesystem test : 
I assume you mean I should test with a cache that is NOT connected to a remote, but rather just to the local filesystem. I will do this and update with a new post very soon.

3) - Where the problem occurs:
I can confirm the problem happens as the files are put into temp-upload folder locally. In my testing the files never made it off my local system due to a 99h long delay on tmp upload. If you check my description I do note this and provide an image of how it looks in the local folder - so yes I think the bug is likely to be in the code governing how the files are copied to the tmp upload. As I said thought this only happens when NOT mounted + tmp-upload - so maybe something in the tmp-upload code is accidentally relying on some added info that it has when mounted. I will check what happens in a purely local test and update i new post.

**Comment by ncw** [comment] 2019-07-04 11:02
> I can confirm the problem happens as the files are put into temp-upload folder locally. 

Sorry, I missed that.  In that case there isn't any point doing a local backend test.

I'm pretty sure the problem is here

https://github.com/ncw/rclone/blob/d72e4105fbe8c011e03eb85a9a68dcb0a3853ae2/backend/cache/cache.go#L1444

That will be using the path for the source file, but it should be adding the cache root on like this like (a few lines on)

https://github.com/ncw/rclone/blob/d72e4105fbe8c011e03eb85a9a68dcb0a3853ae2/backend/cache/cache.go#L1450

I'll have a go at a fix in a moment

**Comment by ncw** [comment] 2019-07-04 11:57
Have a go with this (I haven't tested it, it just looks like it might fix it!)

https://beta.rclone.org/branch/v1.48.0-063-gb910c99d-fix-3326-cache-upload-beta/ (uploaded in 15-30 mins)

**Comment by thestigma** [comment] 2019-07-04 13:08
Update to 1) - configs:

Thinking about it more, these tests were run before I had learned how to edit the config file, so I don't have to guess about the config used. It was all done by flags - and those flags were in my original verbose log:

`--cache-db-path "C:\RCLONECACHE" --cache-chunk-path "C:\RCLONECACHE" --cache-chunk-clean-interval 1m --cache-workers 5 --cache-writes --cache-tmp-upload-path "C:\RCLONEUPLOAD" --cache-tmp-wait-time 99h --drive-upload-cutoff 64M --drive-chunk-size 64M --transfers 4 --fast-list -vv`

Aside from this, nothing except what is auto-configured. All default except possibly 10MB chuncks rather than the default 5MB.

**Comment by thestigma** [comment] 2019-07-04 13:32
I have performed 2 tests now.
####Preperation
- Download new test version
- Copy and overwrite files over my current rclone installation
- Prepare to run the exact same command again that failed in previous version
####TEST-1 : Remote copy on new version
CONFIG
`[RemoteCacheTest2]
type = cache
remote = Teamdrive:/Secure
chunk_size = 32M
info_age = 1y
chunk_total_size = 10G`

COMMAND:
`C:\rclone>rclone copy c:\testfiles\3files\ RemoteCacheTest2:\ --cache-db-path "C:\RCLONECACHE" --cache-chunk-path "C:\RCLONECACHE" --cache-chunk-clean-interval 1m --cache-workers 5 --cache-tmp-upload-path "C:\RCLONEUPLOAD" --cache-tmp-wait-time 99h --drive-upload-cutoff 64M --drive-chunk-size 64M --transfers 4 --fast-list -vv`

LOG:
`
C:\rclone>rclone copy c:\testfiles\3files\ RemoteCacheTest2:\ --cache-db-path "C:\RCLONECACHE" --cache-chunk-path "C:\RCLONECACHE" --cache-chunk-clean-interval 1m --cache-workers 5 --cache-tmp-upload-path "C:\RCLONEUPLOAD" --cache-tmp-wait-time 99h --drive-upload-cutoff 64M --drive-chunk-size 64M --transfers 4 --fast-list -vv
2019/07/04 15:18:13 DEBUG : rclone: Version "v1.48.0-063-gb910c99d-fix-3326-cache-upload-beta" starting with parameters ["rclone" "copy" "c:\\testfiles\\3files\\" "RemoteCacheTest2:\\" "--cache-db-path" "C:\\RCLONECACHE" "--cache-chunk-path" "C:\\RCLONECACHE" "--cache-chunk-clean-interval" "1m" "--cache-workers" "5" "--cache-tmp-upload-path" "C:\\RCLONEUPLOAD" "--cache-tmp-wait-time" "99h" "--drive-upload-cutoff" "64M" "--drive-chunk-size" "64M" "--transfers" "4" "--fast-list" "-vv"]
2019/07/04 15:18:13 DEBUG : Using config file from "C:\\Users\\Stigma\\.config\\rclone\\rclone.conf"
2019/07/04 15:18:14 DEBUG : RemoteCacheTest2: wrapped Teamdrive:Secure at root
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Cache DB path: C:\RCLONECACHE\RemoteCacheTest2.db
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Cache chunk path: C:\RCLONECACHE\RemoteCacheTest2
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Chunk Memory: true
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Chunk Size: 32M
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Chunk Total Size: 10G
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Chunk Clean Interval: 1m0s
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Workers: 5
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: File Age: 1y
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Upload Temp Rest Time: 4.125d
2019/07/04 15:18:14 INFO  : RemoteCacheTest2: Upload Temp FS: C:/RCLONEUPLOAD
2019/07/04 15:18:14 DEBUG : Adding path "cache/expire" to remote control registry
2019/07/04 15:18:14 DEBUG : Adding path "cache/stats" to remote control registry
2019/07/04 15:18:14 DEBUG : Adding path "cache/fetch" to remote control registry
2019/07/04 15:18:14 DEBUG : Cache remote RemoteCacheTest2:: list recursively from ''
2019/07/04 15:18:15 INFO  : Cache remote RemoteCacheTest2:: Waiting for checks to finish
2019/07/04 15:18:15 INFO  : Cache remote RemoteCacheTest2:: Waiting for transfers to finish
2019/07/04 15:18:15 DEBUG : Cache remote RemoteCacheTest2:: put data at 'testfile111.txt'
2019/07/04 15:18:15 DEBUG : Cache remote RemoteCacheTest2:: put data at 'testfile222.txt'
2019/07/04 15:18:15 DEBUG : Cache remote RemoteCacheTest2:: put data at 'testfile333.txt'
2019/07/04 15:18:15 INFO  : testfile111.txt: put: uploaded in temp fs
2019/07/04 15:18:15 INFO  : testfile222.txt: put: uploaded in temp fs
2019/07/04 15:18:15 INFO  : testfile333.txt: put: uploaded in temp fs
2019/07/04 15:18:15 INFO  : testfile111.txt: put: queued for upload
2019/07/04 15:18:15 DEBUG : testfile111.txt: pending upload found
2019/07/04 15:18:15 INFO  : testfile222.txt: put: queued for upload
2019/07/04 15:18:15 DEBUG : testfile222.txt: pending upload found
2019/07/04 15:18:15 INFO  : testfile333.txt: put: queued for upload
2019/07/04 15:18:15 DEBUG : testfile333.txt: pending upload found
2019/07/04 15:18:15 DEBUG : testfile111.txt: put: added to cache
2019/07/04 15:18:15 INFO  : : put: cache expired
2019/07/04 15:18:15 DEBUG : testfile222.txt: put: added to cache
2019/07/04 15:18:15 DEBUG : testfile333.txt: put: added to cache
2019/07/04 15:18:15 DEBUG : testfile111.txt: object hash cached: d41d8cd98f00b204e9800998ecf8427e
2019/07/04 15:18:15 INFO  : testfile111.txt: Copied (new)
2019/07/04 15:18:15 INFO  : : put: cache expired
2019/07/04 15:18:15 INFO  : : put: cache expired
2019/07/04 15:18:15 DEBUG : testfile222.txt: object hash cached: d41d8cd98f00b204e9800998ecf8427e
2019/07/04 15:18:15 INFO  : testfile222.txt: Copied (new)
2019/07/04 15:18:15 DEBUG : testfile333.txt: object hash cached: d41d8cd98f00b204e9800998ecf8427e
2019/07/04 15:18:15 INFO  : testfile333.txt: Copied (new)
2019/07/04 15:18:15 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:        1.7s

2019/07/04 15:18:15 DEBUG : 12 go routines active
2019/07/04 15:18:15 DEBUG : rclone: Version "v1.48.0-063-gb910c99d-fix-3326-cache-upload-beta" finishing with parameters ["rclone" "copy" "c:\\testfiles\\3files\\" "RemoteCacheTest2:\\" "--cache-db-path" "C:\\RCLONECACHE" "--cache-chunk-path" "C:\\RCLONECACHE" "--cache-chunk-clean-interval" "1m" "--cache-workers" "5" "--cache-tmp-upload-path" "C:\\RCLONEUPLOAD" "--cache-tmp-wait-time" "99h" "--drive-upload-cutoff" "64M" "--drive-chunk-size" "64M" "--transfers" "4" "--fast-list" "-vv"]
2019/07/04 15:18:15 DEBUG : Cache remote RemoteCacheTest2:: Services stopped

C:\rclone>`

####RESULT: **FAIL - issue persists**

####TEST-2 Exact same test except cache destination is now local
CONFIG:
`[LocalCacheTest]
type = cache
remote = C:/Secure
chunk_size = 32M
info_age = 1y
chunk_total_size = 10G`

COMMAND:
`C:\rclone>rclone copy c:\testfiles\3files\ LocalCacheTest:\ --cache-db-path "C:\RCLONECACHE" --cache-chunk-path "C:\RCLONECACHE" --cache-chunk-clean-interval 1m --cache-workers 5 --cache-tmp-upload-path "C:\RCLONEUPLOAD" --cache-tmp-wait-time 99h --drive-upload-cutoff 64M --drive-chunk-size 64M --transfers 4 --fast-list -vv`

LOG:
`
C:\rclone>rclone copy c:\testfiles\3files\ LocalCacheTest:\ --cache-db-path "C:\RCLONECACHE" --cache-chunk-path "C:\RCLONECACHE" --cache-chunk-clean-interval 1m --cache-workers 5 --cache-tmp-upload-path "C:\RCLONEUPLOAD" --cache-tmp-wait-time 99h --drive-upload-cutoff 64M --drive-chunk-size 64M --transfers 4 --fast-list -vv
2019/07/04 15:20:04 DEBUG : rclone: Version "v1.48.0-063-gb910c99d-fix-3326-cache-upload-beta" starting with parameters ["rclone" "copy" "c:\\testfiles\\3files\\" "LocalCacheTest:\\" "--cache-db-path" "C:\\RCLONECACHE" "--cache-chunk-path" "C:\\RCLONECACHE" "--cache-chunk-clean-interval" "1m" "--cache-workers" "5" "--cache-tmp-upload-path" "C:\\RCLONEUPLOAD" "--cache-tmp-wait-time" "99h" "--drive-upload-cutoff" "64M" "--drive-chunk-size" "64M" "--transfers" "4" "--fast-list" "-vv"]
2019/07/04 15:20:04 DEBUG : Using config file from "C:\\Users\\Stigma\\.config\\rclone\\rclone.conf"
2019/07/04 15:20:04 DEBUG : LocalCacheTest: wrapped local:\\?\C:\Secure at root
2019/07/04 15:20:04 INFO  : LocalCacheTest: Cache DB path: C:\RCLONECACHE\LocalCacheTest.db
2019/07/04 15:20:04 INFO  : LocalCacheTest: Cache chunk path: C:\RCLONECACHE\LocalCacheTest
2019/07/04 15:20:04 INFO  : LocalCacheTest: Chunk Memory: true
2019/07/04 15:20:04 INFO  : LocalCacheTest: Chunk Size: 32M
2019/07/04 15:20:04 INFO  : LocalCacheTest: Chunk Total Size: 10G
2019/07/04 15:20:04 INFO  : LocalCacheTest: Chunk Clean Interval: 1m0s
2019/07/04 15:20:04 INFO  : LocalCacheTest: Workers: 5
2019/07/04 15:20:04 INFO  : LocalCacheTest: File Age: 1y
2019/07/04 15:20:04 INFO  : LocalCacheTest: Upload Temp Rest Time: 4.125d
2019/07/04 15:20:04 INFO  : LocalCacheTest: Upload Temp FS: C:/RCLONEUPLOAD
2019/07/04 15:20:04 DEBUG : Adding path "cache/expire" to remote control registry
2019/07/04 15:20:04 DEBUG : Adding path "cache/stats" to remote control registry
2019/07/04 15:20:04 DEBUG : Adding path "cache/fetch" to remote control registry
2019/07/04 15:20:04 DEBUG : Cache remote LocalCacheTest:: list ''
2019/07/04 15:20:04 DEBUG : : list: error: missing cached dir:
2019/07/04 15:20:04 DEBUG : : list: read 0 from temp fs
2019/07/04 15:20:04 DEBUG : : list: temp fs entries: []
2019/07/04 15:20:04 INFO  : Cache remote LocalCacheTest:: Waiting for checks to finish
2019/07/04 15:20:04 DEBUG : Cache remote LocalCacheTest:: put data at 'testfile111.txt'
2019/07/04 15:20:04 DEBUG : Cache remote LocalCacheTest:: put data at 'testfile222.txt'
2019/07/04 15:20:04 INFO  : Cache remote LocalCacheTest:: Waiting for transfers to finish
2019/07/04 15:20:04 DEBUG : Cache remote LocalCacheTest:: put data at 'testfile333.txt'
2019/07/04 15:20:04 INFO  : testfile111.txt: put: uploaded in temp fs
2019/07/04 15:20:04 INFO  : testfile222.txt: put: uploaded in temp fs
2019/07/04 15:20:04 INFO  : testfile333.txt: put: uploaded in temp fs
2019/07/04 15:20:04 INFO  : testfile111.txt: put: queued for upload
2019/07/04 15:20:04 DEBUG : testfile111.txt: pending upload found
2019/07/04 15:20:04 INFO  : testfile222.txt: put: queued for upload
2019/07/04 15:20:04 DEBUG : testfile222.txt: pending upload found
2019/07/04 15:20:04 INFO  : testfile333.txt: put: queued for upload
2019/07/04 15:20:04 DEBUG : testfile333.txt: pending upload found
2019/07/04 15:20:04 DEBUG : testfile111.txt: put: added to cache
2019/07/04 15:20:04 INFO  : : put: cache expired
2019/07/04 15:20:04 DEBUG : testfile222.txt: put: added to cache
2019/07/04 15:20:04 DEBUG : testfile333.txt: put: added to cache
2019/07/04 15:20:04 DEBUG : testfile111.txt: object hash cached: d41d8cd98f00b204e9800998ecf8427e
2019/07/04 15:20:04 INFO  : testfile111.txt: Copied (new)
2019/07/04 15:20:04 INFO  : : put: cache expired
2019/07/04 15:20:04 INFO  : : put: cache expired
2019/07/04 15:20:04 DEBUG : testfile222.txt: object hash cached: d41d8cd98f00b204e9800998ecf8427e
2019/07/04 15:20:04 INFO  : testfile222.txt: Copied (new)
2019/07/04 15:20:04 DEBUG : testfile333.txt: object hash cached: d41d8cd98f00b204e9800998ecf8427e
2019/07/04 15:20:04 INFO  : testfile333.txt: Copied (new)
2019/07/04 15:20:04 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:       100ms

2019/07/04 15:20:04 DEBUG : 7 go routines active
2019/07/04 15:20:04 DEBUG : rclone: Version "v1.48.0-063-gb910c99d-fix-3326-cache-upload-beta" finishing with parameters ["rclone" "copy" "c:\\testfiles\\3files\\" "LocalCacheTest:\\" "--cache-db-path" "C:\\RCLONECACHE" "--cache-chunk-path" "C:\\RCLONECACHE" "--cache-chunk-clean-interval" "1m" "--cache-workers" "5" "--cache-tmp-upload-path" "C:\\RCLONEUPLOAD" "--cache-tmp-wait-time" "99h" "--drive-upload-cutoff" "64M" "--drive-chunk-size" "64M" "--transfers" "4" "--fast-list" "-vv"]
2019/07/04 15:20:05 DEBUG : Cache remote LocalCacheTest:: Services stopped`

####RESULT: **FAIL - issue persists**

I'm sorry :(
I am happy to assist you in debugging this in what ways I can - so if/when you are actively working on the issue, feel free to poke me in the slack chat and I will prioritize performing quick testing for you :)
Otherwise I will just check back regularly.

**Comment by thestigma** [comment] 2019-07-04 13:35
Addendum: In all tests, database was deleted between runs. I don't know if that's relevant or not, but I prefer to do that to be sure :)

**Comment by thestigma** [comment] 2020-03-19 01:02
@ncw I think you can close this as your discretion.

I think at this point it is not worth spending effort on fixing the cache-backend when you could rather work on your own VFS cache enhancements.

**Comment by ncw** [comment] 2020-03-20 14:47
I'll leave it open for the moment as a pointer to others, but yes, at some point I'd like to deprecate cache and close the issues.

**Comment by ivandeex** [comment] 2021-02-09 18:32
@thestigma 
The _cache_ backend was deprecated a year ago in favor of VFS and is no more supported.
Feel free to reopen against VFS in rclone 1.54 if you can reproduce.
Thanks.
cc @ncw

**Closed by ivandeex** 2021-02-09 18:32 UTC
Labels: Remote: Cache, bug
