### ISSUE TITLE
rclone beta 5318 can't copy new files to dropbox

### ISSUE THREAD

**Issue by mauricev** [rclone/rclone#5143] opened 2021-03-18 21:16 UTC
#### What is the problem you are having with rclone?
I am trying to copy a file from Windows local computer to my dropbox. The copy fails with "object not found" as if   if the file is not already present at the destination, then rclone won't attempt to copy it at all.

#### What is your rclone version (output from `rclone version`)
1.55.0-beta.5318.2bdbf00fa

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10 x64

####  Which cloud storage system are you using? (e.g. Google Drive)
Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone-new copy -vv e:\test-20 dropbox:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2021/03/18 17:05:24 DEBUG : Creating backend with remote "e:\\test-20"
2021/03/18 17:05:24 DEBUG : fs cache: adding new entry for parent of "e:\\test-20", "//?/e:/"
2021/03/18 17:05:24 DEBUG : Creating backend with remote "dropbox:"
2021/03/18 17:05:24 ERROR : Attempt 1/3 failed with 1 errors and: object not found
2021/03/18 17:05:24 ERROR : Attempt 2/3 failed with 1 errors and: object not found

When running this command with 1.54, which works, the output is different:
2021/03/18 17:04:01 DEBUG : test-20: Need to transfer - File not found at Destination

**Comment by darthShadow** [comment] 2021-03-19 04:11
Can you please add your redacted config too?

**Comment by mauricev** [comment] 2021-03-19 04:16
[dropbox]
type = dropbox
token = {"access_token":"redacted","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}

**Comment by mauricev** [comment] 2021-03-19 04:56
5314.e59acd16c, the latest on the OS X, works and does not exhibit this behavior.

**Comment by darthShadow** [comment] 2021-03-19 05:08
I don't think that really matters since I can't see any change between those 2 commits that could have caused this. It's just the style of path handling that's different in OSX & Windows that's causing this issue.

Paging @ncw

**Comment by darthShadow** [comment] 2021-03-19 08:16
Just to verify the root cause, please try with this build too: https://beta.rclone.org/v1.55.0-beta.5274.ff6868900/

**Comment by mauricev** [comment] 2021-03-19 18:13
That build works

**Comment by darthShadow** [comment] 2021-03-19 18:50
Alright, that narrows it down to the refactoring done by @ncw recently.

Thanks for checking.

**Comment by ncw** [comment] 2021-03-22 16:33
I bisected this problem to 8a46dd1b5761b375c72382bb7a01de6ae8ad72a8 - I must have messed up the windows path parsing somehow.

Comparing the intialisatin of the local backed I can see that the old code translated `\` to `/` which the new code isn't.

new initialisation

    2021/03/22 11:43:04 DEBUG : NewFs name="local" root="Z:\\go\\src\\github.com\\rclone\\rclone\\README.md"

old initialisation

    2021/03/22 11:44:39 DEBUG : NewFs name="local" root="Z:/go/src/github.com/rclone/rclone/README.md"

I've attempted to fix this here, can you give it a go?

[v1.55.0-beta.5327.ec2037afe.fix-5143-windows-path](https://beta.rclone.org/branch/fix-5143-windows-path/v1.55.0-beta.5327.ec2037afe.fix-5143-windows-path/) on branch [fix-5143-windows-path](https://github.com/rclone/rclone/tree/fix-5143-windows-path) (uploaded in 15-30 mins)

**Comment by ncw** [comment] 2021-03-24 09:48
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.55

**Closed** 2021-03-24 09:48 UTC
Labels: OS: Windows, Remote: Dropbox, bug
