### ISSUE TITLE
Ubuntu 18.04, Xanmod and Debian 9.5 upload speed variations.

### ISSUE THREAD

**Issue by Mike5123** [rclone/rclone#2738] opened 2018-11-13 11:35 UTC
#### What is the problem you are having with rclone?
Using rclone copy . gdrive:/ with a bunch of 1GB.bin test files, performance on a default Ubuntu 18.04 is around 400Mbps upload. With xanmod kernel and BBR, as much as 700Mbps.

When using a default Debian 9.5 install with no changes, 950Mbps.

#### What is your rclone version (output from `rclone version`)
v1.44-078-g9b3c951a-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 64bit, Ubuntu 18.04 64bit with xanmod (https://xanmod.org/) and Debian 9.5 64bit.

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy . gdrive:/temp

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Log reveals no abnormalities.

**Comment by ncw** [comment] 2018-11-13 17:07
Are you thinking that there might be something that needs tweaking in rclone to improve the speeds?

Can you try tests with other programs (eg scp a binary somewhere on the 3 OSes)?

Note that you can speed up drive uploads using the --drive-chunk-size flag

**Comment by Mike5123** [comment] 2018-11-13 17:26
I can't test all three OSes since this is all from the same server with several reinstalls. SCP is ~40MB/s per file on Ubuntu 18.04 with xanmod to a tiny buyvm VPS.

Yes, my assumption is it's an issue with rclone, because these tests have all been done on the same server with the same network, same hardware. Nothing changed other then the OS and kernel.

Unless Ubuntu is just not optimized for throughput, but that's a bit outside of my expertise.

**Comment by ncw** [comment] 2018-11-13 17:48
There has been some discussion on the forum about an ubuntu driver bug causing network slowdowns: https://forum.rclone.org/t/sudden-drop-in-download-bandwidth-during-transfer/7255/10

**Comment by Mike5123** [comment] 2018-11-13 17:59
Issue persists using 4.15.0-38-generic. Xanmod kernel is still significantly faster, and the Debian 9.5 OS/kernel can max my port.

I'd just use Debian, but it has issues supporting my iGPU.

**Comment by ncw** [comment] 2018-11-13 22:11
In your tests SCP ran at the same speed as rclone so I'm not convinced this is an rclone problem.

Can you try some different kernels?

What network driver do you use?

**Comment by Mike5123** [comment] 2018-11-13 23:29
Currently on Debian 9.5 with the e1000e driver and a I219-LM. I'm seeing upwards of 60MB/s to my BuyVM VPS on SCP.

But since rclone transfers multiple files at once, the throughput of a single file shouldn't be the only variable. I tested with 8 1GB.bin files in a folder.

**Comment by Mike5123** [comment] 2018-11-14 14:16
I have ruled out the crypt being the problem. Speeds remain the same on regular gdrive on Ubuntu 18.04.

**Comment by animosity22** [comment] 2018-11-14 14:49
There was a kernel bug on Ubuntu so you could try rolling back to a much earlier kernel. 

I run the same hardware and always get much better performance on Debian vs Ubuntu so it definitely for me isn't a rclone issue but a distro issue.

rclone copy tends to limit your transfer speed to around 20-25MB/s per file so it would be best to test with a single file rather than multiple.

You'd see the kernel issue with a packet capture and reviewing that depending on how deep you want to go into trying to identify the issue.

**Comment by animosity22** [comment] 2018-11-14 17:32
I was sharing it because it was found (obviously) and fixed in certain versions. I was suggesting you roll back to the version a person stated in the post so you could test and validate that fixed it.

On my stock debian, I can max my gigabit line as I normally can do that from my mount and a single file copy.

![image](https://user-images.githubusercontent.com/5088712/48500659-67493200-e809-11e8-9f72-d0d2602aafe0.png)

**Comment by Mike5123** [comment] 2018-11-14 20:20
I'm also testing in another datacenter to rule out any abnormalities and only see 26MB/s per-file transfers there as well.

It's possible google drive has poor peering in the EU.

**Comment by Mike5123** [comment] 2018-11-14 20:33
On Ubuntu 18.04, using rsync on the mount I am able to see bursts up to 100MB/s, followed by dips to 15MB/s and back up again.

rsync --progress 00001.m2ts /root/temp.m2ts
00001.m2ts
  1,624,211,456  29%  106.75MB/s    0:00:35

**Comment by Mike5123** [comment] 2018-11-14 20:39
Using the same setup with upload:

rsync --progress 1GB.bin /mnt/gdrive/temp5/
1GB.bin
    260,407,296  24%   22.25MB/s    0:00:34

I'll test with Debian 9.5 again in a bit.

**Comment by animosity22** [comment] 2018-11-14 20:41
Upload is a slightly different animal and a few tweaks can help with that. My use case is all download streaming so I don't get near that:

```
--drive-chunk-size
```
setting to 32M or maybe higher would help uploads.

**Comment by Mike5123** [comment] 2018-11-15 13:34
Right, but that's what this whole issue is about - the upload speed variations between Ubuntu and Debian.

It's not even about single-file uploads, either. As those max at 27MB/s on both defaullt and XanMod kernels. On two different servers, in two different datacenters.

What this issue is about is multi-file uploads using rclone copy, as there is more then 50% additional throughput using the Xanmod kernel and Debian 9.5. Ubuntu's default kernel hard caps at 10MB/s per file, whereas XanMod and Debian 9.5 stock show 20-24MB/s per file.

It's entirely possible the default Ubuntu kernel has a bug that hard caps everything to 10MB/s. It's equally possible rclone has an incompatibility with the default kernel.

**Comment by animosity22** [comment] 2018-11-15 13:36
That's why I shared the kernel bug as the root cause of your issue. You've proven it out very well.

**Comment by dtaht** [comment] 2018-12-04 18:32
I'd just like to point out that cake's primary role to date has been as a shaper, not as a native line-rate qdisc. It can certainly be used as a qdisc, but while it works better in a wider range of circumstances  (mildly better codel, per host fq, classification, gso-splitting), and comes with a horde of new optional features (working through nat, ack-filtering), it eats lower end cpus for breakfast, and you should watch out for that and perhaps tune appropriately. If it was more cpu-efficient I would be pushing for it as the next fq_codel that worked better in all circumstances... 

Still, I'm impressed with your results! Would love to see tc -s qdisc show output on this application.

some notes on cake:

https://arxiv.org/abs/1804.07617

tcp-primary servers that have no namespaces, vms, or tunnels, should also give sch_fq a shot.

We use the flent.org tool a lot in our benchmarks. It gives a lot of detail about what is really going on.

**Comment by animosity22** [comment] 2020-01-10 17:51
This was an old kernel issue that was patched/fixed. Any new issues, please just ask in the forums.

**Closed by animosity22** 2020-01-10 17:51 UTC
