### ISSUE TITLE
Add support for new Google Drive Shortcuts and Folder Structure

### ISSUE THREAD

**Issue by aurelg** [rclone/rclone#4121] opened 2020-04-11 17:50 UTC
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.14
```

#### What problem are you are trying to solve?

Google Drive implements a new Shortcuts and Folder Structure. Those shortcuts are currently silently ignored, yet visible with a DEBUG message:

```
2020/03/28 17:57:19 DEBUG : file2 shortcut.txt: Ignoring unknown document type "application/vnd.google-apps.shortcut"
```

#### How do you think rclone should be changed to solve that?

I think rclone should copy the item pointed to, ideally with hard/soft links depending on filesystem support, to limit disk space usage by multiple shortcuts pointing to the same big file.

Related: [forum entry](https://forum.rclone.org/t/fyi-sep-30-new-google-drive-shortcuts-and-folder-structure/15197/9).

PS: Thanks a lot for this wonderful project/tool!

**Comment by darthShadow** [comment] 2020-04-11 19:59
Closing as the issue is a duplicate of an already existing issue: #4098

**Closed by darthShadow** 2020-04-11 19:59 UTC
