### ISSUE TITLE
An error occurred while using 1fichier, Flood detected: IP Locked

### ISSUE THREAD

**Issue by Hubray** [rclone/rclone#4161] opened 2020-04-24 09:51 UTC
#### What is the problem you are having with rclone?
An error occurred during copy and sync

`Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Flood detected: IP Locked #374\"}"
`

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS 7.7.1908 (64 Bit) KVM

####  Which cloud storage system are you using? (eg Google Drive)
1fichier

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /www/backup test1:test003 -P
rclone sync /www/backup test1:test003 -P --bwlimit 10M
rclone copy /www/backup test1:test005 -P
rclone copy /www/backup test1:test005 -P --bwlimit 10M

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Sorry, I do n’t know which part of the log to present

I copied some information about running errors

`2020-04-24 17:14:31 ERROR : panel/2020-04-11/data/***.json: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Flood detected: IP Locked #374\"}"
2020-04-24 17:14:32 ERROR : panel/2020-04-11/data/***.conf: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Flood detected: IP Locked #374\",\"status\":\"KO\"}"
2020-04-24 17:14:32 ERROR : panel/2020-04-11/data/***.pl: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Flood detected: IP Locked #374\",\"status\":\"KO\"}"
2020-04-24 17:14:33 ERROR : panel/2020-04-11/data/***.json: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Flood detected: IP Locked #374\",\"status\":\"KO\"}"
2020-04-24 17:14:33 ERROR : panel/2020-04-11/data/***.txt: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Flood detected: IP Locked #374\",\"status\":\"KO\"}"
2020-04-24 17:14:33 ERROR : panel/2020-04-11/data/***.conf: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Flood detected: IP Locked #374\"}"
2020-04-24 17:14:34 ERROR : panel/2020-04-11/data/***.pl: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Flood detected: IP Locked #374\",\"status\":\"KO\"}"
2020-04-24 17:14:34 ERROR : panel/2020-04-11/data/***.conf: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Flood detected: IP Locked #374\"}"
2020-04-24 17:14:35 ERROR : panel/2020-04-11/data/***.json: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Flood detected: IP Locked #374\"}"
2020-04-24 17:14:35 ERROR : panel/2020-04-11/data/******.pl: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Flood detected: IP Locked #374\"}"
2020-04-24 17:14:35 ERROR : panel/2020-04-11/data/******.json: Failed to copy: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Flood detected: IP Locked #374\",\"status\":\"KO\"}"
`

**Comment by buengese** [comment] 2020-04-24 10:31
1fichier ramped up their rate-limiting to 11. I'm already working on a fix but it doesn't look great.

**Comment by ncw** [comment] 2020-04-24 16:30
Yes the integration tests are failing too: https://pub.rclone.org/integration-tests/current/fichier-vfs-TestFichier-5.txt

Thanks for working on this @buengese :-)

**Comment by muzzol** [comment] 2020-04-24 19:23
I'm affected by this bug too. Is there any workaround now?

**Comment by buengese** [comment] 2020-04-26 20:11
I've now merged a fix for this into master you can get it by downloading the latest beta at https://beta.rclone.org/

**Closed by buengese** 2020-04-26 20:12 UTC
Labels: Remote: Fichier, bug

**Comment by muzzol** [comment] 2020-04-26 20:23
@buengese  have you found any performance problems with this new limitation?

**Comment by buengese** [comment] 2020-04-27 10:22
Ŷes! The rate limiting slows down everything to crawl. The integration tests now take around an hour to complete which means they are still going to time out in daily runs.

**Comment by ncw** [comment] 2020-04-27 10:39
What do you think about increasing the timeout for the integration tests? The VFS tests in particular are quite long and timeout on more than one backend right now....

Or maybe we should implement something a bit cleverer than a raw timeout? We could make sure the test is making progress (say logging something every 1 minute or less).

**Comment by buengese** [comment] 2020-04-28 13:41
Right now increasing timeout would probably be enough but logging progress does sound like a good long term solution to me.

Regarding 1fichier the problem is rclone extensive use of list directory api. Currently rclone lists the target directory once for every Put() operation. This is necessary because 1fichier allows duplicate files with the same name and there is no dedicated API for checking if a file already exists. The new guidelines for the API now state that the same directory shouldn't be listed more than once every 30 seconds and there also seems to a limit of 1 directory listing every 3 seconds in general. This makes rclone current behavior highly undesirable. Fixing this would require rclone to onlly list each directory once for the entire sync which would require major changes to the core operations.

**Comment by ncw** [comment] 2020-04-29 11:02
We could add an option for the backend not do do that pre-Put check and set it for the integration tests. Though if it causes duplicates the tests will start to fail :-(
