### ISSUE TITLE
1fichier error "use of closed network connection"

### ISSUE THREAD

**Issue by 2803media** [rclone/rclone#7121] opened 2023-07-07 13:25 UTC
#### What is the problem you are having with rclone?

I use rclone to send proxmox backup to 1fichier, the script works for years and since July 2 I have a "use of closed network connection" error and no finish transfers.

If anyone could help me to understand the problem or help me to find the solution !

Thanks

#### What is your rclone version (output from `rclone version`)

```
rclone v1.63.0
- os/version: debian 9.13 (64 bit)
- os/kernel: 4.15.18-28-pve (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.5
- go/linking: static
- go/tags: none
```

#### Which cloud storage system are you using? (e.g. Google Drive)

1fichier

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone --config /root/.config/rclone/rclone.conf \
    --drive-chunk-size=32M copy $tarfile gd-backup_crypt:/$timepath \
    -vv --stats=60s --transfers=16 --checkers=16
```
I try with --transfers=4 with same error

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
INFO: 2023/07/07 15:06:53 DEBUG : Creating backend with remote "gd-backup_crypt:/2023/07/07"
INFO: 2023/07/07 15:06:54 DEBUG : fs cache: renaming cache item "gd-backup_crypt:/2023/07/07" to be canonical "gd-backup_crypt:2023/07/07"
INFO: 2023/07/07 15:06:54 DEBUG : vzdump-lxc-104-2023_07_07-14_59_31.tar.lzo: Need to transfer - File not found at Destination
INFO: 2023/07/07 15:07:54 INFO  : 
INFO: Transferred:   	    1.667 GiB / 9.358 GiB, 18%, 28.938 MiB/s, ETA 4m32s
INFO: Transferred:            0 / 1, 0%
INFO: Elapsed time:       1m0.9s
INFO: Transferring:
INFO:  *    vzdump-lxc-104-2023_07_07-14_59_31.tar.lzo: 17% /9.358Gi, 28.938Mi/s, 4m32s
INFO: 2023/07/07 15:08:54 INFO  : 
INFO: Transferred:   	    3.287 GiB / 9.358 GiB, 35%, 27.865 MiB/s, ETA 3m43s
INFO: Transferred:            0 / 1, 0%
INFO: Elapsed time:       2m0.9s
INFO: Transferring:
INFO:  *    vzdump-lxc-104-2023_07_07-14_59_31.tar.lzo: 35% /9.358Gi, 27.858Mi/s, 3m43s
INFO: 2023/07/07 15:08:58 DEBUG : pacer: low level retry 1/1 (error Post "https://ru-3.1fichier.com/upload.cgi?id=XLYDsUeDek": use of closed network connection)
INFO: 2023/07/07 15:08:58 DEBUG : pacer: Rate limited, increasing sleep to 5s
INFO: 2023/07/07 15:09:54 INFO  : 
INFO: Transferred:   	    3.369 GiB / 9.358 GiB, 36%, 740.439 KiB/s, ETA 2h21m21s
INFO: Transferred:            0 / 1, 0%
INFO: Elapsed time:       3m0.9s
INFO: Transferring:
INFO:  *    vzdump-lxc-104-2023_07_07-14_59_31.tar.lzo: 36% /9.358Gi, 740.310Ki/s, 2h21m22s
INFO: 2023/07/07 15:10:54 INFO  : 
INFO: Transferred:   	    3.369 GiB / 9.358 GiB, 36%, 15.408 KiB/s, ETA 4d17h12m
INFO: Transferred:            0 / 1, 0%
INFO: Elapsed time:       4m0.9s
INFO: Transferring:
INFO:  *    vzdump-lxc-104-2023_07_07-14_59_31.tar.lzo: 36% /9.358Gi, 15.405Ki/s, 113h13m54s
INFO: 2023/07/07 15:11:54 INFO  : 
INFO: Transferred:   	    3.369 GiB / 9.358 GiB, 36%, 328 B/s, ETA 32w2d16h
INFO: Transferred:            0 / 1, 0%
INFO: Elapsed time:       5m0.9s
INFO: Transferring:
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by 2803media** [comment] 2023-07-07 17:51
It's look like suddenly I need to bind to IPV4 address (after years not binding), quite strange. I need to add a --retries 1 because I had some error 500 from 1fichier even if the file is already on their server, in order to avoid multiple uploads.

```
rclone --config /root/.config/rclone/rclone.conf \
    --drive-chunk-size=32M copy gd-backup_crypt:/$rehydrate$CMDARCHIVE $dumpdir \
    -v --stats=60s --transfers=16 --checkers=16 --bind 101.102.103.104 --retries 1
```

If any one could tell me if it's only a problem in my server config or not it would be nice ;)

**Comment by 2803media** [comment] 2023-07-07 18:58
Update, the 1fichier support team just tell me that they found a bug and it will be deploy next week....

**Comment by ncw** [comment] 2023-07-08 10:12
That's good news.

I have difficulty working out exactly how that error message is caused as it is in the go standard library so hopefully that fixes it.

**Comment by darthShadow** [comment] 2023-07-15 20:42
Closing as the issue is not with rclone and instead with the upstream provider.

**Closed by darthShadow** 2023-07-15 20:42 UTC
