### ISSUE TITLE
google shared drives panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wc7086** [rclone/rclone#5471] opened 2021-07-21 18:50 UTC
#### What is the problem you are having with rclone?

I used the following command to run `rclone mount gsd: /tmp /opt/tmp --allow-other --allow-non-empty --umask 000 --attr-timeout 3m --transfers 12 -vv- -log-file bug.log --daemon` , rclone did not enter the background mode, I immediately used Ctrl+C to try to exit the program, the program process still exists, but the following error was prompted.
<details>
<summary>Ctrl + C log</summary>

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17ead91]

goroutine 28 [running]:
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1.1()
	github.com/rclone/rclone/cmd/mountlib/mount.go:256 +0x51
sync.(*Once).doSlow(0xc00072a5f0, 0xc000055e38)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1()
	github.com/rclone/rclone/cmd/mountlib/mount.go:254 +0x65
github.com/rclone/rclone/lib/atexit.Run.func1()
	github.com/rclone/rclone/lib/atexit/atexit.go:104 +0x7f
sync.(*Once).doSlow(0x2e05c98, 0x1f1f140)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/rclone/rclone/lib/atexit.Run()
	github.com/rclone/rclone/lib/atexit/atexit.go:102 +0xb6
github.com/rclone/rclone/lib/atexit.Register.func1.1()
	github.com/rclone/rclone/lib/atexit/atexit.go:52 +0xea
created by github.com/rclone/rclone/lib/atexit.Register.func1
	github.com/rclone/rclone/lib/atexit/atexit.go:44 +0x94
```
</details>

#### What is your rclone version (output from `rclone version`)

rclone v1.56.0
- os/version: debian 10.10 (64 bit)
- os/kernel: 5.10.0-0.bpo.7-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.5
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64 GNU/Linux

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive (Google shared Drive)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```bash
rclone mount gsd:/tmp /opt/tmp --allow-other --allow-non-empty --umask 000 --attr-timeout 3m --transfers 12 -vv --log-file bug.log --daemon

rclone mount gsd:/tmp /opt/tmp --allow-other --allow-non-empty --umask 000 --attr-timeout 3m --transfers 12 --daemon

rclone mount gsd:/tmp /opt/tmp --allow-other --allow-non-empty --umask 000 --attr-timeout 3m --daemon

rclone mount gsd:/tmp /opt/tmp --allow-other  --daemon

rclone mount gsd:/tmp /opt/tmp --allow-other  --daemon
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

<details>
<summary>BUG.log</summary>

```log
2021/07/21 18:25:32 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "mount" "gsd:/tmp" "/opt/tmp" "--allow-other" "--allow-non-empty" "--umask" "000" "--attr-timeout" "3m" "--transfers" "12" "-vv" "--log-file" "bug.log" "--daemon"]
2021/07/21 18:25:32 DEBUG : Creating backend with remote "gsd:/tmp"
2021/07/21 18:25:32 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/07/21 18:25:33 DEBUG : fs cache: renaming cache item "gsd:/tmp" to be canonical "gsd:tmp"
2021/07/21 18:25:33 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "mount" "gsd:/tmp" "/opt/tmp" "--allow-other" "--allow-non-empty" "--umask" "000" "--attr-timeout" "3m" "--transfers" "12" "-vv" "--log-file" "bug.log" "--daemon"]
2021/07/21 18:25:33 DEBUG : Creating backend with remote "gsd:/tmp"
2021/07/21 18:25:33 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/07/21 18:25:33 DEBUG : fs cache: renaming cache item "gsd:/tmp" to be canonical "gsd:tmp"
2021/07/21 18:25:34 DEBUG : Google drive root 'tmp': Mounting on "/opt/tmp"
2021/07/21 18:25:34 DEBUG : : Root: 
2021/07/21 18:25:34 DEBUG : : >Root: node=/, err=<nil>
2021/07/21 18:25:34 INFO  : Signal received: interrupt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17ead91]

goroutine 28 [running]:
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1.1()
	github.com/rclone/rclone/cmd/mountlib/mount.go:256 +0x51
sync.(*Once).doSlow(0xc00074d9c0, 0xc000a40e38)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1()
	github.com/rclone/rclone/cmd/mountlib/mount.go:254 +0x65
github.com/rclone/rclone/lib/atexit.Run.func1()
	github.com/rclone/rclone/lib/atexit/atexit.go:104 +0x7f
sync.(*Once).doSlow(0x2e05c98, 0x1f1f140)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/rclone/rclone/lib/atexit.Run()
	github.com/rclone/rclone/lib/atexit/atexit.go:102 +0xb6
github.com/rclone/rclone/lib/atexit.Register.func1.1()
	github.com/rclone/rclone/lib/atexit/atexit.go:52 +0xea
created by github.com/rclone/rclone/lib/atexit.Register.func1
	github.com/rclone/rclone/lib/atexit/atexit.go:44 +0x94
2021/07/21 18:26:10 DEBUG : /: Attr: 
2021/07/21 18:26:10 DEBUG : /: >Attr: attr=valid=3m0s ino=0 size=0 mode=drwxrwxrwx, err=<nil>
2021/07/21 18:26:10 DEBUG : : Statfs: 
2021/07/21 18:26:10 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2021/07/21 18:26:10 DEBUG : pacer: Rate limited, increasing sleep to 1.335305771s
2021/07/21 18:26:10 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2021/07/21 18:26:10 DEBUG : pacer: Rate limited, increasing sleep to 2.552634054s
2021/07/21 18:26:12 DEBUG : pacer: Reducing sleep to 0s
2021/07/21 18:26:12 DEBUG : Google drive root 'tmp': read info from Shared Drive "justshare"
2021/07/21 18:26:12 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2021/07/21 18:26:18 DEBUG : rclone: Version "v1.56.0" finishing with parameters ["rclone" "mount" "gsd:/tmp" "/opt/tmp" "--allow-other" "--allow-non-empty" "--umask" "000" "--attr-timeout" "3m" "--transfers" "12" "-vv" "--log-file" "bug.log" "--daemon"]
2021/07/21 18:26:24 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "mount" "gsd:/tmp" "/opt/tmp" "--allow-other" "--allow-non-empty" "--umask" "000" "--attr-timeout" "3m" "--transfers" "12" "-vv" "--log-file" "bug.log" "--daemon"]
2021/07/21 18:26:24 DEBUG : Creating backend with remote "gsd:/tmp"
2021/07/21 18:26:24 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/07/21 18:26:25 DEBUG : fs cache: renaming cache item "gsd:/tmp" to be canonical "gsd:tmp"
2021/07/21 18:26:25 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "mount" "gsd:/tmp" "/opt/tmp" "--allow-other" "--allow-non-empty" "--umask" "000" "--attr-timeout" "3m" "--transfers" "12" "-vv" "--log-file" "bug.log" "--daemon"]
2021/07/21 18:26:25 DEBUG : Creating backend with remote "gsd:/tmp"
2021/07/21 18:26:25 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/07/21 18:26:25 DEBUG : fs cache: renaming cache item "gsd:/tmp" to be canonical "gsd:tmp"
2021/07/21 18:26:26 DEBUG : Google drive root 'tmp': Mounting on "/opt/tmp"
2021/07/21 18:26:26 DEBUG : : Root: 
2021/07/21 18:26:26 DEBUG : : >Root: node=/, err=<nil>
2021/07/21 18:27:26 DEBUG : Google drive root 'tmp': Checking for changes on remote
2021/07/21 18:28:22 INFO  : Signal received: interrupt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17ead91]

goroutine 28 [running]:
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1.1()
	github.com/rclone/rclone/cmd/mountlib/mount.go:256 +0x51
sync.(*Once).doSlow(0xc000761110, 0xc000a49e38)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1()
	github.com/rclone/rclone/cmd/mountlib/mount.go:254 +0x65
github.com/rclone/rclone/lib/atexit.Run.func1()
	github.com/rclone/rclone/lib/atexit/atexit.go:104 +0x7f
sync.(*Once).doSlow(0x2e05c98, 0x1f1f140)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/rclone/rclone/lib/atexit.Run()
	github.com/rclone/rclone/lib/atexit/atexit.go:102 +0xb6
github.com/rclone/rclone/lib/atexit.Register.func1.1()
	github.com/rclone/rclone/lib/atexit/atexit.go:52 +0xea
created by github.com/rclone/rclone/lib/atexit.Register.func1
	github.com/rclone/rclone/lib/atexit/atexit.go:44 +0x94
2021/07/21 18:28:26 DEBUG : Google drive root 'tmp': Checking for changes on remote
2021/07/21 18:29:23 DEBUG : /: Attr: 
2021/07/21 18:29:23 DEBUG : /: >Attr: attr=valid=3m0s ino=0 size=0 mode=drwxrwxrwx, err=<nil>
2021/07/21 18:29:23 DEBUG : /: Lookup: name="test"
2021/07/21 18:29:23 DEBUG : /: >Lookup: node=test, err=<nil>
2021/07/21 18:29:23 DEBUG : test: Attr: 
2021/07/21 18:29:23 DEBUG : test: >Attr: a=valid=3m0s ino=0 size=104857600 mode=-rw-rw-rw-, err=<nil>
2021/07/21 18:29:26 DEBUG : Google drive root 'tmp': Checking for changes on remote
2021/07/21 18:29:26 DEBUG : : changeNotify: relativePath="test", type=1
2021/07/21 18:29:26 DEBUG : : invalidating directory cache
2021/07/21 18:29:26 DEBUG : : >changeNotify: 
2021/07/21 18:30:26 DEBUG : Google drive root 'tmp': Checking for changes on remote
2021/07/21 18:31:26 DEBUG : Google drive root 'tmp': Checking for changes on remote
2021/07/21 18:32:26 DEBUG : Google drive root 'tmp': Checking for changes on remote
2021/07/21 18:33:26 DEBUG : Google drive root 'tmp': Checking for changes on remote

```
</details>

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by wc7086** [comment] 2021-07-21 18:53
I did not encounter this problem when using the following versions
```
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.6
```

**Comment by animosity22** [comment] 2021-07-22 00:30
This is a duplicate of:

https://github.com/rclone/rclone/issues/5472

So I'm going to close this one out.

**Closed by animosity22** 2021-07-22 00:30 UTC
Labels: duplicate
