### ISSUE TITLE
it is possible to support baidu pan now

### ISSUE THREAD

**Issue by landall** [rclone/rclone#6169] opened 2022-05-12 22:10 UTC
baidu shows the open api for net disk again.
It is similar to Onedrive  but with less apis.
Some apis can not reply the same result as documented today.

I can give some help to this backend.
However I  use golang only one time, to add a small feature to rclone. Which files should I finish if I want to add a new backend?

**Comment by animosity22** [comment] 2022-05-13 03:42
Duplicate of https://github.com/rclone/rclone/issues/2099

**Closed by animosity22** 2022-05-13 03:42 UTC
