### ISSUE TITLE
Drive backend set doesn't reauth mount

### ISSUE THREAD

**Issue by 0-MegaMind-0** [rclone/rclone#4202] opened 2020-05-05 10:54 UTC
#### What is the problem you are having with rclone?
https://forum.rclone.org/t/edit-service-account-while-mounted/15760
https://github.com/rclone/rclone/commit/a86196a1569dd9beb701f60fc1f01201a1fa55a6

After the thread above a new feature was introduced to set service account file or chunk-size
but using `rclone backend set drive: -o service_account_file=newserviceaccount.json `  doesn't reauth and keeps using the old service account you restart a mount

#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0-278-gef9e6794-beta
- os/arch: linux/amd64
- go version: go1.14.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
`unraid 6.8.3 64 bit` ,  `Ubuntu server 16.04.06 LTS 64 bit`

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone mount drive: mounttest  --allow-other -vvv`
`rclone backend set drive: -o service_account_file=/path/to/newserviceaccount.json`
output
```
{
        "service_account_file": {
                "current": "/path/to/newserviceaccount.json",
                "previous": "/path/to/oldserviceaccount.json"
        }
}
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
rclone backend set drive: -o service_account_file=/path/to/newserviceaccount.json -vv
2020/05/05 19:38:21 DEBUG : rclone: Version "v1.51.0-278-gef9e6794-beta" starting with parameters ["rcloneorig" "--config" "/boot/config/plugins/rclone-beta/.rclone.conf" "backend" "set" "drive:" "-o" "service_account_file=/path/to/newserviceaccount.json" "-vv"]
2020/05/05 19:38:21 DEBUG : Using config file from "/boot/config/plugins/rclone-beta/.rclone.conf"
2020/05/05 19:38:21 DEBUG : Changing Service Account File from /path/to/oldserviceaccount.json to /path/to/newserviceaccount.json
2020/05/05 19:38:21 DEBUG : Saving config "service_account_file" = " /path/to/newserviceaccount.json" in section "drive" of the config file
{
        "service_account_file": {
                "current": " /path/to/newserviceaccount.json",
                "previous": " /path/to/oldserviceaccount.json"
        }
}
```

```
rclone mount drive: /xxx/xxx/xxx/mounttest/ --allow-other -vv
2020/05/05 19:37:52 DEBUG : rclone: Version "v1.51.0-278-gef9e6794-beta" starting with parameters ["rcloneorig" "--config" "/boot/config/plugins/rclone-beta/.rclone.conf" "mount" "drive:" "/xxx/xxx/xxx/mounttest/" "--allow-other" "-vv"]
2020/05/05 19:37:52 DEBUG : Using config file from "/boot/config/plugins/rclone-beta/.rclone.conf"
2020/05/05 19:37:52 DEBUG : Google drive root '': Mounting on "/xxx/xxx/xxx/mounttest/"
2020/05/05 19:37:53 DEBUG : Adding path "vfs/forget" to remote control registry
2020/05/05 19:37:53 DEBUG : Adding path "vfs/refresh" to remote control registry
2020/05/05 19:37:53 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2020/05/05 19:37:53 DEBUG : : Root: 
2020/05/05 19:37:53 DEBUG : : >Root: node=/, err=<nil>
2020/05/05 19:38:53 DEBUG : Google drive root '': Checking for changes on remote
2020/05/05 19:39:53 DEBUG : Google drive root '': Checking for changes on remote
```

I created 3 different service accounts on three different projects so i could verify api requests 

`user1` --> `project1` --> has access to team drive
`user2` --> `project2` --> has access to team drive 
`user3` --> `project3` --> does NOT have acess to team drive 

* Initially mount with `user1.json` and try to copy files `project1` shows api hits

* `backend set drive: service_account_file=user2.json` try to again copy some files `project2` doesn't register any api calls 

* unmount and mount again now `project2` is registering api hits as its now using `user2.json`
* `backend set drive: service_account_file=user3.json` try to again copy some files `project3` doesn't register any api calls and can still use mount since even though user 3 doesn't belong to team drive as its still using `user2`

* unmount and mount again now `user3` is being used since i get a `Error 404: Shared drive not found:` error 

So i'm guessing just changing sa files using backend set doesn't reauth and use the new service account nor does it check if service account has permission to root folder

**Comment by 0-MegaMind-0** [comment] 2020-05-05 11:24
right now from my tests on mounts it doesn't look like
 `rclone backend set drive: -o service_account_file=newserviceaccount.json`
does anything more than 
`rclone config update drive service_account_file newserviceaccount.json`

**Comment by ncw** [comment] 2020-05-05 13:38
This should work properly @darthShadow - care to comment?

**Comment by darthShadow** [comment] 2020-05-05 15:11
Without running it via rc, there is no way for it to choose which rclone to connect and update it live. The backend command as a standalone can only update the config file.

@0-MegaMind-0 Use the rc backend/command example if you want to update a running mount.

There is one issue here that I will fix in my next PR that is, it doesn't check for the team drive access after re-authing with the new service account file. I will add that check too when updating the file.

**Comment by hacktek** [comment] 2020-05-05 16:11
To add, the proper command should be:

rclone rc backend/command command=set fs=drive: [-o service_account_file=sa.json]

How often can this be done? Any likelihood of running into some sort of google rate limiting if it's done too much?

**Comment by darthShadow** [comment] 2020-05-05 16:14
> How often can this be done? Any likelihood of running into some sort of google rate limiting if it's done too much?

As often as you like. I am not aware of any google limits for re-authentication. Do let us know if you find any such limits.

**Comment by 0-MegaMind-0** [comment] 2020-05-05 16:37
@darthShadow  thanks yeah using rc solves the problem and api hits are properly registered so the accounts are being reauthed :) 
started a test mount with 
`rclone mount drive:mounttest --allow-other -vv --rc --rc-no-auth`

and changed the service account using 
`rclone rc backend/command command=set fs=drive: -o service_account_file=path/to/newserviceaccount.json`

would be a good idea to add this to documentation when its rolled out to stable to prevent someone like me to try and do `rclone backend set drive:`


So only one issue remains it that it doesn't check if user has permission to remote. probably would be a good idea to revert back to original when user tries to update rc with a SA account without permissions 

Thanks a lot ;)

**Comment by darthShadow** [comment] 2020-05-05 17:40
> using rc solves the problem and api hits are properly registered so the accounts are being reauthed

Thanks for the confirmation.


> would be a good idea to add this to documentation

Yep, need to clarify this.


> only one issue remains it that it doesn't check if user has permission to remote

Already on my TODO list. Should be done sometime this week once I get some time to work on it.

**Comment by 0-MegaMind-0** [comment] 2020-05-07 09:18
When the service account file doesn't exist you can set a new SA using  `rclone backend set test: -o service_account_file=file.json`
```
rclone backend get newtest: -o service_account_file
2020/05/07 14:44:28 Failed to backend: drive: failed when making oauth client: error opening service account credentials file: open /home/xxx/test.json: no such file or directory
```


```
rclone backend set newtest: -o service_account_file=/home/xxx/sakeys/1.json
2020/05/07 14:47:05 Failed to backend: drive: failed when making oauth client: error opening service account credentials file: open /home/xxx/test.json: no such file or directory
``

**Comment by darthShadow** [comment] 2020-05-07 09:35
No, the error shows that it wasn't able to set the new service account and the reason for it. Any error while changing the service account results in a full rollback so there is no impact on the config or functionality.

**Comment by 0-MegaMind-0** [comment] 2020-05-07 14:13
my bad i was trying to say i **cant** set a new service account file above 

 wouldn't it be a good idea to let `backend set` change the service account when the service account in `rclone.conf` doesn't exist rather than giving a error ?

**Comment by darthShadow** [comment] 2020-05-07 14:49
That will be difficult since the above example will fail before it even reaches the actual function since the remote initialization itself fails.

@ncw Thoughts?

**Comment by ncw** [comment] 2020-05-09 14:27
> That will be difficult since the above example will fail before it even reaches the actual function since the remote initialization itself fails.

Is it the rollback that is the problem?

I think for most use cases you'd want to swap out an existing service file. So if we had to limit it to only swapping out a service file if there was one already I think that would be OK. We could maybe fail early with a more useful message?

**Comment by darthShadow** [comment] 2020-05-09 15:27
> Is it the rollback that is the problem?

Not really, the problem is the init part of the FS, I believe, which fails with the existing service account. Any ideas on how to workaround that?

**Comment by ncw** [comment] 2020-05-10 16:58
> > Is it the rollback that is the problem?
> 
> Not really, the problem is the init part of the FS, I believe, which fails with the existing service account. Any ideas on how to workaround that?

I'm not sure I understand the problem :-( Can you explain more?

**Comment by darthShadow** [comment] 2020-05-10 17:29
So, in this [line](https://github.com/rclone/rclone/blob/bb65974e2f69a624b5294954b622c841c10a78f5/cmd/backend/backend.go#L75), when the FS is initialized, it fails because the existing configured service account is not present for the oauthclient creation.

I think you misunderstood the problem, the problem here is that an invalid or non-existent service account is present in the existing config which needs to be replaced via the backend command with a valid service account.

**Comment by ncw** [comment] 2020-05-19 16:19
> I think you misunderstood the problem, the problem here is that an invalid or non-existent service account is present in the existing config which needs to be replaced via the backend command with a valid service account

I see!


Do we need a fix for this for 1.52 @darthShadow do you think? Or is it user error?

**Comment by darthShadow** [comment] 2020-05-19 16:24
I would pin this to user error since I cannot think of a way to handle the fs not being initialized.

The above requirement can anyway be handled by something like this using the `config update`: `rclone config update newtest service_account_file /home/xxx/sakeys/1.json`

**Comment by ncw** [comment] 2020-05-25 15:37
OK!

I will close this then as I think we have a workaround.

**Closed by ncw** 2020-05-25 15:37 UTC
Labels: Remote: Drive, bug
