### ISSUE TITLE
[Feature Request] cli mode

### ISSUE THREAD

**Issue by scj643** [rclone/rclone#919] opened 2016-11-30 17:30 UTC
A way to interact with the remote destinations in a cli mode would be useful

**Comment by ncw** [comment] 2016-11-30 17:52
Not sure I understand what you mean - can you give an example please?

**Comment by scj643** [comment] 2016-12-01 13:02
Something kinda like https://github.com/OneDrive/onedrive-sdk-python/tree/master/examples except better.

**Comment by calisro** [comment] 2016-12-02 00:16
Doesn't mounting it accomplish that?

**Comment by bobbintb** [comment] 2016-12-02 00:51
I think they mean something like midnight commander?

**Comment by ncw** [comment] 2016-12-02 08:12
A midnight commander mode would be fun yes.  I think now-a-days that sort of interface is called a TUI (text/terminal user interface) - @scj643 is that what you mean?

The idea of being able to navigate a remote in your terminal I like. 

This is a great cross platform library for building TUIs : https://github.com/nsf/termbox-go which I have used before.

**Comment by scj643** [comment] 2016-12-02 17:14
@ncw a tui is what I mean.

**Comment by diamondsw** [comment] 2016-12-07 03:03
You can mount --read-only. Not sure what "every action would have to be confirmed" means?

**Comment by scj643** [comment] 2016-12-07 18:39
By that I mean that if you want to say delete something it would ask twice to confirm. Same with copying and moving. Also this would work on any OS.

**Comment by marrie** [comment] 2016-12-08 07:22
How about accessibility though I'm a visually impaired user and terminal GUIs can be a bit of a pain, doable but because of the way my screen reader interacts with a CLI at least for now it would be troublesome. I'm still trying to get the hang of mounting remotes, it does not want to seem to work here, I might file a bug about this if I can't troubleshoot this myself.

Blessings and happy Wednesday

**Comment by scj643** [comment] 2016-12-08 14:11
@marrie I'm also visually impaired but this wouldn't replace any functionality and maybe provide some sort of gui wrapper for it with better accessibility.

**Comment by marrie** [comment] 2016-12-08 20:20
I can't code my way out of a corner So I don't know these things, at least not yet. It's worth a try if someone can somehow implement accessibility controls for voiceover and nvda and what ever is used on linux these days.

Thanks.

**Comment by xfchen** [comment] 2016-12-21 15:42
+1 for a TUI. Maybe a midnight commander plugin?

I think chances are, many of you are just like me, use rclone to transfer a lot of media files with super long file names encrypted. It get awkward and hard real fast.

**Comment by eharris** [comment] 2017-01-25 10:09
This would also be very nice for crypt'ed remotes that aren't browsable in any reasonably usable way using other tools.

**Comment by jedi453** [comment] 2017-12-18 01:37
+1 This would be perfect for rclone on android (termux), where mounting is not possible without root.

**Comment by ncw** [comment] 2017-12-18 17:57
I'll just note that rclone can now serve a remote as webdav (see [the latest beta](https://beta.rclone.org)) and there are GUI file managers for webdav on android now which might help.

rclone also has `rclone ncdu` which is a terminal based interface for browsing a remote which might be useful too.

**Comment by jedi453** [comment] 2017-12-18 23:39
Hello ncw,
"rclone serve" is perfect for Android and Termux!  Much more elegant than my suggestion!  Thanks, I just didn't know this option existed.
- jedi453

**Comment by ivandeex** [comment] 2020-11-14 18:49
There is a number of external projects that implement UI with various success: RCX on Android, RcloneBrowser on Windows and Linux. See https://rclone.org and https://github.com/rclone/rclone for a list.

Also, rclone provides _basic_ operations in WebUI.

IMHO making a TUI is out of scope for core rclone utility.
Implementing it will open a whole can of worms and overwheln development with feature requests even more.

I suggest closing this ticket.

**Comment by ivandeex** [comment] 2021-10-16 20:38
ticket inactive since 4 years
and has many solutions:
- `rclone ncdu`
- `rclone serve`
- embedded web gui
- RcloneBrowser on desktop
- RCX on Android

**Closed by ivandeex** 2021-10-16 20:38 UTC
Labels: enhancement, thinking, help wanted, Web GUI, UX, API / rc
