### ISSUE TITLE
rclone on Amazon Cloud Drive sometimes returns empty md5sum without any error

### ISSUE THREAD

**Issue by Rufflewind** [rclone/rclone#1414] opened 2017-05-17 06:07 UTC
Steps to reproduce:

```
# run these three in quick succession
rclone delete acd:/testfile.txt
rclone copy testfile.txt acd:/
rclone md5sum acd:/testfile.txt
```

What I expected: either it returns the MD5 in the correct form, or fails and exits with nonzero, preferably with some error message on stderr as well.

What actually happens: It’s kind of random, but sometimes md5sum will return no output, yet nothing is written to stderr and it exits with 0.

It might be caused by [this line](https://github.com/ncw/rclone/blob/master/amazonclouddrive/amazonclouddrive.go#L908), which returns no output but also no error.

---

rclone v1.36 on Arch Linux (x86-64)

**Comment by ncw** [comment] 2017-05-17 11:35
I think this is probably caused by the eventual consistency of the listings for acd.

Sometimes after uploading a file it won't be in the file listings for a while.  I wonder whether partial info is in the file listings at the point md5sum is run.

You can debug with `-vv --dump-bodies` to look see what amazon actually sends.

**Comment by Rufflewind** [comment] 2017-05-17 12:40
Here's the abridged version of what gets received when this bug occurs:

```
{"contentUrl":"https://content-na.drive.amazonaws.com/cdproxy/","customerExists":true,"metadataUrl":"https://cdws.us-east-1.amazonaws.com/drive/v1/"}

{"data":[{"isRoot":true,"eTagResponse":"...","id":"...","kind":"FOLDER","version":142,"labels":[],"createdDate":"...","createdBy":"CloudDriveFiles","restricted":false,"modifiedDate":"2017-05-17T12:27:08.096Z","isShared":false,"parents":[],"status":"AVAILABLE"}],"count":1}

{"data":[{"eTagResponse":"...","id":"...","kind":"FILE","version":4,"labels":[],"contentProperties":{"extension":"txt","size":7,"contentType":"text/plain","version":1,"md5":"14758f1afd44c09b7992073ccf00b43d"},"createdDate":"2017-05-17T12:27:04.840Z","createdBy":"rclone-...","restricted":false,"modifiedDate":"2017-05-17T12:27:08.113Z","name":"hi.txt","isShared":false,"properties":{"CloudDrive":{"ProcessingTimestamp":"1495024025145","Processing":"PDF_PROCESSING"}},"parents":["..."],"status":"TRASH"}],"count":1}

{"data":[{"eTagResponse":"...","id":"...","kind":"FILE","version":4,"labels":[],"contentProperties":{"extension":"txt","size":7,"contentType":"text/plain","version":1,"md5":"14758f1afd44c09b7992073ccf00b43d"},"createdDate":"2017-05-17T12:27:04.840Z","createdBy":"rclone-...","restricted":false,"modifiedDate":"2017-05-17T12:27:08.113Z","name":"hi.txt","isShared":false,"properties":{"CloudDrive":{"ProcessingTimestamp":"1495024025145","Processing":"PDF_PROCESSING"}},"parents":["..."],"status":"TRASH"}],"count":1}

{"data":[],"count":0}  <--- this is not normal, but rclone doesn't detect it as an error
```

I understand that ACD’s API is kind of flaky.  My main concern is that `rclone md5sum` doesn’t always report errors correctly (no stderr, exit code zero).

(Speaking of consistency … it seems that sometimes `delete` and `cp` could happen in the wrong order.  Is that intended?)

**Comment by ncw** [comment] 2017-05-17 15:57
I've tracked this down...

The problem is due to the way rclone interprets the command line.  When you say `rclone md5sum acd:/testfile.txt` rclone doesn't know if `testfile.txt` is a directory or a file.

rclone has a really convoluted method of working out whether it is a directory or a file which just happens to go wrong when amazon declares the file is missing after it previously declared it was there.

So, yes this is a bug and I'll fix it when I rationalise the working out whether `testfile.txt` is a directory or a file code.

This may take a release or two!

**Comment by unnfav** [comment] 2017-05-18 06:39
>The problem is due to the way rclone interprets the command line. When you say rclone md5sum acd:/testfile.txt rclone doesn't know if testfile.txt is a directory or a file.

I am not sure if it is related, but if there is already a directory, e.g. acd:test02, and if you try to upload a file with the same name to the same path, it would just end without giving any errors (even with -vv).

**Comment by ncw** [comment] 2020-01-14 14:13
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.

**Closed by ncw** 2020-01-14 14:13 UTC
Labels: bug
