### ISSUE TITLE
1.49.4 is slow (uploading) vs 1.48 ?

### ISSUE THREAD

**Issue by Rootax** [rclone/rclone#3578] opened 2019-09-30 15:02 UTC
Hi,

So, i'm under w10 x64, and using rclone  => google drive for backups.

I'm not updating rclone often, but today I updated from 1.48 to 1.49.4. And to my surprise, I was limited around 300Mbits/sec uploading to gdrive... Ok, maybe my isp was bottlenecking somewhere (I can upload at 500Mbits/sec).
But, It was strange to me, so, I deleted the same files I just uploaded with 1.49.4, put 1.48 again, and bam, 500mbits. The tests were a few minutes appart, so I don't believe it was a network problem, and it was big files around 10-15gb so speed has time to "settle".

I didn't notice anything weird with 1.49.4, no strange cpu usage, etc... just the "slow" upload speed.

I'm using this command : 
C:\rclonewin64\rclone.exe sync --delete-before --verbose --transfers 8 --checkers 8 --contimeout 45s --timeout 75s --retries 3 --low-level-retries 10 --multi-thread-cutoff=100 --multi-thread-streams=8 --drive-chunk-size 256M --fast-list  --exclude "Films 4K HDR/**" --exclude "Films 4K/**" --exclude "cheg/**" --exclude "seed/**" --stats 2s R:\ gdriveencryptedownapi:backupnas

(I know the mul-thread stuff is not working when uploading)

Sorry for my english :/

**Comment by ncw** [comment] 2019-09-30 21:40
Hmm, can you try [1.49.3](https://downloads.rclone.org/v1.49.3/) - I had a report that 1.49.4 has a strange interaction with Google drive.

**Comment by Rootax** [comment] 2019-10-01 08:41
I just tried 1.49.3, and yes, full speed again.

**Comment by ncw** [comment] 2019-10-01 15:07
Any chance you could try these 3 tests?

### 1.49.4 as released but disable http2

export GODEBUG=http2client=0  # disable HTTP/2 client support

### 1.49.4 compiled with go1.12

https://pub.rclone.org/rclone-v1.49.4-go1.12.6.zip

### 1.49.3 compiled with go1.13

https://pub.rclone.org/rclone-v1.49.3-go1.13.zip

See also a possibly relevant thread in the forum: https://forum.rclone.org/t/1-49-4-plex-internal-errors-on-google-drive/12108/

Thank you :-)

**Comment by ncw** [comment] 2019-10-01 15:08
Ah, just realised you are on Windows so those binaries won't work for you... Can you try the first test anyway?

**Comment by Rootax** [comment] 2019-10-01 15:12
So i've to add -export GODEBUG=http2client=0 to my command line ?

**Comment by ncw** [comment] 2019-10-01 15:19
> So i've to add -export GODEBUG=http2client=0 to my command line ?

Sorry that was unix speak...  You need to set the environment variable `GODEBUG` to `http2client=0`.

You can do this in `cmd` with this I think

    set GODEBUG http2client=0
    rclone ...your command...

**Comment by Rootax** [comment] 2019-10-01 15:27
Ok I did that.

Still not full speed, still limited around 300Mbits/s :/

**Comment by Rootax** [comment] 2019-10-01 17:51
It seems you have found the problem : )
With rclone 1.49.4 go 1.12 i'm at full speed again
With 1.49.3 but go 1.13, same "slower" speed, around 300Mb/sec

Hope it can help !

**Comment by ncw** [comment] 2019-10-01 21:01
> It seems you have found the problem : )
> With rclone 1.49.4 go 1.12 i'm at full speed again
> With 1.49.3 but go 1.13, same "slower" speed, around 300Mb/sec

Thank you very much - very useful testing :-)

**Comment by ncw** [comment] 2019-10-01 21:11
Could you, with the original as released v1.49.4 try this and see if it makes any difference?

    set GODEBUG tls13=0

(note that has to be done in the same CMD window as you run the rclone command)

That TLS change of all the changes in the go1.13 release log looks like the most likely to cause a regression.

**Comment by Rootax** [comment] 2019-10-01 22:23
I'll in a few hours, I'll let you know :)

**Comment by Rootax** [comment] 2019-10-02 09:14
Aaaah, I don't know if that make any sense. With the 1.49.4 (original) + set GODEBUG tls13=0 , I'm not a full speed, but a little better than 300mb/sec, like around 300/400.

I tried with a "full speed" version to see if it wasn't a isp problem, and no, I'm at full speed with thoses versions...

**Comment by ncw** [comment] 2019-10-02 12:32
OK so that probably isn't the problem....

I really need to reproduce this myself so I can bisect the go source, but when I try it I get identical (but much slower) results...

I think what I'll do is build a 1.49.5 using go1.12 and hope that the go team figure out the problem before I release 1.50!

**Comment by ncw** [comment] 2019-10-02 12:39
OK I've decided to revert the 1.49.x builds back to using go1.12

Here is a proposed build - testing appreciated!  This is code identical to 1.49.4 but
- build with go1.12
- the rpm generation is fixed

If it tests well I'll turn it into 1.49.5

https://beta.rclone.org/branch/v1.49.4-003-g2c093214-v1.49-fixes-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment] 2019-10-02 12:55
Broke that build... try this one

https://beta.rclone.org/branch/v1.49.4-003-gb5ea6af6-v1.49-fixes-beta/ (uploaded in 15-30 mins)

**Comment by Rootax** [comment] 2019-10-02 13:00
I'll test as soon as I can, thx !

**Comment by Rootax** [comment] 2019-10-02 13:18
All right, back to full speed with this beta :) I do nothing fancy with rclone, just backuping data to gdrive, so I can't really tell you if it's working without hiccups for other stuff...

**Comment by ncw** [comment] 2019-10-02 14:52
Thank you very much for testing :-)

I'll release that as 1.49.5 once I get a report from my other testers.

**Comment by ivandeex** [comment] 2019-10-03 07:40
@Rootax Please try
`$env:GODEBUG="http2client=0"; rclone cmd...`

**Comment by Rootax** [comment] 2019-10-03 11:19
> @Rootax Please try
> `$env:GODEBUG="http2client=0"; rclone cmd...`

With which version ?

**Comment by ivandeex** [comment] 2019-10-03 11:57
> Could you, with the original as released v1.49.4 try this and see if it makes any difference?
> set GODEBUG tls13=0
> (note that has to be done in the same CMD window as you run the rclone command)
I recall windows has two native shells and mean, in case your windows shell is `powershell` not `cmd`, the SET syntax would have no effect, use  `$env:GODEBUG="tls13=0"; rclone cmd...` instead.

**Comment by Rootax** [comment] 2019-10-03 12:34
Well I tried with cmd, so the set syntax was working, right ?

**Comment by ncw** [comment] 2019-10-03 14:08
> Well I tried with cmd, so the set syntax was working, right ?

Actually I think I got the syntax wrong, it needs to be this

```
set GODEBUG=tls13=0
rclone. ..
```

**Comment by Rootax** [comment] 2019-10-03 17:55
> set GODEBUG=tls13=0

Just did the test : with original 1.49.4, still slower than the "patched" version or older rclone version. A little more unstable (talking about speed) too, like yoyo-ing between 320 and 420 Mb/s. With working version, it's 500 all the way.

I always do the tests with the same number of files, same files, etc.

**Comment by ncw** [comment] 2019-10-03 21:10
Thanks for testing :-)

**Comment by ncw** [comment] 2019-10-05 11:51
I've released a v1.49.5 which you can find at [in the normal place](https://rclone.org/downloads/) which is compiled with go1.12.x

Release announcement: https://forum.rclone.org/t/rclone-1-49-5-release/12166

I need to get to the bottom of this though so would you be willing to do more testing?

The first thing would be to try [the latest beta](https://beta.rclone.org) which is compiled with go1.13.x so likely will have the same problem.

If it does then I'll make a version compiled with the unreleased patches for go.

If that doesn't fix it then we'll need to go deeper!

**Comment by Rootax** [comment] 2019-10-05 12:56
Yeah latest beta has irregular speed too (and is slower) for me.

**Comment by ivandeex** [comment] 2019-10-05 13:48
FYI
TLS 1.3 was landed as optional feature in go 1.12 and activates by default in go 1.13.
This affects how golang client and google drive servers do the connection initialization dance, negotiate ciphers and 0-RTT (very new tls feature) and interact with provider's middle boxes.

https://github.com/golang/go/issues/9671#issuecomment-439561672

https://github.com/openssl/openssl/issues/7482

**Comment by dfunkt** [comment] 2019-10-05 14:06
Unless I misread the message from this commit (https://github.com/golang/go/commit/a8c2e5c6adc0d8f9b976a55bf4e22fcf5770ea55) you can't opt-out from TLS 1.3 anymore.

**Comment by ncw** [comment] 2019-10-05 15:30
> Yeah latest beta has irregular speed too (and is slower) for me.

Can you try this one.. this is v1.49.5 built with go1.13.1 + the latest unreleased patches that will go into go1.13.2 - cross fingers this will work!

[rclone-v1.49.5-windows-amd64-go1.13.1plus.zip](https://github.com/rclone/rclone/files/3693417/rclone-v1.49.5-windows-amd64-go1.13.1plus.zip)

**Comment by Rootax** [comment] 2019-10-05 15:57
> > Yeah latest beta has irregular speed too (and is slower) for me.
> 
> Can you try this one.. this is v1.49.5 built with go1.13.1 + the latest unreleased patches that will go into go1.13.2 - cross fingers this will work!
> 
> [rclone-v1.49.5-windows-amd64-go1.13.1plus.zip](https://github.com/rclone/rclone/files/3693417/rclone-v1.49.5-windows-amd64-go1.13.1plus.zip)

Nop , still unsteady speed and slower :/ For each test I retry with a "stable/fast" release just after, to eliminate a isp or gdrive problem, and, yeah, this build is still problematic for me.

Am I the only one with the problem ??

**Comment by ncw** [comment] 2019-10-05 16:01
> Nop , still unsteady speed and slower :/ For each test I retry with a "stable/fast" release just after, to eliminate a isp or gdrive problem, and, yeah, this build is still problematic for me.

OK thanks for testing and being methodical :-)
 
> Am I the only one with the problem ??

See [this thread on the forum]( https://forum.rclone.org/t/1-49-4-plex-internal-errors-on-google-drive/12108/) which was also fixed by reverting to go1.12 but I don't know if that is the same problem as yours!

**Comment by ncw** [comment] 2019-10-06 11:17
Would it be possible for you to try this test on a Linux VM? So we can see whether this is a Windows specific problem or not?

**Comment by Rootax** [comment] 2019-10-06 13:35
On paper I can, but I don't have the time right now. It will took, what, 1-2 hours to set this up, so it's not a lot but right now for personal reasons, 2h is a lot. I'll have time next week end or the one after, but before that, it's challenging, sorry : /

**Comment by ncw** [comment] 2019-10-07 08:23
> On paper I can, but I don't have the time right now. It will took, what, 1-2 hours to set this up, so it's not a lot but right now for personal reasons, 2h is a lot. I'll have time next week end or the one after, but before that, it's challenging, sorry : /

If you have time that would be great, if not, then we can find another way I'm sure - thank you :-)

**Comment by ncw** [comment] 2019-10-26 17:39
Can you test with [v1.50](https://rclone.org/downloads/) now it has been released?

**Comment by Rootax** [comment] 2019-11-17 10:45
Hello guys. I haven't forgotten this problem. But my fiber is down since mid october, so I can't reproduce the speed problem with my (very) slow backup link.
I'll give an update when my fiber is up again.

**Comment by Rootax** [comment] 2019-11-22 19:09
Well I tried tonight, but it seems I've a problem on my side, since with the "working" version or 1.50.2, I'm at 0k, nothing is uploading tonight... The checks are working... I'm using my own api, and I've not maxed out 750gb in the last 24h... will try tomorrow...

**Comment by Rootax** [comment] 2019-11-22 23:15
All right, so 1.50.2 is working full speed, no problem with it.

**Comment by ncw** [comment] 2019-11-23 16:14
Thanks for testing :-)

I'll close this now then since I think it the same issue as one I've already fixed.

**Closed by ncw** 2019-11-23 16:14 UTC
Labels: bug
