### ISSUE TITLE
Amazon Cloud Drive - Corrupted on File Transfer - Uploads up to 600% per file

### ISSUE THREAD

**Issue by hoveeman** [rclone/rclone#750] opened 2016-09-29 20:06 UTC
I'm using rclone 1.33 on Windows 10 Pro 64bit from cmd. I am running a rclone copy command to backup my music files from my local machine to Amazon Cloud Drive, however I'm getting Corrupted On File Transfer errors on every file. You can see below the output of my command after it has tried upload the files.

`Transferred:   195.105 MBytes (946.044 kBytes/s)
Errors:                 3
Checks:                 0
Transferred:            3
Elapsed time:     3m31.1s
Transferring:
- ...Song1.mp3: 100% done. avg:  181.1, cur:  184.2 kByte/s. ETA: 0s
- ....Song2.mp3: 625% done. avg:  243.3, cur:  174.5 kByte/s. ETA: 0s
- ....Song3.mp3: 309% done. avg:  227.1, cur:  175.2 kByte/s. ETA: 0s
- ....Song4.mp3: 305% done. avg:  221.2, cur:  175.4 kByte/s. ETA: 0s

2016/09/29 09:58:51 Song4.mp3: corrupted on transfer: sizes differ 8605311 vs 27053695
2016/09/29 09:58:51 Song4.mp3: Removing failed copy`

**Comment by ncw** [comment] 2016-10-01 16:15
Can you send a log with `-v` please?

625% done does seem very strange.

Can you do `rclone ls /path/to/Song1.mpg` and check that the size rclone reports is the same as you see in windows explorer?

Have you got anthing else installed which might act on music files?

**Comment by DurvalMenezes** [comment] 2016-10-01 16:16
Hello, 

I'm getting a similar situation here also with ACD, the difference is that I'm getting it during a DOWNload (not up), and my ACD access is encrypted (ie, using a "crypt" section in the rclone.conf file, configured on top of a standard, unencrypted ACD section): 

    Transferred:   104.255 GBytes (11.779 MBytes/s)
    Errors:                 1
    Checks:                 0
    Transferred:           63
    Elapsed time:   2h31m3.2s
    Transferring:
    * TESTFILE.split.ag:  9% done. avg: 6174.3, cur: 5945.8 kByte/s. ETA: 5m19s
    * TESTFILE.split.aw: 54% done. avg: 3000.7, cur: 4881.7 kByte/s. ETA: 3m13s
    * TESTFILE.split.bc:  0% done. avg:  147.1, cur:  111.6 kByte/s. ETA: 5h12m15s
    * TESTFILE.split.aa:  0% done. avg:  230.4, cur:  145.9 kByte/s. ETA: 3h22m5s

    2016/10/01 12:50:02 TESTFILE.split.bc: Failed to copy: failed to authenticate decrypted block - bad password?

I still have the original local file (in the original local dir) that was uploaded to Cloud Drive, and the sizes are indeed different:

File in the "before-upload-to-ACD" directory:

    -rw-rw-r-- 1 durval durval 5177344 Oct  1 12:49 TESTFILE.split.bc

File in the "downloaded-from-ACD" directory:

    -rw-rw-r-- 1 durval durval 2146435072 Aug 16 10:17 TESTFILE.split.bc

Checking the file on ACD with "rclone ls", it is listed with the correct size:

     2146435072 TESTFILE.split.bc

Perhaps both situations (mine and the OP) are being caused by ACD truncating the files during upload *and* download?

The above is in the middle of a large run which is still ongoing. I will run my next batch upload/download in verbose mode and will upload the complete log here when I have it. 

Cheers, 
 -- 
   Durval.

**Comment by DurvalMenezes** [comment] 2016-10-01 17:24
Hello, 

As promised, I did an "rclone sync -v" of the same ACD directory above to the same local directory, and to my great surprise, rclone did NOT even try bringing in the files that were marked with errors during the "rclone copy" above; the verbose output simply showed:

    2016/10/01 13:24:31 TESTFILE.split.bc: Sizes identical
    2016/10/01 13:24:31 TESTFILE.split.bc: Unchanged skipping

I double-checked and it seems the file in the download directory is indeed OK: 

    -rw-rw-r-- 1 durval durval 2146435072 Oct  1 06:43 TESTFILE.split.bc

So, what it looks like is that the original "rclone copy" retried (and finished successfully) the transfer later (ie, *way* after it originally logged the error, which was when I determined that the file was truncated)... I can't be sure as I don't have verbose output for that original "rclone copy".  

Anyway, at least in my case it seems rclone is doing its job and downloading complete, correct files and not failing semi-silently as I feared.  

Sorry for the false alarm.

Cheers, 
 -- 
   Durval.

**Comment by hoveeman** [comment] 2016-10-01 18:46
Thank you @ncw for the follow up! 

I ran the command again with just 1 file transfer and added the -v flag.

```
c:\rclone>c:\rclone\rclone --stats=15s --transfers=1 copy "K:\Music\iTunes\Music" amazon:Music -v
2016/10/01 14:30:18 rclone: Version "v1.33" starting with parameters ["c:\\rclone\\rclone" "--stats=15s" "--transfers=1" "copy" "K:\\Music\\iTunes\\Music" "amazon:Music" "-v"]
2016/10/01 14:30:19 amazon drive root 'Music': Modify window not supported
2016/10/01 14:30:19 amazon drive root 'Music': Reading ""
2016/10/01 14:30:19 amazon drive root 'Music': Finished reading ""
2016/10/01 14:30:19 amazon drive root 'Music': Reading "Artist/"
2016/10/01 14:30:19 amazon drive root 'Music': Finished reading "Artist/"
2016/10/01 14:30:19 amazon drive root 'Music': Reading "Artist/Album/"
2016/10/01 14:30:19 amazon drive root 'Music': Finished reading "Artist/Album/"

2016/10/01 14:18:36
Transferred:   28.079 MBytes (136.510 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     3m30.6s
Transferring:
 * ...Song.mp3: 398% done. avg:  137.7, cur:  125.4 kByte/s. ETA: 0s

2016/10/01 14:18:36 Song.mp3: corrupted on transfer: sizes differ 7390300 vs 29443164
2016/10/01 14:18:36 Song.mp3: Removing failed copy
```

There appears to be nothing in that directory on ACD. I ran the following command: 

```
rclone ls amazon:Music/Artist/Album/Song.mp3`
2016/10/01 14:36:12 directory not found
```

I also checked the file in Windows Explorer, and the file size in Properties matches up with what rclone says, 7390300 bytes.

I have also run the purge command on the directory and started again with the same results.

```
c:\rclone>rclone purge amazon:Music
2016/10/01 14:44:58
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       700ms

```

I do have iTunes and Plex installed on this machine, but they are both off. I have tried other files and they behave in the same way. Occasionally a file will successfully upload.

**Comment by hoveeman** [comment] 2016-10-01 18:58
Ok, I might have an idea as to what might be causing issues. In my copy command I am uploading the music from my K:\ drive. My K:\ drive is a combination of multiple drives using this software. http://www.stablebit.com/DrivePool

I copied the same music folder that I was trying to upload of 12 songs over to my C:\ drive, which is a standard drive and ran the same copy command from that folder and all of the files uploaded successfully. 

`c:\rclone\rclone --stats=15s --transfers=1 copy C:\Music\ amazon:Music -v`

I'm not sure how that software presents the files, but it may be causing issues by presenting the files to rclone in a strange manner.

**Comment by ncw** [comment] 2016-10-01 20:03
That sounds quite plausible - good thinking. 

What rclone does is it reads the length of the file the same way Explorer would. But when it is reading a file it will read as many bytes as the OS gives it, not just the length from the directory listing. That should always be the same number of bytes, but maybe drive pool is causing it not to be somehow.

It might be worth contacting them about it and see what they say. I'd be happy to talk to a technical contact there if you can find one to help.

**Comment by hoveeman** [comment] 2016-10-02 01:36
That sounds great! I started a thread on their forum linking back to here. 

http://community.covecube.com/index.php?/topic/2215-drivepool-issue-with-rclone/

**Comment by drashna** [comment] 2016-10-02 19:23
I'm tech support for Covecube (StableBit), but I'm not the developer. 

The pool drive is an emulated drive, but it passes through disk commands and return the response "normally" in most cases.  Chances are, there is a command being used that isn't being handled properly, or possible an issue with the read striping feature. 

Either way, I've already instructed hoveeman to grab logs for us, so we can see what is going on, and if it is something that *WE* need to fix. More than likely, this is the case,

**Comment by ncw** [comment] 2016-10-02 21:14
@drashna Great, glad to hear that you are on the case. Let me know if you want anything from me.

**Comment by drashna** [comment] 2016-10-03 17:40
@ncw It looks like this is specifically an issue with StableBit DrivePool's Read Striping feature.   

@hoveeman did some testing and disabling this feature does appear to fix the issue.  It's not a critical feature, but it is a performance optimization feature. So ideally, we'd want it left on. 

Specifically, it picks one disk over the other, or (whenever possible) reads from both disks, by reading chunks from each into the memory.  It seems that this process is what is causing the issue with rclone. 

For now, anyone with this issue should turn off the Read Striping feature (in DrivePool, under Pool Options -> Performance -> Read Striping), until we have a fix for the issue. 

I've flagged this issue internally, along with the logs that hoveeman grabbed for us. Once Alex (the developer for StableBit DrivePool) has had a chance to take a look at this, I'll post feedback here (or he will) as soon is there is some. (https://stablebit.com/Admin/IssueAnalysis/27201)

**Comment by ftruzzi** [comment] 2017-03-05 21:34
I have seen the same thing using rclone on Windows + encfs4win + one of the latest build of dokany. 

I'm encrypting a folder using encfs reverse and mapping it to a drive Z:, when I get a "corrupted on transfer: sizes differ" error. This has happened twice this afternoon while uploading large files to ACD, but before reaching 100% on each file.

I will post more info if/when it happens again, unfortunately my upload at home is quite slow so it could take a while.

**Comment by ncw** [comment] 2020-01-14 14:13
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.

**Closed by ncw** 2020-01-14 14:13 UTC
Labels: bug
