### ISSUE TITLE
Add Baidu Pan Disk as a source

### ISSUE THREAD

**Issue by testernav123** [rclone/rclone#4278] opened 2020-05-25 20:34 UTC
#### What is your current rclone version (output from `rclone version`)?
rclone --version
rclone v1.51.0
- os/arch: darwin/amd64
- go version: go1.13.7

#### What problem are you are trying to solve?
To add Baidu Pan (Baidu's web disk) to rclone

#### How do you think rclone should be changed to solve that?
Implement the Baidu disk support. They have a go-supported SDK - https://github.com/baidu/baiducloud-sdk-go 

Related forum post:
https://forum.rclone.org/t/add-baidu-pan-disk-as-a-source/16644

**Comment by ncw** [comment] 2020-05-26 11:29
I think this may be a duplicate of #2099 but I'm not sure. Are these talking about the same Baidu products?

The link above looks like the equivalent of azure blob/azure files, eg  Baidu Object Storage (BOS), Cloud Disk Service (CDS) - these seem to be different to Baidu Pan :confused:

**Comment by casteryh** [comment] 2020-06-14 07:02
@testernav123 mistakes the Baidu Cloud (百度智能云 as they branded it), which is essentially a Baidu version of Azure, as their Baidu Pan, which is for "average end user".

While he wants support for the latter product, the SDK is for the former one.

There are APIs of Baidu Pan from reverse engineering, but Baidu is actively blocking such usage AFAIK. Also note that many developers have stopped to work on reverse engineering Baidu Pan and stopped distributing their related works, since the arrest of the author of pandownloader.

**Comment by testernav123** [comment] 2020-06-14 09:25
Thank you both for the clarification.

And shocking about the arrest! We wouldn't want ncw to not be able to visit China in the future, and since there is no official API for the pan - I guess close the issue?

**Closed** 2020-06-17 14:56 UTC
Labels: enhancement: new backend
