### ISSUE TITLE
mail.ru: cannot unmarshal number NNN into Go struct field ListItem.body.list.mtime of type int64

### ISSUE THREAD

**Issue by dmak** [rclone/rclone#4229] opened 2020-05-13 22:09 UTC
rclone reports the following error when trying to synchronize with mail.ru cloud:
```
$ rclone sync ~/cloudmailru mailru:
2020/05/13 23:37:34 ERROR : Photos: error reading destination directory: json: cannot unmarshal number 18446744073709551615 into Go struct field ListItem.body.list.mtime of type int64
```

**rclone version:** v1.51.0 linux/amd64 go1.13.7
**OS:** Debian Linux x64
**cloud storage system:** [mail.ru cloud](https://rclone.org/mailru/)

**Comment by ncw** [comment] 2020-05-14 17:05
18446744073709551615 = 0xffffffffffffffff = 2**64-1

So changing the type to `uint64` would fix it. However  I think there is probably more to the solution than that...

What do you think @ivandeex ?

**Comment by ivandeex** [comment] 2020-05-17 18:15
@dmak

This constant looks like "-1" represented as a big unsigned int.
I have not seen this value from mail.ru yet, cannot tell for sure what thay mean by that.
This could mark something special about the file (file is wrong/recent/old etc)

As I can't reproduce your situation, let's investigate together using your files.
I have built a special rclone right for you, which will not fail but report files with strange time.
You can download it here: https://github.com/ivandeex/rclone/releases/tag/v1.51.timetest

Please run it like this `C:\path\to\timetest\rclone-windows-4.0-amd64.exe lsl mailru:`, notice file(s) reported like this:
`ERROR: Invalid time 18446744073709551615 for file "/path/to/strange/file"` and report it here.
We can later decide how to treat such files.

Please don't run `rclone sync` against your mailru files before we find out what this time means.

**Comment by dmak** [comment] 2020-05-18 00:51
I see the same error in the output:
```
2020/05/18 02:45:06 ERROR : []: Invalid time 18446744073709551615 for file "Photos/2015/20150718_154544.jpg"
```

**Comment by ivandeex** [comment] 2020-05-18 02:29
In this test build of rclone this "Error" message is in not an actual error but rather a warning. Rclone accepted invalid modification time returned by mail.ru and internally replaced it by "1970-01-01 00:00:00". I warned you against syncing because the file is treated as "very old" and could be overwritten by sync.

Now I ask you look again at `20150718_154544.jpg` and reason: when did you upload this file to mail.ru? Is it old or up-to-date?

**Comment by ivandeex** [comment] 2020-05-18 02:33
By the way, if you have access to https://cloud.mail.ru, please find there the file and tell me what modification time is shown?

**Comment by dmak** [comment] 2020-05-18 09:08
I have found out that locally this file also has timestamp 1 Jan 1970 and in the cloud it appears without date:
![image](https://user-images.githubusercontent.com/366965/82194138-a07aca80-98f6-11ea-97c2-7a148795c5c8.png)
The file was corrupted as well as timestamp was lost probably when this file was copied from one drive to another. Interestingly, online displaying also has some bugs when I click on History:
![image](https://user-images.githubusercontent.com/366965/82194911-d8364200-98f7-11ea-9ab1-a2f6d24cc683.png)

**Comment by ivandeex** [comment] 2020-05-19 20:06
I am going to have the fix merged soon.

**Closed** 2020-09-26 12:12 UTC
Labels: Remote: Mailru, bug

**Comment by dmak** [comment] 2022-11-07 10:29
The issue is sort of back:
```
panic: Invalid UInt64 -1                                                                                                                    
                                                                                                                                            
goroutine 73 [running]:                                                                                                                     
github.com/rclone/rclone/backend/mailru/api.(*BinWriter).WritePu64(0xc0006b97e8?, 0xc000d373b0?)
        github.com/rclone/rclone/backend/mailru/api/helpers.go:67 +0xe8
github.com/rclone/rclone/backend/mailru.(*Object).addFileMetaData(0xc0013c6420, {0x2334130?, 0xc000cf1280}, 0x1)
        github.com/rclone/rclone/backend/mailru/mailru.go:2061 +0x33c
github.com/rclone/rclone/backend/mailru.(*Object).Update(0xc0013c6420, {0x2334130, 0xc000cf1280}, {0x231f2a0, 0xc00238c600}, {0x7f7538811318, 0xc0011d3ec0}, {0xc002166b90, 0x1, 0x1})
        github.com/rclone/rclone/backend/mailru/mailru.go:1737 +0xf26
github.com/rclone/rclone/backend/mailru.(*Fs).Put(0xc0005c31e0, {0x2334130, 0xc000cf1280}, {0x231f2a0, 0xc00238c600}, {0x7f7538811318?, 0xc0011d3ec0?}, {0xc002166b90, 0x1, 0x1})
        github.com/rclone/rclone/backend/mailru/mailru.go:1598 +0x1d6
github.com/rclone/rclone/fs/operations.Copy({0x2334130, 0xc000cf1280}, {0x2345f40, 0xc0005c31e0}, {0x0?, 0x0?}, {0xc000ea0270, 0x2c}, {0x2345ed0, 0xc0011d3ec0})
        github.com/rclone/rclone/fs/operations/operations.go:501 +0x1b6e
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc0008c98c0, {0x2334130, 0xc000cf1280}, 0x0?, {0x2345f40, 0xc0005c31e0}, 0x0?, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:423 +0x1bb
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        github.com/rclone/rclone/fs/sync/sync.go:450 +0x45
```
Should I report it as a new issue?

**Comment by ncw** [comment] 2022-11-07 12:18
@dmak - please make a new issue and a way I can reproduce it if at all possible - thanks.
