### ISSUE TITLE
(OpenStack Swift) Server Side move files with chunks

### ISSUE THREAD

**Issue by cypua** [rclone/rclone#4215] opened 2020-05-09 17:21 UTC
#### What is your current rclone version (output from `rclone version`)?
1.51

#### What problem are you are trying to solve?
rclone handle the chunks for large files, but it's not possible to move or copy with server-side

#### How do you think rclone should be changed to solve that?
When rclone should move or copy large file with a manifest and chunks, it should move / copy the chunks and recreate a new manifest, not moving the whole file.

**Comment by animosity22** [comment] 2020-05-09 21:39
This is a duplicate of:

https://github.com/rclone/rclone/issues/515

**Closed by animosity22** 2020-05-09 21:39 UTC
