### ISSUE TITLE
bwlimit for upload and download

### ISSUE THREAD

**Issue by PiscisSwimeatus** [rclone/rclone#1873] opened 2017-12-02 13:08 UTC
Ability to define separate download and upload limits.

**Comment by ncw** [comment] 2017-12-03 10:34
A good idea, but not easy to implement due to the way rclone works.  I'll put it on the list though!

**Comment by PiscisSwimeatus** [comment] 2018-02-10 22:06
@ncw Any progress on this? Would be really great for Google Drive where there is a diffrence between download and upload limits. I currently have to "Manually" upload since I don't want to limit my mounts downloadspeed, but this screws with my mount cache. Would be much better if I can redirect everything to myt mount.

**Comment by vistalba** [comment] 2018-11-22 08:02
Oh.. just open a new request on this... sorry for that.
I also need separate limits for uploads. I'm on a async internet link and if I copy a file to the rclone mount, my upload is completly blocked so I can't surf on the web anymore for the time until the upload is finished.

Any ideas to solve this or update to this feature?

**Comment by ncw** [comment] 2018-11-23 20:33
> Any ideas to solve this or update to this feature?

I've used [the wondershaper](https://github.com/magnific0/wondershaper) on linux to solve this problem.  It is caused by rclone filling up the upload buffers in your router so the ACK packets needed for the downloads are blocked by them.  Wondershaper will allow the ACK packets to bypass the data transfer packets, keeping things running.

**Comment by Poltergeisen** [comment] 2020-05-29 20:07
Is wondershaper a way that I can utilize full gdrive download speed and limit upload speed specifically for rclone?

**Comment by ncw** [comment] 2020-05-30 15:22
> Is wondershaper a way that I can utilize full gdrive download speed and limit upload speed specifically for rclone?

You tune it for everything and then it will work for rclone or whatever.

**Comment by gfee** [comment] 2020-06-11 00:44
Thanks @ncw & others for the amazing rclone and for looking at this. With a 100/40 Mbps async connection at home this is my only feature request. I really like the colon-separated values idea. My only concern is that it may be easy to get it backwards! Is the natural order `up:down` or `down:up`?

To preserve backwards compatibility of the command, if the colon is omitted I suggest the limit apply to both. So `--bwlimit 2M` is equivalent to `--bwlimit 2M:2M`. If you include the colon but omit one then the omitted value is unlimited. So `--bwlimit 1M:` specifies a 1M upload limit but no limit on downloads. And `--bwlimit :` is equivalent to omitting the command altogether (but why??)

**Comment by ncw** [comment] 2020-06-11 20:46
> Thanks @ncw & others for the amazing rclone and for looking at this. With a 100/40 Mbps async connection at home this is my only feature request. I really like the colon-separated values idea. My only concern is that it may be easy to get it backwards! Is the natural order `up:down` or `down:up`?

Good question. Up:down is probably the natural English way of saying it. Down:up appeals to the programmer...

Probably up:down ...

This could potentially be signalled explicitly up=10M:down=1M perhaps overkill.

> To preserve backwards compatibility of the command, if the colon is omitted I suggest the limit apply to both. So `--bwlimit 2M` is equivalent to `--bwlimit 2M:2M`. 

That was my plan

> If you include the colon but omit one then the omitted value is unlimited. So `--bwlimit 1M:` specifies a 1M upload limit but no limit on downloads. And `--bwlimit :` is equivalent to omitting the command altogether (but why??)

You can also write off instead

My plan is to make the new bandwidth up:down be valid in all the bandwith timetable entries.

What bandwidth limit should a net to net transfer use? Presumably the minimum of the up and down. Same for local to local I suppose.

**Comment by gfee** [comment] 2020-06-12 04:07
Thanks @ncw. I think your convention of `up:down` is sensible and sufficient if backed up by the help docs. I agree that if `up:down` is specified for local-local or remote-remote transfers then using the minimum is the most logical thing to do.

**Comment by vistalba** [comment] 2020-12-01 15:25
any progress in this? I need this to as my upload speed is just around 4M and donwload ist around 12M so it doesn't make sense to limit 3M for downloads.

**Comment by ncw** [comment] 2020-12-07 17:31
I rebased where I've got to with this.

I think it is working but testing appreciated

[v1.54.0-beta.4959.d7c84b094.fix-4395-list-bwlimit](https://beta.rclone.org/branch/fix-4395-list-bwlimit/v1.54.0-beta.4959.d7c84b094.fix-4395-list-bwlimit/) on branch [fix-4395-list-bwlimit](https://github.com/rclone/rclone/tree/fix-4395-list-bwlimit) (uploaded in 15-30 mins)

Whenever you write a bandwidth `--bwlimit 100k` you can now write a pair `--bwlimit 10M:1M` which is upload:download.

**Comment by vistalba** [comment] 2020-12-08 10:53
@ncw First tests are looking good just with `--bwlimit 3M` and at this time I do not see such bursts of the upload anymore ... it looks smoother anyway. Until now I just run some rsync upload job. Looking well... one job at 2.99-3.00MB/s and as I started a second upload it rates both to appox. 1.5MB/s as expected!

Will now run it for some days to see if it's stable.

One question: You wrote about `--bwlimit 10M:1M` so this would be `upload:download`. Is this really the right way around? 
In our country the vice-versa notation is common so all ISPs advertise with `download:upload` speeds. (It isn't a issue just to be as clear as possible and not to mess things :))

**Comment by Poltergeisen** [comment] 2020-12-08 12:38
How would you limit upload but not download in this case?

**Comment by seuffert** [comment] 2020-12-08 12:50
> How would you limit upload but not download in this case?

`--bwlimit 10M:off`

Either limit can be "off" meaning no limit

**Comment by ncw** [comment] 2020-12-08 18:30
@vistalba wrote:
> First tests are looking good just with `--bwlimit 3M` and at this time I do not see such bursts of the upload anymore ... it looks smoother anyway. Until now I just run some rsync upload job. Looking well... one job at 2.99-3.00MB/s and as I started a second upload it rates both to appox. 1.5MB/s as expected!

Great

> Will now run it for some days to see if it's stable.

:+1: 

> One question: You wrote about `--bwlimit 10M:1M` so this would be `upload:download`. Is this really the right way around?
> In our country the vice-versa notation is common so all ISPs advertise with `download:upload` speeds. (It isn't a issue just to be as clear as possible and not to mess things :))

I chose that order because to a native English speaker up down up down sounds natural whereas down up down up doesn't.

I take your point about ISPs advertising their bandwidth as Download:Upload - in the UK ISPs only ever quote download though!

Is there any other prior Art on this?

**Comment by vistalba** [comment] 2020-12-20 12:15
Okay... after almost two weeks for me it runs stable and it doens't burst so much compared to 1.53.3.
I can see some small bursts in this too but... best is to not use to high values for `--buffer-size` and `--drive-chunk-size` I guess.
Or does this values not have any effect on uploads?

In our country the advertise alwas 100M/30M (download/upload) in that way. But I don't know how it is in other countries. It was just something that for me it wan't logic. But as long as it is mentioned in the documentation I think it should be fine.

**Comment by Rootax** [comment] 2021-01-29 11:45
Hello,

Is this fix / commit in the regular beta now ? I don't believe so but maybe I'm not looking correctly.

Thx :)

**Comment by ncw** [comment] 2021-01-30 17:40
It isn't in the regular beta yet and it should be... I will prepare it for merging - thanks for the reminder!

**Comment by LeendertPlas** [comment] 2021-01-30 18:55
can i download this beta release somewhere?

I tried to make the build myself but awk returns an error on windows as the quotation marks are different, so it wouldn't run :(

**Comment by whichken** [comment] 2021-01-30 19:14
> can i download this beta release somewhere?
> 
> I tried to make the build myself but awk returns an error on windows as the quotation marks are different, so it wouldn't run :(

https://beta.rclone.org/branch/fix-4395-list-bwlimit/v1.54.0-beta.4959.d7c84b094.fix-4395-list-bwlimit/

**Comment by LeendertPlas** [comment] 2021-01-30 19:15
thank you!!!

**Comment by LeendertPlas** [comment] 2021-01-30 19:25
i think something went wrong with merging it as i get an error when trying to use this functionaliity.

`2021/01/30 20:23:36 Fatal error: invalid argument "4K:100K" for "--bwlimit" flag: strconv.ParseFloat: parsing "4K:100": invalid syntax`

**Comment by ncw** [comment] 2021-01-30 19:43
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

**Closed** 2021-01-30 19:44 UTC
Labels: bandwidth, enhancement

**Comment by LeendertPlas** [comment] 2021-01-31 13:09
I think this update causes the gui to keep crashing. Every time i start the service, i get updating errors that i can't fetch the latest release of Web Gui which hasn't even been updated in some time. It is also strange that it is a fatal error.


`2021/01/31 13:52:57 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:52:59 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:53:03 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:53:12 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:53:28 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:54:00 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:55:05 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:57:13 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 13:59:21 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:01:29 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:03:38 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:03:55 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:03:55 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:03:57 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:04:02 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:04:10 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:04:26 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:04:58 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:06:03 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:06:49 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:06:51 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:06:55 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
2021/01/31 14:07:04 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest`

**Comment by ncw** [comment] 2021-02-01 10:48
> I think this update causes the gui to keep crashing. Every time i start the service, i get updating errors that i can't fetch the latest release of Web Gui which hasn't even been updated in some time. It is also strange that it is a fatal error.

Is it still doing that @LeendertPlas  ? I think the update and that error are unconnected.

**Comment by LeendertPlas** [comment] 2021-02-01 14:17
i have disabled the gui function for now in my startup command, but the beta version is very unstable for me. I keep getting a memory error after some time. Then the instance restarts but in a paused state. 

This is a part of my error log. the real file for a single day is 40mb so i can't include the entire file. It seems there is a memory leak or failure as the exact same thing does work in the main version. But as i would like to use the bwlimit for uploading i have to use the beta version.
[error.txt](https://github.com/rclone/rclone/files/5904403/error.txt)

**Comment by ncw** [comment] 2021-02-02 10:32
@LeendertPlas that log is definitely an out of memory problem.

What are the parameters to `rclone mount`? I suspect you have a very large value for `--buffer-size` which is using all your memory.

**Comment by LeendertPlas** [comment] 2021-02-02 10:38
this is my stable one:
`nssm get "Rclone Mount2" AppParameters

mount --allow-other --dir-cache-time 1440m --buffer-size 600M --log-level INFO --poll-interval 15s gdrive: X: --config C:\Plex\Rclone2\rclone.conf --cache-dir=D:\Rclone\Cache3 --vfs-cache-mode writes --vfs-cache-max-size 1500G --vfs-cache-max-age 24h --bwlimit-file 20M --bwlimit 3M --no-traverse --drive-stop-on-upload-limit --log-file=C:\Plex\Rclone2\error.txt
`

This is the beta one that keeps generating memory errors:
`c:\Plex\Rclone>nssm get "Rclonebeta" AppParameters

mount --allow-other --dir-cache-time 1440m --buffer-size 600M --log-level INFO --poll-interval 15s gdrive: X: --config C:\Plex\Rclone2\rclone.conf --cache-dir=D:\Rclonebeta\Cache --vfs-cache-mode writes --vfs-cache-max-size 1500G --vfs-cache-max-age 24h --bwlimit-file 20M --bwlimit 4M:off --no-traverse --drive-stop-on-upload-limit --log-file=C:\Plex\Rclone2\error2.txt`

The buffer size is the same, so i don't understand why it would behave differently.

**Comment by ncw** [comment] 2021-02-02 18:39
> The buffer size is the same, so i don't understand why it would behave differently. Can it somehow interpret the buffer-size 'M' incorrectly? I can also remove it if it doesn't impact performance that much.

What `--buffer-size 600M` means is allocate 600 Mbytes of memory for each open file. This adds up really quickly! I suggest you remove it and see if performance is affected. The default is 16M which should be enough for most purposes.

**Comment by LeendertPlas** [comment] 2021-02-03 10:08
thank you. It seems to be stable for now but it does respond slower.

 I also still don't understand why the same variable would have different behaviour in the beta version and the normal version. So something has to have regressed in this respect.

**Comment by ncw** [comment] 2021-02-03 13:13
> thank you. It seems to be stable for now but it does respond slower.

Good.
 
> I also still don't understand why the same variable would have different behaviour in the beta version and the normal version. So something has to have regressed in this respect.

Memory allocation is somewhat random. I expect you were just below before and the beta allocates things in a different order and put you just above...
