### ISSUE TITLE
How do I do server-side-copy from same name folder to another folder outside?

### ISSUE THREAD

**Issue by quekky** [rclone/rclone#3183] opened 2019-05-11 03:55 UTC
For example, a Google Drive user shares two folders that have the same name. I want to copy all the files from both folders. How do I do that?

```
rclone ls remote: --drive-shared-with-me
111 samedir/file1.txt
122 samedir/file2.txt

rclone ls remote: --drive-root-folder-id {ID1}
111 file1.txt

rclone ls remote: --drive-root-folder-id {ID2}
122 file2.txt

rclone copy -vv remote: --drive-root-folder-id {ID1} remote:anotherdir/
ERROR : file1.txt: Failed to copy: failed to make directory: googleapi: Error 403: Forbidden, forbidden

rclone copy -vv remote: --drive-root-folder-id {ID2} remote:anotherdir/
ERROR : file2.txt: Failed to copy: failed to make directory: googleapi: Error 403: Forbidden, forbidden

```

_I think it seems that the destination points the same shared folder (using the folder-id), instead of starting from the root_

**Comment by ncw** [comment] 2019-05-11 16:57
The problem is that the `--drive-root-folder-id {ID1}` is applying to both source and destination.

If you make two remotes `src` and `dst` say, then you can use environment variables to target which one you want, so

    RCLONE_CONFIG_DST_DRIVE_ROOT_FOLDER_ID=xxx

Here are the docs on [setting environment variables](https://rclone.org/docs/#config-file).

**Comment by animosity22** [comment] 2020-01-12 18:08
This was answered. Closing out.

**Closed by animosity22** 2020-01-12 18:08 UTC
