### ISSUE TITLE
Chunker resume by checking existing chunks.

### ISSUE THREAD

**Issue by BizClimb** [rclone/rclone#4999] opened 2021-02-06 18:28 UTC
#### What is your current rclone version (output from `rclone version`)?
rclone v1.54.0-beta.5136.0d8bcc08d

#### What problem are you are trying to solve?
Have chunker restart where left off in case of issue interruption or other unexpected issues during large time consuming transfers.

#### How do you think rclone should be changed to solve that?
I've been trying to upload a 500GB file for a few days now, and opendrive limits files to 100G, but opendrive seems to be very buggy with its back end. If something goes wrong with the transfer the entire time consuming procedure needs to be restarted.
Chunker seems to be an "almost completely solved" solution for this, with the exception that if the procedure gets broken either manually cancelled or something else, there is no way to pickup where it left off.

I currently solve this by splitting the file locally into many parts (basically what chunker does but locall first via 7zip) then I can upload and rclone will check if the existing "part" exists or not and can essentially "resume" with unfinished chunks.

Is it possible to integrate the "chunk" check directly into rclone either globally or via an option so it can check if a chunk already exists (Filesize/Hash/etc..) and begin where it left off?

**Comment by ivandeex** [comment] 2021-02-06 23:48
Duplicate of https://github.com/rclone/rclone/issues/87
Put your thumbs up there
Using chunker for resumable uploads was proposed by https://github.com/rclone/rclone/issues/87#issuecomment-671506822 and discussed elsewhere
The feature is in works, no ETA yet

**Closed by ivandeex** 2021-02-06 23:48 UTC
