### ISSUE TITLE
googlephotos: gracefully handling 401 UNAUTHENTICATED or 403 Forbidden

### ISSUE THREAD

**Issue by philips** [rclone/rclone#4396] opened 2020-06-29 17:05 UTC
#### What is the problem you are having with rclone?

At some point during my (long running) transfers I will start to get 401 UNAUTHENTICATED or 403 Forbidden in my logs. I think it depends on whether rclone is talking to the Google Photos API or fetching a media item.

#### What is your rclone version (output from `rclone version`)

1.52.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

docker image on raspberryos

####  Which cloud storage system are you using? (eg Google Drive)

googlephotos

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
copy photos:/media/by-month/ /data
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
{"level":"error","msg":"error reading source directory: couldn't list files: Request had invalid authentication credentials
. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/i
dentity/sign-in/web/devconsole-project. (401 UNAUTHENTICATED)","object":"2015/2015-06","objectType":"string","source":"marc
h/march.go:400","time":"2020-06-29T06:58:03.548214+00:00"}    
```

Very truncated log line because the media APIs return a very verbose HTML page.

```
{"level":"error","msg":"Failed to copy: failed to open source object: \u003c!DOCTYPE html\u003e\u003chtml... Error 403 (Forbidden) ... Your client does not have permis... from this server.  (Client IP address: 23.242.200.52)\u003cbr\u003e\u003cbr\u003e\nForbi$
den...That’s all we know.\u003c/ins\u003e (403 403 Forbidden)","object":"20/2020-04/00100lrPORTRAIT_00100_BURST20200424125154988_COVER.jpg","objectType":"*googlephotos.Object","source":"operation$
/operations.go:466","time":"2020-06-29T16:53:46.232323+00:00"}
```

**Comment by philips** [comment] 2020-06-29 17:06
I am still investigating this but some hunches:

1. Do we need to get a new auth token?
2. Should rclone just exit and let the user handle this?
3. ???

**Comment by ncw** [comment] 2020-07-01 22:26
That is weird!

Rclone should automatically get a new auth token. There should be debug logs about this you should be able to find. I wonder if this failed and the token expired?

**Comment by philips** [comment] 2020-07-01 23:07
One odd thing about my setup: I am building a hosted web application that
then generates the rclone.conf and runs rclone. Maybe something about that
workflow breaks rclone's renew pipeline?

I can't see anything obvious but open to hints!

**Comment by achembarpu** [comment] 2020-07-02 13:42
I'm facing the same issue, running rclone from command-line (or cron/systemd).
The issue is API usage limits, as far as I can tell. Is exponential backoff implemented for this backend, similar to the Google Drive one?

**Comment by philips** [comment] 2020-07-02 15:31
I think the first thing I am going to do is for debugging is to modify rclone to: on a media 403, attempt an OAUTH renew, and retry the request with the new token. 

The challenge is that it seems to take 20 minutes to an hour to hit this case; it is going to be really annoying to debug.

I wonder if this is some sort of new API limit introduced by the [recent redesign](https://www.blog.google/products/photos/redesigned-google-photos/)

**Comment by ncw** [comment] 2020-07-02 18:02
@philips & @achembarpu - a joint reply!

> Maybe something about that workflow breaks rclone's renew pipeline?

Rclone saves the token in the rclone.conf after it renews it. If rclone can't write to the config, I'm not sure what will happen.

> The issue is API usage limits, as far as I can tell. Is exponential backoff implemented for this backend, similar to the Google Drive one?

The remote does implement exponential backoff. Are you using your own client_id? Rclone's may well be overloaded - I keep applying for more quota but I may need to do so again.



> I think the first thing I am going to do is for debugging is to modify rclone to: on a media 403, attempt an OAUTH renew, and retry the request with the new token.

Worth a try! Let me know how it goes.



> I wonder if this is some sort of new API limit introduced by the [recent redesign](https://www.blog.google/products/photos/redesigned-google-photos/)

As far as I know the google photos web app doesn't use the API - it can do lots of stuff you can't do via the API..

**Comment by achembarpu** [comment] 2020-07-02 20:06
Hi @ncw!

I am indeed using my own client_id. I suspect that I am reaching the limits because I am trying to clone my entire gphotos, for my initial backup. For now, I've resorted to running it until I hit the message and then waiting until it unrestricts me again.

BTW Is there any way to disable the "by-day, by-month" trees entirely to save storage space? And does rclone download the image just once, and clone it across all three "by-*" trees?

Thanks!

**Comment by philips** [comment] 2020-07-02 20:13
Yes I am using my own client id.

I will double check the perms for the config, good idea.

I am doing full backups of photos as well. I just do by-month tree. There
isn't much purpose to doing all of them.

**Comment by ncw** [comment] 2020-07-04 10:42
> BTW Is there any way to disable the "by-day, by-month" trees entirely to save storage space? And does rclone download the image just once, and clone it across all three "by-*" trees?

These are just different views into the same data so you should only do one.

They will also have the photos which are in albums duplicated too.

**Comment by achembarpu** [comment] 2020-07-04 17:28
Understood. Thanks so much for rclone!

**Comment by ncw** [comment] 2020-07-06 12:44
Is there anything to fix on this issue, or shall I close it?

**Comment by achembarpu** [comment] 2020-07-06 13:34
I think that there is scope for rclone to handle this error more gracefully though. Right now, it just leads to infinite error messages, since the API rate limiting is in place and rclone is still constantly hitting it. Maybe rclone can exit with an error instead?

**Comment by ncw** [comment] 2020-07-06 14:33
Hmm...

- 401 UNAUTHENTICATED - is a request to get a new token - I'm guessing this is failing though - do you see token requests if you do a `-vv --dump headers`?
- 403 Forbidden probably means the token has expired.

So both of these point to some sort of auth problem as @philips originally suggested.

Do debug further we need a log with `-vv --dump headers` of the problem I think....

**Comment by philips** [comment] 2020-07-06 14:42
I am going to be AFK for the next 2-3 weeks so I won't be able to
personally debug further.

**Comment by animosity22** [comment] 2020-10-21 16:58
If you want to post on the forum, please do.

https://forum.rclone.org as this looks to be very stale.

You can test with the latest and see how that works as well!

**Closed by animosity22** 2020-10-21 16:58 UTC
Labels: Remote: Google Photos, question
