### ISSUE TITLE
mega: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#3055] opened 2019-03-15 21:17 UTC
#### What is the problem you are having with rclone?
I tried to get the list of current folders via lsd command, and I ran into a runtime error while doing so. The message I got was "panic: runtime error: index out of range"
Here's the log from the terminal:

```
goroutine 1 [running]:
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).addFSNode(0xc000375400, 0xc043c81390, 0x8, 0xc043c81398, 0x8, 0xc043c813a0, 0xb, 0x0, 0xc0439636b0, 0x2b, ...)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:724 +0x1545
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).getFileSystem(0xc000375400, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:834 +0x35c
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).Login(0xc000375400, 0xc000200de7, 0x19, 0xc0003b0790, 0xf, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:575 +0xc5
github.com/ncw/rclone/backend/mega.NewFs(0x7fffa8e7a7c7, 0x2, 0x7fffa8e7a7c7, 0x0, 0x14161c0, 0xc00034d080, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/backend/mega/mega.go:207 +0x599
github.com/ncw/rclone/fs.NewFs(0x7fffa8e7a7c7, 0x3, 0xc00012f200, 0x7fffa8e7a7c7, 0x2, 0x7fffa8e7a7c7)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/fs.go:1058 +0xb5
github.com/ncw/rclone/cmd.NewFsFile(0x7fffa8e7a7c7, 0x3, 0x129, 0xc0003c4a80, 0xc000266c00, 0xc00032dbf8)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:86 +0x92
github.com/ncw/rclone/cmd.newFsFileAddFilter(0x7fffa8e7a7c7, 0x3, 0xc00032dca8, 0xe2aa93, 0xc0001a5300, 0xc00032dcd0)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:104 +0x4d
github.com/ncw/rclone/cmd.NewFsSrc(0xc0002db6a0, 0x1, 0x1, 0xc0002db6a0, 0x1)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:126 +0x41
github.com/ncw/rclone/cmd/lsd.glob..func1(0x1db6780, 0xc0002db6a0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/lsd/lsd.go:53 +0x9c
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x1db6780, 0xc0002db650, 0x1, 0x1, 0x1db6780, 0xc0002db650)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1db0d40, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x1db0d40, 0xc000090058, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/ncw/rclone/cmd.Main()
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:480 +0x46
main.main()
	/home/travis/gopath/src/github.com/ncw/rclone/rclone.go:13 +0x20
```

#### What is your rclone version (output from `rclone version`)
rclone v1.46
os/arch: linux/amd64
go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
 Ubuntu 18.10 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
Mega.nz

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd aK:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/03/15 21:10:52 DEBUG : rclone: Version "v1.46" starting with parameters ["rclone" "-vv" "lsd" "ak:"]
2019/03/15 21:10:52 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).addFSNode(0xc000377400, 0xc043c0b3a0, 0x8, 0xc043c0b3a8, 0x8, 0xc043c0b3b0, 0xb, 0x0, 0xc0438ed6b0, 0x2b, ...)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:724 +0x1545
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).getFileSystem(0xc000377400, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:834 +0x35c
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).Login(0xc000377400, 0xc00020ae47, 0x19, 0xc0003b2860, 0xf, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:575 +0xc5
github.com/ncw/rclone/backend/mega.NewFs(0x7ffdf4eaf7c7, 0x2, 0x7ffdf4eaf7c7, 0x0, 0x14161c0, 0xc00034f0e0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/backend/mega/mega.go:207 +0x599
github.com/ncw/rclone/fs.NewFs(0x7ffdf4eaf7c7, 0x3, 0xc0000711a0, 0x7ffdf4eaf7c7, 0x2, 0x7ffdf4eaf7c7)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/fs.go:1058 +0xb5
github.com/ncw/rclone/cmd.NewFsFile(0x7ffdf4eaf7c7, 0x3, 0x129, 0xc0003c6a80, 0xc000270c00, 0xc000335bf8)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:86 +0x92
github.com/ncw/rclone/cmd.newFsFileAddFilter(0x7ffdf4eaf7c7, 0x3, 0xc000335ca8, 0xe2aa93, 0xc0001b1300, 0xc000335cd0)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:104 +0x4d
github.com/ncw/rclone/cmd.NewFsSrc(0xc00034c6c0, 0x1, 0x2, 0xc00034c6c0, 0x1)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:126 +0x41
github.com/ncw/rclone/cmd/lsd.glob..func1(0x1db6780, 0xc00034c6c0, 0x1, 0x2)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/lsd/lsd.go:53 +0x9c
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x1db6780, 0xc00034c620, 0x2, 0x2, 0x1db6780, 0xc00034c620)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1db0d40, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x1db0d40, 0xc00008e058, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/ncw/rclone/cmd.Main()
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:480 +0x46
main.main()
	/home/travis/gopath/src/github.com/ncw/rclone/rclone.go:13 +0x20
```

**Comment by ncw** [comment] 2019-03-16 10:53
Do any other rclone commands work?  I'm guessing not.

Did it ever work?

This could possibly be relevant: https://github.com/ncw/rclone/issues/2480

Try logging into that account on mega.nz  - then try rclone again - does that help?

Can you send the result of

    rclone -vv lsd ak: --dump bodies

Thanks

**Comment by rabe398** [comment] 2019-03-16 16:56
None of the other commands work. I tried using MegCMD and it worked for me. Logging into the website didn't help, I guess the runtime error happens because I have too many files on my drive. I have a 8 TB account, and about 3000 folders , 687520 files.
Here's the result of the command "rclone -vv lsd ak: --dump bodies"
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x127f1ac, 0x16)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:608 +0x72 fp=0x7ffe39de0310 sp=0x7ffe39de02e0 pc=0x42c122
runtime.sysMap(0xc000000000, 0x4000000, 0x1de6a18)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mem_linux.go:156 +0xc7 fp=0x7ffe39de0350 sp=0x7ffe39de0310 pc=0x417347
runtime.(*mheap).sysAlloc(0x1dccea0, 0x4000000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:619 +0x1c7 fp=0x7ffe39de03d8 sp=0x7ffe39de0350 pc=0x40b247
runtime.(*mheap).grow(0x1dccea0, 0x1, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:920 +0x42 fp=0x7ffe39de0430 sp=0x7ffe39de03d8 pc=0x423692
runtime.(*mheap).allocSpanLocked(0x1dccea0, 0x1, 0x1de6a28, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:848 +0x337 fp=0x7ffe39de0470 sp=0x7ffe39de0430 pc=0x423517
runtime.(*mheap).alloc_m(0x1dccea0, 0x1, 0x2a, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:692 +0x119 fp=0x7ffe39de04b0 sp=0x7ffe39de0470 pc=0x422d29
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:759 +0x4c fp=0x7ffe39de04e8 sp=0x7ffe39de04b0 pc=0x457e6c
runtime.(*mheap).alloc(0x1dccea0, 0x1, 0x1002a, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:758 +0x8a fp=0x7ffe39de0538 sp=0x7ffe39de04e8 pc=0x422fca
runtime.(*mcentral).grow(0x1dcec58, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mcentral.go:232 +0x94 fp=0x7ffe39de0580 sp=0x7ffe39de0538 pc=0x416d44
runtime.(*mcentral).cacheSpan(0x1dcec58, 0x7efcfd1a6000)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mcentral.go:106 +0x2f8 fp=0x7ffe39de05c8 sp=0x7ffe39de0580 pc=0x416898
runtime.(*mcache).refill(0x7efcfd1a6000, 0x2a)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mcache.go:122 +0x95 fp=0x7ffe39de05f8 sp=0x7ffe39de05c8 pc=0x416455
runtime.(*mcache).nextFree.func1()
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:749 +0x32 fp=0x7ffe39de0618 sp=0x7ffe39de05f8 pc=0x457282
runtime.(*mcache).nextFree(0x7efcfd1a6000, 0x1de6a2a, 0x4000, 0x7efcfd1a6000, 0x7ffe39de06d8)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:748 +0xb6 fp=0x7ffe39de0670 sp=0x7ffe39de0618 pc=0x40b8f6
runtime.mallocgc(0x180, 0x125e000, 0x7ffe39de0701, 0x7efcfd1aa000)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:903 +0x793 fp=0x7ffe39de0710 sp=0x7ffe39de0670 pc=0x40c243
runtime.newobject(0x125e000, 0x1de6a80)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:1032 +0x38 fp=0x7ffe39de0740 sp=0x7ffe39de0710 pc=0x40c628
runtime.malg(0x7efc00008000, 0x7efcfd1a6000)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:3285 +0x31 fp=0x7ffe39de0780 sp=0x7ffe39de0740 pc=0x435661
runtime.mpreinit(0x1dc7980)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/os_linux.go:311 +0x29 fp=0x7ffe39de07a0 sp=0x7ffe39de0780 pc=0x42a559
runtime.mcommoninit(0x1dc7980)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:624 +0xc1 fp=0x7ffe39de07d8 sp=0x7ffe39de07a0 pc=0x42ef71
runtime.schedinit()
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:546 +0x89 fp=0x7ffe39de0840 sp=0x7ffe39de07d8 pc=0x42ec39
runtime.rt0_go(0x7ffe39de0878, 0x6, 0x7ffe39de0878, 0x0, 0x0, 0x6, 0x7ffe39de27a4, 0x7ffe39de27ab, 0x7ffe39de27af, 0x7ffe39de27b3, ...)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:195 +0x11a fp=0x7ffe39de0848 sp=0x7ffe39de0840 pc=0x459efa

**Comment by rabe398** [comment] 2019-03-18 19:56
Any updates?

**Comment by ncw** [comment] 2019-03-18 22:28
Ok here is something for you to try

https://beta.rclone.org/branch/v1.46.0-103-gf79d46b0-fix-3055-mega-crash-beta/ (uploaded in 15-30 mins)

This attempts to skip the bad items.

It should log things with `-v` can you paste the logs here?

**Comment by rabe398** [comment] 2019-03-18 23:17
I'm guessing it still hasn't updated, so I will wait.
What does it do exactly and what do you mean by "skip the bad items." like skip files ? I though the reason for the crash was  out of memory

**Comment by ncw** [comment] 2019-03-19 10:13
> I'm guessing it still hasn't updated, so I will wait.

Many apologies, I forgot to push the branch.  It should be there in 15-30 mins.

> What does it do exactly and what do you mean by "skip the bad items." like skip files ? I though the reason for the crash was out of memory

The original crash `panic: runtime error: index out of range` is caused by an item rclone doesn't understand I think - this patch attempts to skip that item.  I don't know whether that will work though!

**Comment by rabe398** [comment] 2019-03-19 21:43
Thanks for helping me out.
The script would just get stuck
Here is the log from the terminal:
2019/03/19 23:41:53 DEBUG : *go-mega*: Retry API request 1/10: Try again
2019/03/19 23:41:53 DEBUG : *go-mega*: Retry API request 2/10: Try again
2019/03/19 23:41:53 DEBUG : *go-mega*: Retry API request 3/10: Try again
2019/03/19 23:41:53 DEBUG : *go-mega*: Retry API request 4/10: Try again
2019/03/19 23:41:53 DEBUG : *go-mega*: Retry API request 5/10: Try again
2019/03/19 23:41:53 DEBUG : *go-mega*: Retry API request 6/10: Try again
2019/03/19 23:41:54 DEBUG : *go-mega*: Retry API request 7/10: Try again
2019/03/19 23:41:54 DEBUG : *go-mega*: Retry API request 8/10: Try again
2019/03/19 23:41:56 DEBUG : *go-mega*: Retry API request 9/10: Try again
2019/03/19 23:41:58 DEBUG : *go-mega*: Retry API request 10/10: Try again

**Comment by rabe398** [comment] 2019-03-19 21:46
I think there's somethin wrong with the mega server, I can't login via megacmd or my phone. I will try again later, will keep you updated

**Comment by rabe398** [comment] 2019-03-19 22:10
The script failed, here's the log from the console. I omitted sensitive information
--------------------------------------------------------
2019/03/20 00:00:16 DEBUG : rclone: Version "v1.46.0-103-gf79d46b0-fix-3055-mega-crash-beta" starting with parameters ["rclone" "-vv" "lsd" "me:"]
2019/03/20 00:00:16 DEBUG : Using config file from "C:\\Users\\Wind\\.config\\rclone\\rclone.conf"
2019/03/20 00:05:02 INFO  : *go-mega*: ignoring item: compkey too short (0): mega.FSNode{Hash:"##DELETED##", Parent:"##DELETED##", User:"##DELETED##", T:0, Attr:"##DELETED##", Key:"##DELETED##", Ts:##DELETED##, SUser:"", SKey:"", Sz:##DELETED##}
2019/03/20 00:05:02 INFO  : *go-mega*: ignoring item: compkey too short (0): mega.FSNode{Hash:"##DELETED##", Parent:"##DELETED##", User:"##DELETED##", T:0, Attr:"##DELETED##", Key:"##DELETED##", Ts:##DELETED##, SUser:"", SKey:"", Sz:##DELETED##}
2019/03/20 00:05:07 INFO  : *go-mega*: ignoring item: compkey too short (0): mega.FSNode{Hash:"##DELETED##", Parent:"##DELETED##", User:"##DELETED##", T:0, Attr:"##DELETED##", Key:"##DELETED##", Ts:##DELETED##, SUser:"", SKey:"", Sz:##DELETED##}
2019/03/20 00:05:07 INFO  : *go-mega*: ignoring item: compkey too short (0): mega.FSNode{Hash:"##DELETED##", Parent:"##DELETED##", User:"##DELETED##, T:0, Attr:"##DELETED##, Key:"##DELETED##", Ts:##DELETED##, SUser:"", SKey:"", Sz:##DELETED##}
2019/03/20 00:05:09 Failed to create file system for "me:": couldn't login: Block decryption failed

**Comment by rabe398** [comment] 2019-03-21 07:16
Will it help if I contact mega support for help regarding this matter?

**Comment by ncw** [comment] 2019-03-21 22:06
> Will it help if I contact mega support for help regarding this matter?
> I really appreciate it for taking the time to help me out to solve this bug

Probably not because rclone is not a supported client.  You could ask whether there is something odd about your account I suppose.

> EDIT: I tried another account with 4 TB of storage, it worked. There's something wrong with this 8 TB account, it works on megacmd and not on your script

The problem with rclone's mega support is that is was reverse engineered from the C++ megacmd source.  Mega don't publish any specifications alas.  That probably means that there is a bug but it is in the rclone source, or more precisely in the [go-mega library](https://travis-ci.org/t3rm1n4l/go-mega).

I don't know how your C++ & Go is, but digging into that library and finding out exactly where the problem is and comparing it with the C++ implementation is the way forward.

Would it be possible for me to be able to access your account for a while?  That would help a lot!  If you feel comfortable with that then drop me an email to nick@craig-wood.com with "rclone issue #3055" in the subject.

**Comment by rabe398** [comment] 2019-03-22 01:04
I'm sorry buddy I can't give you my account, the stuff that I have on my account are vital for my business, I can't share them with anyone.
If you have another solution, I'm all ears.
Thank you  very much for the help. I will try to import about 4 TB of stuff into another account and see if the script will work after I import them into the new account. That's the only solution I could think of at this moment

**Comment by ncw** [comment] 2019-03-25 16:33
> I'm sorry buddy I can't give you my account, the stuff that I have on my account are vital for my business, I can't share them with anyone.

Understood :-)

> Sadly my c++ knowledge is pretty basic, I only studied one course.

Not my favourite language either!

> If you have another solution, I'm all ears.

I can't think of one at the moment.... I (or another developer) really need access to an account which has the problem...

> Thank you very much for the help. I will try to import about 4 TB of stuff into another account and see if the script will work after I import them into the new account. That's the only solution I could think of at this moment

That is worth a try certainly.

**Comment by caspertone2003** [comment] 2019-04-10 15:07
@ncw 

My situation seems to have some common elements

https://forum.rclone.org/t/failed-to-create-file-system-for-remote-folder-couldnt-login-try-again/9501

I send you a PM with rclone issue #3055 sharing the failing remote account.

TIA

**Comment by ncw** [comment] 2019-10-26 18:01
The crash is fixed so I'm going to close this issue.

Mega use might be better served by https://github.com/rclone/rclone/issues/3660

**Closed by ncw** 2019-10-26 18:01 UTC
Labels: Remote: Mega, bug
