### ISSUE TITLE
mail.ru cloud Unknown resource type "camera-upload"

### ISSUE THREAD

**Issue by kuhytitusdlz** [rclone/rclone#4025] opened 2020-03-02 09:41 UTC
![Image 121](https://user-images.githubusercontent.com/15821799/75664477-96e0af80-5c83-11ea-89f0-28b67d96e3e6.png)
Hi,

I get blank list:
```
C:\rclone>rclone --log-file=rclone.log --log-level DEBUG lsd test-mail:/

C:\\rclone>
````
log-file:
```
2020/03/02 12:35:37 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "--log-file=rclone.log" "--log-level" "DEBUG" "lsd" "test-mail:/"]
2020/03/02 12:35:37 DEBUG : Using config file from "C:\\rclone\\rclone.conf"
2020/03/02 12:35:38 DEBUG : []: Excluding path "/Camera Uploads" from list: Unknown resource type "camera-upload"
2020/03/02 12:35:38 DEBUG : 5 go routines active
2020/03/02 12:35:38 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["rclone" "--log-file=rclone.log" "--log-level" "DEBUG" "lsd" "test-mail:/"]
```

**Comment by ncw** [comment] 2020-03-03 10:07
> 2020/03/02 12:35:38 DEBUG : []: Excluding path "/Camera Uploads" from list: Unknown resource type "camera-upload"

That is because the "Camera Uploads" object has reported itself as being a "camera-upload" instead of being a "file" or a "folder".

Maybe we could treat it as a "folder" I don't know - what do you think @ivandeex ?

**Comment by shvchk** [comment] 2020-04-13 21:37
Temporary workaround is to make a copy of this folder via web interface (make sure you have enough free space), use rclone to copy/sync that copied folder, then you can delete it (to free used space).

**Comment by Kabachek** [comment] 2020-05-03 19:01
Hi.
This also affects folders that's shared with other accounts:
`2020/05/03 16:11:29 DEBUG : []: Excluding path "/CUBE" from list: Unknown resource type "shared"
`

**Comment by ivandeex** [comment] 2020-05-17 18:54
@kuhytitusdlz @shvchk @Kabachek 
Please run beta rclone from https://github.com/ivandeex/rclone/releases/tag/v1.51.cameraupload and report whether it solves your problem.

**Comment by Kabachek** [comment] 2020-05-18 10:31
Running beta on my NB, not on target system (mipsle needed for that)
<pre>
2020/05/18 13:18:01 DEBUG : rclone: Version "v1.51.0-DEV" starting with parameters ["rclone-windows-4.0-amd64.exe" "-vv" "--log-file=rclone-log.txt" "--use-mmap" "size" "mailru:/"]
2020/05/18 13:18:01 DEBUG : Using config file from "C:\\Users\\User\\.config\\rclone\\rclone.conf"
2020/05/18 13:18:01 DEBUG : fs cache: renaming cache item "mailru:/" to be canonical "mailru:"
2020/05/18 13:18:05 ERROR : Camera Uploads: error listing: is a file not a directory
2020/05/18 13:18:17 DEBUG : 21 go routines active
2020/05/18 13:18:17 Failed to size with 2 errors: last error was: is a file not a directory
</pre>

**Comment by ivandeex** [comment] 2020-05-18 13:40
@Kabachek
Please try another beta from https://github.com/ivandeex/rclone/releases/tag/v1.51.cameraupload2
Now it treats share/camera-upload items as files.
I'm still wondering how to reproduce camera uploads. Can I install some Android app and tap something?

**Comment by Kabachek** [comment] 2020-05-18 17:22
> I'm still wondering how to reproduce camera uploads. Can I install some Android app and tap something?

Yep, Mail.ru have it's own app in GPlay [https://play.google.com/store/apps/details?id=ru.mail.cloud](url) 
In the android application, you should select the "Auto load" option or something similar. But i'm not sure, because i have iOS.

Well, when i check the root dir size, it's still exclude:
<pre>C:\Users\User\Downloads\rclone>rclone-windows-4.0-amd64.exe -vv --use-mmap size mailru:

2020/05/18 19:46:54 DEBUG : rclone: Version "v1.51.0-DEV" starting with parameters ["rclone-windows-4.0-amd64.exe" "-vv" "--use-mmap" "size" "mailru:"]
2020/05/18 19:46:54 DEBUG : Using config file from "C:\\Users\\User\\.config\\rclone\\rclone.conf"
2020/05/18 19:46:54 INFO  : []: Valid token not found, authorizing.
2020/05/18 19:46:54 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2020/05/18 19:46:54 DEBUG : mailru: Saved new token in config file
2020/05/18 19:46:55 INFO  : []: Handling item "Camera Uploads" of type "camera-upload" as a file
2020/05/18 19:46:55 DEBUG : []: Excluding path "/Camera Uploads" from list: invalid hash
Total objects: 45889
Total size: 215.021 GBytes (230876750310 Bytes)
2020/05/18 19:47:11 DEBUG : 22 go routines active </pre>

But, if i check "mailru:Camera uploads" instead, rclone "size" command works properly:
<pre>C:\Users\User\Downloads\rclone>rclone-windows-4.0-amd64.exe -vv --use-mmap size "mailru:/Camera uploads"

2020/05/18 19:47:55 DEBUG : rclone: Version "v1.51.0-DEV" starting with parameters ["rclone-windows-4.0-amd64.exe" "-vv" "--use-mmap" "size" "mailru:/Camera uploads"]
2020/05/18 19:47:55 DEBUG : Using config file from "C:\\Users\\User\\.config\\rclone\\rclone.conf"
2020/05/18 19:47:55 DEBUG : fs cache: renaming cache item "mailru:/Camera uploads" to be canonical "mailru:Camera uploads"
Total objects: 11148
Total size: 63.750 GBytes (68450664349 Bytes)
2020/05/18 19:48:00 DEBUG : 5 go routines active</pre>

**Comment by ivandeex** [comment] 2020-05-19 20:03
Thanks for the hint. I installed the android app and reproduced your issue. Investigating it now.

**Comment by PikaYellow35** [comment] 2020-06-04 08:56
Same problem on folders, that shared to you.
```
rclone lsd mail-drive: -vv
2020/06/04 11:41:12 DEBUG : rclone: Version "v1.52.0" starting with parameters ["rclone" "lsd" "mail-drive:" "-vv"]
2020/06/04 11:41:12 DEBUG : Using config file from "/home/yellow/.config/rclone/rclone.conf"
2020/06/04 11:41:12 DEBUG : []: Excluding path "/Aspia" from list: Unknown resource type "mounted"
2020/06/04 11:41:12 DEBUG : []: Excluding path "/KeeP" from list: Unknown resource type "mounted"
2020/06/04 11:41:12 DEBUG : 4 go routines active
```

**Comment by Cinerar** [comment] 2020-06-25 10:50
Same problem for shared folders via mailru backend.
If i use webdav backend to access mail.ru everything works ok.

**Comment by PikaYellow35** [comment] 2020-07-24 15:35
@Cinerar webdav access to mail.ru cloud enabled only for business account. I'm simple user and for me webdav return 403 code.

**Comment by ivandeex** [comment] 2020-10-15 01:14
I'm going to extend the list of special folders as follows:
```
"folder", "camera-upload", "mounted", "shared"
```
(taken from [WebDavMailRuCloud](https://github.com/yar229/WebDavMailRuCloud/blob/master/MailRuCloud/MailRuCloudApi/Base/Repos/MailRuCloud/DtoImport.cs#L188)).
Rclone will treat all of them as a directory.
Also rclone will print a debugging (`-vv`) message for non-"folder" kinds.
I think it's also ok to add a flag `--mailru-quirks=unknownfolders` to make rclone accept unknown/future kinds of folders but print a warning.
I'm going to cut a beta with the fix soon, sorry and thanks all for patience.

**Comment by ivandeex** [comment] 2020-10-16 22:28
@kuhytitusdlz @shvchk @Kabachek @PikaYellow35 

I released a beta that fixes this issue (linux/windows only atm). Please give it a try and report:
https://github.com/ivandeex/rclone/releases/tag/v1.53-mailru-camera-4

The test procedure is described in the pull request https://github.com/rclone/rclone/pull/4690#issuecomment-710676056

If the fix works for you, we will merge https://github.com/rclone/rclone/pull/4690 on master, publish a new beta with more architectures, and include it in the next rclone release.

Thanks.

**Comment by Kabachek** [comment] 2020-10-18 15:46
Seems no problems there
<pre>
2020/10/18 17:55:44 DEBUG : rclone: Version "v1.53-mailru-camera-4" starting with parameters ["rclone-windows-4.0-amd64.exe" "-vv" "--use-mmap" "sync" "mailru:"
"Z:\\" "--log-file" "mailru-camera-3.txt"]
2020/10/18 17:55:44 DEBUG : Using config file from "C:\\Users\\User\\.config\\rclone\\rclone.conf"
2020/10/18 17:55:44 DEBUG : Creating backend with remote "mailru:"
2020/10/18 17:55:45 DEBUG : Creating backend with remote "Z:\\"
2020/10/18 17:55:45 DEBUG : fs cache: renaming cache item "Z:\\" to be canonical "//?/Z:/"
2020/10/18 17:55:45 DEBUG : []: [Camera Uploads]: folder has type "camera-upload"
</pre>
<pre>
2020/10/18 18:09:03 DEBUG : Camera Uploads/2020-10-17 19.18.26.MOV: Starting multi-thread copy with 2 parts of size 127.312M
2020/10/18 18:09:03 DEBUG : Camera Uploads/2020-10-17 19.18.26.MOV: multi-thread copy: stream 2/2 (133496832-266974740) size 127.294M starting
2020/10/18 18:09:03 DEBUG : Camera Uploads/2020-10-17 19.18.26.MOV: multi-thread copy: stream 1/2 (0-133496832) size 127.312M starting
2020/10/18 18:09:04 DEBUG : []: Switch file server: locks 1, url https://cloclo22.datacloudmail.ru/oauth-get/, expiry "2020-10-18T18:12:03.5884129+03:00"
2020/10/18 18:09:04 DEBUG : []: Switch file server: locks 1, url https://cloclo4.datacloudmail.ru/oauth-get/, expiry "2020-10-18T18:12:03.5684118+03:00"
2020/10/18 18:09:31 DEBUG : Camera Uploads/2020-10-17 19.05.54.MOV: MailruHash = 64d431268db95bae63cb3c6229166ce1ce3a0a60 OK
2020/10/18 18:09:31 INFO  : Camera Uploads/2020-10-17 19.05.54.MOV: Copied (new)
2020/10/18 18:09:31 DEBUG : []: Lock file server:   locks 2, url https://cloclo4.datacloudmail.ru/oauth-get/
....

</pre>
<pre>
2020/10/18 18:33:27 INFO  :
Transferred:      914.676M / 914.676 MBytes, 100%, 420.983 kBytes/s, ETA 0s
Checks:             58086 / 58086, 100%
Transferred:           39 / 39, 100%
Elapsed time:     37m42.7s

2020/10/18 18:33:27 DEBUG : 3 go routines active
</pre>

**Closed** 2020-10-26 17:04 UTC
Labels: Remote: Mailru, bug
