### ISSUE TITLE
mount - total free space

### ISSUE THREAD

**Issue by thecoolreaver** [rclone/rclone#5276] opened 2021-04-25 19:32 UTC
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/mount-free-space/23742

#### What is your current rclone version (output from `rclone version`)?

```bash
bash# rclone version
rclone v1.55.0
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount
```

#### What problem are you are trying to solve?

If reference to this line via @ncw via the forum post, https://github.com/rclone/rclone/blob/89daa9efd1ce206931fa58b2a7374fc791ada67b/vfs/vfs.go#L546-L547
If the total size of a remote is unknown, it will default to 1PB in size or the total size reported from the remote the remote supports giving that info.
I would like to be able to have a parameter that if set, set the total size of the mount different from the actual remote total size, In case we want to use it like a quota of the space as another way of saying it.

#### How do you think rclone should be changed to solve that?

N/A
Do not know enough of the go language to help currently

**Comment by ivandeex** [comment] 2021-04-26 07:52
Duplicate of #3997

**Comment by ivandeex** [comment] 2021-09-21 05:01
Janitor duplicate requests

**Closed by ivandeex** 2021-09-21 05:01 UTC
Labels: duplicate, question
