### ISSUE TITLE
google drive - remote error: tls: bad record MAC

### ISSUE THREAD

**Issue by lodgnewt** [rclone/rclone#1893] opened 2017-12-08 02:15 UTC
I decided to use scaleway seedbox v1s to upload files to google drive and ran into a problem.
an error `remote error: tls: bad record MAC` with big files over 1gb

rclone v1.38
- os/arch: linux/amd64
- go version: go1.9

Ubuntu 16.04.3 LTS

Google Drive

https://pastebin.com/ib3kcT09

**Comment by ncw** [comment] 2017-12-08 09:24
This is either a go bug, or something weird about your setup.

Here are all the [go issues which mention that error](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+%22tls%3A+bad+record+MAC%22).  None of them look applicable since they are either very old, or apply to a plugin mode build (which rclone doesn't use).

The first thing to try would be to try some different versions of things...

Can you try...

1) [the latest beta](https://beta.rclone.org) please?  I expect this will still have the same issue, but it would be prudent to check.

2) rclone tip compiled with go tip (see below) - can you see if that fixes the problem please?  That is the same as the beta, just compiled with the very latest go compiler.

[rclone-v1.38-215-g5061aaaf-go-tip.zip](https://github.com/ncw/rclone/files/1542109/rclone-v1.38-215-g5061aaaf-go-tip.zip)

If 1) succeeds - problem solved! if 2) succeeds this will be in rclone 1.40 probably when go 1.10 is properly released (it is in beta now).  If 1) & 2) fail we need to dig deeper and possibly report a go bug.

**Comment by lodgnewt** [comment] 2017-12-08 10:43
1. https://pastebin.com/jnKiWZre
2. same trouble https://pastebin.com/5AMAEJDQ

**Comment by ncw** [comment] 2017-12-08 17:13
So both have the issue, but it is quite intermittent.

I read [here that turning the tcp checksum offload off](https://github.com/cockroachdb/cockroach/issues/9971) might help, something like

     sudo /sbin/ethtool -K ethX gso off tso off sg off gro off

Can you give that a go?  Subsitute ethX for the name of your interface card - use `ifconfig` to find it out.

We've seen this at $DAYJOB too so it is worth a try!

**Comment by lodgnewt** [comment] 2017-12-11 01:57
after turning off tcp checksum offload and reboot 
https://pastebin.com/5kyUL3dF

**Comment by ncw** [comment] 2017-12-12 09:43
What this error means is that a tls packet arrived with a bad checksum.  This could be a corrupted packet or a bug in go.

Can you try to reproduce it with this program?

[httpsget.zip](https://github.com/ncw/rclone/files/1551003/httpsget.zip)

It will download a 1 GB file from https://speed.hetzner.de/.  It should print something like this if it is successful. You may need to run it a few times to get it to blow up.

```
Status: 200: 200 OK
Downloading .......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................OK
MD5SUM c044d8d9ef314ecc00ab91104fad7438
Downloaded 1048575678 bytes in 10.684287333s @ 748.8 Mbit/s
```

**Comment by lodgnewt** [comment] 2017-12-26 09:37
I start periodically. it will not explode. strange))

**Comment by petercris** [comment] 2018-01-01 16:29
Hi!
Exactly same problem here, with scaleway seedbox vc1s on Amsterdam.
Any solution?
Thanks!!

**Comment by ncw** [comment] 2018-01-05 13:52
@petercris I'd like to get to the bottom of this, but as I said above it is either a go bug or something strange about the setup of the scaleway seedbox.

Perhaps the most likely possibility is that the packets are getting corrupted somehow (hence the suggestion to disable checksum offload).  Can you test out disabling all the offload things on the NIC?

If I can make a stand alone program to replicate the problem then I can report it to the go team but it looks like my httpsget program above didn't reproduce the problem.

PS what exactly is a `scaleway seedbox`?  Is it some sort of image I could download and run on scaleway? If you could give instructions that would be great!

**Comment by ncw** [comment] 2018-04-01 14:50
It might be worth trying rclone v1.40 which was compiled with go1.10 to see if that fixes it.

**Comment by ncw** [comment] 2019-02-12 10:26
Here is a version with go1.12rc2 to see if that helps

[rclone-v1.46.0-011-gc3eecbe9-beta-go1.12rc2.gz](https://github.com/ncw/rclone/files/2855287/rclone-v1.46.0-011-gc3eecbe9-beta-go1.12rc2.gz)

**Comment by ivandeex** [comment] 2021-01-23 00:01
Closing after 2 years of inactivity

**Closed by ivandeex** 2021-01-23 00:01 UTC
Labels: Remote: Drive, bug, needs retest, waiting for reply...
