### ISSUE TITLE
rclone config modifications overwrite symlink

### ISSUE THREAD

**Issue by Jwink3101** [rclone/rclone#4386] opened 2020-06-24 19:44 UTC
## What is the problem you are having with rclone?

If you use rclone to modify a symlinked config file, it will break the link and overwrite it 

For example:

```
$ ln -s /full/path/to/synced/config config.conf
$ rclone --config rclone.cfg config
$ .... rename a remote for example
```
Now the `rclone.cfg` is no longer a link. It is its own full file 

#### What is your rclone version (output from `rclone version`)

Originally with 1.52.1 but I saw the update so I tested with that too

```
rclone v1.52.2
- os/arch: darwin/amd64
- go version: go1.14.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS (64bit) and Debian Linux (64bit)

####  Which cloud storage system are you using? (eg Google Drive)

N/A

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Nominally, `rclone config` but I suspect this issue will happen for *any* update to the config file such as a new token from OneDrive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

These won't be that useful for this but just to match the spirit of the request:

```rclone
2020/06/24 13:42:00 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "-vv" "--config" "rclone.cfg" "config"]
2020/06/24 13:42:00 DEBUG : Using config file from "**REDACTED FULL/PATH**/rclone.cfg"
...
2020/06/24 13:42:14 DEBUG : rclone: Version "v1.52.2" finishing with parameters ["rclone" "-vv" "--config" "rclone.cfg" "config"]
```

**Comment by Dibbyo456** [comment] 2020-06-25 11:15
Knows issue. Duplicate of #3845

**Comment by ncw** [comment] 2020-06-25 11:37
If you want to use a symlink, then symlinking the `.config/rclone` directory will work better.

Or use `--config` or `RCLONE_CONFIG`.

**Closed** 2020-06-25 20:10 UTC
