### ISSUE TITLE
Bug - rclone copy - HTTP HEAD failure converts file GET to file/ GET (directory)

### ISSUE THREAD

**Issue by sagiegurari** [rclone/rclone#5929] opened 2022-01-19 09:52 UTC
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/trying-to-copy-single-file-via-http-and-url-changes-to-directory/28709

#### What is the problem you are having with rclone?

with http backend, in case the HEAD request fails (for example with 403), the GET that comes afterwards converts a file request to a dir request. meaning the request http://domain/file.txt changes to http://domain/file.txt/

#### What is your rclone version (output from `rclone version`)

rclone v1.57.0

os/version: debian 9.13
os/kernel: 4.19.75-v7l+ (armv7l)
os/type: linux
os/arch: arm
go/version: go1.17.2
go/linking: static
go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

not relevant

#### Which cloud storage system are you using? (e.g. Google Drive)

HTTP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone copy

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

see forum post. but... in general i found the actual problem in the server logs.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment] 2022-01-19 13:00
If the goal is to solve it, you need to provide a way to produce the issue with a debug log.

**Comment by sagiegurari** [comment] 2022-01-19 13:19
The issue was that my personal nginx had some access control and in addition only allowed for get/post and didn't allow head that caused the head to get rejected.
i fixed my nginx and now rclone works fine for me and i don't need a fix.

however, i decided to report the issue so you can find the bug in rclone to make rclone better.

basically you can try to put a simple php server and if head request return a 403 not allowed.
otherwise return the file.
than run rclone copy on that with request to copy a file (not dir) like /file.txt and you will see that if head fails, the get that comes afterwards gets messed up and becomes /file.txt/ (extra /).

if its not critical for you, you can close the issue.

**Comment by animosity22** [comment] 2022-01-19 13:24
Without steps to reproduce an issue, there's no way to fix it.

Hardly any issue ever reported it critical for me as that's not the point as it's important to you and if you want a fix, I'm trying to collect the information to make a fix possible.

There's already:

https://rclone.org/http/#http-no-slash

https://rclone.org/http/#http-no-head

If it's fixed for you, feel free to close the issue out.

If not, share the steps and commands on how to reproduce the problem with some logs.

**Comment by sagiegurari** [comment] 2022-01-19 13:26
tried both params actually. both didn't do anything to resolve this.
i think the no head is only for directly list command and is ignored by copy command (too bad).

i can try to setup some test case so you can run and repo

**Comment by animosity22** [comment] 2022-01-19 13:30
That would be perfect, basically my goal is to give a nice package to the folks that can actually fix it so they spend the time fixing the bug/defect/item and less time collecting. I just push papers and sadly don't program :)

**Comment by sagiegurari** [comment] 2022-01-19 16:15
ok so very simple test case

1. create simple txt file to serve, let's call it test.txt
2. create php file router.php
```
<?php
if ($_SERVER['REQUEST_METHOD'] === 'HEAD') {
    http_response_code(403);
} else {
    return false;
}
?>
```

3. start php server as follows:
```
php -S 0.0.0.0:5555 -t ./ ./router.php
```
This will start a php server that serves all local files.

4. create target dir and check php serves the test file correctly (using wget)
```
mkdir -p ./target/

cd ./target
wget http://localhost:5555/test.txt
cat ./test.txt
rm ./test.txt
cd -
```

5. run rclone
```
rclone copy --http-url=http://localhost:5555/ :http:test.txt ./target/
```

it fails.
if you remove the HEAD condition and basically it won't return 403 on HEAD, rclone works well.

```
022/01/19 16:14:30 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "copy" "--http-url=http://localhost:5555/" ":http:test.txt" "./target/" "-vv"]
2022/01/19 16:14:30 DEBUG : Creating backend with remote ":http:test.txt"
2022/01/19 16:14:30 DEBUG : :http: detected overridden config - adding "{Od1Cq}" suffix to name
2022/01/19 16:14:30 NOTICE: Config file "/home/gitpod/.config/rclone/rclone.conf" not found - using defaults
2022/01/19 16:14:30 DEBUG : fs cache: renaming cache item ":http:test.txt" to be canonical ":http{Od1Cq}:test.txt"
2022/01/19 16:14:30 DEBUG : Creating backend with remote "./target/"
2022/01/19 16:14:30 DEBUG : fs cache: renaming cache item "./target/" to be canonical "/workspace/misc-test/target"
2022/01/19 16:14:30 ERROR : http://localhost:5555/test.txt/: error reading source root directory: error listing "": Can't parse content type "text/plain"
2022/01/19 16:14:30 DEBUG : Local file system at /workspace/misc-test/target: Waiting for checks to finish
2022/01/19 16:14:30 DEBUG : Local file system at /workspace/misc-test/target: Waiting for transfers to finish
2022/01/19 16:14:30 ERROR : Attempt 1/3 failed with 1 errors and: error listing "": Can't parse content type "text/plain"
2022/01/19 16:14:30 ERROR : http://localhost:5555/test.txt/: error reading source root directory: error listing "": Can't parse content type "text/plain"
2022/01/19 16:14:30 DEBUG : Local file system at /workspace/misc-test/target: Waiting for checks to finish
2022/01/19 16:14:30 DEBUG : Local file system at /workspace/misc-test/target: Waiting for transfers to finish
2022/01/19 16:14:30 ERROR : Attempt 2/3 failed with 1 errors and: error listing "": Can't parse content type "text/plain"
2022/01/19 16:14:30 ERROR : http://localhost:5555/test.txt/: error reading source root directory: error listing "": Can't parse content type "text/plain"
2022/01/19 16:14:30 DEBUG : Local file system at /workspace/misc-test/target: Waiting for checks to finish
2022/01/19 16:14:30 DEBUG : Local file system at /workspace/misc-test/target: Waiting for transfers to finish
2022/01/19 16:14:30 ERROR : Attempt 3/3 failed with 1 errors and: error listing "": Can't parse content type "text/plain"
2022/01/19 16:14:30 INFO  : 
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s

2022/01/19 16:14:30 DEBUG : 3 go routines active
2022/01/19 16:14:30 Failed to copy: error listing "": Can't parse content type "text/plain"
```

**Comment by albertony** [comment] 2022-01-19 19:40
Great bug report! 👍 

The problem is in the backend initialization, where it is trying to classify the path given on command line. Without much experience in this part of the code, I think the case is that it cannot in general trust the user to always use suffix "/" when specifying directories, and therefore issues a HEAD request to find out. Don't know how to work around when the HEAD request fails.. Add option to let user specify? Issue a GET instead? Assume lack of suffix "/" indicates file? Don't know...

https://github.com/rclone/rclone/blob/c504d970174a604a39fdb2b2d1c51f2ca34ab31d/backend/http/http.go#L171-L199

**Comment by albertony** [comment] 2022-01-19 22:10
@sagiegurari I guess a workaround would be to specify a directory path (which matches the default assumption when head request fails), and then use filtering to pick the file instead.

E.g. instead of:
```
rclone copy --http-url=http://localhost:5555/ :http:test.txt ./target/
```
Then:
```
rclone copy --http-url=http://localhost:5555/ :http: ./target/ --include /test.txt
```

**Comment by sagiegurari** [comment] 2022-01-19 22:46
nice. wasn't aware of include param

**Comment by albertony** [comment] 2022-01-20 12:38
Just for the record, a second workaround mentioned in the forum: 

> You might be better off using
> 
> rclone copyurl https://somedomain.com//path/subpath/myfile.txt myfile.txt
> This just does a single GET request.

**Comment by ncw** [comment] 2022-01-20 16:29
> The problem is in the backend initialization, where it is trying to classify the path given on command line.  Without much experience in this part of the code, I think the case is that it cannot in general trust the user to always use suffix "/" when specifying directories, and therefore issues a HEAD request to find out. 

You are 100% correct :-)

> Don't know how to work around when the HEAD request fails.. Add option to let user specify? Issue a GET instead? Assume lack of suffix "/" indicates file? Don't know...
> 
> https://github.com/rclone/rclone/blob/c504d970174a604a39fdb2b2d1c51f2ca34ab31d/backend/http/http.go#L171-L199

Probably what we should do is look at the result of the HEAD request a bit more carefully.

How about this

Issue HEAD request
- if no error assume root is a file
- if 404 error assume root is a directory and add /
- if some sort of redirect 301,302,303,307,308 check the `Location:` header
    - if it ends with a / then assume root is a directory
    - otherwise assume root is a file
- if any other error then log something like this
    - "Assuming root is a file as server returned error (%v) on HEAD request. Add a trailing / if it is a directory."
    - Assume it is a file

That would potentially be a backwards incompatible change if a the HEAD request is returning something other than 404 or a redirect when the file isn't found. I think that is fairly unlikely though and the log message would point it out.

**Closed** 2022-01-26 10:41 UTC
Labels: bug, Remote: HTTP

**Comment by WizzardSK** [comment] 2024-06-21 05:44
Not sure if is it related, but I am having problem with --http-no-head when I use --vfs-cache-mode full.
Without using cache I may run "head" command on file to check the file size and then I can work with that like usual. 
With cache after running "head" on file it does not refresh the file size and even does not write anything. Like file was empty.
