### ISSUE TITLE
"Illegal instruction" when running on Raspberry Pi

### ISSUE THREAD

**Issue by marcone** [rclone/rclone#4582] opened 2020-09-10 16:02 UTC
It looks like the arm binary is no longer compatible with Raspberry Pi. The install script downloads rclone-current-linux-arm.zip, however the rclone binary contained within results in "Illegal instruction" when run.

rclone used to work fine on Raspberry Pi (I confirmed that https://downloads.rclone.org/v1.52.3/rclone-v1.52.3-linux-arm.zip still works).

**Comment by darthShadow** [comment] 2020-09-10 16:25
Duplicate of #4553. This is fixed in the latest beta builds and eventually will become available as 1.53.1. In the meanwhile, you can use this release candidate: https://beta.rclone.org/branch/v1.53-stable/v1.53.1-beta.4753.6a0398211.v1.53-stable

**Closed by darthShadow** 2020-09-10 16:25 UTC

**Comment by marcone** [comment] 2020-09-10 16:35
Any idea when "eventually" will be? As it stands, everyone trying to install rclone on Raspberry Pi using the normal `curl https://rclone.org/install.sh | sudo bash ` will get a non-working binary.

**Comment by darthShadow** [comment] 2020-09-10 17:04
@ncw ?

**Comment by ncw** [comment] 2020-09-12 11:53
I'm preparing the release now!

**Comment by ncw** [comment] 2020-09-13 09:32
It is out! https://forum.rclone.org/t/rclone-1-53-1-release/19083

Sorry for the delay.
