### ISSUE TITLE
Crash forces power-off reset/reboot

### ISSUE THREAD

**Issue by dr-mcgillicuddy** [rclone/rclone#4126] opened 2020-04-12 07:34 UTC
#### What is the problem you are having with rclone?

Total system lockup on macOS.

Not reproducible but, usually some combination of these things--sometimes it happens, but not always.
1. doing a server side move of a lot of files (in this case 86)
2. I start a second, simultaneous move of another 50 files
2. mount the drive on another device simultaneously to these actions
3. some of the files are duplicates, and I get a replace/skip/cancel dialogue--I choose skip
4. I start another move of a lot of files (about 45) while one of the server side moves is still in progress, and the move with duplicates shows cancelling, but not cleared.

trying to quit rclone with ctrl+c throws an error about the fuse volume being in use.  I could not copy the exact text because of the destructive nature of the crash.

Everything locks up.  EVERYTHING.  I can switch apps, but as soon as I interact with the app, it pinwheels.  I tried to take a spindump, and I can't even do that because when I try to save the output, activity monitor pinwheels.  Nothing is printing errors, to any logs.  Activity monitor shows Finder as "Not Responding" and that is the only process that shows not responding.  The only way to recover is a complete reboot--but not even soft reboot--a hard power off.  I've never seen anything crash in this destructive of a way on MacOS, ever.

This is hugely problematic because it is so destructive that the only safe way to use rclone mount is to close all other tasks on the system, because if it decides to crash destructively, everything is lost on the hard reboot, and no changes can be saved because any interaction with apps causes them to pinwheel as well.

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: darwin/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS 10.15.3

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount drive: ~/drive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

just a bunch of serverside move confirmations...

**Comment by dragetd** [comment] 2020-04-12 16:24
Userspace code should never be able to lock the kernel up in any way. If something like this happens, the problems must be outside of rclone.

Does the darwin kernel provide fuse natively? If not, and an extra fuse module is needed, then this could be a bug in the fuse module for Mac. It would run/trigger some kernel code that could cause a total system lockup.

The other alternative would be faulty hardware. Corrupted memory or a flaky IO-Controller would cause such things.

Things you can do: Try checking your RAM and stress your CPU. No idea about good tools for that on Mac. On x86 you would use memtest for example.
Check you disk and see if it has any errors.
Try other fuse-based filesystem like sshfs or whatnot and see if you can reproduce this in other ways.

Most likely there is sadly not much rclone can do for you at this point.

**Comment by dr-mcgillicuddy** [comment] 2020-04-12 16:37
>Does the darwin kernel provide fuse natively? 
No

> The other alternative would be faulty hardware. Corrupted memory or a flaky IO-Controller would cause such things.
There is a built in hardware test, I show no problems.

> Try other fuse-based filesystem like sshfs or whatnot and see if you can reproduce this in other ways.

I'm not sure how I'd do this, but I have used other FUSE filesystems before and have never seen them take down a system this way.


This isn't really a kernel lockup.  If it was, I would expect no response whatsoever.  In fact, applications that are already open still work.  I can switch between them.  Once I close them, though, they are gone forever.  That includes Finder.

I've never seen anything like this before and since I don't have access to any tools during this behavior, I have no idea how to give any more information.  But this has only ever happened to me with rclone.  It might be a Go issue.  Or related to the way rclone interacts with FUSE

But in 19 years of using Darwin-based systems I have never seen anything unrecoverable like this, and only when using rclone.

**Comment by dragetd** [comment] 2020-04-12 16:41
I am a complete darwin noob. But I assume it has some kernel logs, system logs and other things… maybe you are able to read them shortly before the lockup happens? I used to run a second machine, SSH into my system and follow the logs while working with the main machine.

**Comment by Zirro** [comment] 2020-04-12 21:12
I've had this type of lockup occur on several macOS versions before I started using rclone, so I doubt that it's the cause. It seemed to get more frequent with the release of Catalina though, which finally prompted me to go through remove all kernel extensions I no longer need. Since doing so I've not experienced this type of lockup again.

Given the reported circumstances - and with the lockups I saw usually occuring under heavy IO activity - my first guess at the culprit would be https://osxfuse.github.io/, as macOS does indeed not include FUSE by default.

**Comment by dr-mcgillicuddy** [comment] 2020-04-13 09:27
> I've had this type of lockup occur on several macOS versions before I started using rclone, so I doubt that it's the cause. It seemed to get more frequent with the release of Catalina though, which finally prompted me to go through remove all kernel extensions I no longer need. Since doing so I've not experienced this type of lockup again.
> 
> Given the reported circumstances - and with the lockups I saw usually occuring under heavy IO activity - my first guess at the culprit would be https://osxfuse.github.io/, as macOS does indeed not include FUSE by default.

Well, this isn't heavy I/O because it's all server-side.  And again, only with rclone, so maybe something to do with a specific interaction of rclone and FUSE

Any of you OSX-ers have tips on getting any debug info?  System logs are unremarkable, so I need something else to go on.  My only kexts btw are the standard VirtualBox ones.

**Comment by animosity22** [comment] 2020-04-19 17:41
If it's locking up, I agree with @Zirro and post/try to get some help from the fuse side as a start. I rarely run mounts on my Mac as I just move a file here/there as I use Linux for majority of my mount work.

**Comment by animosity22** [comment] 2020-05-18 12:35
Is there anything to do here from the rclone standpoint ?

**Comment by ncw** [comment] 2020-05-19 11:08
I would guess that this is something to do with rclone blocking on requests from the macOS kernel (via OSXFUSE) and this in turn blocking macOS.

Server side moves should be quite quick so if this is the case I'd expect the moves to complete then the system return back to normal...

The fact it didn't is probably a bug, but where????

Can you still reproduce this with [the latest beta](https://beta.rclone.org) @dr-mcgillicuddy ?

**Comment by RickyBubbles** [comment] 2020-05-19 11:16
I'll try.

I'm not currently running any betas so I'll upgrade my various installs and see if it crops up again.

But it existed in 1.50.x as well as 1.51 for whatever that's worth.

**Comment by dr-mcgillicuddy** [comment] 2020-07-28 06:12
I guess I'm the only one experiencing this, so maybe go ahead and close it?

The lockup/beachball hasn't happened to me in the last several months, so unfortunately I can't provide logs or anything else to help with troubleshooting.

**Comment by ncw** [comment] 2020-07-28 09:28
I'll just note that we are changing the fuse interface within rclone on macOS for 1.54. You can try the new interface in the beta using `rclone cmount` and this will be in 1.53 when it is released. `rclone cmount` will become `rclone mount` for 1.54.

We are doing this because the fuse interface we are using (bazil/fuse) is stopping support for macOS due to OSXFUSE licence changes.

The new interface (billziss/cgofuse) is based on calling into the C fuse library directory rather than talking straight to the kernel interface and I'm hopeful that it will reduce the number of oddities on macOS mounts.

Anyway, I'll close this now and I'd appreciate testing with `rclone cmount` - please make a new issue if you see crashes there :-)

**Closed by ncw** 2020-07-28 09:28 UTC
Labels: question
