### ISSUE TITLE
sync: add option to always skip hashsum check

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4793] opened 2020-11-23 07:17 UTC
https://github.com/rclone/rclone/blob/211b08f771472cbe6f0a60824010b84303d9b12e/fs/operations/operations.go#L216

**Comment by zhucan** [comment] 2020-11-23 07:20
@ncw  I have other question, why not check 'mtime' first, check 'size' second  and check 'hash' third?

**Comment by ncw** [comment] 2020-11-23 15:48
Rclone will only get to that point if the sizes are the same but the modtimes are different which usually means a file needs transferring. However rclone does a check with checksum just to make sure and if it is really the same it just updates the modtime.



> I have other question, why not check 'mtime' first, check 'size' second and check 'hash' third?

Size is the quickest thing to check so we check that first.

We only check the checksum if the modtime if different, but the size is the same (without `--checksum`)

**Comment by zhucan** [comment] 2020-11-24 02:58
> Rclone will only get to that point if the sizes are the same but the modtimes are different which usually means a file needs transferring. However rclone does a check with checksum just to make sure and if it is really the same it just updates the modtime.
> 
> > I have other question, why not check 'mtime' first, check 'size' second and check 'hash' third?
> 
> Size is the quickest thing to check so we check that first.
> 
> We only check the checksum if the modtime if different, but the size is the same (without `--checksum`)

If sizes are the same but the modtimes are different which usually means files needs transferring,  it's needed to check the checksum? Because of check the checksum that there is a lot of pressure on storage.

**Comment by zhucan** [comment] 2020-11-24 07:42
@ncw I have other question, Can not copy acl for object from a bucket to other bucket with rclone？

**Comment by ncw** [comment] 2020-11-24 18:10
> If sizes are the same but the modtimes are different which usually means files needs transferring, it's needed to check the checksum? Because of check the checksum that there is a lot of pressure on storage.

What would you like rclone to do here? Just upload the file?

If so then you need the flag

      --no-update-modtime    Don't update destination mod-time if files identical.

> I have other question, Can not copy acl for object from a bucket to other bucket with rclone？

Which backend is this?

And are you doing a server side copy or not?

I think for a server side copy rclone will copy the ACL for S3.

**Comment by zhucan** [comment] 2020-11-25 03:09
> I think for a server side copy rclone will copy the ACL for S3.

Backend is ceph rgw, maybe not support server side copy.

**Comment by zhucan** [comment] 2020-11-25 03:11
> What would you like rclone to do here? Just upload the file?

Yes, Just upload, But we want to check hash, only want to check  modtime & size.

**Comment by ncw** [comment] 2020-11-25 09:56
> Yes, Just upload, But we want to check hash, only want to check modtime & size.

Then --no-update-modtime is just what you want.

**Comment by zhucan** [comment] 2020-11-25 10:30
@ncw https://github.com/rclone/rclone/blob/7078311a844fe7a12b66ff6e632065d20b48b7d2/fs/operations/operations.go#L216
--no-update-modtime will check the hash.

**Comment by ncw** [comment] 2020-11-25 10:35
Hmm, you are right.

If you use this flag then I think it will work for you provided that the modification times only ever increase on the source files.

  -u, --update                    Skip files that are newer on the destination.

Give it a go!

**Comment by ivandeex** [comment] 2020-11-25 10:47
@ncw
I spent some time marking (most?) **some** open issues/PRs requesting various variations of `change detection` flags. I dare summarize, to me it's a deep self-contradictory mess.
https://github.com/rclone/rclone/issues?q=label%3A%22change+detection%22

**Comment by zhucan** [comment] 2020-11-25 11:06
> Hmm, you are right.
> 
> If you use this flag then I think it will work for you provided that the modification times only ever increase on the source files.
> 
> -u, --update Skip files that are newer on the destination.
> 
> Give it a go!

The same to --update.

**Comment by ncw** [comment] 2020-11-25 11:22
@ivandeex wrote:
> I spent some time marking (most?) **some** open issues/PRs requesting various variations of `change detection` flags. I dare summarize, to me it's a deep self-contradictory mess.

The basic sync design and user interface is based on rsync so I'm going to blame that ;-)

> Add `filtering` flags on top https://github.com/rclone/rclone/issues?q=label%3A%22filtering%22
> No wonder the flag page in docs is one of the longest.

Indeed!
 
> Basically, we have three basic traits: hash,size,mtime. Sooner or later rclone will support all ordered permutations thereof.

There are a lot of tradeoff, alas.

The comparison code `equal` has cyclomatic complexity larger than my brain can hold.

@zhucan wrote
> The same to --update.

What you are looking for here is an optimization - you'd rather transfer a file than check its checksum. For most users, checking a checksum is much much quicker than transferring a file.

Why is that different for you?

Which backend are you using?

What is the rclone command you are using for the transfer?

**Comment by ivandeex** [comment] 2020-11-25 11:46
@zhucan Please provide info from the rclone feature template (or bug. is this issue a bug?)

**Comment by ivandeex** [comment] 2020-11-25 20:49
Looks like there isn't use case and this issue is a group of assorted code-related questions (answered above). `git blame` is the tool of choice here.

**Comment by zhucan** [comment] 2020-11-26 03:17
> Why is that different for you?
Because of there is hundreds of millions of small files will cause great read pressure on storage, if we check hash. so we want to only check modtime and size under the condition that the customer can guarantee the consistency of md5.

**Comment by zhucan** [comment] 2020-11-26 03:17
> Why is that different for you

Because of there is hundreds of millions of small files will cause great read pressure on storage, if we check hash. so we want to only check modtime and size under the condition that the customer can guarantee the consistency of md5.

**Comment by zhucan** [comment] 2020-11-26 03:18
> Which backend are you using

ceph rgw

**Comment by zhucan** [comment] 2020-11-26 03:19
> What is the rclone command you are using for the transfer

We have changed this part of the file in rclone（func equal）, only add some flags.

**Comment by ncw** [comment] 2020-11-26 11:45
> Because of there is hundreds of millions of small files will cause great read pressure on storage, if we check hash. so we want to only check modtime and size under the condition that the customer can guarantee the consistency of md5.

Why do you have 100s of millions of files which has
- size the same
- modtime different

That isn't a usual situation. Are you trying to get the modtimes set on all the files that didn't have them set before?

----

> We have changed this part of the file in rclone（func equal）, only add some flags.

I think adding another flag is the only possibility.

What you want is a flag which says "if mod times are the same then don't check the checksum, transfer anyway".

I looked to see if `rsync` has a flag which does this - it doesn't!

So we could make a flag called `--no-checksum-if-same-age` (or something).

Another idea would be to only do the checksum calculation if we are not using `--no-update-modtime` but that would mean that if you had `--no-update-modtime=true` then rclone would transfer identical files which is undesirable.

----

Do we need to add a new flag or are you happy with a source code patch @zhucan ?

**Comment by ivandeex** [comment] 2020-11-26 11:48
Related to https://github.com/rclone/rclone/pull/4011#issuecomment-734246794

**Comment by ivandeex** [comment] 2020-11-26 19:37
> > Because of there is hundreds of millions of small files will cause great read pressure
> Why do you have 100s of millions of files which have size the same

Probably the problem is that https://github.com/kubernetes/system-validators/issues/17 is closed and https://github.com/kubernetes/kubernetes/issues/93504 is rotten

**Comment by ivandeex** [comment] 2020-11-26 22:35
I wonder if they developed a deep neural net for submitting bug reports, would it start from improving own dependencies?

**Comment by ivandeex** [comment] 2020-11-27 16:44
> copy acl for object from a bucket to other bucket with rclone？

- Mentioned in https://forum.rclone.org/t/s3-bucket-migration-with-metadata-issues/10262
- Blocks on https://github.com/rclone/rclone/issues/111
- Beta available https://github.com/rclone/rclone/tree/fix-111-metadata

**Comment by zhucan** [comment] 2020-12-02 08:35
> > copy acl for object from a bucket to other bucket with rclone？
> 
> * Requested by https://forum.rclone.org/t/s3-bucket-migration-with-metadata-issues/10262
> * Blocks on #111
> * Beta available https://github.com/rclone/rclone/tree/fix-111-metadata

This pr only can copy metadata, not acl.

**Comment by ivandeex** [comment] 2020-12-02 10:47
> This pr only can copy metadata, not acl.

then it's not implemented.
you can try s3cmd or s3 api to copy acl.

**Comment by zhucan** [comment] 2020-12-02 10:51
> > This pr only can copy metadata, not acl.
> 
> then it's not implemented.
> you can try s3cmd or s3 api to copy acl.

copy that, we had added the operation.

**Comment by ivandeex** [comment] 2020-12-02 20:55
"ACL copy" status: WontfFix

**Comment by ivandeex** [comment] 2020-12-02 21:06
Change detection logic proposed here is an advanced case that will be implemented by more general issue #4810 (advanced change detection)

@ncw 
Do we want to keep this open for collecting use cases?
Blocks on #4810 ?
or Duplicates #4810 ?

**Comment by zhucan** [comment] 2020-12-03 03:38
> "S3 ACL copy support" - status `WontfFix`

Is there plan?

**Comment by ivandeex** [comment] 2020-12-03 08:00
probably no
i can't find a ticket.

**Comment by ivandeex** [comment] 2020-12-03 08:03
@zhucan 
since this ticket is dedicated to change detection
please submit new ticket
"s3: copy ACL for an object from bucket to bucket"

**Comment by zhucan** [comment] 2020-12-03 08:30
@ivandeex copy that

**Comment by zhucan** [comment] 2020-12-03 08:40
> So we could make a flag called `--no-checksum-if-same-age` (or something).

only '--no-checksum' can do this, if modtime and size are same.  if we use 'rclone copy' without other flags,  it will check size and modtime and when the size and modtime are same that will checksum, so  we can add the flags '--no--checksum' skip the to checksum when the size and modtime are same.
Is it ok? @ncw

**Comment by ivandeex** [comment] 2021-11-19 15:42
Request captured in https://github.com/rclone/rclone/issues/4810#issuecomment-974180662
Superseded by more general
- #4810

**Closed by ivandeex** 2021-11-19 15:42 UTC
Labels: Remote: S3, change detection
