### ISSUE TITLE
What does this mean? Cannot unmarshal object into Go struct field UploadAPIError.error of type string

### ISSUE THREAD

**Issue by Toontje** [rclone/rclone#2106] opened 2018-02-28 10:07 UTC
Failed to copy: upload failed: json: cannot unmarshal object into Go struct field UploadAPIError.error of type string

during copying from local to Dropbox.

**Comment by ncw** [comment] 2018-03-06 09:11
If you can get this error consistently it is a bug (either in rclone or dropbox).

If you just got it once then it might be caused by a networking glitch.

Can you reproduce the problem?

**Comment by Toontje** [comment] 2018-03-06 09:47
Yes, this happens when i upload certain JSON documents. When i have more time i will troubleshoot further.

**Comment by ncw** [comment] 2018-03-06 11:36
Great.  If you can get me a reproducer, or a log with `-vv --dump-bodies` that would be perfect.

**Comment by ncw** [comment] 2018-05-22 21:03
Can you email the unedited log to nick@craig-wood.com please? Can you put a link to this issue in so I've got some context?

Thanks

**Comment by ikarus23** [comment] 2018-05-22 21:14
Done. Let me know when I can help you with anything.

**Comment by ncw** [comment] 2018-05-23 14:15
@ikarus23 thanks for the log.  I can see what is going on now!

Firstly the dropbox sdk is masking the real error.  I've reported this as a bug: https://github.com/dropbox/dropbox-sdk-go-unofficial/issues/44

What it should have reported is "path/malformed_path/...".  Looking at the crypted filename you were trying to upload, it has a path segment (a directory) which is longer than 255 characters.  I can see in the log you sent me that it is 151 characters. Unfortunately crypt bulks up the filenames (by a factor of 8/5 roughly).

So you can either rename the directory to something a bit shorter, or turn off file name encryption or use file name obfuscation instead.

There isn't a really good solution to this at the moment - sorry!

**Comment by ikarus23** [comment] 2018-05-23 18:51
Oh, that makes sense! Thank you for your feedback. I guess I have to shorten the names then.
(Or can the file name encryption be changed to obfuscation without re-uploading everything?)

**Comment by ncw** [comment] 2018-06-07 15:29
> Or can the file name encryption be changed to obfuscation without re-uploading everything?

In theory, but rclone can't do it directly...

What you'd have to do is work out what the new crypted names were then rename them (which you could use an rclone mount on the underlying remote for).

**Comment by coreycauble** [comment] 2019-09-29 19:58
So I had this also happen because the space at the end of the folder name, just FYI.
Strode_Drone_/XXXXXXX.XXX 
the _ being spaces

**Comment by ncw** [comment] 2019-10-25 13:38
This is now fixed in the upstream library so when they make an official release I'll pull it into rclone.

Will likely be for rclone v1.51

**Closed** 2020-08-25 20:50 UTC
Labels: Remote: Dropbox, bug

**Comment by MartinRamm** [comment] 2020-10-23 09:03
I just ran into this problem again with v1.54 when using the `mount` command.
I was able to use `cd`, but could not open files (I received a `I/O error.` when using `cat`).
Turns out I had a double `/` in the path.
e.g.: `rclone mount "dropbox://fake//path/to/a/folder" "/mount/dropbox"` instead of `rclone mount "dropbox://fake/path/to/a/folder" "/mount/dropbox"` (error being the double `/` between `fake` and `path`)
