### ISSUE TITLE
build: Stop the stable release making a beta

### ISSUE THREAD

**Issue by robertbaker** [rclone/rclone#4586] opened 2020-09-13 20:23 UTC
## What is the problem you are having with rclone?

https://beta.rclone.org/rclone-beta-latest-windows-amd64.zip is not being built at the same time as the other "latest" betas. If you look at the timestamps, the "latest" beta files are updated around 3AM, except for `rclone-beta-latest-windows-amd64.zip`. Downloading and extracting the file and running rclone --version has verified that the rclone build is 1 commit behind the version.txt

If you go into the version folder for the latest version, (right now) https://beta.rclone.org/v1.54.0-beta.4770.a73c78545/rclone-beta-latest-windows-amd64.zip does not exist either.

There is a related issue here that happens upon release. So for today a new stable version was released, but the beta.rclone.org version shows a beta tag still (even though no beta). Since there isn't a beta (commit after rls tag), at this point in time, the version.txt should match the rls tag.

This is an issue when using version.txt to compare to `rclone --version` to see there is an updated version (in this case beta). In this case, version.txt will show a beta version but will download (right now) `rclone v1.53.1` and thus if (for example) a script is ran that checks the versions and determines if it needs to update rclone, it will basically check,`'rclone v1.54.0-beta.4770.a73c78545' != 'rclone v1.53.1'` and think there's an update available when there isn't.

**Comment by ncw** [comment] 2020-09-15 10:46
The windows beta being a version behind is because in this build: https://github.com/rclone/rclone/actions/runs/252250750 the Windows build failed. The tests hit one of those failures which happen every now and again.

This is unfortunate but it will get corrected the next time master is build. I gave the actions a rebuild which should fix it.

It is particularly unfortunate that this happened for the first commit after the stable release was released. The stable release process makes a beta (which it shouldn't) and the first commit after the stable release on master fixes it.

So fixing the stable release making a beta would be the best thing to do. Which alas involves more fighting with Make files...

**Comment by ivandeex** [comment] 2020-12-06 00:21
Duplicate of #4789

**Comment by ivandeex** [comment] 2020-12-06 00:23
Related to #4809

**Comment by ncw** [comment] 2021-01-28 14:22
This was fixed with 1ce0b4596588d4cef42d264b0f35ba66f7a1dff4 as part of #4789

**Closed by ncw** 2021-01-28 14:22 UTC
Labels: bug, build, duplicate
