### ISSUE TITLE
--no-check-certificate: slow startup, uses lots of CPU

### ISSUE THREAD

**Issue by hashbackup** [rclone/rclone#1016] opened 2017-01-10 22:15 UTC
rclone v1.35 seems to have a pretty long startup time, usually 7 seconds.  HashBackup can use rclone to transfer backup files to and from some destinations that aren't natively supported.  To preserve backup integrity, HB sends or receives 1 file per rclone invocation and does it's own multithreading and synchronization.

With both Amazon Cloud Drive and Dropbox, the first http request takes a long time, usually 7-8 seconds.  Here is a log for dropbox copying 1 file local to remote (... is an abbreviated pathname for posting):
```
$ time rclone --dump-auth --dump-bodies --dump-headers -c -v copyto /Users/.../hbrclone/dest.db drop:test/dest.db
2017/01/10 16:51:08 rclone: Version "v1.35" starting with parameters ["rclone" "--dump-auth" "--dump-bodies" "--dump-headers" "-c" "-v" "copyto" "/Users/.../hbrclone/dest.db" "drop:test/dest.db"]
2017/01/10 16:51:08 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/01/10 16:51:08 HTTP REQUEST (req 0xc4200eaa50)
2017/01/10 16:51:08 GET /1/metadata%2Fauto%2Ftest?file_limit=10000&include_deleted=false&list=false&locale=en HTTP/1.1
Host: api.dropbox.com
User-Agent: rclone/v1.35
Authorization: Bearer (hex)
Accept-Encoding: gzip

2017/01/10 16:51:08 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*******  here is an 8 second delay, with high CPU usage  ********
2017/01/10 16:51:16 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/01/10 16:51:16 HTTP RESPONSE (req 0xc4200eaa50)
2017/01/10 16:51:16 HTTP/1.1 200 OK
Content-Length: 244
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/javascript
Date: Tue, 10 Jan 2017 21:51:16 GMT
Pragma: no-cache
Server: nginx
Set-Cookie: gvc=(blah); expires=Sun, 09 Jan 2022 21:51:16 GMT; httponly; Path=/; secure
User-Agent: 
X-Content-Type-Options: nosniff
X-Dropbox-Http-Protocol: None
X-Dropbox-Request-Id: (hex)
X-Frame-Options: SAMEORIGIN
X-Server-Response-Time: 800

{"read_only": false, "revision": 2, "bytes": 0, "thumb_exists": false, "rev": "252d50fc1", "modified": "Tue, 10 Jan 2017 20:02:37 +0000", "size": "0 bytes", "path": "/test", "is_dir": true, "modifier": null, "root": "dropbox", "icon": "folder"}
2017/01/10 16:51:16 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```
This request is just verifying that the directory "test" exists on the remote.  The next request actually copies the file and is instantaneous.

During this 8 second delay, CPU usage is very high, as shown here using the time command:
```
2017/01/10 16:51:17 Go routines at exit 5

real	0m8.207s
user	0m5.516s
sys	0m5.946s
```
The rclone command ran for 8 real-time seconds and used 11.4 CPU seconds (142% CPU usage; it's a dual CPU system).  I only had this 1 remote configured. 

I tried using --checkers=1, -I to ignore times, removing -c, adding -n, and finally discovered the cause: SSL cert checking.  If I add --no-check-certificate, the same command runs almost instantaneously. 

Is there any way to improve this?  I make secure connections all the time from the test system and it doesn't take anywhere near 8 seconds.

Thanks!

**Comment by hashbackup** [comment] 2017-01-10 22:45
Forgot to mention, this is on an OSX 10.6.8 system if it matters.

Here are some more timing details.  It was doing this (time output from rclone and time command):
```
Elapsed time:          7s
2017/01/10 17:10:05 Go routines at exit 5

real	0m7.135s
user	0m5.512s
sys	0m5.924s
```
and with --no-check-certificate, it is:
```
Elapsed time:       700ms
2017/01/10 17:11:27 Go routines at exit 5

real	0m0.779s
user	0m0.064s
sys	0m0.047s
```

**Comment by ncw** [comment] 2017-01-11 09:23
I don't see this on linux, so I think it is probably an OS X specific problem.

Here is a version of rclone build with go tip - does that help?

[rclone-v1.35-23-ga7d8ccd-osx-go-tip.zip](https://github.com/ncw/rclone/files/698394/rclone-v1.35-23-ga7d8ccd-osx-go-tip.zip)

Another thing you could try is build rclone on your OS X machine locally.  That will be able to use the native SSL libraries which may make a difference.

**Comment by hashbackup** [comment] 2017-01-11 17:03
Yes, that fixes it - thanks!  Out of curiosity, what was the problem?

**Comment by garyo** [comment] 2017-02-17 15:02
rclone 1.35 on Windows also has this problem; it's very slow to start up (even just `rclone --help` takes ~10 sec) unless I use `--no-check-certificate`

**Comment by ncw** [comment] 2017-02-17 16:53
@garyo that seems strange - `--no-check-certficate` shouldn't do anything for just rclone help.  Did you have any other parameters?

**Comment by ivandeex** [comment] 2020-11-16 18:25
@garyo 
Does the problem reproduce for you with latest rclone 1.53.2 ?
If not, let's close this issue as the original problem was fixed.

**Comment by garyo** [comment] 2020-11-16 18:43
I haven't seen it in a while. It might have been due to Windows trying to use ipv6 which my ISP doesn't support. I turned that off and many things got faster. I'm also pretty much only using it from WSL at this point. So feel free to close.

**Closed** 2020-11-16 18:46 UTC
Labels: OS: Windows, Remote: Amazon Cloud Drive, Waiting for user reply :hourglass_flowing_sand:, bug, needs retest
