### ISSUE TITLE
rclone mount - Multipart download implemented?

### ISSUE THREAD

**Issue by venomone** [rclone/rclone#6042] opened 2022-03-18 17:01 UTC
#### Output of `rclone version`

rclone v1.57.0
- os/version: debian bullseye/sid (64 bit)
- os/kernel: 5.13.0-35-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none

#### Describe the issue

I'm using rclone to mount a nginx webroot. If I download something using nginx tough the rclone mount, I have a download speed of exactly 7,2 MB/s, but not more per connection. I know that my S3 storage can handle 10 Gbit/s+ at least, and other tools like s3browser under windows are working also fine. So my question is does rclone mount support multipart download, as to me, it really seems like it's not, not at all ;).
The funny fact is that, as already explained, this runs per connection. So I can open 30 connection each 7.2 MB/s but how to get higher throughput on a single download if --transfers flag is not supported by mount?

Thanks in advance

**Comment by animosity22** [comment] 2022-03-18 17:20
duplicate of:

https://github.com/rclone/rclone/issues/4760

**Closed by animosity22** 2022-03-18 17:20 UTC
Labels: duplicate
