### ISSUE TITLE
Unable to download Google Docs 

### ISSUE THREAD

**Issue by Nikratio** [rclone/rclone#5461] opened 2021-07-15 10:26 UTC
About 1 week ago, rclone stopped being able to sync Google Docs files for me. In the past, the same command worked. Now, it fails every time:

```
nikratio@vostro ~/l/gdrive-backup [SIGINT]> rclone --version
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.15.9
```

```
 rclone sync --retries 10 \
                                              --drive-export-formats ods,odt,odp \
                                              gdrive:/ ~/lib/gdrive-backup/ -vv
2021/07/15 11:25:02 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "sync" "--retries" "10" "--drive-export-formats" "ods,odt,odp" "gdrive:/" "/home/nikratio/lib/gdrive-backup/" "-vv"]
2021/07/15 11:25:02 DEBUG : Using config file from "/home/nikratio/.rclone.conf"
2021/07/15 11:25:02 DEBUG : Creating backend with remote "gdrive:/"
2021/07/15 11:25:03 DEBUG : Google drive root '': root_folder_id = "0ANpFR3fFtVwqUk9PVA" - save this in the config to speed up startup
2021/07/15 11:25:03 DEBUG : fs cache: renaming cache item "gdrive:/" to be canonical "gdrive:"
2021/07/15 11:25:03 DEBUG : Creating backend with remote "/home/nikratio/lib/gdrive-backup/"
[...]
2021/07/15 11:25:08 ERROR : Quotation for electrical work at 5 Acacia Walk AL51SH: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: Only files with binary content can be downloaded. Use Export with Docs Editors files., fileNotDownloadable
[...]
```

**Comment by itaj-sherman** [comment] 2021-07-15 22:05
Duplicate of #5455

**Closed** 2021-07-16 16:05 UTC
