### ISSUE TITLE
[Feature Request] rclone mount - allow files to be opened in read/write mode 

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#998] opened 2017-01-07 13:27 UTC
eg. enable buffer files locally 

If you edit file directly on mount it will be destroyed: https://forum.rclone.org/t/rclone-mount-crypt-amazon-drive-filed-destroyed-on-edit-save/645

**Comment by ncw** [comment] 2017-01-09 16:35
I think this is probably a duplicate of #711 - what do you think?

**Comment by flixajki** [comment] 2017-01-10 08:35
Hmm yes regarding cache, but not regarding bug where file gets destroyed ( probably would be best to stick with one issue )

**Comment by ncw** [comment] 2020-01-23 16:13
I think this is fixed by --vfs-cache-mode writes

**Closed by ncw** 2020-01-23 16:13 UTC
