### ISSUE TITLE
UID/GID not preserved when mounting remote SSH/SFTP folder

### ISSUE THREAD

**Issue by Markus74a** [rclone/rclone#6494] opened 2022-10-14 11:29 UTC
#### What is the problem you are having with rclone?

Since *SSHFS* is not longer actively developed, I'm trying to replace it by *rclone*. However, *rclone* does not preserve UID/GID in the mounted directories:

* When I mount a remote directory with *SSHFS* to a local directory, the UID and GID are preserved and shown correctly
* When I mount a remote directory with *rclone* to a local directory, the UID and GID of all files and directories are always shown as the ones of the mounting user: If I mount as root all files get UID=0 and if I mount as normal user all files show up with my normal UID.

According to the help `clone mount --help`:
```
--uid uint32         Override the uid field set by the filesystem (not supported on Windows)
--gid uint32         Override the gid field set by the filesystem (not supported on Windows)
```
So if the filesystem supports UID/GID (for example, *ext4* accessed over *SFTP*)  and I do *not* use these options, I would expect all files and directories to show their correct UID/GID.

The bug happens with at least two remote system: One is a normal *Ubuntu* server, one is a *Synology* NAS with SSH/SFTP enabled.

#### What is your rclone version (output from `rclone version`)
rclone v1.59.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/version: arch 22.0.0 (64 bit)
- os/kernel: 5.15.72-1-MANJARO (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.1
- go/linking: dynamic
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)
SSH/SFTP accessing a remote *ext4* file system

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone mount XXX:/home/XXX/test /test -vv` (executed as root)

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2022/10/14 12:58:10 DEBUG : rclone: Version "v1.59.2" starting with parameters ["rclone" "mount" "XXX:/home/XXX/test" "/test" "-vv"]
2022/10/14 12:58:10 DEBUG : Creating backend with remote "XXX:/home/XXX/test"
2022/10/14 12:58:10 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2022/10/14 12:58:10 DEBUG : sftp://XXX@XXX:22//home/XXX/test: New connection 192.168.0.XXX:42212->XXX.XXX.XXX.XXX:22 to "SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.7"
2022/10/14 12:58:10 DEBUG : sftp://XXX@XXX:22//home/XXX/test: Shell type "unix" from config
2022/10/14 12:58:11 DEBUG : sftp://XXX@XXX:22//home/XXX/test: Using root directory "/home/XXX/test"
2022/10/14 12:58:11 INFO  : sftp://XXX@XXX:22//home/XXX/test: poll-interval is not supported by this remote
2022/10/14 12:58:11 DEBUG : sftp://XXX@XXX:22//home/XXX/test: Mounting on "/test"
2022/10/14 12:58:11 DEBUG : : Root: 
2022/10/14 12:58:11 DEBUG : : >Root: node=/, err=<nil>
2022/10/14 12:58:20 DEBUG : /: Attr: 
2022/10/14 12:58:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2022/10/14 12:58:21 DEBUG : /: ReadDirAll: 
2022/10/14 12:58:21 DEBUG : /: >ReadDirAll: item=4, err=<nil>
2022/10/14 12:58:21 DEBUG : /: Lookup: name="abc"
2022/10/14 12:58:21 DEBUG : /: >Lookup: node=abc, err=<nil>
2022/10/14 12:58:21 DEBUG : abc: Attr: 
2022/10/14 12:58:21 DEBUG : abc: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2022/10/14 12:58:21 DEBUG : /: Lookup: name="xyz"
2022/10/14 12:58:21 DEBUG : /: >Lookup: node=xyz, err=<nil>
2022/10/14 12:58:21 DEBUG : xyz: Attr: 
2022/10/14 12:58:21 DEBUG : xyz: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
```
After `rclone`is running, a `ls -al /test` is executed on the directory. The files `abc` and `xyz` have different UIDs and GIDs, but both show up with UID=0 and GID=0 in the local directory.

**Comment by animosity22** [comment] 2022-10-14 11:55
Fuse mounts are only available to the user running them.

You'd have to add --allow-other and add the uid/gid commands 

```
rclone mount remote: /home/felix/test --allow-other --uid 1000 --gid 1000
```

as root works fine for me.

**Comment by Markus74a** [comment] 2022-10-14 13:13
I do not want to see UID=1000 / GID=1000 on every file or directory.
I want to see the **correct** UID / GID on every file or directory.

The problem is not the access itself (which works as expected), but that all UID/GID are shown the wrong way.

For example, if you mount `/bin` as user `felix`, then *rclone* would show you that every single file in the directory is owned by `felix:felix`, even though obviously every file in `/bin` in owned by `root:root`.

**Comment by animosity22** [comment] 2022-10-14 13:14
That's not how fuse mount works unfortunately. It's a user space mount so it works as such.

**Comment by Markus74a** [comment] 2022-10-14 13:19
Of course it works this way because **SSHFS** has been doing it for years with FUSE mounts.

The problem is not the file access (which is handled correctly by the kernel), but the incorrect file information (which *rclone* provides).

**Comment by animosity22** [comment] 2022-10-14 13:20
Sorry I mistyped s/fuse/rclone/g.

https://github.com/rclone/rclone/issues/5604

https://github.com/rclone/rclone/issues/4742

**Comment by animosity22** [comment] 2022-10-14 13:20
It's a duplicate of many other items out there.

**Comment by animosity22** [comment] 2022-10-20 11:54
Closing as a duplicate.

**Closed by animosity22** 2022-10-20 11:54 UTC
Labels: duplicate
