### ISSUE TITLE
failing to copy large files to acd (Reset without error count inc)

### ISSUE THREAD

**Issue by ADeane6** [rclone/rclone#1255] opened 2017-03-19 22:33 UTC
Hey,
I'm getting a an issue where the upload is getting reset on large files 15gb+ it looks like a connection reset. Any setting I need to add to keep the connection open due to large file size?

rclone version: rclone v1.35

my os is freenas which is on FreeBSD 9.3-RELEASE-p25 amd64

I'm using Amazon Cloud Drive and trying to run the below
    
    rclone -v --transfers 1 --ignore-existing copy /mnt/all/UHD_Media/ acd:UHD_Media/ > & /var/log/rcloneUHD.log &

Logs

    2017/03/19 22:13:41
    Transferred:   51.265 GBytes (1.767 MBytes/s)
    Errors:                 0
    Checks:                21
    Transferred:            2
    Elapsed time:   8h15m1.4s
    Transferring:
     * ...erstellar (2014)/Interstellar(BR-Disk).mkv: 63% done, 893.665 kBytes/s, ETA: 3h55m23s

    2017/03/19 22:13:44 Movies/Interstellar (2014)/Interstellar(BR-Disk).mkv: Upload error detected but didn't finish upload: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: read tcp 10.56.12.0:18627->52.87.95.159:443: read: connection reset by peer ("HTTP status UNKNOWN")
    2017/03/19 22:13:44 pacer: Rate limited, sleeping for 476.771718ms (1 consecutive low level retries)
     2017/03/19 22:13:44 pacer: low level retry 1/1 (error Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: read tcp 10.56.12.0:18627->52.87.95.159:443: read: connection reset by peer)
    2017/03/19 22:13:44 Movies/Interstellar (2014)/Interstellar(BR-Disk).mkv: Received error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: read tcp 10.56.12.0:18627->52.87.95.159:443: read: connection reset by peer - low level retry 1/10
    2017/03/19 22:13:44 pacer: Resetting sleep to minimum 20ms on success
    2017/03/19 22:14:41
    Transferred:   51.331 GBytes (1.766 MBytes/s)
    Errors:                 0
    Checks:                21
    Transferred:            2
    Elapsed time:   8h16m1.4s
    Transferring:
     * ...erstellar (2014)/Interstellar(BR-Disk).mkv:  0% done, 1.060 MBytes/s, ETA: 8h54m23s

**Comment by mazeprince** [comment] 2017-03-21 13:22
First question, how big is the file? ACD has a file size limit of 50GB.
Second, did your internet connection dropped during the transfer? There could be several reasons for this: the router couldn't handle the transfer load, or your internet provider forced a reset of your connection and so on...

**Comment by ADeane6** [comment] 2017-03-21 21:51
@mazeprince The files are ~25gb max and I'm running pfsense router is able to handle the load and I've had no connection drops for weeks. no ip renew either so and connection didn't get reset so really not sure why this is happening. 

Aslo today I noticed some files were at 100% but timed out waitung for object to be found, any ideas why this happens as well

    Transferred:   332.631 GBytes (1.697 MBytes/s)
    Errors:                 0
    Checks:                26
    Transferred:           11
    Elapsed time:  55h46m1.4s
    Transferring:
     * ... (2012)/The Dark Knight Rises(BR-Disk).mkv: 100% done, 0 Bytes/s, ETA: 0s

    2017/03/21 21:44:41 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1153/1165)
    2017/03/21 21:44:46 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1154/1165)
    2017/03/21 21:44:52 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1155/1165)
    2017/03/21 21:44:57 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1156/1165)
    2017/03/21 21:45:02 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1157/1165)
    2017/03/21 21:45:07 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1158/1165)
    2017/03/21 21:45:12 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1159/1165)
    2017/03/21 21:45:17 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1160/1165)
    2017/03/21 21:45:22 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1161/1165)
    2017/03/21 21:45:27 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1162/1165)
    2017/03/21 21:45:33 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1163/1165)
    2017/03/21 21:45:38 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1164/1165)
    2017/03/21 21:45:41
    Transferred:   332.631 GBytes (1.696 MBytes/s)
    Errors:                 0
    Checks:                26
    Transferred:           11
    Elapsed time:  55h47m1.4s
    Transferring:
     * ... (2012)/The Dark Knight Rises(BR-Disk).mkv: 100% done, 0 Bytes/s, ETA: 0s

    2017/03/21 21:45:53 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Object not found - waiting (1165/1165)
    2017/03/21 21:45:58 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Giving up waiting for object - returning original error: HTTP code 504: "504 GATEWAY_TIMEOUT": no response body ("504 GATEWAY_TIMEOUT")
    2017/03/21 21:45:58 pacer: Rate limited, sleeping for 762.776516ms (1 consecutive low level retries)
    2017/03/21 21:45:58 pacer: low level retry 1/1 (error HTTP code 504: "504 GATEWAY_TIMEOUT": no response body)
    2017/03/21 21:45:58 Movies/Dark Knight Rises, The (2012)/The Dark Knight Rises(BR-Disk).mkv: Received error: HTTP code 504: "504 GATEWAY_TIMEOUT": no response body - low level retry 1/10
    2017/03/21 21:45:58 pacer: Resetting sleep to minimum 20ms on success
    2017/03/21 21:46:41
    Transferred:   332.720 GBytes (1.696 MBytes/s)
    Errors:                 0
    Checks:                26
    Transferred:           11
    Elapsed time:  55h48m1.4s
    Transferring:
     * ... (2012)/The Dark Knight Rises(BR-Disk).mkv:  0% done, 2.017 MBytes/s, ETA: 4h32m56s

**Comment by mazeprince** [comment] 2017-03-22 12:24
Unfortunately i have no other ideas for your initial problem.
As for your timed out 100% files: It looks like ACD has sometimes a lag with large uploaded files, thats why there is the --acd-upload-wait-per-gb option. Default is 3 min per GB and for me that was always more than enough, but maybe it helps in your case to adjust it. Although with default 3 min it rclone waits 60 minutes for a 20GB file... that should be more than enough in my opinion.
Sorry i cant really help you any further.

**Comment by ADeane6** [comment] 2017-03-22 13:40
@mazeprince Thanks for taht, think i might move to transfer 2 files at a time and extend the wait.

**Comment by ncw** [comment] 2017-03-22 14:56
> I'm getting a an issue where the upload is getting reset on large files 15gb+ it looks like a connection reset. Any setting I need to add to keep the connection open due to large file size?

Connection resets can be caused by Amazon, your ISP, your router or any bit of networking equipment.

Most likely suspect is your router, though pfsense is very reliable I hear.  Is there another box the pfsense router connects to?

Some ISPs have been known to kill long running TCP connections...

**Comment by diamondsw** [comment] 2017-03-30 17:29
`First question, how big is the file? ACD has a file size limit of 50GB.`
This has been discussed extensively in other threads, and yet rclone **still** will sit there and uselessly upload files well in excess of the limit. I sent ~700GB to Amazon (Two runs, three attempts each, of a 115GB file) before I finally found the bug reports in here - rclone gave no errors and spent a couple days on those useless transfers. I thought rclone was designed to throw an error if the file being uploaded was in excess of the 50GB limit?

**Comment by ADeane6** [comment] 2017-03-30 22:22
> The files are ~25gb max 
The largest file is actually 32gb on disk so well under the 50gb limit, I have about 1TB of large files so just gonna put them on a back drive instead of ACD

**Comment by ncw** [comment] 2017-03-31 12:51
@diamondsw BTW rclone writes this warning if it detects a too big file

    "Warning: file %q may fail because it is too big. Use --max-size=%dM to skip large files.

**Comment by ncw** [comment] 2020-01-14 14:13
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.

**Closed by ncw** 2020-01-14 14:13 UTC
