### ISSUE TITLE
--cache-db-path and --cache-chunk-path are using the default value of --cache-dir not the value of --cache-dir set on the command line when using vfs

### ISSUE THREAD

**Issue by kieranlee1970** [rclone/rclone#2604] opened 2018-09-25 02:38 UTC
Added a vfs flag to my rclone mount with cache and crypt and. instead of using the --cache-chunk-path I set. the cache-backend files are being stored in /tmp/rclone

From: https://forum.rclone.org/t/cach-chunk-path-ignored-when-vfs-set/6907

**Comment by ncw** [comment] 2018-09-25 14:18
I've managed to replicate this problem.

The problem is that `--cache-db-path` and `--cache-chunk-path` are using the default value of `--cache-dir` not the value of `--cache-dir` set on the command line.

This is due to the initialisation sequence of rclone... and the cache backend using the value of `fs.CacheDir` in an `init()` function when `--config-dir` hasn't been parsed yet.

This can be fixed by making the defaults "" and filling them up in `NewFs` - I think re-ordering the init sequence is probably too hard.

Though could set the default and see if it changed in `NewFs` which would mean the default would appear in the command line flags.

Also need to check use of `fs.CacheDir` in the other remotes.

**Comment by ivandeex** [comment] 2021-02-09 16:14
@kieranlee1970 Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment] 2021-03-12 14:40
I am going to close this stale ticket.
Also, the cache backend has been obsoleted and replaced by VFS in recent versions of rclone.

**Closed by ivandeex** 2021-03-12 14:40 UTC
Labels: Remote: Cache, bug, waiting for reply...
