### ISSUE TITLE
mega: Cannot connect if password contains cyrillic characters

### ISSUE THREAD

**Issue by PRESFIL** [rclone/rclone#5406] opened 2021-06-12 21:30 UTC
#### The associated forum post URL from `https://forum.rclone.org`

None.

#### What is the problem you are having with rclone?

It is not possible to establish a connection from accounts on mega.nz, the password of which contains Cyrillic characters. Megasync, Web client and other clients are working properly.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.56.0-beta.5550.3349b055f
- os/version: arch 21.0.6 (64 bit)
- os/kernel: 5.12.8-1-MANJARO (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.5
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

```
Manjaro Linux, 64 bit
```

#### Which cloud storage system are you using? (e.g. Google Drive)

```
Mega
```

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```sh
rclone mount -vv <account>:/ /tm/test/
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/06/13 00:13:41 DEBUG : rclone: Version "v1.56.0-beta.5550.3349b055f" starting with parameters ["rclone" "mount" "-vv" "Mega-presfil:/" "/tmp/test/"]
2021/06/13 00:13:41 DEBUG : Creating backend with remote "Mega-presfil:/"
2021/06/13 00:13:41 DEBUG : Using config file from "/home/presfil/.config/rclone/rclone.conf"
2021/06/13 00:13:43 Failed to create file system for "Mega-presfil:/": couldn't login: Object (typically, node or user) not found
```
### Notes

Similar issue:

- https://github.com/rclone/rclone/issues/4677

I repeated then `rclone lsf`. As a result, the error code [-9] printed out.

**Comment by animosity22** [comment] 2021-12-07 20:16
This would be a duplicate of the second item you've listed.

https://github.com/rclone/rclone/issues/4677

So closing this out to follow that.

**Closed by animosity22** 2021-12-07 20:16 UTC
Labels: question, Remote: Mega
