### ISSUE TITLE
FTP - Failed to copy: corrupted on transfer: sizes differ 3250436352 vs 0

### ISSUE THREAD

**Issue by alolis** [rclone/rclone#7330] opened 2023-09-22 06:58 UTC
#### The associated forum post URL from `https://forum.rclone.org`

There is none.

#### What is the problem you are having with rclone?

I am getting ` Failed to copy: corrupted on transfer: sizes differ 3250436352 vs 0` error (numbers can differ on each run) when I am trying to copy a file that has `[]` in the file name from my local disk to a box.com FTP backend.

If I remove the `[]` from the file name, it works.

I would also like to add here that Ι have tested with Filezilla FTP client and uploaded the file with `[]` in its name successfully so I assume something is going on with the rclone backend.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.64.0
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 4.4.249-1.el7.elrepo.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.1
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 22.04 x64

#### Which cloud storage system are you using? (e.g. Google Drive)

FTP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
./rclone copy [test].mkv target: -vvP --dump bodies --retries 1
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2023/09/19 10:49:50 DEBUG : rclone: Version "v1.64.0" starting with parameters ["rclone" "copy" "/example/[test].mkv" "target:" "-vvP" "--dump" "bodies" "--retries" "1"]
2023/09/19 10:49:50 DEBUG : Creating backend with remote "/example/[test].mkv"
2023/09/19 10:49:50 DEBUG : Using config file from "/Users/example/rclone.conf"
2023/09/19 10:49:50 DEBUG : fs cache: adding new entry for parent of "/example/[test].mkv", "/example"
2023/09/19 10:49:50 DEBUG : Creating backend with remote "target:"
2023/09/19 10:49:50 DEBUG : ftp://ftp.box.com:21: Connecting to FTP server
2023/09/19 10:49:50 DEBUG : ftp://ftp.box.com:21: dial("tcp","ftp.box.com:21")
2023/09/19 10:49:50 DEBUG : ftp://ftp.box.com:21: > dial: conn=*fshttp.timeoutConn, err=<nil>
2023/09/19 10:49:50 DEBUG : FTP Rx: "220 Service ready for new user."
2023/09/19 10:49:50 DEBUG : FTP Tx: "USER ********"
2023/09/19 10:49:50 DEBUG : FTP Rx: "331 User name okay, need password for *********"
2023/09/19 10:49:50 DEBUG : FTP Tx: PASS *****
2023/09/19 10:49:52 DEBUG : FTP Rx: "230 User logged in, proceed."
2023/09/19 10:49:52 DEBUG : FTP Tx: "FEAT"
2023/09/19 10:49:52 DEBUG : FTP Rx: "211-Extensions supported"
2023/09/19 10:49:52 DEBUG : FTP Rx: " SIZE"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MDTM"
2023/09/19 10:49:52 DEBUG : FTP Rx: " LANG en;zh-tw;ja;is"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MLST Size;Modify;Create;Type;Perm"
2023/09/19 10:49:52 DEBUG : FTP Rx: " AUTH SSL"
2023/09/19 10:49:52 DEBUG : FTP Rx: " AUTH TLS"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MODE Z"
2023/09/19 10:49:52 DEBUG : FTP Rx: " UTF8"
2023/09/19 10:49:52 DEBUG : FTP Rx: " TVFS"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MD5"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MMD5"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MFCT"
2023/09/19 10:49:52 DEBUG : FTP Rx: " MFMT"
2023/09/19 10:49:52 DEBUG : FTP Rx: "211 End"
2023/09/19 10:49:52 DEBUG : FTP Tx: "TYPE I"
2023/09/19 10:49:52 DEBUG : FTP Rx: "200 Command TYPE okay."
2023/09/19 10:49:52 DEBUG : FTP Tx: "OPTS UTF8 ON"
2023/09/19 10:49:52 DEBUG : FTP Rx: "200 Command OPTS okay."
2023-09-19 10:49:52 DEBUG : FTP Tx: "MLST [test].mkv"
2023-09-19 10:49:52 DEBUG : FTP Rx: "250-"
2023-09-19 10:49:52 DEBUG : FTP Rx: "Size=0;Modify=19700131000000.000;Create=19700131000000.000;Type=dir; /"
2023-09-19 10:49:52 DEBUG : FTP Rx: ""
2023-09-19 10:49:52 DEBUG : FTP Rx: "250 Requested file action okay, completed."
2023-09-19 10:49:52 DEBUG : [test].mkv: Need to transfer - File not found at Destination
2023-09-19 10:49:52 DEBUG : FTP Tx: "EPSV"
2023-09-19 10:49:52 DEBUG : FTP Rx: "229 Entering Passive Mode (|||****|)"
2023-09-19 10:49:52 DEBUG : ftp://ftp.box.com:21: dial("tcp","*.*.*.*:*")
2023-09-19 10:49:52 DEBUG : ftp://ftp.box.com:21: > dial: conn=*fshttp.timeoutConn, err=<nil>
2023-09-19 10:49:52 DEBUG : FTP Tx: "STOR [test].mkv.lotuwuv6.partial"
2023-09-19 10:49:53 DEBUG : FTP Rx: "150 File status okay; about to open data connection."
2023-09-19 10:57:02 DEBUG : FTP Rx: "226 Transfer complete."
2023-09-19 10:57:02 DEBUG : FTP Tx: "MFMT 20230916122101 [test].mkv.lotuwuv6.partial"
2023-09-19 10:57:02 DEBUG : FTP Rx: "213 ModifyTime=20230916122101; [test].mkv.lotuwuv6.partial"
2023-09-19 10:57:02 DEBUG : FTP Tx: "MLST [test].mkv.lotuwuv6.partial"
2023-09-19 10:57:02 DEBUG : FTP Rx: "250-"
2023-09-19 10:57:02 DEBUG : FTP Rx: "Size=0;Modify=19700131000000.000;Create=19700131000000.000;Type=dir; /"
2023-09-19 10:57:02 DEBUG : FTP Rx: ""
2023-09-19 10:57:02 DEBUG : FTP Rx: "250 Requested file action okay, completed."
2023-09-19 10:57:02 ERROR : [test].mkv.lotuwuv6.partial: corrupted on transfer: sizes differ 3250436352 vs 0
2023-09-19 10:57:02 INFO  : [test].mkv.lotuwuv6.partial: Removing failed copy
2023-09-19 10:57:02 DEBUG : FTP Tx: "MLST [test].mkv.lotuwuv6.partial"
2023-09-19 10:57:03 DEBUG : FTP Rx: "250-"
2023-09-19 10:57:03 DEBUG : FTP Rx: "Size=0;Modify=19700131000000.000;Create=19700131000000.000;Type=dir; /"
2023-09-19 10:57:03 DEBUG : FTP Rx: ""
2023-09-19 10:57:03 DEBUG : FTP Rx: "250 Requested file action okay, completed."
2023-09-19 10:57:03 DEBUG : FTP Tx: "RMD [test].mkv.lotuwuv6.partial"
2023-09-19 10:57:03 DEBUG : FTP Rx: "550 Not a valid directory \"[test].mkv.lotuwuv6.partial\"."
2023-09-19 10:57:03 DEBUG : FTP Tx: "NOOP"
2023-09-19 10:57:03 DEBUG : FTP Rx: "200 Command NOOP okay."
2023-09-19 10:57:03 INFO  : [test].mkv.lotuwuv6.partial: Failed to remove failed copy: directory not found
2023-09-19 10:57:03 ERROR : Attempt 1/1 failed with 1 errors and: corrupted on transfer: sizes differ 3250436352 vs 0
Transferred:           3.027 GiB / 3.027 GiB, 100%, 2.665 MiB/s, ETA 0s
Errors:                 1 (retrying may help)
Elapsed time:      7m13.1s
2023/09/19 10:57:03 INFO  : 
Transferred:           3.027 GiB / 3.027 GiB, 100%, 2.665 MiB/s, ETA 0s
Errors:                 1 (retrying may help)
Elapsed time:      7m13.1s

2023/09/19 10:57:03 DEBUG : 6 go routines active
2023/09/19 10:57:03 DEBUG : ftp://ftp.box.com:21: closing 1 unused connections
2023/09/19 10:57:03 DEBUG : FTP Tx: "QUIT"
2023/09/19 10:57:03 Failed to copy: corrupted on transfer: sizes differ 3250436352 vs 0
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment] 2023-09-22 16:19
After rclone does a transfer it likes to check it has arrived properly.

Here rclone attempts to find info about that single file

> 2023-09-19 10:57:02 DEBUG : FTP Tx: "MLST [test].mkv.lotuwuv6.partial"
> 2023-09-19 10:57:03 DEBUG : FTP Rx: "250-"
> 2023-09-19 10:57:03 DEBUG : FTP Rx: "Size=0;Modify=19700131000000.000;Create=19700131000000.000;Type=dir; /"
> 2023-09-19 10:57:03 DEBUG : FTP Rx: ""
> 2023-09-19 10:57:03 DEBUG : FTP Rx: "250 Requested file action okay, completed."

You can see the server returns `Size=0` so I'd say this is a bug in the server.

There are several workarounds you could take but probably the best one is to use this

    --ftp-encoding=Slash,Del,Ctl,RightSpace,Dot,SquareBracket

That will change those characters into unicode wide equivalents (this adds `SquareBracket` to the default set). The pureftpd server is like this - I wonder if that is what box is using.

**Comment by alolis** [comment] 2023-09-22 16:43
@ncw ,thanks for having a look. I am not sure which FTP server they are using but in general they do have a bad reputation for their FTP. 

I will have a look at the recommended workaround and get back to you.

**Comment by ncw** [comment] 2023-09-22 17:01
> Will it affect in some weird way the FTP servers that they do work just fine?

It will change how the file with `[]` is represented on the server. So if you have already uploaded files with `[]` on the other servers you probably don't want to set it there.

**Comment by alolis** [comment] 2023-09-26 07:40
@ncw , I played around with the `ftp-encoding` flag and it indeed it works but unfortunately it alters the file names which is not acceptable in my case. You mentioned other work arounds. Can you please share them so I can have a look?

In addition, I re-run tests with Filezilla and the full debug log enabled in order to try and understand why it works there. Here is the full log in case your eye catches something helpful:

```
Status:          Connection established, initializing TLS...
Trace:            tls_layer_impl::client_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            TLS Handshake successful
Trace:            Protocol: TLS1.2, Key exchange: ECDHE-SECP384R1-RSA-SHA384, Cipher: AES-256-GCM, MAC: AEAD, ALPN: 
Trace:            tls_layer_impl::verify_certificate()
Trace:            System trust store decision: true
Trace:            Sending certificate_verification_event
Trace:            CFtpControlSocket::SetAsyncRequestReply
Trace:            set_verification_result(true)
Status:          TLS connection established, waiting for welcome message...
Trace:            CFtpControlSocket::OnReceive()
Response:     220 Service ready for new user.
Trace:            CFtpLogonOpData::ParseResponse() in state 1
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 5
Trace:            CFtpLogonOpData::Send() in state 6
Command:     USER *****************
Trace:            CFtpControlSocket::OnReceive()
Response:     331 User name okay, need password for *************
Trace:            CFtpLogonOpData::ParseResponse() in state 6
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 6
Command:     PASS *********
Trace:            CFtpControlSocket::OnReceive()
Response:     230 User logged in, proceed.
Trace:            CFtpLogonOpData::ParseResponse() in state 6
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 10
Command:     OPTS UTF8 ON
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command OPTS okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 10
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 11
Command:     PBSZ 0
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command PBSZ okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 11
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 12
Command:     PROT P
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command PROT okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 12
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 13
Command:     OPTS MLST size;modify;type;
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command OPTS okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 13
Status:          Logged in
Trace:            Measured latency of 457 ms
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpLogonOpData::Reset(0) in state 15
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpListOpData::Send() in state 0
Status:          Retrieving directory listing...
Trace:            CFtpChangeDirOpData::Send() in state 0
Trace:            CFtpChangeDirOpData::Send() in state 1
Command:     PWD
Trace:            CFtpControlSocket::OnReceive()
Response:     257 "/" is current directory.
Trace:            CFtpChangeDirOpData::ParseResponse() in state 1
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpChangeDirOpData::Reset(0) in state 1
Trace:            CFtpListOpData::SubcommandResult(0) in state 1
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpListOpData::Send() in state 2
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpListOpData::Reset(0) in state 2
Status:          Directory listing of "/" successful
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 0
Status:          Resolving address of ftp.box.com
Status:          Connecting to *.*.*.*:*...
Status:          Connection established, initializing TLS...
Trace:            tls_layer_impl::client_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            TLS Handshake successful
Trace:            Protocol: TLS1.2, Key exchange: ECDHE-SECP384R1-RSA-SHA384, Cipher: AES-256-GCM, MAC: AEAD, ALPN: 
Trace:            tls_layer_impl::verify_certificate()
Trace:            System trust store decision: true
Trace:            Sending certificate_verification_event
Trace:            CFtpControlSocket::SetAsyncRequestReply
Trace:            set_verification_result(true)
Status:          TLS connection established, waiting for welcome message...
Trace:            CFtpControlSocket::OnReceive()
Response:     220 Service ready for new user.
Trace:            CFtpLogonOpData::ParseResponse() in state 1
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 5
Trace:            CFtpLogonOpData::Send() in state 6
Command:     USER *********************
Trace:            CFtpControlSocket::OnReceive()
Response:     331 User name okay, need password for *********************.
Trace:            CFtpLogonOpData::ParseResponse() in state 6
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 6
Command:     PASS *********
Trace:            CFtpControlSocket::OnReceive()
Response:     230 User logged in, proceed.
Trace:            CFtpLogonOpData::ParseResponse() in state 6
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 10
Command:     OPTS UTF8 ON
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command OPTS okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 10
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 11
Command:     PBSZ 0
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command PBSZ okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 11
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 12
Command:     PROT P
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command PROT okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 12
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpLogonOpData::Send() in state 13
Command:     OPTS MLST size;modify;type;
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command OPTS okay.
Trace:            CFtpLogonOpData::ParseResponse() in state 13
Status:          Logged in
Trace:            Measured latency of 260 ms
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpLogonOpData::Reset(0) in state 15
Trace:            CFtpControlSocket::FileTransfer()
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpFileTransferOpData::Send() in state 0
Status:          Starting upload of /example/[test].mkv
Trace:            CFtpChangeDirOpData::Send() in state 0
Trace:            CFtpChangeDirOpData::Send() in state 2
Command:     CWD /
Trace:            CFtpControlSocket::OnReceive()
Response:     250 Directory changed to /
Trace:            CFtpChangeDirOpData::ParseResponse() in state 2
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpChangeDirOpData::Send() in state 3
Command:     PWD
Trace:            CFtpControlSocket::OnReceive()
Response:     257 "/" is current directory.
Trace:            CFtpChangeDirOpData::ParseResponse() in state 3
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpChangeDirOpData::Reset(0) in state 3
Trace:            CFtpFileTransferOpData::SubcommandResult(0) in state 1
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpFileTransferOpData::Send() in state 5
Trace:            CFtpRawTransferOpData::Send() in state 0
Trace:            CFtpRawTransferOpData::Send() in state 1
Command:     TYPE I
Trace:            CFtpControlSocket::OnReceive()
Response:     200 Command TYPE okay.
Trace:            CFtpRawTransferOpData::ParseResponse() in state 1
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpRawTransferOpData::Send() in state 2
Command:     PASV
Trace:            CFtpControlSocket::OnReceive()
Response:     227 Entering Passive Mode (*,*,*,*,*)
Trace:            CFtpRawTransferOpData::ParseResponse() in state 2
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpRawTransferOpData::Send() in state 4
Trace:            Binding data connection source IP to control connection source IP *.*.*.*
Trace:            tls_layer_impl::client_handshake()
Trace:            Trying to resume existing TLS session.
Command:     STOR [test].mkv
Trace:            tls_layer_impl::continue_handshake()
Trace:            CFtpControlSocket::OnReceive()
Response:     150 File status okay; about to open data connection.
Trace:            CFtpRawTransferOpData::ParseResponse() in state 4
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpRawTransferOpData::Send() in state 5
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            TLS Handshake successful
Trace:            Protocol: TLS1.2, Key exchange: ECDHE-SECP384R1-RSA-SHA384, Cipher: AES-256-GCM, MAC: AEAD, ALPN: 
Trace:            tls_layer_impl::verify_certificate()
Trace:            set_verification_result(true)
Trace:            CTransferSocket::OnConnect
Trace:            tls_layer_impl::shutdown()
Trace:            Postponing shutdown, send_buffer_ not empty
Trace:            tls_layer_impl::continue_shutdown()
Trace:            tls_layer_impl::shutdown()
Trace:            CTransferSocket::TransferEnd(1)
Trace:            tls_layer_impl::shutdown()
Trace:            CFtpControlSocket::TransferEnd()
Trace:            CFtpControlSocket::OnReceive()
Response:     226 Transfer complete.
Trace:            CFtpRawTransferOpData::ParseResponse() in state 7
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpRawTransferOpData::Reset(0) in state 7
Trace:            CFtpFileTransferOpData::SubcommandResult(0) in state 7
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpFileTransferOpData::Reset(0) in state 7
Status:          File transfer successful, transferred 10485760 bytes in 12 seconds
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpListOpData::Send() in state 0
Status:          Retrieving directory listing of "/"...
Trace:            CFtpChangeDirOpData::Send() in state 0
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpChangeDirOpData::Reset(0) in state 0
Trace:            CFtpListOpData::SubcommandResult(0) in state 1
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpListOpData::Send() in state 2
Trace:            CFtpRawTransferOpData::Send() in state 0
Trace:            CFtpRawTransferOpData::Send() in state 2
Command:     PASV
Trace:            CFtpControlSocket::OnReceive()
Response:     227 Entering Passive Mode (*,*,*,*,*)
Trace:            CFtpRawTransferOpData::ParseResponse() in state 2
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpRawTransferOpData::Send() in state 4
Trace:            Binding data connection source IP to control connection source IP *.*.*.*.*
Trace:            tls_layer_impl::client_handshake()
Trace:            Trying to resume existing TLS session.
Command:     MLSD
Trace:            tls_layer_impl::continue_handshake()
Trace:            CFtpControlSocket::OnReceive()
Response:     150 File status okay; about to open data connection.
Trace:            CFtpRawTransferOpData::ParseResponse() in state 4
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpRawTransferOpData::Send() in state 5
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            tls_layer_impl::continue_handshake()
Trace:            TLS Handshake successful
Trace:            Protocol: TLS1.2, Key exchange: ECDHE-SECP384R1-RSA-SHA384, Cipher: AES-256-GCM, MAC: AEAD, ALPN: 
Trace:            tls_layer_impl::verify_certificate()
Trace:            set_verification_result(true)
Trace:            CTransferSocket::OnConnect
Trace:            CFtpControlSocket::OnReceive()
Response:     226 Closing data connection.
Trace:            CFtpRawTransferOpData::ParseResponse() in state 5
Trace:            CControlSocket::SendNextCommand()
Trace:            CFtpRawTransferOpData::Send() in state 8
Trace:            CTransferSocket::TransferEnd(1)
Trace:            tls_layer_impl::shutdown()
Trace:            tls_layer_impl::continue_shutdown()
Trace:            CFtpControlSocket::TransferEnd()
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpRawTransferOpData::Reset(0) in state 8
Trace:            CFtpListOpData::SubcommandResult(0) in state 3
Trace:            CFtpControlSocket::ResetOperation(0)
Trace:            CControlSocket::ResetOperation(0)
Trace:            CFtpListOpData::Reset(0) in state 3
Status:          Directory listing of "/" successful
```

Thank you for your time.

**Comment by ncw** [comment] 2023-09-27 17:11
> 2023-09-19 10:57:02 DEBUG : FTP Tx: "MLST [test].mkv.lotuwuv6.partial"

As far as I am aware this is a bug in the server. The problem is that it is interpreting the `[` and `]` as wildcards which it shouldn't be doing with `MLST`.

I know that pureftpd has this bug so I suspect your FTP server is based on that.

I created a bug report at https://github.com/jedisct1/pure-ftpd but the author decided to remove the ability to submit bugs! See https://github.com/rclone/rclone/issues/1438 for more info!

However if you use `--ignore-size` it should work around the problem in a not completely satisfactory way. I'd use filters to upload the files without `[]` without `--ignore-size` then upload the files with `[]` with `--ignore-size`.

**Comment by alolis** [comment] 2023-09-29 05:55
@ncw , thank you for all the info. I will play around with `--ignore-size` and decide about the workaround that I will use.

I am still curious though why Filezilla works somehow. Perhaps they ignore the size internally for this case as you are also recommending.

**Comment by ncw** [comment] 2023-10-03 19:57
> I am still curious though why Filezilla works somehow. Perhaps they ignore the size internally for this case as you are also recommending.

Rclone manages to upload the file fine, it is just checking it is uploaded properly that is the problem. I expect Filezilla doesn't bother checking, or checks in a different way.

**Comment by alolis** [comment] 2023-10-04 08:26
@ncw ,I tried the `--ignore-size` flag and now I get a different error:

```
2023-10-04 10:25:28 INFO  : [10MB].file.pogiyol1.partial: Failed to remove failed copy: directory not found
2023-10-04 10:25:28 ERROR : Attempt 1/1 failed with 1 errors and: Move Rename failed: 553 Can't rename file.
Transferred:              10 MiB / 10 MiB, 100%, 421.047 KiB/s, ETA 0s
Errors:                 1 (retrying may help)
Elapsed time:        29.2s
2023/10/04 10:25:28 INFO  : 
Transferred:              10 MiB / 10 MiB, 100%, 421.047 KiB/s, ETA 0s
Errors:                 1 (retrying may help)
Elapsed time:        29.2s

2023/10/04 10:25:28 DEBUG : 7 go routines active
2023/10/04 10:25:28 DEBUG : ftp://ftp.box.com:21: closing 1 unused connections
2023/10/04 10:25:28 DEBUG : FTP Tx: "QUIT"
2023/10/04 10:25:28 Failed to copy: Move Rename failed: 553 Can't rename file.
```

If I remove the `--ignore-size` flag then I am back to the original problem. 

Thanks for your input so far, I appreciate it.

**Comment by ncw** [comment] 2023-10-04 14:22
Ach, that is the new partial code...

You'll have to add `--disable PartialUploads` too I think.

**Comment by alolis** [comment] 2023-10-05 07:47
{{--ignore-size} in combination with {{--disable PartialUploads} did the trick!

Thanks for all the help @ncw . You can close this ticket if you want.

**Comment by ncw** [comment] 2023-10-05 09:28
Glad you got it working. I will close this now as I don't think it is an rclone bug, but it will be here for others to find in the future.

**Closed by ncw** 2023-10-05 09:28 UTC
