### ISSUE TITLE
1.60.1 of rclone purge does not work on google drive or onedrive.

### ISSUE THREAD

**Issue by iesv** [rclone/rclone#6587] opened 2022-11-28 00:10 UTC
#### What is the problem you are having with rclone?

rclone purge does not work on google drive or onedrive.

#### What is your rclone version (output from `rclone version`)

1.60.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

win10x64

#### Which cloud storage system are you using? (e.g. Google Drive)

google drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone purge remote:/

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment] 2022-11-28 06:42
In the specified command you have no path, so are you trying to delete everything within the remote? I don't know if that is supposed to work or not, will have to check that. But, did your case used to work before (previous versions of rclone? And can you include a log from a run with `-vv` , please.

**Comment by iesv** [comment] 2022-11-28 07:02
Yes, I want to delete everything.

E:\>rclone purge iesv:/ -vv
2022/11/28 15:01:55 DEBUG : rclone: Version "v1.60.1" starting with parameters ["rclone" "purge" "iesv:/" "-vv"]
2022/11/28 15:01:55 DEBUG : Creating backend with remote "iesv:/"
2022/11/28 15:01:55 DEBUG : Using config file from "C:\\Users\\Administrator\\AppData\\Roaming\\rclone\\rclone.conf"
2022/11/28 15:01:56 DEBUG : fs cache: renaming cache item "iesv:/" to be canonical "iesv:"
2022/11/28 15:01:56 ERROR : Attempt 1/3 failed with 1 errors and: can't purge root directory
2022/11/28 15:01:56 ERROR : Attempt 2/3 failed with 1 errors and: can't purge root directory
2022/11/28 15:01:56 ERROR : Attempt 3/3 failed with 1 errors and: can't purge root directory
2022/11/28 15:01:56 DEBUG : 3 go routines active
2022/11/28 15:01:56 Failed to purge: can't purge root directory

**Comment by albertony** [comment] 2022-11-28 07:28
Yes, exactly, that log message says it all.

Maybe `rclone delete remote: --rmdirs` does what you want?

**Comment by iesv** [comment] 2022-11-28 08:08
Currently, the only two commands available for clearing all files are
"rclone delete remote:/" and "rclone rmdirs remote:/"
"rclone purge" doesn't work.

**Comment by albertony** [comment] 2022-11-28 08:10
Sure, but that is by design. Did you not achieve what you wanted with the other commands?

**Comment by iesv** [comment] 2022-11-28 08:17
So, as for "rclone purge", what does it do?

**Comment by albertony** [comment] 2022-11-28 08:26
Purge removes the path you point it to.

> Remove the path and all of its contents

While delete removes the *content* of the path you point it to:

> Remove the files in path.

The root of a remote is special, it need to exist (in general), and therefore purge on the root is forbidden. The other commands works in your case because they operate on the content within the remote.

If you wanted to delete a directory called "mydir" you could use purge, like this:

`rclone delete remote:mydir`

**Comment by iesv** [comment] 2022-11-28 08:45
Thank you very much! Now I see.

**Comment by albertony** [comment] 2022-11-28 08:58
Great. I think we can close this issue then(?).
Just a friendly tip: If you have any more questions like this, you will often get quicker help if you ask in the forum. It's a great place to get help and discuss *possible* bugs and solutions.

**Closed by albertony** 2022-11-28 08:58 UTC
Labels: question

**Comment by iesv** [comment] 2022-11-28 09:32
Okay. Thanks again for your patient reply!
