### ISSUE TITLE
rclone can not copy object from s3 to s3  and the key is ". " or ".."?

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4704] opened 2020-10-23 09:46 UTC
#### What is the problem you are having with rclone?
can not copy the object with "." from s3 to s3?

#### What is your rclone version (output from `rclone version`)
v1.51.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
centos 

####  Which cloud storage system are you using? (eg Google Drive)
s3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy  s3:/src s3:/target

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

for example:
![image](https://user-images.githubusercontent.com/13997135/96988967-a2a51d00-1557-11eb-9702-4159477f3918.png)

**Comment by zhucan** [comment] 2020-10-23 09:50
@ncw

**Comment by darthShadow** [comment] 2020-10-23 10:40
Can you please try with the latest version and report back?

**Comment by zhucan** [comment] 2020-10-23 10:42
> Can you please try with the latest version and report back?

ok, I will try it with latest version.

**Comment by zhucan** [comment] 2020-10-26 02:09
@darthShadow  Please take a look.
![image](https://user-images.githubusercontent.com/13997135/97126964-43235900-1773-11eb-9386-012b57197d2b.png)
 
The rclone version is v1.15.4

**Comment by darthShadow** [comment] 2020-10-26 05:06
Can you also show your config file?

**Comment by zhucan** [comment] 2020-10-26 07:03
> Can you also show your config file?
as follows：
![image](https://user-images.githubusercontent.com/13997135/97142817-5c8ccb00-179c-11eb-83bb-7f24306174f6.png)

**Comment by ncw** [comment] 2020-10-26 15:15
Am I right in thinking you have an object called `.` - is that correct?

This is run as part of the integration tests so is known to work with the S3 providers in the integration tests

However I think you must be using a non-AWS s3 - is that correct?

Which S3 provider are you using?

**Comment by zhucan** [comment] 2020-10-26 16:31
Yes, we have an object called “.”，our s3 provider is ceph rgw，we can use aws s3api to put an object that the name is “.” to the bucket.发自我的iPhone------------------ Original ------------------From: Nick Craig-Wood  <notifications@github.com>Date: Mon,Oct 26,2020 11:16 PMTo: rclone/rclone <rclone@noreply.github.com>Cc: Louis Koo <zhucan.k8s@gmail.com>, Author <author@noreply.github.com>Subject: Re: [rclone/rclone] rclone can not copy object from s3 to s3  and thekey is ". " or ".."? (#4704)
Am I right in thinking you have an object called . - is that correct?
This is run as part of the integration tests so is known to work with the S3 providers in the integration tests
However I think you must be using a non-AWS s3 - is that correct?
Which S3 provider are you using?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rclone/rclone/issues/4704#issuecomment-716614983",
"url": "https://github.com/rclone/rclone/issues/4704#issuecomment-716614983",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ncw** [comment] 2020-10-27 17:44
OK I've done a bit more experimenting and I think this is a bug.

The integration tests were testing the wrong thing because the encoding was incorrect for the s3 backend.

I've attempted to fix the problems with that, however I still can't upload a file called ".."

Note that if you list a file called "." it will appear with its unicode equivalent "．" as "." isn't a valid file name. You'll need to use that unicode equivalent in the command line if you want to access a file called ".".

Have a go with this and see if it fixes your problems

[v1.54.0-beta.4852.b26d5da84.fix-4704-s3-dot](https://beta.rclone.org/branch/fix-4704-s3-dot/v1.54.0-beta.4852.b26d5da84.fix-4704-s3-dot/) on branch [fix-4704-s3-dot](https://github.com/rclone/rclone/tree/fix-4704-s3-dot) (uploaded in 15-30 mins)

**Comment by zhucan** [comment] 2020-10-28 05:58
@ncw Thanks, I will try it, why not can upload a file called ".."?

**Comment by zhucan** [comment] 2020-10-28 06:33
@ncw I had tested with "." and "..",  it can be uploaded to the bucket. Thanks

- object name is "."

![Uploading image.png…]()

- object name is ".."
![Uploading image.png…]()

**Comment by ncw** [comment] 2020-10-28 12:03
Thanks for testing.

Can you try uploading a file called `..` in a directory called `..` - that is where the integration tests are failing.

**Comment by zhucan** [comment] 2020-10-29 02:06
ok, I will try it later.

**Comment by zhucan** [comment] 2020-10-29 02:54
like this:
![image](https://user-images.githubusercontent.com/13997135/97519879-fa6ada80-19d4-11eb-8d10-eb6c86dd9ac6.png)

I had tested, it's ok. @ncw

**Comment by ivandeex** [comment] 2020-11-26 21:29
Fixed on branch https://github.com/rclone/rclone/commits/fix-4704-s3-dot as confirmed by user. Pending merge and integration test.

**Comment by ncw** [comment] 2020-11-27 11:04
The integration test fails for this, so that needs fixing.

I'm concerned that this could break existing workflows so maybe needs a flag?

**Comment by ivandeex** [comment] 2020-11-27 12:47
> we can use aws s3api to put an object that the name is “.” to the bucket

So s3api is a known workaround for organizations willing to name their files "." or ".." or "//".

**Comment by zhucan** [comment] 2021-02-07 06:28
@ivandeex how to deal the special key with "//" ?

**Comment by ivandeex** [comment] 2021-02-26 04:12
rclone handles `//` in paths using standard golang library in numerous places around the codebase. worse, it's handled by packages rclone depends on. so for `//` the status is `WON'T FIX`.
your requirements are really exotic, so your team needs will need exotic software to satisfy your customer.

**Comment by ivandeex** [comment] 2021-02-26 04:18
probably i can allocate some time later to try `.`,`..` combinations with https://github.com/rclone/rclone/commits/fix-4704-s3-dot against _ceph rados_, for example https://github.com/bobrik/docker-radosgw and maybe come up with a pull. task priority low. no eta.

**Closed** 2021-07-27 01:20 UTC
Labels: Remote: S3, encoding, enhancement
